### ISSUE TITLE
Docker: Documentation incomplete? What is "realm" where is the default config file?

### ISSUE THREAD

**Issue by KeenMaron** [coturn/coturn#1013]
Hi,

i just tried coturn with docker:

```
docker run -d --network=host \
           -v $(pwd)/my.conf:/etc/coturn/turnserver.conf \
       coturn/coturn \
	   -n --log-file=stdout \
	   --external-ip='$(detect-external-ip)' \
	   --relay-ip='$(detect-external-ip)'
```

I tried to open "turnserver.conf" but it says it is a folder?
How to access the default config file? Should i have to create it by myself? Is there any default config file?

What is the meaning of every option? (lt-cred-mech, no-multicast-peers, no-tlsv1, realm?) And how should i configure it?

```
docker run -d --network=host coturn/coturn \
           -n --log-file=stdout \
           --min-port=49160 --max-port=49200 \
           --lt-cred-mech --fingerprint \
           --no-multicast-peers --no-cli \
           --no-tlsv1 --no-tlsv1_1 \
           --realm=my.realm.org \  
```

**Comment by tyranron** [comment]
@KeenMaron 

> I tried to open "turnserver.conf" but it says it is a folder?
> How to access the default config file? Should i have to create it by myself? Is there any default config file?

See the [Docker bind mounts documentation](https://docs.docker.com/storage/bind-mounts/) to understand how it works.

Regarding the default config, you don't have to specify it all (you may fully omit bind mount). You should specify it only if you want to configure Coturn via a file.

> What is the meaning of every option? (lt-cred-mech, no-multicast-peers, no-tlsv1, realm?) And how should i configure it?

See the [Wiki page describing `turnserver` options](https://github.com/coturn/coturn/wiki/turnserver).

**Comment by KeenMaron** [comment]
Ok thank you! I have overseen the links in the docker installation guide or they are missing.

**Comment by eakraly** [comment]
Hi @KeenMaron !
> Is it possible to set a coturn server with only 10 ports?

Yes. 
But your suspicion is correct - the port range is about the system configuration rather than "count" of ports or amount of traffic.
min-port/max-port should cover the ephemeral range that your underlying system allows to use to prevent a scenario where turnserver allocates port nnnnn but it is not in the range and turn session setup fails

**Comment by KeenMaron** [comment]
Ok thanks for the reply. Still a bit confusing. So the worst case scenario is, that my calls could fail more often, because of a small range of open ports?
