### ISSUE TITLE
max-port ignored in config file

### ISSUE THREAD

**Issue by 3x3cut0r** [coturn/coturn#1014]
I setup min-port=49160 and max-port=49200
in my turnserver.con but if i check a connection with turnutils_uclient it seems like this parameter is ignored because the port-range is still between 49152 an 65535.
because i run coturn on a docker-rootless instance i cannot open the whole range of ports because i cannot set network=host.
using the whole range of ports would freeze my instance. (see https://github.com/instrumentisto/coturn-docker-image/issues/3)

am i missing something here?

**Comment by ggarber** [comment]
I just tested it and it filters the ports properly in my case.  I used the latest version (4.6.0) and these command line arguments:
```
../bin/turnserver --use-auth-secret  --static-auth-secret=secret --realm=north.gov --allow-loopback-peers --min-port 49160 --max-port 49180
```
All the relay addresses were using ports in that range and as soon as tried try to connect to many users I get an error of "no available ports".

Can you share how you tested the ports?  Are you sure those are local ports and not remote ports?

Also if you can share the "docker run" command to reproduce it I could try locally.
