### ISSUE TITLE
docker image coturn/coturn:debian is logging mysql db password on startup

### ISSUE THREAD

**Issue by godfuture** [coturn/coturn#1017]
Hi,
I think it is not a good idea to log the full password of db connection. Please remove following log or change it such that the password is not fully shown:
`0: : MySQL DB connection success: host=mariadb dbname=coturn user=coturn password=***** port=3306 connect_timeout=60 read_timeout=60`

**Comment by tyranron** [comment]
@godfuture as far as I see, the `password` is masked and doesn't reveal its actual value. What is the security concern with that?

**Comment by eakraly** [comment]
@tyranron I think what we have above is an example - it is @godfuture who masked the password
In his log it appears as cleartext

**Comment by godfuture** [comment]
sorry, stupid me. For sure I have removed my password. It was cleartext. I should have replaced it with "123456" or similar to make it obvious.
