### ISSUE TITLE
The openssl precompiling conditions of the mainrelay.c THREAD_setup function are inconsistent

### ISSUE THREAD

**Issue by xiongyue23** [coturn/coturn#1019]
THREAD_setup's CRYPTO_THREADID_set_callback Inconsistent precompiled conditions

#if **OPENSSL_VERSION_NUMBER >= 0x10000000L**
void coturn_id_function(CRYPTO_THREADID *ctid);
void coturn_id_function(CRYPTO_THREADID *ctid)
{
	UNUSED_ARG(ctid);
    CRYPTO_THREADID_set_numeric(ctid, (unsigned long)pthread_self());
}
#else
unsigned long coturn_id_function(void);
unsigned long coturn_id_function(void)
{
    return (unsigned long)pthread_self();
}
#endif

#if **OPENSSL_VERSION_NUMBER >= 0x10000000L && OPENSSL_VERSION_NUMBER <= OPENSSL_VERSION_1_1_1**
	CRYPTO_THREADID_set_callback(coturn_id_function);
#else
	CRYPTO_set_id_callback(coturn_id_function);
#endif

**Comment by eakraly** [comment]
Thank you @xiongyue23 
I think #1012 is exactly about this issue

**Comment by xiongyue23** [comment]
Thank you.

**Comment by xiongyue23** [comment]
Hello, I want to ask，Does version 4.5.2 need to fix this problem？Otherwise, my local compilation will alarm, and there will be problems in running。thank you   @eakraly

**Comment by eakraly** [comment]
@xiongyue23 I hope we finally figure out all deprecated openssl APIs and warnings by 4.7.0
