### ISSUE TITLE
The mobility feature does not work with lt-cred-mech

### ISSUE THREAD

**Issue by richiemann** [coturn/coturn#103]
I am trying to implement the mobility feature on a TURN client (based on pjsips pjnath 2.6).

On the current master git version the feature works well on  sessions using the no-auth authentication method. The refresh request with the mobility token is sent and the sessions is refreshed as expected. The session continues uninterrupted on the new connection.
[mobility-no-auth.pcapng.zip](https://github.com/coturn/coturn/files/801943/mobility-no-auth.pcapng.zip)

However, if the server has the  lt-cred-mech set, the refresh request is met with a 401 response, but the subsequent refresh request (with all authentication parameters set appropriately) is also met with a 401. The sessions can not be moved to the new TURN connection.
[mobility-lt-cred-mech.pcapng.zip](https://github.com/coturn/coturn/files/801945/mobility-lt-cred-mech.pcapng.zip)

The test runs on TURN over TCP. Mid connection the client is moved from one network to another. Wireshark traces attached for both tests.

Are there any variations on the mobility TURN message flows using lt-cred-mech?

Best regards,

Ricardo

**Comment by mom040267** [comment]
Check and run the test scripts for mobility (in project directory
examples/scripts/mobile/) . They work with long-term mechanism. You can
compare their network dump with your network dumps and see what is
different.

Oleg

**Comment by richiemann** [comment]
Thanks, those scripts did the trick. My refresh request was malformed.
