### ISSUE TITLE
Coturn turnserver.conf not found, Cannot bind TLS/TCP listener socket to addr

### ISSUE THREAD

**Issue by mmmill29** [coturn/coturn#1035]
Hi, I am a student trying to create a coturn server using an AWS Ec2 instance of Ubuntu. I have tried configuring the server myself and cannot resolve these issues, if anyone can weigh in/speculate on the .conf file and console output:

Here are the security group rules: 

-- TLS 32355 - 65535, 3478-3479 : 0.0.0.0/0 (all)
-- UDP 32355 - 65535, 3478-3479 : 0.0.0.0/0 (all)

Here is the output: 

``` 0: : Config file found: /etc/turnserver.conf
ERROR: Cannot open log file for writing: /var/log/coturn/coturn_2022-10-22.log
0: : log file opened: /var/log/turn_47167_2022-10-22.log
0: : Relay address to use: 172.XX.XX.XXX
0: : Whitelisting external-ip private part: 172.XX.XX.XXX
0: : Config file found: /etc/turnserver.conf
0: : 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.2 'dan Eider'
0: : 
Max number of open files/sockets allowed for this process: 1048576
0: : 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
0: : 

==== Show him the instruments, Practical Frost: ====

0: : TLS supported
0: : DTLS supported
0: : DTLS 1.2 supported
0: : TURN/STUN ALPN supported
0: : Third-party authorization (oAuth) supported
0: : GCM (AEAD) supported
0: : OpenSSL compile-time version: OpenSSL 3.0.2 15 Mar 2022 (0x30000020)
0: : 
0: : SQLite supported, default database location is /var/lib/turn/turndb
0: : Redis supported
0: : PostgreSQL supported
0: : MySQL supported
0: : MongoDB is not supported
0: : 
0: : Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: : Domain name: 
0: : Default realm: 
0: : ERROR: 
CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
0: : WARNING: cannot find certificate file: turn_server_cert.pem (1)
0: : WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
0: : WARNING: cannot find private key file: turn_server_pkey.pem (1)
0: : WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
0: : NO EXPLICIT LISTENER ADDRESS(ES) ARE CONFIGURED
0: : ===========Discovering listener addresses: =========
0: : Listener address to use: 127.0.0.1
0: : Listener address to use: 172.XX.XX.XXX                          #(EC2 instance)
0: : Listener address to use: ::1
0: : =====================================================
0: : Total: 1 'real' addresses discovered
0: : =====================================================
0: : pid file created: /var/run/turnserver.pid
0: : IO method (main listener thread): epoll (with changelist)
0: : Wait for relay ports initialization...
0: :   relay 172.XX.XX.XXX initialization... //(EC2 Instance)
0: :   relay 172.XX.XX.XXX initialization done //(EC2 Instance) 
0: : Relay ports initialization done
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=1 created
bind: Address already in use
0: : Trying to bind fd 12 to <127.0.0.1:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: : Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478
0: : Trying to bind TLS/TCP listener socket to addr 127.0.0.1:3478, again...
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=0 created
0: : IPv4. UDP listener opened on: 127.0.0.1:3478
0: : IPv4. UDP listener opened on: 127.0.0.1:3479
0: : IPv4. UDP listener opened on: 172.XX.XX.XXX:3478     //(EC2 instance)
0: : IPv4. UDP listener opened on: 172.XX.XX.XXX:3479     //(EC2 instance)
0: : IPv6. UDP listener opened on: ::1:3478
0: : IPv6. UDP listener opened on: ::1:3479
0: : Total General servers: 2
bind: Address already in use
0: : Trying to bind fd 29 to <127.0.0.1:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: : Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478
0: : Trying to bind TLS/TCP listener socket to addr 127.0.0.1:3478, again...
0: : IO method (admin thread): epoll (with changelist)
0: : IO method (auth thread): epoll (with changelist)
0: : IO method (auth thread): epoll (with changelist)
0: : SQLite DB connection success: /var/lib/turn/turndb
bind: Address already in use
0: : Trying to bind fd 12 to <127.0.0.1:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: : Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478
0: : Trying to bind TLS/TCP listener socket to addr 127.0.0.1:3478, again...
bind: Address already in use
0: : Trying to bind fd 29 to <127.0.0.1:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: : Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478
0: : Trying to bind TLS/TCP listener socket to addr 127.0.0.1:3478, again...
bind: Address already in use
0: : Trying to bind fd 12 to <127.0.0.1:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: : Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478
0: : Trying to bind TLS/TCP listener socket to addr 127.0.0.1:3478, again...
bind: Address already in use
```

Here is the turnserver.conf (Which is inside of /etc/ as I've repeatedly edited it). I would love any advice on how to ensure the proper configuration is being read in and we are able to move forward with our project.

``` Coturn TURN SERVER configuration file

listening-port=3478

tls-listening-port=5349

listening-ip=172.XX.XX.XXX //(EC2 instance)
                                     
relay-ip=172.XX.XX.XXX //(Same EC2 instance) 

external-ip=3.19.73.XXX/172.31.44.XXX [Public Ec2 over private ec2 IP]

min-port=3478
max-port=65535

verbose

fingerprint
/#temporary settings 
no-auth


user=xxxxxxxxx:XXXXXXXXXXXXXXXXXXXXX

realm=ec2-x-xx-xx-xxx.us-east-2.compute.amazonaws.com 

log-file=/var/log/coturn/coturn.log

#pidfile="/var/run/turnserver.pid"


cli-ip=127.0.0.1
# CLI server port. Default is 5766.
cli-port=5766

#
cli-password=user=0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


```

I have been troubleshooting for over a week and cannot figure out where I am going wrong if someone with more experience could weigh in, I would greatly appreciate it!

**Comment by mmmill29** [comment]
Further info: I ran a netstat which shows that it is only allocating to TCP ports on top of not reading the .conf file, which is in the default location of /etc/. I have posted everywhere else that I know to without luck. 
``
 sudo netstat -tulpn | grep 3478
tcp        0      0 172.31.XX.XXX:3478      0.0.0.0:*               LISTEN      51761/turnserver    
tcp        0      0 172.31.XX.XXX:3478      0.0.0.0:*               LISTEN      51761/turnserver    
udp        0      0 172.31.XX.XXX:3478      0.0.0.0:*                           51761/turnserver    
udp        0      0 172.31.XX.XXX:3478      0.0.0.0:*                           51761/turnserver

**Comment by ggarber** [comment]
It looks like if you have other process already running in the same ports.  Can you double check that?

Also why do you think turnserver.conf is being read?

How are you starting coturn?  Can you try manually from the command line?

**Comment by mmmill29** [comment]
Not sure why it isn't showing up on this version of what I copied/pasted, but the first line when I check coturn status or restart coturn is that there is no .conf file and default CLI settings are being used. The netstat shows that the socket is being listened to by the turnserver, but is listening for tcp instead of udp, which is the opposite of what I need. But in order to specify no-tcp (if that is the sole workaround, it's the only one I can think of off the top of my head at the moment) I would need the .conf file to be being read, which it is not. I will try to get the updated output and see if that helps.

**Comment by mmmill29** [comment]
> It looks like if you have other process already running in the same ports. Can you double check that?
> 
> Also why do you think turnserver.conf is being read?
> 
> How are you starting coturn? Can you try manually from the command line?

I have restarted it using sudo systemctl restart coturn
I have listed out:
 netstat -tulpn | grep 3478     which showed that TCP listeners exist on the 3478 port as a result of starting a coturn server (When I need UDP or I cannot perform the trickle ICE candidate gathering and prove that it is working)
 
 tcp        0      0 172.31.44.196:3478      0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.31.44.196:3478      0.0.0.0:*               LISTEN      -                   
udp        0      0 172.31.44.196:3478      0.0.0.0:*                           -                   
udp        0      0 172.31.44.196:3478      0.0.0.0:*                           -    

systemctl list-unit-files | grep enabled | grep coturn
Which outputs: 
coturn.service                                 enabled         enabled

I can input the information into https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ which times out and does not proceed with any connection, which is holding us back from connecting to any of our other system components. It is also stating in coturn status that no .conf file was found, despite it being in /etc/ because I can call on and edit/save it repeatedly, successfully.

**Comment by mmmill29** [comment]
If anyone else runs into this specific issue, it is from not using ```sudo turnserver -c turnserver.conf``` to start the instance. Once I killed the existing coturn.service and started a new server instanceu sing the above command, the ports were not denied access and the configuration file was read appropriately.
