### ISSUE TITLE
Able to use STUN/TURN server by only one origin (WebRTC)

### ISSUE THREAD

**Issue by MustafaEminn** [coturn/coturn#1037]
Could we set a origin rule? 

Rule:
Accept request which have www.example.org origin.

**Comment by ggarber** [comment]
Nop, the TURN server doesn't know the url where the request is coming from.

Use authentication with short duration of credentials to prevent usage from other sites.  

Check https://github.com/coturn/coturn/blob/master/README.turnserver#L186

**Comment by eakraly** [comment]
Seems like there is a solution @MustafaEminn ?
Please comment if there is still an issue
