### ISSUE TITLE
Feature request: individual HTML pages

### ISSUE THREAD

**Issue by greg-man** [coturn/coturn#104]
Hi there,

when accessed via HTTP/S coturn delivers its built in HTML pages. Would it be of much effort to have a configurable option for a html directory, from which individual HTML content could be loaded? This would it also make easy to combine coturn with automatically created and renewed ssl certificates from let's encrypt.

Greg

**Comment by eakraly** [comment]
Seems like this issue did not lead to any practical outcome.
Closing this issue. Please reopen if there is more to it.
