### ISSUE TITLE
Proper type in sizeof used?

### ISSUE THREAD

**Issue by gjasny** [coturn/coturn#1045]
Hello,

our static code analysis suggested to take a deeper look at the following two sizeof expressions:

https://github.com/coturn/coturn/blob/cfa5f66cd7ad9a085ee32ffdadafcc84e3093750/src/apps/relay/ns_ioalib_engine_impl.c#L3882

https://github.com/coturn/coturn/blob/cfa5f66cd7ad9a085ee32ffdadafcc84e3093750/src/apps/relay/ns_ioalib_engine_impl.c#L3952

Maybe `sizeof(size_t*)` should be changed into `sizeof(size_t)`. Could you please have a look?

Thanks,
Gregor

**Comment by eakraly** [comment]
Great finding @gjasny 
I agree that it should be `sizeof(size_t)`.
We are lucky that most (or all) of the time `sizeof(size_t)` == `sizeof(size_t*)`

Will you please submit a PR and verify with your static code analysis tool?
Thank you!
