### ISSUE TITLE
Configure HTTPS management interface

### ISSUE THREAD

**Issue by flo-sch** [coturn/coturn#105]
Hey,

I am running coturn v4.2.1.2 on debian 8.

Is it currently possible to configure the management interface?
I did not see any mention about it in the documentation ;

Even though I do not have any admin user yet,
I can still access the interface within a browser :
https://my-domain.tld:5349
(Actually work without https aswell)

The thing is, even if it does not display anything special without an admin access,
The server response provide the used version as an HTTP header :
`Server: Coturn-4.2.1.2 'Monza'`

Anyway, I would prefer to be able to configure how this interface could be accessed,
Potentially, from localhost only, so I could proxy it and set a custom policy.

Is such feature already possible in any version?

**Comment by misi** [comment]
Hi,

See this commit
https://github.com/coturn/coturn/commit/e241d0c71ffc33a8dbab2aaad48a44790b55b887
This is a fix, to avoid leaking the version info, but according RFC version
should be sent.

Best,
Misi

2017-03-05 13:01 GMT+01:00 Florent SCHILDKNECHT <notifications@github.com>:

**Comment by flo-sch** [comment]
Thanks!

Which RFC mention this?

**Comment by thib-ack** [comment]
Hello,
I think this issue can be closed as this has been implemented in #129 and is available since 4.5.1.0.

Thanks,

**Comment by misi** [comment]
@flo-sch  rfc5766 
@thib-ack  Thanks I close it now.
