### ISSUE TITLE
Out of date releases

### ISSUE THREAD

**Issue by benturner** [coturn/coturn#106]
Hi,

https://github.com/coturn/coturn/blob/master/ChangeLog shows the latest version `4.5.0.6`.
https://github.com/coturn/coturn/wiki/Downloads shows the latest version `4.5.0.5`.
https://github.com/coturn/coturn/releases shows the latest version at `4.5.0.4`.

Am I right in thinking that `4.5.0.5` is actually the latest release, and `4.5.0.6` is "in progress"?

**Comment by mom040267** [comment]
4.5.0.6 is a sort of "in progress".

**Comment by benturner** [comment]
Thanks!
