### ISSUE TITLE
The "pu" command seems to show wrong filtered data

### ISSUE THREAD

**Issue by dbrgn** [coturn/coturn#107]
On a coturn instance, the `pu` command via telnet interface seems to show inconsistent data:

```
> pu

    user: <a>, 851 sessions
    user: <b>, 321 sessions
    user: <c>, 1 sessions

  Total sessions: 1173

> pu udp

    user: <a>, 344 sessions
    user: <b>, 181 sessions
    user: <c>, 1 sessions

  Total sessions: 526

> pu tcp

  Total sessions: 0

> pu tls

  Total sessions: 0

> pu dtls

  Total sessions: 0
```

With `ps` I can see many sessions with `client protocol TCP, relay protocol UDP` or `client protocol TLS/TCP, relay protocol UDP`. Why don't they show up in the stats?

Version: coturn 4.5.0.3-1build1 on Ubuntu 16.04

**Comment by misi** [comment]
@dbrgn  Could you restest it with the latest master? THX

**Comment by eakraly** [comment]
Hi @dbrgn !
Is this still an issue that needs to be addressed?

**Comment by dbrgn** [comment]
@misi sorry, I somehow missed your question when you replied!

@eakraly I'm not sure, I'll have to test with the current version next week. I'll close the issue for now, but will re-open in case it's still inconsistent.
