### ISSUE TITLE
Do not forget Debian, before 12 freeze

### ISSUE THREAD

**Issue by Neustradamus** [coturn/coturn#1074]
@eakraly, @ggarber: It is important to update in Debian Unstable, before 12 freeze!
- https://tracker.debian.org/pkg/coturn
- https://packages.debian.org/fr/sid/coturn

Old team members cited here in Debian page:
- Oleg Moskalenko
- Mészáros Mihály

Current team:
- Debian VoIP Team

**Comment by eakraly** [comment]
Hi @Neustradamus ! Do you have any experience with releasing Debian versions?

**Comment by Neustradamus** [comment]
@eakraly: No... but @misi is one of current maintainer...

I know @bootc, @debalance, @tehnick who do a good job!

**Comment by Neustradamus** [comment]
@eakraly: ping

**Comment by eakraly** [comment]
I suppose I would need to dig into this myself 😝

**Comment by marrobHD** [comment]
> I suppose I would need to dig into this myself 😝 

Please!
If you do, please also create docs for it (how to package coturn for Debian).

**Comment by eakraly** [comment]
Also @mymedia2
Looks like was the last uploader - something you may have time to contribute?

**Comment by Neustradamus** [comment]
@eakraly: Time is counted now!
- https://tracker.debian.org/pkg/coturn

Can you contact Debian VoIP team?

**Comment by marrobHD** [comment]
I also contacted pkg-voip-maintainers@alioth-lists.debian.net weeks ago, but never got a reply. Maybe someone else can send another mail?

**Comment by marrobHD** [comment]
I also contacted pkg-voip-maintainers@alioth-lists.debian.net weeks ago, but never got a reply. Maybe someone else can send another mail?

**Comment by Neustradamus** [comment]
@marrobHD: It is this email address...
- https://salsa.debian.org/pkg-voip-team

I see your message...
- https://alioth-lists.debian.net/pipermail/pkg-voip-maintainers/2022-December/037070.html

@misi on salsa:
- https://salsa.debian.org/misi-guest

I see this repository:
- https://salsa.debian.org/wferi/coturn

Creator of the repository:
- Ferenc Wágner <wferi@debian.org>

Maybe an email to him?

Links:
- https://tracker.debian.org/pkg/coturn

**Comment by Neustradamus** [comment]
@ all and @marrobHD: It is this email address...
- https://salsa.debian.org/pkg-voip-team

I see your message...
- https://alioth-lists.debian.net/pipermail/pkg-voip-maintainers/2022-December/037070.html

@misi on salsa:
- https://salsa.debian.org/misi-guest

I see this repository:
- https://salsa.debian.org/wferi/coturn

Creator of the repository:
- Ferenc Wágner <wferi@debian.org>

Maybe an email to him?

There is a page here:
- https://wiki.debian.org/Teams/VoIP

There is an archived repository too:
- https://salsa.debian.org/pkg-voip-team/coturn

**Comment by wferi** [comment]
Hi folks,
I got notified of https://salsa.debian.org/wferi/coturn/-/commit/b1fe951cb47d06bcc05da25da4653dc17f1b32b2#note_370524, but this seems a better place to reply. As a Debian Developer, I sponsored Misi's uploads into the Debian archive in the last couple of years. I don't use coturn myself, so I can't properly maintain it, but I helped to shape its packaging and it was in a fairly good shape last time I looked. So I don't expect any trouble packaging and uploading its newest upstream version, and I'm also willing to help with those if needed. But see also https://alioth-lists.debian.net/pipermail/pkg-voip-maintainers/2022-December/037114.html. What's the official download location nowadays? 4.7.0 mentioned in https://alioth-lists.debian.net/pipermail/pkg-voip-maintainers/2022-December/037070.html eludes me.

**Comment by marrobHD** [comment]
> Hi folks,
> I got notified of https://salsa.debian.org/wferi/coturn/-/commit/b1fe951cb47d06bcc05da25da4653dc17f1b32b2#note_370524, but this seems a better place to reply. As a Debian Developer, I sponsored Misi's uploads into the Debian archive in the last couple of years. I don't use coturn myself, so I can't properly maintain it, but I helped to shape its packaging and it was in a fairly good shape last time I looked. So I don't expect any trouble packaging and uploading its newest upstream version, and I'm also willing to help with those if needed. But see also https://alioth-lists.debian.net/pipermail/pkg-voip-maintainers/2022-December/037114.html. What's the official download location nowadays? 4.7.0 mentioned in https://alioth-lists.debian.net/pipermail/pkg-voip-maintainers/2022-December/037070.html eludes me.


I'm not a maintainer myself, I looked into the changelog and saw 4.7. My fault. 

The current version seems to be `4.6.1`. There's also a GitHub-Release for it (`4.6.1-r0`), at commit `744a263d80816ead30872ec33a52c241cb1634a5`. I guess you can clone the repo and checkout to the commit-id (```git checkout -b v4.6.1 744a263d80816ead30872ec33a52c241cb1634a5```.

**Comment by Neustradamus** [comment]
@rfc1036: Maybe you can help...

**Comment by eakraly** [comment]
I had a call with @misi where he shared a lot of information on how to proceed
Hope I will have some free time this week to try and make progress

**Comment by dzatoah** [comment]
Coturn is in unstable with version 4.6.1-1. Can this issue be closed then?

**Comment by eakraly** [comment]
Hi @dzatoah - what do you mean by unstable?

**Comment by mymedia2** [comment]
On February 14, 2023 3:15:12 AM GMT+03:00, Pavel Punsky ***@***.***> wrote:
>Hi @dzatoah - what do you mean by unstable?

He meant that coturn is now updated in Debian by uploading in our unstable distribution and is going to enter into coming Debian release, bookworm. In other words, the job is done and the issue may be closed.
Current status of the coturn package in Debian -> https://tracker.debian.org/pkg/coturn

**Comment by mymedia2** [comment]
He meant that coturn is now updated in Debian by uploading in our unstable distribution and is going to enter into coming Debian release, bookworm. In other words, the job is done and the issue may be closed.
Current status of the coturn package in Debian -> https://tracker.debian.org/pkg/coturn

**Comment by Neustradamus** [comment]
Debian 12 has been released:
- https://www.debian.org/News/2023/20230610

**Comment by eakraly** [comment]
And it contains 4.6.1-1
