### ISSUE TITLE
Unable to authenticate Nextcloud Talk with coturn deployed on my k8s cluster

### ISSUE THREAD

**Issue by jattind** [coturn/coturn#1076]
I have both coturn and nextcloud Talk installed in a k8s cluster. 
Nextcloud version: 24.0.5
cotrun version: latest

coturn config:
===========
realm=coturn20001.sempre.local
listening-ip=0.0.0.0
listening-port=3478
tls-listening-port=443
min-port=49152
max-port=65535
log-file=stdout
verbose
pidfile=/var/tmp/turnserver.pid
use-auth-secret
static-auth-secret=north
fingerprint
total-quota=0
bps-capacity=0
stale-nonce
no-multicast-peers
user=turnUser:demo@sempre!
pkey=/tls/tls.key
cert=/tls/tls.crt
mysql-userdb=“host=10.39.55.74 port=3306 dbname=coturn user=coturn password=sempre! connect_timeout=30”

In Nextcloud Talk settings I configure the URL for my coturn instance, specify the secret configured in the coturn DB and click the test server connection button. It fails to connect and the coturn logs show the following:

1240: : IPv4. tcp or tls connected to: 10.39.55.82:28183
1240: : session 001000000000000006: realm <coturn20001.sempre.local> user <>: incoming packet message processed, error 401: Unauthorized
1240: : IPv4. tcp or tls connected to: 10.39.55.82:36328
1240: : session 001000000000000007: realm <coturn20001.sempre.local> user <>: incoming packet message processed, error 401: Unauthorized
1240: : ERROR: check_stun_auth: Cannot find credentials of user <1667434059:turn-test-user>
1240: : session 001000000000000006: realm <coturn20001.sempre.local> user <1667434059:turn-test-user>: incoming packet message processed, error 401: Unauthorized
1241: : ERROR: check_stun_auth: Cannot find credentials of user <1667434059:turn-test-user>
1241: : session 001000000000000007: realm <coturn20001.sempre.local> user <1667434059:turn-test-user>: incoming packet message processed, error 401: Unauthorized
1241: : session 001000000000000006: TCP socket closed remotely 10.39.55.82:28183
1241: : session 001000000000000006: usage: realm=<coturn20001.sempre.local>, username=<1667434059:turn-test-user>, rp=2, rb=160, sp=2, sb=224
1241: : session 001000000000000006: peer usage: realm=<coturn20001.sempre.local>, username=<1667434059:turn-test-user>, rp=0, rb=0, sp=0, sb=0
1241: : session 001000000000000006: closed (2nd stage), user <1667434059:turn-test-user> realm <coturn20001.sempre.local> origin <>, local 0.0.0.0:3478, remote 10.39.55.82:28183, reason: TCP connection closed by client (callback)
1241: : session 001000000000000007: TCP socket closed remotely 10.39.55.82:36328
1241: : session 001000000000000007: usage: realm=<coturn20001.sempre.local>, username=<1667434059:turn-test-user>, rp=2, rb=160, sp=2, sb=224
1241: : session 001000000000000007: peer usage: realm=<coturn20001.sempre.local>, username=<1667434059:turn-test-user>, rp=0, rb=0, sp=0, sb=0
1241: : session 001000000000000007: closed (2nd stage), user <1667434059:turn-test-user> realm <coturn20001.sempre.local> origin <>, local 0.0.0.0:3478, remote 10.39.55.82:36328, reason: TCP connection closed by client (callback)

**Comment by jattind** [comment]
Actually figured out that the DB secret was misconfigured.

**Comment by alperentokgoz** [comment]
Hi @jattind 
I am having a similar problem. Can you explain in detail how you solved this problem and what you checked? Also, I don't understand how you tested the server connection.

**Comment by jattind** [comment]
I was using an external DB (MariaDB). After installing it I need to configure the secret.

Create a secret:
- openssl rand -hex 32
- db93ad2b3f584e8cd1e7b37a39832ce243aab395e7d21d66d1194843dbbc1c46

Insert the secret into the DB table:
- INSERT INTO turn_secret (realm, value) VALUES ('coturn.my.local', 'db93ad2b3f584e8cd1e7b37a39832ce243aab395e7d21d66d1194843dbbc1c46');
- Make sure to use the correct URL for your own coturn server.

Before installing coturn, modify turnserver.conf:
- turn-certificate.yaml - URL for the server
- turnserver.conf - URL for coturn and IP address of DB

Use the following in Nextcloud
- URL: coturn.my.local:3478
- Secret: db93ad2b3f584e8cd1e7b37a39832ce243aab395e7d21d66d1194843dbbc1c46
