### ISSUE TITLE
source does not build cleanly in a chrooted environment

### ISSUE THREAD

**Issue by law** [coturn/coturn#109]
Attempting to build v4.5.0.4 in a checkinstall-managed chroot fails with multiple directories being created incorrectly.  Steps to recreate are: 
```
git clone -b 4.5.0.4 --single-branch https://github.com/coturn/coturn.git ./
./configure --prefix=/opt
make
checkinstall -y --pkgname=ev-coturn --pkgversion=4.5.0.4 --pkgrelease=1 --pakdir=../ --fstrans=yes --install=no
```

Multiple directories will error out in turn with that checkinstall comand, such as: 
```
cp -rpf examples/etc /opt/coturn/share/examples/turnserver 
cp: preserving times for '/opt/coturn/share/examples/turnserver/etc': 
No such file or directory Makefile:167: recipe for target 'install' failed 
make: *** [install] Error 1 ****  Installation failed.
 Aborting package creation. 
Cleaning up...
OK Bye.
```

Tracing it back, it appears to be a less-than-inclusive enumerating of directories in the `configure` and `Makefile.in` scripts.

**Comment by mom040267** [comment]
Can you be specific ?

Those files are used to build Coturn in FreeBSD and Debian packages, and
they work just fine.

Oleg

**Comment by law** [comment]
Hey Oleg, thanks for the quick reply.  In digging around on this, the problem seems to be that the parent directories of some paths are not created.  For example, the above error is because the Makefile defines EXAMPLESDIR with: 

```EXAMPLESDIR = /opt/coturn/share/examples/turnserver
examplesdir = /opt/coturn/share/examples/turnserver
```

(line 25 and 26 of a post-configure Makefile) 
and tries to create it with

```
${MKDIR} ${DESTDIR}${EXAMPLESDIR}
```

(line 173 of a post-configure Makefile)

However, there is no '/opt/coturn/share' directory being created previously, nor is there an '/opt/coturn/share/examples' directory being created.  Since the MKDIR command is defined as 'install -d' instead of something like 'mkdir -p', the specified parent directories are not created as needed.  

Let me know if this helps explain the situation, I can try a different way of going about it if not.

**Comment by mom040267** [comment]
Hi Lee. Thanks for explanation. But it is still not clear. The thing is
that the "install" utility must create all directories, this is from the
"man install" page:

*-d*      Create directories.  Missing parent directories are created as
required.


Oleg

**Comment by eakraly** [comment]
Hi @law !
Do you still have an issue? If yes please reopen.
