### ISSUE TITLE
Coturn started, but not working

### ISSUE THREAD

**Issue by VladlenO** [coturn/coturn#1104]
I accidentally started installing postgre sql.  during the installation process, he wanted to change with the coturn.  I canceled the intervention in the file and deleted the postgre itself.  But, now my coturn server starts, but does not work in nextcloud.  I provide you with port logs and settings.
[https://digic.cloud/s/ZDpZeAHHFqaiHBk](config and view terminal status and ports) 

Monitoring screenschot
![Screenshot_20221123_152312_com maoux ismyserveronline huawei](https://user-images.githubusercontent.com/91730566/203557639-8cf568f6-c460-42bd-94f7-3bbbc3bd13f7.jpg)

**Comment by eakraly** [comment]
Hi @VladlenO !
It is not very clear what happened from your description.
Could be that coturn is now configured to use PostgreSQL (or some other form of authentication) instead what you had before?
Like - could be that your auth is broken now?

**Comment by VladlenO** [comment]
Experienced found out that the server ignores the ssl port. With this setting, everything works, but I'm not sure if this is a secure connection, although the certificates are in perfect order.

`# TURN listener port for UDP and TCP (Default: 3478).
# Note: actually, TLS & DTLS sessions can connect to the 
# "plain" TCP & UDP port(s), too - if allowed by configuration.
#
listening-port=5349 # change port 3478 and working

# TURN listener port for TLS (Default: 5349).
# Note: actually, "plain" TCP & UDP sessions can connect to the TLS & DTLS
# port(s), too - if allowed by configuration. The TURN server 
# "automatically" recognizes the type of traffic. Actually, two listening
# endpoints (the "plain" one and the "tls" one) are equivalent in terms of
# functionality; but we keep both endpoints to satisfy the RFC 5766 specs.
# For secure TCP connections, we currently support SSL version 3 and 
# TLS version 1.0, 1.1 and 1.2.
# For secure UDP connections, we support DTLS version 1.
#
tls-listening-port=5349 # ignored this option all the time`

**Comment by eakraly** [comment]
Security of TURN servers is often misunderstood.
You can run a secure TURN server without SSL certificates (in case of WebRTC)

If you want to test SSL configuration of your server you can use https://www.ssllabs.com/ssltest/
They provide very nice summary and action items
(I have no affiliation to them - I used them personally a lot in the past)

**Comment by eakraly** [comment]
Hi @VladlenO 
Seems like your issue has been resolved. I will review your comment regarding turnserver ignoring `tls-listening-port` configuration.
If you have any issues pls reopen. Thank you!
