### ISSUE TITLE
Turn Server Data Usage Stats on Multi User System

### ISSUE THREAD

**Issue by batusekerci** [coturn/coturn#1107]
Hi,
AFAIU to get the stats data, we must use redis database. I tried to used it, I displayed the traffic data (with psubscribe turn/realm/*/user/*/allocation/*/traffic ) but the other subscribe events have never worked (	psubscribe turn/realm/*/user/*/allocation/*/traffic/peer or psubscribe turn/realm/*/user/*/allocation/*/total_traffic even if the allocation is deleted). So, I tried to get past traffic data from redis db but I couldn't find how. At redis, KEYS * command gives just "status" events.

Even if I get these traffic data, I couldn't realize how to use it with multi users. Currently in our project we have one user(in terms of coturn) and other users are using turn over this user. We want to track each users turn usage seperately. I inspected Turn Rest API, AFAIU it is just used to authorize the user which already exists in Coturn db. This is the point I couldn't realize exactly. I can use an ice server list which includes different username-credential peers. But I must have initialized these username-credential peers on coturn db before. Am I right? If I am right, I do not have an idea how to do this. Detection of user's request to use turn from frontend -> Should generate credentials like this [https://stackoverflow.com/questions/35766382/coturn-how-to-use-turn-rest-api](url) which I am already achieved -> if this is a new user, my backend should go to my EC2 instance and run "turnadmin create user command" somehow -> then I will let the WebRTC connection - > then track the usage of specific user and send it back to my backend somehow.

Is this a true scenario? If not, how should it be? Is there another way to manage multiple users and their data usage? Any help would be appreciated.

Edit: BTW we tried to track the usage where we created peer connection object from RTCPeerConnection interface. I realized that incoming bytes are lower than the redis output. So I think there is a loss and I think I should calculate it from turn side.

**Comment by batusekerci** [comment]
> Hi, AFAIU to get the stats data, we must use redis database. I tried to used it, I displayed the traffic data (with psubscribe turn/realm/_/user/_/allocation/_/traffic ) but the other subscribe events have never worked ( psubscribe turn/realm/_/user/_/allocation/_/traffic/peer or psubscribe turn/realm/_/user/_/allocation/*/total_traffic even if the allocation is deleted). So, I tried to get past traffic data from redis db but I couldn't find how. At redis, KEYS * command gives just "status" events.
> 
> Even if I get these traffic data, I couldn't realize how to use it with multi users. Currently in our project we have one user(in terms of coturn) and other users are using turn over this user. We want to track each users turn usage seperately. I inspected Turn Rest API, AFAIU it is just used to authorize the user which already exists in Coturn db. This is the point I couldn't realize exactly. I can use an ice server list which includes different username-credential peers. But I must have initialized these username-credential peers on coturn db before. Am I right? If I am right, I do not have an idea how to do this. Detection of user's request to use turn from frontend -> Should generate credentials like this [https://stackoverflow.com/questions/35766382/coturn-how-to-use-turn-rest-api](url) which I am already achieved -> if this is a new user, my backend should go to my EC2 instance and run "turnadmin create user command" somehow -> then I will let the WebRTC connection - > then track the usage of specific user and send it back to my backend somehow.
> 
> Is this a true scenario? If not, how should it be? Is there another way to manage multiple users and their data usage? Any help would be appreciated.

Edit: BTW we tried to track the usage where we created peer connection object from RTCPeerConnection interface. I realized that incoming bytes are lower than the redis output. So I think there is a loss and I think I should calculate it from turn side.

**Comment by eakraly** [comment]
Hi @batusekerci 

turnserver provides prometheus interface that allows you to monitor metrics emitted by turnserver - this is a very common interface and can be consumed/fed into multiple monitoring systems. I think redis was developed in the past as a quick workaround for monitoring - I would not use it for anything as it does not provide much data, have gaps, and can cause performance issues.

What I suggest you do to (if I understand you correctly) is following:
- Run turnserver with `--prometheus` to enable prometheus interface
- You can configure specific port with `--prometheus-port`, default is 9641
- Enable username labels with `-prometheus-username-labels` this will label every metric with specific username you gave in your credentials
- Scrape/ingest the metrics in whatever monitoring solution you have (prometheus + grafana for example)
- Now you can build graphs/monitor per user or aggregate

VERY IMPORTANT NOTE: if you have potentially infinite amount of usernames then turnserver will appear as if it is leaking memory - prometheus library that is used in turnserver does not provide mechanism to "delete" old labels (usernames) so it will grow until you run out of memory. That is why `-prometheus-username-labels` is off by default

**Comment by batusekerci** [comment]
I uncommented the prometheus label in config file but I get these errors in sysout:

0: : Bad configuration format: prometheus
0: : Bad configuration format: prometheus-username-labels

My Coturn version is 4.5.2. 
I installed libprom and libpromhttp. 
Prometheus is installed and working at :9090 successfully.

Thanks for the response BTW

**Comment by eakraly** [comment]
@batusekerci I recommend 4.6.1

You also need to rebuild turnserver most probably
When you run turnserver - what does it tell about prometheus support?

**Comment by batusekerci** [comment]
I removed coturn with: `sudo apt-get purge --auto-remove coturn`
I installed again with: `sudo apt install coturn`
I started it again and got the same errors. Isn't turnserver rebuilt when we reinstall coturn? 
I could not understand your last words. Like I said, it prints to sysout(verbose mode is open from config) : "Bad configuration format: prometheus" Is there another place to see different logs?
I am going to try 4.6.1

**Comment by eakraly** [comment]
You are installing from a package repository - not sure what version you are getting
Please run `turnserver --help` and look for mentions of prometheus

**Comment by batusekerci** [comment]
Thank you very much! CoTURN 4.6.1 gives metrics from Prometheus. 

Notes for future readers: 

I set up a new EC2 instance and after installing dependencies( libprom etc.), I installed 4.6.1 with Makefile.
There are some consequences of not using apt get installation method. I have suffered from the missing files because "installation with Makefile" does not create the essential files and folders (such as turnserver.conf, coturn.service etc.) 
You can use the examples folder of coturn repo in order to create these missing files.

I still get  "WARNING: STUN CHANGE_REQUEST not supported: only one IP address is provided" warning in sysout. I use exactly the same turnserver.conf file at another EC2 instance ( filled IP fields differently of course) and I do not get this warning IDKW. But as I observed, there are no problems while using CoTurn.
