### ISSUE TITLE
Install rfc5766-turn-server, Trying to bind fd to <ip address>: errno=99

### ISSUE THREAD

**Issue by khoachung89** [coturn/coturn#111]
I'm using an Ubuntu 14.04 (an Azure VPS actually) so i have to installed rfc5766-turn-server not the latest coturn version. I have following [this guide](https://installion.co.uk/ubuntu/trusty/universe/r/rfc5766-turn-server/install/index.html).

At the last step, i cannot start turnserver. My command to start:

`turnserver -n -L <my_server_public_IP> -X <my_server_public_IP> -E <my_server_public_IP> -a -f -r my-domain.com --cert /myPath/TurnServerCerts/turnserver.crt --pkey /myPath/TurnServerCerts/TurnServerCerts/turnserver.key`

I got the following from the log:

0:
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Citrix-3.2.3.1 'Marshal West'
0:
Max number of open files/sockets allowed for this process: 4096
0:
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 2000 (approximately)
0:

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: Redis supported
0: PostgreSQL supported
0: MySQL supported
0: OpenSSL version: fresh enough
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: Listener address to use: <my_server_public_IP>
0: Relay address to use: <my_server_public_IP>
0: Config file found: /etc/turnuserdb.conf
0: SSL23: Certificate file found: /myPath/TurnServerCerts/turnserver.crt
0: SSL23: Private key file found: /myPath/TurnServerCerts/turnserver.key
0: TLS1.0: Certificate file found: /myPath/TurnServerCerts/turnserver.crt
0: TLS1.0: Private key file found: /myPath/TurnServerCerts/turnserver.key
0: TLS1.1: Certificate file found: /myPath/TurnServerCerts/turnserver.crt
0: TLS1.1: Private key file found: /myPath/TurnServerCerts/turnserver.key
0: TLS1.2: Certificate file found: /myPath/TurnServerCerts/turnserver.crt
0: TLS1.2: Private key file found: /myPath/TurnServerCerts/turnserver.key
0: TLS cipher suite: DEFAULT
0: DTLS: Certificate file found: /myPath/TurnServerCerts/turnserver.crt
0: DTLS: Private key file found: /myPath/TurnServerCerts/turnserver.key
0: DTLS cipher suite: DEFAULT
0: pid file created: /var/run/turnserver.pid
0: IO method (main listener thread): epoll (with changelist)
0: WARNING: I cannot support STUN CHANGE_REQUEST functionality because only one IP address is provided
0: Wait for relay ports initialization...
0:   relay <my_server_public_IP> initialization...
0:   relay <my_server_public_IP> initialization done
0: Relay ports initialization done
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=0 created
bind: Cannot assign requested address
bind: Cannot assign requested address
0: Trying to bind fd 14 to <my_server_public_IP:3478>: errno=99
Cannot bind local socket to addr: Cannot assign requested address
0: Cannot bind UDP/DTLS listener socket to addr <my_server_public_IP:3478>:3478
0: Trying to bind UDP/DTLS listener socket to addr <my_server_public_IP:3478>:3478, again...
0: Trying to bind fd 15 to <my_server_public_IP:3478>: errno=99
Cannot bind local socket to addr: Cannot assign requested address
0: Cannot bind TCP/TLS listener socket to addr <my_server_public_IP:3478>:3478
0: Trying to bind TCP/TLS listener socket to addr <my_server_public_IP:3478>, again...

And now, i still cannot start turn server.

**UPDATE**

I have tried removing the -L parameter and the turnserver can start without above error. Of course, it's listening my local IP address only (127.0.0.1/10.0.1.4/::1). How can i force it listening my public IP address?

**Comment by mom040267** [comment]
Something is already using that port.

**Comment by KartikRajaS** [comment]
user=root:o******
listening-port=2434
listening-ip=192.168.1.1  \\local ip
relay-ip=192.168.1.1    \\local ip
external-ip=<my public ip>

**turnserver.config**

this is my config file when is run listening ip with local ip address no error occurs.. but when i replace it with mu public ip or server's ip i am getting the same above mentioned error..


Can any one please guide me to start the turnserver without any error..

**Comment by RamyaAshika** [comment]
Whether it works @KartikRajaS

**Comment by RamyaAshika** [comment]
how to fix this issue? Any solution @mom040267 @khoachung89

**Comment by shrikant12345** [comment]
Issue resolved by changing min and max ip range from 
# (default values are 49152 and 65535)
#
min-port=69152
max-port=85535
