### ISSUE TITLE
ERROR: check_stun_auth: Cannot find credentials of user

### ISSUE THREAD

**Issue by SalvatoreAD** [coturn/coturn#112]
Can you help me?

I used "turnadmin" to add login credentials, I tested my server on the site "[trickle ICE](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/)" if i test "stun: myip: 3478" with the credentials, the site responds properly, if I use "turn: myip: 3478" comes out this error.

This is another error: "realm <xxx.xxx.xxx.xxx> user <username>: incoming packet message processed, error 401: Unauthorized"

**Comment by mom040267** [comment]
We are dealing with TURN issues here, this is about WebRTC setup.

**Comment by 350078238** [comment]
我也遇到这个问题，不知道怎么解决，请问你解决了吗？

**Comment by elhananjair** [comment]
@mom040267 Hello recently I am getting the same error in the **turnserver.log file,** although everything is working for me (video, audio...) I could still see this error. I specified a user OAuth section of **turnserver.conf** for a purpose of using that username and password in Janus config file. Things are working fine but this error is still showing up
