### ISSUE TITLE
socket buffer operation error when using TCP/TLS

### ISSUE THREAD

**Issue by paride** [coturn/coturn#113]
While setting up a `turns:` server I noticed that I could not connect to it using Google's webrtc library [1].

> 2721: IPv4. tcp or tls connected to: 1.2.3.4:47716
> 2721: session 000000000000000002: TLS/TCP socket disconnected: 1.2.3.4:47716
> 2721: session 000000000000000002: closed (2nd stage), user <> realm <mydomain> origin <>, local 192.168.43.70:8443, remote 1.2.3.4:47716, reason: **TLS/TCP socket buffer operation error** (callback)

In order to guess what the problem is I tried to connect to coturn via https using Chromium, but the browser gave me this error: `ERR_SSL_PROTOCOL_ERROR` , while coturn logged the same error as before. After trying a few things I noticed that I could connect to the server using Firefox, curl, or other tools, but not with Chromium. If I don't use TLS everything works fine both with Chromium and with the webrtc library.

I really don't know what could be wrong. The only thing I can think of if that both Chromium and the webrtc library use Google's BoringSSL library instead of OpenSSL, so the culprit may lie there,

This issue is easy to reproduce, for example this is a coturn server working fine with curl
```
$ curl https://turn1.whispersystems.org
<!DOCTYPE html>
<html>
  <head>
    <title>TURN Server (https admin connection)</title>
 <style> table, th, td { border: 1px solid black; border-collapse: collapse; text-align: left; padding: 5px;} table#msg th { color: red; background-color: white; } </style> </head>
  <body>
    <b>TURN Server</b><br><i>https admin connection</i><br>
<br>To use the HTTPS admin connection, you have to set the database table <b><i>admin_user</i></b> with the admin user accounts.<br>
</body>
</html>
```
the same is true with Firefox, while Chromium gives `ERR_SSL_PROTOCOL_ERROR`. I'm not the only one experiencing this issue [2] [3].

I'm running coturn 4.5.0.5 from Debian Stretch.

[1] https://chromium.googlesource.com/external/webrtc
[2] https://groups.google.com/forum/#!topic/turn-server-project-rfc5766-turn-server/CxrWCQjDGKc
[3] https://groups.google.com/forum/#!topic/turn-server-project-rfc5766-turn-server/-jFdNKSdebE

**Comment by mom040267** [comment]
As far as i understand boring ssl is not 100% compatible with open ssl. If there is a protocol difference then you have to use separate turn servers for chromium and for other users - the first one linked with boring ssl, the second linked with open ssl. That sounds silly, i understand. Somebody has to debug what is wrong in the negotiations.

**Comment by paride** [comment]
Wait, it is not supposed to be like this, otherwise Google products would be unusable. BoringSSL is just another library implementing TLS, it's derived from OpenSSL and it's not breaking the standard.

**Comment by davidben** [comment]
This is caused by a typo in the ALPN callback. `ta_len` here should be `ha_len`. As a result, you're not actually spelling "http/1.1" in your ALPN callback correctly. Newer Chromes notice this and fail the connection. Previously, we would silently treat anything we didn't recognize as HTTP/1.1.
https://github.com/coturn/coturn/blob/516e534ef258fb52bfd001f6929948f9dbf7ea52/src/apps/relay/mainrelay.c#L2459

**Comment by vol4iniche** [comment]
I see the same issue in the 4.5.0.6 version

**Comment by MichaIng** [comment]
I ran into the same issue on 4.5.0.5 (version before the fix was applied). Upgraded to 4.5.0.7 and issue was gone.

Just checked code on 4.5.0.6 and the fix already seems to be applied there: https://github.com/coturn/coturn/blob/6aa8b7685bad4d0fba48881d27c95c7d00ea8644/src/apps/relay/mainrelay.c#L2459
- Also fits to release date > date of fix.

So if @vol4iniche you still face the issue, then there seems to be something else wrong. `ERR_SSL_PROTOCOL_ERROR` of course can have many reasons. Check if the coturn log file contains the same error messages as well.

**Comment by jonathanmmm** [comment]
Where is this file? Tried to find it, I have debian 8 and only 4.5.0.5-1+deb9u1 version is installed.

Would like to change this on my own.

**Comment by MichaIng** [comment]
@jonathanmmm 
This is a source file, so you cannot fix this on an installed coTURN.

> 4.5.0.5-1+deb9u1

So you are on Debian 9 Stretch, aren't you?
From there you can install coTURN 4.5.1 from backports: https://packages.debian.org/stretch-backports/coturn

**Comment by jonathanmmm** [comment]
Can you help what I have to enter in the sources list?
I dont want to Update All Things automatically to backports (if this could Happen?)

**Comment by MichaIng** [comment]
E.g. `echo 'deb https://deb.debian.org/debian stretch-backports main' > /etc/apt/sources.list.d/stretch-backports` should be sufficient.

To assure that no packages are updated automatically from backports, the following should work:
`echo -e 'Package: *\nPin: release n=stretch-backports\nPin-Priority: -1' > /etc/apt/preferences.d/stretch-backports`

Then `apt update` which should print pulling from backports then.
Then `apt -t stretch-backports install coturn` for force installing/updating coTURN from backports + all required dependencies.

**Comment by teddythetwig** [comment]
I'm still getting this issue on 4.5.1
Running CoTurn on Fedora 29
```
1295: session 000000000000000057: TLS/TCP socket disconnected: CONNIP:21300
1295: session 000000000000000057: usage: realm=<REALM>, username=<>, rp=0, rb=0, sp=0, sb=0
1295: session 000000000000000057: closed (2nd stage), user <> realm <REALM> origin <>, local RELAYIP:443, remote CLIENTIP:21300, reason: TLS/TCP socket buffer operation error (callback)
```

**Comment by rasos** [comment]
I am also still getting this on 4.5.0.7-1ubuntu2.18.04.1

> reason: TLS/TCP socket buffer operation error (callback)

**Comment by rasos** [comment]
Getting same error on 4.5.1.1-1.1 (Debian buster)

> closed (2nd stage), user <> realm <mydoain.eu> origin <>, local 178.63.mmm.nnn:443, remote 92.118.xxx.yyy:47466, reason: TCP socket buffer operation error (callback)

The typo as reported above indeed is not in the master branch anymore, so likely no regression. Reopen the issue?

**Comment by spacetourist** [comment]
I have the same experience as @rasos using the same version. What is the impact of this issue on a running server?

**Comment by psi-4ward** [comment]
same here

**Comment by localguru** [comment]
Same here with coturn 4.5.1.2

**Comment by misi** [comment]
If you check the code "TLS/TCP socket buffer operation error (callback)"
Any not clean TLS close could cause it. We need to check it more. 
https://github.com/coturn/coturn/blob/db68c761954853f2fb167e507d2aab9b0989d943/src/apps/relay/ns_ioalib_engine_impl.c#L2880

**Comment by localguru** [comment]
Same here with coturn 4.5.1.1-1.1build2 on Ubuntu 20.04 LTS. cert= contains the full chain, test with testssl.sh is fine. Any ideas?

**Comment by rasos** [comment]
@paride or any other maintainer would you consider to re-open this issue? Or should we open a new one?

**Comment by paride** [comment]
@rasos I can't reopen it, I suggest to open a new bug and mention that this one regressed. I'm not using coturn anymore so I can't be more precise.

**Comment by dhaminitinAltran** [comment]
facing the same error as well. Has anyone got the solution yet?

**Comment by knoy** [comment]
Is coturn TLS really broken? It seems there are many issues of people unable to get TURNS setup

**Comment by tanero** [comment]
have same issue on ubuntu 20.04 .

**Comment by andyxheli** [comment]
Same here 

322: handle_udp_packet: New UDP endpoint: local addr 66.158.36.55:443, remote addr 188.172.110.153:37915
322: session 002000000000000024: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
322: handle_udp_packet: New UDP endpoint: local addr 66.158.36.55:443, remote addr 188.172.110.153:39927
322: session 002000000000000025: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
322: handle_udp_packet: New UDP endpoint: local addr 66.158.36.55:443, remote addr 188.172.110.153:38019
322: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
322: IPv4. tcp or tls connected to: 188.172.110.153:44450
322: IPv4. tcp or tls connected to: 188.172.110.153:45354
322: IPv4. tcp or tls connected to: 188.172.110.153:51851
323: session 002000000000000024: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
323: session 002000000000000025: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
323: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
323: session 003000000000000018: TLS/TCP socket disconnected: 188.172.110.153:44450
323: session 003000000000000018: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
323: session 002000000000000027: TLS/TCP socket disconnected: 188.172.110.153:45354
323: session 002000000000000027: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
323: session 003000000000000018: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:44450, reason: TLS/TCP socket buffer operation error (callback)
323: session 002000000000000027: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:45354, reason: TLS/TCP socket buffer operation error (callback)
323: session 003000000000000019: TLS/TCP socket disconnected: 188.172.110.153:51851
323: session 003000000000000019: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
323: session 003000000000000019: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:51851, reason: TLS/TCP socket buffer operation error (callback)
323: IPv4. tcp or tls connected to: 188.172.110.153:34398
323: IPv4. tcp or tls connected to: 188.172.110.153:53906
323: IPv4. tcp or tls connected to: 188.172.110.153:56365
324: session 003000000000000020: TLS/TCP socket disconnected: 188.172.110.153:56365
324: session 003000000000000020: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
324: session 003000000000000020: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:56365, reason: TLS/TCP socket buffer operation error (callback)
324: session 001000000000000015: TLS/TCP socket disconnected: 188.172.110.153:53906
324: session 001000000000000015: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
324: session 001000000000000015: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:53906, reason: TLS/TCP socket buffer operation error (callback)
325: session 000000000000000022: TLS/TCP socket disconnected: 188.172.110.153:34398
325: session 000000000000000022: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
325: session 000000000000000022: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:34398, reason: TLS/TCP socket buffer operation error (callback)
326: IPv4. tcp or tls connected to: 66.158.36.34:62884
326: IPv4. tcp or tls connected to: 66.158.36.34:56719
326: IPv4. tcp or tls connected to: 66.158.36.34:63836
326: IPv4. tcp or tls connected to: 66.158.36.34:57723
326: IPv4. tcp or tls connected to: 66.158.36.34:55736
326: IPv4. tcp or tls connected to: 66.158.36.34:53584
326: session 001000000000000016: realm <turn.axtsolutions.com> user <>: incoming packet message processed, error 401: Unauthorized
326: session 001000000000000017: realm <turn.axtsolutions.com> user <>: incoming packet message processed, error 401: Unauthorized
326: IPv4. Local relay addr: 66.158.36.55:65441
326: session 001000000000000016: new, realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, lifetime=600, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
326: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet ALLOCATE processed, success
326: IPv4. Local relay addr: 66.158.36.56:52892
326: session 001000000000000017: new, realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, lifetime=600, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
326: session 001000000000000017: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet ALLOCATE processed, success
326: session 001000000000000016: peer 10.107.47.112 lifetime updated: 300
326: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
326: session 001000000000000016: peer 10.107.47.112 lifetime updated: 300
326: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
326: session 001000000000000016: peer 10.207.195.153 lifetime updated: 300
326: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
326: session 001000000000000017: peer 10.107.47.112 lifetime updated: 300
326: session 001000000000000017: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
326: session 001000000000000017: peer 10.107.47.112 lifetime updated: 300
326: session 001000000000000017: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
326: session 001000000000000017: peer 10.207.195.153 lifetime updated: 300
326: session 001000000000000017: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
331: session 001000000000000016: peer 188.172.110.153 lifetime updated: 300
331: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
331: session 001000000000000017: peer 188.172.110.153 lifetime updated: 300
331: session 001000000000000017: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
331: session 001000000000000016: peer 188.172.110.153 lifetime updated: 300
331: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
331: session 001000000000000017: peer 188.172.110.153 lifetime updated: 300
331: session 001000000000000017: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
331: session 001000000000000016: peer 188.172.110.153 lifetime updated: 600
331: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CHANNEL_BIND processed, success
333: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
333: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
336: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=1124, rb=810368, sp=924, sb=523064
341: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=1014, rb=754530, sp=1034, sb=697436
343: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
345: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=778, rb=469813, sp=1270, sb=976316
351: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=749, rb=330110, sp=1299, sb=941652
353: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
354: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
357: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=643, rb=183835, sp=1405, sb=1046468
363: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=561, rb=90282, sp=1487, sb=1097328
364: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
369: session 003000000000000021: TLS/TCP socket disconnected: 66.158.36.34:53584
369: session 003000000000000021: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
369: session 002000000000000028: TLS/TCP socket disconnected: 66.158.36.34:57723
369: session 003000000000000021: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:53584, reason: TLS/TCP socket buffer operation error (callback)
369: session 000000000000000023: TLS/TCP socket disconnected: 66.158.36.34:63836
369: session 000000000000000023: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
369: session 000000000000000023: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:63836, reason: TLS/TCP socket buffer operation error (callback)
369: session 002000000000000028: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
369: session 002000000000000028: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:57723, reason: TLS/TCP socket buffer operation error (callback)
369: session 002000000000000029: TLS/TCP socket disconnected: 66.158.36.34:55736
369: session 002000000000000029: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
369: session 002000000000000029: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:55736, reason: TLS/TCP socket buffer operation error (callback)
370: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=589, rb=75351, sp=1459, sb=1021352
374: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
376: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=519, rb=68391, sp=1529, sb=1197756
382: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=473, rb=62824, sp=1575, sb=1314792
382: session 002000000000000024: usage: realm=<turn.axtsolutions.com>, username=<>, rp=2, rb=40, sp=2, sb=192
382: session 002000000000000024: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:37915, reason: allocation watchdog determined stale session state
382: session 002000000000000025: usage: realm=<turn.axtsolutions.com>, username=<>, rp=2, rb=40, sp=2, sb=192
382: session 002000000000000025: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:39927, reason: allocation watchdog determined stale session state

**Comment by neilyoung** [comment]
Same here, Raspberry PI OS buster

reason: TLS/TCP socket buffer operation error (callback)

**Comment by neilyoung** [comment]
It maybe can really be a trust issue with the certificate. I'm having an let's encrypt certificate and provided the fullchain.pem. However, in wireshark I see, that my client (browser) is rejecting the certificate with "Unknown certificate"

**Comment by neilyoung** [comment]
Arghh... That was a beginner mistake... I was trying to fetch turn candidates using the public address of my TURN server, not the name. That caused the "Certificate unknown"

And finally it worked (after returning to fixed credential authentication, currently I'm getting 401 with the REST API credential).

So basically it was a certificate issue (IP instead of FQDN on call) and the "TLS/TCP socket buffer operation error" is such a generic trace, that it points to nothing, because it comes at every TLS termination, even a good one.

Having relay candidates via TLS. Hurray...

No issue anymore here
