### ISSUE TITLE
TURN connection fails with Firefox, times out with Chrome

### ISSUE THREAD

**Issue by AshleyScirra** [coturn/coturn#1132]
I'm pretty stuck on this so I appreciate any help! We had coturn running smoothly previously, and then a few weeks ago we did some routine software updates. Now the TURN server doesn't appear to work properly. It's running Ubuntu 22.04 LTS with the latest available coturn 4.5.2-3.1~ubuntu22.04.1. We see the following behavior in browsers connecting to TURN:

1) In Firefox, connections fail to be established entirely. Sometimes it logs a console message saying "your TURN server is broken", but sometimes not.
2) In Chrome, connections succeed, but after 30-40 seconds it disconnects. The connection state changes to "failed".

In both cases I can't figure out any much more about what happened from either about:webrtc, chrome://webrtc-internals, or the logs on the TURN server. I'm not sure I can make sense of the logs anyway.

I've made a test case that demonstrates the problem. Try this URL: https://downloads.scirra.com/labs/turn-test/
This sets `iceTransportPolicy` to `"relay"` on the RTCPeerConnection in order to force it to go via our TURN server at `turn:multiplayer-turn.construct.net` (username `scirra`, password `construct`). This allows the problem to be observed with two browser tabs on the same device. Try following these steps:

1. Open the URL on two browser tabs
2. In the first tab, enter name user1, room name abc123, and click login
3. In the second tab, enter name user2, room name abc123, and click login
4. Try using the chat (messages should appear in the other tab)

In Firefox it never establishes a connection so chat messages are never transmitted, and it eventually times out and quits. In Chrome it connects and messages can be exchanged, but then it disconnects after 30-40 seconds. The `max-allocate-lifetime` in turnserver.conf is left at its default of 3600 so I don't see how it's that.

I'm at a loss as to what is going on. All I know is it used to work and now it doesn't work properly. Having a functioning TURN service is important to us. Can anyone figure out what has gone wrong? Is it a coturn bug? I'm happy to pay for time to investigate if anyone offers commercial diagnostic services.

**Comment by AshleyScirra** [comment]
OK, I think I managed to figure this one out myself. For the benefit of future Internet searches with the same problem - using coturn with WebRTC in browsers requires the following two settings to be enabled in turnserver.conf:

`fingerprint`
`lt-cred-mech`

With those the above problem I described appears to be fixed. Apologies for filing an issue - my bad!

**Comment by Willis0826** [comment]
Thank you @AshleyScirra . It works!

At first glance, neither `fingerprint `nor `lt-cred-mech` seems to be related to the 40-second disconnect issue, but it did resolve the problem 😆 

By the way, it works on my side even without `fingerprint`.
