### ISSUE TITLE
Mismatched allocation: wrong transaction ID, when duplicating ICE ports

### ISSUE THREAD

**Issue by kolserdav** [coturn/coturn#1138]
When I restart my application and if the tests allocate the same ICE ports for the client (client role is https://github.com/shinyoshiaki/werift-webrtc) that were allocated in the previous application server session, then `coturn` returns the following error. Only restarting `coturn` helps.
```sh
[
  [
    'ERROR-CODE',
    [ 437, 'Mismatched allocation: wrong transaction ID\x00' ]
  ],
  [ 'SOFTWARE', "Coturn-4.5.2 'dan Eider'" ],
  [ 'FINGERPRINT', 4171264430 ]
]
```
More from this post https://github.com/shinyoshiaki/werift-webrtc/issues/304#issuecomment-1374376601

Possible way to reproduce the problem https://github.com/kolserdav/werift-sfu-react/blob/master/docs/CONTRIBUTING.md

Everything indicates that this problem is in `coturn`, since on the first run everything works fine, and only after stopping and restarting the application server `coturn` gives this error when the same ICE ports are allocated as in the previous run. This means that `coturn` keeps some state about connections, even if the process making the connection is not running.

**Comment by eakraly** [comment]
Hi @kolserdav 
Your explanation makes perfect sense but I do not agree this is a problem
Allocations have a lifetime (600 seconds by default as defined by RFC) - so it continues to persist even if client restarts.
This is especially valid if UDP is used as there is no way for coturn to figure out that client restarted.
Moreover, this is seen as a security attack which coturn tries to prevent (rejects fingerprints).

I think the flow of the client is not correct - TURN (not coturn specifically) assumes allocation needs to be negotiated. There are no "reserved" ports for specific clients - if client restarts it needs to reallocate TURN session (including exchange with the peer)

**Comment by kolserdav** [comment]
Hi @eakraly  
Thanks for your reply.

>Allocation has a lifetime (600 seconds by default as defined by RFC) 

- Obviously, the situation I described is due to this.

I will have to take this into account in my application somehow.
