### ISSUE TITLE
cannot start TLS and DTLS listeners because private key file is not set properly

### ISSUE THREAD

**Issue by AhmedHumk** [coturn/coturn#1139]
on my ubuntu 20 i tried to install coturn although i have created the config and point it to a certbot certficate no matter what i do i get this warning 

```
 #012CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
Jan 10 16:32:04 vps-7 turnserver: 0: WARNING: cannot find certificate file: turn_server_cert.pem (1)
Jan 10 16:32:04 vps-7 turnserver: 0: WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
Jan 10 16:32:04 vps-7 turnserver: 0: WARNING: cannot find private key file: turn_server_pkey.pem (1)
Jan 10 16:32:04 vps-7 turnserver: 0: WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
```

also my certificate file doesn't called turn_server_cert.pem

whats wrong exactly in this case ?

**Comment by tinusm369** [comment]
Try copying both turn_server_cert.pem and turn_server_pkey.pem files from 'examples/etc/' and place them in the bin folder.

**Comment by eakraly** [comment]
Hi @AhmedHumk !
The message tells exactly what the issue is:

**Comment by nums** [comment]
Hello @AhmedHumk,

check the file right of your file, files must be in 0644

**Comment by computersalat** [comment]
Why am I getting this ?:
```
0: (563): WARNING: cannot find certificate file: /etc/coturn/tls/turn_server_cert.pem (1)
0: (563): WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
0: (563): WARNING: cannot find private key file: /etc/coturn/tls/turn_server_pkey.pem (1)
0: (563): WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
0: (563): INFO: Certificate file found: /etc/coturn/tls/turn_server_cert.pem
0: (563): INFO: Private key file found: /etc/coturn/tls/turn_server_pkey.pem
```
Why does coturn warn about not finding the cert/key ... and later it does find them?
What are the preferred permission/ownership of cert/key when server is running as `coturn:coturn`
What is the meaning of:
```
- certificate file is not set properly
- private key file is not set properly
```
Can you please be a bit more specific on what exactly you want ?
No matter where I place cert/key or what permission/ownership I define ... I am _NOT_ getting rid of those warnings and TLS running.

**Comment by JeanPluzo** [comment]
Hi,

it would be wise for those having problems to post their respective `docker-compose.yml` files (if any) or the command(s) you use to startup coturn.
Since coturn has changed to a docker implementation, these errors might not be from coturn itself but from docker.

Regards,
J.

**Comment by computersalat** [comment]
Why can't coturn read that stuff as _root_ before dropping the privileges to 'coturn' user ?
Other daemons do exactly that.

**Comment by eakraly** [comment]
@computersalat can you pls submit a PR to improve it?

**Comment by computersalat** [comment]
@eakraly 
> @computersalat can you pls submit a PR to improve it?
sorry, I can't. I am not a dev. I am a Sysadmin finding solutions to handle and tweak around those _disablities_

**Comment by raucha** [comment]
> Hello @AhmedHumk,
> 
> check the file right of your file, files must be in 0644

Thank you, your help resolved my issue.

**Comment by zyrakq** [comment]
https://github.com/coturn/coturn/issues/1648
