### ISSUE TITLE
The turn server kept getting stuck

### ISSUE THREAD

**Issue by vipcxj** [coturn/coturn#1143]
I tried everything, and the server kept getting stuck, not reporting errors, but not working and it took me a while to figure that out, because there were no errors in the log, and everything seemed fine except that it was stuck there.
If something wrong happened, where is the errors I can see?

Here is the log output:
```
0: : log file opened: /var/tmp/turn_2023-01-13.log
0: : Config file found: /etc/turnserver.conf
0: : Config file found: /etc/turnserver.conf
0: :
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.2 'dan Eider'
0: :
Max number of open files/sockets allowed for this process: 65535
0: :
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 32500 (approximately)
0: :

==== Show him the instruments, Practical Frost: ====

0: : TLS supported
0: : DTLS supported
0: : DTLS 1.2 supported
0: : TURN/STUN ALPN supported
0: : Third-party authorization (oAuth) supported
0: : GCM (AEAD) supported
0: : OpenSSL compile-time version: OpenSSL 1.0.2k-fips  26 Jan 2017 (0x100020bf)
0: :
0: : SQLite is not supported
0: : Redis is not supported
0: : PostgreSQL is not supported
0: : MySQL is not supported
0: : MongoDB is not supported
0: :
0: : Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: : Domain name:
0: : Default realm: 190.92.221.222:3478
0: : NO EXPLICIT LISTENER ADDRESS(ES) ARE CONFIGURED
0: : ===========Discovering listener addresses: =========
0: : Listener address to use: 127.0.0.1
0: : Listener address to use: 172.16.0.162
0: : Listener address to use: 172.16.0.78
0: : Listener address to use: ::1
0: : =====================================================
0: : Total: 2 'real' addresses discovered
0: : =====================================================
0: : NO EXPLICIT RELAY ADDRESS(ES) ARE CONFIGURED
0: : ===========Discovering relay addresses: =============
0: : Relay address to use: 172.16.0.162
0: : Relay address to use: 172.16.0.78
0: : Relay address to use: ::1
0: : =====================================================
0: : Total: 3 relay addresses discovered
0: : =====================================================
0: : log file opened: /var/tmp/turn_2023-01-13.log
0: : pid file created: /var/run/turnserver.pid
0: : IO method (main listener thread): epoll (with changelist)
```
I try 'lsof -i:3478', nothing output. 
I try `turnutils_uclient -v -u admin -w 123456 127.0.0.1` and `turnutils_uclient -v -u admin -w 123456 190.92.221.222`,
```
0: : IPv4. Connected from: 127.0.0.1:49425
0: : IPv4. Connected from: 127.0.0.1:49425
0: : IPv4. Connected to: 127.0.0.1:3478
0: : IPv4. Connected to: 127.0.0.1:3478
0: : allocate sent
0: : allocate sent
recv: Connection refused
```
At last I found there is no running turn server at all.
I start the server like this `turnserver -v -a -o -r 190.92.221.222:3478`
I can start any number of servers:
```
root     15425     1  0 18:25 ?        00:00:00 turnserver -v -a -o -r 190.92.221.222:3478
root     15443     1  0 18:29 ?        00:00:00 turnserver -v -a -o -r 190.92.221.222:3478
root     15445     1  0 18:29 ?        00:00:00 turnserver -v -a -o -r 190.92.221.222:3478
root     15447     1  0 18:29 ?        00:00:00 turnserver -v -a -o -r 190.92.221.222:3478
root     15449 14480  0 18:29 pts/0    00:00:00 grep --color=auto turnserver
```
This means that the services are not listening on any ports. Or they're stuck
The key is no error output, So there's no clue as to how it happened
Here is the conf:
```
external-ip=190.92.221.222
verbose
lt-cred-mech
user=admin:123456
no-tls
no-dtls
log-file=/var/tmp/turn.log
```
I try a lot of conf file, nothing work.

**Comment by eakraly** [comment]
Hi  @vipcxj !
Sorry you are having issues running turnserver
First idea that comes to mind is firewall setup (iptables/ufw) - maybe it blocks turnserver from using any ports?
Or the user under which turnserver runs has no network access permissions?

**Comment by vipcxj** [comment]
@eakraly I found the issue relate to #686, #697, #683, #868.
The bug seems has been fixed in #684 a year ago at release 4.5.3.
However, there is no 4.5.3 released , there is no 4.5.3 released, there is no 4.5.3 released. The Important things have to be said three times.
So many many people like me have to face this bug which have been fixed one year ago.
Now the workaround is downgrade to  4.5.1.3

**Comment by eakraly** [comment]
@vipcxj glad you found the solution.

**Comment by vipcxj** [comment]
@eakraly So when  4.5.3 is released?

**Comment by eakraly** [comment]
4.5.3 will not be released
We are at 4.6.1 already

**Comment by vipcxj** [comment]
@eakraly However, all tutorials about installing on centos in the internet are using 4.5.2, and all versions after 4.5.2 on GitHub are labeled docker, so this docker version is not only for docker, but also for centos?

**Comment by eakraly** [comment]
@vipcxj coturn source code can be built for multiple supported platforms - docker container is one of the options.

You can always build from source code.
