### ISSUE TITLE
cannot connect to turn server (coturn) with Let's Encrypt SSL/TLS or Zero SSL (ubuntu 22.0)

### ISSUE THREAD

**Issue by mrtnetwork** [coturn/coturn#1146]
I configured the server as below

```Coturn-4.5.1.1 'dan Eider'```
```
tls-listening-port=5349
fingerprint
use-auth-secret
server-name=turn.***.com
realm=turn.****.com
verbose
cert=/etc/coturn/certs/turn.***.com.fullchain.pem
pkey=/etc/coturn/certs/turn.***.com.privkey.pem
dh-file=/etc/coturn/certs/ssl-dhparams.pem
mobility
min-port=49152
max-port=65535

```
Nginx ( the problem is not Nginx because the problem is still alive when I don't use Nginx )

```
stream {
    ...
    ...
    error_log /var/log/nginx/str.error.log;
    upstream turnTls {
        server turn_tls_IP:5349;
    }
    map $ssl_preread_server_name $upstream {
        ....
        ....
        ...
        turn.****.com turnTls;
    }
   
    server {
    
        error_log /var/log/nginx/xxx.err.log;
        listen 443;         
        listen [::]:443;
        proxy_pass $upstream;
        ssl_preread on;
        proxy_buffer_size 10m;
       
    }
}
```

When I access the server with Android phones with ```turns``` protocol like

```
  {
            'urls': ['turns:turn.***.com:443?transport=tcp'],
            'username': $username,
            'credential': $password,
}
```
The server cannot get user credentials, and the server log is as follows

```
7: session 002000000000000001: closed (2nd stage), user <> realm <turn.****.com> origin <>, local ****:5349, remote ***:53712, reason: TLS/TCP socket buffer operation error (callback)

```
As you can see, the user's access ```user <>```  information is empty and I got ```reason: TLS/TCP socket buffer operation error (callback) ```

with [Trickle ICE tools](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) sometimes work (The percentage of healthy connection with ```Zero SSL``` is higher ```than Let's Encrypt```)

```
0.783   Done
0.782   relay   2831610 udp *****   65082   0 | 31519 | 255 turns:turn.***.com:443?transport=tcp    tls
```
Coturn log

```
session 000000000000000025: new, realm=<turn.****.com>, username=<1674486335:user_80_156>, lifetime=600, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2

````
I did the following but the problem was not solved

disable some TlS protocols (related to [this](https://github.com/coturn/coturn/issues/809) page)
```
no-tlsv1
no-tlsv1_1
no-tlsv1_2
no-sslv3
...
```
I copied lets encrypt keys to ```/etc/coturn``` which is chmodded with 600 and owned by ```turnserver:turnserve```

I stopped ```NGINX``` and contacted Turn directly via TLS on port 443

With ```Nginx```, I decrypt in ```server``` block and then transferred it to the Turn server

```

stream {
    server {
        listen 443 ssl;

        ssl_certificate             ... fullchain.pem;
        ssl_certificate_key         ... privkey.pem;
  
        ssl_dhparam                 ... dhparam.pem;
        proxy_ssl                   off;
        proxy_pass                  turn_Ip_NoTLS:3478;
    }
}

```

I tested in many android device with ```ISRG Root X1``` and ```DST Root CA X3```

**Comment by eakraly** [comment]
Hi @MohsenHaydari !

As usual - first thing I recommend is to use latest version of coturn (4.6.1) if possible.
Much easier to assist in this case... 

My initial guess is that you may be having some TLS incompatibility somewhere
- TLS 1.3 (which 4.5.1.1 does not support)
- Nginx persists connections and trying to reuse them (just a random idea)

**Comment by MohsenHaydari** [comment]
> Hi @MohsenHaydari !
> 
> As usual - first thing I recommend is to use latest version of coturn (4.6.1) if possible. Much easier to assist in this case...
> 
> My initial guess is that you may be having some TLS incompatibility somewhere
> 
> * TLS 1.3 (which 4.5.1.1 does not support)
> * Nginx persists connections and trying to reuse them (just a random idea)

Hi, thanks for your answer
coturn 4.6.1 only available for docker? 
I use ubuntu and I can't find this version in any repository

**Comment by eakraly** [comment]
That is correct @MohsenHaydari - we are working on updating coturn for debian/ubuntu.
You can build from source code if that is an option from you

**Comment by eMOHAMAD69** [comment]
Hi @MohsenHaydari !
The same log exist on my syslog and my problem is as second participant join the room, both moderator and the guest lost their connection; stick to the "rejoin now" page and the try to rejoin.

also here is my JVB service : 

JVB 2023-05-30 23:31:46.377 SEVERE: [22] HealthChecker.run#181: Health check failed in PT0.000007S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=**Address discovery through STUN failed**)

I did deploy jitsi-meet on a fresh Ubuntu 22 virtual machine with 16GB RAM and 16 Core CPU so that only 1GB RAM is used by all. everything's fine but participant connection. Have did you move on? 

/

**Comment by KhanhHH** [comment]
Any news on this? Not working for me on 4.6.2-r3

**Comment by eakraly** [comment]
> Any news on this? Not working for me on 4.6.2-r3 

Hi @KhanhHH ! Please post your verbose log (including startup of the turnserver) - this will help debugging the issue.

**Comment by KhanhHH** [comment]
> > Any news on this? Not working for me on 4.6.2-r3
> 
> Hi @KhanhHH ! Please post your verbose log (including startup of the turnserver) - this will help debugging the issue.

Just found out the problem is not by Coturn, it caused by cloud blocked 443/udp protocol.
