### ISSUE TITLE
Messages on Google Groups

### ISSUE THREAD

**Issue by Neustradamus** [coturn/coturn#1148]
I see that there are messages on the TURN Server (Open-Source project) Google Groups:
- https://groups.google.com/g/turn-server-project-rfc5766-turn-server

Examples:
- https://groups.google.com/g/turn-server-project-rfc5766-turn-server/c/U8L6XragJVA
- https://groups.google.com/g/turn-server-project-rfc5766-turn-server/c/eqs36wNNqL8
- ...

**Comment by eakraly** [comment]
Well, Google Group is about community mostly - people helping each other (at least in my view - we should define it @ggarber )
Maintainers should and will respond but some questions hardly related to coturn itself
In any case - thank you for pointing out. We should definitely monitor GG as well
