### ISSUE TITLE
Anycast support

### ISSUE THREAD

**Issue by AnshulMalik** [coturn/coturn#1149]
Hi, not sure where to ask this, but can `coturn` instances be deployed to multiple regions with one anycast IP?

If yes, would like to know how. And if not, how can this be supported and how hard would it be to do?.

**Comment by eakraly** [comment]
Interesting questions @AnshulMalik  - what is your goal? What are you trying to achieve?

(btw the answer is - no idea, but I think it is very possible)

**Comment by AnshulMalik** [comment]
I am trying to deploy turns in multiple regions so that I have a turn server close to peer across the world. But I can't give this big list to each peer, I'd ideally want to give all of them one IP address which would connect them to nearest turn.

So, I was thinking anycast can help here, but coturn being stateful, if a turn instance dies, and traffic gets routed to another turn instance, it won't know about the allocations happened on the previous instance, so not sure how that would work.

https://groups.google.com/d/msgid/turn-server-project-rfc5766-turn-server/28b8c9c1-1779-48f7-aac6-c1694846dcbcn%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by eakraly** [comment]
Let's try to break it down:
 - Your goal of using anycast as a global routing makes sense. I think should be doable but I cannot help you with practical details. As alternative, you can use DNS ge-routing to nearest location (geo-routing using AWS Route53 for example) so all clients get the same turn URL but when resolving it they get different regions and also different IPs inside the same region which allows scaling out turn deployment in a region
 - When turn instance dies all existing sessions will be closed and clients will lose connection - it should be detected on the client side and connection "re-negotiated" (which will allocate new turn server)

**Comment by AnshulMalik** [comment]
Thanks for the help @eakraly. This will certainly acheive the results I desire.
