### ISSUE TITLE
Tag new version?

### ISSUE THREAD

**Issue by vvug** [coturn/coturn#115]
Hi,

as we had a couple of non trivial bug fixed since 4.5.0.6, is it possible for you to tag a new minor release, so to favor inclusion in downstream distributions?

Thank you

**Comment by mom040267** [comment]
We will try to do that soon, in a few days.

Oleg

**Comment by mom040267** [comment]
And by the way, 4.0.5.6 is not officially released yet, so it will be
4.0.5.6 release.

**Comment by mom040267** [comment]
I released 4.5.0.6
