### ISSUE TITLE
No IPv6 relay-candidates unless `--allocation-default-address-family=keep` is specified

### ISSUE THREAD

**Issue by marrobHD** [coturn/coturn#1150]
I noticed, that there are no IPv6 relay-candidates available, unless `--allocation-default-address-family=keep` is specified.
Also STUN (V4/V6) doesn't seem to work.

- Coturn Version Coturn-4.6.1 'Gorst'

Config:

```
listening-port=3478
tls-listening-port=5349

alt-listening-port=0
alt-tls-listening-port=0

listening-ip=MY_IPv6
listening-ip=192.168.116.15
external-ip=MY_EXT_IPv4/192.168.116.15

min-port=64000
max-port=65535

verbose

lt-cred-mech
use-auth-secret

static-auth-secret=MY_AUTH_SECRET
realm=MY_REALM
no-tcp-relay

cert=/etc/coturn/certs/my.cer
pkey=/etc/coturn/certs/my.key

cipher-list="ECDH+AESGCM:ECDH+CHACHA20:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS"

syslog
no-software-attribute
no-multicast-peers

allowed-peer-ip=192.168.116.15
allowed-peer-ip=MY_IPv6

proc-user=turnserver

proc-group=turnserver

no-cli
no-tlsv1
no-tlsv1_1
no-tlsv1_2
```

**Comment by eakraly** [comment]
Hi @marrobHD 
According to documentation of the flag:
```
# TURN server allocates address family according TURN client requested address family.
# If address family not requested explicitly by the client, then it falls back to this default.
# The standard RFC explicitly define that this default must be IPv4, 
# so use other option values with care! 
# Possible values: "ipv4" or "ipv6" or "keep" 
# "keep" sets the allocation default address family according to 
# the TURN client allocation request connection address family.
```

Which means following:
- Client uses IPv6
- Client requests allocation but does NOT request IPv6 address family explicitly
- Default is IPv4 according to RFC
- turnserver returns IPv4
- Flag `--allocation-default-address-family=keep` uses allocation request's address family as the allocation default address family (IPv6 in this case)

To sum it up: the client must use either `REQUESTED-ADDRESS-FAMILY` or `ADDITIONAL-ADDRESS-FAMILY` to get IPv6 allocation (either specifically IPv6 or both IPv6 and IPv4).

Here is the relevant section in RFC https://www.rfc-editor.org/rfc/rfc8656#section-7.2 (see bullet 7 last sentence). I do not what was the reason to do that but it is there.

**Comment by eakraly** [comment]
Unrelated question: why do you have following in your config - is it to allow turn connection to itself?
```
allowed-peer-ip=192.168.116.15
allowed-peer-ip=MY_IPv6
```

**Comment by marrobHD** [comment]
> Unrelated question: why do you have following in your config - is it to allow turn connection to itself?
> ```
> allowed-peer-ip=192.168.116.15
> allowed-peer-ip=MY_IPv6
> ```
> 

Yes👀

**Comment by eakraly** [comment]
Back to your original question @marrobHD - it looks like the behavior is by design.
Does it address your question?

**Comment by marrobHD** [comment]
> Back to your original question @marrobHD - it looks like the behavior is by design.
> Does it address your question?

Yeah, thanks!
