### ISSUE TITLE
Question- How to enable DTLS in coturn 

### ISSUE THREAD

**Issue by Govind10g** [coturn/coturn#1151]
Hi Team,

Currently we are using TLS encryption enabled using port 443 along with the certificates details in the turn configuration file. 
**We are not using UDP port in our configuration.** 

So wanted to know How to enable the DTLS in coturn configuration ? 

@eakraly @ggarber

**Comment by eakraly** [comment]
Hi @Govind10g 

DTLS uses the same certificate - so you should be fine there.
In terms of protocol itself
- Make sure you have `no-dtls=false` or commented out (this is default)
- Not sure if you must enable UDP for DTLS to work...

**Comment by Govind10g** [comment]
@eakraly ,

Thanks for the reply ...Yes even I had this doubt without UDP how we can use DTLS. :|
