### ISSUE TITLE
Feature Request: Making coturn stats permanent for Prometheus export 

### ISSUE THREAD

**Issue by batusekerci** [coturn/coturn#1153]
Hi everyone, we are using Prometheus metrics for acquiring the usage stats. But as you know, whenever the coturn service is restarted, metrics will be erased. We could not found a way about saving each usage of user linearly ( leaving Redis aside ) since usages are reset. 

As a request, maybe there can be a field in the config file and metrics can be permanent, so if coturn or machine is restarted somehow, metrics will be continue to append.

Thanks.

**Comment by eakraly** [comment]
Hi @batusekerci 

Your question is not about coturn but prometheus: it should persist the metrics scraped from the turnserver.
There is absolutely no issue with current metrics that prevents from scraping and storing the history (by prometheus) which then can be displayed (in grafana for example).

**Comment by batusekerci** [comment]
We changed our mind since keeping and parsing the whole metric data will create bad situations. So, we tried to use Prometheus HTTP API but always get `Bad request`. Why is the only working endpoints **/metrics** and **/** ? 

Is there any way to reset or remove prometheus metrics?

**Comment by eakraly** [comment]
You can disable prometheus metrics interface by not passing `--prometheus` to turnserver

There is only one interface to metrics and that is `/metrics` - it returns a formatted text that describes all the metrics turnserver gathered. I'm not sure how you get `Bad request` - can you please provide more detailed information so I can assist you? Please provide turnserver config/command line, http request (curl request) you use to pull metrics for test, logs etc.

**Comment by batusekerci** [comment]
Okay, I understand that there is no different way. We have to use just `/metrics` endpoint and we cannot modify the monitoring settings for prometheus on CoTurn. Thanks!

**Comment by jbg** [comment]
> So, we tried to use Prometheus HTTP API but always get Bad request. Why is the only working endpoints /metrics and / ?

You're supposed to run a separate Prometheus server which scrapes your CoTURN servers. The Prometheus HTTP API is provided by Prometheus, not by the individual monitored workloads like CoTURN.
