### ISSUE TITLE
What is the appropriate configuration for VPN TURN connectivity?

### ISSUE THREAD

**Issue by tearfulnumpty** [coturn/coturn#1155]
I'm currently using coturn for use with a Matrix (synapse) turn server for VOIP and other webRTC related things.  

On the coturn server, I am also hosting a VPN server.  I'm trying to configure things so that voice calls through Matrix will work in all possible configurations.  

___

Let me elaborate:  Let's say I have `device A` and `device B`, and I have `home network` and `vpn network`.  `Home network` is in the `192.168.1.1` subnet, and `vpn network` is in `10.10.10.1`.  My coturn server is hosted on `home network`, and my `vpn network` is running on the same machine/OS.  Matrix/Synapse as well.  Let's also make up `external network` as anything that isn't on either of the other networks.  

*In the past*, I have experienced issues with `device A` speaking to `device B` if both devices are on the same `home network`.  If one device is on `home network` and the other is on `external network`, it'd be fine, or if both were on `external network`, things would be fine.  

Today, I tried to reconfigure coturn to avoid the above problem, but it seems like that isn't an issue anymore for one reason or another.  However, I do have another issue, and it relates to the `vpn network`.  

___

For my two devices `device A` and `device B`, they demonstrate some interesting behavior with relation to the VPN.  It took a bit of troubleshooting, but eventually I discovered that there's a setting in my VPN (wireguard) for kernel level support, and enabling this setting as opposed to running the VPN in userspace was the cause of my problems.  Any time one of my devices, either `device A` *or* `device B`, was connected to the VPN with kernel implementation, I would get a 403 unauthorized error message in coturn's logs, and the call would fail to connect.  

Here's some logs, 787 being relevant, with the other lines for context:

```
781: : IPv4. tcp or tls connected to: externalip:49331
781: : session 003000000000000001: realm <domain_name> user <>: incoming packet message processed, error 401: Unauthorized
781: : IPv4. Local relay addr: 192.168.1.2:50134
781: : session 003000000000000001: new, realm=<domain_name>, username=<user_nid:@user:matrixurl>, lifetime=600
781: : session 003000000000000001: realm <domain_name> user <user_nid:@user:matrixurl>: incoming packet ALLOCATE processed, success
787: : session 003000000000000001: realm <domain_name> user <user_nid:@user:matrixurl>: incoming packet CREATE_PERMISSION processed, error 403: Forbidden IP
787: : session 003000000000000001: realm <domain_name> user <user_nid:@user:matrixurl>: incoming packet message processed, error 403: Forbidden IP
791: : session 003000000000000001: refreshed, realm=<domain_name>, username=<user_nid:@user:matrixurl>, lifetime=0
```

So obviously, "the fix" is to just use the userspace VPN implementation, right?  Well, that isn't a great long term solution, as it obviously is worse for the performance of my devices, and will be a larger power drain, thus lowering battery life.  

Here's my coturn config:

```
response-origin-only-with-rfc5780

no-rfc5780

no-stun-backward-compatibility

no-tlsv1
no-tlsv1_1
no-tlsv1_2

use-auth-secret
static-auth-secret=somesecret
realm=domain_name
log-file=/var/log/turnserver/turn.log
pidfile=/run/turnserver/turnserver.pid
cli-password=somerandompw


allowed-peer-ip=192.168.1.2
allowed-peer-ip=10.10.10.1
```

I've also experimented a lot with the following config settings:

```
external-ip=external_ip/192.168.1.2
external-ip=external_ip/10.10.10.1

relay-ip=192.168.1.2
relay-ip=10.10.10.1
```

But I couldn't get anything successful between them.  

I've tried allowing multicast, I've tried allowing a range of peer IP's, etc with no change.  Enabling loopback however *does* remove the 403 errors, but the call still won't connect.  

What can I do to easily identify what specifically changes between the non-kernel and kernel level VPN usage?  Why does one work while the other doesn't?  Is there anything I can do to my configuration to make this work better?  What other information can I provide?  

Thanks.

**Comment by eakraly** [comment]
Hi @tearfulnumpty 
coturn blocks localhost by default - that is why I guess you needed to enable loopback for it to work in kernel mode. This is a security feature to prevent establishing connections to other services running on the same IP.

Please run turnserver with verbose logs - which may help you to troubleshoot the issue.
Also, please use latest version of coturn (4.6.1 or master)

**Comment by eakraly** [comment]
No comments from OP - closing
