### ISSUE TITLE
can not find libcrypto.so

### ISSUE THREAD

**Issue by zwfengineer** [coturn/coturn#1157]
machine:Linux userver 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Bug:
turnserver: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

**Comment by zwfengineer** [comment]
I forget clean the envirment

**Comment by eakraly** [comment]
Hi @zwfengineer !
Looks like you found the problem - mind closing the issue then?
