### ISSUE TITLE
STUN SERVER 

### ISSUE THREAD

**Issue by webleb** [coturn/coturn#1158]
Hello,
I am testing STUN between 2 different internet connection behind 2 routers.
Internet A and internet B when A is before B the connection is established and video call start successfully but when internet/router B start first the connection never established.
maybe because the port is closed after few seconds on B so stun maybe need to update the ip address/port for all users every time new user connect.
or maybe we can use upnp.
any solution please advice.
Thanks 
@jbg @tony2001 @byronclark @dbrgn

**Comment by webleb** [comment]
please send me stun url for testing

**Comment by eakraly** [comment]
Hi @webleb 
There is not enough information to help you. One reason it could happen is if you have a combination of NATs that requires TURN (STUN is not enough). See some info here https://doc-kurento.readthedocs.io/en/latest/knowledge/nat.html#nat-traversal
