### ISSUE TITLE
BUG - IPv6, System crash turnserver-3.2.5.4-CentOS7-x86_64

### ISSUE THREAD

**Issue by shamun** [coturn/coturn#116]
FYI. 

Recently i just noticed when i enabled IPv6 on my CentOS 3.10.0-123.8.1.el7.x86_64, while running turn serer: turnserver-3.2.5.4-CentOS7-x86_64.tar.gz system wash crashing.

The moment i removed IPv6 and its again not crashing. Is it normal that version 3.2.5.4 was incompatible for IPv6 or some kernel conflict?

**Comment by mom040267** [comment]
That is not a known bug. We did test it with IPv6, of course.
Try a newer version (4x), we are not fixing bugs in 3.x versions anymore.
