### ISSUE TITLE
Debian docker image 4.6.1-r2 does not include prometheus stun metrics

### ISSUE THREAD

**Issue by inaqui-signal** [coturn/coturn#1164]
Can someone confirm that they see `stun*` prometheus metrics and the type label for `turn_total_allocations` when they run `curl http://localhost:9641/metrics` using the `coturn/coturn:4.6.1-r2-debian` docker image. I only see `turn*` and `process*` related metrics and no type label for `turn_total_allocations`.

Could the docker image have been mistakenly built with an older release tag or commit? I very well could have borked up my local environment but afaict i'm pulling the right image.

**Comment by eakraly** [comment]
Hi @inaqui-signal !
4.6.1-r2 is built off latest master so should contain stun metrics
Did you make a STUN request to the server before querying the prometheus interface? IIRC the library does not generate a metric in the output if it was not updated even once

**Comment by inaqui-signal** [comment]
If I build the `docker/coturn/debian/Dockerfile` image from master locally I do see the metrics appear even without any stun requests being made.

```
docker build -f docker/coturn/debian/Dockerfile -t a
docker run a turnserver --prometheus
```

```
...
# HELP stun_binding_request Incoming STUN Binding requests
# TYPE stun_binding_request counter

# HELP stun_binding_response Outgoing STUN Binding responses
# TYPE stun_binding_response counter

# HELP turn_traffic_rcvp Represents finished sessions received packets
# TYPE turn_traffic_rcvp counter

# HELP stun_binding_error STUN Binding errors
# TYPE stun_binding_error counter
...
```

I noticed that tag `4.6.1` is on December 3rd but the `docker/4.6.1*` tags are advancing. Maybe the Debian docker image is being built using the `4.6.1` tag?

If you want to confirm what i'm seeing you can try this...

```
ARG coturn_ver=4.6.1-r2

FROM coturn/coturn:${coturn_ver}-debian AS runtime

USER root:root

# Update system packages.
RUN mkdir -p /var/lib/apt/lists/partial && apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y --no-install-recommends --no-install-suggests ca-certificates \
 && update-ca-certificates \
 # Install curl for ip detection
 && apt-get install -y --no-install-recommends --no-install-suggests curl \
 # install jq for parsing gcp metadata
 && apt-get install -y --no-install-recommends --no-install-suggests jq \
 # Install coturn
 && mkdir /etc/turn \
 && chown -R nobody:nogroup /etc/turn \
 # Cleanup unnecessary stuff.
 && rm -rf /var/lib/apt/lists/*
```

Build the image  and then run the image `turnserver --prometheus` and run `docker exec $container_id curl http://localhost:9641/metrics` from another shell.

**Comment by tyranron** [comment]
@eakraly @inaqui-signal 

> Maybe the Debian docker image is being built using the `4.6.1` tag?

Yes, exactly! Otherwise, it wouldn't have `4.6.1` version included in the tag. We cannot name Docker image under `4.6.1` version, but build something else inside.

Latest `master` could be found under [`edge-debian`/`edge-alpine` Docker tags](https://github.com/coturn/coturn/tree/cc2560b06acd2d64e0660131ac003772508c190d/docker/coturn#edge-dist).
