### ISSUE TITLE
TURN/TLS request crashes listeners

### ISSUE THREAD

**Issue by thehunmonkgroup** [coturn/coturn#117]
Running 4.5.0.6 on Debian Jessie (via the unstable package available at https://packages.debian.org/sid/coturn)

When I connect via the turns: protocol (using https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/), it appears the listeners on all ports crash (verified by running ```netstat -nl | grep [port]``` both before and after making the turns: call). No further STUN/TURN requests work after this crash, until the service is restarted.

It doesn't appear that the coturn process itself crashes.

I turned on the ```Verbose``` flag in ```/etc/turnserver.conf```, but the only output I get before the listeners crash is this:

```
176: IPv4. tcp or tls connected to: XXX.XXX.XXX.XXX:49230
```

I know that's not much debugging info to go on, happy to collect more if I get instructions on how!

**Comment by thehunmonkgroup** [comment]
I'll also note that I tried connecting via the openssl client, and got this:

```
openssl s_client -connect [ip:port]
CONNECTED(00000003)
write:errno=54
```

...and observed the same behavior

**Comment by mom040267** [comment]
Sounds like SSL libraries mismatch.

I am not sure that that package is supposed to work with Jessie. The
package was build for Sid. It may have different packages than Jessie.

I'd suggest building coturn from scratch, or use Ubuntu with their 'ported'
package.

Oleg

**Comment by thehunmonkgroup** [comment]
Yup, spot on. I built openssl/libevent/coturn from scratch, and it works perfectly now, thanks!
