### ISSUE TITLE
TLS 1.3 support clarification

### ISSUE THREAD

**Issue by brentmedicom** [coturn/coturn#1171]
Hello,

I was hoping to clarify whether TLS 1.3 support requires an unreleased version of coturn (4.7.0?). I am currently unable to get coturn to use TLS 1.3 in version 4.6.1 and looking at [https://github.com/coturn/coturn/blob/master/ChangeLog](url), it appears possible that TLS 1.3 work is associated with the unreleased version; however, I may be interpreting the changelog incorrectly as TLS 1.3 support is listed in the readme [https://github.com/coturn/coturn/blob/master/README.md](url).

Would it be possible to clarify if TLS 1.3 support requires an unreleased version of coturn? If it does, is there any guidance on a release timeline beyond that minor releases (4.x.0) are generally 2-3 months apart?

Thanks!

**Comment by eakraly** [comment]
Hi @brentmedicom 
TLS1.3 is supported on the latest master
If you use docker version then latest docker/4.6.1-r2 supports it

Next version release timeline is being discussed. Thanks!

**Comment by brentmedicom** [comment]
Thanks for the insight, @eakraly!

I am using the docker version with the alpine image, but I can't seem to leverage TLS1.3 with 4.6.1-r2. Confusingly, if I pull the edge image, TLS1.3 works.

**Comment by eakraly** [comment]
right - alpine based docker was blocked on latest openssl.
we are working on releasing 4.6.2 which will address the issue.

**Comment by brentmedicom** [comment]
Understood. Appreciate the additional clarification! Looking forward to 4.6.2.
