### ISSUE TITLE
server coturn doesn't work with synapse matrix

### ISSUE THREAD

**Issue by nekooee** [coturn/coturn#1172]
I installed and checked all configs in the cotuner and synapse. but this is not work. I test it with a tester and you can see the result below:

![image](https://user-images.githubusercontent.com/6003803/225478972-03b21749-b507-454e-9c29-0ff468aedd04.png)

please help me.

**Comment by crawford** [comment]
Try the last bullet point on https://matrix-org.github.io/synapse/develop/turn-howto.html#troubleshooting, specifically the "coturn only" recommendation. This helped me figure out that my hosting provider had a firewall in front of my virtual machine that was interfering.

**Comment by nekooee** [comment]
Thank you. my problem is solved. The problem was with the firewall.
