### ISSUE TITLE
How correctly interpreter traffic statistics 

### ISSUE THREAD

**Issue by tomzini** [coturn/coturn#1175]
Hi all,
I'm using coturn on Ubuntu 22.04.1 LTS, installed using official package for this distro. 
In my test I need to collects some traffic statistics using pub/sub via Redis. What I noticed is a discrepance in information returned by Redis with the same traffic information shown using the CLI (with ps command). This an example where peer on session  000000000000000002 send traffic to peer in session 001000000000000001 (this peer only a receiver)

From Redis (or server log. Redis and log returns same data):

533: : session 001000000000000001: usage: realm=<turn.nextworks.it>, username=<user>, rp=507, rb=33520, sp=1544, sb=515506
533: : session 001000000000000001: peer usage: realm=<turn.nextworks.it>, username=<user>, rp=1541, rb=509102, sp=504, sb=31172
533: : session 000000000000000002: usage: realm=<turn.nextworks.it>, username=<user>, rp=1544, rb=518876, sp=505, sb=33310
533: : session 000000000000000002: peer usage: realm=<turn.nextworks.it>, username=<user>, rp=504, rb=31214, sp=1543, sb=510283

The same information using "ps" command from CLI

> ps

    1) id=000000000000000002, user <user>:
      realm: turn.xxxxxx.it
      started 451 secs ago
      expiring in 450 secs
      client protocol UDP, relay protocol UDP
      client addr xxxxxx, server addr xxxxxx
      relay addr xxxxxx:51751
      fingerprints enforced: ON
      mobile: OFF
      usage: rp=14037, rb=5187448, sp=4405, sb=292015
       rate: r=11709, s=659, total=12368 (bytes per sec)
      peers:
          10.0.0.7
          10.0.0.7:57667
          10.0.0.7:56044

    2) id=001000000000000001, user <user>:
      realm: turn.xxxxxx.it
      started 453 secs ago
      expiring in 147 secs
      client protocol UDP, relay protocol UDP
      client addr xxxxxx, server addr xxxxxx
      relay addr xxxxxx:57667
      fingerprints enforced: OFF
      mobile: OFF
      usage: rp=4431, rb=296053, sp=14008, sb=5157406
       rate: r=665, s=11589, total=12254 (bytes per sec)
    
All usage information (bytes and packets) differ a lot from Redis data.

Moreover, data returned from CLI result more similar to what I measured at the receiver client level.

The question is, is there something I'm interpreting incorrectly? What is the correct way to read in "pseudo-realtime" traffic metrics (without use phrometeus) ?

Thanks

**Comment by eakraly** [comment]
Hi @tomzini 

IIRC, usage data is updated after the connection ends (in redis and prometheus)
I suppose (without looking into code) that telnet provides more real-time data because it queries active sessions
