### ISSUE TITLE
Containarized CoTurn server is not reachable neither by Trickle Ice nor Telnet

### ISSUE THREAD

**Issue by KarthikHebbarMN** [coturn/coturn#1179]
Steps followed 

- Launched a VM in GCP
- Created a test firewall rule with "Allow All" so all ports are listened to
- Tested tlenet against another signaling service (unreals) port 8888 easily connects
- Ran the following docker commands in order (after failure to connect at each iteration)

**Iteration 1**
`docker run  -d --network=host --rm  --entrypoint "turnserver" coturn/coturn -p 3478 -X 35.223.194.221 -L 127.0.0.1 --no-cli --no-tls --no-dtls --pidfile /var/run/turnserver.pid -f -a -v -n -u 'PixelStreamingUser:AnotherTURNintheroad'` 

Got
 `Cannot create pid file: /var/run/turnserver.pid: Permission denied
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported ....`

`<html>
<body>

Time | Type | Foundation | Protocol | Address | Port | Priority | URL (if present) | relayProtocol (if present)
-- | -- | -- | -- | -- | -- | -- | -- | --
0.002 | host | 1405439333 | udp | 6dfd0aa8-71f6-426f-9cae-639eb90c02e2.local | 51202 | 126 \| 30 \| 255 |   |  
0.089 | srflx | 1629647231 | udp | 49.206.3.210 | 32082 | 100 \| 30 \| 255 | stun:stun1.l.google.com:19302 |  
39.958 | Done

Note: errors from onicecandidateerror above are not neccessarily fatal. For example an IPv6 DNS lookup may fail but relay candidates can still be gathered via IPv4.
The server stun:35.223.194.221:3478 returned an error with code=701:
STUN server address is incompatible.
The server stun:stun1.l.google.com:19302 returned an error with code=701:
STUN host lookup received error.
The server stun:35.223.194.221:3478 returned an error with code=701:
STUN binding request timed out.
The server turn:35.223.194.221:3478?transport=udp returned an error with code=701:
TURN allocate request timed out.

</body>
</html>`

**Iteration 2:** 
`docker run  -d --network=host --rm coturn/coturn -p 3478 -X 35.223.194.221 -L 127.0.0.1 --no-cli --no-tls --no-dtls  -v -n -u 'PixelStreamingUser:AnotherTURNintheroad'` (Removed -f and -a as regards to [ThisIssue](https://github.com/coturn/coturn/issues/683#issuecomment-759084451) )

Results are exact same. 
 `Cannot create pid file: /var/run/turnserver.pid: Permission denied
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported ....`

I considered sctp and even though its mentioned here #492 to be benign, I spent some time figuring out sctp to enable in gcp VMs. 

**Iteration n: (Got desprate)**
`docker run -d --network host coturn/coturn --listening-port=3479 --min-port=49160 --max-port=42000 `

Results are same.

Telnet
>telnet 35.223.194.221 3478
Connecting To 35.223.194.221...Could not open connection to the host, on port 3478: Connect failed

>telnet 35.223.194.221 3478
Connecting To 35.223.194.221...Could not open connection to the host, on port 3478: Connect failed

>telnet 35.223.194.221 3478
Connecting To 35.223.194.221...Could not open connection to the host, on port 3478: Connect failed

>telnet 35.223.194.221 3478
Connecting To 35.223.194.221...Could not open connection to the host, on port 3478: Connect failed

>telnet 35.223.194.221 3478
Connecting To 35.223.194.221...Could not open connection to the host, on port 3478: Connect failed

>telnet 35.223.194.221 3479
Connecting To 35.223.194.221...Could not open connection to the host, on port 3479: Connect failed

One more issue was if I ran the command listed 
`docker run -d -p 3478:3478 -p 3478:3478/udp -p 5349:5349 -p 5349:5349/udp -p 49152-65535:49152-65535/udp coturn/coturn`
Entire VM froze up. Not sure if this is because of memory limitation in the VM or not.

Looking forward to any help, been hacking at this issue for over 8 hours. 
Many Thanks

**Comment by tyranron** [comment]
@KarthikHebbarMN could you show full Coturn logs after running this command?

> **Iteration n: (Got desprate)**
> `docker run -d --network host coturn/coturn --listening-port=3479 --min-port=49160 --max-port=42000 `

**Comment by KarthikHebbarMN** [comment]
Sure 

>  karthik_hebbar@instance-2 ~ $ docker run -it --network host coturn/coturn --listening-port=3479 --min-port=4916 --max-port=42000 
> 0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
> 0: : log file opened: /var/tmp/turn_1_2023-03-29.log
> 0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
> 0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
> 0: : 
> RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
> Version Coturn-4.6.1 'Gorst'
> 0: : 
> Max number of open files/sockets allowed for this process: 1048576
> 0: : 
> Due to the open files/sockets limitation,
> max supported number of TURN Sessions possible is: 524000 (approximately)
> 0: : 
> 
> ==== Show him the instruments, Practical Frost: ====
> 
> 0: : TLS supported
> 0: : DTLS supported
> 0: : DTLS 1.2 supported
> 0: : TURN/STUN ALPN supported
> 0: : Third-party authorization (oAuth) supported
> 0: : GCM (AEAD) supported
> 0: : OpenSSL compile-time version: OpenSSL 1.1.1n  15 Mar 2022 (0x101010ef)
> 0: : 
> 0: : SQLite supported, default database location is /var/lib/coturn/turndb
> 0: : Redis supported
> 0: : PostgreSQL supported
> 0: : MySQL supported
> 0: : MongoDB supported
> 0: : 
> 0: : Default Net Engine version: 3 (UDP thread per CPU core)
> 
> =====================================================
> 
> 0: : Domain name: 
> 0: : Default realm: 
> 0: : ERROR: 
> CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
> 0: : WARNING: cannot find certificate file: turn_server_cert.pem (1)
> 0: : WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
> 0: : WARNING: cannot find private key file: turn_server_pkey.pem (1)
> 0: : WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
> 0: : NO EXPLICIT LISTENER ADDRESS(ES) ARE CONFIGURED
> 0: : ===========Discovering listener addresses: =========
> 0: : Listener address to use: 127.0.0.1
> 0: : Listener address to use: 10.128.0.3
> 0: : Listener address to use: 172.18.0.1
> 0: : Listener address to use: 172.17.0.1
> 0: : Listener address to use: ::1
> 0: : =====================================================
> 0: : Total: 3 'real' addresses discovered
> 0: : =====================================================
> 0: : NO EXPLICIT RELAY ADDRESS(ES) ARE CONFIGURED
> 0: : ===========Discovering relay addresses: =============
> 0: : Relay address to use: 10.128.0.3
> 0: : Relay address to use: 172.18.0.1
> 0: : Relay address to use: 172.17.0.1
> 0: : Relay address to use: ::1
> 0: : =====================================================
> 0: : Total: 4 relay addresses discovered
> 0: : =====================================================
> Cannot create pid file: /var/run/turnserver.pid: Permission denied
> 0: : Cannot create pid file: /var/run/turnserver.pid
> 0: : pid file created: /var/tmp/turnserver.pid
> 0: : IO method (main listener thread): epoll (with changelist)
> 0: : Wait for relay ports initialization...
> 0: :   relay 10.128.0.3 initialization...
> 0: :   relay 10.128.0.3 initialization done
> 0: :   relay 172.18.0.1 initialization...
> 0: :   relay 172.18.0.1 initialization done
> 0: :   relay 172.17.0.1 initialization...
> 0: :   relay 172.17.0.1 initialization done
> 0: :   relay ::1 initialization...
> 0: :   relay ::1 initialization done
> 0: : Relay ports initialization done
> 0: : IO method (general relay thread): epoll (with changelist)
> 0: : turn server id=0 created
> 0: : IO method (general relay thread): epoll (with changelist)
> 0: : turn server id=1 created
> socket: Protocol not supported
> 0: : Total General servers: 2
> 0: : IO method (auth thread): epoll (with changelist)
> 0: : IO method (auth thread): epoll (with changelist)
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> 0: : IO method (admin thread): epoll (with changelist)
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> socket: Protocol not supported
> 0: : SQLite DB connection success: /var/lib/coturn/turndb
> 0: : Prom

**Comment by eakraly** [comment]
@KarthikHebbarMN I see 2 issues:
1. I see is `--min-port=49160 --max-port=42000` which means min-port > max-port. You probably wanted 41960-42000 range

2. Pay attention to the interfaces you can use. This is what coturn sees (from the log):
```
0: : Listener address to use: 127.0.0.1
0: : Listener address to use: 10.128.0.3
0: : Listener address to use: 172.18.0.1
0: : Listener address to use: 172.17.0.1
0: : Listener address to use: ::1
```
You cannot use localhost (127.0.0.1 or ::1) for listening IP (your first command has `-L 127.0.0.1`).

**Comment by eakraly** [comment]
@KarthikHebbarMN have not heard from you for a long time - I'm closing the issue. If you still experience an issue please post.

**Comment by KarthikHebbarMN** [comment]
Hey @eakraly,
Thank you so much for taking time out of your valuable time and helping me with this. I had to put the project on hold as I had traveled off share for work. Will try out this week with a few arguments and follow the guides you have told me. 

Thanks

**Comment by MukalDadhwal** [comment]
hey do this on the vm and try trickling the service again

`sudo ufw allow 3478`
