### ISSUE TITLE
how provide local and public ip manually to webRTC app instead using signal and stun and turn server

### ISSUE THREAD

**Issue by webleb** [coturn/coturn#1186]
Hello,
is there any solution that allow me to provide the info needed for any webRTC app to Establish peer to peer connection manually instead of using Stun and Turn and Signal server such local and public ip.
@jbg @tony2001 @byronclark @dbrgn @NeoCat @eakraly

**Comment by fippo** [comment]
There is not. While you can find out your public ip, you can not find out how a NAT device maps the random port used by WebRTC.

**Comment by ggarber** [comment]
Yep, what fippo said.

For some very specific use cases maybe you can map IPs and ports manually in the NAT router, but you still need to get the port selected by one PeerConnection and pass it somehow to the other side.

Anyway this would be more a WebRTC question and a coturn issue so i'm closing it for now.   Hope that's ok.

**Comment by webleb** [comment]
@ggarber @fippo 
maybe we can configure webRTC to open specific port instead of random one.
if someone are able to do that please add me skype live:inf.dealer

**Comment by jbg** [comment]
Even if it does, you still don't know what port the NAT device is going to map it to.

**Comment by webleb** [comment]
no solution in javascript ?

**Comment by webleb** [comment]
so this is going to be possible only when users are using mobile data where there is no Nat i think

**Comment by jbg** [comment]
There is no way, looking from the inside of a network with a NAT device at the edge, to know, in general, what external port a NAT device is going to map your port to. That applies regardless of which programming language you are using. This is why STUN & TURN exists.

Mobile data often involves NAT nowadays too.

**Comment by webleb** [comment]
NAT is involved when we are using routers only.
i am trying to connect 2 peers without using signal and stun and turn server.
i am open to any solution that can provide the info needed for connection like ip which dont involve a server.(even manually every user can share his ip .... with others.)

**Comment by jbg** [comment]
If both peers have public (globally-routable) IPs, you just need them to share their IPs with each other. But even on mobile data, non-globally-routable IPs are often being given out nowadays (so there is a NAT device in the mobile provider network). There is no general solution that doesn't involve at least a STUN server.

**Comment by webleb** [comment]
OK. how i can share the ip manually with webRTC instead using signal and stun.
is there a solution that can work for me on any webRTC framework i could use?

**Comment by fippo** [comment]
Even if you share IPs using carrier pigeons you will still need to exchange the ICE username fragment and passwords as well as the DTLS fingerprints. This was a very specific design choice in WebRTC for security reasons.

**Comment by webleb** [comment]
I want a STUN-Like script in javascript (not node.js) that can read the ips from file.
does anyone can provide such solution.

**Comment by webleb** [comment]
@jbg @fippo @tony2001 
can i download STUN server locally on users mobiles?

**Comment by jbg** [comment]
Sure, but it won't help you to discover the mapped port on the NAT since the STUN server is also behind it.

**Comment by webleb** [comment]
@jbg Ok. but cant also discover the other peers if public ips are provided or signal server is also installed locally?
