### ISSUE TITLE
Only a small number of logs appear to be get logged with Coturn 4.6.2 when syslog option is enabled

### ISSUE THREAD

**Issue by brentmedicom** [coturn/coturn#1188]
Environment information:

- arm64-based Linux
- Coturn 4.6.2 (alpine tag) running using Docker
- PostgreSQL 15 running using Docker

Relevant Coturn configuration options:

- verbose
- syslog

Hi, I upgraded a server to use the latest 4.6.2 release and noticed that I only seem to be getting a few logs from coturn when it is started but no subsequent logs:

$ docker-compose up
Creating postgresql ... done
Creating coturn     ... done
Attaching to postgresql, coturn
postgresql    | 
postgresql    | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgresql    | 
postgresql    | 2023-04-12 12:43:58.053 UTC [1] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgresql    | 2023-04-12 12:43:58.053 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql    | 2023-04-12 12:43:58.053 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgresql    | 2023-04-12 12:43:58.056 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql    | 2023-04-12 12:43:58.060 UTC [29] LOG:  database system was shut down at 2023-04-12 12:43:52 UTC
postgresql    | 2023-04-12 12:43:58.065 UTC [1] LOG:  database system is ready to accept connections
coturn        | 0: (1): INFO: System cpu num is 16
coturn        | 0: (1): INFO: System cpu num is 16
coturn        | 0: (1): INFO: System enable num is 16

No logs appear to be logged beyond the initial three shown above. If I revert to 4.6.1-r3, the logs are logged as expected with all of the listeners, the Coturn version, etc. As part of troubleshooting, I also tried switching to the debian and edge-alpine tags but experienced the same issue.

If I do not use the syslog option, the logs are generated as expected using 4.6.2. Is it possible that there is a regression with the syslog option in 4.6.2?

**Comment by eakraly** [comment]
Hi @brentmedicom 

Logs have been extensively cleaned up - especially on start (some duplicates, some verbose etc)
Try running with -v (verbose) and see if it works better for you

**Comment by brentmedicom** [comment]
Hi @eakraly. I am actually running with verbose and syslog in that example. I tried removing verbose and leaving syslog, but the issue still persists. As soon as I remove the syslog option, the issue appears to clear up.

**Comment by eakraly** [comment]
But do logs appear in syslog?

When you run with syslog all logs redirected there and nothing (almost) shows up on stdout

Can you confirm if the full log appears in syslog?

**Comment by brentmedicom** [comment]
It appears that things got a little weird with some of the changes with Amazon Linux 2023 (AL2023). After working through things, it appears that everything is logging as expected. Apologies for the false alarm.

Thanks for the troubleshooting assistance @eakraly! Also huge thanks to the team for getting 4.6.2 out.
