### ISSUE TITLE
Potential Vulnerability

### ISSUE THREAD

**Issue by artemkazants** [coturn/coturn#1195]
Hello, Team.

Your program is used as a TURN server in our web application infrastructure.
During penetration testing, the following problem was identified:

When using the TURN server as a proxy server using the stunner utility (https://github.com/firefart/stunner), an attacker can access internal and external web resources from our server.
A static username and password is used for all users.
Potentially an attacker could get the ip and use it for spamming emails etc which could result in our IP being blacklisted.

Please take a look at this issue and provide suggestions on how to fix this issue.

**Comment by eakraly** [comment]
Hi @artemkazants 

Both issues that you mentioned (accessing internal web resources and static username/password) are not coturn vulnerabilities but configuration issues. You can easily fix both by properly configuring it:

1. Listen and allow allocation on public interfaces only
2. Use `--denied-peer-ip` configuration option to block access to internal subnets
3. Use --use-auth-secret which enables what's called TURN REST API that allows generation of unique credentials to each user signed by a shared secret. Or use DB to store username/password for each user

Also regarding accessing internal resources - it is a well known issue for 7 years - described here https://www.rtcsec.com/article/slack-webrtc-turn-compromise-and-bug-bounty/ by Sandro who is the author of the stunner tool....

**Comment by eakraly** [comment]
No updates from OP - closing
