### ISSUE TITLE
Coturn behind Cloudflare Proxy

### ISSUE THREAD

**Issue by mghadam** [coturn/coturn#1196]
I have set up a working coturn on a subdomain behind nginx reverse proxy that only uses port 443 TCP according to https://github.com/coturn/coturn/issues/702

When I activate cloudflare CDN service for this subdomain, coturn stops working. Is there any way available to relay streaming traffic through cloudflare CDN?

**Comment by jbg** [comment]
CloudFlare Proxy speaks HTTP(S). TURN is not HTTP(S), even if you run it on the same port. CloudFlare Spectrum supports arbitrary TCP traffic, but only on the Enterprise tier. (This is really a discussion to be had with CloudFlare support.)

**Comment by eakraly** [comment]
Thanks @jbg !
This is a good point - see here https://developers.cloudflare.com/spectrum/

@mghadam you need Cloudflare to proxy raw TCP connections rather than HTTP/S for TURN to work

**Comment by 16g** [comment]
Thank you guys! You saved me time.

**Comment by Gekko23** [comment]
> [@mghadam](https://github.com/mghadam) you need Cloudflare to proxy raw TCP connections rather than HTTP/S for TURN to work

I don't understand, what this means. Do you suggest to disable DNS proxy -> DNS only? If not, could you please describe what to do?
