### ISSUE TITLE
STUN on old routers

### ISSUE THREAD

**Issue by webleb** [coturn/coturn#1200]
Hello, is there a way to make STUN working on old routers? i have note port forwarding feature on router it can be useful ?
@jbg @tony2001 @byronclark @dbrgn @NeoCat

**Comment by jbg** [comment]
Please don't tag random people in your issue.

Your question is unclear. The age of a router is not itself a factor in whether STUN or TURN will work through it.

**Comment by webleb** [comment]
> Please don't tag random people in your issue.
> 
> Your question is unclear. The age of a router is not itself a factor in whether STUN or TURN will work through it.

I am not tagging random people it is github which suggest these people.
Old routers dont have STUN Feature while new routers allow you to enable or disable stun.
My question is that can use port forwarding to make STUN working or it cant help.
Thanks and sorry if I tag you

**Comment by jbg** [comment]
What does your question have to do with CoTURN?

**Comment by webleb** [comment]
> What does your question have to do with CoTURN?

CoTURN can be used as TURN or STUN server and my question can we make STUN working by using port forwarding

**Comment by jbg** [comment]
If you mean that you are running CoTURN as a STUN server behind a router that is doing NAT, then port forwarding would work if the router preserves the client IP.
