### ISSUE TITLE
abnormal source port setting after recvmsg call

### ISSUE THREAD

**Issue by JeffreyVIP** [coturn/coturn#121]
Dear Sir/Madam

Environment: Debian 8.5
Latest coturn version (git clone today).

Network Topology:
Endpoint A (Public Internet)  <==> Firewall <==> coTURN <==> Endpoint B (Inside Network, no TURN support)

with external / internal IP mapping, coturn is installed in a inside network.
So relay IP address in SIP protocol is public IP address.

In order to let inside video endpoint to accept RTP stream from coturn server, I have below iptables command set.

`iptables -t nat -A POSTROUTING -o eth0 -d 10.0.0.0/8 -m udp -p udp -j SNAT --to-source 101.251.144.47`

101.251.114.47 is the public IP mapped to coturn private IP.

When a RTP stream with small size, 23 bytes udp payload length comes from endpoint B to coturn server, the source udp port will be wrongly set within recvmsg() function (IP is correctly set, but source port always be 1024), which cause abnormal behavior of TURN function. Endpoint A can't receive RTP stream from endpoint B, but Endpoint B can receive RTP stream from Endpoint A.

The recvmsg call in function: udp_recvfrom()
file: ns_ioalib_engine_impl.c

When I remove the iptable rule, source port will be correctly set within recvmsg, and Endpoint A can receive RTP stream relayed by coturn from Endpoint B, but Endpoint B won't accept stream relayed via coturn.

Seems there is conflicts between recvmsg and iptables.

Any hints to solve the issue?

Thanks.

**Comment by misi** [comment]
@JeffreyName 

If the issue is still actual, could you please retest it with the latest master too?

**Comment by ggarber** [comment]
This issue is too old and there is no feedback from the author.  Please reopen if this is still an issue with the latest version.  Thank you.
