### ISSUE TITLE
Which value should set on --external-ip?

### ISSUE THREAD

**Issue by nowjean** [coturn/coturn#1210]
Hi
I am running coturn on kubernetes. 
When I command "ps -ef"  in the coturn container,
I can see below result.

```
$ coturn-765dbbc557-5jjpj:/$ ps -ef
PID   USER     TIME  COMMAND
    1 nobody    0:04 turnserver --log-file=stdout --external-ip=123.456.789.10
```

I have two public IP addresses on coturn which are In-boud and Out-bound  public IP addresses.
When I change --external-ip value to In-bound or Out-bound IP Address, both of them working correctly (Streaming is good).

Which value is correct ?

Thanks.

**Comment by tyranron** [comment]
@nowjean using in-bound IP should be more correct.

**Comment by nowjean** [comment]
> @nowjean using in-bound IP should be more correct.

@tyranron Thanks for your comment! I just want to make sure my question. I've checked Coturn traffic with wireshark.  Then,
"--external-ip=123.456.789.10" will set relay transport address. With this situation, --external-ip should be set in-bound IP of coturn?

**Comment by tyranron** [comment]
@nowjean yes.

**Comment by eakraly** [comment]
Question answered - closing the issue.
