### ISSUE TITLE
Coturn UDP port dynamically open and close?

### ISSUE THREAD

**Issue by nowjean** [coturn/coturn#1212]
Hi.

I am running coturn on Kuberntes.
When I check coturn UDP port with nmap,

```
coturn-7868cbcd8f-959kc:/# nmap -n -PN -sT -sU -p- 127.0.0.1
Starting Nmap 7.93 ( https://nmap.org ) at 2023-05-18 05:16 UTC
Nmap scan report for 127.0.0.1
Host is up (0.000058s latency).
Not shown: 65534 closed udp ports (port-unreach), 65534 closed tcp ports (conn-refused)
PORT     STATE SERVICE
3478/tcp open  stun
3478/udp open  stun

Nmap done: 1 IP address (1 host up) scanned in 1.65 seconds
```
I can see only 3478 TCP/UDP. 

But, TURN function seems working correctly. 
With wireshark packet, I could see Allocate Success Response,  CreatePermission Success, Binding Success Response, and ChannelData Turn  Message.

So, I've tested for UDP connection.
```
test@test# nmap -sU -p 49156 <coturn IP>
Starting Nmap 7.80 ( https://nmap.org ) at 2023-05-18 05:02 Asia
Nmap scan report for <Coturn IP>
Host is up (0.00094s latency).

PORT      STATE         SERVICE
49156/udp open|filtered unknown

Nmap done: 1 IP address (1 host up) scanned in 0.49 seconds
```

Like above result, UDP conneciton is opend! But, In coturn with nmap UDP check result still only open to 3478 TCP/UDP.

So, This is my question, 
Coturn open and close UDP port dynamically?

**Comment by nowjean** [comment]
Oh, is the reason why 49152-65535 ports are Dynamic ports??

**Comment by rolandwu777** [comment]
@nowjean Can you try use "netstat -ltupn" instead of "nmap ..." ?

**Comment by nowjean** [comment]
> @nowjean Can you try use "netstat -ltupn" instead of "nmap ..." ?

@rolandwu777 Same result.  49152-65535 ports are Dynamic ports that are available for use by any application to use in communicating with any other application, using the internet's TCP or UDP.(https://www.techtarget.com/searchnetworking/definition/UDP-User-Datagram-Protocol).

**Comment by rolandwu777** [comment]
@nowjean 
1. You may want to do a wireshark. 
2. I am still understanding TURN, but I think it will use 3478 to receive TURN messages and relay will use one of the port dynamically specified in turnserver.conf to relay the messages.

\# Lower and upper bounds of the UDP relay endpoints:
\# (default values are 49152 and 65535)
\#
min-port=40000
max-port=49998

5. https://webrtc-turn-server-test.vercel.app/
If you can make this URL work and you can do a tshark and just capture the loopback interface and you will see one of the relay port will be used during the turn session. Also during that session, if you do netstat -ltupn, you shouls see the port is used.
tshark -i lo -w test.pcap 

6. Usually, TURN server should be dedicated, so there is a lower chance for port conflicts. However, if it is not dedicated, port conflicts are possible, so need to be avoid the conflict.
7. Usually, if a session is not actively running, even port range is reserved, depend on the implemtation, the application (turnserver) may not listen to the port. That may waste too much CPU.

**Comment by rolandwu777** [comment]
@nowjean In wireshark, what are the scr/dst ports used for TURN messages?

**Comment by nowjean** [comment]
@rolandwu777 Thanks for your kindly comment and sorry for long long question..
First of all my coturn and media server running on Kubernetes.

Refer to below wireshark COTURN server packet, XOR-RELAYED-ADDRESS: <Coturn Public IP>:49153. I dunno about XOR-RELAYED-ADDRESS's role.

I think like you said TURN message use 3478 port with Coturn priaveIP(345,346,365,366,367,369,370) and relay use one of dynamic port(49152-65535) like 371 packet.

My new qeustion is role of XOR-RELAYED-ADDRESS. 
When Binding Request user(352,353,354,355) use 49153 port which is above XOR-RELAYED-ADDRESS port. But, When I change this IP to randomly to Coturn PublicIP or Coturn NAT IP or Coturn PrivatIp, It also works fine. 

(Also, When I capture wireshark Client packet, XOR-RELAYED-ADDRESS: <Coturn Public IP>:49153 used byt Binding Request user's src ip and port.)

I thought  it is  just id of allocation, But after I read RFC 5766 (https://www.rfc-editor.org/rfc/rfc5766), It used by TURN traffic.
Then, How coturn server can coturn server notice XOR-RELAYED-ADDRESS: <Coturn PublicIP or NAT IP> to <Coturn PrivateIP> ? 

I opened only 3478 TCP/UDP port for Coturn PublicIP.

```
345	11.186109	<Coturn PriavateIP>	<ClientIP>	STUN	150	Allocate Success Response XOR-RELAYED-ADDRESS: <Coturn Public IP>:49153 XOR-MAPPED-ADDRESS: <ClientIP>:56789 lifetime: 600
346	11.323736        <ClientIP>	<Coturn PrivateIP> 	STUN	238	Send Indication XOR-PEER-ADDRESS: <Media PrivateIP>:40420
352	11.323736	<Coturn PrivateIP>	<Media PrivateIP>	STUN	146	Binding Request user: 2b7fd235:0ahJ
353	11.323736	<Media PrivateIP>	<Coturn PrivateIP>	STUN	146	Binding Request user: 0ahJ:2b7fd235
354	11.323736	<Coturn PrivateIP>	<Media PrivateIP>	STUN	146	Binding Success Response XOR-MAPPED-ADDRESS: <Coturn PrivateIP>:49153
355	11.323736	<Media PrivateIP>	<Coturn PrivateIP>	STUN	146	Binding Success Response XOR-MAPPED-ADDRESS: <Media PrivateIP>:40420
365	11.323736	<ClientIP>	<Coturn PrivateIP> 	STUN	166	Channel-Bind Request ChannelNumber=0x4000 XOR-PEER-ADDRESS: <Media PrivateIP>:40420 user: test realm: test with nonce
366	11.323736        <ClientIP>	<Coturn PrivateIP> 	STUN	238	Send Indication XOR-PEER-ADDRESS: <Media PrivateIP>:40420
367	11.323736	<Coturn PrivateIP>	     <ClientIP>       	STUN	118	Channel-Bind Success Response
369	11.340880	<Coturn PrivateIP>	      <ClientIP> 	STUN	827	ChannelData TURN Message
370	11.340880	<ClientIP>	<Coturn PrivateIP> 	STUN	946	ChannelData TURN Message
371	11.340880	<Coturn PrivateIP>	<Media PrivateIP> 	UDP 	827	49153 -> 40420 Len=106
```

**Comment by rolandwu777** [comment]
@nowjean Okay. I provided some personal thought on #1214. Today I did some capture using https://webrtc-turn-server-test.vercel.app/. I guess I know what you are talking about. There is one point I still could not explained the reason, but after some thought, I think I have some thory
. 
1. If you change the extnernal IP to a dummy address, such as 5.5.5.5. When the client send the request "Allocate Request UDP user", it return the dummy allocated XOR-RELAYED-ADDRESS, say, 5.5.5.5:30001.
2. The other client, also send "Allocate Request UDP user", it return the dummy allocated XOR-RELAYED-ADDRESS, say, 5.5.5.5:30013.
3. You actually can find [ICE Candidate pair: 5.5.5.5:30013 <=> 5.5.5.5:30001] 
   using this URL => chrome://webrtc-internals/

4. One point I could not figure out is 5.5.5.5 is not a reachable IP adderss, but how can client send a stun message to 5.5.5.5:30013 or 30001 to get a STUN response, so it can get sucessful ICE connection. 
 My thoery is the COTURN server does know 5.5.5.5:30013 and 5.5.5.5:30001, so it just interconnect them. I'm not sure if this behavior is intentional or an optimization. I don't know if it's a standard TURN server behavior. Reading the coturn source code might provide clarity, but I'm satisfied with my theory for now. :-)

**Comment by rolandwu777** [comment]
@nowjean 
[I thought it is just id of allocation, But after I read RFC 5766 (https://www.rfc-editor.org/rfc/rfc5766), It used by TURN traffic.
Then, How coturn server can coturn server notice XOR-RELAYED-ADDRESS: to ?]
This is like if you give your friend your cell phone number wrong, you can still call your firend as long as your friend give you the right cell phone number. (but your friend may not be able to call you though.)

**Comment by eakraly** [comment]
Hi @rolandwu777 and @nowjean 

There are a few intro articles you can find on TURN and its function. You can start with this basic one https://bloggeek.me/webrtc-turn/

The idea is that TURN acts as a proxy, where it relays traffic between a client (represented by the TURN) and its peer. So relay address is the address used by TURN to represent the client and then relay packets both ways.

:3478 is the control port which clients use to establish connection to the relay - data is relayed over different ports (that's the dynamic range you let turn server use) and may even be a different IP.

In some scenarios, there would be double-relay where the connection is client<->relay1<->relay2<->peer. It is even more confusing when relay1 and relay2 are the same relay but different ports.

**Comment by rolandwu777** [comment]
@eakraly  Thank you!

**Comment by nowjean** [comment]
@rolandwu777 @eakraly Thanks a lot! I will test more again this issue later. Actually, I couldn't find reference of Coturn on Kubernetes. Also, I run two Coturn pod with loadbalancer and more than 100 media servers use two Coturn pod. Streaming seems good. There was no disconnection during 2 hours streaming service. But, I'm not sure it is really working correctly or not.

If I get to know this connectivity issue, I will post again! Thanks!
