### ISSUE TITLE
Peer IP denied

### ISSUE THREAD

**Issue by pilipovicn** [coturn/coturn#1213]
I am using coturn with Synapse matrix server. Both on my LAN, behind NAT. TURN ports forwarded correctly.

I have disabled relaying to my private IPs (255.255.255.0) for security reasons since I have other machines and services running on my LAN.
`denied-peer-ip=192.168.0.0-192.168.255.255`

With this, it sometimes works, but sometimes I get the error:
`ERROR: A peer IP 192.168.0.xxx denied in the range: 192.168.0.0-192.168.255.255`

Why is it picking the IP from the denied range? How do I restrict it to some other range?
Who is responsible for picking the peer IP? It changes every once in a while, and if it picks some other private IP like 10.0.xxx.xxx the calls work.
I tried looking though TURN specs but I'm not sure exactly on the operation of the protocol.

**Comment by Govind10g** [comment]
Are you testing in any kind of VPN or in plan network ?
and What is your client IP during this test ?

**Comment by pilipovicn** [comment]
This is inside a home LAN. I tested with a client, both with a public IP and private in the same LAN, the error still appears no matter the IP.

**Comment by eakraly** [comment]
Hi @pilipovicn 

Do you see it in relay logs? Can it be that someone external is trying to make a connection into your internal network and your setup actually prevents them from doing that? Meaning, your setup actually working correctly?


Other idea is that it may be related to double relay scenario: client<->relay<->relay<->peer

This happens when both client and peer force into relay only mode. And when both are on the same server you have a scenario where relay must forward traffic to itself but it should do so using relay-ip (which is public) and not internal private-ip...

**Comment by pilipovicn** [comment]
I don't think it's the first case. Those rejections happen only when I try to do a WebRTC call. I can tell the originating IP is familiar.

As for the second, I'm not sure if I understood, but the TURN server and Synapse server are on the same machine, behind NAT. Could that be it?

**Comment by eakraly** [comment]
Yes, makes sense - if they are on the same IP and Synapse connecting from internal IP then coturn blocks the connections because it is explicitly forbidden.

Basically, any of the client/peers cannot run in the `denied-peer-ip=192.168.0.0-192.168.255.255` range according to your configuration

**Comment by AdelKS** [comment]
I just hit against this issue, and while checking the [coturn synapse-specific configuration](https://element-hq.github.io/synapse/latest/setup/turn/coturn.html) I saw this particular snippet in `coturn`'s config file

```
# special case the turn server itself so that client->TURN->TURN->client flows work
# this should be one of the turn server's listening IPs
allowed-peer-ip=10.0.0.1
```

And in my case (same as yours: both `synapse` and `coturn` run on the same physical host,  behind a NAT) I just had to replace it with 

```
# special case the turn server itself so that client->TURN->TURN->client flows work
# this should be one of the turn server's listening IPs
allowed-peer-ip=192.168.xxx.xxx # my server's internal IP
```

Hope it is useful for some
