### ISSUE TITLE
Current allocation count

### ISSUE THREAD

**Issue by Lazarus404** [coturn/coturn#1215]
Hi guys,

Is there a way to find out the current allocation count through Redis or somesuch?  I've seen there's a way through Prometheus, but I'm not using that.

Many thanks,

**Comment by JeanPluzo** [comment]
Hi,
you mean you need to see the current connections made to coturn?
coturn has a built in telnet server (port 5766). You could login there and see the current sessions, current users, etc.
Hope this helps.

Regards,
J.

**Comment by eakraly** [comment]
Hi @Lazarus404 You can use Prometheus interface or Redis to get metrics (including count of active allocations) for that
