### ISSUE TITLE
STUN working but turn not

### ISSUE THREAD

**Issue by MarcusFloeser** [coturn/coturn#1218]
Hello,

I'm trying to setup a coturn server behind a firewall. The coturn should be used in addition to allow users to connect over port 443/tcp to the meeting where corporate firewalls deny outgoing udp sessions.

I setup the firewall with dNAT and sNAT and allowed incoming 443/tcp to my private IP. My turnserver.conf looks like following:

```
listening-port=3478
tls-listening-port=443

listening-ip=0.0.0.0

external-ip=<external NAT IP>/<local server IP>

min-port=10000
max-port=20000

verbose

no-auth

#use-auth-secret
#static-auth-secret=fe0501dacc3573b5baa3f1e19e2f005b3ec8c7067c4743c60de0d7c464a51d8b

server-name=turn.mydomain.com

#user=test:test

realm=mydomain.com

#no-udp
#no-udp-relay
#no-tcp

cert=/etc/coturn/ssl/domain.crt
pkey=/etc/coturn/ssl/domain.key
pkey-pwd=sametime

log-file=/var/log/coturn/turnserver.log

simple-log

#no-stun

#secure-stun

no-tlsv1
no-tlsv1_1
no-tlsv1_2

no-rfc5780

no-stun-backward-compatibility

response-origin-only-with-rfc5780

```

I tested with the Trickle ICE tool. The STUN part is returning correctly "srflx", but the turn part does not return "relay". So something seems to be wrong configured?

**Comment by eakraly** [comment]
Hi @MarcusFloeser 
Can you try and test with turnutils_uclient? It will provide more details regarding ports and where it fails

**Comment by MarcusFloeser** [comment]
the issue is solved. There was a port blocked on turn server ..
