### ISSUE TITLE
Ques - One to one call is working even when my TURN server is in stopped state ? Any idea why ?

### ISSUE THREAD

**Issue by Govind10g** [coturn/coturn#1219]
Hi All,

I observed my element page which is integrated with CoTURN is able to make a call between two different user when the TURN server is in stopped state.

Any idea why ? How it is working STUN/TURN ?

**Comment by eakraly** [comment]
Hi @Govind10g TURN is only used when peers cannot make a direct connection (or you force them to).
So this is actually expected.
