### ISSUE TITLE
./configure problem

### ISSUE THREAD

**Issue by colin-liu** [coturn/coturn#122]
I use Mac in coturn folder run `./configure`, generate log below.
Please help me to solve it, Thanks.
```
➜  coturn ./configure      
install is /usr/bin/install
pkill is /usr/bin/pkill
sqlite3 is /usr/bin/sqlite3
Use TMP dir /var/tmp
Compiler: cc
Library option -lsocket cannot be used
Library option -lrt cannot be used
Library option -lwldap32 cannot be used
Library option -lwldap64 cannot be used
Library option -lintl cannot be used
Library option -lnsl cannot be used
Sockets code is fine: sin_len field present
pthread barriers not found
Ignore IP_RECVERR
Library option -lcrypto cannot be used
ERROR: OpenSSL Crypto development libraries are not installed properly in required location.
Abort.
```

**Comment by mom040267** [comment]
Something is not right about your OpenSSL setup.

I just tried on my Mac Book (that has vanilla latest Mac OS X) and it
configures just fine.

**Comment by tpedersen123** [comment]
@colin-liu I had the same problems. This post helped me
http://stackoverflow.com/questions/33530865/compiling-c-programs-using-libssl-on-os-x-el-capitan

More specifically I just added the exports:
```
export LDFLAGS=-L/usr/local/opt/openssl/lib
export CPPFLAGS=-I/usr/local/opt/openssl/include
```

**Comment by mike-aungsan** [comment]
I have the same issue on ubuntu.

./configure
ginstall: not found
install is /usr/bin/install
pkill is /usr/bin/pkill
sqlite3: not found
sqlite: not found
Use TMP dir /var/tmp
Compiler: cc
Library option -lsocket cannot be used
Library option -lwldap32 cannot be used
Library option -lwldap64 cannot be used
Library option -lintl cannot be used
Sockets code is fine: no sin_len field present
Ignore IP_RECVERR
Library option -lcrypto cannot be used
ERROR: OpenSSL Crypto development libraries are not installed properly in required location.
Abort.


 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty


uname -a
Linux webrtc-dev 4.4.0-92-generic #115~14.04.1-Ubuntu SMP Thu Aug 10 15:06:53 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 71104** [comment]
+1

**Comment by misi** [comment]
try apt install openssl-dev

**Comment by jay58** [comment]
The issue is still persistent with me.

I did echo $CPPFLAGS and echo $LDFLAGS and both the path is the same as mentioned in the above comments.

Logs:
>install is /usr/bin/install
pkill is /usr/bin/pkill
sqlite3 is /usr/bin/sqlite3
Use TMP dir /var/tmp
Compiler: cc
Library option -lsocket cannot be used
Library option -lrt cannot be used
Library option -lwldap32 cannot be used
Library option -lwldap64 cannot be used
Library option -lintl cannot be used
Library option -lnsl cannot be used
Sockets code is fine: sin_len field present
pthread barriers not found
Ignore IP_RECVERR
Crypto SSL lib found.
SSL lib found.
WARNING: Cannot find GCM support.
Turning GCM off.
Libevent2 development is not installed properly
ERROR: Libevent2 development libraries are not installed properly in required location.
ERROR: may be you have just too old libevent tool - then you have to upgrade it.
See the INSTALL file.
Abort.

**Comment by YY030913** [comment]
> @colin-liu I had the same problem. This post helped me
> http://stackoverflow.com/questions/33530865/compiling-c-programs-using-libssl-on-os-x-el-capitan
> 
> More specifically I just added the exports:
> 
> ```
> export LDFLAGS=-L/usr/local/opt/openssl/lib
> export CPPFLAGS=-I/usr/local/opt/openssl/include
> ```


$sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G2022

~/.bash_profile
export LDFLAGS="-L/usr/local/opt/openssl\@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl\@1.1/include"


$ echo $LDFLAGS
-L/usr/local/opt/openssl\@1.1/lib


$ echo $CPPFLAGS
-I/usr/local/opt/openssl\@1.1/include

when run
$ ./configure 
still error
ERROR: OpenSSL Crypto development libraries are not installed properly in required location.

**Comment by daxiondi** [comment]
On CentOS (and other RPM-based distributions), you need to install the openssl-devel package:

sudo yum install openssl-devel
(Use sudo dnf ... on CentOS 8, RHEL 8 or Fedora.)

The equivalent in the Debian ecosystem is libssl-dev

**Comment by Rohit-Simulanis** [comment]
Hi I am trying to install Coturn but getting error.
Cannot use Compiler unknown property
<img width="399" alt="Screenshot 2020-06-30 at 2 19 53 PM" src="https://user-images.githubusercontent.com/26364916/86477349-df10fb00-bd65-11ea-9b57-c8e96606f795.png">

**Comment by daxiondi** [comment]
> 嗨，我正在尝试安装Coturn，但出现错误。
> 无法使用编译器未知属性
> <img alt="截图2020-06-30 at 2 19 53 PM" width="399" src="https://user-images.githubusercontent.com/26364916/86477349-df10fb00-bd65-11ea-9b57-c8e96606f795.png">

Depending on what seems like a permission issue, you can try 
```chmod 777 /var/ tmp/*```

**Comment by daxiondi** [comment]
> 嗨，我正在尝试安装Coturn，但出现错误。
> 无法使用编译器未知属性
> <img alt="截图2020-06-30 at 2 19 53 PM" width="399" src="https://user-images.githubusercontent.com/26364916/86477349-df10fb00-bd65-11ea-9b57-c8e96606f795.png">

If there are more issues, welcome to QQ group 959024679

**Comment by SandeepKhore** [comment]
Hi,

I'm referring https://github.com/coturn/coturn/blob/master/INSTALL to install on MacBook Pro.

Was getting below error so I installed openssl using brew.
<img width="700" alt="Screenshot 2021-01-13 at 6 00 46 PM" src="https://user-images.githubusercontent.com/30897338/104452627-463b2200-55c9-11eb-9d07-10a895c0aba8.png">

This error fixed but started getting issue related to Libevent2.
<img width="657" alt="Screenshot 2021-01-13 at 6 02 05 PM" src="https://user-images.githubusercontent.com/30897338/104452812-88646380-55c9-11eb-9ba0-1fb21d74b351.png">

Let me know if I'm missing anything.

Thanks

**Comment by misi** [comment]
Unfortunately I don't have a mac, so I can't test it.

According travis test it should work and compile on travis...

See for osx install logs in travis: https://travis-ci.org/github/coturn/coturn

**Comment by eakraly** [comment]
Hi @SandeepKhore !
Do you still have an issue? It looks like you are missing libevent library
You can install it on mac using `brew install libevent`

**Comment by Seunmul** [comment]
> @colin-liu I had the same problem. This post helped me http://stackoverflow.com/questions/33530865/compiling-c-programs-using-libssl-on-os-x-el-capitan
> 
> More specifically I just added the exports:
> 
> ```
> export LDFLAGS=-L/usr/local/opt/openssl/lib
> export CPPFLAGS=-I/usr/local/opt/openssl/include
> ```

thank you! I solved same problem 

Intel imac / MacOS 12

**Comment by ftpxzxh** [comment]
> I try 
sudo apt-get install libtool
and success
