### ISSUE TITLE
add the alpine version into the tag on docker hub in order to be able to pin the alpine version

### ISSUE THREAD

**Issue by szaimen** [coturn/coturn#1226]
Hi, 

thanks for this awesome project! 

Currently, I am using the coturn container as base for one of my projects and would like to pin the alpine version in order to not run into unexpected updates.

So I would like to ask if it would be possible to create additional tags like `4.6.2-alpine3.18`. Currently I need to pin the rc version like e.g. `4.6.2-r3-alpine` since otherwise the alpine base might unexpectedly gets updated in between. 

Thanks for considering!

**Comment by tyranron** [comment]
@szaimen released as [4.6.2-r4](https://github.com/coturn/coturn/releases/tag/docker%2F4.6.2-r4).
