### ISSUE TITLE
same account, login at same time

### ISSUE THREAD

**Issue by tangxinzhou** [coturn/coturn#124]
Hi ,

I recently tested the program of the turn client, using coturn at server side.

I started two turn client programs at the same time , with the same account to login . I found that these two programs with same account can both login successfully , and these two programs can exchange data with each other.

I wonder if this is a normal feature, or a bug that will be fixed in the future. 

I want to use this feature.

BR

**Comment by mom040267** [comment]
This is a "normal" feature. There is no requirement that a user account can
have only one session.

It would be impossible to enforce - because of stall and "lost" sockets,
etc.
