### ISSUE TITLE
Storage of the voice data

### ISSUE THREAD

**Issue by NasserAlmanji** [coturn/coturn#125]
Is it possible to store the voice data relayed through the server?

And how to replay it?

Kind regards,
Nasser

**Comment by mom040267** [comment]
No, that would be a very custom development.

**Comment by NasserAlmanji** [comment]
Do you provide such development?

**Comment by NasserAlmanji** [comment]
Also, how much custom development does it require? Are there many lines of code to change?

**Comment by mom040267** [comment]
no we do not

**Comment by ggarber** [comment]
Voice is typically encrypted when it goes through TURN so even if you do the custom development (not to hard) you won't be able to use it later.
