### ISSUE TITLE
Coturn packet loss

### ISSUE THREAD

**Issue by Raksha-CPU** [coturn/coturn#1252]
I am using Coturn (a server for NAT traversal) on AKS (Azure Kubernetes Service) with a load balancer. Coturn is being utilized within an application to establish audio connections to a corporate network. However, I am encountering an issue where the audio connection drops every 40 seconds for about 2 to 3 seconds when connected to the corporate network.

Can you please suggest a solution?

**Comment by eakraly** [comment]
Hi @Raksha-CPU 
What makes you think it is a coturn issue? Your setup is highly specific to your use case and it is almost impossible to provide a good recommendation in this case

Please review logs from all sides:
- Can you see packet loss somewhere?
- Is it a disconnect and reconnect?
- Do you have 40 second timeout somewhere and it fires?
