### ISSUE TITLE
Memory leak in 'main' function

### ISSUE THREAD

**Issue by JoraGevorgyan** [coturn/coturn#1260]
The memory leak is reported by a static analyzer tool developed at [CAST](https://www.linkedin.com/company/cast-center)

return value of  [realloc](https://github.com/coturn/coturn/blob/2a695ea8551e782169c495d9239b2a0388763879/src/apps/peer/mainudpserver.c#L94) is stored in the same variable, so it may lose the value in case of failure of realloc

**Comment by ggarber** [comment]
Thank you very much for the report @JoraGevorgyan .   

In general coturn doesn't handle the cases where malloc/realloc would fail.

Given that fact and that the realloc is in an app used only for internal testing (mainudpserver) I think it should be ok to close this ticket if you are ok with it.

But thank you again!  It is great to have people looking at these issues.
