### ISSUE TITLE
TURN/STUN ALPN is not supported

### ISSUE THREAD

**Issue by Jerrylove** [coturn/coturn#127]
1.configure:
turnserver.conf:
listeningip=xxx.xxx.xxx.xxx
listenport=3478
user=admin:admin
only these infomation
2.start:
turnserver -L xxx.xxx.xxx.xxx -o -a -b /etc/turnuserdb.conf -f -r xxx

3.infomation:
TLS supported
DTLS supported
DTLS 1.2 is not supported
TURN/STUN ALPN is not supported
Third-party authorization (oAuth) supported
GCM (AEAD) supported
OpenSSL compile-time version: OpenSSL 1.0.1e-fips 11 Feb 2013 (0x1000105f)
......

DTLS 1.2 is not supported and TURN/STUN ALPN is not supported,why please?

**Comment by mom040267** [comment]
Because your OpenSSL version is too old
