### ISSUE TITLE
Add ability to change default prometheus port on coturn server

### ISSUE THREAD

**Issue by leonidgorbachev** [coturn/coturn#1276]
Hello, dear coturn team

Currently, with enabling of prometheus coturn by option "--prometheus", coturn opens port 9641 for metrics request.
Due security reasons, its possible that very limited number of ports available for listening.
Could you please consider to add the ability to change this port to another one?

Thank you in advance

**Comment by eakraly** [comment]
Hi @leonidgorbachev 
See `prometheus-port` in configuration file - it already provides the feature you request

Please reopen the issue if that does not work for you!
