### ISSUE TITLE
empty listening-ip= does _NOT_ let the system listen on IPv4 and IPv6

### ISSUE THREAD

**Issue by computersalat** [coturn/coturn#1294]
Hi

in config there is the following comment:
```
# Listener IP address of relay server. Multiple listeners can be specified.
# If no IP(s) specified in the config file or in the command line options,
# then all IPv4 and IPv6 system IPs will be used for listening.
```

hence I tried
```
listening-ip=
```
with the result, that coturn is _only_ listening on _IPv4_ addresses

if you want to make it listen on _IPv4_ as well as on _IPv6_ you need:
```
listening-ip=::
```

You should either update  your documentation/comment to point this out or fix your code that _empty IP_
```
listening-ip=
```
will result in listening on _any_ IPv4 and IPv6 address

**Comment by eakraly** [comment]
@computersalat feel free to submit a PR

**Comment by computersalat** [comment]
with
```
listening-ip=::
```

I get:
```
0: (9990): INFO: Wait for relay ports initialization...
0: (9990): INFO:   relay :: initialization...
0: (9990): INFO:   relay :: initialization done
0: (9990): INFO: Relay ports initialization done
0: (9990): INFO: Total General servers: 2
3: (9993): DEBUG: turn server id=0 created
3: (9993): INFO: IPv6. TLS/TCP listener opened on : :::3478
3: (9993): INFO: IPv6. TLS/TCP listener opened on : :::5349
3: (9994): DEBUG: turn server id=1 created
3: (9994): INFO: IPv6. TLS/TCP listener opened on : :::3478
3: (9994): INFO: IPv6. TLS/TCP listener opened on : :::5349
3: (9990): INFO: IPv6. DTLS/UDP listener opened on: :::3478
3: (9990): INFO: IPv6. DTLS/UDP listener opened on: :::5349
```

hence only listening on IPv6

**Comment by computersalat** [comment]
@eakraly 
here it is: #1336

**Comment by computersalat** [comment]
@eakraly 

I fully agree to fix the main cause.
But I am not able to fix it as I don't know C or C++.
Ich just wanted to bring awareness about the problem and how it is possible to work around until it gets a fix.
Anyone else with C/C++ knowledge should kindly step in and provide a fix.
Thank you
Chris
