### ISSUE TITLE
Configure with mysql 

### ISSUE THREAD

**Issue by yasirrose** [coturn/coturn#130]
i have configure coturn server using mysql support.  ip:port is now showing turn server text which is showing successful installation. 

But when i tried it in tickle-ice. I got following results which is showing no relay server. 
![screenshot_1](https://cloud.githubusercontent.com/assets/5586359/26061673/066d3a9c-39a2-11e7-9bfe-18c5f01cebe5.png)

I have created the user using following command which i am using to access my turnserver through code. 
`turnadmin -a -M “host=localhost dbname=turn user=turn password=turn” -u altanai -r mycompany.com -p 123456`

I am directly using these username and password in my code but it is not working. 

Can any one let me know what i am doing wrong?

**Comment by OrangeDog** [comment]
How have you configured it? Possibly related to #147.

**Comment by mom040267** [comment]
See the script example:

examples/scripts/longtermsecuredb/secure_relay_with_db_mysql.sh

**Comment by eakraly** [comment]
@yasirrose this issue is 5 years old
If you still have an issue please open a new one. Thank you!
