### ISSUE TITLE
CMake Build doesn't detect Prometheus

### ISSUE THREAD

**Issue by richard-signal** [coturn/coturn#1304]
I've noticed that the CMake build doesn't seem to detect Prometheus libraries, although configure can.

It seems like a script to find it would be needed based on the output from the CMake github automation: https://github.com/coturn/coturn/actions/runs/6622872744/job/17989011141#step:5:106  (note that the github automation does install prometheus, so it would be expected to find it)

There's some other libraries listed that also don't have a find script. Sorry for no PR on this, CMake scripting is outside my wheelhouse.

**Comment by KangLin** [comment]
Fix in #1315
