### ISSUE TITLE
401 Unauthorized Problem

### ISSUE THREAD

**Issue by alperentokgoz** [coturn/coturn#1309]
Hi, I'm having problems after the coturn upgrade. That's why I wanted to open this thread as an issue. I'm trying to find the source of the problem here. can you help me for this?  @misi @eakraly 

I am using Mariadb, the only difference with the old version is the 0: (30970): INFO: MySQL is not supported status in the turnserver output (old version 4.5.x INFO: MySQL supported.). However, I think this should not have an effect.

turnserver.conf
```

> listening-port=3478
> tls-listening-port=443
> alt-listening-port=3479
> alt-tls-listening-port=444
> listening-ip=my_ip
> listening-ip=10.34.1.11
> relay-ip=my_ip
> external-ip=my_ip
> verbose
> lt-cred-mech
> fingerprint
> mysql-userdb="host=db_ip dbname=db_name user=db_user password=db_pass port=3306 connect_timeout=db_timeout"
> secret-key-file=key
> realm=realm
> cert=cert.pem
> pkey=pkey.pem

```

turn log
```

> INFO: IPv4. CLI connected to: 127.0.0.1:14309
> INFO: IPv4. CLI session disconnected from: 127.0.0.1:14309
> INFO: UDP notifier parameters: host=localhost port=5555
> INFO: session 001000001000000002: realm <realm> user <>: incoming packet message processed, error 401: Unauthorized
> ERROR: check_stun_auth: Cannot find credentials of user <k98hce76d57c930a0d089da0f78cb73dab8d4h5c>
> INFO: session 001000001000000002: realm <realm> user <k98hce76d57c930a0d089da0f78cb73dab8d4h5c>: incoming packet message processed, error 401: Unauthorized
> INFO: IPv4. CLI connected to: 127.0.0.1:14439
> INFO: IPv4. CLI session disconnected from: 127.0.0.1:14439
> INFO: session 001000001000000002: usage: realm=<realm>, username=<k98hce76d57c930a0d089da0f78cb73dab8d4h5c>, rp=3, rb=176, sp=3, sb=308
> INFO: session 001000001000000002: peer usage: realm=<realm>, username=<k98hce76d57c930a0d089da0f78cb73dab8d4h5c>, rp=0, rb=0, sp=0, sb=0
> INFO: session 001000001000000002: closed (2nd stage), user <k98hce76d57c930a0d089da0f78cb73dab8d4h5c> realm <realm> origin <>, local xx.xxx.xxx.xx:3478, remote ip:port, reason: allocation watchdog determined stale session state
> INFO: IPv4. CLI connected to: 127.0.0.1:14679
> INFO: IPv4. CLI session disconnected from: 127.0.0.1:14679

```

turnserver
`

> [root@root1-1 adm]# turnserver
> 0: (30970): INFO: System cpu num is 4
> 0: (30970): INFO: log file opened: /var/log/turn_30970_2023-11-02.log
> 0: (30970): INFO: System enable num is 4
> 0: (30970): WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
> 0: (30970): INFO: Coturn Version Coturn-4.6.2 'Gorst'
> 0: (30970): INFO: Max number of open files/sockets allowed for this process: 4096
> 0: (30970): INFO: Due to the open files/sockets limitation, max supported number of TURN Sessions possible is: 2000 (approximately)
> 0: (30970): INFO:
> 
> ==== Show him the instruments, Practical Frost: ====
> 
> 0: (30970): INFO: OpenSSL compile-time version: OpenSSL 1.1.1k  FIPS 25 Mar 2021 (0x101010bf)
> 0: (30970): INFO: TLS 1.3 supported
> 0: (30970): INFO: DTLS 1.2 supported
> 0: (30970): INFO: TURN/STUN ALPN supported
> 0: (30970): INFO: Third-party authorization (oAuth) supported
> 0: (30970): INFO: GCM (AEAD) supported
> 0: (30970): INFO: SQLite is not supported
> 0: (30970): INFO: Redis is not supported
> 0: (30970): INFO: PostgreSQL is not supported
> 0: (30970): INFO: MySQL is not supported
> 0: (30970): INFO: MongoDB is not supported
> 0: (30970): INFO: Default Net Engine version: 3 (UDP thread per CPU core)
> 0: (30970): INFO: Domain name:
> 0: (30970): INFO: Default realm:
> 0: (30970): ERROR: CONFIG: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
> 0: (30970): WARNING: cannot find certificate file: cert.pem (1)
> 0: (30970): WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
> 0: (30970): WARNING: cannot find private key file: pkey.pem (1)
> 0: (30970): WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
> 0: (30970): INFO: Certificate file found: /home/adm/cert.pem
> 0: (30970): INFO: Private key file found: /home/adm/pkey.pem
> 

`

wireshark
![image](https://github.com/coturn/coturn/assets/100135283/d4992771-8478-4c5a-87db-9f4b70898ec2)

**Comment by eakraly** [comment]
Hi @alperentokgoz 
`MySQL is not supported` means that MariaDB is also not supported and your credentials are not used.
If you build coturn yourself pls make sure to satisfy dependencies to have MySQL/MariaDB support

**Comment by alperentokgoz** [comment]
Thank you for this @eakraly
