### ISSUE TITLE
instability

### ISSUE THREAD

**Issue by 741680193** [coturn/coturn#1317]
![微信截图_20231114154640](https://github.com/coturn/coturn/assets/71587111/7f836f6d-8ddd-445f-a4e6-343e769852e8)
![微信截图_20231114154756](https://github.com/coturn/coturn/assets/71587111/95db5538-95bf-4a71-ace4-5981dc929388)

**Comment by KangLin** [comment]
Refactoring in progress　#1301 
You use it for testing and send me the logs.
