### ISSUE TITLE
TURNSERVER connection error.. error occurs while running TURNSERVER

### ISSUE THREAD

**Issue by KartikRajaS** [coturn/coturn#132]
user=root:o******
listening-port=2434
listening-ip=192.168.1.1 \local ip
relay-ip=192.168.1.1 \local ip
external-ip=

turnserver.config

this is my config file when is run listening ip with local ip address no error occurs.. but when i replace it with mu public ip or server's ip i am getting the same below mentioned error..

Can any one please guide me to start the turnserver without any error..

ERror OCcured..............
0: Trying to bind fd 14 to <my_server_public_IP:3478>: errno=99
Cannot bind local socket to addr: Cannot assign requested address
0: Cannot bind UDP/DTLS listener socket to addr <my_server_public_IP:3478>:3478
0: Trying to bind UDP/DTLS listener socket to addr <my_server_public_IP:3478>:3478, again...
0: Trying to bind fd 15 to <my_server_public_IP:3478>: errno=99
Cannot bind local socket to addr: Cannot assign requested address
0: Cannot bind TCP/TLS listener socket to addr <my_server_public_IP:3478>:3478
0: Trying to bind TCP/TLS listener socket to addr <my_server_public_IP:3478>, again...
..............................................................................................

**Comment by ckurapati** [comment]
we have same issue...can some one help us.

**Comment by rojarand** [comment]
Setting explicitly network engine type to 1 or 2 helped for me. Try add ne=1 or ne=2 in your turnserver.config.

**Comment by RamyaAshika** [comment]
Can you please explain this clearly @rojarand because I'm also facing the same issue.

**Comment by eakraly** [comment]
This issue is 4 years old...
If the problem is still relevant please open a new issue.
