### ISSUE TITLE
Coturn leaks sensitive information

### ISSUE THREAD

**Issue by jjesusglia** [coturn/coturn#1331]
Using https://github.com/firefart/stunner, I'm able to retrieve **coturn** software version, protocols, response-origin and realms.

Example:

```
[27/11/23 10:26:17] ➜  stunner git:(main) ./stunner info -s <turn addr>:443
INFO[0000] this server supports the STUN protocol
INFO[0000] Attributes:
INFO[0000] 	RESPONSE-ORIGIN:  <turn addr>:443
INFO[0000] 	SOFTWARE: Coturn-4.6.2 'Gorst'
INFO[0000] this server supports the TURN protocol with UDP transports
INFO[0000] Attributes:
INFO[0000] 	REALM:  <turn realm>
INFO[0000] 	SOFTWARE: Coturn-4.6.2 'Gorst'
INFO[0000] this server supports the TURN protocol with TCP transports
INFO[0000] Attributes:
INFO[0000] 	REALM:  <turn realm>
INFO[0000] 	SOFTWARE: Coturn-4.6.2 'Gorst'
```

Is it possible to hide this using a flag? If not, is there any feature planned to turn this on/off via a flag?

Thanks!

**Comment by kadoshita** [comment]
@jjesusglia You can hide this information by no-software-attribute flag.
https://github.com/coturn/coturn/blob/master/README.turnserver#L171

**Comment by jjesusglia** [comment]
This issue can now be closed, thanks @kadoshita.
