### ISSUE TITLE
My coturn-4.5.0.6 is not working with debian 8.5

### ISSUE THREAD

**Issue by reachingfdreams** [coturn/coturn#134]
Hi All!

Could you please help me to figure out why my COTURN is not working?
I have tried clone the lastest src from github and build COTURN in my sandbox Debian 8.5 and my turnserver.conf file as follows:

listening-device=eth0
verbose
Verbose
no-auth
userdb=/var/db/turndb
max-bps=3000000
no-stdout-log
stun-only
log-file=/var/log/turnserver/turnserver.log

List of essential packages were installed before building:
fakeroot
checkinstall
debhelper
devscripts
dh-autoreconf
git
automake
autoconf
erlang
build-essential
libssl-dev
libevent-dev
libexpat-dev
libyaml-dev

After successfully building, I installed on my sandbox and try to test it using javascript code running on Google Chrome.
And I did not see any candidate with: "typ srflx".

function checkCoTURNServer(turnConfig, timeout){ 
  return new Promise(function(resolve, reject){
    setTimeout(function(){
        if(promiseResolved) return;
        resolve(false);
        promiseResolved = true;
    }, timeout || 10000);

    var promiseResolved = false
      , myPeerConnection = window.RTCPeerConnection || window.mozRTCPeerConnection || window.webkitRTCPeerConnection   //compatibility for firefox and chrome
      , pc = new myPeerConnection({iceServers:[turnConfig]})
      , noop = function(){};
    pc.createDataChannel("");    //create a bogus data channel
    pc.createOffer(function(sdp){
	  console.log(sdp.sdp);
      pc.setLocalDescription(sdp, noop, noop);
    }, noop);    // create offer and set local description
    pc.onicecandidate = function(ice){  //listen for candidate events
	  console.log(ice.candidate.candidate);
    };
  });   
}

checkCoTURNServer({
    url: 'stun:10.3.4.40:3478'
}).then(function(bool){
    console.log('is TURN server active? ', bool? 'yes':'no');
}).catch(console.error.bind(console));

Following is contents of turnserver.log:

220: log file opened: /var/log/turnserver/turnserver_2017-05-19.log
220: log file reopened: /var/log/turnserver/turnserver_2017-05-19.log
220: timer_event_handler: timeout 0x2498290: timer_handler
221: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
221: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
221: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
221: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
221: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
221: timer_event_handler: timeout 0x2498290: timer_handler
222: timer_event_handler: timeout 0x24991b0: rtcp_map_timeout_handler
222: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
222: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
222: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
222: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
222: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
222: timer_event_handler: timeout 0x2498290: timer_handler
223: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
223: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
223: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
223: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
223: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
223: timer_event_handler: timeout 0x2498290: timer_handler
224: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
224: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
224: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
224: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
224: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
224: timer_event_handler: timeout 0x2498290: timer_handler
225: timer_event_handler: timeout 0x24991b0: rtcp_map_timeout_handler
225: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
225: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
225: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
225: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
225: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
225: udp_server_input_handler:628:start
225: handle_udp_packet: New UDP endpoint: local addr 10.3.4.40:3478, remote addr 10.0.12.47:56718
225: open_client_connection_session:4613:start
225: read_client_connection:4414:start
225: read_client_connection: data.buffer=0x7f59e400380c, data.len=20
225: handle_turn_binding:2701:start
225: handle_turn_binding:2888:end
225: session 000000000000000008: realm <> user <>: incoming packet BINDING processed, success
225: write_client_connection:4223:end
225: read_client_connection:4520:end
225: open_client_connection_session:4647:end
225: udp_server_input_handler:666:end
225: timer_event_handler: timeout 0x2498290: timer_handler
226: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
226: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
226: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
226: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
226: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
226: timer_event_handler: timeout 0x2498290: timer_handler
227: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
227: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
227: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
227: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
227: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
227: timer_event_handler: timeout 0x2498290: timer_handler
228: timer_event_handler: timeout 0x24991b0: rtcp_map_timeout_handler
228: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
228: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
228: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
228: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
228: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
228: timer_event_handler: timeout 0x7f59e40183c0: client_to_be_allocated_timeout_handler
228: client_to_be_allocated_timeout_handler:4165:start
228: shutdown_client_connection:4080:start
228: closing session 0x7f59e4013980, client socket 0x7f59e4013810 (socket session=0x7f59e4013980)
228: shutdown_client_connection:4145:end
228: client_to_be_allocated_timeout_handler:4195:end
228: timer_event_handler: timeout 0x2498290: timer_handler
229: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
229: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
229: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
229: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
229: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
229: timer_event_handler: timeout 0x2498290: timer_handler
230: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
230: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
230: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
230: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
230: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
230: timer_event_handler: timeout 0x2498290: timer_handler
231: timer_event_handler: timeout 0x24991b0: rtcp_map_timeout_handler
231: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
231: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
231: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
231: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
231: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
231: timer_event_handler: timeout 0x2498290: timer_handler
232: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
232: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
232: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
232: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
232: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
232: timer_event_handler: timeout 0x2498290: timer_handler
233: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
233: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
233: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
233: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
233: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
233: timer_event_handler: timeout 0x2498290: timer_handler
234: timer_event_handler: timeout 0x24991b0: rtcp_map_timeout_handler
234: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
234: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
234: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
234: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
234: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
234: timer_event_handler: timeout 0x2498290: timer_handler
235: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
235: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
235: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
235: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
235: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
235: udp_server_input_handler:628:start
235: handle_udp_packet: New UDP endpoint: local addr 10.3.4.40:3478, remote addr 10.0.12.47:56718
235: open_client_connection_session:4613:start
235: read_client_connection:4414:start
235: read_client_connection: data.buffer=0x7f59e400380c, data.len=20
235: handle_turn_binding:2701:start
235: handle_turn_binding:2888:end
235: session 000000000000000009: realm <> user <>: incoming packet BINDING processed, success
235: write_client_connection:4223:end
235: read_client_connection:4520:end
235: open_client_connection_session:4647:end
235: udp_server_input_handler:666:end
235: timer_event_handler: timeout 0x2498290: timer_handler
236: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
236: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
236: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
236: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
236: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
236: timer_event_handler: timeout 0x2498290: timer_handler
237: timer_event_handler: timeout 0x24991b0: rtcp_map_timeout_handler
237: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
237: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
237: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
237: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
237: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
237: timer_event_handler: timeout 0x2498290: timer_handler
238: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
238: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
238: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
238: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
238: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
238: timer_event_handler: timeout 0x7f59e40183c0: client_to_be_allocated_timeout_handler
238: client_to_be_allocated_timeout_handler:4165:start
238: shutdown_client_connection:4080:start
238: closing session 0x7f59e4013980, client socket 0x7f59e4013810 (socket session=0x7f59e4013980)
238: shutdown_client_connection:4145:end
238: client_to_be_allocated_timeout_handler:4195:end
238: timer_event_handler: timeout 0x2498290: timer_handler
239: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
239: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
239: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
239: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
239: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
239: timer_event_handler: timeout 0x2498290: timer_handler
240: timer_event_handler: timeout 0x24991b0: rtcp_map_timeout_handler
240: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
240: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
240: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
240: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
240: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
240: run_listener_server: cycle=49
240: timer_event_handler: timeout 0x2498290: timer_handler
241: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
241: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
241: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
241: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
241: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
241: timer_event_handler: timeout 0x2498290: timer_handler
242: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
242: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
242: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
242: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
242: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
242: udp_server_input_handler:628:start
242: handle_udp_packet: New UDP endpoint: local addr 10.3.4.40:3478, remote addr 10.0.12.47:63516
242: open_client_connection_session:4613:start
242: read_client_connection:4414:start
242: read_client_connection: data.buffer=0x7f59e400380c, data.len=20
242: handle_turn_binding:2701:start
242: handle_turn_binding:2888:end
242: session 000000000000000010: realm <> user <>: incoming packet BINDING processed, success
242: write_client_connection:4223:end
242: read_client_connection:4520:end
242: open_client_connection_session:4647:end
242: udp_server_input_handler:666:end
242: timer_event_handler: timeout 0x2498290: timer_handler
243: timer_event_handler: timeout 0x24991b0: rtcp_map_timeout_handler
243: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
243: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
243: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
243: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
243: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
243: timer_event_handler: timeout 0x2498290: timer_handler
244: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
244: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
244: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
244: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
244: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
244: timer_event_handler: timeout 0x2498290: timer_handler
245: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
245: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
245: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
245: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
245: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
245: timer_event_handler: timeout 0x7f59e40183c0: client_to_be_allocated_timeout_handler
245: client_to_be_allocated_timeout_handler:4165:start
245: shutdown_client_connection:4080:start
245: closing session 0x7f59e4013980, client socket 0x7f59e4013810 (socket session=0x7f59e4013980)
245: shutdown_client_connection:4145:end
245: client_to_be_allocated_timeout_handler:4195:end
245: udp_server_input_handler:628:start
245: handle_udp_packet: New UDP endpoint: local addr 10.3.4.40:3478, remote addr 10.0.12.47:56718
245: open_client_connection_session:4613:start
245: read_client_connection:4414:start
245: read_client_connection: data.buffer=0x7f59e400380c, data.len=20
245: handle_turn_binding:2701:start
245: handle_turn_binding:2888:end
245: session 000000000000000011: realm <> user <>: incoming packet BINDING processed, success
245: write_client_connection:4200:start
245: write_client_connection: prepare to write to s 0x7f59e4013810
245: write_client_connection:4223:end
245: read_client_connection:4520:end
245: open_client_connection_session:4647:end
245: udp_server_input_handler:666:end
245: timer_event_handler: timeout 0x2498290: timer_handler
246: timer_event_handler: timeout 0x24991b0: rtcp_map_timeout_handler
246: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
246: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
246: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
246: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
246: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
246: timer_event_handler: timeout 0x2498290: timer_handler
247: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
247: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
247: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
247: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
247: timer_event_handler: timeout 0x7f59e0001e30: timer_handler
247: timer_event_handler: timeout 0x2498290: timer_handler
248: timer_event_handler: timeout 0x7f59e4001c90: timer_handler
248: timer_event_handler: timeout 0x7f59e4002df0: timer_timeout_handler
248: timer_event_handler: timeout 0x7f59dc001c90: timer_handler
248: timer_event_handler: timeout 0x7f59dc002df0: timer_timeout_handler
248: timer_event_handler: timeout 0x7f59e0001e30: timer_handler

**Comment by wangbing8895** [comment]
I also met this error! Have you solved the problem yet?help me
