### ISSUE TITLE
Why does MSVC build use `HeapAlloc` over `malloc` ?

### ISSUE THREAD

**Issue by jonesmz** [coturn/coturn#1358]
mainrelay.c has
```
#if defined(WINDOWS)
    #include <Iphlpapi.h>

    #define WORKING_BUFFER_SIZE 15000
    #define MAX_TRIES 3

    #define MALLOC(x) HeapAlloc(GetProcessHeap(), 0, (x))
    #define FREE(x) HeapFree(GetProcessHeap(), 0, (x))
#endif
```
but microsoft supports the malloc function, so why define these macros?

https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/malloc?view=msvc-170

**Comment by KangLin** [comment]
Because the some API of windows must need HeapAlloc. ag: GetAdaptersAddresses

**Comment by jonesmz** [comment]
The documentation for GetAdaptersAddresses states that any memory allocation mechanism can be used as long as the matching deallocation mechanism is used.

To the best of my knowedge, these macros are not needed, and should be replaced with calls to malloc and free directly.

**Comment by KangLin** [comment]
The example in the docs is HeapAlloc. so I think it's better to keep it.

**Comment by jonesmz** [comment]
> The example in the docs is HeapAlloc. so I think it's better to keep it.

I'm not understanding how that justifies using a non-standard allocation function?

It's just an example. The document clearly says that any method of acquiring a buffer is fine.

**Comment by jonesmz** [comment]
Quoting from the documentation:

https://learn.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getadaptersaddresses

> Addresses are returned as a linked list of [IP_ADAPTER_ADDRESSES](https://learn.microsoft.com/en-us/windows/desktop/api/iptypes/ns-iptypes-ip_adapter_addresses_lh) structures in the buffer pointed to by the AdapterAddresses parameter. The application that calls the GetAdaptersAddresses function must allocate the amount of memory needed to return the IP_ADAPTER_ADDRESSES structures pointed to by the AdapterAddresses parameter. When these returned structures are no longer required, the application should free the memory allocated. This can be accomplished by calling the [HeapAlloc](https://learn.microsoft.com/en-us/windows/desktop/api/heapapi/nf-heapapi-heapalloc) function to allocate memory and later calling the [HeapFree](https://learn.microsoft.com/en-us/windows/desktop/api/heapapi/nf-heapapi-heapfree) function to free the allocated memory, as shown in the example code. **Other memory allocation and free functions can be used as long as the same family of functions are used for both the allocation and the free function.**

Emphasis mine

**Comment by KangLin** [comment]
@jonesmz 
Learn more about the difference between HeapAlloc and malloc.

**Comment by jonesmz** [comment]
> @jonesmz Learn more about the difference between HeapAlloc and malloc.

That's an absolutely terrible response.

If there is some relevant difference, please feel free to enlighten me.

**Comment by KangLin** [comment]
Hehe, it's good if you're happy.

**Comment by jonesmz** [comment]
Unless you have some information to the contrary, i think it's reasonable to assume that `malloc()` is essentially implemented as `HeapAlloc(GetProcessHeap(), 0, (x))` on windows anyway.

As such, there's no reason to be calling `HeapAlloc` directly

**Comment by KangLin** [comment]
There is no absolute. You can change your mind if you want to.

**Comment by jonesmz** [comment]
> There is no absolute. You can change your mind if you want to.

Are you being intentionally flippant?

I'm trying to help make coturn better because it's got a lot of bugs that are effecting me directly.

Having random macros implementing standardized functions with no justification isn't helping me.

Can you provide some kind of justification for why `HeapAlloc` should be used instead of `malloc`? If so, please do so.

If you're just going to respond with another troll answer, then please don't bother.
