### ISSUE TITLE
COTURN in weird state  turnserver-4.5.0.3-CentOS7.1-x86

### ISSUE THREAD

**Issue by parnamis** [coturn/coturn#136]
Hi,

We have COTURN running successfully over 2 months and we have started seeing some issues on it.
1) Logging from coturn is stopped to log file.
2) No significant network traffic but observing a lot of interrupts and context switching (e.g. below)

vmstat 5
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 8  0      0 13386588 127172 2213356    0    0     0     1    0    0  4 13 82  0  1
 3  0      0 13388724 127172 2213096    0    0     0     0 99409 413616 13 50 36  0  0
 4  0      0 13388252 127172 2212812    0    0     0     2 98654 409224 13 50 37  0  0
 5  0      0 13387280 127172 2213020    0    0     0     1 98472 422886 14 50 36  0  0
 4  0      0 13388136 127172 2212812    0    0     0     2 99253 409356 13 50 37  0  0
 6  0      0 13387976 127172 2213364    0    0     0     0 102751 406674 13 49 37  0  0
 6  0      0 13388036 127172 2213340    0    0     0     4 99067 422938 13 50 36  0  0
 6  0      0 13388632 127172 2213300    0    0     0     4 100172 393625 14 49 37  0  0
 8  0      0 13384968 127172 2213364    0    0     0     0 98694 409881 13 50 36  0  0
 7  0      0 13385660 127172 2213864    0    0     0     7 99689 423639 13 51 36  0  0
 6  0      0 13386232 127172 2213340    0    0     0     9 102011 409450 13 49 37  0  0
 6  0      0 13385396 127172 2213468    0    0     0     1 101015 422359 14 50 36  0  0
 6  0      0 13386424 127172 2213788    0    0     0     7 105773 402658 14 48 38  0  0
 7  0      0 13386852 127172 2212868    0    0     0     0 103496 389802 14 47 38  0  1
 7  0      0 13386448 127172 2214096    0    0     0    14 101776 419647 14 50 36  0  0
 6  0      0 13385504 127172 2213948    0    0     0    89 95287 404751 13 50 36  0  1
 6  0      0 13387228 127172 2213456    0    0     0    27 101850 402241 13 49 38  0  0
 8  0      0 13386696 127172 2213704    0    0     0     0 96170 403354 14 50 36  0  0
 6  0      0 13387724 127172 2213192    0    0     0    11 97979 419021 14 50 36  0  0
 7  0      0 13386584 127172 2213916    0    0     0     8 96110 416838 14 50 35  0  0
 2  0      0 13385748 127172 2214000    0    0     0     0 100817 387224 14 48 38  0  0
 6  0      0 13384820 127172 2213996    0    0     0    19 104365 412482 14 49 37  0  0
 7  0      0 13385332 127172 2213984    0    0     0     3 104122 402506 13 49 38  0  0
 5  0      0 13386116 127172 2213572    0    0     0     0 97027 409117 14 50 36  0  0
 5  0      0 13386240 127172 2214044    0    0     0     4 98339 417938 13 50 36  0  0
 4  0      0 13386148 127172 2213700    0    0     0     0 98382 407609 14 50 36  0  0
 6  0      0 13386904 127172 2213976    0    0     0     2 99328 400466 13 49 37  0  0
 5  0      0 13387596 127172 2214200    0    0     0     1 105858 414736 13 49 37  0  0
 4  0      0 13387776 127172 2213712    0    0     0     4 102729 417757 13 50 37  0  0

PS: we are keeping system in same state if more info needed.
Its running on VM with below configuration.
16GB RAM and 8 VCPUs

**Comment by mom040267** [comment]
We suggest migrating to the latest Coturn version, there were some
potential problems fixed since 4.5.0.3

Oleg

**Comment by misi** [comment]
@parnamis  
I an closing this issue because we did not receive any further comment. Please reopen or open new if you still have issues with the latest git version.
