### ISSUE TITLE
STATUS still lists short-term crendentials as being implemented

### ISSUE THREAD

**Issue by OrangeDog** [coturn/coturn#138]
> 19) Short-term credentials mechanism implemented.

Though as far as I can tell they were removed in version 4.4.1.1

> The server-side short-term credentials mechanism support cancelled;

**Comment by OrangeDog** [comment]
Also still seems to be documented as if it existed
https://github.com/coturn/coturn/blob/master/README.turnserver#L592

**Comment by eakraly** [comment]
Status file updated
