### ISSUE TITLE
Can the minimum required version of cmake be changed?

### ISSUE THREAD

**Issue by jonesmz** [coturn/coturn#1384]
Currently the minimum required version of cmake is set to 3.5. This is *very* old, being the version shipped in Ubuntu 14.04.

CentOS 7 (which becomes end of life June 2024) ships cmake 3.8 http://mirror.centos.org/centos/7/os/x86_64/Packages/
CentOS 8 is apparently already end-of-life?

Ubuntu 18.04 LTS ships CMake 3.10 https://launchpad.net/ubuntu/bionic/+source/cmake

Ideally we can set the minimum version to 3.14, which was released almost 5 years ago (3.13 was released over 5 years ago), or even newer.

Does the project have a listing of specific platforms with specific release versions that are supposed to be supported? I think coturn should set the minimum required version of cmake to the oldest of the supported platforms and no older.

**Comment by KangLin** [comment]
There are currently no features in the higher version of cmake.


> Does the project have a listing of specific platforms with specific release versions that are supposed to be supported? I think coturn should set the minimum required version of cmake to the oldest of the supported platforms and no older.

Agree!

**Comment by jonesmz** [comment]
> There are currently no features in the higher version of cmake.

Could you clarify what you mean here?

There are an enormous number of features in versions of cmake newer than 3.5 that aren't available in 3.5.

But I'm not going to try to re-work the cmake code to take advantage of these features if the PR would be rejected due to needing to support some specific version of AIX from 15 years ago.

**Comment by KangLin** [comment]
As you thought, compatibility was in mind at the time, so I amn't used the feature that the higher version of cmake.

**Comment by jonesmz** [comment]
Right, that makes sense.

If I could wave a magic wand, i would say to set the minimum cmake version to whatever the oldest version supported by the latest release of redhat enterprise linux, latest LTS ubuntu, or latest arch linux. If not that then just the latest release of cmake as of today.

But i have no idea what level of backwards compatibility support the project maintainers want with bizare older systems.

So i would like some kind of authoritative answer on how conservative the project wants to be before i make a PR.

**Comment by KangLin** [comment]
There is no authoritative answer. The two main authors are no longer maintained.
Starting with the next release, I want to refactor the code. #1327











At 2024-01-18 11:52:53, "Michael Jones" ***@***.***> wrote:

Right, that makes sense.

If I could wave a magic wand, i would say to set the minimum cmake version to whatever the oldest version supported by the latest release of redhat enterprise linux, latest LTS ubuntu, or latest arch linux. If not that then just the latest release of cmake as of today.

But i have no idea what level of backwards compatibility support the project maintainers want with bizare older systems.

So i would like some kind of authoritative answer on how conservative the project wants to be before i make a PR.

**Comment by jonesmz** [comment]
Then who has PR merge permission? Those would be the people who can provide an authoritative answer.

**Comment by KangLin** [comment]
@eakraly @ggarber has merge permission.

**Comment by eakraly** [comment]
Hi @jonesmz 
What features do you need in cmake that you are do not have now?

(I have an idea what can we do but want to hear the answer to the question above first)

**Comment by eakraly** [comment]
> There is no authoritative answer. The two main authors are no longer maintained.

@KangLin you are the author of cmake build - you should know :)
make is still the main mechanism to build coturn. We can update minimal cmake version to something more modern IMHO.
Today, the agent job that builds and validates cmake uses ubuntu 20.04 which bundles cmake 3.16 - we can use that version as minimal.

What do you think?

**Comment by KangLin** [comment]
> make is still the main mechanism to build coturn. 

IMHO. the make isnot a modern standard automake(Custom scripts from twenty years ago). 
Now cmake is works, so there's no need to keep maintaining it. I think 5.0.0 onwards, it could be removed.

> the agent job that builds and validates cmake uses ubuntu 20.04 which bundles cmake 3.16 - we can use that version as minimal.

It's a good idea to set it to a version that is supported by CI.

**Comment by jonesmz** [comment]
>  What features do you need in cmake that you are do not have now?

It's less about need and more about want. There are features in newer versions of cmake that make life a lot easier than 10 years ago.

Just off of the top of my head 

1. https://cmake.org/cmake/help/latest/generator/Ninja%20Multi-Config.html support for a single cmake build tree allowing to compile different configurations (e.g. debug, release, so on) was added in 3.17
2. Substantially more featureful and bug-free support for generation expressions
3. Support for build profiles defined in standalone json files, instead of directly in cmake's CMakeLists.txt
4. Improvements to support for unit tests via `ctest`

I use cmake at $dayjob, and have had to work with Kitware to get things fixed or improved in quite a few cases, so I dread trying to work with such an old version.

**Comment by eakraly** [comment]
> Now cmake is works, so there's no need to keep maintaining it. I think 5.0.0 onwards, it could be removed.

"Can be removed" as long as we convert all uses of make. Whether make is modern or standard is of no discussion - all legacy projects use legacy build systems and spending time in their modernization needs to be justified (even if we spend our own time on this)

Let's start with modernizing cmake since we are in agreement here?

**Comment by KangLin** [comment]
> "Can be removed" as long as we convert all uses of make. Whether make is modern or standard is of no discussion - all legacy projects use legacy build systems and spending time in their modernization needs to be justified (even if we spend our own time on this)

Ok! Current keep it. but next main version. it is remove.

> 
> Let's start with modernizing cmake since we are in agreement here?

Support cmake. The minimum version of cmake required is not an issue. Create CI first. The minimum version is same of the version of cmake in CI.

CI:
Windows
MinGW
Ubuntu
Macos

Other, Please add .....
