### ISSUE TITLE
Firefox 53 doesn't seem to like coturn

### ISSUE THREAD

**Issue by dbrgn** [coturn/coturn#140]
I'm not sure if this is related to coturn at all. But our setup that worked flawlessly until Firefox 52 (and under Chrome) doesn't seem to work anymore with Firefox 53.

I'm using coturn 4.5.0.3-1build1 on Debian 8. The configuration on the client side looks like this:

    'stun:stun.example.com:443',
    'turn:turn.example.com:443?transport=udp',
    'turn:turn.example.com:443?transport=tcp',

When setting up a peer connection, Firefox 53 complains:

> ICE failed, your TURN server appears to be broken, see about:webrtc for more details

Any ideas how to debug this?

**Comment by dbrgn** [comment]
I asked two other people to test this in their networks. It seems to work there with Firefox 53, so I'd assume it's either a problem in my network configuration or in Firefox 53. I'll close this for now, sorry for the hassle.

**Comment by mom040267** [comment]
Upgrade to the latest coturn version.
