### ISSUE TITLE
Improved stats

### ISSUE THREAD

**Issue by OrangeDog** [coturn/coturn#141]
The stats recorded by coturn lack some basic things I was expecting:

- Timing
    For example, "refreshed=777" is of little use unless you know when it was refreshed.
    You'd want to know both when the session started (especially when recording its end) and how long it's going to last unless its refreshed.
- Bandwidth usage
    For example, when a session is closed (or expires), record how many bytes were sent/received by each peer.

**Comment by ggarber** [comment]
There are many more metrics now exposed, expecially when prometheus is enabled so closing it for now.
