### ISSUE TITLE
upgrade to 4.6.2

### ISSUE THREAD

**Issue by docjojo** [coturn/coturn#1417]
Hello,

why does 

`apt install coturn`

respond already newest version, where on project site it is 4.6.2 ?

`coturn is already the newest version (4.5.2-3.1~ubuntu22.04.1).`

Tnx.

**Comment by jonesmz** [comment]
The package provided by a specific distribution of linux (In your case, ubuntu 22.04) is not controlled by the Coturn project.

Please redirect this request to the Ubuntu bug tracker or customer service team.

**Comment by docjojo** [comment]
Thanks. 
Tried to build and install 4.6.2 and `/usr/local/bin/turnserver` works, but running as deamon with same config fails with timeout.

**Comment by jonesmz** [comment]
Note that the configuration file has changed between releases.

Try using the newer configuration file with whatever local changes you need.

**Comment by docjojo** [comment]
default config of newest version has no settings, it is all commented.
So where is the change?

Strange thing is, that changing `/usr/bin/turnserver` to `/usr/local/bin/turnserver` with `systemctl edit --full coturn` is with no luck, and after changing back even the old coturn version will not run anymore as deamon.

**Comment by jonesmz** [comment]
The list of options in the configuration file is not the same between releases.

Re-apply the settings that you want to have set in the new config file.

Nevertheless, I don't think that these issues are for the coturn project to solve, you probably would have better luck with stackoverflow.

**Comment by docjojo** [comment]
thank you.

**Comment by eakraly** [comment]
Hi @docjojo ! Hope you figured it out. If not, please reopen the issue. Thanks!
