### ISSUE TITLE
Some logging configuration file options don't work

### ISSUE THREAD

**Issue by OrangeDog** [coturn/coturn#142]
Even though the default config file has them listed, they don't do anything because logging is set up before the config is loaded. They only work if you put them on the command line.

So far I've found `simple-log`, `no-stdout-log` to be ineffective. I imagine there are others too.

**Comment by devnewton** [comment]
Same for _log-file_.

I just need stdout but it seems impossible to prevent coturn from writing logs where it wants :-) 

I am using coturn ubuntu 16.04 package:

> Package: coturn
> Version: 4.5.0.3-1build1
> Priority: extra
> Section: universe/net
> Origin: Ubuntu

**Comment by saphsoph88** [comment]
Hi All,

I've installed COTURN on AWS centos machine and I'm not that nerd in Linux. I want to perform stress testing and I want to see the live logs, not just the logs that are stored in the log file as I want to see all the details and consumption of the service live.

is there any way to achieve this ?!

Respect,
Mustapha

**Comment by misi** [comment]
@OrangeDog  Could you please retest it with the actual master branch?
There are fixes regarding logs.

**Comment by misi** [comment]
@devnewton If you want you can log to syslog and in syslog you could filter and redirect to /dev/null
Not log to anywhere is very edge case. The normal use case is to log somewhere. If you think it is still need then please send Pull Request.

**Comment by misi** [comment]
@saphsoph88 Try to use -V or -v flag with turnserver to see the logs
I think you should also use the --cli-password commands to set password, and try to login to cli...

**Comment by eakraly** [comment]
Hi @saphsoph88 @OrangeDog
If you still have issues with logs - please open a new issue
