### ISSUE TITLE
turnadmin opens log file with no control over it

### ISSUE THREAD

**Issue by OrangeDog** [coturn/coturn#143]
If for example you use the `--psql-userdb` option, `turnadmin` will create a log file so it can tell you about it.
```
0: log file opened: /var/tmp/turn_7625_2017-05-31.log
0: PostgreSQL DB connection success: host=... dbname=... user=... password=... connect_timeout=...
```
However, it does not support any of the logging control options, so you cannot stop it or anything.

**Comment by misi** [comment]
Can you please send a PR?
Unfortunately it is a generic issue See issue #272 
I will merge it with #272 to avoid duplicate.
Let's continue on it..
