### ISSUE TITLE
Link Error : netengine.c:(.text+0x5f9b): undefined reference to `evthread_use_pthreads'

### ISSUE THREAD

**Issue by linwenchen** [coturn/coturn#1448]
1. When i use `cmake .. && make` command to  build coturn. some errors happen.
```bash
[ 81%] Linking C executable ../../../bin/turnserver
/usr/bin/ld: CMakeFiles/turnserver.dir/netengine.c.o: in function `setup_server':
netengine.c:(.text+0x5f9b): undefined reference to `evthread_use_pthreads'
collect2: error: ld returned 1 exit status
make[2]: *** [src/apps/relay/CMakeFiles/turnserver.dir/build.make:330: bin/turnserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:481: src/apps/relay/CMakeFiles/turnserver.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

2. And i found this -> [[Libevent Multithread Support](https://stackoverflow.com/questions/9153528/libevent-multithread-support)](https://stackoverflow.com/questions/9153528/libevent-multithread-support)

3. I try to modify `src/apps/common/CMakeLists.txt:42`, and it work well.
```cmake
# old
list(APPEND COMMON_LIBS libevent::core libevent::extra libevent::openssl)
# new
list(APPEND COMMON_LIBS libevent::core libevent::extra libevent::openssl libevent::pthreads)
```

INFOMATION:
> ```bash
> # lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 22.04.2 LTS
> Release:        22.04
> Codename:       jammy
> ```
> coturn : `Commit: 412788b120a8db0c9f9bc998b88892de39eb0ce7(master)`
> libevent version: [release-2.2.1-alpha](https://github.com/libevent/libevent/releases/tag/release-2.2.1-alpha)
> ```bash
> # libevent build command
> mkdir build && cd build && cmake .. -DEVENT__DISABLE_MBEDTLS=ON && make && make install
> ```

**Comment by linwenchen** [comment]
I did a test. When I build `libevent` by myself, `/usr/local/lib/cmake/libevent/LibeventConfig.cmake` is generated, which results in `line 41` being judged to be true. `COMMON_LIBS` does not add `libevent::pthreads`, which will cause compilation errors.

When I use `apt-get install libevent-dev` to install `libevent`, `apt-get` does not install `LibeventConfig.cmake` for me. It will use `coturn/cmake/LibeventConfig.cmake`.

The key point is that `lines 44-50` will be executed and used. This will add all components of libevent, `core extra openssl pthreads`, so it can work normally.

```cmake
# src/apps/common/CMakeLists.txt

find_package(Libevent CONFIG)
if(Libevent_FOUND)
    list(APPEND COMMON_LIBS libevent::core libevent::extra libevent::openssl)
else()
    find_package(Libevent MODULE)
    if(Libevent_FOUND)
        list(APPEND COMMON_LIBS ${Libevent_LIBRARIES})
        list(APPEND COMMON_INCLUDE_DIR ${Libevent_INCLUDE_DIRS})
    else()
        message(FATAL_ERROR "Must set Libevent")
    endif()
endif()
```

**Comment by ggarber** [comment]
I think it makes sense.  Thank you very much @linwenchen.   Can you create a Pull Request for that change?

Also @KangLin take a look if you have time.

**Comment by linwenchen** [comment]
This is my first PR on the public project coturn. Any feedback on my submission process is greatly appreciated!

**Comment by KangLin** [comment]
> When I use `apt-get install libevent-dev` to install `libevent`, `apt-get` does not install `LibeventConfig.cmake` for me. It will use `coturn/cmake/LibeventConfig.cmake`.

It is will use coturn/cmake/FindLibevent.cmake. your version of coturn?

**Comment by linwenchen** [comment]
> > When I use `apt-get install libevent-dev` to install `libevent`, `apt-get` does not install `LibeventConfig.cmake` for me. It will use `coturn/cmake/LibeventConfig.cmake`.
> 
> It is will use coturn/cmake/FindLibevent.cmake. your version of coturn?

coturn : Commit: 412788b120a8db0c9f9bc998b88892de39eb0ce7(master)

**Comment by KangLin** [comment]
> > > When I use `apt-get install libevent-dev` to install `libevent`, `apt-get` does not install `LibeventConfig.cmake` for me. It will use `coturn/cmake/LibeventConfig.cmake`.
> > 
> > 
> > It is will use coturn/cmake/FindLibevent.cmake. your version of coturn?
> 
> coturn : Commit: [412788b](https://github.com/coturn/coturn/commit/412788b120a8db0c9f9bc998b88892de39eb0ce7)(master)

It is coturn/cmake/FindLibevent.cmake .  typo?

**Comment by KangLin** [comment]
@ggarber  please merge #1466

**Comment by linwenchen** [comment]
> > > > When I use `apt-get install libevent-dev` to install `libevent`, `apt-get` does not install `LibeventConfig.cmake` for me. It will use `coturn/cmake/LibeventConfig.cmake`.
> > > 
> > > 
> > > It is will use coturn/cmake/FindLibevent.cmake. your version of coturn?
> > 
> > 
> > coturn : Commit: [412788b](https://github.com/coturn/coturn/commit/412788b120a8db0c9f9bc998b88892de39eb0ce7)(master)
> 
> It is coturn/cmake/FindLibevent.cmake . typo?


No. The problem is, when there's a default `LibeventConfig.cmake` file like `/usr/local/lib/cmake/libevent/LibeventConfig.cmake`, the check at `src/apps/common/CMakeLists.txt:41` thinks it's true. This causes the `libevent::pthreads` component not to be added.
