### ISSUE TITLE
error 401: Unauthorized help~ 

### ISSUE THREAD

**Issue by bestxpp** [coturn/coturn#1453]
### there is my config  deply on 10.0.5.25:

` cat turnserver.conf
#listening-ip=0.0.0.0

listening-port=3478

min-port=40000
max-port=60000

verbose

external-ip=10.0.5.25

lt-cred-mech
user=root:123456

log-file=/var/tmp/turn.log
#simple-log`

when  i use turnutils_uclient make a test ,it Unauthorized.

### turnutils_uclient -v -u root -w 123456 -s -y -p 3478 10.0.5.25
0: : IPv4. Connected from: 192.168.8.132:58392
0: : IPv4. Connected from: 192.168.8.132:58392
0: : IPv4. Connected to: 10.0.5.25:3478
0: : allocate sent
0: : allocate response received: 
0: : error 401 (Unauthorized)
0: : IPv4. Connected from: 192.168.8.132:36184
0: : IPv4. Connected to: 10.0.5.25:3478
0: : IPv4. Connected from: 192.168.8.132:59017
0: : IPv4. Connected to: 10.0.5.25:3478
0: : IPv4. Connected from: 192.168.8.132:41156
0: : IPv4. Connected to: 10.0.5.25:3478
0: : IPv4. Connected from: 192.168.8.132:37983
0: : IPv4. Connected to: 10.0.5.25:3478
0: : allocate sent
0: : allocate response received: 
0: : error 401 (Unauthorized)

How should I solve this problem?

**Comment by dangngoctam00** [comment]
I think you should add `realm=something` to your config file.

**Comment by bestxpp** [comment]
> I think you should add `realm=something` to your config file.

thx   you are right
