### ISSUE TITLE
[RFC7250] Raw public keys openssl functionality 

### ISSUE THREAD

**Issue by Nikolayshcx** [coturn/coturn#1456]
Hi guys, in our organization we're using the coturn server, and we need the raw public keys functionality of openssl 3.2.1 enabled. We've implemented a basic functionality switch with a configuration parameter, which in our tests looks like it's working so it'll be a good idea to add it to the official project.

**Comment by jonesmz** [comment]
You'd need to open a pull request with the changes so they can be reviewed and discussed.

**Comment by Nikolayshcx** [comment]
merged to master

**Comment by vdukhovni** [comment]
I don't see any code to actually *authenticate* the RPKs. Is that not needed for some reason?
As it is, it looks like raw public keys can be negotiated, but not verified.

**Comment by eakraly** [comment]
@vdukhovni RPK means those are not certificates but only pair of matching public/private keys

In that sense public key IS the authentication - meaning it has to be properly traced to the publisher (chain of trust does not include 3rd party CA).
For example, it is published on a website or distributed among clients by the provider. Once used you can be sure that only the provider can decrypt the traffic (and not rely on 3rd party CA)

**Comment by vdukhovni** [comment]
> @vdukhovni RPK means those are not certificates but only pair of matching public/private keys
> 
> In that sense public key IS the authentication - meaning it has to be properly traced to the publisher (chain of trust does not include 3rd party CA). For example, it is published on a website or distributed among clients by the provider. Once used you can be sure that only the provider can decrypt the traffic (and not rely on 3rd party CA)

You're mistaken. Authentication of presented public keys in OpenSSL is based on provided TLSA records (not necessarily from DNS, possibly locally sythesised, the `SSL_add_expected_rpk()` function was added to synthesise the requisite TLSA records when a set of possible expected public keys (EVP_PKEY objects) is available before the connection starts).

This implementation does not perform authentication of the RPKs.
