### ISSUE TITLE
REST API  problem...

### ISSUE THREAD

**Issue by GiantKs** [coturn/coturn#1461]
Because persistent account passwords are not secure at all on the web side, I was looking for a REST API way,

The first one I have seen in the literature describes that you can directly interact with coturn server, similar to coturn itself exposes a series of interfaces and uses http to call these interfaces, so as to achieve the purpose of dynamically adding and deleting turn users;

The other is to start the coturn server based on use-auth-secret, static-auth-secret, and then use the timestamp on either side to generate the expiration user (which I have already used);
I would like to know whether the first method can be realized?  thanks

**Comment by GiantKs** [comment]
supplement, these are the features (I didn't see them in the official conf file)
![image](https://github.com/coturn/coturn/assets/39474344/0481d838-f0cd-4680-8f45-f8e4f998fc3e)

**Comment by ggarber** [comment]
Yes, the first method (adding users to the coturn database) can be realized but you will end up exposing those persistent users and passwords in the web side and that's not desireable.

The recommended and most common way is the second approach (using a shared secret to generate temporal credentials with expiration).

This could be useful for you to understand how it works: https://medium.com/@BeingOttoman/coturn-rest-api-development-deployment-7bac065c64aa
