### ISSUE TITLE
Specifying a prometheus port results in segfault

### ISSUE THREAD

**Issue by alexg-axis** [coturn/coturn#1476]
When using the `--prometheus-port` flag, coturn fails to start and instead core dumps.

```
turnserver --prometheus --prometheus-port 9641
```

```
0: (362596): INFO: System cpu num is 5
0: (362596): INFO: log file opened: /var/log/turn_362596_2024-04-23.log
0: (362596): INFO: System enable num is 5
0: (362596): WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
Segmentation fault (core dumped)
```

Omitting the flag lets coturn start successfully.

Coturn version: 4.6.2
Prometheus library version: 5a518078b2ce7fcee72d6a7cdede314595525c5b
libmicrohttpd-dev version: 0.9.75-6

**Comment by dangngoctam00** [comment]
You should use `--prometheus-port=9641`

**Comment by alexg-axis** [comment]
Solved. Thanks.
