### ISSUE TITLE
bind: Cannot assign requested address

### ISSUE THREAD

**Issue by PaxtonPenguin** [coturn/coturn#1478]
i'm trying to set up coturn for something, and it dont work.

0: : Config file found: /etc/turnserver.conf
1: : Listener address to use: 66.41.76.224
1: : Config file found: /etc/turnserver.conf
1: :
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.6.1 'Gorst'
1: :
Max number of open files/sockets allowed for this process: 1048576
1: :
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
1: :

==== Show him the instruments, Practical Frost: ====

1: : TLS supported
1: : DTLS supported
1: : DTLS 1.2 supported
1: : TURN/STUN ALPN supported
1: : Third-party authorization (oAuth) supported
1: : GCM (AEAD) supported
1: : OpenSSL compile-time version: OpenSSL 3.0.10 1 Aug 2023 (0x300000a0)
1: :
1: : SQLite supported, default database location is /var/lib/turn/turndb
1: : Redis supported
1: : PostgreSQL supported
1: : MySQL supported
1: : MongoDB is not supported
1: :
1: : Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================
1: : Domain name:
1: : Default realm: turn.[redacted].com
1: : ERROR:
CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
1: : SSL23: Certificate file found: /etc/turnserver/fullchain.pem
1: : SSL23: Private key file found: /etc/turnserver/privkey.pem
1: : TLS1.0: Certificate file found: /etc/turnserver/fullchain.pem
1: : TLS1.0: Private key file found: /etc/turnserver/privkey.pem
1: : TLS1.1: Certificate file found: /etc/turnserver/fullchain.pem
1: : TLS1.1: Private key file found: /etc/turnserver/privkey.pem
1: : TLS1.2: Certificate file found: /etc/turnserver/fullchain.pem
1: : TLS1.2: Private key file found: /etc/turnserver/privkey.pem
1: : TLS cipher suite: DEFAULT
1: : Relay address to use: [dont look at my ip]
1: : pid file created: /var/run/turnserver.pid
1: : IO method (main listener thread): epoll (with changelist)
1: : INFO: RFC5780 disabled! /NAT behavior discovery/
1: : Wait for relay ports initialization...
1: :   relay [ip] initialization...
1: :   relay [ip] initialization done
1: : Relay ports initialization done
1: : IO method (general relay thread): epoll (with changelist)
1: : turn server id=2 created
bind: Cannot assign requested address
1: : Trying to bind fd 12 to <[ip]:3478>: errno=99
Cannot bind local socket to addr: Cannot assign requested address

thats the output from sudo turnserver/coturn (with website and ip blocked out)

server-name=turn.[webbysite].com
realm=turn.[waambysit].com
listening-ip=turn.[wombat sauce].com

listening-port=3478
min-port=10000
max-port=20000

verbose

use-auth-secret
static-auth-secret=[dont, just dont'

cert=/etc/turnserver/fullchain.pem
pkey=/etc/turnserver/privkey.pem

no-udp
#no-tls
no-dtls

and thats my config (website blocked out)

can anyone help me?

**Comment by PaxtonPenguin** [comment]
i'm also using ssh, if anyone was wondering

**Comment by eakraly** [comment]
Making a guess here @PaxtonPenguin 
You use hostname as the listening IP `listening-ip=turn.[wombat sauce].com` so that coturn resolves it to an actual IP using DNS and then, using resolved IP, tries to bind the socket to the address. That's where it fails.

Error 99 means `EADDRNOTAVAIL` which means this IP does not exist in your system
That means your DNS is not up to date - actual IP of the machine you run on does not match DNS record.
Try without specifying listening-ip and see if it works

**Comment by PaxtonPenguin** [comment]
that worked

**Comment by eakraly** [comment]
> that worked

Update your DNS or use some other way to specify listening IP
Or you can go without specifying IP and coturn will listen on all interfaces
