### ISSUE TITLE
Redis pubsub: no /traffic messages, but plenty of __XXX__

### ISSUE THREAD

**Issue by OrangeDog** [coturn/coturn#150]
According to [schema.stats.redis](https://github.com/coturn/coturn/blob/master/turndb/schema.stats.redis) there are supposed to be messages published with keys ending `/traffic`, but I see no such thing in practice.
What is seen, however, are messages with the key `__XXX__` and the message `__YYY__`, which look distinctly like someone forgot to fill in a placeholder...
```
$ redis-cli
127.0.0.1:6379> select 1
OK
127.0.0.1:6379[1]> psubscribe *
Reading messages... (press Ctrl-C to quit)
1) "psubscribe"
2) "*"
3) (integer) 1
1) "pmessage"
2) "*"
3) "turn/realm/local/user/test/allocation/000000000000000012/status"
4) "new lifetime=777"
1) "pmessage"
2) "*"
3) "__XXX__"
4) "__YYY__"
1) "pmessage"
2) "*"
3) "__XXX__"
4) "__YYY__"
```

**Comment by mom040267** [comment]
No, those ___XXX__ and ___YYY___ messages are not from coturn. Looks like
your redis somehow truncating the full message.

**Comment by OrangeDog** [comment]
Are you sure about that: https://github.com/coturn/coturn/blob/4.5.0.6/src/apps/relay/netengine.c#L1555

**Comment by mom040267** [comment]
Hm... that looks like a debug output. I'll check that.

**Comment by strannick-ru** [comment]
Debian 8, installed coturn and libhiredis0.10
Same problem.

Only /status messages in redis-cli, not /traffic.
And ___XXX__ and ___YYY___ messages

Its problem with package or something else?

**Comment by eakraly** [comment]
Those definitely look like placeholders for some events but not implemented - starting from the original source code import
I suggest removing this code as it does nothing and only adds load on redis

(and as my personal opinion - redis is not a monitoring system and should not be used as such. prometheus is much better interface and if anything - it is worth investing time improving prometheus metrics)

@ggarber what do you think?
Might also improve #913 just a tiny little bit

**Comment by eakraly** [comment]
#427 stays for the traffic publishing
