### ISSUE TITLE
Provide prebuilt binaries for various platforms

### ISSUE THREAD

**Issue by guoard** [coturn/coturn#1518]
I have noticed that the Debian package for Coturn is not frequently updated.

Could you consider providing prebuilt binaries for various platforms/architecture and hosting them on the GitHub releases page?

If you agree with this suggestion, I would be more than happy to contribute to this effort.

**Comment by eakraly** [comment]
Hi @guoard 
I think most of the users use docker package

And true, Debian is not updated frequently enough for a number of reasons
