### ISSUE TITLE
Random port periodically creates connection to coTURN and shutdown immediately 

### ISSUE THREAD

**Issue by dangngoctam00** [coturn/coturn#1519]
Hello, when checking log of coTURN, I see that there are many connections from random port which connect to coTURN and close immediately, as a result, coTURN log and send message to redis.
Here is the result of wireshark:
![image](https://github.com/coturn/coturn/assets/58434052/c95fb787-6e35-45e8-a9fd-1eb93f1cf18e)
Example log from coTURN:
```bash
1293: (18446744073709551615): INFO: shutdown_client_connection:4130:end
1313: (18446744073709551615): INFO: server_input_handler:80:start
1313: (18446744073709551615): INFO: IPv4. tcp or tls connected to: 127.0.0.1:53114
1313: (18446744073709551615): INFO: server_input_handler:117:end
1313: (18446744073709551615): INFO: open_client_connection_session:4644:start
1313: (18446744073709551615): INFO: open_client_connection_session:4675:end
1313: (18446744073709551615): INFO: session 005000000000000008: TCP socket closed remotely 127.0.0.1:53114
1313: (18446744073709551615): INFO: shutdown_client_connection:4059:start
1313: (18446744073709551615): INFO: closing session 0x102809200, client socket 0x101604580 (socket session=0x102809200)
1313: (18446744073709551615): INFO: session 005000000000000008: closed (2nd stage), user <> realm <127.0.0.1> origin <>, local 127.0.0.1:3478, remote 127.0.0.1:53114, reason: TCP connection closed by client (callback)
```
I don't know whether coTURN are running a job to check connectiviy for these random port? Thank you.

**Comment by eakraly** [comment]
Hi @dangngoctam00 
I'm not aware of any functionality that would do it

Maybe you have some external functionality that checks if turn is alive by creating connections to it?
That is something that AWS LB would do

**Comment by dangngoctam00** [comment]
Hi @eakraly , 
This is the result from my local machine, but it seems like not a big problem, so I will close this ticket. Thank you.
