### ISSUE TITLE
Use pkg-config

### ISSUE THREAD

**Issue by hvenev** [coturn/coturn#152]
```
pkg-config {--cflags,--libs} libevent libevent_pthreads libevent_openssl
pkg-config {--cflags,--libs} sqlite3
pkg-config {--cflags,--libs} mariadb
pkg-config {--cflags,--libs} libpq
pkg-config {--cflags,--libs} mongoc-1.0
pkg-config {--cflags,--libs} hiredis
```

This will remove most assumptions about the locations of headers/libraries and will stop the `-rpath` pollution.

Edit: [meson](http://mesonbuild.com/) seems like a nice build system. Should I submit a pull request with support for it?

**Comment by misi** [comment]
@hvenev 
AFAIK Oleg goal was to make possible to run on all platform. 
If you think pkg-config is not violating this rule then please send PR
