### ISSUE TITLE
Test client to allocate and listen

### ISSUE THREAD

**Issue by OrangeDog** [coturn/coturn#153]
Is there a way to get `testutils_uclient` to allocate and wait for data indications (which it then replies to) instead of initiating send indications to a configured peer?

If not, can such a tool be added?
I'm trying to test various ICE resolutions, but can't easily set up such an arrangement.

**Comment by ggarber** [comment]
This has been opened for a while and it looks like there is not a big interest on implementing it so closing it for now.  Please chime in if you think this is important to keep it open.
