### ISSUE TITLE
check_stun_auth: Cannot find credentials of user <123456:abc>

### ISSUE THREAD

**Issue by augustus-j** [coturn/coturn#1534]
There is a bug in the master branch which is breaking the authentication when we are using `use-auth-secret` and `static-auth-secret` in turnserver.conf.  

```
4837: (32): ERROR: session 001000000000000027: check_stun_auth: Cannot find credentials of user <1719824186:abc>
```

I did a git bisect to find the bad commit and found that it was introduced in commit `edebb9ad05556175cf7b688f2d1c92324ddcec00`.  If we revert this commit then coturn works fine.

**Comment by jonesmz** [comment]
This commit? https://github.com/coturn/coturn/commit/edebb9ad05556175cf7b688f2d1c92324ddcec00

**Comment by augustus-j** [comment]
> This commit? [edebb9a](https://github.com/coturn/coturn/commit/edebb9ad05556175cf7b688f2d1c92324ddcec00)

yes

**Comment by hudson-s** [comment]
I had the same bug，plz see   #1533

**Comment by jonesmz** [comment]
Would either of you be willing to create a unit test reproducing the problem?

**Comment by eakraly** [comment]
> Would either of you be willing to create a unit test reproducing the problem?

@augustus-j Thank you for the report
Ideally your turnserver.conf, turnserver command and turnutils_uclient command that can be used to repro the failure

That will help us dramatically
