### ISSUE TITLE
logfile clarification

### ISSUE THREAD

**Issue by ghost** [coturn/coturn#156]
Hello Devs.

I`m not sure how to persuade coturn to log only to the configured logfile (/var/log/turnserver.log) for example. I always end up with two logfiles even if i set "simple-log". I get the configured logfile + turn_pid_date.log.  Here is my config:

listening-port=443
alt-listening-port=3478
listening-ip=137...
relay-ip=137...
fingerprint
realm=spreedbox.local
total-quota=100
bps-capacity=0
no-loopback-peers
no-multicast-peers
log-file=/var/log/turnserver.log
simple-log

Any hints?

thanks and cheers

**Comment by benbro** [comment]
I have the same issue with Coturn 4.5.0.7.
I'm trying to use logrotate under ubuntu 18.04.

**Comment by eakraly** [comment]
OP account non-existent...
I've tested it with 4.5.2 and it works properly (only configured log file created)
