### ISSUE TITLE
wrong content for wiki page turnutils_stunclient

### ISSUE THREAD

**Issue by mateuszzz88** [coturn/coturn#157]
https://github.com/coturn/coturn/wiki/turnutils_stunclient contains info about turnutils_rfc5769check and not _stunclient. 
Additionally _rfc5769check is not actually available in latest release - is not copied to target after make install.

**Comment by misi** [comment]
* https://github.com/coturn/coturn/wiki/turnutils_stunclient is fixed now.
* You are correct that rfc5769 is no longer installed. I added some warning..
Thanks for the report.
