### ISSUE TITLE
Could not Trickle ICE server using external IP

### ISSUE THREAD

**Issue by AmitKasundra** [coturn/coturn#158]
Hello, I have setup Coturn server from Url https://www.webrtc-experiment.com/docs/TURN-server-installation-guide.html#coturn in **Ubuntu**.

Turnserver is working fine using local-ip, but when I try to trickle using exernal-ip I get error  **Not reachable?**

If I access turnserver from browser url I can access it using external-ip. I get message.

> **TURN Server**
> _https admin connection_
> 
> To use the HTTPS admin connection, you have to set the database table **_admin_user_** with the admin user accounts.

My **turnserver.conf** looks like:

> user=test:test123
> listening-port=3478 
> tls-listening-port=5349
> listening-ip=192.168.22.101
> relay-ip=192.168.22.101
> external-ip=202.137.12.10
> realm=yourdomain.com
> server-name=yourdomain.com
> lt-cred-mech
> userdb=/etc/turnuserdb.conf
> 
> cert=/etc/ssl/my-certificate.pem
> pkey=/etc/ssl/my-private.key
> no-stdout-log

My **turnuserdb.conf** looks like:
>
> test:test123
>

I am starting turn server using command:

> sudo turnserver -a

And I try to trickle using below format:

> turn:202.137.12.10:3478[test:test123]

**Trickle**: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

Please tell me where I am going wrong.

**Comment by mvsvolkov** [comment]
maybe it will helps, but problem likes we've got
in our situation we use router IP address and it start's to work, you could try something like this

external-ip=202.137.12.10**/192.168.22.1** (your router ip if exists)

**Comment by AmitKasundra** [comment]
Hi mvsvolkov, I got what was wrong, it turned out to be that UDP port 3478 was blocked.

Also I was able to get trickle if I used 
> turn:202.137.12.10:3478?transport=tcp[test:test123].

My external-ip looks like
> external-ip=202.137.12.10**(public ip)**/192.168.22.101**(local-ip)**

**Comment by chanhbc** [comment]
I have the same problem, I tried your way but did not work. Can you help me fix it?
```
listening-device=chanhbc
relay-device=chanhbc
listening-ip=192.168.1.109
listening-port=3478
tls-listening-port=5349
relay-ip=192.168.1.109
external-ip=27.72.61.237
relay-threads=50
lt-cred-mech
static-auth-secret=chanhbc
user=chanhbc:0x3dd53575688e2b9d126e89a336111b37
userdb=/etc/turnuserdb.conf
#max-bps=102400
pidfile="/var/run/turnserver.pid"
no-loopback-peers
no-multicast-peers
sha256
mobility
no-cli
cert=/etc/turn_server_cert.pem
pkey=/etc/turn_server_pkey.pem
stale-nonce
use-auth-secret
Verbose
fingerprint
```

**Comment by misi** [comment]
Try to remove **ALL** of these options:
- listening-device=chanhbc
- relay-device=chanhbc
- relay-threads=50
- userdb=/etc/turnuserdb.conf # THIS IS NOT an SQLITE db I guess!!
- mobility
- stale-nonce

**Comment by chanhbc** [comment]
i edited file.
My **/etc/turnserver.conf** looks like:
```
user=chanhbc:chanhbc
listening-port=3478
tls-listening-port=5349
listening-ip=192.168.1.109
relay-ip=192.168.1.109
external-ip=27.72.61.237/192.168.1.109
realm=yourdomain.com
server-name=yourdomain.com
lt-cred-mech
userdb=/etc/turnuserdb.conf

cert=/etc/ssl/my-certificate.pem
pkey=/etc/ssl/my-private.key
no-stdout-log
```
My **/etc/turnuserdb.conf** looks like:
```
chanhbc:chanhbc
```
I starting server use command:
```
sudo turnserver -a
```
And I try to trickle using below format:
```
turn:192.168.1.1.09:3478[chanhbc:chanhbc]
```
Results returned on the same computer:
![image](https://user-images.githubusercontent.com/16756220/39734420-7c0df98a-52a1-11e8-95a3-6567dea0b552.png)

Results returned on another computer:
![image](https://user-images.githubusercontent.com/16756220/39734378-5144e93e-52a1-11e8-9c9c-551816bfbdec.png)

And If i try to trickle using below format:
```
turn:27.72.61.237:3478[chanhbc:chanhbc]
```
result:
![image](https://user-images.githubusercontent.com/16756220/39734571-1221a70a-52a2-11e8-81d2-b03f961711ce.png)

![image](https://user-images.githubusercontent.com/16756220/39734548-f382fa74-52a1-11e8-8c41-6d8f9bc0d1cb.png)

Please tell me where I am going wrong. Sorry for my English not good.

**Comment by chanhbc** [comment]
@misi i try but not working

**Comment by MazenImara** [comment]
you have to configure you router port forwarding and add port map with port 3478 and your local ip

**Comment by chanhbc** [comment]
thank @MazenImara, i install success on Server not on My Computer

**Comment by neo125874** [comment]
@chanhbc Hi, could you share how you solve this problem?

**Comment by chanhbc** [comment]
i config after run my server ubuntu and it's working.

**Comment by neo125874** [comment]
@chanhbc what king of config? could you explain more? thanks!

**Comment by chanhbc** [comment]
I will answer tomorrow, because I do not remember my turnserver configuration

**Comment by neo125874** [comment]
@chanhbc many many thanks, hope to see the setting tomorrow, we ran into this situation recently...

**Comment by neo125874** [comment]
@chanhbc hi, you mentioned above "server-ip", public or private? and you built the server then the mobile or broswer are in different wifi?

**Comment by chanhbc** [comment]
That is the public ip (ip can access server control from another place) is usually the IP-WIFI of the server

**Comment by chanhbc** [comment]
When you install turnserver on the server, it is accessible anywhere as long as there is a network (I have not tried it with ip6)

**Comment by neo125874** [comment]
@chanhbc did you have your server behind firewall?   any further configuration?

**Comment by chanhbc** [comment]
No, I do not have to configure the firewall on my server. I recommend running on a trial server (I can not install on google server)

**Comment by neo125874** [comment]
@chanhbc thanks for sharing, our issue happened cause of the firewall, but really appreciate for your config & testing pics.

**Comment by OrionStark** [comment]
Perhaps this can help you:

- Check your firewal for allowing TCP/UDP over your TURN server PORT

**Comment by preAGIcoder** [comment]
We were also facing same issue, (we also changed the credentials recently and did `sudo systemctl restart coturn`). After lot of debugging, we restarted the server (reboot the remote ubuntu server) and it someout fixed the issue.
