### ISSUE TITLE
Use alternate MySQL installation 

### ISSUE THREAD

**Issue by vittico** [coturn/coturn#16]
Hi!

Im currently using a alternate mysql installation on my build machine. Usually under /opt/mysql. Is there any way to use that installation to bud coTurn?

Thanks.

**Comment by mom040267** [comment]
try to configure that like this:

$ configure --prefix=/opt

**Comment by vittico** [comment]
OK. Ill try! Ill let you know.

**Comment by vittico** [comment]
BTW: I forgot to thank you! =) Ill try and let you know.
