### ISSUE TITLE
RTCIceGatheringState is getting stuck on "gathering" state in iOS

### ISSUE THREAD

**Issue by dhavalyq** [coturn/coturn#1600]
Hi,
I'm using Coturn server and It's working fine in India. 

But, I'm facing issue when I test my App in Singapore. Specifically on Simba network.

I did debugging and found that RTCIceGatheringState is getting stuck on "gathering" state which creates a issue as I'm setting remote description once I get "complete" state. 

Anyone facing same issue with particular mobile network?

**Comment by RSATom** [comment]
Are you running your app in browser?

**Comment by dhavalyq** [comment]
No. It's iOS native app

**Comment by RSATom** [comment]
What are you using for WebRTC support then?

**Comment by dhavalyq** [comment]
https://github.com/stasel/WebRTC

**Comment by RSATom** [comment]
So it's Google WebRTC... If I remember correctly I've seen similar issue with GStreamer, but there it was related to wrong order of API calls. Anyway, I don't think it's related to `coturn`...

**Comment by dhavalyq** [comment]
Thanks for your help! I’ll dig deeper into this and confirm if the issue is related to the API call order or something else. I’ll update here and close the issue accordingly.

**Comment by dhavalyq** [comment]
I found that the issue was due to a misconfiguration of the server ports.
