### ISSUE TITLE
Inconsistent File names

### ISSUE THREAD

**Issue by benbro** [coturn/coturn#161]
The config and log files use turnserver.* instead of coturn.
I'm using the deb package on Ubuntu 16.04

```
deb package: coturn
/etc/default/coturn
/etc/turnserver.conf
/var/log/turn_1234_2017-06-19.log
```

Is it possible to?
- Rename turnserver.conf to coturn.conf
- Move log files to /var/log/coturn directory and rename them to coturn.1.log, coturn.2.log...`
- rename proc, user and group in /etc/init.d/coturn to coturn

**Comment by misi** [comment]
You should use syslog and then you could define the right place where to put the logs.
Or please send a Pull Request with the proposed changes.

**Comment by benbro** [comment]
Why did you close the issue?
It isn't fixed yet.

**Comment by misi** [comment]
Sorry it was my mistake...

**Comment by benbro** [comment]
It's ok. Doesn't seems like you think there is a problem.

**Comment by LorbusChris** [comment]
Hi
have a look at how I handle it for my RPM packaging in Fedora :)
https://github.com/LorbusChris/coturn-rpm (it's currently up for review to get pulled into Fedora properly).
