### ISSUE TITLE
[CMake] Use pkg-config to Find Hiredis Instead of `find_package`

### ISSUE THREAD

**Issue by bc-lee** [coturn/coturn#1618]
## Summary

Switch to using `pkg-config` for locating Hiredis in CMake (`pkg_check_modules(hiredis IMPORTED_TARGET hiredis)`) instead of relying on `find_package`. This approach ensures better compatibility across different systems and package managers.

## Problem

A colleague told that Hiredis was not found on their macOS workstation using the current CMake setup. They had installed Hiredis through Homebrew, and the installation was confirmed to be correct.

Upon reviewing the coturn project’s CMake files, I discovered that it uses `find_package(hiredis)`, which fails to locate Hiredis both on their system and mine.

## Analysis

The [Hiredis](https://github.com/redis/hiredis) library supports both Makefile-based and CMake-based builds. Both build systems generate appropriate `pkg-config` files. However, when using the Makefile-based build, CMake modules such as `HiredisConfig.cmake` are not generated, leading to inconsistent availability of `HiredisConfig.cmake`.

Different package systems handle Hiredis CMake Modules in varying ways. For example:

- [Debian `libhiredis-dev`](https://packages.debian.org/bookworm/amd64/libhiredis-dev/filelist): Provides `HiredisConfig.cmake` and `HiredisConfigVersion.cmake`.
- [Fedora `hiredis-devel`](https://fedora.pkgs.org/41/fedora-x86_64/hiredis-devel-1.2.0-3.fc41.x86_64.rpm.html): Does not include CMake Modules.
- [MinGW Hiredis](https://packages.msys2.org/packages/mingw-w64-x86_64-hiredis): Includes `hiredis-config.cmake`.
- [Homebrew Hiredis](https://github.com/Homebrew/homebrew-core/blob/90e7a8c761463b3a0acecf76ac526641dc30333b/Formula/h/hiredis.rb): Does not include CMake Modules.

This inconsistency creates problems when using `find_package`, which relies on the presence of `HiredisConfig.cmake`.

## Suggestion

To ensure compatibility across various environments and package systems, replace the current usage of `find_package(hiredis)` with:

```cmake
pkg_check_modules(hiredis IMPORTED_TARGET hiredis)
```

This change leverages `pkg-config`, which is consistently available regardless of whether the package manager includes CMake Modules for Hiredis.

**Comment by KangLin** [comment]
Lead to not work under MSVC. The correct way to do this is to use [Module mode](https://cmake.org/cmake/help/latest/command/find_package.html#id7) and put it in the Findhiredis.cmak file.
