### ISSUE TITLE
TURN Server not working

### ISSUE THREAD

**Issue by diegobill** [coturn/coturn#162]
I opened this issue https://github.com/jsxc/jsxc/issues/583 in my xmpp client (JSXC), but the problem is with my turn server (coturn), I tested my turn server with https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ but i did not receive any candidates. I tested numb.viagenie.ca turn server too, but no candidates returned. What is the problem with these turn servers?

**Comment by callancarr** [comment]
I am also having this problem, can't seem to fix it. Using and running a stock coturn config

**Comment by diegobill** [comment]
@callancarr , Do you running coturn in a private enterprise network too? I am testing ejabberd as STUN/TURN server but I had problems too: https://github.com/processone/ejabberd/issues/1925

**Comment by callancarr** [comment]
I'm running coturn on my own amazon lightsail vps instance.

If I go to the URL on http I can see that the server is running, but my app requires https and when I go on there I get a certificate compatibility error. Documentation for Coturn is extremely convoluted no luck :/

**Comment by diegobill** [comment]
I fixed the problem, I changed the /etc/turnserver.conf to:

```
listening-port=3478
tls-listening-port=5349
alt-listening-port=3479
alt-tls-listening-port=5350
listening-ip=IP1
listening-ip=IP2
relay-ip=IP1
min-port=49152
max-port=65535
verbose
fingerprint
#use-auth-secret
#static-auth-secret
#userdb=/var/lib/turn/turndb
realm=IP1
cert=/certs/cert.pem
pkey=/certs/key.pem
dh-file=/etc/turn/dhparam.pem
no-stdout-log
log-file=/var/log/turn/turn.log
lt-cred-mech
user=USERNAME:PASSWORD

no-sslv3
no-tlsv1
```

Comment:

```
#use-auth-secret
#static-auth-secret
#userdb=/var/lib/turn/turndb
```

Insert:
```
lt-cred-mech
user=USERNAME:PASSWORD
```

**Comment by peturbg** [comment]
https://github.com/coturn/coturn/issues/174

**Comment by peturbg** [comment]
if you use ubuntu or debian then you use bad program that give you problems, update the latest version from ubuntu or debian pool web site. ftp.ubuntu.com and seek for pool
ftp.debian.org and seek for pool. in this pool there are all new  ubuntu or debian programs. why then you download the old programs. becouse ubuntu and debian are SHITS and they dont want you to have new stable secure

**Comment by misi** [comment]
If I am correct the issue has been resolved and was configuration issue. 
Thanks for sharing. 
(btw. I have added in latest coTURN version a warning in the log about that 
if lt-cread-mech and use-auth-secret used in the same time, then it will cause that use-auth-secret will override lt-crec-mech.)

I will close this issue now, 
but If you think there are any not resolved issues then please reopen it and comment.

Thanks again..

**Comment by wxWU5** [comment]
Excuse me, I have the same problem, I want to know the IP1, IP2 in your turnserver.conf are all public IP?@diegobill

**Comment by misi** [comment]
AFAIK only the external ip is the public ip.

**Comment by wxWU5** [comment]
> AFAIK only the external ip is the public ip.

Thanks for your reply, I have solved this problem.

**Comment by stevesss** [comment]
I keep getting this mesage on startup: "oturn disabled in /etc/default" when in fact it is "TURNSERVER_ENABLED=1" In addition, it won't start
