### ISSUE TITLE
turnserver on virtual centos 7 server

### ISSUE THREAD

**Issue by sachinbanugariya** [coturn/coturn#164]
hello,

i just want simple turnserver installtion for webrtc interface,
i installed turn server on my virtual centos server,
and after setup i run below command:

turnserver -a -o -v -n  --no-dtls --no-tls -u user:pw -r "someRealm"

but after this command turn server process is started on localhost(127.0.0.1), and local ip of virtual server not started on my external server ip of server.

can you please send me command for start turn server on my external ip,
or send me turnserver.conf dummy example which run on virtual server.

i also try to install on dynamic server on that turn server process seems on external public ip,
but i want to start turn server on my virtual server.

please help ASAP.
thanks.

**Comment by No5251** [comment]
Hi,

just read the friendly manual:
https://github.com/coturn/coturn/blob/master/README.turnserver#L30

**Comment by misi** [comment]
Please try to add 
 * -E option to specify relay IP and  with your IP address or addresses.
 * -L option for the listening IP with your IP address or addresses.
and 
 * -X if you are behind NAT

Read for more the manuals..
It should work. 
If not then please reopen this issue.
