### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by 2opremio** [coturn/coturn#166]
Is this a totally crazy thing to do/request?

**Comment by firegurafiku** [comment]
It seems like no one is currently willing to invest their time to make a proper Windows port right now, and I can understand that. What I cannot understand is why you would need a TURN server running on Windows. What inherent benefits would TURN-on-Windows have over TURN-on-Linux to justify buying a license from Microsoft?

**Comment by misi** [comment]
You can try to run it in cygwin..

**Comment by 2opremio** [comment]
Some companies only have Windows machines for their on-premise services.

Some services already working only on Windows would benefit from being colocated with coturn.

I can enumerate a few more reasons if you want me to :)

**Comment by misi** [comment]
I don't know about anybody who are planning to do this work unfortunately.
It would be great if you can do it..

Please send a Pull Request with the changes that needed to port it to win too.
And we would be happy to merge it!

**Comment by firegurafiku** [comment]
Since only cross-platform libraries are used in the project, there are chances that the proposed CMake configuration (currently in `migrate-to-cmake` branch) can actually function on Windows. Yet, I have not tested this use-case.

**Comment by kunal-vzw** [comment]
+1 for a request for Windows support, for many of the reasons outlined here already i.e. requiring to integrate existing Windows services of our system with STUN/TURN servers ideally running on the same instance...

**Comment by powerzumsel** [comment]
+1

**Comment by Mike-McAnally** [comment]
No reason to be an OS snob.   Many of us have decades of experience with windows servers and feel more comfortable working with them.   Or may have access to an IT dept. with a windows server installation.  It's surprising that in this day and age of equality and inclusiveness, I would even have to respond.

**Comment by KangLin** [comment]
Let's do it !
The following tasks need to be completed:
1. MSVC language features
1.1 Thread. Do you(@misi) consider std c++ 11 thread?
1.1.1 Thread synchronization (completed)
1.2 socket
1.2.1 Asynchronous IO
2. windows service
3. Review the code to ensure the correct logic of the program
4. Create CI
5. Create test 

I am doing 1、2.
Please @misi do 3
Welcome @SamuelMarks and everyone to do it together.

**Comment by SamuelMarks** [comment]
@KangLin If I get the time I can help out

2 and 4 would be easiest for me to contribute. 1.1 you can't use [`std::thread`](https://en.cppreference.com/w/cpp/thread/thread) because we're in C not C++. Oh also I can easily contribute 1.2 as I've done similar contributions to a bunch of other C projects (porting them to MSVC).

**Comment by KangLin** [comment]
About thread, There are several methods:
There are several methods:
1. Start from scratch, write for different operating systems
2. Using libevent-pthread, this libevent is doing
3. Use std::thread
I recommend using std::thread, it is language level, cross-platform should be the best, but the project needs to use C++, I think this is not a problem. 
Please discuss it together and see which way to use.

**Comment by KangLin** [comment]
@SamuelMarks  I suggest you do it in the order of  4.  -> 1.2 -> 2  :smile:

**Comment by SamuelMarks** [comment]
libevent and libuv are reasonably cross-platform, but I wouldn't consider either without approval from the project maintainer. They're a reasonably big dependency and require changing the entire architecture around one or more event loops.

The alternative is to implement the cross-platform threading at the lowest level, with a bunch if `ifdefs` for MSVC threading.

**Comment by KangLin** [comment]
Yes.
2. 3. is simple and requires less work, but it will affect existing projects.
1 Simple modification requires a lot of work, but it will not affect existing projects.
Please @mom040267 @misi @firegurafiku express your opinions .

**Comment by KangLin** [comment]
This turn_mutex_init_recursive is not available in MSVC.
Is it really needed in this project?
If it is not necessary, consider removing ？

**Comment by SamuelMarks** [comment]
It's defined here: https://github.com/coturn/coturn/blob/9bcc898/src/apps/common/ns_turn_utils.c#L109-L133

You could probably use https://sourceforge.net/projects/pthreads4w if you wanted to stick with the pthreads API. But maintaining a proper MSVC threading interface might be more expected than adding a pthreads4w dependency. Might have performance advantages also.

**Comment by KangLin** [comment]
@SamuelMarks I am know it deined. 
I review the code. I don't think this feature is needed. So, I suggest to remove it.

**Comment by KangLin** [comment]
In #855, The following changes have been made:
1. Replace outdated functions with new standard functions
2. Add corresponding MSVC functions for non-standard functions 
3. Remove warnings about unsafe functions
4. CMAKE: modify find find pack Libevent and openssl 
5. Modify include files

Except for the service program, all other applications can be compiled and run successfully! 

Please @mom040267 @misi @SamuelMarks review it.

**Comment by SamuelMarks** [comment]
Good work @KangLin , I've left a bunch of minor comments. I'll wait for it to merge to master then I'll contribute CI/CD

**Comment by KangLin** [comment]
@SamuelMarks Thank you are reviwer. I accepted some suggestions. 
I will wait for everyone to decide how to modify the thread before starting subsequent server program modifications

**Comment by KangLin** [comment]
> It's defined here: https://github.com/coturn/coturn/blob/9bcc898/src/apps/common/ns_turn_utils.c#L109-L133
> 
> You could probably use https://sourceforge.net/projects/pthreads4w if you wanted to stick with the pthreads API. But maintaining a proper MSVC threading interface might be more expected than adding a pthreads4w dependency. Might have performance advantages also.
> 
> EDIT: Actually they claim on-par or faster performance: https://sourceforge.net/p/pthreads4w/wiki/Home

OK! use pthreads4w!

**Comment by KangLin** [comment]
> It's defined here: https://github.com/coturn/coturn/blob/9bcc898/src/apps/common/ns_turn_utils.c#L109-L133
> 
> You could probably use https://sourceforge.net/projects/pthreads4w if you wanted to stick with the pthreads API. But maintaining a proper MSVC threading interface might be more expected than adding a pthreads4w dependency. Might have performance advantages also.
> 
> EDIT: Actually they claim on-par or faster performance: https://sourceforge.net/p/pthreads4w/wiki/Home

OK! use pthreads4w!
