### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [coturn/coturn#17]
I would like to point out that identifiers like "[`__LIB_TURN_MSG_CPP__`](https://github.com/coturn/coturn/blob/3c40c14f40b1f382e7fac9dff548865358cd8655/src/client%2B%2B/TurnMsgLib.h#L31)" and "[`_SOCKET_TYPE`](https://github.com/coturn/coturn/blob/948a61d2502ed0b222ee8626095c95041349b22d/src/server/ns_turn_ioalib.h#L85)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by mom040267** [comment]
this is C. This is not C++.

**Comment by elfring** [comment]
What is the status for [the source file "TurnMsgLib.h"](https://github.com/coturn/coturn/blob/3c40c14f40b1f382e7fac9dff548865358cd8655/src/client%2B%2B/TurnMsgLib.h#L31 "Update candidate")?

Would you like to read corresponding information sources that describe [the consequences of underscores in such identifiers](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by mom040267** [comment]
That is a half-baked unfinished C++ wrapper. I do not think that it is
widely used now. We may return to it later.

Thanks
Oleg

**Comment by elfring** [comment]
Would you like to clean-up the remaining source code places which tamper still with the reserved name space?
