### ISSUE TITLE
Fedora Official Package

### ISSUE THREAD

**Issue by LorbusChris** [coturn/coturn#171]
Hello Everyone,
I'd like to get coturn into fedora proper. I saw it's also the first issue in the TODO file (although that was last updated 2yrs ago, so not sure how important this is for you).

I have forked rpm/turnserver.spec to https://github.com/LorbusChris/coturn-rpm and made a few rather little changes.

Builds in COPR live here:
https://copr.fedorainfracloud.org/coprs/lorbus/turnserver/monitor/

I will begin the process of becoming a Fedora Packager and submit the spec for review by Fedora QA next month, but I wanted to offer all of you devs the opportunity to review the spec beforehand. 

I will happily upstream any changes made to the spec to this repo, however eventually the spec will live in the fedora repos (ie. src.fedoraproject.org/rpms/coturn or src.fedoraproject.org/rpms/turnserver)

I have one remaining question (that will also need answering by fedora QA, but I'd like to hear your opinion nevertheless):
Would you prefer the package name be coturn or turnserver?

Cheers, Chris

**Comment by mom040267** [comment]
Hi Chris

thanks for working on the package.

The package name is up to you, I do not have a preference.

Oleg

On Tue, Aug 22, 2017 at 2:48 PM, Christian Glombek <notifications@github.com

**Comment by LorbusChris** [comment]
Created a Package Review Request: https://bugzilla.redhat.com/show_bug.cgi?id=1491492

**Comment by mom040267** [comment]
Looks great, thanks !

Oleg

On Wed, Sep 13, 2017 at 5:49 PM, Christian Glombek <notifications@github.com

**Comment by LorbusChris** [comment]
The Review Request has been updated with a new spec and build.
If you're a Fedora Packager please review and consider sponsoring.
https://bugzilla.redhat.com/show_bug.cgi?id=1491492
https://github.com/LorbusChris/coturn-rpm

**Comment by DudleyDursley** [comment]
Is this still being worked on?

**Comment by LorbusChris** [comment]
@DudleyDursley Not currently, but I still plan to pick this up at some point. (I just need to do another review of the specfile myself, and then ping the assigned Fedora packager to do the same. Hopefully I'll find some time for that during the coming holidays.)

**Comment by jistr** [comment]
Just wanna say this would be very useful for anyone running a [Synapse](https://github.com/matrix-org/synapse) + Coturn duo on top of Fedora or in a Fedora container, i hope i'm not alone doing this :smiley:. Synapse is already in the official repos.

I currently maintain & use a [Coturn container image](https://github.com/mugful/fedora-coturn) on top of Fedora 28, would like to bump it onto F29, but didn't find a package for F29 that looks maintained. (The Copr repo i use for F28 looks unmaintained too, now that i checked :smiley:.)

**Comment by LorbusChris** [comment]
@jistr that's great to hear! I'll try to get a rebuild for f29 done before end of year :)

**Comment by jistr** [comment]
@LorbusChris Thanks! No pressure though, first and foremost have nice holidays :smiley:.

**Comment by Sesivany** [comment]
I'd really appreciate an updated package for Fedora 29, too. The current one is conflicting with the version of mariadb_lib in F29.
BTW why did it get stuck in the review process for the official repos? I may help it get unstuck.

**Comment by LorbusChris** [comment]
@jistr @Sesivany a new build is available on copr.

I updated the BZ ticket, https://bugzilla.redhat.com/show_bug.cgi?id=1491492
Another thorough review to finally get into the Fedora repos would be appreciated.

**Comment by jistr** [comment]
@LorbusChris Thanks! I'll update my [Coturn container image at Quay.io](https://quay.io/repository/mugful/fedora-coturn).

**Comment by Sesivany** [comment]
> @jistr @Sesivany a new build is available on copr.

I installed coturn from your Copr repo, but the service failed to start with the following error: coturn.service: Job coturn.service/start failed with result 'dependency'

What could it be? I'm running it in an LXC-based VPS if it has any influence on it.

**Comment by LorbusChris** [comment]
@Sesivany what package version do you run? It should be 4.5.1.0-2 ...but maybe the init service is failing.

Could you post the output of `sudo journalctl -u coturn -u coturn-init`?

**Comment by Sesivany** [comment]
Seems like some problem with initial certificate generation:
Feb 17 10:52:01 vps.eischmann.cz systemd[1]: coturn-init.service: Failed to reset devices.list: Operation not permitted
Feb 17 10:52:01 vps.eischmann.cz systemd[1]: Starting One-time configuration for coturn...
Feb 17 10:52:01 vps.eischmann.cz openssl[5240]: Generating a RSA private key
Feb 17 10:52:01 vps.eischmann.cz openssl[5240]: .................+++++
Feb 17 10:52:01 vps.eischmann.cz openssl[5240]: ............................................+++++
Feb 17 10:52:01 vps.eischmann.cz openssl[5240]: writing new private key to '/etc/pki/coturn/private/turn_server_pkey.pem'
Feb 17 10:52:01 vps.eischmann.cz openssl[5240]: -----
Feb 17 10:52:01 vps.eischmann.cz openssl[5240]: You are about to be asked to enter information that will be incorporated
Feb 17 10:52:01 vps.eischmann.cz openssl[5240]: into your certificate request.
Feb 17 10:52:01 vps.eischmann.cz openssl[5240]: What you are about to enter is what is called a Distinguished Name or a DN.
Feb 17 10:52:01 vps.eischmann.cz openssl[5240]: There are quite a few fields but you can leave some blank
Feb 17 10:52:01 vps.eischmann.cz openssl[5240]: For some fields there will be a default value,
Feb 17 10:52:01 vps.eischmann.cz openssl[5240]: If you enter '.', the field will be left blank.
Feb 17 10:52:01 vps.eischmann.cz openssl[5240]: -----
Feb 17 10:52:01 vps.eischmann.cz openssl[5240]: Country Name (2 letter code) [XX]:problems making Certificate Request
Feb 17 10:52:01 vps.eischmann.cz systemd[1]: coturn-init.service: Main process exited, code=exited, status=1/FAILURE
Feb 17 10:52:01 vps.eischmann.cz systemd[1]: coturn-init.service: Failed with result 'exit-code'.
Feb 17 10:52:01 vps.eischmann.cz systemd[1]: Failed to start One-time configuration for coturn.
Feb 17 10:52:01 vps.eischmann.cz systemd[1]: Dependency failed for coturn.
Feb 17 10:52:01 vps.eischmann.cz systemd[1]: coturn.service: Job coturn.service/start failed with result 'dependency'.

My coturn.conf was set up according to this tutorial (no-TLS variant for the start): https://help.nextcloud.com/t/howto-setup-nextcloud-talk-with-turn-server/30794

**Comment by LorbusChris** [comment]
Thanks! Running Coturn without creating a proper config beforehand doesn't make much sense anyway. I think I'll remove the init service all together and replace it with instructions how to prep a config in the README. Anybody not ok with that?

**Comment by jistr** [comment]
+1 for manual config. As far as i can imagine, trying to default or autogenerate config for a service like Coturn will end up being either dangerous (proxying whatever for whoever) or useless (not proxying).

**Comment by LorbusChris** [comment]
coturn v.4.5.1.0 is now in the official Fedora repos! 🎉

I'll do my best to keep the rpm up to date (hopefully I'll get around to update the package to 4.5.1.1 this week :)

**Comment by jistr** [comment]
Thanks @LorbusChris! I updated the Quay.io container image to Fedora 29 and the latest RPM.
