### ISSUE TITLE
Stress Test and Live Monitor 

### ISSUE THREAD

**Issue by saphsoph88** [coturn/coturn#172]
Hi,

I've successfully installed the COTURN server on AWS centos server, However I'm looking forward the following item to achieve;

1- Optimum parameters to enable/adjust the server with.

2- How to perform stress testing as we've more than 50 TPS for texting so we will need to perform huge stress test.

3- I dont want to perform the test and then check from the log files. I want to perform live monitoring for all requests that are being handled by the server. How to achieve this.

Respect,
Mustapha

**Comment by misi** [comment]
1. I think optimum parameters depends on your hw, os, service and scenario. 
I think the best way to run tests in your lab environment and with real app and scenario.
2. There are many ways. like using turnutils_uclient and turnutils_peer or headless browser test, etc.
3. Not clear what you mean about live monitoring. May see web admin or cli interface. 
For debugging proposes you could run server with detailed verbose log options with very detailed logs if you need to know the details.

**Comment by DoanAhmed** [comment]
It's been a while since the post was sent but saphsoph88 - Mustapha can you explain steps how I can install the Coturn on AWS ? I'm new in webRTC, STUN/TURN etc. . 

Much Appreciated,
Doan.

**Comment by misi** [comment]
I close it now. 
Please reopen a new issue if I left out any open question or you have any further question.
