### ISSUE TITLE
Coturn Connection Number

### ISSUE THREAD

**Issue by saphsoph88** [coturn/coturn#175]
Hi, 

i've created a tool that simulates the client connection to the coturn server and I start to face a delay after shooting more than 4k connections. My machine specs is 1 GB RAM and 2.8 GHz processor. I want to know the current active connections connected to the coturn server, The numbers only.

Thanks

**Comment by misi** [comment]
Could you detail more how you stress test coturn? 
I want to reproduce the issue. 

Thanks for your help and cooperation in advance!

**Comment by misi** [comment]
@saphsoph88 
I didn't get any update from you and I can't help without it. 
Please open a new issue with a more detailed report.
With coTURN version and all client & server options and config.
