### ISSUE TITLE
Sometimes failing TURN Server

### ISSUE THREAD

**Issue by vishnusudhakarreddy** [coturn/coturn#181]
Hi Team,

I deployed CoTurn TURN server in ubunutu 14.04. It was working with in  some networks only but not all. Can you please suggest me why it is not working in all networks.

Thanks.

**Comment by misi** [comment]
We need more detailed issue report to help.
Please detail your scenario as much as possible.
There are so many scenarios, that so general problem report couldn't be answered.
Sorry... 
Please open a more specific issue with detailed error report..
