### ISSUE TITLE
Clarification regarding the proprietary license of the configure script

### ISSUE THREAD

**Issue by Apteryks** [coturn/coturn#182]
Is this file still under a proprietary license? Is it OK for users to use it for their own needs? Is it not OK for users to modify or redistribute it? Thanks for clarifying!

**Comment by mom040267** [comment]
There is no license or copyright info in the script. You can do whatever
your want with that.

The script was written for the sole purpose of the coturn configuration, so
I'd not expect that it is very suitable for other projects and for generic
purposes.

Oleg

**Comment by Apteryks** [comment]
Thanks for the clarifications, Oleg! What caused me to think there might be an issue was that comment in the configure script: `# Proprietary configure script of Coturn project`. Maybe it could be dropped to prevent further confusion?

**Comment by mom040267** [comment]
"Proprietary" here means that it was created for the single purpose of
coturn configuration and it has never been considered for anything else -
unlike the general-purpose GNU configuration scripts. It has nothing to do
with the copyright.

Oleg

**Comment by Apteryks** [comment]
I see. Thanks again!
