### ISSUE TITLE
What's an idle session used for? And it's not got 0-freshed, staying for 10 minutes.

### ISSUE THREAD

**Issue by tengg** [coturn/coturn#183]
Hi,
I was testing the TURN server with most simple scenario:
turnutil_uclient [parameters] -e [peer_ip]  IP_ADDR

From the TURN cli, I see 3 sessions when the above transmission is ongoing.
Two of the sessions were actually working: they have "peer" listed, and the 3rd one has no such information.

After the transmission finished, the two working session were freshed lifetime=0, but the 3rd one just staying there, until 600 seconds passed..

Could someone enlighten me what's the 3rd session for?

Some output from console:
> ps

    1) id=000000000000014740, user <user1>:
      started 2 secs ago
      expiring in 598 secs
      client protocol UDP, relay protocol UDP
      client addr 72.21.196.70:15827, server addr 72.21.16.194:4172
      relay addr 72.21.16.194:58886
      fingerprints enforced: ON
      mobile: OFF
      usage: rp=7, rb=1160, sp=6, sb=624
       rate: r=0, s=0, total=0 (bytes per sec)
      peers:
          72.21.16.194

    2) id=021000000000015355, user <user1>:
      started 2 secs ago
      expiring in 598 secs
      client protocol UDP, relay protocol UDP
      client addr 72.21.196.70:27590, server addr 72.21.16.194:4172
      relay addr 72.21.16.194:53657
      fingerprints enforced: ON
      mobile: OFF
      usage: rp=7, rb=1168, sp=6, sb=612
       rate: r=0, s=0, total=0 (bytes per sec)
      peers:
          72.21.16.194

    3) id=012000000000014614, user <user1>:
      started 2 secs ago
      expiring in 598 secs
      client protocol UDP, relay protocol UDP
      client addr 72.21.196.70:9815, server addr 72.21.16.194:4172
      relay addr 72.21.16.194:53656
      fingerprints enforced: ON
      mobile: OFF
      usage: rp=3, rb=428, sp=2, sb=256
       rate: r=0, s=0, total=0 (bytes per sec)

  Total sessions: 3

**Comment by misi** [comment]
@tengg 
There was a bugfix and lot of changes..
Could you please reproduce it with the latest master branch this issue?
If it is solved then please close it.. 
Thanks in advance for your help and cooperation!
