### ISSUE TITLE
./configure problem and coturn does not work

### ISSUE THREAD

**Issue by SherlockUnknowEn** [coturn/coturn#186]
I use Ubuntu 16.04, and I run

> $ ./configure

then the terminal show me:

**Library option -lsqlite3 cannot be used
SQLite3 development library cannot be found.

SQLite DEVELOPMENT LIBRARY (libsqlite3) AND/OR HEADER (sqlite3.h)
	ARE NOT INSTALLED PROPERLY ON THIS SYSTEM.
	THAT'S OK BUT THE TURN SERVER IS BUILDING WITHOUT SQLITE SUPPORT.

POSTGRESQL DEVELOPMENT LIBRARY (libpq.a) AND/OR HEADER (libpq-fe.h)
	ARE NOT INSTALLED PROPERLY ON THIS SYSTEM.
	THAT'S OK BUT THE TURN SERVER IS BUILDING WITHOUT POSTGRESQL DATABASE SUPPORT.

MYSQL DEVELOPMENT LIBRARY (libmysqlclient) AND/OR HEADER (mysql.h)
	ARE NOT INSTALLED PROPERLY ON THIS SYSTEM.
	THAT'S OK BUT THE TURN SERVER IS BUILDING WITHOUT MYSQL DATABASE SUPPORT.

MONGODB DEVELOPMENT LIBRARIES (libmongoc-1.0 and libbson-1.0) AND/OR HEADER (mongoc.h)
	ARE NOT INSTALLED PROPERLY ON THIS SYSTEM.
	THAT'S OK BUT THE TURN SERVER IS BUILDING WITHOUT MONGODB SUPPORT.

HIREDIS DEVELOPMENT LIBRARY (libhiredis.*) AND/OR HEADERS (hiredis/*.h)
	ARE NOT INSTALLED PROPERLY ON THIS SYSTEM.
	THAT'S OK BUT THE TURN SERVER IS BUILDING WITHOUT REDIS SUPPORT.**

and if I continue, run

> sudo turnserver -n -a --listening-ip=myip --listening-port=3210 -r myralm

coturn can't not bind socket

**0: Trying to bind fd 16 to <106.14.136.75:3210>: errno=99
Cannot bind local socket to addr: Cannot assign requested address
0: Trying to bind fd 20 to <106.14.136.75:3210>: errno=99
Cannot bind local socket to addr: Cannot assign requested address
0: Cannot bind DTLS/UDP listener socket to addr 106.14.136.75:3210
0: Trying to bind DTLS/UDP listener socket to addr 106.14.136.75:3210, again...
0: Trying to bind fd 18 to <106.14.136.75:3210>: errno=99
Cannot bind local socket to addr: Cannot assign requested address**

and if I run

> turnserver -o

the ternimal show me

**0: GCM (AEAD) supported
0: OpenSSL compile-time version: OpenSSL 1.0.2g  1 Mar 2016 (0x1000207f)
0: 
0: SQLite is not supported
0: Redis is not supported
0: PostgreSQL is not supported
0: MySQL is not supported
0: MongoDB is not supported
0: 
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: Config file found: /usr/local/etc/turnserver.conf**

how can I solve this problem

**Comment by misi** [comment]
IMHO
1. To solve dependency lib problem use
`apt-get build-dep coturn`
2. Regarding can not bind socket 
Please check that you not run already coturn or port is not busy e.g. see netstat -lnp output

**Comment by misi** [comment]
I am going to close this ticket, please reopen it or open new if I didn't answered your question or you have further question.

**Comment by sanjaikumarvn** [comment]
I am getting below error on .\configure

ERROR: cannot use compiler unknown properly

Could some one please help

ginstall is /usr/bin/ginstall
pkill is /usr/bin/pkill
sqlite3 is /usr/bin/sqlite3
Use TMP dir /var/tmp
Compiler: unknown

**Comment by c4m4** [comment]
ubuntu bionic 
 apt-get build-dep coturn
Reading package lists... Done
E: Unable to find a source package for coturn
