### ISSUE TITLE
turnutils_uclient: get_hmackey_size wrong for OAuth

### ISSUE THREAD

**Issue by kdubb** [coturn/coturn#189]
When using the `-J` option the `turnutils_uclient` generates a 20 byte "session key" or "mac_key" but when adding the `MESSAGE-INTEGRITY` attribute it only uses 16 bytes of the session/mac key; this is because `get_hmackey_size` returns 16 for the default `HMAC-SHA1`.

16 bytes is the correct length for keys generated from long-term credentials (because MD5 is what generates the key) but for OAuth the spec (RFC 7635) says it `MUST` support a 20 byte key. I'm assuming that since the spec is saying you must support a 20 byte key that it requires you use the entire key and not just an arbitrary portion of it; otherwise how would an arbitrary client know what portion of the session/mac key to use when adding the attribute.

I discovered this when implementing an OAuth authorization server to interface with coturn.  Since the only way to communicate the key length you are using is via the `key_length` field of the encrypted `ACCESS-TOKEN` it seems that whatever `turnutils_uclient` and/or coturn are doing is incorrect and that it should always be using the entire session/mac key.

**Comment by misi** [comment]
Thanks for the report. I will check it..

(btw. Is your server open source or publicly available? thx)

**Comment by misi** [comment]
I also guess that intention of RFC7635 was to use 20 byte keys, for SHA1.
Unfortunately I couldn't find in the normative part of RFC7635 any explicit reference 
You mentioned that you found it. Can you point me on it?

In "Appendix A" I found the example where truncating the key, but it is conflicting to HMAC definition of howto truncate a key.

**Comment by kdubb** [comment]
We are discussing opening up our TURN implementation but for now it is not. Our primary reason for building was to make some large changes to the authorization, reporting and statistics supporting multiple user domains and such.

**Comment by kdubb** [comment]
The mandatory requirement in 7635 appears in [Section 6.2](https://tools.ietf.org/html/rfc7635#section-6.2). In the `key_length` description it speaks of a requirement to support 160-bit key length.

Regardless of that requirement, `turnutils_uclient` seemingly cannot send me 20-bytes and expect me to somehow _just know_ to only the first 16-bytes; if it's only using 16-bytes then it should only send that many.

Since `coturn` properly authenticates in this scenario it must be incorrect as well; when you send it a 20-byte key it just uses the first 16 bytes.

**Comment by misi** [comment]
Could you send a PR?

**Comment by misi** [comment]
I see that it is a bug, but I don't find the time to work on it.

**Comment by misi** [comment]
Please check and test  branch: fix-oauth

**Comment by Neustradamus** [comment]
@kdubb: Have you tested the fix-oauth?
