### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [coturn/coturn#19]
The function "[printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function "[sighup_callback_handler](https://github.com/coturn/coturn/blob/cfe61ab2848e5bb31de782e2143f5983e2ebec2f/src/apps/common/ns_turn_utils.c#L344 "Check signal handling implementation.")".

**Comment by mom040267** [comment]
and mutexes are not safe, too. I'll fix that.

**Comment by mom040267** [comment]
I fixed it and I pushed the fix to the repository.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/coturn/coturn/commit/25000742f4aed00e7364a8f3a73b6e27e5ce6291 "Signal handler became asynchronous-safe.").
