### ISSUE TITLE
Building static linked binaries

### ISSUE THREAD

**Issue by andybrown668** [coturn/coturn#190]
Hi there, 
great work! Only thing I need is a static build to make it easy to containerize this in a scratch image... is that possible? (I tried altering the generated makefile to add -static but it didn't work; possibly I did it wrong)

cheers
Andy

**Comment by firegurafiku** [comment]
Hi Andy,
Why would you need a pure static build? In theory, you can collapse the whole dependency tree into the single fat executable, but what exactly it would be useful for? And, to what extent should it be static: do you want your openssl and libc be statically linked too?

**Comment by eakraly** [comment]
Hi @andybrown668. I believe things changed in the last 5 years since you opened this issue.
For now I'm closing it. If you are still interested in this feature you can reopen this issue or open a new one.
And PR is welcome! Thank you!
