### ISSUE TITLE
about 'secure-stun'

### ISSUE THREAD

**Issue by wujin099** [coturn/coturn#20]
I see 'secure-stun' configuration in the turnsever.conf, when I uncomment it, I cannot test the stun request right,I find someone also got this problem but no good solution,can you tell me what's the reason?

**Comment by mom040267** [comment]
Secure-stun means that the stun binding requests require authentication. Usually anonymous binding requests are allowed. Do not use those, they are only for exotic cases.

**Comment by wujin099** [comment]
Ok,I understand.Thank you for your answer!
