### ISSUE TITLE
How to upgrade openssl compile-time version?

### ISSUE THREAD

**Issue by yasmagic** [coturn/coturn#200]
I've upgraded opensssl to to the latest "OpenSSL **1.0.2n**  7 Dec 2017" version in Ubuntu 14.0.4, however coturn is still showing as:

OpenSSL compile-time version: OpenSSL **1.0.2g-fips**  1 Mar 2016 (0x1000207f)

How to change this to reflect latest openssl version?

**Comment by mom040267** [comment]
this text is set during the compile time, so if you just upgrade your
libraries it does not affect that text. You have to recompile from sources.

**Comment by yasmagic** [comment]
I did that, but no luck. Here are my steps:

wget http://turnserver.open-sys.org/downloads/v4.5.0.6/turnserver-4.5.0.6.tar.gz
tar xzf turnserver-4.5.0.6.tar.gz
cd turnserver-4.5.0.6
./configure
make
make install

**Comment by mom040267** [comment]
that means that during configuration it is still finding the old dev
libraries on your system

**Comment by misi** [comment]
I think this issue has been solved. Isn't it? If not then please reopen it.
