### ISSUE TITLE
How do I run the docker build?

### ISSUE THREAD

**Issue by circuitry2** [coturn/coturn#201]
Hello, I installed the docker build for coturn.
I tried running `docker run -ti coturnbuild`.
This brought me to an ubuntu terminal.
Where are the binaries located and how do I run them?
I looked in the /bin directory but I'm not seeing anything.
Do I need to expose the ip and port of the docker container as well to connect to the STUN/TURN server?

Thanks so much!

**Comment by misi** [comment]
Try to contact the docker Pull Request submitter..

**Comment by misi** [comment]
@circuitry2 I will close this issue, because I can help you more, but please follow issue https://github.com/coturn/coturn/issues/273
