### ISSUE TITLE
Plugin for custom long time credentials

### ISSUE THREAD

**Issue by mesibo** [coturn/coturn#202]
It would be great if you can add support to  add pluggable interface for  long time credentials instead of getting it from db or config file. 

I am sure there is some kind of interface since coturn supports multiple db etc, in that case could you point me to right location where we can add our own custom interface

**Comment by misi** [comment]
See: src/apps/relay/dbdrivers
You could add/delete credentials to/from db.

**Comment by misi** [comment]
Please reopen this or new if you have any further questions regarding this feature..
