### ISSUE TITLE
how to use turn server to  relay

### ISSUE THREAD

**Issue by wlyu** [coturn/coturn#206]
1.lcoal NAT : Full Cane NAT
  turnserver ip =47.93.227.xxx
2.two clients
  A-192.168.103.188:6666  
  B-192.168.103.188:6667  
3.turnserver relay address
  A-47.93.227.xxx 60638
  B-47.93.227.xxx 51976
  
Question:
    
   47.93.227.xxx:60638/udp/relay -> 47.93.227.xxx:51976/udp/relay (text.RTP), failing.
   
   Why the server can not relay?

**Comment by misi** [comment]
It is up to your nat. 
Does it support hairpinning? 
Most NAT AFAIK  does not support it.
See nat-discovery hairpin check rfc5780

**Comment by misi** [comment]
See: git source 
turnutils_natdiscovery -H rfc5780.turn.geant.org

**Comment by wlyu** [comment]
it looks success!!
############
FC 5780 response 1
No ALG: Mapped == XOR-Mapped
0: IPv4. Response origin: : 193.198.203.133:3478
0: IPv4. Other addr: : 193.198.203.132:3479
0: IPv4. UDP reflexive addr: 47.93.227.xxx:34838
0: IPv4. Local addr: : 0.0.0.0:34838
Received a request (maybe a successful hairpinning)

**Comment by misi** [comment]
If you receive timeout your NAT does not support hairping

```
STUN receive timeout..
STUN receive timeout..
```

If your NAT box support hairpinning then
```
Received a request (maybe a successful hairpinning)
```
I hope I answered your issue. 
If I did it then please close it..

**Comment by misi** [comment]
Ok, so it is not as simple as I thought for the first sight.. 

Could you send more info about the issue. What fails exactly? 
Did you made a packet capture and Verbose log in coturn?

**Comment by CoreyCole** [comment]
@msisi I'm using the amazon linux EC2 coturn-4.5.0.6 - ami-908316f0 and I think I am also having problems with relay. I'm able to connect my two phones on the same Wifi subnet and when one is on Wifi and the other is on LTE.

But, I'm not able to connect the two phones when both are on LTE (one t-mobile and the other at&t). I'm not sure about this hairpinning. I don't think my EC2 is behind a NAT, it is just on an aws VPC with a public IP. I don't see anything about hairpinning in my logfile.
```
Starting TURN server...
0: log file opened: /var/log/turn_29683_2019-12-17.log
0:
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.0.6 'dan Eider'
0:
Max number of open files/sockets allowed for this process: 33000
0:
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 16500 (approximately)
0:

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: DTLS 1.2 is not supported
0: TURN/STUN ALPN is not supported
0: Third-party authorization (oAuth) supported
0: GCM (AEAD) supported
0: OpenSSL compile-time version: OpenSSL 1.0.1k-fips 8 Jan 2015 (0x100010bf)
0:
0: SQLite supported, default database location is /usr/local/var/db/turndb
0: Redis supported
0: PostgreSQL supported
0: MySQL supported
0: MongoDB supported
0:
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: Config file found: /etc/turnserver.conf
```
Where do I check these "received a request" logs? Sorry I'm very new to this. I've read through the readme and the config file included in the EC2 AMI, but its still unclear to me where to find these logs if not in the logfile printed out when I run `sudo /etc/rc.d/init.d/coturn start` (`/var/log/turn_29683_2019-12-17.log` in my case)
