### ISSUE TITLE
missing relay candidates in Chrome

### ISSUE THREAD

**Issue by 481wgxoy4** [coturn/coturn#207]
Hey,
I'm trying to run a coturn server on Ubuntu behind a NAT.
Using the Trickle ICE Tool at https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ I'm testing my configuration, but only using Firefox (Nightly 59.0a1 (2018-01-14) (64-Bit)) I do get relay candidates.
![firefox-nightly-coturn-](https://user-images.githubusercontent.com/35459201/34948847-9a5b67c4-fa0e-11e7-9541-5526989655f6.png)
Using Chrome (63.0.3239.132 stable (64-Bit) and 65.0.3322.0 canary (64-Bit)) no relay candidates where found - regardless of using turn or turns, port 3478 or 5349. Also the tool seems to be stuck forever. The 'Gather candidates' button stays disabled.
![chrome-canary-coturn-](https://user-images.githubusercontent.com/35459201/34949071-4c2fdde0-fa0f-11e7-9171-825540507171.png)

Which coturn versions did I test:
4.5.0.6-1ubuntu2 on Ubuntu Artful
and
4.5.0.7-1ubuntu1 on Ubuntu Bionic
(both downloaded and installed via apt)

/etc/turnserver.conf

listening-port=3478
tls-listening-port=5349
external-ip=(mypublicip)
min-port=49152
max-port=65535
fingerprint
lt-cred-mech
user=user:pass
cert=/etc/letsencrypt/live/mydomain/fullchain.pem
pkey=/etc/letsencrypt/live/mydomain/privkey.pem
cipher-list="DEFAULT"
log-file=/var/log/turn.log
simple-log
proc-user=coturn
proc-group=coturn
no-cli
no-sslv3
no-tlsv1

On chrome://webrtc-internals/ I could not find anything usefull regarding this issue.

Running the resiprocate-turn-server (using the same setup) works for Firefox and Chrome, but sadly I could not figure out a way to run the resiprocate one behind a NAT, it always sends its local ip address to the peers, to which they can not connect.

Do you have any idea what is going wrong with my coturn setup? Is this a Chrome bug?

Thanks a lot!

**Comment by 481wgxoy4** [comment]
running

chromium-browser --enable-logging=stderr --v=4

on another machine I noticed a lot of these:

Received TURN allocate error response, id=385a4447784c347a56664d4e, code=401, rtt=86

I've attached the logfile. [chrome(1).log](https://github.com/coturn/coturn/files/1632299/chrome.1.log)

**Comment by misi** [comment]
What do you see in the packet capture on your TURN server?

**Comment by misi** [comment]
From the log you could see the auth failures:
```
[1:17:0115/170821.931270:INFO:turnport.cc(1233)]` Jingle:Port[0x7f6af009ef90:audio:1:0:relay:Net[any:0.0.0.x/0:Unknown]]: Received TURN allocate error response, id=2b6c64486b6a754c2f453045, code=401, rtt=85
```
The issue is that no realm defined in your config...
realm=yourdomain.com

**Comment by 481wgxoy4** [comment]
Thanks, that's it!
