### ISSUE TITLE
libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by KlausHans** [coturn/coturn#209]
Hello,

i've recently upgraded from Debian 8 to 9. I think the coturn package was updated too, because it doesn't work anymore. If i try to start it with
`turnserver -c /etc/turnserver.conf --daemon -v`
the following error appears:
`turnserver: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`
I've read somewhere, that libcrypto.so.1.0.0 is deprecated.
Is there any fix for this problem?

coturn package version: 4.5.0.5-1+b1

**Comment by misi** [comment]
Do you use debian offical coturn package?
If not then please rebuild with the upgraded libs...

**Comment by KlausHans** [comment]
Yes, official debian coturn package.

**Comment by misi** [comment]
It should be some local issue. 
I have checked and I have a debian that is upgrade to Debian 8 =>9
Run the same  4.5.0.5-1+b1
with the same command line  /usr/bin/turnserver -c /etc/turnserver.conf -o -v

May could you share you config in private?

ldd /usr/bin/turnserver | grep libcrypto
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f6decf06000)

I hope I could give a small help..

**Comment by misi** [comment]
$apt-file search /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
libssl1.1: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1

So check if libssl1.1 is installed properly..
