### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG Error

### ISSUE THREAD

**Issue by brtptrs** [coturn/coturn#210]
We have Coturn running on Ubuntu 16.01 whith de standard apt-get installation. After some standard system upgrades (end of 2017) all https requests to corurn return SSL_ERROR_RX_RECORD_TOO_LONG as error and our webrtc apps fail.
Prior to that everything work just fine. Currently we can't log into the admin gui either.

http:// requests return "Default Deamon" which i presume is the normal Coturn message. 

We have even reinstalled coturn from scratch but still get the same results. I have not found any other reports for this problem, so I guess we have a config error somewhere, but we have not been able to track it down. Does anyone have an idea where this could come from?

**Comment by misi** [comment]
Ubuntu 16.10 or 16.04.1? 
http://old-releases.ubuntu.com/releases/

**Comment by brtptrs** [comment]
16.04 sorry

**Comment by brtptrs** [comment]
The logs shows errors like:
TLS/TCP socket buffer operation error

**Comment by misi** [comment]
I have just tested on 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
with default TLS and it seems working for me.

Can you share more details? I can't reproduce..

**Comment by brtptrs** [comment]
Thanks for the feedback. We installed coturn on a bionic test server, which solved the problem.
