### ISSUE TITLE
auth-secret TCP connection closed by client (callback)

### ISSUE THREAD

**Issue by Eviora90** [coturn/coturn#214]
Been trying to set up a turn-server for nextcloud but can't seem to get it running.
The server is running on an Ubuntu LTS behind NAT

turnserver.conf
```
# Coturn TURN SERVER configuration file
listening-port=80
tls-listening-port=443
listening-ip=10.1.2.30
relay-ip=10.1.2.30
external-ip=y.y.y.y/10.1.2.30
verbose
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=SECRET
realm=turn.eviora.de
stale-nonce
cert=/ssl/fullchain.pem
pkey=/ssl/privkey.pem
dh-file=/ssl/dhparam.pem
cipher-list="DEFAULT"
log-file=/var/tmp/turn.log
simple-log
no-stun
no-loopback-peers
no-multicast-peers

no-sslv3
no-tlsv1
```
/var/tmp/turn.log
```
Host: turn.eviora.de:443
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Accept: image/webp,image/apng,image/*,*/*;q=0.8
Referer: http://turn.eviora.de:443/
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,es;q=0.6
Cookie: _ga=GA1.2.1347324805.1480025938

448: session 000000000000000003: TCP socket closed remotely 84.179.xx.xx:34689
448: session 000000000000000003: closed (2nd stage), user <> realm <turn.eviora.de> origin <>, local 10.1.2.30:443, remote 84.179.xx.xx:34689, reason: TCP connection closed by client (callback)
```
I can't get an output from nextcloud and/or figure out why. 

if I try with normal user authentication it seems to work? I get this reply from Trickle ICE
```
Time	Component	Type	Foundation	Protocol	Address	Port	Priority
0.006	1	host	3013953624	udp	192.168.1.100	51313	126 | 31 | 0
0.006	1	host	2416775427	udp	2001::9d38:78cf:3438:d356:xxxx:xxxx	51314	126 | 11 | 0
0.049	1	srflx	842163049	udp	83.179.xx.xx	6888	100 | 30 | 255
0.147	1	relay	882345837	udp	y.y.y.y	55497	2 | 30 | 255
0.147	Done
0.148
```

**Comment by misi** [comment]
Could you send a more detailed coturn (-V) log?

> TCP connection closed by client
For me it seems ICE User Agent closed the connection


Please analyze and share your logs in your browser or client

If it is a browser then something like this...

Debug FireFox

Firefox:

export NSPR_LOG_FILE=/home/ehugg/tmp/nspr.log
export NSPR_LOG_MODULES=signaling:5,mtransport:5,timestamp:1
export R_LOG_LEVEL=9
export R_LOG_DESTINATION=stderr

 

ICE media log:

 For ICE/STUN/TURN: 
     Set R_LOG_DESTINATION=stderr 
     Set R_LOG_LEVEL=3 (can be anything between 1 and 9) 
     Set R_LOG_VERBOSE=1 if you want to include the module name 
generating the message 

For "signaling" (SDP offer/answer handling) and media transport, we use 
the normal Mozilla logging infrastructure, which uses a comma-separated 
list of modules, each one with its indicated log level; for WebRTC, 
you'll be most interested in these: 
     Set NSPR_LOG_MODULES=signaling:5,mtransport:5 
You can also add ",timestamp:1" to that list if you want each log 
message to include timestamps. 
Debug Chrome

google-chrome --enable-logging=stderr --v=4 --vmodule=*libjingle/*=9 --vmodule=*media/*=9

 linux log file:

.config/chromium/chrome_debug.log

Basic info: https://www.chromium.org/for-testers/enable-logging 

a) --vmodule=*source*/talk/*=3
b)  --vmodule=*third_party/libjingle/*=3
c) --vmodule=*libjingle/source/talk/*=3

--enable-logging=stderr --log-level=3 --vmodule=*libjingle/*=3,*=0

**Comment by Eviora90** [comment]
So I tried really hard to get some decent logs and stuff but I might have done it all wrong. 

These are my "normal tries" without involving Nextcloud:
Username+PW: [https://pastebin.com/ziqd9Rsn](https://pastebin.com/ziqd9Rsn)
Secret: [https://pastebin.com/UhP6iA6U](https://pastebin.com/UhP6iA6U)

I can't really seem to get any decent output from the Talk-App .., which makes me think I might have configured it wrong. The nspr log remains empty and obviously then coturn doesn't log anything either .. 
I'm starting to think its a nextcloud issue but I'd like to make sure I have the Turnserver running correctly anyways. The only thing I can get from browser debugging is this I suppose ... 
Nextcloud Error: [https://pastebin.com/X7XfpwtG](https://pastebin.com/X7XfpwtG)

Sorry it took so long to respond! Honestly I'm gratefull for any feedback at all.

**Comment by misi** [comment]
@Eviora90 
If you run debian  check `/etc/default/coturn` if `TURNSERVER_ENABLED=1` not commented out.

**Comment by misi** [comment]
@Eviora90 Can you share again the infos above. I can't reach them now. 
Sorry for my delayed reply.

**Comment by rasos** [comment]
I think you can't use both user authentification and the secret mechanism in parallel:

```
lt-cred-mech
use-auth-secret
```

**Comment by ggarber** [comment]
please reopen if hte answers received didn't help
