### ISSUE TITLE
coturn stable version for production

### ISSUE THREAD

**Issue by tengg** [coturn/coturn#215]
A quick question, which version do you use for production(more stable)?
My project is currently using rfc5766 turnserver, and I'm considering to migrate to coturn.

**Comment by misi** [comment]
The latest contains always the latest bug fixes. 
I am working on some fixes, so if you could wait for next version then it would fix few bugs.
The when will be released is good question, it depends my free time.

**Comment by bradleythughes** [comment]
We always run the latest coturn release in production, which is currently 4.5.0.7.

**Comment by misi** [comment]
I also suggest to use the latest version..
I am closing this issue, but please reopen if you have further question..
