### ISSUE TITLE
coturn runs out of ports after a while

### ISSUE THREAD

**Issue by x-yuri** [coturn/coturn#218]
Number of connections drops to about 100. Number of sessions to about 9. It has about 55k connections/sessions at peak time. It doesn't provides relays in such state. And in the log I see "no available ports" message, presumably for every connection. I have a couple of conjectures here:

* it forgets to release ports occasionally (port leaks)
* it has to do with [`turnports.low/high`][low-high] overflow; some statuses are [reserved][reserved-statuses], so when `high` reaches `-4` (and other reserved values), the port doesn't get [released][release]
* some of the servers had incorrect time (around 7 hours drift)

Any suggestions are welcome. What to log? What to check? Any simple/fast way to check which ports are really open?

P.S. I've added some [logging][logging] to coturn. Not supposed to be merged, apparently.

[logging]: https://github.com/x-yuri/coturn/commit/f7d9f1207ac03930b82f6f0b098db2e066556ed5

[low-high]: https://github.com/coturn/coturn/blob/4.5.0.7/src/apps/relay/turn_ports.c#L49-L50
[reserved-statuses]: https://github.com/coturn/coturn/blob/4.5.0.7/src/apps/relay/turn_ports.c#L42-L45
[release]: https://github.com/coturn/coturn/blob/4.5.0.7/src/apps/relay/turn_ports.c#L204

By the way, you might be interested in `systemd` unit config:

```
[Unit]
Description=Turn server

[Service]
Type=forking
ExecStart=/usr/bin/turnserver -c /etc/turnserver.conf -o -v --simple-log
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```

and `logrotate` config (works with `--simple-log`):

```
/var/log/turn.log {
    rotate  5
    size  100M
    compress
    delaycompress
    sharedscripts
    postrotate
        /bin/kill -HUP `cat /var/run/turnserver.pid 2> /dev/null`
    endscript
}
```

**Comment by misi** [comment]
Thanks for the detailed report. 
Actually I don't find time to debug it, but it is definitely on my TODO list, if you have any further info please share it..

**Comment by misi** [comment]
@x-yuri 
Could you please test the latest master branch if the issue still exists?
Thanks for your cooperation..

**Comment by x-yuri** [comment]
@misi After that we've ordered more servers, and I'm not sure I can reproduce the issue anymore. The turn servers are running nonstop for at least a month. So the issue probably might be closed.

Although some minor leaks might take place:

> it has to do with turnports.low/high overflow; some statuses are reserved, so when high reaches -4 (and other reserved values), the port doesn't get released

**Comment by misi** [comment]
@x-yuri  I will try to debug it. How can I reproduce the issue? Set min and max to a very small port range? Or any hint would be appreciated. 
Thx

**Comment by x-yuri** [comment]
@misi Supposedly yes. But it's been at least a month since the issue doesn't manifest itself. With a considerable load.

What you can check is probably the following:

> it has to do with turnports.low/high overflow; some statuses are reserved, so when high reaches -4 (and other reserved values), the port doesn't get released

**Comment by misi** [comment]
@x-yuri  I tried to use very narrow port range but I could not reproduce it yet. 
Do you have any other hints, how should I reproduce it?

**Comment by x-yuri** [comment]
@misi I've just checked, 1 out of 11 turn servers is down owing to running out of disk space. The other ten are still running since Aug 10-17.

I was bitten a couple of times by running out of space. So theoretically the issue may have something to do with it. There's a strange thing about this running out of space though (atime < mtime/ctime).

```
$ stat /var/log/turn.log
  Size: 0
Access: 2018-10-08 06:37:19.256201334 +0300                                                          
Modify: 2018-10-12 12:17:54.848671578 +0300                                                          
Change: 2018-10-12 12:17:54.848671578 +0300

$ stat /var/log/turn.log.1
  Size: 103631051461
Access: 2018-10-12 06:25:01.373426892 +0300                                                          
Modify: 2018-10-08 06:37:19.260201438 +0300                                                          
Change: 2018-10-08 06:37:19.260201438 +0300
```

`6:25` must be around the time `logrotate` is to be started. It seems like the log was not rotated on Oct 9 and was kept until it ran out of space. But the timestamps are weird, can one modify or change a file without accessing it? Well, it may have something to do with running out of space. Also, it's my debug version of the `coturn` (with extra code for debugging), so I may have introduced some issues. Anyways, that doesn't seem relevant.

If my memory serves me right at some point I realized that the time is significantly off. Setting correct time may had a positive effect.

Can you take a look at [my additions][1], and tell if that could possibly break anything? I'm not sure if I should switch to current master version with less options to investigate the issue if it reproduces. One option here is for you to implement a way to ask the server about current status with regards to the ports usage. In a temporary branch, or as a new feature. Or make the server to be more specific when it says it's out of ports.

In any case, I'll tell you if anything comes up.

[1]: https://github.com/x-yuri/coturn/commit/f7d9f1207ac03930b82f6f0b098db2e066556ed5

**Comment by theassyrian** [comment]
If your still having time issues set this up:
https://wiki.debian.org/NTP
use a more realtime drift ^

Also if your getting a lot of reason: TCP socket buffer operation error (callback) see below:
https://github.com/coturn/coturn/issues/113#issuecomment-288878034

getting -> incoming packet message processed, error 401: Unauthorized see below:
https://groups.google.com/forum/#!topic/turn-server-project-rfc5766-turn-server/4uik2fZ6wQo

You should also check this out:
https://serverfault.com/questions/329845/how-to-forcibly-close-a-socket-in-time-wait
see comments about kernel settings in /proc if you want to mod the code this is a good place to do it for tcp/udp cleaning of sessions:
Because I bet your getting a lot of SYN_RECV from ddos or failed logins
netstat -an |egrep 'SYN|TIM|EST'


if your getting a lot of errors in /var/log/syslog like nf_conntrack: table full, dropping packet
than your getting ddos'ed see here
-----------------------------------------------------------------------------------------------
https://security.stackexchange.com/questions/43205/nf-conntrack-table-full-dropping-packet

**Comment by eakraly** [comment]
This issue is 4 years old
If still relevant please open a new one. Thank you!
