### ISSUE TITLE
How about turn server cluster?

### ISSUE THREAD

**Issue by chenxiemin** [coturn/coturn#219]
Hi,

I encounter a big trouble that the server speed is slow at different country. For example:
    American turn client -> Turn Server -> China turn client.
Any idea about this issue? Thank you so much.

Sincerely
Xiemin

**Comment by chenxiemin** [comment]
I use iptables to forward the udp packets and then it seems to work, thanks for all.

**Comment by gurupras** [comment]
Could you elaborate on this solution? I'm facing a similar issue where the speed of setting up a webRTC connection is painfully slow between two clients via TURN.

**Comment by misi** [comment]
IMHO the only right solution to use a closest server to the client.
So your webRTC App need to be smart and setup the closest TURN servers.

You could setup an app that make a lookup for coTURN credential and also the closest server, based on geoip and turn/signaling client IP.

See an example on my Ansible playbooks:

- https://github.com/misi/stun-api
- https://github.com/misi/stun-ansible 
  See the [coturn-rest.yml](https://github.com/misi/stun-ansible/blob/master/coturn-rest.yml)

You could setup using the ansible playbook a service like I operate for the NREN community.
See for the REST API doc page: https://api.turn.geant.org/doc/index.html

If you have eduGAIN access then you could use the service so get an api_key/token front https://turn.geant.org

**Comment by zhangalex** [comment]
Agree with misi. Set up an api, check the area of clients and return the suggested TURN to that client app.

**Comment by gurupras** [comment]
Ah, I can certainly implement a geo-IP lookup to determine the closest TURN server and return results accordingly.

Just for the same of completeness, in case of webRTC, since this is typically used by _two_ clients, would the answer be to return the closest TURN servers to _each_ of the clients? How then do we handle communication between the TURN servers? The OP seems to suggest that the problem was solved using `iptables`. Could you kindly give me a bare-minimum rundown of what that would entail?

**Comment by misi** [comment]
I also don't understand the solution that @chenxiemin mentioned above.

Two TURN server could relay traffic if needed, it is not an issue, but in most cases only one TURN server is enough. ICE agent would use two relay in the very least / worst case.

**Comment by tengg** [comment]
So confused.. 
How's the title related to anything discussed in this thread?

**Comment by chan1600** [comment]
> Ah, I can certainly implement a geo-IP lookup to determine the closest TURN server and return results accordingly.
> 
> Just for the same of completeness, in case of webRTC, since this is typically used by _two_ clients, would the answer be to return the closest TURN servers to _each_ of the clients? How then do we handle communication between the TURN servers? The OP seems to suggest that the problem was solved using `iptables`. Could you kindly give me a bare-minimum rundown of what that would entail?

I also have this question.
For example, if I use geo-IP lookup to determine the closest TURN server.
1. Client A connected to the closest TURN deployed in Japan
2. Client B connected to the closest TURN deployed in US
How do we let two TURN communicate with each other?

**Comment by tengg** [comment]
> > Ah, I can certainly implement a geo-IP lookup to determine the closest TURN server and return results accordingly.
> > Just for the same of completeness, in case of webRTC, since this is typically used by _two_ clients, would the answer be to return the closest TURN servers to _each_ of the clients? How then do we handle communication between the TURN servers? The OP seems to suggest that the problem was solved using `iptables`. Could you kindly give me a bare-minimum rundown of what that would entail?
> 
> I also have this question.
> For example, if I use geo-IP lookup to determine the closest TURN server.
> 
> 1. Client A connected to the closest TURN deployed in Japan
> 2. Client B connected to the closest TURN deployed in US
>    How do we let two TURN communicate with each other?
> 
> Edit: I just see that there is a ALTERNATE-SERVER mechanism, gonna take a look of it

Cascading the TURN server is not defined in RFC, however there’s some solution if you use AWS.

Check out global accelerator, it uses aws backbone to solve the cross continent latency issue. Or if you want to setup server less for real-time communication, check out Amazon chime sdk.

**Comment by chan1600** [comment]
> > > Ah, I can certainly implement a geo-IP lookup to determine the closest TURN server and return results accordingly.
> > > Just for the same of completeness, in case of webRTC, since this is typically used by _two_ clients, would the answer be to return the closest TURN servers to _each_ of the clients? How then do we handle communication between the TURN servers? The OP seems to suggest that the problem was solved using `iptables`. Could you kindly give me a bare-minimum rundown of what that would entail?
> > 
> > 
> > I also have this question.
> > For example, if I use geo-IP lookup to determine the closest TURN server.
> > 
> > 1. Client A connected to the closest TURN deployed in Japan
> > 2. Client B connected to the closest TURN deployed in US
> >    How do we let two TURN communicate with each other?
> > 
> > Edit: I just see that there is a ALTERNATE-SERVER mechanism, gonna take a look of it
> 
> Cascading the TURN server is not defined in RFC, however there’s some solution if you use AWS.
> 
> Check out global accelerator, it uses aws backbone to solve the cross continent latency issue. Or if you want to setup server less for real-time communication, check out Amazon chime sdk.

Thank you. I will check the global accelerator.

**Comment by tengg** [comment]
It’s free to use this endpoint to detect your location:
https://nearest-aws-region.l.chime.aws

**Comment by ggarber** [comment]
I've seen people using GCP Premium Networking (provides similar capabilities as AWS Global Accelerator) but the most common approach for this is to have coturn servers in multiple regions and connect users to the closest one as @misi said.

You have at least two options for this:
1/ Do it manually.   Your signaling or API server checks the location of the client based on his IP and returns the name/IP of a turn server close to his location.

2/ Use DNS.  You register your servers in a DNS provider (f.e AWS Route53) and that DNS provider gives the client the IP of the closest coturn instance when the client tries to establish a connection to turn.mycompany.domain.com

Let me know if that doesn't answer this question.

**Comment by eakraly** [comment]
No updates, closing.
