### ISSUE TITLE
rest api How should I set up?

### ISSUE THREAD

**Issue by goldsoft8888** [coturn/coturn#22]
My turn server: turn.me.com
My OPENFIRE SERVER: ME.COM
I need ME.COM username and password,
How should I set up?

Apart turnserver.conf, also you need to set other files?

689: ERROR: check_stun_auth: Can not find credentials of user <20769326b318>
814: ERROR: check_stun_auth: Can not find credentials of user <20769326b318>
814: ERROR: check_stun_auth: Can not find credentials of user <20769326b318>

**Comment by mom040267** [comment]
That is explained in wiki. Also, read the forum - lots of people already solved that task.

**Comment by goldsoft8888** [comment]
Please tell me the specific site, I need to refer to.
