### ISSUE TITLE
Q: allocation stats sent/receive

### ISSUE THREAD

**Issue by tengg** [coturn/coturn#224]
Hi,
Could some one enlighten me that in turnserver console, the traffic stats of sp, sp, rp, rb:

What's the received traffic in an allocation? Are they the traffic from client? Or from peers?
If the received traffic are from client, then it should be rp == sp, rb == sb, right? But they are not.

If the received traffic are from peer, then what are these traffic? Callee's traffic are supposed to from its own allocation.

Really confused..
Thanks

**Comment by misi** [comment]
AFAIU:
These are TURN client traffics.
See: /src/server/ns_turn_server.c

> If the received traffic are from client, then it should be rp == sp, rb == sb, right?
I am not sure..

**Comment by tengg** [comment]
@misi 
Thanks but still didn't figure out from ns_turn_server.c...
What do you mean by "client traffics"?
Are these traffics between client and turnserver? If so, why so many traffic from TURN-> client? There should be much..

**Comment by misi** [comment]
@tengg 

>Could some one enlighten me that in turnserver console, the traffic stats of sp, sb, rp, rb:
sp = Sent Packets
sb = Sent Bytes
rp = received Packets
rb = Received Bytes
>What's the received traffic in an allocation? Are they the traffic from client? Or from peers?
AFAIU Client<=> Sever communication. Sent from server to client and Received from client to server.
>If the received traffic are from client, then it should be rp == sp, rb == sb, right? But they are not.
No they not related anyhow to each other. So you are wrong.. Sent/Received on Server side to/from client.
>If the received traffic are from peer, then what are these traffic? Callee's traffic are supposed to from its own allocation.  
I didn't understand your last question.. Could you please rephrase it?
I hope I have answered all of your questions.
Let me know if I missed out something..

**Comment by misi** [comment]
1. Communication is two way. 
* Client send packet to Server , and server relays to peer 
* Peer could send to Server that is relayed back to Client.

2. sent packet (sp) How many packets sent. 
One packet data length could vary. So Sent Bytes (sb) is the sum of packet lengths.

**Comment by tengg** [comment]
@misi 
Please correct me if I'm wrong, since I haven't worked on the webRTC client side, only TURN server side.

Assuming we have a scenario that both caller->callee and callee->caller need TURN to relay the traffic.

Caller will definitely create an allocation on TURN server, but will callee also create an allocation as well?

**Comment by misi** [comment]
@tengg 
>Caller will definitely create an allocation on TURN server, but will callee also create an allocation as well?
It depends on client settings. My guess that both client will allocate TURN realy address, but because in most case they could communicate using only one relay and ICE will prefer more one relay than two relay they will choose to use One relay only. Of course in worst case the two browser could fall back to both client are talking to a turn server and the two allocated ip address is communicating directly. But in most cases TURN server is discovered by one of the browser as Peer Reflexive Candidate, so only one TURN is needed. I hope I am not too cloudy. But all in all in almost all cases one turn server will be used.

**Comment by tengg** [comment]
Ok finally understood it. Appreciate your help!
Thanks, I'm closing this issue.

**Comment by sumit-airmeet** [comment]
I have the same doubt which @tengg had.
If TURN just relayes the traffic, i.e. RP from client are relayed as SP to Server and similarly RP from Server are relayed as sSP to Client, then why is RP is not equal to SP?
