### ISSUE TITLE
no "make install" in build-docker.sh 

### ISSUE THREAD

**Issue by wanghaolw** [coturn/coturn#231]
This is a bug, I think...
`${docker} bash -c "./configure && make"` -> `${docker} bash -c "./configure && make && make install"`

**Comment by misi** [comment]
I am not sure. I don't believe it is a bug, rather a design decision to run it from the same place.
We could discuss that it is good or not, but I think it has been done by intention.

**Comment by misi** [comment]
I will close this let't move the discussion on the other docker issue #273
