### ISSUE TITLE
libressl support

### ISSUE THREAD

**Issue by github-k8n** [coturn/coturn#232]
When compiling coturn with libressl instead of openssl, the following error occurs:

cc  -march=x86-64 -O2 -pipe -mtune=generic -g  -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Wcast-qual -I/usr/include -I/usr/include/ -I/usr/local/include -march=x86-64 -O2 -pipe -mtune=generic -DTURN_HAS_DAEMON       -DINSTALL_PREFIX=/usr -DTURNDB=/var/lib/db/turndb -Isrc -Isrc/apps/common -Isrc/server -Isrc/client -Isrc/client++ -I/usr/include/ -I/usr/local/include/  -DTURN_NO_PQ -DTURN_NO_MYSQL -DTURN_NO_SQLITE -DTURN_NO_MONGO -DTURN_NO_HIREDIS src/apps/relay/ns_ioalib_engine_impl.c src/apps/relay/turn_ports.c src/apps/relay/http_server.c -Ilib src/apps/relay/mainrelay.c src/apps/relay/netengine.c src/apps/relay/libtelnet.c src/apps/relay/turn_admin_server.c src/apps/relay/userdb.c src/apps/relay/tls_listener.c src/apps/relay/dtls_listener.c src/apps/common/hiredis_libevent2.c src/apps/relay/dbdrivers/dbdriver.c src/apps/relay/dbdrivers/dbd_sqlite.c src/apps/relay/dbdrivers/dbd_pgsql.c src/apps/relay/dbdrivers/dbd_mysql.c src/apps/relay/dbdrivers/dbd_mongo.c src/apps/relay/dbdrivers/dbd_redis.c src/apps/common/apputils.c src/apps/common/ns_turn_utils.c src/apps/common/stun_buffer.c src/client/ns_turn_ioaddr.c src/client/ns_turn_msg_addr.c src/client/ns_turn_msg.c  src/server/ns_turn_allocation.c src/server/ns_turn_maps_rtcp.c src/server/ns_turn_maps.c src/server/ns_turn_server.c -o bin/turnserver  -Wl,-O1 -Wl,--as-needed -Wl,-O1 -Wl,--as-needed -L/usr/lib/ -L/usr/local/lib/ -L/usr/lib64/ -L/usr/local/lib64/ -lrt -lnsl -lresolv -pthread -lcrypto -lssl -levent_core -levent_extra -levent_openssl -levent_pthreads  -Wl,-rpath,/usr/lib/ -Wl,-rpath,/usr/local/lib/ -Wl,-rpath,/usr/lib64/ -Wl,-rpath,/usr/local/lib64/ -Wl,-rpath,/usr/local/lib 
src/apps/relay/turn_admin_server.c: In function ‘https_print_top_page_header’:
src/apps/relay/turn_admin_server.c:1416:64: warning: ‘</i></b><br>
   ’ directive output may be truncated writing 14 bytes into a region of size between 13 and 45 [-Wformat-truncation=]
     snprintf(dst,ADMIN_USER_MAX_LENGTH*2," admin user: <b><i>%s</i></b><br>\r\n",as->as_login);
                                                                ^~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from src/apps/relay/turn_admin_server.c:32:
/usr/include/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 34 and 66 bytes into a destination of size 64
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/server/ns_turn_server.c: In function ‘handle_turn_allocate’:
src/server/ns_turn_server.c:1144:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
     if(even_port>0) {
       ^
src/server/ns_turn_server.c:1149:4: note: here
    case STUN_ATTRIBUTE_REQUESTED_ADDRESS_FAMILY: {
    ^~~~
/usr/lib//libevent_openssl.so: undefined reference to `BIO_set_data'
/usr/lib//libevent_openssl.so: undefined reference to `BIO_set_shutdown'
/usr/lib//libevent_openssl.so: undefined reference to `BIO_meth_set_read'
/usr/lib//libevent_openssl.so: undefined reference to `BIO_meth_set_puts'
/usr/lib//libevent_openssl.so: undefined reference to `BIO_set_init'
/usr/lib//libevent_openssl.so: undefined reference to `BIO_meth_set_destroy'
/usr/lib//libevent_openssl.so: undefined reference to `BIO_meth_new'
/usr/lib//libevent_openssl.so: undefined reference to `BIO_meth_set_write'
/usr/lib//libevent_openssl.so: undefined reference to `BIO_get_init'
/usr/lib//libevent_openssl.so: undefined reference to `BIO_get_shutdown'
/usr/lib//libevent_openssl.so: undefined reference to `BIO_get_data'
/usr/lib//libevent_openssl.so: undefined reference to `BIO_meth_set_ctrl'
/usr/lib//libevent_openssl.so: undefined reference to `BIO_meth_set_create'
collect2: error: ld returned 1 exit status
make: *** [Makefile:134: bin/turnserver] Error 1

**Comment by github-k8n** [comment]
Hi, any chance of getting this addressed in a future version?
Do you need any further input/data on this?

**Comment by misi** [comment]
Try to send a pull request with your proposed changes.
Unfortunately it is over my competence. 
Sorry for bugging but @mom040267 could you add any comment?

**Comment by mom040267** [comment]
Unfortunately, I do not have any immediate solution - just somebody has to
take time and investigate it. I believe that a while ago I tried libressl
and it was working. Either something changed or the compiling environment
is incorrect.

Oleg

**Comment by github-k8n** [comment]
This is on gentoo using
libressl-2.6.4
coturn-4.5.0.7

Looking through the internet for similar issues with other packages, I think it might have to do with openssl version detection? (sorry,  not really familiar with that..)

i.e. replace something like

_\# if OPENSSL_VERSION_NUMBER < 0x10100000L_

with

_\# if OPENSSL_VERSION_NUMBER < 0x10100000L || defined(LIBRESSL_VERSION_NUMBER)_

**Comment by misi** [comment]
Coud you test it if it work and send a Pull Request? We are out off resources, don't find time to do it.. Sorry..

**Comment by github-k8n** [comment]
Issue seems to be related to libevent.
Using head of libevent git and building coturn with that seems to work fine. Thus now waiting for a new libevent release.
See also https://bugs.gentoo.org/652586

Thus this issue could probably be closed. (closing)
