### ISSUE TITLE
 Cannot find credentials of user (Opera) - My turn server broken

### ISSUE THREAD

**Issue by BR9** [coturn/coturn#238]
Dear All,

my english a little weak sorry

I'm not sure if the Turn server works

turnserver.conf
-----------------------

```
`# Run as TURN server only, all STUN requests will be ignored.
no-stun

# Specify listening port. Change to 80 or 443 to go around some strict NATs.
listening-port=3478
tls-listening-port=443

# Specify listening IP, if not set then Coturn listens on all system IPs.
listening-ip=139.59.128.10
relay-ip=139.59.128.10
external-ip=139.59.128.10

# These lines enable support for WebRTC
fingerprint
lt-cred-mech
user=*****:*****
realm=instreamservers.com
server-name=instreamservers.com

mysql-userdb="host=localhost dbname=coturn user=root password=******* connect_timeout=60"


# Authentication method


total-quota=100

# Total bytes-per-second bandwidth the TURN server is allowed to allocate
# for the sessions, combined (input and output network streams are treated separately).
bps-capacity=6553600
max-bps=6553600

# use real-valid certificate/privatekey files
cert=etc/apache2/ssl/instreamservers_com.crt
pkey=etc/apache2/ssl/ssl.instreamservers.com.key


# This line provides extra security.
stale-nonce

log-file=/var/log/turnserver/turn.log
no-loopback-peers

mobility
no-sslv3
no-tlsv1
no-tlsv1_1
`
```
Chrome = Is Turn Server Active = Yes
Mozilla = Is Turn Server Active = Yes, sometimes = no
Opera = Is Turn Server Active = NO!

I Using simplewebrtc and signalmaster = it works fine

But I can not get broadcast between opera and safari
I thought you'd fix it with a turn server

```
root@ubuntu-s-1vcpu-2gb-fra1-01:~# turnutils_uclient -u hakanberk -W ****** instreamservers.com

0: Cannot complete Allocation
0: ERROR: Cannot complete Allocation
```

![x532](https://user-images.githubusercontent.com/27887377/39161046-600e9558-4777-11e8-906e-e1c94dc7440d.png)

 just opera 

![adsiz](https://user-images.githubusercontent.com/27887377/39161159-0dc65b90-4778-11e8-8544-60f36e934e55.png)

Thanks for your help

**Comment by misi** [comment]
Try these:
1. Check your user database that passwords are in HA1 format.
2. Try to comment out stale-nonce. see more about it. https://medium.com/confrere/gone-in-1100-seconds-hunting-bugs-on-the-edge-of-webrtc-132a186c45dd
3. Comment out mobility. I guess you don't require it.

**Comment by BR9** [comment]
Dear @misi 

This is the final situation

![x1234](https://user-images.githubusercontent.com/27887377/39222777-150fbeee-4847-11e8-9a56-76ba807070a8.png)

But there is no broadcast stream.

Can you help me?

**Comment by misi** [comment]
I see now that the authentication works correctly.
Try to allow STUN in your config file
I see many STUN (binding 0x1)request that's are ignored.

**Comment by BR9** [comment]
@misi Thank You!
Everything is ok

The final question
I did not understand the static_auth and user relationship

How exactly should I create an algorithm?

Sample;

```
user:hakanberk:asdasd123asd
             
# Authentication method
use-auth-secret
static-auth-secret=asdasd123asd       
```

how can user and static-auth-secret connect with each other?

**Comment by misi** [comment]
unfortunately I don't fully the first half of your question.

You could find here more info about the process of auth in the following function
https://github.com/coturn/coturn/blob/114881bc9a455b8694634dd4cc3c3acb22845826/src/apps/relay/userdb.c#L401

And about  static_auth in line 617.

I hope this helps..

**Comment by BR9** [comment]
@misi  

I thank you for all your help 😃

**Comment by misi** [comment]
@BR9 
You are welcome..
