### ISSUE TITLE
Google Network Loadbalancer

### ISSUE THREAD

**Issue by geigev** [coturn/coturn#239]
Hello,
I am trying to run a cluster of turn/stun servers behind a layer 3 network load balancer on google cloud. The turn/stun servers make up a "target-pool" and the load balancer (forwarding rule) points to the pool. I managed to get the turn server to work using the `--listening-ip=0.0.0.0` flag, but I still cannot get reflexive candidates despite attempting various configurations of the `--external-ip`; the stun server **does work** if I hit the coturn's ip directly rather than going through the network load balancer, but obviously I don't want to do this.

Does anyone have any ideas on how I could get this to work? I assume its going to involve some combination of the `--listening-ip` and `-external-ip flags.`

**Comment by misi** [comment]
Please close the issue if you feel it is solved. thx..
