### ISSUE TITLE
non-interactive build and install

### ISSUE THREAD

**Issue by tgabi333** [coturn/coturn#24]
configure should respect non-interactive consoles, and use cat command instead of more

We try to use always the newest coturn implementation building from source, but our scripts cannot handle the last command of `make install` as it uses more command.

**Comment by mom040267** [comment]
will be fixed in 4.5.0.3

**Comment by mom040267** [comment]
fixed in 4.5.0.3

**Comment by tgabi333** [comment]
Thank you! :)
