### ISSUE TITLE
user-quota actually behaves like total-quota?

### ISSUE THREAD

**Issue by daniloarcidiacono** [coturn/coturn#243]
Hi,
I'm tuning my coturn server installation in order to mitigate denial-of-service attacks.
To that end I've set the user-quota option, but when I try to use two different users, the second one seems to be blocked by the allocation of the first one, even if they have different usernames.

Here's an excerpt of my configuration file (any missing standard option is commented in my full config file):

```
listening-port=443
tls-listening-port=443
alt-listening-port=3478
alt-tls-listening-port=443
verbose
fingerprint
lt-cred-mech
user=adminOne:Password
user=adminTwo:Password
realm=mycompany.org
check-origin-consistency
user-quota=2
log-file=/var/log/turn.log
pidfile="/var/run/turnserver.pid"

```

Note: I use 2 as user-quota because each user creates two RTCPeerConnections (one for sending a stream, and one for receiving).
I've also tried the TURN rest API authentication mechanisms, but nothing changed.

Thanks

**Comment by misi** [comment]
Thanks for reporting!
https://github.com/coturn/coturn/blob/d89fcb28fc857c6b850670246ffd601077ecf4fe/src/apps/relay/mainrelay.c#L1250-L1257

**Comment by daniloarcidiacono** [comment]
Just to be sure: as a quick workaround, can I simply swap user-quota with total-quota in my configuration file or that would still lead to inconsistencies in coturn's data structures?
If that's the case, when can I expect a new release?Unfortunately, I really need this feature working for production. 

Thanks

**Comment by misi** [comment]
I need to check! I will try to do it tomorrow..

Danilo Arcidiacono <notifications@github.com> ezt írta (időpont: 2018. máj.
10., Csü 15:46):

**Comment by pplanel** [comment]
Any update on this?

**Comment by misi** [comment]
I believe I have fixed it!

I think this commit was wrong: https://github.com/coturn/coturn/commit/59ee141ff039c8ee71602442f62ccdd22b6ca8e3

Please test the fix in the master branch..
Let me know if you still experience issues or if it works fine. 
Thanks!
