### ISSUE TITLE
Port range for turn server mode

### ISSUE THREAD

**Issue by Josue-T** [coturn/coturn#246]
Hello,

As I understand, to have a full functional turn server we need to open a port range (between 49152 and 65535).  This range could be reduced (I tried with 40 ports) with the `min-port` and` max-port` options. This means that we need to open this range in the Turn server firewall. These things could be a big security hole in some cases. So my questions are:
- What is the minimum port range we need to open?
- Is there a solution to run a full functional server without opening this port range in the firewall ?

**Comment by misi** [comment]
The port range depends on the number of allocation, and so it is connected on the number of parallel client connections..
* Please avoid to set the port range too tight to not over-constrain your service.
* No

**Comment by misi** [comment]
I think I answered your question. 
If you have any further question then please open a new issue.
