### ISSUE TITLE
debian package is missing in downloads since v4.4.5.3

### ISSUE THREAD

**Issue by spariev** [coturn/coturn#25]
The last version of debian package in Downloads is 4.4.5.3 - http://turnserver.open-sys.org/downloads/v4.4.5.3/turnserver-4.4.5.3-debian-wheezy-ubuntu-mint-x86-64bits.tar.gz . All versions after that (4.4.5.4, 4.5.0.1, 4.5.0.2) do not have debian packages. Is it dropped altogether or it's just an error ?

**Comment by mom040267** [comment]
No, it is not dropped, we just decided to let users to use whatever latest
package is available in Debian and its derivatives:

https://packages.qa.debian.org/c/coturn.html

The same is true for FreeBSD port.

Oleg

**Comment by spariev** [comment]
Thanks for the quick reply.
So as far as I understand it, to get the latest version of coturn I should go to https://packages.debian.org/sid/amd64/coturn/download and download deb file from preferred mirror - is it right ?

**Comment by mom040267** [comment]
I guess you are right.

We are just submitting the package to Debian. The lifecycle of the package
is out of our control.

Oleg

**Comment by spariev** [comment]
Ok, thanks, closing the issue then.
