### ISSUE TITLE
Don’t Assume Sun Studio Compiler on SunOS

### ISSUE THREAD

**Issue by mrferda** [coturn/coturn#250]
illumos users may want to build coturn with gcc while the configure script adds imcompatible Sun Studio compiler flags.

Builds fine after commenting out line 619-624 in configure.

Please consider another method to determine the compiler in use.

**Comment by misi** [comment]
Could you please add a PR with your proposed changes? THX

**Comment by mrferda** [comment]
Here’s a patch that provides the functionality.
Not tested with actual Sun Studio since I don’t have access to a Solaris box.
Not sure how to suppress the gcc errors.

[configure_SunOS_gcc.patch.txt](https://github.com/coturn/coturn/files/2121234/configure_SunOS_gcc.patch.txt)

**Comment by misi** [comment]
On linux your PR makes trouble. Please fix it..

**Comment by misi** [comment]
@mrferda

I will close this issue because the PR made problems on Linux, and I didn't received new fix.
Please refactor and reopen the issue after it.
Thanks for your patience!
