### ISSUE TITLE
SDP offer creation speed

### ISSUE THREAD

**Issue by Avol** [coturn/coturn#251]
Creating an offer takes around 15 seconds. Using this service: http://xirsys.com/, it takes around 1 second to create an offer. Is there a way to get such fast connection speed with coturn? If so, how can I do that? If that makes any difference I'm connecting from wrtc npm lib using node.js using UDP packets.
Thanks, in advance.

**Comment by misi** [comment]
@Avol I don't really understand what is your problem. offer creation is connected on STUN/TURN speed only if you use classic ICE. Use trickle ICE. 

Could you please give us a detailed comparison and logs and packet dumps that we can analyze?

**Comment by misi** [comment]
@Avol  I couldn't help you from this. I close this issue. Please reopen it if I can help you further..
