### ISSUE TITLE
Logging before config file is read

### ISSUE THREAD

**Issue by eiver** [coturn/coturn#255]
Hi I have the following issue. I want coturn to log just to: /var/log/coturn/coturn.log instead of default settings.

On Linux Mint (Ubuntu) I have the following in the /etc/turnserver.conf:
log-file=/var/log/coturn/coturn.log
simple-log
no-stdout-log

Unfortunately some entries still end up in the default log location. I looked at the code and I think the issue is in mainrelay.c line 1929 and 1932.

Function print_features() is called before read_config_file(), so some entries are logged using default settings instead of what is defined in the config file. I think the function read_config_file() should be called as early as possible in main().

Unfortunately I cannot test it myself, because I don't know how to compile this project under Linux.

**Comment by misi** [comment]
Many thanks for the report! 
I am not sure if there wasn't any reason for this design decision..
Could you please send a Pull Request with the fix?

**Comment by eiver** [comment]
Hi!

Here is what I did so far:
1. Managed to compile the code
2. Analyzed git history and determined, that this peace of code has not been modified since "initial code import", so it must be rather old
3. Determined that just moving read_config_file() below print_features() is only part of the solution
4. set_rtpfile() from ns_turn_utils.c is still being called somewhere and it writes "log file opened" to the default file, but I can't figure out where this call occurs

I will continue to analyze this bug, but it will probably take some time as I don't quite understand the source code yet. It would probably be better and faster, if someone with more experience with this code base made the change.

**Comment by misi** [comment]
Unfortunately Oleg is busy with other works and I am the only person who actively contributes in this project actually. :(
This way please if possible help me and go on with this fix and continue to read the code...
Thanks!

**Comment by eiver** [comment]
That is most unfortunate. Its such a great project. Too bad so few people are interested in maintaining it. Kudos to you.

Anyway you can find the pull request for this bug at https://github.com/coturn/coturn/pull/264

Please review it carefully, as this is my first ever commit to this project and I don't know exactly the inner workings of a stun/turn server, so couldn't test the whole functionality.
I only tested that it runs (doesn't crash on startup) and that it doesn't log to the wrong log file anymore, so the bug should be fixed.

**Comment by misi** [comment]
@eiver 
Now I am closing this issue.. 
PR has been merged! Many Thanks for the PR!
 
Highly appreciated your help and cooperation!
Thanks!
