### ISSUE TITLE
Could mention the semicolon in file not found warnings.

### ISSUE THREAD

**Issue by heyheyjc** [coturn/coturn#256]
I realize this was my fault, having copied the SSL certificate paths from nginx.conf, however it was still several hours of my life getting TURN working with SSL I'll never get back.

It wasn't permissions, it wasn't anything clever, it was the semicolons at the end of the lines, which were invisible to me by then,

**Comment by misi** [comment]
Please send a Pull Reuest..

**Comment by heyheyjc** [comment]
Which would be best?
1) add a warning at the top of the default turnserver.conf, 
2) add 'path/permissions/semicolons?' to the file not found messages,
3) allow trailing semicolons (is there a downside to this?)

**Comment by misi** [comment]
I think the best way would be add a warning in the log in case there is a semicolons in the end. Saying in the warning that please doublecheck your config.

But please also consider that trailing semicolons are a valid filename!

**Comment by heyheyjc** [comment]
Yeah, I did wonder about that, even though lots of other configs, eg NGINX, use semicolons.

My C/C++ is 20 years old, you don't want me trying any real programming, but "Double-check your config" is one of those messages that merely frustrates people; they know their config has a problem, they just can't find it. Offering specific things to look for is way better.

How about option 2. above? Would you accept that?

**Comment by misi** [comment]
I don't really understand your option 2 proposal. :-/

>My C/C++ is 20 years old, you don't want me trying any real programming

I learnt in 1996-1997, so my knowledge is comparable with yours.. 
I am not the writer of these codes. I am just a simple maintainer. Don't over expect my competence.. :-)

My proposal was to point out exactly in which option the semicolon is problematic.
If we point out the problem exactly and warn the user with option name it is easy to find and fix.

**Comment by misi** [comment]
It is done AFAIU.
