### ISSUE TITLE
Coturn Nginx reverse_proxy Nextcloud Talk

### ISSUE THREAD

**Issue by jonathanmmm** [coturn/coturn#259]
Hi Coturn Team and all others :) 

I am running a Nextcloud Server with Nextcloud Talk and I want to use Coturn as the STUN and TURN Server.

I got the Server working on the standard port but I want it also to run as a backup on port 443 or completely.

I can make the coturn website working over tls with reverse proxy and without, but coturn probably doesnt use the normal http protocol.

So I used a stream to get it without http, but I dont get it to work properly.

in my nginx.conf I have:

`stream {
        server {
                listen 443 udp;
                proxy_pass 127.0.0.1:5349;
        }
        server {
                listen 443;
                proxy_pass 127.0.0.1:444;
        }
}
http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_tokens off;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        gzip on;
        gzip_disable "msie6";
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
`

(How can I make the Code look good in here? Tried the insert Code method but it looks chaotic)

and my coturn file in sites-enabled/available:

`upstream coturn {

server 127.0.0.1:5349;
}

server {
    listen 444; #ssl http2;
    listen [::]:444; #ssl http2;
    server_name coturn.wwjd.dynu.net 127.0.0.1;

   ssl_certificate /root/wwjd.dynu.net_ecc_pem/fullchain.pem;
   ssl_certificate_key /root/wwjd.dynu.net_ecc_pem/key.pem;

    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_protocols TLSv1.1 TLSv1.2;  # drop SSLv3 and TLSv1 (POODLE vulnerability)
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    ssl_session_tickets on;
    ssl_session_ticket_key /etc/nginx/session-key/nginx_ticketkey;

    ssl_prefer_server_ciphers on;
ssl_ciphers "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH EDH+aRSA !aNULL !eNULL !LO$
    ssl_stapling on;
 ssl_stapling_verify on;
    ssl_trusted_certificate  /root/wwjd.dynu.net_ecc_pem/fullchain.pem;
resolver 192.168.x.1 valid=300s; #My Router
resolver_timeout 5s;
    # Add headers to serve security related headers
    # Before enabling Strict-Transport-Security headers please read into this
    # topic first.
     add_header Strict-Transport-Security "max-age=35768000; includeSubDomains; preload";

    ## Headers
   add_header Referrer-Policy "no-referrer";
   add_header X-Frame-Options "ALLOW-FROM AllowAll" always;
   add_header X-XSS-Protection "1; mode=block";
   add_header X-Robots-Tag none;
   add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;
#add_header Access-Control-Allow-Origin wwjd.dynu.net;
    location / {
            proxy_pass         http://coturn;
           # proxy_responses: 0;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
  }
}
`

My Router can forward ports, both tcp and udp e.g. port 443 tcp to my server on port 443.

Or he can forward the outside port 443 tcp to inside 4444 tcp e.g.

I could get coturn working with udp 443 ----> udp 5349 but nothing else, still tcp 443 is missing.

Has somebody an idea?

Many people have this problem, wanting to run TURN and STUN server with other web applications at the same time.

I can also proxy http and not https like in this example, does it make a difference? I can`t proxy_pass to non http only in stream (see nginx.conf) but not in the coturn file.

**Comment by misi** [comment]
Hi,

My idea is to use iptables portforwarding 443 to normal stun or turn port.

My 2 cents,
Misi

jonathanmmm <notifications@github.com> ezt írta (időpont: 2018. aug. 7., Ke
12:48):

**Comment by jonathanmmm** [comment]
So I could get port 443 udp get to work over the router portforwarding. Is there any way to let the tcp port 443 be shared for nextcloud (or any other website) and the coturn server? Both could have different domain or subdomain names with wildcard certificates.

**Comment by jonathanmmm** [comment]
Hi,

I am using in the turnserver.conf:

no-loopback-peers does this make it inpossible? because I am forwarding from nginx to coturn over 127.0.0.1?

And bps-capacity=0 means off or the byte limit is 0?

also I put stale-nonce but without a number behind?

I just followed installing guides.

**Comment by jonathanmmm** [comment]
I am using the following turnserver.conf:

tls-listening-port=5349
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=xxxxxx....
realm=subdomain.xxxx.xxxx
total-quota=100
bps-capacity=0
stale-nonce
cert=/root/xxx/fullchain.pem
pkey=/root/xxx/key.pem
dh-file=/xxx/dhparam.pem
cipher-list="xxxx"
#no-loopback-peers
no-multicast
no-tlsv1


So If I am using no-loopback-peers (which I now uncommented) I can't establish a connection via 127.0.0.1 etc.

So I need this to be off, because nginx is forwarding over a subdomain over the localhost to coturn, right?

Also does this makes sense:
total-quota=100
bps-capacity=0
stale-nonce

total-quoata means maximum of 100 users?
bps-capacity=0 means limit of bytes is 0 does not make sense to me?
If I type turnserver it gives a lot of information and also:
 "0 bytes per second allowed, combined server capacity"

stale-nonce has in the example "=600" behind it but I don't have a number.

I just copied it from guides for the nextcloud talk app but does this makes any sense?

**Comment by misi** [comment]
I think we discussed many things.
Do we have any further open question? 
If no open question, then please close this issue. Thanks!

**Comment by rasos** [comment]
@jonathanmmm did you finally succeed to forward 443 udp to Jitsi Meet? Does ice4j propose this port as a viable pairing option?

**Comment by jonathanmmm** [comment]
@misi @rasos Sorry for the late answer.
I still don`t know how to get it to work behind nginx.
Is there any way to split the traffic through dns (like coturn.website.com and website.com) one time to TURN and STUN and the other time to HTTPS? Or which traffic it is?

It is also very difficult to prove that stun or turn works. the webrtc test just puts sometimes "done" and sometimes not and sometimes "done" even if I change the port to some completely different that is not open, e.g. Port 2.

**Comment by misi** [comment]
@jonathanmmm  
1.Unfortunately I don't understand the first half of your question. Can you please explain it more. thx..
2. To test sun/turn server you can use turnutils_uclient see the example/scripts folder for examples.

**Comment by jonathanmmm** [comment]
@misi I want to run coturn behind nginx.
So my nextcloud can use https over TCP 443 and coturn can use TCP 443, too on the Same Maschine.

Nginx uses DNS names too Split.
E.g. nextcloud.mydomain.com
Is nextcloud and myprivateblog.mydomain.com is my Blog. Both Using TCP 443 HTTPS.

**Comment by misi** [comment]
@jonathanmmm 
I guess Nginx acts like a NAT. Terminates tcp connection on proxy and opens a new between the proxy and turn server.
So you need configure coturn accordingly.
set --external-ip to your nginx global ip..

(Just a waning the reverse proxy will load one core on coturn. AFAIK multi core cpu load balancing is based on source ip and if reveres proxy hide it then it will only load 1 core.)

**Comment by jonathanmmm** [comment]
Do you mean 0.0.0.0:443 (this I believe what nginx listens)
I dont know If there is a way that nginx can determine If the traffic is for HTTPS or Turn

**Comment by misi** [comment]
I mean the global IP of your nginx host.

**Comment by jonathanmmm** [comment]
My nginx host has some 192.168.x.x Ip and a global ipv6 but is behind my Router.
Do you mean the 192.168.x.x.?

**Comment by jonathanmmm** [comment]
In nignx I can use proxy_pass and this can go to http://127.0.0.1:5349 for example. But Turn doesnt use http or https right?

**Comment by daimoc** [comment]
Hi, It seems possible with Nginx to split https traffic from other ssl connection using ssl_preread_module according to https://superuser.com/questions/1135208/can-nginx-serve-ssh-and-https-at-the-same-time-on-the-same-port and http://nginx.org/en/docs/stream/ngx_stream_ssl_preread_module.html#ssl_preread.
So in theory with Nginx, you can send your nextcloud HTTPS traffic to one internal port and the STUN traffic to an other but I didn't try it wet.

**Comment by jonathanmmm** [comment]
Thanks, I would like to try that. I am using Debian 9 with nginx 1.10.3 so I need to install backports of nginx-stretch right? (Found in the changelog the adding of preread by nginx (1.12.0-1) experimental; urgency=medium on https://metadata.ftp-master.debian.org/changelogs/main/n/nginx/nginx_1.14.1-1~bpo9+1_changelog)

What kind of traffic uses STUN and TURN? I have configured:
no-udp
no-tcp
and enabled TLS with certificate, so they should also use TLS right? Is TURN and STUN sending the DNS name or do I need to make like that the website uses TLSv1.1 and STUN and TURN TLSv1.2 to differentiate?

**Comment by dhaminitinAltran** [comment]
@jonathanmmm can you share the turn config for TLS setup?

**Comment by jonathanmmm** [comment]
`tls-listening-port=5349                                                                                                                              
fingerprint                                                                                                                                          
lt-cred-mech                                                                                                                                         
use-auth-secret=<mysecret>                                                                                                                                                                                               realm=website                                                                                                                         
total-quota=100                                                                                                                                      
bps-capacity=0                                                                                                                                       
stale-nonce                                                                                                                                          
cert=/opt/certs/website_ecc/fullchain.pem                                                                                               
pkey=/opt/certs/website_ecc/key.pem                                                                                                     
dh-file=/etc/ssl/certs/dhparam.pem                                                                                                                   
cipher-list="ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AES:RSA+3DES:!ADH:!AECDH:!MD5"                     
no-loopback-peers                                                                                                                                    
no-multicast-peers                                                                                                                                   
no-sslv3                                                                                                                                             
no-tlsv1                                                                                                                                             
no-tlsv1_1                                                                                                                                           
no-stdout-log                                                                                                                                        
simple-log                                                                                                                                           
log-file=/dev/null`

**Comment by dhaminitinAltran** [comment]
@jonathanmmm  is the Nginx configuration the same which is mentioned in the first comment? and were you able to relay both TCP and UDP traffic via the Ngnix server to the co-turn server?

**Comment by jonathanmmm** [comment]
Feb 10 04:17:03 turnserver[981]: 2: Trying to bind fd 316 to <[2003:ipv6 address]:3478>: errno=99
Feb 10 04:17:03 turnserver[981]: 2: Cannot bind TLS/TCP listener socket to addr [2003:ipv6address]:3478

I found this in systemctl status coturn.service

Netstat shows that turnserver binds to many ports, also to 2003:xx:3478 ipv6 but mostly not public (fd8b or something like that)

**Comment by dhaminitinAltran** [comment]
can you share the Ngnix conf file as well? or give me a place where I can contact you? I am facing this issue for a long time.

**Comment by jonathanmmm** [comment]
Look at the top of this issue, this was my proposed conf for coturn in nginx. Right now I dont use nginx and coturn dkrectly, didnt work so far.
