### ISSUE TITLE
mysql-encryption refactor

### ISSUE THREAD

**Issue by misi** [coturn/coturn#263]
@mustafabingul  @erdemduman
I am not really satisfied yet with the options number name and convetions conform, but I don't want to block you so I did merged PR260. But it would be nice if you could you please refactor the option to align the conventions: 

1. Do not use 0/1 option but have a default not encrypted password and if password file presents.
2. Reffactor and use less options in turnadmin.

Thank You for your help and cooperation in advance!

**Comment by erdemduman** [comment]
1. Done

2. If there is a way to get second argument without another option (For example: turnadmin -E -p password /keyfilepath) , -f option can be removed. However, getopt does not allow that kind of command as far as I can see. It searches for another option when the white space appears. It would be amazing to have your opinion about reducing options.

Thanks!

**Comment by mustafabingul** [comment]
When will you release next version of containing our content(our commits)?

**Comment by misi** [comment]
Unfortunately I didn't made yet any release. I need to figure out howto make it.
(I also need to ask help from Oleg.)

But first we need to test carefully the changes on all platform! (BSD, Linux, etc.)

**Comment by erdemduman** [comment]
Sorry for late reply.
There should be a pull request now.

As far as I understand, you mean "-f" option should be deleted and "-E" option, which has already been created, should be used instead of "-f" option.  Am I right?

**Comment by misi** [comment]
@erdemduman @mustafabingul 
Thanks for the PR. 
I have edited and merged it. 
I hope you like it in the actual little bit edited form.
If you are happy with it then please let me know, and I will close this issue. 
Thx!

**Comment by erdemduman** [comment]
Thanks! You can close the issue.
There is another thing btw;

Since we are using this turn server in our project, we need the latest release. Otherwise, we are gonna have to use a modified old release, which is coturn-4.5.0.7.
So, we have to be sure whether we are using a stable release, which means a bug free code should be used.
Is it possible for you to provide a new release as soon as possible?

Best wishes!
@misi

**Comment by misi** [comment]
@erdemduman 
I am working hard on testing the master branch this week, and release is in the pipe.
Please report if you find any issue..

Thanks for your patience..
