### ISSUE TITLE
coturn fails with default Let's Encrypt cert/key permissions

### ISSUE THREAD

**Issue by hakong** [coturn/coturn#268]
Environment: CentOS 7.5 (turnserver-4.5.0.7-0.el7.centos.x86_64.rpm)

Problem:
```
turnserver[29388]: 0: WARNING: cannot find certificate file: /etc/letsencrypt/live/domain.com/fullchain.pem (1)
turnserver[29388]: 0: WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
turnserver[29388]: 0: WARNING: cannot find private key file: /etc/letsencrypt/live/domain.com/privkey.pem (1)
turnserver[29388]: 0: WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
```

coturn starts and runs as the user "turnserver", which does not have access to the certificates created by Let's Encrypt with their default permissions. This works fine with other services (nginx/apache/whatever) since they drop privs **after** reading the certs. Ideally coturn would also behave this way.

I'd prefer no to make my certs accessible to non-root users. I could use post-hook scripts with Let's Encrypt, but I think coturn should be able to work with the default perms Let's Encrypt uses.

Just throwing this out there. Appreciate a nice and clean solution if anyone thinks of one! I'll think about it and try to come up with one.

**Comment by misi** [comment]
Can you please double check your startup script start with root and specify "proc-user" and "proc-group"? 
I run a test and for me it seems to work fine...

**Comment by hakong** [comment]
Installed
```
turnserver-4.5.0.7-0.el7.centos.x86_64.rpm
turnserver-client-libs-4.5.0.7-0.el7.centos.x86_64.rpm
turnserver-utils-4.5.0.7-0.el7.centos.x86_64.rpm
```
/usr/lib/systemd/system/turnserver.service says:
```
[Service]
User=turnserver
Group=turnserver
```
This is the reason why coturn can't read certificates. It starts as the user `turnserver` and group `turnserver`.

coturn would have to start as root:root, read the cert/privkey, then drop privs to coturn:coturn.

**Comment by misi** [comment]
I think the issue is more or less resolved. 
If you think there still left any open question then please reopen it or open new one.

**Comment by misi** [comment]
@alexte 
Please open a new issue about it, and please add more details like coturn sw version and your config, etc.. 
Many Thanks!

**Comment by alexte** [comment]
Do you think this is a bug ? Aren't there reasons for spaces at the end of a config line ? 
It might be worth only a note in the documentation.

**Comment by benbro** [comment]
I think nginx let you load new config and cert without stopping existing connections. It creates  a new worker process and stops the old one only when all connections are closed.
https://unix.stackexchange.com/a/333580

Isn't changing permissions on a private cert insecure and no standard?

**Comment by expressrussian** [comment]
Ubuntu 19.10 - i have the same error.
No spaces in config.
User turnserver/turnserver
-rw-r--r-- 1 root root 3562 Oct 12 20:18 fullchain5.pem
lrwxrwxrwx 1 root root   38 Oct 12 20:18 fullchain.pem -> ../../archive/domain.eu/fullchain5.pem

The files should be readable by anybody! Why coturn cannot read available files???

**Comment by paulmenzel** [comment]
@expressrussian, please open a new issue as yours seems unrelated. But, the Let’s Encrypt certificates should *not* be readable by everyone. By default, the directory the certificates are stored in are only accessible by the user `root`.

    $ ls -ld /etc/letsencrypt/archive/
    drwx------ 3 root root 4096 Mar 18 14:46 /etc/letsencrypt/archive/
