### ISSUE TITLE
coturn server video call setup, works one way, not the other

### ISSUE THREAD

**Issue by cchadwickk** [coturn/coturn#275]
Hi

(If there is another suitable subreddit for this, please let me know)

We're trying to get our video calling webapp to work using a coturn server. The connection works one way from office wifi to 4g device network but not the other way around. From what i've gathered so far, the ICE candidates are gathered correctly, but the connection fails on connecting to relay server. Any help would be appreciated. I've manually tried disabling UDP relays incase that might've been an issue. I've tried:

1.Adding ?transport=TCP
2.UDP and TCP ports are open on the EC2 instance running the coturn server Thanks

The failing log : https://pastebin.com/TZ39CacR
Log for working: https://pastebin.com/t2031mZu

157 ip is 4g
118 and 115 are office
172 is internal ip of turnserver
13 is the external ip of ec2 server

**Comment by cchadwickk** [comment]
- Coturn-4.5.0.7 'dan Eider'
- Adding the chrome://webrtc-internal dump and event log 

[webrtc_internals_dump (1).txt](https://github.com/coturn/coturn/files/2378507/webrtc_internals_dump.1.txt)

[event_log_20180913_1438_544_2.log](https://github.com/coturn/coturn/files/2378514/event_log_20180913_1438_544_2.log)
-Since this is a webapp I can provide you with credentials to try it out aswell over email or something.
 By packet dump you mean tcpdump ? What filters should I apply ? I will keep adding more log files as I obtain them.

**Comment by misi** [comment]
Trickle ICE is used. Check signaling too..
I need ICE debug logs from both side.

I can see from webrtc_internals_dump that ICE connection state is still in checking state.
ICE connection state: => ICEConnectionStateChecking

So it is still doing stun checks, not yet finished the checks. Wait more in trace until timeout..

Try to trace the ice agent debug.
My guess that it is not really coturn related issue, but I can't tell anything from this. 

Could you please provide more details? 

From both side ice/stun/turn debug trace log.

Test the turn with two browser first on both mobile and office network.. 
And try to make an ICE trace.

As mentioned you could find some info here: https://misi.github.io/webrtc-c0d3l4b/#30

**Comment by cchadwickk** [comment]
Alright for some reason, the google turn server works fine for our setup.
Google
{
                    urls: 'turn:64.233.188.127:19305?transport=udp',
                    username: 'CIjR8twFEgYhlX3HtQoYzc/s6OMTIICjBQ',
                    credential: 'b64oHkaVuv7YapRLyCApUiFiraw='
}
Ours:
turnserver.fuguchat.com:3478

How can I gather what the difference in the setup is ?

**Comment by cchadwickk** [comment]
--server-relay

So the server works with this option. What is this for.....

**Comment by misi** [comment]
```
# Server relay. NON-STANDARD AND DANGEROUS OPTION.
# Only for those applications when we want to run
# server applications on the relay endpoints.
# This option eliminates the IP permissions check on
# the packets incoming to the relay endpoints.
#
#server-relay
```

**Comment by cchadwickk** [comment]
Hi is there some more documentation where I can study what this does, or why it shouldnt be used in production servers ? Also why does enabling ti work...mostly is there some more documentation ?

**Comment by cchadwickk** [comment]
Because I need to run production server and this is the only parameter that enables it to work...., I can ping you the credentials for our webapp and the credentials for the turn server if you share me an email ID.

**Comment by cchadwickk** [comment]
Oh so that means regardless of who allocated the IP(or port) the incoming packet can be connected via any client IP ? That could be an issue since our office internet switches between 2 static (external) IPs. Thank you so much for your replies.

**Comment by misi** [comment]
I think there are no open question so I close it. Please reopen if there is any,

**Comment by kbrmimbyl** [comment]
@cchadwickk I'm facing the exact same one-way problem. Any update on what worked for you? I want to avoid the --server-relay option of possible.

**Comment by cchadwickk** [comment]
Turns out my office IT has setup to alternate between 2 public IP addresses
randomly. So if connection is made by IP 1, turn server won't allow same
connection to be continued by IP 2 unless server-relay is enabled. So that
is definitely required in my case.

**Comment by kbrmimbyl** [comment]
Thanks. I can confirm that enabling --server-relay does work for me. I think I'll move coturn to a dedicated server so that DDoS attackers have nothing much to attack. Right now coturn is running in parallel with a couple more things.
