### ISSUE TITLE
udp send: Message too long

### ISSUE THREAD

**Issue by pjosep** [coturn/coturn#277]
Hi, I am connecting a turn client to the coturn server over TCP, and attempting to communicate to a peer over UDP.  When doing so, I am seeing coturn elicit the following error before killing off my connection to the server.

`udp send: Message too long`

This doesn't seem to be a consistent thing (at least not that I have noticed yet), and I unfortunately don't know what the exact scenario is that causes this to happen.  There are no other logs to indicate what exactly the input that caused this could be. From what I can see, the turn client isn't sending any packets that seem out of the ordinary big. When this happens, it would appear the turn client is actually trying to send the same data multiple times in a row, and either the Peer isn't getting it, or there are no logs to show that it actually got it.  And it is after 3-4 times sending the same data that I get this error message.

Any thoughts on what could cause this?

**Comment by pjosep** [comment]
I currently don't have a consistent way to reproduce this, and thus I don't have much more information.

Better error handling at a minimum would be great. If/when I am able to reproduce this more regularly, I will try and update this ticket with exact details.

Attached is my config for reference though:
[coturn.conf.txt](https://github.com/coturn/coturn/files/2394535/coturn.conf.txt)

**Comment by misi** [comment]
I will try to also test it.

We could only add better error handling, if we know what unhandled error is not handled correctly,  
this way please try to debug that part that I pointed out, and if possible find out what is the exact issue there if possible. The project actually has very limited resources.

To keep clean this issue queue:
I hope you understand that I would be happy to only leave open for long time issues that are exactly reproducible.
What do you think? 
Would you mind if we close this issue if you don't find a way to reproduce it in the next 2 month, and open again a new issue when you find it?
Thanks for your understanding..

**Comment by pjosep** [comment]
Sure thing.

**Comment by eakraly** [comment]
Hi @pjosep!
It took closer to 4 years and not 2 month :)
If you still have an issue - please file a new one!
