### ISSUE TITLE
credentials are incorrect when only config userdb

### ISSUE THREAD

**Issue by yayuntian** [coturn/coturn#279]
## First test

- sqlite

![image](https://user-images.githubusercontent.com/2228382/46064249-7fa1b680-c1a1-11e8-9c10-41e2c8d58aa7.png)

- conf
```
listening-port=15001
listening-ip=192.168.9.217
external-ip=47.92.169.145
#relay-ip=192.168.9.217

min-port=15000
max-port=17000

fingerprint
lt-cred-mech
userdb=/usr/local/var/db/turndb
user=clientdev:cc69ab228a5a00f7af212*******        // comment it
realm=ysten.com

no-tcp
no-loopback-peers
verbose
```

![image](https://user-images.githubusercontent.com/2228382/46064436-f343c380-c1a1-11e8-9ee4-f4a820ee2ab6.png)

============ Boundary line ============

**comment user line**
```
#user=clientdev:cc69ab228a5a00f7af212*******
```

### test turn

then log
```
22: handle_udp_packet: New UDP endpoint: local addr 192.168.9.217:15001, remote addr 221.131.123.204:46891
22: session 001000000000000001: realm <ysten.com> user <>: incoming packet BINDING processed, success
22: handle_udp_packet: New UDP endpoint: local addr 192.168.9.217:15001, remote addr 221.131.123.204:55493
22: session 001000000000000002: realm <ysten.com> user <>: incoming packet BINDING processed, success
22: session 001000000000000002: realm <ysten.com> user <>: incoming packet message processed, error 401: Unauthorized
22: session 001000000000000001: realm <ysten.com> user <>: incoming packet message processed, error 401: Unauthorized
22: ERROR: check_stun_auth: user clientdev credentials are incorrect
22: session 001000000000000001: realm <ysten.com> user <clientdev>: incoming packet message processed, error 401: Unauthorized
22: ERROR: check_stun_auth: user clientdev credentials are incorrect
22: session 001000000000000002: realm <ysten.com> user <clientdev>: incoming packet message processed, error 401: Unauthorized
```
and

![image](https://user-images.githubusercontent.com/2228382/46064695-b4623d80-c1a2-11e8-8e0d-f6e61397e851.png)

### test stun

error log
```
80: handle_udp_packet: New UDP endpoint: local addr 192.168.9.217:15001, remote addr 221.131.123.204:38818
80: session 000000000000000001: realm <ysten.com> user <>: incoming packet BINDING processed, success
80: handle_udp_packet: New UDP endpoint: local addr 192.168.9.217:15001, remote addr 221.131.123.204:48047
80: session 003000000000000001: realm <ysten.com> user <>: incoming packet BINDING processed, success
80: session 000000000000000001: realm <ysten.com> user <>: incoming packet message processed, error 401: Unauthorized
80: session 003000000000000001: realm <ysten.com> user <>: incoming packet message processed, error 401: Unauthorized
80: ERROR: check_stun_auth: user clientdev credentials are incorrect
80: session 000000000000000001: realm <ysten.com> user <clientdev>: incoming packet message processed, error 401: Unauthorized
80: ERROR: check_stun_auth: user clientdev credentials are incorrect
80: session 003000000000000001: realm <ysten.com> user <clientdev>: incoming packet message processed, error 401: Unauthorized
82: session 001000000000000001: closed (2nd stage), user <clientdev> realm <ysten.com> origin <>, local 192.168.9.217:15001, remote 221.131.123.204:46891, reason: allocation watchdog determined stale session state
82: session 001000000000000002: closed (2nd stage), user <clientdev> realm <ysten.com> origin <>, local 192.168.9.217:15001, remote 221.131.123.204:55493, reason: allocation watchdog determined stale session state
```

![image](https://user-images.githubusercontent.com/2228382/46064769-e7a4cc80-c1a2-11e8-8ea5-30d2e9aaa701.png)

## help & question

1、Why not use the sqlite DB record directly when stun/turn  verifying ？
2、Static user and db user difference （persistent_users_db & ram_db） ？

**Comment by misi** [comment]
You mix the HA1 and cleartext password, and this cause your anomaly.
See turnserver.conf 
**Notice the 0x prefix!**
In db we use the HA1 password
```
#user=ninefingers:0xbc807ee29df3c9ffa736523fb2c4e8ee
# Or, equivalently, with open clear password (less secure):
#user=ninefingers:youhavetoberealistic
```
You can create HA1
`echo -n "user:realm:password" | md5sum | cut -d' ' -f1`

**Comment by yayuntian** [comment]
> You mix the HA1 and cleartext password, and this cause your anomaly.
> See turnserver.conf
> **Notice the 0x prefix!**
> In db we use the HA1 password
> 
> ```
> #user=ninefingers:0xbc807ee29df3c9ffa736523fb2c4e8ee
> # Or, equivalently, with open clear password (less secure):
> #user=ninefingers:youhavetoberealistic
> ```
> You can create HA1
> `echo -n "user:realm:password" | md5sum | cut -d' ' -f1`

I understand that the sqlite HA1, can not use the user line in the configuration file, directly use the  sqlite DB

**Comment by misi** [comment]
@yayuntian I didn't understand your last comment. Could you explain it more..

**Comment by yayuntian** [comment]
Can i not use the `user=ninefingers:0xbc807ee29df3c9ffa736523fb2c4e8ee` line?

just run cmd add user, Only use the sqlite DB in the future
```
turnadmin -a -u clientdev -r ysten.com -p ****
```

so， conf simple like
```
listening-port=15001
listening-ip=192.168.9.217
external-ip=47.92.169.145

min-port=15000
max-port=17000

fingerprint
lt-cred-mech
userdb=/usr/local/var/db/turndb
realm=ysten.com
```

**Comment by misi** [comment]
> Can i not use the user=ninefingers:0xbc807ee29df3c9ffa736523fb2c4e8ee line?

You can use password in either clear or encrypted in turnserver.conf configuration.
But be aware if you mix db and config file that  config file will be checked first and has precedence over db.

And turnadmin will not add to config file static credentials.

**Comment by yayuntian** [comment]
I think if only the DB is configured, it should be read from the DB. or config file and the DB should take effect at the same time. but config priority is high. 

I will try to achieve this, what do you think?:-)  @misi

**Comment by misi** [comment]
coTURN designed that way that always config file has precedence over db. 
You can avoid to use any config file credential and this way you avoid any confusion..
