### ISSUE TITLE
Firefox not working for relay

### ISSUE THREAD

**Issue by geigev** [coturn/coturn#280]
I have a coturn server in docker using the Turn REST API and time limited credentials. The command I am using looks like this
```
CMD turnserver -a -n -r turn.mydomain.com \
	--cert=/sslkeys/fullchain.pem \
	--pkey=/sslkeys/privkey.pem \
	--use-auth-secret --static-auth-secret=$TURN_SECRET --max-bps=3000000 --cipher-list=ALL \
	-f -m 3 -q 100 -Q 300 \
	--listening-ip=${myip} --tls-listening-port=443 --listening-port=443
```

This works perfectly in chrome for all types of candidates, including relay. When I force the client to use a turn server using `ice_transport_policy=relay` everything works fine.

When using Firefox, non relay candidates work, but when using `ice_transport_policy=relay` the client cannot connect to the turn. I am having trouble identifying the issue as everything looks fine. The client is able to gather all the relay candidates and the remote SDP looks normal to me:

![rsdp](https://user-images.githubusercontent.com/12450753/46220344-aa555180-c2fe-11e8-8feb-5e26cae7f4e2.png)

If there is any other information that I should provide, please let me know. Any help would be very much appreciated.

Also, I tested using turn providers like xirsys/twilio and it seemed to work fine with firefox.

**Comment by misi** [comment]
@geigev 
Can you also make further traces?
1. what is on FF ice log on page about:webrtc?
2. Please send a fifefox ICE debug log: 
See this for howto 
https://misi.github.io/webrtc-c0d3l4b/#30

**Comment by misi** [comment]
Are you sure that it is not an issue on FF side? Why do you think it is coTURN issue?

**Comment by misi** [comment]
Make a TCP dump I guess you have an authentication issue..

AFAIK you should not use the same port for both of these!!
--tls-listening-port=443 
--listening-port=443

**Comment by geigev** [comment]
@misi thanks, I'll try changing the ports, and make further traces when I get a chance. It could definitely be an issue on the FF side, but I tested with other turn services (not coTURN), and there weren't any issues.

**Comment by misi** [comment]
You have used this two listener with the same port, that fits to the case you have described. Such setting may cause anomalies on coturn side... So You experienced that it is not working with coturn such config, but worked with other TURN service.

I need to reproduce it to be able to investigate, and after it fix. 
Of course if there is any issue on our side. :-)

I tried to reproduce it, but unfortunately I didn't find anything.

So I am still in doubt if it is a coTURN issue or not. :-(

I need at least packet traces, all logs from firefox webrtc engine. (open in new tab "about:webrtc" site). 
And also send me the browser developer / js console logs. + turn server config and logs..

This way I still need your help. Please give me any prove that it is a coTURN issue.
Many thanks for your cooperation..

**Comment by geigev** [comment]
This ended up being an issue with the way I was generating credentials on my end; for some reason it was only affecting firefox. Thanks @misi
