### ISSUE TITLE
Channel messages to peers do not contribute to measured bandwidth.

### ISSUE THREAD

**Issue by AnsonKindred** [coturn/coturn#281]
The write_to_peerchannel method is not adding to sent_bytes or incrementing sent_packets. I assume it should be doing the same thing the write_client_connection method is doing. 

I noticed this when testing to see if the bandwidth I was sending matched up with what CoTurn was measuring. I found that sent_bytes was less than what I was sending over the relay so something had to be wrong.

The numbers seem more correct when I copy the bandwidth reporting code from write_to_peerchannel but I would love some confirmation that that is the right thing to do. Measuring bandwidth correctly is pretty critical to being able to charge customers accordingly.

**Comment by misi** [comment]
AFAIU coTURN is measuing between TURN Client and Server Traffic. 

So not between Peer and TURN server. 

This way I think it shouldn't add sent bytes on write_to_peerchannel.

You measure packets and bytes on TURN client side (or  peer side?) but the Sent Received packets is not match what you see on TURN server side? 
(The peer and TURN Client traffic will not match of course..)
Am I understand your report correctly that you meausred on TURN Client side?
If so, please help me with a detailed data measurement about such issue. 
Thanks..

**Comment by AnsonKindred** [comment]
Ah, I was just mistakenly assuming that sent_bytes was a tally of all the bytes sent, not just the bytes between server and client. I don't suppose there is a way to get the total bytes sent? If I wanted to implement that myself am I on the right track? Also I assume that means the bandwidth limitations don't apply to traffic between the server and peer either?

**Comment by misi** [comment]
Yes it could be added further stats to see client and peer communication, the question is how much overhead/delay it adds to the forwarding.. 
Please send a Pull Request if you will be developed such extended Server <-> Peer stat collection
