### ISSUE TITLE
FR: Support TLSv1.3

### ISSUE THREAD

**Issue by alexara** [coturn/coturn#282]
> For secure TCP connections, we currently support SSL version 3 and TLS versions 1.0, 1.1, 1.2

Since OpenSSL 1.1.1 has been released, providing TLSv1.3, it would be very welcomed if Coturn support it. :)

**Comment by misi** [comment]
Could you send a Pull Request? 
I am busy with other issues.. Thanks..

**Comment by eakraly** [comment]
The goal is to have it as a by-product in #989

**Comment by eakraly** [comment]
Closing this in favor of #630
