### ISSUE TITLE
Client cannot send data in turn  mode with tcp 

### ISSUE THREAD

**Issue by ivanhxq** [coturn/coturn#286]
When peer-to-peer communication uses the turn of the server to use the turn to forward through tcp, there is a problem that one end of the client cannot send data, but the other end can send.

**Comment by misi** [comment]
I am not really see the problem can you give a detailed report. 
With 
* server config, 
* packet capture on 
  * clients and 
  * server side 
Sw versions
etc.

Thanks..

**Comment by ivanhxq** [comment]
> I am not really see the problem can you give a detailed report.
> With
> 
> * server config,
> * packet capture on
>   
>   * clients and
>   * server side
>     Sw versions
>     etc.
> 
> Thanks..

thanks for replying.here is my detail report:
server use default config,just run :./turnserver&

client use pjsip ice demo "icedemo" for test,run as:
./icedemo -s www.mstar-tv.cn -t www.mstar-tv.cn -T

www.mstar-tv.cn is the PC' donain of turnserver 

-t www.mstar-tv.cn -T mean can use turn  tcp as relay 

I test 10 pairs,it is easy to come out this problem.

I will collect more detail log when this problem  recurrence later.

**Comment by misi** [comment]
I need packet capture to see what happens on the wire..

**Comment by misi** [comment]
@ivanhxq I tested with pjproject2.8 icedemo 
and server allocated relay candidate successfully and sent data on -T tcp

**Comment by ggarber** [comment]
assuming this is already solved or not relevant, reopen if that's not the case.  Thank you!
