### ISSUE TITLE
Problem with proc-user and proc-group on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by cron0mat** [coturn/coturn#287]
I am running coTURN server on a VPS with public IP. 
I use it for NextCloud Talk and it works just fine.

Function is breaking if I enable **proc-user and proc-group** in the settings (both set to **turnserver**).
Video and audio chat doesn't work any more in that case.

Log file says that switching user and group is done and I don't get further logging in that file (owned by root) - I am wondering why the turnserver doesn't open another logfile, owned by the new user.

My system is Ubuntu 18.04 LTS and coTURN Version is 4.5.0.7-1ubuntu2 (from Ubuntu repos).

Here are my settings (just the active lines, xxx set to mask sensitive data) :

> tls-listening-port=5349
listening-ip=xxx.xxx.xxx.xxx
relay-ip=xxx.xxx.xxx.xxx
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
realm=turn.mydomain.net
total-quota=100
bps-capacity=0
stale-nonce=600
cert=/etc/letsencrypt/live/turn.mydomain.net/fullchain.pem
pkey=/etc/letsencrypt/live/turn.mydomain.net/privkey.pem
cipherlist="ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AES:RSA+3DES:!ADH:!AECDH:!MD5"
**proc-user=turnserver**
**proc-group=turnserver**
no-loopback-peers
no-multicast-peers
dh-file=/etc/turn/dhparams.pem
no-tlsv1
no-tlsv1_1

**Comment by misi** [comment]
Have you tried to use with syslog instead of file logging?

**Comment by cron0mat** [comment]
Good hint !
With active **syslog** I can use **proc-user** and **proc-group** without any problems !

Could you add some comments to the turnserver.conf to use this parameter together ?
