### ISSUE TITLE
100% CPU utilisation 

### ISSUE THREAD

**Issue by sergey-safarov** [coturn/coturn#29]
Coturn daemon cannot work on host with one core in one CPU.
But corectly starts on host with two cores in one CPU.

**Comment by sergey-safarov** [comment]
I can provide access to test box with one core if it  will help.

**Comment by mom040267** [comment]
I tested it on a Linux with all three network engine options and I cannot reproduce it.
Please send the system access info to mom040267@gmail.com. One possible problem is that the runtime system and the compilation system are very different in regard to the kernel version and to the available libraries.

**Comment by sergey-safarov** [comment]
Issue reproduced on host with commit a49355e072901efed1e50601f3a21229a8d9db3f
Systemd according "CPUSchedulingPolicy=fifo" set process sheduling to fifo
And program call contiguously make system call 'sched_yield"

Part of log
sendto(3, "<14>Nov 17 16:23:23 turnserver: "..., 93, MSG_NOSIGNAL, NULL, 0) = 93
sendto(3, "<14>Nov 17 16:23:23 turnserver: "..., 74, MSG_NOSIGNAL, NULL, 0) = 74
sendto(3, "<14>Nov 17 16:23:23 turnserver: "..., 73, MSG_NOSIGNAL, NULL, 0) = 73
sendto(3, "<14>Nov 17 16:23:23 turnserver: "..., 75, MSG_NOSIGNAL, NULL, 0) = 75
sendto(3, "<14>Nov 17 16:23:23 turnserver: "..., 65, MSG_NOSIGNAL, NULL, 0) = 65
sendto(3, "<14>Nov 17 16:23:23 turnserver: "..., 67, MSG_NOSIGNAL, NULL, 0) = 67
sendto(3, "<14>Nov 17 16:23:23 turnserver: "..., 67, MSG_NOSIGNAL, NULL, 0) = 67
mmap(NULL, 2101248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f71cecb1000
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f71ce4b0000
mprotect(0x7f71ce4b0000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f71cecafeb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f71cecb09d0, tls=0x7f71cecb0700, child_tidptr=0x7f71cecb09d0) = 2283
mmap(NULL, 2101248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f71ce2af000
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f71cdaae000
mprotect(0x7f71cdaae000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f71ce2adeb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f71ce2ae9d0, tls=0x7f71ce2ae700, child_tidptr=0x7f71ce2ae9d0) = 2284
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0

**Comment by mom040267** [comment]
Are you using real-time scheduler ? This program was not meant to be used as a real-time program. Too many parallel activities to manage. The only supported scheduler is "other". I just noticed that you introduced that "fifo" in the systemd; I'll have to revert it.
