### ISSUE TITLE
INSTALL ON WINDOWS

### ISSUE THREAD

**Issue by ph4t0o0o0om** [coturn/coturn#290]
Is it possible to install this server on windows machine?

**Comment by misi** [comment]
I never did it. But AFAIH it should work. 
Try it in cygwin.. 
So it should work, but I suggest to choose a different OS for production evnironment.

**Comment by misi** [comment]
I don't think we could add here more. Please open new issue if we could help you more..

**Comment by ph4t0o0o0om** [comment]
What OS you prefer to install co turn? Please help

**Comment by misi** [comment]
I think Linux and BSD is the preferred platform.
