### ISSUE TITLE
session allocation timeout?

### ISSUE THREAD

**Issue by duchuan1** [coturn/coturn#293]
I run it in Cygwin and I meeting follow error, could somebody can help me?

- CommandLine
`turnserver.exe --listening-port=3478 --tls-listening-port=5349 --lt-cred-mech --user=test:test1 --userdb=turndb --mobility --no-cli --pkey=turn_server_pkey.pem --cert=turn_server_cert.pem --fingerprint  --verbose`

- Test Environmet:
    https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ 

- Error Message
1.  the  user is empty in first, so it has error Unauthorized
 : handle_udp_packet: New UDP endpoint: local addr 192.168.0.102:3478, remote addr 192.168.0.102:59995
3: session 136000000000000001: realm <> user <>: incoming packet message processed, error 401: Unauthorized

2. allocation timeout
 session 136000000000000002: closed (2nd stage), user <test> realm <> origin <>, local 192.168.0.102:3478, remote 192.168.0.102:59996, reason: **allocation timeout**

[fullErrorMessage.txt](https://github.com/coturn/coturn/files/2512965/fullErrorMessage.txt)

**Comment by duchuan1** [comment]
![image](https://user-images.githubusercontent.com/17233516/47471564-6beb7d80-d83d-11e8-971a-5957ab93eded.png)

```
: handle_udp_packet: New UDP endpoint: local addr 192.168.0.102:3478, remote addr 192.168.0.102:59995
3: session 136000000000000001: realm <> user <>: incoming packet message processed, error 401: Unauthorized
3: IPv4. Local relay addr: 192.168.0.102:54850
3: session 136000000000000001: new, realm=<>, username=<test>, lifetime=3600
3: session 136000000000000001: realm <> user <test>: incoming packet ALLOCATE processed, success
3: handle_udp_packet: New UDP endpoint: local addr 192.168.0.102:3478, remote addr 192.168.0.102:59996
3: session 136000000000000002: realm <> user <>: incoming packet message processed, error 401: Unauthorized
3: IPv4. Local relay addr: 192.168.0.102:52529
3: session 136000000000000002: new, realm=<>, username=<test>, lifetime=3600
3: session 136000000000000002: realm <> user <test>: incoming packet ALLOCATE processed, success
3: session 136000000000000001: refreshed, realm=<>, username=<test>, lifetime=0
3: session 136000000000000001: realm <> user <test>: incoming packet REFRESH processed, success
3: session 136000000000000002: refreshed, realm=<>, username=<test>, lifetime=0
3: session 136000000000000002: realm <> user <test>: incoming packet REFRESH processed, success
4: session 136000000000000001: usage: realm=<>, username=<test>, rp=3, rb=236, sp=3, sb=312
4: session 136000000000000001: closed (2nd stage), user <test> realm <> origin <>, local 192.168.0.102:3478, remote 192.168.0.102:59995, reason: allocation timeout
4: session 136000000000000001: delete: realm=<>, username=<test>
4: session 136000000000000002: usage: realm=<>, username=<test>, rp=3, rb=236, sp=3, sb=312
4: session 136000000000000002: closed (2nd stage), user <test> realm <> origin <>, local 192.168.0.102:3478, remote 192.168.0.102:59996, reason: allocation timeout
4: session 136000000000000002: delete: realm=<>, username=<test>
```

**Comment by misi** [comment]
@duchuan1 
I think it is feature.

**Comment by misi** [comment]
It express that your allocation is refreshed with lifetime 0 and closing the 2nd stage is happened due this reason..
I agree that may "allocation timeout" is not perfectly express it.

If you are not happy with it please send a PR..

**Comment by duchuan1** [comment]
It's ok
thanks

**Comment by marksalpeter** [comment]
Im having the same problem. @duchuan1 were you ever able to solve this issue?
