### ISSUE TITLE
Authentication in coturn with Kamailio user database - possible?

### ISSUE THREAD

**Issue by daviddean99** [coturn/coturn#296]
I'm using coturn alongside Kamailio. Works great!

Now I would like to enable authentication in coturn and re-use the credentials already in Kamailio.

I don't want to have to maintain two sets of credentials in different databases.

What's the best way of using the Kamailio user database for authentication in coturn?

Thanks.

**Comment by misi** [comment]
Kamailio database access configuration is much more felxible than coTURN's, so try to setup a table that is based on coturn ltc_cred table exended with kamailio subscriber extra fields ..
