### ISSUE TITLE
68: session 007000000000000001: realm user <>: incoming packet message processed, error 401: Unauthorized

### ISSUE THREAD

**Issue by gdudas** [coturn/coturn#297]
Hi,

we use Coturn 4.5.0.7 with Nextcloud 14.0.3, we have some "Unauthorized" entries in coturn logs:
68: session 007000000000000001: realm user <>: incoming packet message processed, error 401: Unauthorized

The STATIC_AUTH_SECRET is correct in Nextcloud Talk settings. What's wrong, and why we have these entries?

Thank you!

**Comment by misi** [comment]
If every second time auth was successful, and you don't have any issues, then it is not a problem it is how digest auth works, don't care about it.
See: https://www.ietf.org/proceedings/87/slides/slides-87-behave-10.pdf

**Comment by mokkin** [comment]
We have the same entries and problems with screensharing with nextcloud Talk too. I already connected to an existing ticket in the nextcloud forum:
https://help.nextcloud.com/t/screensharing-doesnt-work-properly-nextcloud-talk-turnserver/52121/2?u=mokkin
Do you have any idea if these `incoming packet message processed, error 401: Unauthorized` entries could be the problem?

**Comment by misi** [comment]
@mokkin I commented the mentioned nextcloud issue..

**Comment by ancin** [comment]
I have the same problem. Do you have any idea? this authorize from config file or DB table?
I configed the user and pswd,like this pattern user11:paswd..

Thanks.
