### ISSUE TITLE
Reporting vulnerabilities in coturn

### ISSUE THREAD

**Issue by iarce-qb** [coturn/coturn#301]
Hello,
Is there a standard way of reporting vulnerabilities in coturn, such as an email address to send the report to, or should I open issues here ?
Regards,
/ivan
Quarkslab Vulnerability Reports team

**Comment by misi** [comment]
Please send the vulnerabilty or fix direct to me + cc Oleg. My email is
misi@majd.eu Thanks!

2018. nov. 6., Ke 19:03 dátummal iarce-qb <notifications@github.com> ezt
írta:

**Comment by misi** [comment]
Can you please share your finding before end of this week..
I am working actually on other security fixes and if possible I want to check if it is a duplicate or not. And if it could be fixed easily then include the fix for your finding too in our next release..

Thanks!

**Comment by misi** [comment]
@iarce-qb  Many thanks for your cooperation!

**Comment by misi** [comment]
@iarce-qb Unfortunately I still didn't received your report yet Can you please send it?

**Comment by misi** [comment]
Unfortunately I still not got it.. :(

**Comment by iarce-qb** [comment]
I am sorry, I sent the report to the wrong email and it bounced but I did not realize until today that I checked my "junk" folder. I just resent it.

**Comment by misi** [comment]
Many Thanks..
I will release it soon..
