### ISSUE TITLE
UDP not in within 49152 - 65535 range

### ISSUE THREAD

**Issue by lc2a** [coturn/coturn#302]
**/etc/turnserver.conf**
```
listening-port=3478
min-port=49152
max-port=65535
fingerprint
lt-cred-mech
user=kurento:0xde622176c6cb42c121d8c268c33d4afb
realm=kurento.org
```

**1) remote addr 10.23.34.4:12320**

`1385: handle_udp_packet: New UDP endpoint: local addr 10.23.34.4:3478, ### remote addr 10.23.34.4:12320
1385: session 001000000000000022: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1385: handle_udp_packet: New UDP endpoint: local addr 10.23.34.4:3478, remote addr 10.23.34.4:5446
1385: session 000000000000000043: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1385: IPv4. Local relay addr: 10.23.34.4:61186
1385: session 001000000000000022: new, realm=<kurento.org>, username=<kurento>, lifetime=600
1385: session 001000000000000022: realm <kurento.org> user <kurento>: incoming packet ALLOCATE processed, success
1386: session 001000000000000022: peer 192.168.1.52 lifetime updated: 300
1386: session 001000000000000022: realm <kurento.org> user <kurento>: incoming packet CREATE_PERMISSION processed, success
1386: session 001000000000000022: peer 192.168.1.52 lifetime updated: 300
1386: session 001000000000000022: realm <kurento.org> user <kurento>: incoming packet CREATE_PERMISSION processed, success
1386: session 000000000000000043: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1386: session 001000000000000022: peer 175.156.158.145 lifetime updated: 300
1386: session 001000000000000022: realm <kurento.org> user <kurento>: incoming packet CREATE_PERMISSION processed, success
1386: session 000000000000000042: closed (2nd stage), user <kurento> realm <kurento.org> origin <>, local 10.23.34.4:3478, remote 10.23.34.4:17154, reason: allocation timeout
1386: session 000000000000000042: delete: realm=<kurento.org>, username=<kurento>
1386: session 000000000000000042: peer 192.168.1.52 deleted
1386: session 000000000000000042: peer 175.156.158.145 deleted
1386: session 000000000000000043: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1387: session 000000000000000043: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1388: session 000000000000000043: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1390: session 001000000000000022: refreshed, realm=<kurento.org>, username=<kurento>, lifetime=0
1390: session 001000000000000022: realm <kurento.org> user <kurento>: incoming packet REFRESH processed, success
1390: session 001000000000000022: refreshed, realm=<kurento.org>, username=<kurento>, lifetime=0
1390: session 001000000000000022: realm <kurento.org> user <kurento>: incoming packet REFRESH processed, success
`

2. **remote addr 10.23.34.4:34817**

`1391: handle_udp_packet: New UDP endpoint: local addr 10.23.34.4:3478, **remote addr 10.23.34.4:34817**
1391: session 001000000000000023: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1391: handle_udp_packet: New UDP endpoint: local addr 10.23.34.4:3478, remote addr 10.23.34.4:45674
1391: session 000000000000000044: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1391: IPv4. Local relay addr: 10.23.34.4:55546
1391: session 001000000000000023: new, realm=<kurento.org>, username=<kurento>, lifetime=600
1391: session 001000000000000023: realm <kurento.org> user <kurento>: incoming packet ALLOCATE processed, success
1391: session 001000000000000023: peer 192.168.1.52 lifetime updated: 300
1391: session 001000000000000023: realm <kurento.org> user <kurento>: incoming packet CREATE_PERMISSION processed, success
1391: session 001000000000000023: peer 192.168.1.52 lifetime updated: 300
1391: session 001000000000000023: realm <kurento.org> user <kurento>: incoming packet CREATE_PERMISSION processed, success
1391: session 000000000000000044: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1391: session 001000000000000023: peer 175.156.158.145 lifetime updated: 300
1391: session 001000000000000023: realm <kurento.org> user <kurento>: incoming packet CREATE_PERMISSION processed, success
1391: session 001000000000000022: closed (2nd stage), user <kurento> realm <kurento.org> origin <>, local 10.23.34.4:3478, remote 10.23.34.4:12320, reason: allocation timeout
1391: session 001000000000000022: delete: realm=<kurento.org>, username=<kurento>
1391: session 001000000000000022: peer 192.168.1.52 deleted
1391: session 001000000000000022: peer 175.156.158.145 deleted
1392: session 000000000000000044: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1392: session 000000000000000044: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1393: session 001000000000000023: refreshed, realm=<kurento.org>, username=<kurento>, lifetime=0
1393: session 001000000000000023: realm <kurento.org> user <kurento>: incoming packet REFRESH processed, success
1393: session 001000000000000023: refreshed, realm=<kurento.org>, username=<kurento>, lifetime=0
1393: session 001000000000000023: realm <kurento.org> user <kurento>: incoming packet REFRESH processed, success
`

3. **remote addr 10.23.34.4:63101**    Finally got port within 49152 - 65535 range.

`1394: handle_udp_packet: New UDP endpoint: local addr 10.23.34.4:3478, **remote addr 10.23.34.4:63101**
1394: session 000000000000000045: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1394: handle_udp_packet: New UDP endpoint: local addr 10.23.34.4:3478, remote addr 10.23.34.4:31689
1394: session 000000000000000046: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1394: IPv4. Local relay addr: 10.23.34.4:52681
1394: session 000000000000000045: new, realm=<kurento.org>, username=<kurento>, lifetime=600
1394: session 000000000000000045: realm <kurento.org> user <kurento>: incoming packet ALLOCATE processed, success
1394: session 000000000000000045: peer 192.168.1.52 lifetime updated: 300
1394: session 000000000000000045: realm <kurento.org> user <kurento>: incoming packet CREATE_PERMISSION processed, success
1394: session 000000000000000045: peer 192.168.1.52 lifetime updated: 300
1394: session 000000000000000045: realm <kurento.org> user <kurento>: incoming packet CREATE_PERMISSION processed, success
1394: session 000000000000000046: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1394: session 001000000000000023: closed (2nd stage), user <kurento> realm <kurento.org> origin <>, local 10.23.34.4:3478, remote 10.23.34.4:34817, reason: allocation timeout
1394: session 001000000000000023: delete: realm=<kurento.org>, username=<kurento>
1394: session 001000000000000023: peer 192.168.1.52 deleted
1394: session 001000000000000023: peer 175.156.158.145 deleted
1394: session 000000000000000046: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1395: session 000000000000000046: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1397: session 000000000000000046: realm <kurento.org> user <>: incoming packet message processed, error 401: Unauthorized
1397: session 000000000000000045: refreshed, realm=<kurento.org>, username=<kurento>, lifetime=0
1397: session 000000000000000045: realm <kurento.org> user <kurento>: incoming packet REFRESH processed, success
1397: session 000000000000000045: refreshed, realm=<kurento.org>, username=<kurento>, lifetime=0
1397: session 000000000000000045: realm <kurento.org> user <kurento>: incoming packet REFRESH processed, success
1398: session 000000000000000045: closed (2nd stage), user <kurento> realm <kurento.org> origin <>, local 10.23.34.4:3478, remote 10.23.34.4:63101, reason: allocation timeout
1398: session 000000000000000045: delete: realm=<kurento.org>, username=<kurento>
1398: session 000000000000000045: peer 192.168.1.52 deleted
`

I would like to get the UDP port in defined range

**Comment by misi** [comment]
Which coturn version have you used?

2018. nov. 7., Sze 16:58 dátummal lc2a <notifications@github.com> ezt írta:

**Comment by lc2a** [comment]
Solved by added IceServer at Client side as well.

Thanks
