### ISSUE TITLE
certificate issue in coturn server

### ISSUE THREAD

**Issue by anaspa** [coturn/coturn#310]
We have configured a coturn server. The server log is shown below

RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.2.1.2 'Monza'
0: 
Max number of open files/sockets allowed for this process: 65536
0: 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 32500 (approximately)
0: 

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: AEAD supported
0: Redis supported
0: PostgreSQL supported
0: MySQL supported
0: MongoDB is not supported
0: OpenSSL compile-time version 0x1000105f: fresh enough
0: Default Net Engine version: 2 (UDP thread per network endpoint)

=====================================================

0: Config file found: /root/../etc/turnserver.conf
0: Listener address to use: 10.132.0.2
0: Relay address to use: 10.132.0.2
0: Config file found: /root/../etc/turnserver.conf
0: Domain name: 
0: Default realm: <realm>
0: oAuth server name: <server name>
0: Config file found: /root/../etc/turnuserdb.conf
0: SSL23: Certificate file found: /root/envirnments/development/api_server/cert/certificate.pem
0: SSL23: Private key file found: /root/envirnments/development/api_server/cert/private.pem
0: TLS1.0: Certificate file found: /root/envirnments/development/api_server/cert/certificate.pem
0: TLS1.0: Private key file found: /root/envirnments/development/api_server/cert/private.pem
0: TLS1.1: Certificate file found: /root/envirnments/development/api_server/cert/certificate.pem
0: TLS1.1: Private key file found: /root/envirnments/development/api_server/cert/private.pem
0: TLS1.2: Certificate file found: /root/envirnments/development/api_server/cert/certificate.pem
0: TLS1.2: Private key file found: /root/envirnments/development/api_server/cert/private.pem
0: TLS cipher suite: DEFAULT
0: DTLS: Certificate file found: /root/envirnments/development/api_server/cert/certificate.pem
0: DTLS: Private key file found: /root/envirnments/development/api_server/cert/private.pem
0: DTLS cipher suite: DEFAULT
0: pid file created: /var/run/turnserver.pid
0: IO method (main listener thread): epoll (with changelist)
0: WARNING: I cannot support STUN CHANGE_REQUEST functionality because only one IP address is provided
0: Wait for relay ports initialization...
0:   relay 10.132.0.2 initialization...
0:   relay 10.132.0.2 initialization done
0: Relay ports initialization done
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=0 created
0: IO method (udp listener/relay thread): epoll (with changelist)
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=1 created
0: turn server id=128 created
0: IO method (udp listener/relay thread): epoll (with changelist)
0: turn server id=129 created
0: IPv4. UDP/DTLS listener opened on: 10.132.0.2:3478
0: IPv4. UDP/DTLS listener opened on: 10.132.0.2:5349
0: IPv4. TCP/TLS listener opened on : 10.132.0.2:3478
0: IPv4. TCP/TLS listener opened on : 10.132.0.2:5349
0: Total UDP servers: 2
0: Total General servers: 2
0: IO method (auth thread): epoll (with changelist)
0: IO method (cli thread): epoll (with changelist)
0: IPv4. CLI listener opened on : 127.0.0.1:5766

We are using original certificates(not self-signed) for running the server. But we got an issue when running the following command

openssl s_client -connect <domain name>:3478 | openssl x509 -noout -subject -issuer

depth=0 OU = Domain Control Validated, OU = PositiveSSL, CN = <domain name>
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL, CN = <domain name>
verify error:num=21:unable to verify the first certificate
verify return:1
subject= /OU=Domain Control Validated/OU=PositiveSSL/CN=<domain name>
issuer= /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA

How could we solve it? Due to this issue, we can't proceed with it?
Please help us.
@misi

**Comment by misi** [comment]
What is your result with turnutils_uclient?
See the shell scripts in the examples/scripts/

**Comment by anaspa** [comment]
After adding the transport type, this issue resolved. We have another issue, will raise as seperate
