### ISSUE TITLE
Stream clarity issue

### ISSUE THREAD

**Issue by anaspa** [coturn/coturn#312]
We have used the coturn turn server for our WebRTC application. When we using the coturn turn server frame loss and frame distortion is happening in peer end.
Our stream resolution is 1280x720 30FPS.
@misi

**Comment by misi** [comment]
This could cause many many things. It can not only be  a turn server issue. Please narrow down it to a turn issue, (if there is any) and open a new case with detailed information. 
I couldn't help with only so few info..

Check webrtc stats, turn server location etc.

**Comment by anaspa** [comment]
VM configuration of turn server installed:
2 core machine
4 GB RAM
the result of a speed test is given below
Retrieving speedtest.net configuration...
Testing from Google Cloud (X.X.X.X)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by FSIT AG (Dietikon) [53.77 km]: 21.757 ms
Testing download speed................................................................................
Download: 529.65 Mbit/s
Testing upload speed................................................................................................
Upload: 537.50 Mbit/s
These are the system information.

Which of the webrtc stats info are needed?

**Comment by misi** [comment]
e.g. During the call see the browser webrtc stats:
**Firefox:**
`about:webrtc`
**Chrome:**
`chrome://webrtc-internals`

**Comment by misi** [comment]
But only report it if you narrowed down to turn issue.
Unfortunately I don't have time to help you more..
