### ISSUE TITLE
IPv6 Setup

### ISSUE THREAD

**Issue by aylesm** [coturn/coturn#315]
Hi,

I'm trying to get my turn server working on an IPv6 network.  I am using PJSIP to connect to STUN/TURN.  STUN appears to work correctly, TURN works for IPv4.  When I switch to IPv6 I get a timeout on the client and the following in the coturn logs.

Dec 10 18:10:51 ip-10-0-18-152 turnserver: 354097: session 001000000000000098: realm <REALM_TAG> user <>: incoming packet OLD STUN message processed, error 420: Unknown attribute: TURN server was configured without RFC 5780 support

I am running the latest coturn server.  Using PJSIP 2.8 client.

My conf is:

```
external-ip=<SERVER_IP>
tls-listening-port=443
lt-cred-mech
use-auth-secret
static-auth-secret=AUTH_SECRET
realm=REALM_TAG
syslog
mobility
no-sslv2
no-sslv3
```

Any pointers would be gratefully received.

**Comment by misi** [comment]
Can you please send a packet capture?
THX!

**Comment by cruizba** [comment]
Is it actually possible to use in  `external-ip` an IPv6? Just curious @misi

**Comment by ggarber** [comment]
Yes, it is supported.  You can see at an example in the docker configuration README with the --ipv6 flag: https://hub.docker.com/r/coturn/coturn
