### ISSUE TITLE
turnserver runs as root on Ubuntu 16.04

### ISSUE THREAD

**Issue by Dantali0n** [coturn/coturn#316]
Coturn version: 4.5.0.3
Distro: Ubuntu 16.04 server X64

The -u and -g options aren't passed onto start-stop-daemon causing the turnserver to run as root on Ubuntu 16.04.

[init.d-script.sh.txt](https://github.com/coturn/coturn/files/2689931/init.d-script.sh.txt)

Please see line 51 & 53 of the init.d script that I got after installing this package.

**Comment by misi** [comment]
We changed it in version 4.5.0.8.
https://packages.debian.org/sid/coturn
