### ISSUE TITLE
cannot bind to lower ports

### ISSUE THREAD

**Issue by pdarcos** [coturn/coturn#318]
Hi,

Just installed 4.5.0.8 on Debian Stretch and noticed that it fails to bind to lower ports like 443, but if I don't set tls-listening-port to 443 and leave it commented out it binds fine to 5349.

This is a fresh install of Debian and I'm certain there's nothing already bound to 443. In fact I've tried changing tls-listening-port  to 444 and other values and it only binds when I give a large port number.

This leads me to believe there's a permission issue that's preventing latest coturn from binding to lower ports (at least on Debian Stretch)

**Comment by pdarcos** [comment]
Just confirmed my suspicion it is a permissions problem by running the same config file by using the command line with sudo instead of systemctl and it binds fine to 443.

**Comment by misi** [comment]
Many thanks for the report.
I will check it..

Misi

2018. dec. 28., Pén 19:17 dátummal Darcos <notifications@github.com> ezt
írta:

**Comment by misi** [comment]
Hi,

It is feature not bug :)

Try to add systemd coturn script in [service] section the following line if
you want to listen on low ports:

AmbientCapabilities=CAP_NET_BIND_SERVICE

Second alternative solution (my prefered one) is a port redirection in
netfilter/iptables from port 443 to STUN/TURN port.

Misi

2018. dec. 28., Pén 19:17 dátummal Darcos <notifications@github.com> ezt
írta:

**Comment by pdarcos** [comment]
Thanks for confirming @misi
