### ISSUE TITLE
CoTURN at system startup (CentOS 7.x and AWS)

### ISSUE THREAD

**Issue by Chandramouli-P** [coturn/coturn#319]
Hello,

I installed and configured STUN/TURN (CoTurn) server successfully on CentOS 7.x in AWS EC2 environment. Please find my below queries:

1) How to start "turnserver" at system startup like "sudo systemctl enable turnserver"?
2) I am unable to start "turnserver" as daemon. If I execute the "turnserver -o" command, simply it is terminating and not running. But, If I execute the "nohup turnserver &" command, it is working fine. Is it the right way?
3) Relay IP is the private IP address? As I said, I installed CoTurn on Amazon EC2. Which one is the correction configuration in turnserver.conf file:
Option 1: 
	external-ip=Public IP address/Private IP address
(OR)
Option 2: 
	external-ip=Public IP address
	relay-ip=Private IP address
4) What is "server-name" field in turnserver.conf file? Can I give any name to "server-name" field?
5) What is "realm" field in turnserver.conf? Should I give my AWS EC2 hostname (FQDN) to "realm" field? (OR) Can I give any name to "realm" field? If so, Do I need to give public FQDN or private FQDN?

Any help would be appreciated.

Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Any update would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by misi** [comment]
@Chandramouli-P 
1. 
See https://github.com/coturn/coturn/blob/debian/master/debian/coturn.service
2.
It is running as a daemon. Please read more about how daemons work.
3.
I don't know your EC setup. 
If your host has private IP than I guess you are behind a load balancer.
I think Option2 should work for you. (I guess option1 should work too..)
4. https://github.com/coturn/coturn/blob/master/README.turnserver#L424
5. Whatever string you like. Normally it match with your domain name.

**Comment by misi** [comment]
Didn't I do already?
See:

> 2. It is running as a daemon. Please read more about how daemons work.
> 3. I don't know your EC setup.
> If your host has private IP than I guess you are behind a load balancer.
> I think Option2 should work for you. (I guess option1 should work too..)
> 4. https://github.com/coturn/coturn/blob/master/README.turnserver#L424
> 5. Whatever string you like. Normally it match with your domain name.

**Comment by misi** [comment]
If I still feel that I did not answered your question the then please try to rephrase it...

**Comment by Chandramouli-P** [comment]
Hello Mészáros Mihály,

I am sorry and haven't noticed. I am clear with my queries in this thread.

Thank you.

Best Regards,
Chandramouli.

**Comment by baptx** [comment]
@misi the file https://github.com/coturn/coturn/blob/debian/master/debian/coturn.service does not work on CentOS, the daemon -o fails with SystemD (like @Chandramouli-P mentionned).
Here is a working SystemD service file that I got working on CentOS:
```
[Unit]
Description=coturn
After=network-online.target

[Service]
ExecStart=/usr/local/bin/turnserver
Restart=always
User=root
Group=root
Environment=PATH=/usr/bin:/usr/local/bin
Environment=NODE_ENV=production
WorkingDirectory=/var/nodejs/websocket

[Install]
WantedBy=multi-user.target
```
By the way, the Debian package starts coturn as root (not with a "turnserver" user like in your file), is it normal? Is it necessary to run the STUN / TURN server as root?
On CentOS, I run it as root also, otherwise there is an error: `Cannot create pid file: /var/run/turnserver.pid: Permission denied`.
