### ISSUE TITLE
Cannot access Rest API endpoint

### ISSUE THREAD

**Issue by ic5y** [coturn/coturn#32]
Installed the server, configured, enabled the RestAPI mode but when I open the server-ip:3478 only the management interface opens. I deleted the admin user because I read that the management interface only shows when there is an admin in admin_user table.

If I made a user from admin page, then user turnutils_uclient then the test run successfully, so I can connect to my server, only the endpoint is not working or something :(

**Comment by mom040267** [comment]
There is no REST API http endpoint in coturn. The documentation never says
that it has. Read the related topics in the forum and in the wiki.

**Comment by ic5y** [comment]
then how can I use the rest api actually? I should send a GET to server-ip:3478/?service=turn&username=<username> then I should get the response, shouldnt I?

**Comment by mom040267** [comment]
No. Read the forum and the wiki.
