### ISSUE TITLE
Possible to send custom message?

### ISSUE THREAD

**Issue by vince-lynch** [coturn/coturn#321]
Hey, Rather than the default response I would like to either change the string or add my own.
Is this possible?

**Comment by misi** [comment]
I don't understand your question.
Can you please rephrase it? Thanks..

**Comment by eakraly** [comment]
Hi @vince-lynch 
Looks like you are trying to implement some custom version of turnserver
Of course you can do that customizing turnserver code (changing outgoing STUN and TURN messages)

It does not look like a feature that we could develop or support, though
