### ISSUE TITLE
How do you deploy coturn as a relay service?

### ISSUE THREAD

**Issue by garrylea** [coturn/coturn#322]
firstly, I want deploy coturn as a relay service, the turnserver.conf is 

===================
listening-ip=172.17.49.199 #the internal ip
listening-port=3478

relay-ip=172.17.49.199

external-ip=xxx.xxx.xxx.xxx #the public ip 

min-port=49152
max-port=65535

Verbose

fingerprint

user=garrylea:111111
realm=xxx.xxx.xxx.xxx # the public ip

cert=/usr/local/coturn/etc/turn_server_cert.pem
pkey=/usr/local/coturn/etc/turn_server_pkey.pem
no-stun
===============================

note: I use aliyun ecs virtual machine. 

then, I start turn server by "turnserver -v turnserver.conf"

when I test it by https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/, I don't get the relay.

why? I don't konw where is the error? How do I deploy the coturn as a relay server?

**Comment by misi** [comment]
Try 
turnserver -c turnserver.conf

**Comment by eakraly** [comment]
Hi @garrylea 
This issue is 3 years old
If you still have an issue running turnserver please open a new one
