### ISSUE TITLE
Bad HTTP headers sent by management interface when admin users are not defined

### ISSUE THREAD

**Issue by gribunin** [coturn/coturn#329]
When admin users are not defined, the HTTPs management interface sends the text "To use the HTTPS admin connection, you have to set the database table admin_user with the admin user accounts." and adds the header "Connection: close". But "\r\n" symbols are missed after "Connection: close" so it gets concatenated with the next header (which is "Content-Type...") resulting in the following HTTP headers:

Connection: closeContentType: text/html; charset=UTF-8
Content-Length: [content length]

**Comment by gribunin** [comment]
Pull request #330 has been created

**Comment by misi** [comment]
Merged Thanks!
