### ISSUE TITLE
Is there a way to use short-term crendentials ?

### ISSUE THREAD

**Issue by Neilpang** [coturn/coturn#334]
I'm using turnserver.
Can I use short-term crendentials ?

I found this issue: https://github.com/coturn/coturn/issues/138

It seems that the short-term is removed, but is there a reason ?

Thanks very much .

**Comment by misi** [comment]
No! Because of.lack of reply protection..
It is only for ICE.

Misi

2019. jan. 22., Ke 16:34 dátummal neil <notifications@github.com> ezt írta:

**Comment by Neilpang** [comment]
thanks.
