### ISSUE TITLE
Debian instructions need update

### ISSUE THREAD

**Issue by David-dp-** [coturn/coturn#336]
I'll list a few related issues...

1) The installation instructions https://github.com/coturn/coturn/blob/master/INSTALL advise downloading package from http://packages.qa.debian.org/r/coturn.html and that page in turn references https://packages.debian.org/source/stable/coturn The packages available there begin with "coturn", not "turnserver"; for example: http://deb.debian.org/debian/pool/main/c/coturn/coturn_4.5.0.5.orig.tar.gz

2) Once the tar.gz is downloaded to a Debian8 machine, and one follows the INSTALL after unpacking, it says to do: sudo gdebi coturn*.deb But this file isn't present after unpacking. This problem was previously reported here in https://github.com/coturn/coturn/issues/25 but it was closed without fixing the documentation problem.

3) The accepted solution in issue 25 was to download a package from https://packages.debian.org/sid/amd64/coturn/download for example, http://ftp.us.debian.org/debian/pool/main/c/coturn/coturn_4.5.0.8-1_amd64.deb However, re-running: sudo gdebi coturn*.deb fails: Dependency is not satisfiable: libevent-core-2.1-6 (>= 2.1.8-stable)

4) If one tries to follow https://github.com/coturn/coturn/blob/master/INSTALL about building the unpacked tar.gz the first step fails: ./configure
ginstall: not found
install is /usr/bin/install
pkill is /usr/bin/pkill
sqlite3: not found
sqlite: not found
Use TMP dir /var/tmp
Compiler: unknown
ERROR: cannot use compiler unknown properly

My only thought of a work-around is to try Ubuntu instead of Debian.

**Comment by misi** [comment]
Use the official debian package ...
Just 
```apt install coturn```

Or rebuild form debian source package

**Comment by lininn** [comment]
yum install gcc gcc-c++
