### ISSUE TITLE
Bad configuration format: psql-userdb

### ISSUE THREAD

**Issue by fitraditya** [coturn/coturn#34]
I tried to use postgresql as userdb, but I got this following error:
0: log file opened: /var/log/turn.log
0: Config file found: /etc/turnserver.conf
0: Bad configuration format: psql-userdb

My configuration looks like this:
psql-userdb="host=10.130.108.XXX dbname=dbname user=qisuser password=qispassword connect_timeout=30"

I also tried following format:
psql-userdb="postgresql://qisuser:qispassword@10.130.108.XXX:5432/dbname"

Any ideas on what the correct format should be?

Thank you.

**Comment by mom040267** [comment]
It may mean that your turnserver binary was compiled without portgres support.

**Comment by fitraditya** [comment]
I have installed libpq5 and libpq-dev.

I also got following when running ./configure:
SQLite library found.
SQLite development found.
PostgreSQL found.
MySQL found.
MONGODB DEVELOPMENT LIBRARIES (libmongoc-1.0 and libbson-1.0) AND/OR HEADER (mongoc.h)
	ARE NOT INSTALLED PROPERLY ON THIS SYSTEM.
	THAT'S OK BUT THE TURN SERVER IS BUILDING WITHOUT MONGODB SUPPORT.
Hiredis found.

Did I missed something?

**Comment by mom040267** [comment]
I ll check that later.

**Comment by mom040267** [comment]
I cannot reproduce it.

Check that you have no hidden symbols in your file, and no non-English
characters that looks like English characters. That is the most probable
cause.
