### ISSUE TITLE
Log isn't written where configured

### ISSUE THREAD

**Issue by David-dp-** [coturn/coturn#343]
Although /etc/turnserver.conf contains log-file=/var/tmp/turn.log the log instead appears at /var/log/turn_9121_2019-02-14.log

Here's how I discovered this...

0. All steps as root
1. On Debian8 ec2, installed this way: apt install coturn
2. To run as a service, uncommented TURNSERVER_ENABLED=1 in /etc/default/coturn
3. Verified it's running: service --status-all
4. Read /usr/share/doc/coturn/README.Debian
5. Edited /etc/turnserver.conf
    (Left listening port as default for now)
    external-ip=((ec2's static public IP))/((ec2's private IP))
    user=someUserNameSetOnlyHere:somePasswordSetOnlyHere
    verbose
    simple-log
    syslog
    log-file=/var/tmp/turn.log
6. service coturn restart
7. /usr/bin/turnutils_stunclient -p 3478 ((private ip))
   stdout should show results
8. ls -l /var/log/ |grep turn
     Shows match: turn_9121_2019-02-14.log
9. ls -l /var/tmp/turn.log
     No match.

**Comment by lgrahl** [comment]
Furthermore, a log file is being written even if the setting `log-file=stdout` has been set.

**Comment by misi** [comment]
@David-dp- Try to use only syslog and comment out simple-log.
I guess simple-log option turns on file logging.

**Comment by misi** [comment]
@lgrahl I need to check it. 
Thanks for reporting it.

**Comment by David-dp-** [comment]
But I do want file-logging. It's not appearing where config specifies.

This isn't a blocker for me, but was a source of confusion for this
first-time user.

**Comment by misi** [comment]
I will change the default log to syslog, to avoid any confusion around file logging. 
And also allow to log even if turnserver is runing from systemd with unprivileged user.

**Comment by misi** [comment]
As man page states the turnserver tries in this order to write the log file in the following directories: /var/log/turnserver, /var/log, /var/tmp, /tmp and . (current)
If it finds it has the right permission starts logging if not fall backs to the next directory in the list.

**Comment by David-dp-** [comment]
If a log location is configured, shouldn't it try that first, and if that
fails, write an error to the log if it can be written to one of the
fallback locations?

**Comment by Sanyy** [comment]
The log is also world readable when it's created with postgres database credentials.

**Comment by damnms** [comment]
i configured turnserver to write to /var/log/turn.log, and what do i see in my syslog?
Jan 14 22:33:55 server turnserver[32225]: ERROR: Cannot open log file for writing: /var/log/turn_2021-01-14.log

thats a very nasty behaviour

**Comment by misi** [comment]
@damnms  If you can send a Pull Request I am happy to merge. Unfortunately I am busy with other issues..

**Comment by fredericpetit02** [comment]
Hello, same situation on Debian Buster

  Package: coturn
  Version: 4.5.1.1-1.1+deb10u2 armhf

two errors : /var/log not writable by turnserver and after a touch/777 isn't written where configured like David-dp- says.

**Comment by Nicholi** [comment]
I believe a lot of the logging was fixed/modified just after 4.5.1.

I am using Ubuntu's `4.5.1.1-1.1ubuntu0.20.04.2` and have noticed similar behavior when checking the log files. Also every restart of coturn would truncate the current log (wiping out old data). I'm fairly certain most of this has been fixed for next release.

**Comment by eakraly** [comment]
Some logging changes have been implemented since last update here
Please test with 4.6.0 and if the problem is still there - open a new issue

Thank you!
