### ISSUE TITLE
DFN-CERT-2019-0180 vulnerability

### ISSUE THREAD

**Issue by PiotrIr** [coturn/coturn#346]
I've scanned my coturn server using openvas and it showed me vulnerability as on subject. It also advises to upgrade to version 4.5.0.9 or above. However when I do apt upgrade on my Ubuntu 16.04, it shows me message: "coturn is already the newest version (4.5.0.7-1ubuntu2.18.04.1)". Could you advise please? Is any other repository which I can use to upgrade my TURN server?

**Comment by misi** [comment]
It could be confusing sorry about it. 

You need to upgrade to 4.5.1.0 for the proper fix.

I made a hotfix for debian stable and ubuntu LTS.
I made a hotfix that is backported to 4.5.0.7 for ubuntu LTS versions  and 4.5.0.8 for e.g. stable debian.

I have also made a backports package of 4.5.1.0 for debian stable. 
It would be also great to have 4.5.1.0 backports for ubuntu LTS too. 
It is still missing.. (Unfortunately I have limited time so I can't do it for all distribution.)

- https://packages.ubuntu.com/search?keywords=coturn
- https://packages.debian.org/search?keywords=coturn

**Comment by PiotrIr** [comment]
Hi Mihály,
Thank you for your quick reply.
I just wander what I should do with this now. I mean should I upgrade or apply hotfix (if so could you advise how?) or pretty soon I will be able to do apt upgrade and I will get 4.5.1.0 version installed?

**Comment by misi** [comment]
Hotfix is a good start. So upgrade to the latest hotfix release in your distribution.

This is disabling "hard coded" the web-admin interface. And fix two other issues.
If you don't required to use webadmin interface then the hotfix is fixing all three known vulnerabilities.

I hope this helps.

**Comment by PiotrIr** [comment]
Hi Mihály,

Could you tell me how to install the hotfix and check if it is correct version of coturn please?
When I'm doing apt upgrade it shows me "coturn is already the newest version (4.5.0.7-1ubuntu2.18.04.1)"

**Comment by misi** [comment]
The ".1" at the and show that your package has the hotfix.
If you want to test it. You can try to make a http connection with wget or any browser to your stun/turn port and if it fails than you are safe.

**Comment by PiotrIr** [comment]
Thank you Mihály,
