### ISSUE TITLE
http request failed

### ISSUE THREAD

**Issue by yincongcyincong** [coturn/coturn#348]
this is my command
`
 /usr/bin/turnserver --listening-port=9999 -v --no-tls --no-dtls --lt-cred-mech --listening-device=ens160 --relay-device=ens160 --min-port=49152 --max-port=65535 --fingerprint --static-auth-secret=1234 --stale-nonce --cert=/mnt/webrtc/tls/nginxcrt.pem --pkey=/mnt/webrtc/tls/nginxkey.pem --no-loopback-peers --no-multicast-peers --mobility --no-cli
`

this is error when i user "http://192.168.3.196:9999/v1alpha/iceconfig?key=29a949ab78ef12c604bdb01aa48ffb79" request turnserver
`
10: IPv4. tcp or tls connected to: 10.17.8.125:50724
10: IPv4. tcp or tls connected to: 10.17.8.125:50723
10: HTTPS connection has been disabled due Vulnerability in the Web interface !!!
10: session 002000000000000001: client socket to be closed in client handler: ss=0x7fc1f4003f20
10: session 002000000000000001: closed (2nd stage), user <> realm <> origin <>, local 192.168.3.196:9999, remote 10.17.8.125:50723, reason: general
15: session 003000000000000001: TCP socket closed remotely 10.17.8.125:50724
15: session 003000000000000001: closed (
`

**Comment by misi** [comment]
Which os distribution(ver) 
Which coturn version do you use?

Use coturn version 4.5.1.0
See man page coturn: web-admin part
       --web-admin
              Enable Turn Web-admin support. By default it is disabled.

       --web-admin-ip=<IP>
              Local system IP address to be used for Web-admin server endpoint. Default value is 127.0.0.1.

       --web-admin-port=<port>
              Web-admin server port. Default is 8080.

       --web-admin-listen-on-workers
              Enable for web-admin server to listens on STUN/TURN workers STUN/TURN ports.  By default it is disabled for security resons!  (This beahvior used to be the default bahavior, and was enabled by default.)

**Comment by yincongcyincong** [comment]
my conturn‘s version is 4.5.0.3，i will user 4.5.1.0
