### ISSUE TITLE
Documentation Gone For AWS Instance

### ISSUE THREAD

**Issue by jasonboggess** [coturn/coturn#35]
It looks like there is a 4.5.0.3 version of the AWS EC2 AMI (thank you!!) but there's no documentation on how to access or setup. I found this page through google: https://coturn.googlecode.com/svn-history/r865/amazonlinuxami/turnserver-4.4.5.3-amazon-aws-ec2-x86_64.txt but I cannot find a similar page in github (either the repo or the wiki).

Thanks so much for making this!

**Comment by mom040267** [comment]
On Wed, Feb 3, 2016 at 5:56 PM, jasonboggess <notifications@github.com>
wrote:

> It looks like there is a 4.5.0.3 version of the AWS EC2 AMI (thank you!!)
> but there's no documentation on how to access or setup. I found this page
> through google:
> https://coturn.googlecode.com/svn-history/r865/amazonlinuxami/turnserver-4.4.5.3-amazon-aws-ec2-x86_64.txt
> but I cannot find a similar page in github (either the repo or the wiki).
>
The documentation is available inside AMI.


> Also wondering how to access the AMI. Created a server with the image, but
> the public key I chose is not allowing me to access it.
>

I have no idea. Your public key must allow access to the servers that you
created.

**Comment by jasonboggess** [comment]
We can close this. I create a new instance/key and it worked (aws magic? haha). I found the docs where you said they were!
