### ISSUE TITLE
Coturn 4.5.1.0 stretch-backports debian 9.8

### ISSUE THREAD

**Issue by PiotrIr** [coturn/coturn#350]
Hi,
I'm trying to install Coturn 4.5.1.0 from stretch-backports repository on Debian 9.8. After installation the service starts correctly but there is no /etc/turnserver.conf file and the service is not not listening on any ports. When I create the /etc/turnserver.conf, it doesn't change anything. Could you advise please?

**Comment by misi** [comment]
I have checked and I have turnserver.conf  in the pac
```
root@misi-coturn-test:/home/misi# dpkg -L coturn |grep conf
/usr/share/doc/coturn/examples/etc/turnserver.conf.gz
/etc/turnserver.conf
root@misi-coturn-test:/home/misi# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch
root@misi-coturn-test:/home/misi# dpkg -l coturn
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                  Version                         Architecture                    Description
+++-=====================================================-===============================-===============================-===============================================================================================================
ii  coturn                                                4.5.1.0-1~bpo9+1                amd64                           TURN and STUN server for VoIP
root@misi-coturn-test:/home/misi#
```

**Comment by PiotrIr** [comment]
Hi,

Thank you for quick reply.
I've installed it from the eb http://deb.debian.org/debian stretch-backports main repository.
On my server is missing:

amsroot@rich-turn:~$ dpkg -L coturn |grep conf
/usr/share/doc/coturn/examples/etc/turnserver.conf.gz
amsroot@rich-turn:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch
amsroot@rich-turn:~$ dpkg -l coturn
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  coturn         4.5.1.0-1~bp amd64        TURN and STUN server for VoIP

**Comment by misi** [comment]
what is the output on your host the
`dpkg -L coturn |grep conf`

**Comment by PiotrIr** [comment]
dpkg -L coturn |grep conf
/usr/share/doc/coturn/examples/etc/turnserver.conf.gz

No more

**Comment by misi** [comment]
Thanks! I will try to purge my package and install again. 
But unfortunately I will check it only tomorrow..

**Comment by PiotrIr** [comment]
Thank you!

**Comment by wferi** [comment]
Wasn't the coturn package installed and then removed (but not purged) from your system? If you manually remove a config file dpkg will respect that administrator decision on reinstall, until the package is purged.
See https://raphaelhertzog.com/2010/09/21/debian-conffile-configuration-file-managed-by-dpkg/ for details.

**Comment by PiotrIr** [comment]
Hi
It is  installation on fresh system. I've done it twice.

**Comment by wferi** [comment]
Right, it's a bug, that file is simply missing.

**Comment by misi** [comment]
@PiotrIr  thanks. I can confirm it.
Sorry it was my fault.. :( 
Sorry for the inconveniences, and thanks for reporting it.

Until I fix it as workaround 
`gunzip --stdout /usr/share/doc/coturn/examples/etc/turnserver.conf.gz > /etc/turnserver.conf`

**Comment by PiotrIr** [comment]
Hi Mihály,
Thank for this.
Unfortunately I still have no luck with this. When I set any port apart of 80 it is working, but when I set 
listening-port=80
It is not. 
The server is dedicated for Coturn. There is nothing what listen on port 80 (as far as I know). There is also no logs in \var\log folder, I mean no file at all. Will you be able to advise me something please?

netstat -l
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     9735     /run/systemd/fsck.progress
unix  2      [ ACC ]     STREAM     LISTENING     12595    /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     1495     /run/user/1000/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     1500     /run/user/1000/gnupg/S.gpg-agent.extra
unix  2      [ ACC ]     STREAM     LISTENING     9694     /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     1503     /run/user/1000/gnupg/S.gpg-agent
unix  2      [ ACC ]     STREAM     LISTENING     1505     /run/user/1000/gnupg/S.gpg-agent.ssh
unix  2      [ ACC ]     STREAM     LISTENING     1507     /run/user/1000/gnupg/S.gpg-agent.browser
unix  2      [ ACC ]     SEQPACKET  LISTENING     9706     /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     9719     /run/systemd/journal/stdout

service coturn status
â coturn.service - coTURN STUN/TURN Server
   Loaded: loaded (/lib/systemd/system/coturn.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-03-01 09:42:59 GMT; 54s ago
     Docs: man:coturn(1)
           man:turnadmin(1)
           man:turnserver(1)
  Process: 752 ExecStartPost=/bin/sleep 2 (code=exited, status=0/SUCCESS)
  Process: 750 ExecStart=/usr/bin/turnserver --daemon -c /etc/turnserver.conf --pidfile /run/turnserver/turnserver.pid (code=exited, status=0/SUCCESS)
 Main PID: 751 (turnserver)
    Tasks: 9 (limit: 9830)
   CGroup: /system.slice/coturn.service
           ââ751 /usr/bin/turnserver --daemon -c /etc/turnserver.conf --pidfile /run/turnserver/turnserver.pid

Mar 01 09:42:57 rich-turn systemd[1]: coturn.service: Service hold-off time over, scheduling restart.
Mar 01 09:42:57 rich-turn systemd[1]: Stopped coTURN STUN/TURN Server.
Mar 01 09:42:57 rich-turn systemd[1]: Starting coTURN STUN/TURN Server...
Mar 01 09:42:59 rich-turn systemd[1]: Started coTURN STUN/TURN Server.

journalctl -u coturn -b
-- Logs begin at Fri 2019-03-01 09:32:54 GMT, end at Fri 2019-03-01 09:44:10 GMT. --
Mar 01 09:32:55 rich-turn systemd[1]: Starting coTURN STUN/TURN Server...
Mar 01 09:32:58 rich-turn systemd[1]: Started coTURN STUN/TURN Server.
Mar 01 09:33:56 rich-turn systemd[1]: coturn.service: Main process exited, code=exited, status=255/n/a
Mar 01 09:33:56 rich-turn systemd[1]: coturn.service: Unit entered failed state.
Mar 01 09:33:56 rich-turn systemd[1]: coturn.service: Failed with result 'exit-code'.
Mar 01 09:33:56 rich-turn systemd[1]: coturn.service: Service hold-off time over, scheduling restart.
Mar 01 09:33:56 rich-turn systemd[1]: Stopped coTURN STUN/TURN Server.
Mar 01 09:33:56 rich-turn systemd[1]: Starting coTURN STUN/TURN Server...
Mar 01 09:33:58 rich-turn systemd[1]: Started coTURN STUN/TURN Server.
Mar 01 09:34:56 rich-turn systemd[1]: coturn.service: Main process exited, code=exited, status=255/n/a
Mar 01 09:34:56 rich-turn systemd[1]: coturn.service: Unit entered failed state.
Mar 01 09:34:56 rich-turn systemd[1]: coturn.service: Failed with result 'exit-code'.
Mar 01 09:34:56 rich-turn systemd[1]: coturn.service: Service hold-off time over, scheduling restart.
Mar 01 09:34:56 rich-turn systemd[1]: Stopped coTURN STUN/TURN Server.
Mar 01 09:34:56 rich-turn systemd[1]: Starting coTURN STUN/TURN Server...
Mar 01 09:34:58 rich-turn systemd[1]: Started coTURN STUN/TURN Server.

**Comment by PiotrIr** [comment]
Hi,
I've eventually found location of logs (/var/tmp/systemd-private-bd0076a1b850408da1c534eb4252358c-coturn.service-OhlgM4/tmp/turn_904_2019-03-01.log) - is any way to change it?

It shows:
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:80, again...
0: Trying to bind fd 40 to <127.0.0.1:80>: errno=13
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:80
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:80, again...
0: Trying to bind fd 26 to <127.0.0.1:80>: errno=13
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:80
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:80, again...
0: Trying to bind fd 21 to <127.0.0.1:80>: errno=13
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:80
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:80, again...
0: Trying to bind fd 20 to <127.0.0.1:80>: errno=13
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:80
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:80, again...
0: Trying to bind fd 39 to <127.0.0.1:80>: errno=13
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:80
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:80, again...
0: Trying to bind fd 46 to <127.0.0.1:80>: errno=13
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:80
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:80, again...
0: Trying to bind fd 41 to <127.0.0.1:80>: errno=13
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:80
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:80, again...

**Comment by misi** [comment]
change the log location in config or even better to use syslog

**Comment by PiotrIr** [comment]
At lest I found the reason of my problem but don't have a resolution yet (I'm more familiar with Ubuntu than Debian). The issue is, looks like coturn doesn't have root privileges so I can't run it on port below 1024 and write logs directly to \var\logs. I know I cold use iptables to redirect ports but could you tell me if this right way to do this? Perhaps it would be possible to run the coturn on port 80? It would simplify also using lets encrypt for...

**Comment by misi** [comment]
Add to your systemd config 
`AmbientCapabilities=CAP_NET_BIND_SERVICE`

**Comment by misi** [comment]
As I mentioned try to enable in config the `syslog`.

**Comment by PiotrIr** [comment]
Sorry for annoying you but it looks I have no luck with Debian. 
Eventually I've managed to start everything on listening-port but not able to do this on tls-listening-port. I've got certificate from certbot and specified path to:
cert=/etc/letsencrypt/live/turn.my.domain/cert.pem
pkey=/etc/letsencrypt/live/turn.my.domain/privkey.pem
or
cert=/etc/letsencrypt/live/turn.my.domain/fullchain.pem
pkey=/etc/letsencrypt/live/turn.my.domain/privkey.pem
But the service listening only on port without tls. There is noting in logs even if I enabled extra verbose mode. It just simply rung standard port and no more. Could it be permission issue?
Also if I will add 
AmbientCapabilities=CAP_NET_BIND_SERVICE
to the service - could you tell me what happen after coturn update? Will the parameter stay?

**Comment by PiotrIr** [comment]
Eventually I managed to fully run coturn with 

# chmod 755 /etc/letsencrypt/live/
# chmod 755 /etc/letsencrypt/archive/
and forwarding port 443 to 8443 (just in case updates will change 
AmbientCapabilities=CAP_NET_BIND_SERVICE setting).

Many thanks for your help.

**Comment by misi** [comment]
@PiotrIr IMHO this chmod 755 works but in long term is not a smart solution from security point of view.

**Comment by PiotrIr** [comment]
Hmm, so what would you recommend as a smart solution?
