### ISSUE TITLE
tcp_peer_accept_connection: peer has no permission to connect

### ISSUE THREAD

**Issue by wxWU5** [coturn/coturn#352]
Hello, I could not connect to the relay ip&port and I get a fail message like tcp_peer_accept_connection: peer has no permission to connect. Actually, I have recevied createPermission success response 
![image](https://user-images.githubusercontent.com/44425604/53622594-49c39b00-3c35-11e9-8833-2a3cdd6188ca.png). AFAIK,  XOR-PEER-ADDRESS: 0.0.0.0:0 indicates all ip are get the permission. 
This is my log:
[turn_3792_2019-03-01.log](https://github.com/coturn/coturn/files/2918342/turn_3792_2019-03-01.log)
These are my configure:
# relay-device=eth1
# listening-ip=172.17.52.32
listening-port=3478
tls-listening-port=5349
relay-ip=172.17.52.32
external-ip=public ip
# userdb=/etc/turnuserdb.conf
relay-threads=50 
min-port=49152 
max-port=65535 

verbose
# cli-password=qwerty
allowed-peer=218.2.216.15
 
user=81151007173:TUBG7CX0
user=81151007428:YGG4C2SJ
realm=REALM
stale-nonce=600
cert=/etc/turn_server_cert.pem
pkey=/etc/turn_server_pkey.pem
pidfile="/var/run/turnserver.pid"

Anyone can help me to solve this problem? Thanks!

**Comment by misi** [comment]
I need to check it. Please be patient..

**Comment by wxWU5** [comment]
OK, thanks for your reply.

**Comment by misi** [comment]
Wildcard is not supported as far as I know in coturn. 
And I think reading again the https://tools.ietf.org/html/rfc5766#section-2.3 that it is not possible because you have to add your permitted ip one by one as a protection mechanism..
And if we allow a wildcard then it is like we didn't implement this permission in the protocol.

**Comment by wxWU5** [comment]
> Wildcard is not supported as far as I know in coturn.
> (I have double checked the code and I didn't find any sign that coturn supports wildcard permissions.)
> 
> And I think reading again the https://tools.ietf.org/html/rfc5766#section-2.3 that it is not possible because you have to add your permitted ip one by one as a protection mechanism..
> And if we allow a wildcard then it is like we didn't implement this permission in the protocol.
> 
> I hope I answered your question..

All right, thank you for letting me know about these.
