### ISSUE TITLE
Unable to access web interface of turnadmin

### ISSUE THREAD

**Issue by Chandramouli-P** [coturn/coturn#355]
Hello,

I already installed coturn and worked successfully many times. Now, I am trying to setup coturn in a new CentOS 7.x server on AWS. I generated SSL certificates using openssl as usual and created a admin user with this command:

turnadmin -A -u chandramouli -r ec2-11-123-26-12.ap-south-1.compute.amazonaws.com -p password

Now, When I am trying to open admin interface to add Turn users (https://11-123-26-12:5349 or https://11-123-26-12:3478), **I am getting the below errors on coturn console:**

42: IPv4. tcp or tls connected to: 183.83.80.29:6138
42: session 000000000000000001: client socket to be closed in client handler: ss=0x7f27600038f0
42: session 000000000000000001: usage: realm=<ec2-11-123-26-12.ap-south-1.compute.amazonaws.com>, username=<>, rp=1, rb=341, sp=0, sb=0
42: session 000000000000000001: closed (2nd stage), user <> realm <ec2-11-123-26-12.ap-south-1.compute.amazonaws.com> origin <>, local 10.1.0.123:5349, remote 183.83.80.29:6138, reason: general
42: session 000000000000000001: SSL shutdown received, socket to be closed (local 10.1.0.123:5349, remote 183.83.80.29:6138)

**Below is the Turnserver configuration:**
min-port=49152
max-port=65535
verbose
fingerprint
lt-cred-mech
realm=ec2-11-123-26-12.ap-south-1.compute.amazonaws.com
listening-ip=10.1.0.123
relay-ip=10.1.0.123
external-ip=11-123-26-12
log-file=/var/log/turnserver.log
listening-port=3478
tls-listening-port=5349

For your information, firewall is completely removed from CentOS server and allowed all traffic in AWS. Also, I changed the IP addresses in this thread. I have done this many times. But, I really don't understand why I am getting the above errors this time. Hence, request you to help us to resolve the issue.

Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Any update would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by misi** [comment]
Which version do you use?

**Comment by Chandramouli-P** [comment]
Hello,

I am not sure about the version. But, I got the code through git by using the below commands:

git clone https://github.com/coturn/coturn.git
cd coturn
./configure
make
sudo make install

Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Any update would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by misi** [comment]
man turnserver 
See web-admin part:
       --web-admin
              Enable Turn Web-admin support. By default it is disabled.

       --web-admin-ip=<IP>
              Local system IP address to be used for Web-admin server endpoint. Default value is 127.0.0.1.

       --web-admin-port=<port>
              Web-admin server port. Default is 8080.

       --web-admin-listen-on-workers
              Enable for web-admin server to listens on STUN/TURN workers STUN/TURN ports.  By default it is disabled for security resons!  (This behavior used to be the default behavior, and was enabled by default.)

**Comment by Chandramouli-P** [comment]
Hello,

Thank you very much for your help.

Best Regards,
Chandramouli.

**Comment by rasos** [comment]
I am just getting

```
TURN Server
use https connection for the admin session
```

and if I connect with `https` nothing happens.

**Comment by nejeoui** [comment]
Same here 

TURN Server
use https connection for the admin session

But when i connect with https i got timeout

**Comment by ivan-uqido** [comment]
I have the same problem with coturn 4.5.2 on latest ubuntu 20.04.02 LTS: http works but return just a simple message to use https instead; https doesn't load and the request go in timeout.

**Comment by claudiocastro** [comment]
make sure to setup the "cert" and "pkey" parameter in order to use web-admin

**Comment by ivan-uqido** [comment]
@claudiocastro in my case those two parameters are configured with Letsencrypt certificates.

**Comment by claudiocastro** [comment]
@ivan-uqido take a look at the logs, maybe you have the wrong permissions on the letsencrypt certificates?

**Comment by filoucrackeur** [comment]
is it possible to use web admin without https ?

**Comment by eakraly** [comment]
Hi @rorrim-dev @filoucrackeur @nejeoui 
Do you still have an issue or did you find a workaround?

**Comment by Cremesis** [comment]
@eakraly I haven't found a workaround, but I left the project where I used coturn now...
