### ISSUE TITLE
[Question] How can I edit coturn project, what tool can i use to edit ?

### ISSUE THREAD

**Issue by hangocanh2303** [coturn/coturn#357]
First, thank for view my question
Can you solve this question for me?

**Comment by misi** [comment]
Use your favorite text editor or developer environment.

I am not really sure if I understood your question correctly.

**Comment by hangocanh2303** [comment]
@misi It's very basic question, I 'm beginner. I read rfc document about stun, turn. When I install coturn library in my centOS server. I don't understand how coturn code work flow.

**Comment by chanduthedev** [comment]
Hi @hangocanh2303 , you can use your favorite text editor to modify existing source code.  Please follow below steps to understand the complete flow.

1. Add some debug logs
2. Recompile 
3. Install 
4. Repeat 1-3 steps until you understand the complete flow.

Happy Coding!!

**Comment by misi** [comment]
Happy coding also! 
Unfortunately I don't have the resource to help you more.
I am so sorry for the late reply..
