### ISSUE TITLE
Empty CLI password even if CLI disabled

### ISSUE THREAD

**Issue by madmath03** [coturn/coturn#361]
The turnserver displays a configuration error when CLI password is empty even if the CLI has been disabled with `--no-cli`:
https://github.com/coturn/coturn/blob/856c3c9ff620ae2b00354ac55c539ba3dadb16f7/src/apps/relay/mainrelay.c#L2252-L2255

**Comment by misi** [comment]
Thanks for reporting and fixing it.

**Comment by VolodyaIvanets** [comment]
I was trying to start turnserver v4.5.1.1 with **no-cli** option but got same error message:
```
# turnserver --no-cli
0: ERROR:
CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
```

**Comment by misi** [comment]
Thanks @VolodyaIvanets!
Can you please open a new issue send a PR. 
I am busy with other stuff. So sorry..
Thanks.

**Comment by theronic** [comment]
Also bitten by this. How do I set a CLI password?

**Comment by de-saksham** [comment]
@theronic  cli-password=yourpassword

**Comment by developdeez** [comment]
Same issue. How do you use that command @de-saksham ?
I'm new to linux

**Comment by de-saksham** [comment]
@developdeez you can enter this in turnserver.conf file like
cli-password = yourpassword

Yes, as experienced until you don't pass this cli-password server won't start. This is the only issue.

**Comment by misi** [comment]
It is because of security and vulnerability reported by many. Sorry for it. 
It is just you should set a password.

**Comment by misi** [comment]
I fixed the no-cli issue.

**Comment by lekhnath** [comment]
@misi I generated hashed password using following command:
```bash
$ turnadmin -P -p mypassword
$5$2b68f7dfecd69648$d87a5bc81adc17921cea7e4b30c2e2d0f5eb0339d2e0d3f20f3e7ece5489e7ea
```
And updated configuration file `/etc/turnserver.conf` as follows:
```txt
cli-password=$5$2b68f7dfecd69648$d87a5bc81adc17921cea7e4b30c2e2d0f5eb0339d2e0d3f20f3e7ece5489e7ea
```

and then re run the `turnserver` command but still getting the same error message that says **CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!**

What should I do next to apply the configuration changes?

Error log:

```txt
0: log file opened: /var/tmp/turn_3295_2020-07-21.log
0: 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.0.7 'dan Eider'
0: 
Max number of open files/sockets allowed for this process: 1048576
0: 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
0: 

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: DTLS 1.2 supported
0: TURN/STUN ALPN supported
0: Third-party authorization (oAuth) supported
0: GCM (AEAD) supported
0: OpenSSL compile-time version: OpenSSL 1.1.1  11 Sep 2018 (0x1010100f)
0: 
0: SQLite supported, default database location is /var/lib/turn/turndb
0: Redis supported
0: PostgreSQL supported
0: MySQL supported
0: MongoDB is not supported
0: 
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: Listener address to use: <privateip>
0: Domain name: 
0: Default realm: someRealm
0: ERROR: 
CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
0: Relay address to use: <privateip>
```

**Comment by lekhnath** [comment]
@misi never mind I was using `-n` option in `turnserver` command which was bypassing the configuration file. :)

**Comment by nilinswap** [comment]
> @misi I generated hashed password using following command:
> 
> ```shell
> $ turnadmin -P -p mypassword
> $5$2b68f7dfecd69648$d87a5bc81adc17921cea7e4b30c2e2d0f5eb0339d2e0d3f20f3e7ece5489e7ea
> ```
> 
> And updated configuration file `/etc/turnserver.conf` as follows:
> 
> ```
> cli-password=$5$2b68f7dfecd69648$d87a5bc81adc17921cea7e4b30c2e2d0f5eb0339d2e0d3f20f3e7ece5489e7ea
> ```
> 
> and then re run the `turnserver` command but still getting the same error message that says **CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!**
> 
> What should I do next to apply the configuration changes?
> 
> Error log:
> 
> ```
> 0: log file opened: /var/tmp/turn_3295_2020-07-21.log
> 0: 
> RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
> Version Coturn-4.5.0.7 'dan Eider'
> 0: 
> Max number of open files/sockets allowed for this process: 1048576
> 0: 
> Due to the open files/sockets limitation,
> max supported number of TURN Sessions possible is: 524000 (approximately)
> 0: 
> 
> ==== Show him the instruments, Practical Frost: ====
> 
> 0: TLS supported
> 0: DTLS supported
> 0: DTLS 1.2 supported
> 0: TURN/STUN ALPN supported
> 0: Third-party authorization (oAuth) supported
> 0: GCM (AEAD) supported
> 0: OpenSSL compile-time version: OpenSSL 1.1.1  11 Sep 2018 (0x1010100f)
> 0: 
> 0: SQLite supported, default database location is /var/lib/turn/turndb
> 0: Redis supported
> 0: PostgreSQL supported
> 0: MySQL supported
> 0: MongoDB is not supported
> 0: 
> 0: Default Net Engine version: 3 (UDP thread per CPU core)
> 
> =====================================================
> 
> 0: Listener address to use: <privateip>
> 0: Domain name: 
> 0: Default realm: someRealm
> 0: ERROR: 
> CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
> 0: Relay address to use: <privateip>
> ```

this works for me well. Thanks @lekhnath

**Comment by yanghanxing1** [comment]
> @misi我使用以下命令生成了哈希密码：
> 
> ```shell
> $ turnadmin -P -p mypassword
>  $ 5 $ 2 b68f7dfecd69648 $ d87a5bc81adc17921cea7e4b30c2e2d0f5eb0339d2e0d3f20f3e7ece5489e7ea
> ```
> 
> 并更新了配置文件`/etc/turnserver.conf`，如下所示：
> 
> ```
> cli-password=$5$2b68f7dfecd69648$d87a5bc81adc17921cea7e4b30c2e2d0f5eb0339d2e0d3f20f3e7ece5489e7ea
> ```
> 
> 然后重新运行该`turnserver`命令，但仍收到表示**配置错误的**错误消息**：空cli-password，因此telnet cli接口已禁用！请设置一个非空的cli-password！**
> 
> 接下来，我该怎么做才能应用配置更改？
> 
> 错误日志：
> 
> ```
> 0: log file opened: /var/tmp/turn_3295_2020-07-21.log
> 0: 
> RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
> Version Coturn-4.5.0.7 'dan Eider'
> 0: 
> Max number of open files/sockets allowed for this process: 1048576
> 0: 
> Due to the open files/sockets limitation,
> max supported number of TURN Sessions possible is: 524000 (approximately)
> 0: 
> 
> ==== Show him the instruments, Practical Frost: ====
> 
> 0: TLS supported
> 0: DTLS supported
> 0: DTLS 1.2 supported
> 0: TURN/STUN ALPN supported
> 0: Third-party authorization (oAuth) supported
> 0: GCM (AEAD) supported
> 0: OpenSSL compile-time version: OpenSSL 1.1.1  11 Sep 2018 (0x1010100f)
> 0: 
> 0: SQLite supported, default database location is /var/lib/turn/turndb
> 0: Redis supported
> 0: PostgreSQL supported
> 0: MySQL supported
> 0: MongoDB is not supported
> 0: 
> 0: Default Net Engine version: 3 (UDP thread per CPU core)
> 
> =====================================================
> 
> 0: Listener address to use: <privateip>
> 0: Domain name: 
> 0: Default realm: someRealm
> 0: ERROR: 
> CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
> 0: Relay address to use: <privateip>
> ```



> @misi没关系，我`-n`在`turnserver`绕过配置文件的命令中使用了选项。:)

same question!sir,how do you solve this problem?

**Comment by Govind10g** [comment]
Facing same issue ? any update on this ? 
Sep 23 08:23:44 ip-xyz turnserver[23507]: 0: : #012CONFIG: --no-tcp-relay: TCP relay endpoints are not allowed.
Sep 23 08:23:44 ip-xyz turnserver[23507]: 0: : ERROR: #012CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!

**Comment by Vakil-Parth** [comment]
@Govind10g I think we need to add password to `/etc/turnserver.conf`. example cli-password=xxxxx
and pass `--cli-password` argument with password set to /etc/turnserver.conf. example 
`turnserver -a -o -v -n -u user:pass -p 3478 -r someRealm -X xxx.xxx.xxx.xxx/xx.xx.x.x --no-dtls --no-tls --cli-password=xxxxx`
