### ISSUE TITLE
webrtc connection within vpn

### ISSUE THREAD

**Issue by HeyConDev** [coturn/coturn#365]
Hello. I have to build a medical webrtc communication solution for patients and their doctors. 
Privacy and confidentiality is very important for our users. Our application runs without problems in the chrome browser and this also in the VPN tunnel. The connection fails, however, if the same application in the Firefox browser to be operated.

Patients sometimes stay in countries where privacy is not taken seriously. The internet connection is currently often insufficient in these countries. Therefore, the patient is provided with a special, prioritized line that provides the necessary speed for a video chat session. The structure of this line takes the form of a VPN tunnel (provider: pulse secure). The policies of our organization require Firefox.

We use the absolutely great coturn server with this configuration:
`listening-port=3478
tls-listening-port=5349
realm=xyz.com
min-port=49152
max-port=65535
user=uuuuuuuuuuuuu:ppppppppppp
pkey=/usr/local/psa/var/modules/letsencrypt/etc/live/turn.xyz.net/privkey.pem
cert=/usr/local/psa/var/modules/letsencrypt/etc/live/turn.xyz.net/cert.pem
CA-file=/usr/local/psa/var/modules/letsencrypt/etc/live/turn.xyz.net/chain.pem
mysql-userdb="host=localhost dbname=turnxxxxxx user=uuuuuuuuuuuu password=ppppppppppp port=3306"
fingerprint
lt-cred-mech`
     
I want to help the affected people and therefore I am open to any idea or suggestion that will help me to solve the problem. Thank you.

**Comment by misi** [comment]
Hi,

(May I am the only one, but) I didn't understand your actual problem,
that you want to solve.

Can you please explain it more?

Thanks,
Misi

2019. 03. 14. 16:30 keltezéssel, Ariane írta:

**Comment by HeyConDev** [comment]
Hello misi,
thank you for asking. I try again to make it clearer. 
Our application enables one to one peer connections in the medical field. The software is used in the area of ​​corporate health. That's why I have to adhere to certain specifications of the companies. This includes that all connections MUST always be made in the VPN tunnel (pulse secure) - including the webrtc peer to peer connection. (Unfortunately I do not have the option to choose another VPN user.)

When users use Chromium-based browsers in combination with their VPN tunnel, everything works perfectly. However, the connection should also be possible with the Firefox browser.

Our application works fine in Firefox without VPN. However, if users build their VPN tunnel, then use the Firefox browser to connect to their doctor through our application, this will fail. There is no connection established.

Now that I have several components (my software, firefox, coturn) involved, I'm now trying to figure out where I possibly did something wrong and what I can do to get my users to run a webrtc video conference in the VPN tunnel in the Firefox browser can. I am also in conversation with firefox and also with the VPN manufacturer Pulse secure. I'm here to ask to find out if it can be due to a setting I made on the coturn.

I hope to have clarified my concerns more clearly.

Thank you.
Ariane.

**Comment by misi** [comment]
Dear Ariane,

AFAIU it is not coturn related issue.

I think you should check the firefox "webrtc-internal" page.
So open on a new tab the "about:webrtc" and check the ICE negotiation logs..

My guess that Firefox tries hard to avoid fingerprinting of the user and
probably it does not gather the VPN interface IP address during ICE
candidate gathering.

My 2 cents,
Misi

**Comment by bradleythughes** [comment]
Looking at the list of open Firefox bugs matching "webrtc" and "turn", there are a number of bugs related to using a vpn/proxy that could affect you. I am not sure how many of them are actually relevant to your use-case. I do see that some of the issues have workarounds that might help you get your client working.

https://bugzilla.mozilla.org/buglist.cgi?quicksearch=webrtc+turn

And in particular, one of these might be interesting to you:
https://bugzilla.mozilla.org/show_bug.cgi?id=1202451
https://bugzilla.mozilla.org/show_bug.cgi?id=1421240
https://bugzilla.mozilla.org/show_bug.cgi?id=1385030
https://bugzilla.mozilla.org/show_bug.cgi?id=1471700
https://bugzilla.mozilla.org/show_bug.cgi?id=1247542
https://bugzilla.mozilla.org/show_bug.cgi?id=1454099
https://bugzilla.mozilla.org/show_bug.cgi?id=1505329
https://bugzilla.mozilla.org/show_bug.cgi?id=1416220

**Comment by HeyConDev** [comment]
Hi Bradley,
thak you very much for your suggestions. I'll take a look at that in detail.
With regards
Ariane.

**Comment by ggarber** [comment]
This has been open for a long time so I'm assuming that the issue is solved or not relevant anymore.   Thank you @bradleythughes for the information and links.
