### ISSUE TITLE
turnadmin does not disconnect from DB properly

### ISSUE THREAD

**Issue by shu-mutou** [coturn/coturn#366]
I use MySQL for userdb. When I add or delete user using turnadmin, MySQL reported notice like "Aborted connection [nnnnnnnn] todb: ...........". This causes accumulation of sockets to MySQL with TIME_WAIT.
In documents, using turnadmin is recommended for userdb management, but its not suitable for other application due to above problem.
We need documentation for userdb management from other application, especially creation of hmackey, or proper disconnection from DB for turnadmin.
My turnserver is v4.5.0.8.
BTW, I uses turnadmin from my Java application.

**Comment by misi** [comment]
Thanks for reporting. I need to check it..
Any correction in Pull Request is very welcomed.. ;-)
