### ISSUE TITLE
[Question] Sqlite database error when install parallel coturn 

### ISSUE THREAD

**Issue by hangocanh2303** [coturn/coturn#369]
Hi
I want to install two coturn in one server. I install first coturn worked well
But when i install second coturn, I get this error when I use turnadmin command: 
ERROR: Cannot open SQLite DB connection: </home/abc/def/bin-turnserver-4.5.1.0>, runtime error:
  unable to open database file
  (If your intention is to use an SQLite database for the TURN server, then
  check and fix, if necessary, the effective permissions of the TURN server
  process and of the DB directory and then re-start the TURN server)

-And error db connection directory above not the same with directory in turnserver.conf file 
Why I get this error. 
Thank you

**Comment by misi** [comment]
Check the sqlite file location... and set it in your config file

**Comment by hangocanh2303** [comment]
Thank @misi , but in my config file, I set log file location: /u01/run/BackEndApp/turn_test_4.5.1.0/var/db/turndb
When I use command turnadmin -l, coturn print this error: 
ERROR: Cannot open SQLite DB connection: </u01/run/BackEndApp/turn_test_4.5.1.0>
I mean: coturn not determine true location of log file i set. 
In case I install parallel coturn, first coturn worked well, but second coturn, error same above

**Comment by hangocanh2303** [comment]
Hi @misi , I don't want to create new question topic, so I post a new question here: 
What exactly turn session in coturn project? When one user A call to user B, I see multi session create, How can I create one session for one call (for grep log)?

**Comment by misi** [comment]
Turn session is created for every transport. 
A WebRTC call could use one or multiple transport depending on multiplexing. 
See this: https://misi.github.io/webrtc-c0d3l4b/#10

**Comment by hangocanh2303** [comment]
ok @misi, when I config multiplex and bundle, It's worked. 
But when install parallel coturn, second coturn worked, but when i use turnadmin command with second coturn, sqlite error still exist. I hope your library better, thank @misi

**Comment by misi** [comment]
Try to install multiple coturn in docker on one host. 
Perhaps it could help..

**Comment by hangocanh2303** [comment]
> Turn session is created for every transport.
> A WebRTC call could use one or multiple transport depending on multiplexing.
> See this: https://misi.github.io/webrtc-c0d3l4b/#10
Hey @misi, I have new issue: 
I change multiplexing to maxbundle and when A call to B, one session for A and one session for B created. 
But, If device of A or B disconnect network when call, and connected again -> It created  new session and old session did not close. Both New session and old session tranfer data. How can I close old session when new session created ?

**Comment by misi** [comment]
You have to wait for timeout. If the TURN agent don't renew it, then it will expire..

**Comment by eakraly** [comment]
3.5 year old issue
Please reopen if the issue is still relevant
