### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by almereyda** [coturn/coturn#37]
The @matrix-org project uses the `coturn` server, also within the [semi-official Docker environment](https://github.com/silvio/docker-matrix) by @silvio.

I am currently [refactoring said image](https://github.com/allmende/docker-matrix/tree/master/images/coturn) to split up services into separate containers.

Any wishes for configurability of the container?
We could try to create a generalized, official one and learn from [the others](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=coturn&starCount=0).

This could result in a Pull Request to this repository, if requested.

**Comment by capensisma** [comment]
This is a very good idea :) :+1:

**Comment by ebakhtarov** [comment]
Indeed, a good idea :+1:

**Comment by almereyda** [comment]
WiP now lives in https://lab.allmende.io/allmende/docker-coturn

**Comment by marcosArruda** [comment]
+1

**Comment by zhangalex** [comment]
Why not put on github.com? 👍

**Comment by gamalkamal** [comment]
why you dont put it in dockerhub

**Comment by misi** [comment]
Please send Pull Request, and I would happy to include it.
@gamalkamal @zhangalex @marcosArruda @almereyda @ebakhtarov @meteorplus @almereyda 
I will close this issue and let's continue on #273
