### ISSUE TITLE
Update versione for CentOS 7

### ISSUE THREAD

**Issue by mirkotn** [coturn/coturn#372]
could you please update the latest release for centos 7?

**Comment by misi** [comment]
Can you please explain what you mean? 
You can checkout the code from git and build it manually...
Unfortunately I don't have actually resources to maintain the binary in CentOS, but feel free to join and help and make it happen.

**Comment by xavierba** [comment]
As Fedora does now ship coturn, maintained by @LorbusChris, adding an EL7 build is just a matter of requesting a branch and doing a build. I'm currently looking at fixing some stuff in the specfile, so I verified it builds fine on EL7. Please file a bug against coturn in Fedora bug tracker.

**Comment by misi** [comment]
@xavierba Can you please help me on it? Point me where should we open a bug and any hints about the content of the new issue?

**Comment by xavierba** [comment]
@misi, I'll take care of the EL7 build once @LorbusChris has committed the various specfile fixes I have provided him.

**Comment by misi** [comment]
@xavierba 
btw.
I would be happy to merge all of your packaging developments to main coturn repo if you like.
I do the Debian packaging in this repo,  "debian/*" branches to keep it in one place, and make it easy to find things for newcomers. 
If you like we can do it for your developments too, but I am also Ok if you want to keep it in separate repository, but then I think we need to add a link to your repository in the main Readme(if it is not there already).

**Comment by eakraly** [comment]
@mirkotn @xavierba thank you for your contributions
It seems like this issue has no more activity - closing it
Please open a new one if there is more to do. Thank you!
