### ISSUE TITLE
Question about traffic in/out of turnserver

### ISSUE THREAD

**Issue by meodorewan** [coturn/coturn#374]
Hello,

I'm monitoring traffic on my turnserver, have tried `--redis-statsdb`. This flag exposes `allocated memory` in turnserver for each sessions, right?. It is good but not enough to measure turnserver's traffic. So I need the actual in/out traffic, i.e how many bytes turnserver sent/received, and sent to whom?

I found other information in `log`
` rp=1019, rb=172966, sp=1029, sb=174718`
`rp=1022, rb=173476, sp=1026, sb=174208`  

What is this log for? Is it the actual in/out traffic of turnserver?

**Comment by misi** [comment]
See this: https://github.com/coturn/coturn/blob/master/turndb/schema.stats.redis

**Comment by meodorewan** [comment]
> See this: https://github.com/coturn/coturn/blob/master/turndb/schema.stats.redis

As I read in `ns_turn_server.c`, it seems that the stats in `log`, and `--redis-statsdb` received_packets are all from 
`turn_session_info->received_packets` and `_ts_ur_super_session->received_packets`, and logically `log` and `--redis-statsdb` writes the same number, is it right?

Is there any different between `_ts_ur_super_session` and `turn_session_info` structs?

**Comment by misi** [comment]
See: 

- https://github.com/coturn/coturn/pull/191/files
- https://github.com/coturn/coturn/pull/212/files
