### ISSUE TITLE
turnutils_uclient not supporting TLS 1.2?

### ISSUE THREAD

**Issue by tenge-amzn** [coturn/coturn#376]
Hi,
It seems if we disable tls1.0 and tls1.1 on turnserver config, the uclient will not able to connect the server via TLS.

Is this something in backlog or no one ever brought up? I might be able to make a PR if no one is planning work on it

Thanks,

**Comment by misi** [comment]
We need to check it..

**Comment by Neustradamus** [comment]
@misi: Any news?

**Comment by application-developer-DA** [comment]
I tried to test the TLS relay using:

```
turnutils_uclient -u <user> -w <password> -S snapturn.snapview.de
```

and I ended up having:
```
0: : ERROR: 
ERROR: no private key found!
0: : ERROR: 
ERROR: no private key found!
```

Is it because the TLS 1.2 is not supported or for any other reason? (there must be no need to supply a private key on the client side, on the server side it's all configured, with the proper ports and with the certificate and key)

**Comment by matthew-turnaroundfactor** [comment]
This appears to still be an issue. The test client appears to lack support for both TLS 1.2 and TLS 1.3.

The "ERROR: no private key found!" @application-developer-DA saw can be bypassed by supplying a TLS client certificate with the -k option. Even if the server is not requiring/validating TLS client certificates the turnutils_uclient wants a client certificate parameter.

**Comment by eakraly** [comment]
Notes for maintainers:
- Related to #924 - massive cleanup of deprecated APIs and copies of SSL contexts is required
- Seems like turnutils_uclient incorrectly sees that option `-i` is set even if not provided
- Which then requires private key (which is not present because neither `-i` nor `-k` set)
-
