### ISSUE TITLE
Cannot Assign Requested Address - running through all the ports

### ISSUE THREAD

**Issue by WarnerV** [coturn/coturn#380]
Trying to get out-of-the-box Turnserver on Ubuntu 18.04 to work behind NAT, I have a problem.

The server starts without any errors, but as soon as I try to connect with an external device,  Turnserver starts running through all available ports, giving this message with each port:

`Trying to bind fd x to <1.2.3.4:49678>: errno=99
bind: Cannot assign requested address`

This takes a while, as there are many ports available, until it finishes with 

`create_relay_ioa_sockets: no available ports 3`

What am I doing wrong? 

- I have re-set both the router and the Ubuntu instance, and I can't imagine the ports are _actually_ in use
- My goal is to get pixelstreaming (Unreal Engine) to work, using Turnserver on Ubuntu and UE4, WebRTC and Signalling Webserver on Windows 
- For testing, I'm forwarding some of the Relay ports to the Ubuntu PC, some to the Windows PC and some not at all.. On all of the ports I'm getting the same result

Log output on starting the server is the following

` 0: log file opened: /var/log/turn_12549_2019-04-18.log
0:
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.0.7 'dan Eider'
0:
Max number of open files/sockets allowed for this process: 1048576
0:
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
0:

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: DTLS 1.2 supported
0: TURN/STUN ALPN supported
0: Third-party authorization (oAuth) supported
0: GCM (AEAD) supported
0: OpenSSL compile-time version: OpenSSL 1.1.0g  2 Nov 2017 (0x1010007f)
0:
0: SQLite supported, default database location is /var/lib/turn/turndb
0: Redis supported
0: PostgreSQL supported
0: MySQL supported
0: MongoDB is not supported
0:
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: Config file found: /root/../etc/turnserver.conf
0: Relay address to use: 2.229.233.234
0: Config file found: /root/../etc/turnserver.conf
0: Domain name:
0: Default realm: warnerveltman.com
0: ERROR:
CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
0:
CONFIGURATION ALERT: you specified user accounts, (-u option)
        but you also specified the anonymous user access option (-z or --no-auth option).
        User accounts will be ignored.
0: SSL23: Certificate file found: /usr/local/etc/turnservervwcert.pem
0: SSL23: Private key file found: /usr/local/etc/turnserverwvkey.pem
0: TLS1.0: Certificate file found: /usr/local/etc/turnservervwcert.pem
0: TLS1.0: Private key file found: /usr/local/etc/turnserverwvkey.pem
0: TLS1.1: Certificate file found: /usr/local/etc/turnservervwcert.pem
0: TLS1.1: Private key file found: /usr/local/etc/turnserverwvkey.pem
0: TLS1.2: Certificate file found: /usr/local/etc/turnservervwcert.pem
0: TLS1.2: Private key file found: /usr/local/etc/turnserverwvkey.pem
0: TLS cipher suite: DEFAULT
0: DTLS1.2: Certificate file found: /usr/local/etc/turnservervwcert.pem
0: DTLS1.2: Private key file found: /usr/local/etc/turnserverwvkey.pem
0: DTLS: Certificate file found: /usr/local/etc/turnservervwcert.pem
0: DTLS: Private key file found: /usr/local/etc/turnserverwvkey.pem
0: DTLS cipher suite: DEFAULT
0: NO EXPLICIT LISTENER ADDRESS(ES) ARE CONFIGURED
0: ===========Discovering listener addresses: =========
0: Listener address to use: 127.0.0.1
0: Listener address to use: 192.168.0.100
0: Listener address to use: ::1
0: =====================================================
0: Total: 1 'real' addresses discovered
0: =====================================================
0: pid file created: /var/run/turnserver.pid
0: IO method (main listener thread): epoll (with changelist)
0: WARNING: I cannot support STUN CHANGE_REQUEST functionality because only one IP address is provided
0: Wait for relay ports initialization...
0:   relay 2.229.233.234 initialization...
0:   relay 2.229.233.234 initialization done
0: Relay ports initialization done
0: IO method (general relay thread): epoll (with changelist)
0: IO method (general relay thread): epoll (with changelist)
0: IO method (general relay thread): epoll (with changelist)
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=1 created
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=0 created
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=2 created
0: IO method (general relay thread): epoll (with changelist)
0: IO method (udp listener/relay thread): epoll (with changelist)
0: turn server id=4 created
0: turn server id=3 created
0: turn server id=5 created
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=6 created
0: turn server id=7 created
0: turn server id=128 created
0: IO method (udp listener/relay thread): epoll (with changelist)
0: turn server id=129 created
0: IO method (udp listener/relay thread): epoll (with changelist)
0: turn server id=130 created
0: IO method (udp listener/relay thread): epoll (with changelist)
0: turn server id=131 created
0: IO method (udp listener/relay thread): epoll (with changelist)
0: turn server id=132 created
0: IO method (udp listener/relay thread): epoll (with changelist)
0: turn server id=133 created
0: Total UDP servers: 6
0: Total General servers: 8
0: IO method (auth thread): epoll (with changelist)
0: IO method (auth thread): epoll (with changelist)
0: IO method (auth thread): epoll (with changelist)
0: IO method (auth thread): epoll (with changelist)
0: IO method (admin thread): epoll (with changelist)
0: SQLite DB connection success: /var/lib/turn/turndb`

**Comment by WarnerV** [comment]
Okay.. many hours of fiddling later I solved the issue: The RELAY address should be the local IP (you can leave it empty in the config file), the LISTENING address should be the local IP (you can leave it empty in the config file) and only the EXTERNAL address should be the external IP. In my initial setup it was starting correctly (not sure exactly how), but as soon as ports were needed, the machine was not in charge of assigning them and created said error for each possible port.

Hope it helps someone!

**Comment by ranjit-singh-cc** [comment]
Hey I can see "Max number of open files/sockets allowed for this process: 1048576" - when I am running my turn server its showing 3200 number only. can you please let me know how you increased it.
