### ISSUE TITLE
Is client initiated SSL renegotiation prevention enabled by defualt?

### ISSUE THREAD

**Issue by tenge-amzn** [coturn/coturn#383]
Hi,
I saw this from changelog:
https://github.com/coturn/coturn/blob/e0d84e14ed45575bf239e747408effa7bc96d871/ChangeLog#L286

I'm wondering if this feature is enabled by default? As I tested manually, the renegotiation will stop after 3 retries. Just to confirm.

Thank you

**Comment by misi** [comment]
I think you are right.
`#define SSL_MAX_RENEG_NUMBER (3)`

See also:
https://github.com/coturn/coturn/commit/65db0bb9f6622652472a3f5fcec0832f89593dfb

**Comment by Neustradamus** [comment]
@misi: Can you look?

**Comment by eakraly** [comment]
TLS renegotiation completely disabled in #942
