### ISSUE TITLE
Packet loss and no connection when on LTE in some countries

### ISSUE THREAD

**Issue by oliverhausler** [coturn/coturn#387]
In some networks, no connection is established when an LTE mobile phone is called and relay candidates are to be used. I believe there is packet loss on coturn.

- The issue mainly happens when an LTE mobile phone is called, but also seems to happen on fiber-optic connections.
- The issue happens with multiple providers in Europe (Germany, Czech Republic), but apparently not in the US.
- T-Mobile in the US works, whereas T-Mobile Germany does not.
- The issue occurs in coturn versions `4.5.1.1`, `4.5.0.10` and `4.5.0.5`.
- The issue occurs on multiple servers at multiple providers. Servers are Ubuntu 16.04 LTE and non-firewalled.
- The issue happens with and without coturn being in a Docker container.
- The issue happens consistently, but sometimes (very rarely) we see a connection being established even where it typically does not work.
- When I am in a network where it works and I force `relay` in `rtcpeerconnection`, coturn works perfectly fine.
- Also seems to work in home DSL connections.

This is why we believe there is a bug in `coturn`, or our `config` is wrong.

# Example

Relay does not work when the callee is in the Vodafone Germany network.

- M is on Vodafone in Germany
- O is on T-Mobile in the US

When M calls O, a connection is established, and we see the following candidates. Note that the established connection is `prflx`, and there is no response for the `relay` candidates, which suggests that it works on some providers because the `prflx` IP is visible. Interesting also, that one of the relay candidates received some responses but not all.

![image](https://user-images.githubusercontent.com/8090341/57424785-c04cbe00-71cd-11e9-96ae-c9ac46866149.png)

When O calls M, no connection is established, and we see more incoming traffic on coturn than outgoing. Seems there is packet loss. You can also see there is no response below.

![image](https://user-images.githubusercontent.com/8090341/57424853-fd18b500-71cd-11e9-9de5-4b4a9a4a2e9b.png)

![image](https://user-images.githubusercontent.com/8090341/57425834-b75deb80-71d1-11e9-8ca1-3c709c706051.png)

![image](https://user-images.githubusercontent.com/8090341/57424907-30f3da80-71ce-11e9-887b-74249dd7a447.png)

While IPs are accessible in the US, it looks like `prflx` does not work in Europe due to privacy concerns. But why doesn't `relay` via coturn kick in then?

- Can you say from the candidates, if my suspicion that `prflx` is hidden in Europe due to GDPR makes sense?
- Is this enough data to conclude that the issue is most probably on coturn when `relay` is used? Why does it work when I force `relay`? Why does it work sometimes where it otherwise does not work?
- The bandwidth diagram suggests packet loss on coturn. Would it be possible that packet loss on coturn occurs because an outside provider does not accept UDP packets? We would probably see them as outgoing bandwidth then, correct?
- The fact that packets are sent and bandwidth is used means both sides believe everything is set up while it is not.

We're out of ideas. Any idea where we could dig in?

# Config and Log

We tried different ports and configurations. We're seeing the same results no matter what we change.

```
listening-ip=195.201.123.58
relay-ip=195.201.123.58
web-admin-ip=195.201.123.58
static-auth-secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# Listen
listening-port=3478
tls-listening-port=5349
min-port=49152
max-port=65535
# Cert
cert=/etc/cert/cert.pem
pkey=/etc/cert/certkey.pem
# Auth
use-auth-secret
# Web admin
web-admin
web-admin-port=447
# Logging
Verbose
log-file=stdout
# Other
fingerprint
realm=attach.live
userdb=/usr/local/var/db/turndb
```

Here's the full log of a failed session:

[logs.txt](https://github.com/coturn/coturn/files/3160240/logs.txt)

**Comment by oliverhausler** [comment]
@misi Could you have a quick look at this here, please. I am unsure if it's an issue with coturn or a config problem. Maybe you can see it and point me in the right direction. I can also give you access to a test setup in case you want to look at it directly.

**Comment by misi** [comment]
Hi @oliverhausler  I am busy with other tasks, but I will get you back ASAP.. 
Thanks for your patience..

**Comment by oliverhausler** [comment]
@misi Thank you so much. It's solved. Problem wasn't in coturn, but rather a bug in our client:

>It was a bug in our client. After creating the answer, peer connection was initialized asynchronously =>, and if it took too long and turn was too fast, it wouldn't receive all candidates. Strange that something like this can result in packet loss on coturn, but it did.

I'm closing this.

**Comment by mallamsripooja** [comment]
> 

@oliverhausler Hi, I am facing a similar issue, can you please share how you resolved your issue?

I am using simple-peer but due to async initialization the code flow is inconsistent, are you using simple-peer or RTCPeerConnection?
