### ISSUE TITLE
Binding Error Response error-code: 401

### ISSUE THREAD

**Issue by armin1402** [coturn/coturn#389]
Hi,

im trying to get coturn running to support stun and turn. 

I got a strange behavior, and i'm not sure how to get correct configuration file. 

Here is my setup:

#### Config
```
listening-port=3478
tls-listening-port=5349
alt-listening-port=3479
alt-tls-listening-port=5350
listening-ip=195.201.141.251
relay-ip=195.201.141.251
min-port=49152
max-port=65535
realm=coturn.optomed.de
cert=/var/lib/acme/coturn.optomed.de/fullchain.pem
pkey=/var/lib/acme/coturn.optomed.de/key.pem
no-stdout-log
syslog
pidfile=/run/turnserver/turnserver.pid
secure-stun
cli-ip=127.0.0.1
cli-port=5766
cipher-list="HIGH"
no-loopback-peers
no-multicast-peers
stun-only
```

#### Result
`11959	314.007987	195.201.141.251	10.XX.XX.37	STUN	106	Binding Success Response XOR-MAPPED-ADDRESS: 93.XXX.XXX.XXX:63075 MAPPED-ADDRESS: 93.XXX.XXX.XXX:63075 RESPONSE-ORIGIN: 195.201.141.251:3478`

### TURN enabled
After enabling TURN with static credentials all stun requests will fail with 401

#### Config
```
listening-port=3478
tls-listening-port=5349
alt-listening-port=3479
alt-tls-listening-port=5350
listening-ip=195.201.141.251
relay-ip=195.201.141.251
min-port=49152
max-port=65535
lt-cred-mech
realm=coturn.optomed.de
cert=/var/lib/acme/coturn.optomed.de/fullchain.pem
pkey=/var/lib/acme/coturn.optomed.de/key.pem
no-stdout-log
syslog
pidfile=/run/turnserver/turnserver.pid
secure-stun
cli-ip=127.0.0.1
cli-port=5766
fingerprint
cipher-list="HIGH"
no-loopback-peers
no-multicast-peers
user=demo:demo
verbose
```
yep, i know demo/demo is public. ;-)

#### Errors

`4029	125.892422	195.201.141.251	10.XX.XX.37	STUN	142	Binding Error Response error-code: 401 (Unauthorized) Unauthorized with nonce realm: coturn.optomed.de`

```
Mai 13 13:26:55 coturn.optomed.de turnserver[3417]: 164: handle_udp_packet: New UDP endpoint: local addr 195.201.141.251:3478, remote addr 93.XXX.XXX.XXX:58925
Mai 13 13:26:55 coturn.optomed.de turnserver[3417]: 164: session 001000000000000001: realm <coturn.optomed.de> user <>: incoming packet message processed, error 401: Unauthorized
Mai 13 13:26:56 coturn.optomed.de turnserver[3417]: 166: handle_udp_packet: New UDP endpoint: local addr 195.201.141.251:3478, remote addr 93.XXX.XXX.XXX:58927
Mai 13 13:26:56 coturn.optomed.de turnserver[3417]: 166: session 000000000000000002: realm <coturn.optomed.de> user <>: incoming packet message processed, error 401: Unauthorized
Mai 13 13:26:57 coturn.optomed.de turnserver[3417]: 166: handle_udp_packet: New UDP endpoint: local addr 195.201.141.251:3478, remote addr 93.XXX.XXX.XXX:58929
Mai 13 13:26:57 coturn.optomed.de turnserver[3417]: 166: session 001000000000000002: realm <coturn.optomed.de> user <>: incoming packet message processed, error 401: Unauthorized
``` 

Coturn version: 4.5.0.7

**Comment by misi** [comment]
I made a quick test and It seems I can allocate port.
See
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
STUN or TURN URI: `turn:195.201.141.251`
TURN username: `demo`
TURN password: `demo`

**Comment by armin1402** [comment]
Hi Misi,

turn:195.201.141.251 is indeed working with credentials, but stun isn't. 

You can check it with Wireshark.

![grafik](https://user-images.githubusercontent.com/32325508/57620607-90b10380-7589-11e9-8e09-e5f95d0e122e.png)

![grafik](https://user-images.githubusercontent.com/32325508/57620650-ae7e6880-7589-11e9-8214-99d01c9d4a85.png)

Here an example stun-only:

![grafik](https://user-images.githubusercontent.com/32325508/57620884-5bf17c00-758a-11e9-9504-d7dc5694618c.png)

the latest entry with 93.x.x.x is my public IPv4 address.

**Comment by fadenb** [comment]
Any news on this issue?
Anything I can do to help debug/fix it?

**Comment by eakraly** [comment]
Is this issue still relevant @fadenb @armin1402 ?

**Comment by eakraly** [comment]
Inactive - closing
