### ISSUE TITLE
Feature request: configurable verbosity level

### ISSUE THREAD

**Issue by ppp0** [coturn/coturn#39]
We're using the lowest verbosity according to the conf file

```
[..]
# Uncomment to run TURN server in 'normal' 'moderate' verbose mode.
# By default the verbose mode is off.
#verbose

# Uncomment to run TURN server in 'extra' verbose mode.
# This mode is very annoying and produces lots of output.
# Not recommended under any normal circumstances.
#
#Verbose
[..]
```

It would be nice if one could use `TURN_LOG_LEVEL` (https://github.com/coturn/coturn/blob/e544a6c0f2578251f56d1da22a1b27a3ef12d9c4/src/apps/common/ns_turn_utils.h#L52) to set the verbosity level instead or additionally

We end up with log files of ca 275MB every day (easily compressable, though) right now.

Thank you for looking into the issue

**Comment by misi** [comment]
@ppp0  Could you please send a Pull Request with this enhancement. 
Unfortunately my efforts are over my limits, but I try to help..

**Comment by ppp0** [comment]
project expired, thanks for reaching out
