### ISSUE TITLE
TLS downgrade attack prevention?

### ISSUE THREAD

**Issue by tenge-amzn** [coturn/coturn#394]
Hi there,

I'm wondering if there is a way we can enable TLS_FALLBACK_SCSV?
https://datatracker.ietf.org/doc/rfc7507/

**Comment by tenge-amzn** [comment]
If I try to connect CoTurn TLS port with TLS1.1 and -fallback_scsv, the server does not fail the handshake. This should not happen.

`openssl s_client -connect my.turn.server:443 -fallback_scsv -tls1_1`

I'm wondering if we can add this functionality or is it in planning?

**Comment by misi** [comment]
@tenge-amzn 

It would be nice to have, but AFAIK noone works on it yet.
Please help us and make a Pull Request..

Thanks!

**Comment by Neustradamus** [comment]
@misi: Any news?

**Comment by eakraly** [comment]
I suggest to disable TLS and TLS 1.1 instead as this is a modern recommendation (and there are no known downgrade attacks against TLS 1.2 and TLS 1.3 - TLS_FALLBACK_SCSV does not work with 1.2 and 1.3)
