### ISSUE TITLE
Question: Certificate renewal?

### ISSUE THREAD

**Issue by christoofar** [coturn/coturn#402]
I'm a dope here... but I was wondering...

What does coturn do when a certificate expires?  If I have a letsencrypt script writing new .pem files over the ones that were loaded when coturn launched, does coturn pick it up on its own, or do I need to cycle (stop/start) turnserver?

**Comment by JarnoVgr** [comment]
Sending the `SIGUSR2` signal reloads certificates.

Relevant PR: https://github.com/coturn/coturn/pull/236

**Comment by RSATom** [comment]
Can you please clarify why this issue still not closed. If I understand correctly patch for reload certs by SIGUSR2 already merged. Is there still some issues with certs reload?

**Comment by cruizba** [comment]
> Can you please clarify why this issue still not closed. If I understand correctly patch for reload certs by SIGUSR2 already merged. Is there still some issues with certs reload?
> Thanks in advance.
> @misi

Yes that would be know to know @misi :). Seems like sending the signal is a really good option if possible to reload certificates.

**Comment by christoofar** [comment]
I'll close it myself.  I know how to send SIGUSR2 lol
