### ISSUE TITLE
Segfault in libc-2.12.so

### ISSUE THREAD

**Issue by ksaldiran** [coturn/coturn#403]
Hello,

I use turnserver-3.2.5.9 version and get below segfault error rarely. Maybe this issue was resolved next versions. Is there any idea or suggestion?

`May 24 23:47:02 nycinet-7 kernel: turnserver[24802]: segfault at c0 ip 00000034ede44009 sp 00007f94fe4643f0 error 4 in libc-2.12.so[34ede00000+18a000]`

**Comment by ksaldiran** [comment]
Any idea ?

**Comment by JarnoVgr** [comment]
The version you're using is from before 2014. Maybe consider updating? ;)

**Comment by ksaldiran** [comment]
Thanks for response
