### ISSUE TITLE
very high latency and no packet loss

### ISSUE THREAD

**Issue by AliBahramiEhsan** [coturn/coturn#414]
First of all, great work! thanks!
I configured and run my turnserver as follows (installing it via apt-get install coturn):
turnserver -a -o -v -n -p 3478  --no-dtls --no-tls -u someusername:somepassword -r "somerealm"
everything works fine and I checked it via trickle ICE service.
Problem is that when my turn server acts as a relay server, latency goes up. latency is became something between 5 to 10 seconds.
My priority is to make latency down, and quality is not my concern. What can I do for reducing latency?
P.S: I opened a[ stackoverflow question](https://stackoverflow.com/questions/56984735/using-turn-server-as-relay-makes-latency-high), but that wasn't very helpful.
Regards

**Comment by eakraly** [comment]
Hi @AliBahramiEhsan !
This question is 3 years old - sorry no one helped you
If you still have an issue please reopen

(My guess would be that your turnserver was overloaded or the application ended up using TCP which created latency_
