### ISSUE TITLE
wrong version number in 4.5.1.2?

### ISSUE THREAD

**Issue by localguru** [coturn/coturn#415]
Hi,

checked out from master (version 4.5.1.2), built a backport for Ubuntu/Bionic. Sylog shows

```
turnserver: 0: #012RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server#012Version Coturn-4.5.1.1 'dan Eider'
```

but should that be version 4.5.1.2? TURN_SERVER_VERSION is set to "4.5.1.1" in src/ns_turn_defs.h.

Ciao!

**Comment by misi** [comment]
@localguru Sorry for my late reply..
I am just continue how Oleg started it, 
so master is dev branch and we just tag releases.

- 4.5.1.1 is the latest release 
- 4.5.1.2 not yet released...
