### ISSUE TITLE
Flat-file user database has been removed

### ISSUE THREAD

**Issue by zbuf** [coturn/coturn#42]
Hi, I'm looking for some clarification on the removal of flat-file user database.

It was removed after version 4.2.3.1 in commit b9ef9f4c ("working on sqlite support") with no further comment.

What is the reason for its removal, and is it something which could be restored?

Are there any extra considerations that make flat-file functionality unusable? Or was it simply removed because it did not fit into the 'dbdrivers' hierarchy?

**Comment by mom040267** [comment]
Flat file database was replaced with sqlite database and will not be restored. It is too difficult to maintain.

**Comment by zbuf** [comment]
Is there some difficulty that is not immediately apparent? eg. threading.

Because whilst I am not yet familiar with the code, it it does seem that the flat file functionality could sit in a self-contained way within 'dbdrivers' hierarchy -- possibly much simpler than the database drivers, as there is only the reading of username-password to do.

If I were to look further into the code, which aspects make this difficult?

Thanks

**Comment by mom040267** [comment]
It would actually be more difficult, because you have to parse the file and somehow update the file. Sqlite is simple and efficient. If you need database that is contained in a single viewable file then use sqlite.

**Comment by zbuf** [comment]
Ok, that is just the work I would expect for any file reader. Is it valid to implement only a subset of the methods in _turn_dbdriver_t and will this prevent some key functionality of the server?

**Comment by mom040267** [comment]
I personally think that this not a good idea. If you want to do that then you will have to find out which parts you have to implement.
