### ISSUE TITLE
jokes, spelling and grammar errors

### ISSUE THREAD

**Issue by activedecay** [coturn/coturn#422]
The sheer volume of spelling and grammar mistakes in this project give me extreme anxiety and is making me feel suspicious of the project's quality. For example:

    the timestamp format is just seconds sinse 1970

From the config, it's not clear what this means:

    If the value is missed, then it means 'true'.

and this comment doesn't read well, making it seem like the line numbers should be swapped around
```
# --no-tls and --no-dtls mean that we are not trying to
# --no-auth means that no authentication to be used, 
# allow anonymous users. 
# start TLS and DTLS services.
```

Is this supposed to be a joke or reference to something?

    ==== Show him the instruments, Practical Frost: ====

There are a large number of other grammatical mistakes that make it hard to understand how to use the program.

**Comment by mom040267** [comment]
1) Grammar mistakes:

To our defense, we can admit that we got bad eduction in some shithole
countries and this is the reason why we are working as software engineers,
and we are not in respectable occupations like lawyers, hotel receptionists
or politicians.

2) Extreme anxiety:

We can recommend a doctor visit, before it comes to something serious. If
you feel yourself in immediate danger, call 911.

3) Jokes:

As foreigners, we are entitled to bad sense of humor and to unintelligible
jokes.

**Comment by activedecay** [comment]
well played <3

**Comment by bradleythughes** [comment]
To echo what @mom040267 said, the spelling/grammar mistakes you find can often be attributed to the fact that English is not the authors' first language. Feel free to submit a pull request to correct any errors you find. :)

With regards to jokes, the "Show him the instruments, Practical Frost" message seems to be a reference to [The First Law](https://en.wikipedia.org/wiki/The_First_Law), a fantasy book series. I'm tempted to read them to see if there's a hidden subtext. ;)

**Comment by OrangeDog** [comment]
These are perfectly clear

    the timestamp format is just seconds sinse 1970

Technically it should specify 1970-01-01T00:00:00.000Z or "the unix epoch" but it's obviously referring to standard unix timestamps. The literal reading of seconds since 1970-12-31T59:59:59.999Z is unlikely.

    If the value is missed, then it means 'true'.

If the value is omitted, the default value is 'true'.

It is however very hard to work out how to use the program, and many features that are claimed don't exist, don't work, or are insecure. See other issues for details.

**Comment by eakraly** [comment]
Nothing to add here

I think all previous developers and maintainers of coturn deserve no less than a standing ovation - empowering webrtc projects (and not only) around the world for the last 10 years.

Respekt!
