### ISSUE TITLE
Coturn over TLS with NGinx - baseline 

### ISSUE THREAD

**Issue by maxpavlov** [coturn/coturn#428]
Hello. 

So I have seen several discussions about running coturn behind NGINX proxy, and I have several questions.

1. Does running coturn using only TLS ports binds it to TCP mode? 
2. Is Coturn a mainly http-based API, since I've seen a suggestion to just do an SSL termination via nginx and route request to non-TLS Coturn ports using HTTP? Would that work? 

Thanks in advance.

**Comment by maxpavlov** [comment]
I found out that TURN is not an http-based protocol, however, SSL handshake can be be done even on TCP-mode connections in modern load balancers.

**Comment by karolyi** [comment]
@maxpavlov I'm also looking into terminating SSL with nginx on port 443/TCP for coturn, since nginx does the letsencrypt certificate refreshes and it has loads of other virtualhosts.

did you manage to find a way for that? I'm looking into the documentation and searching the web for solutions, but there doesn't seem to be one that solves this issue.

**Comment by karolyi** [comment]
@misi you might have something to add on this as well?

My goal would be to generate the SSL certificates with certbot and let nginx terminate the SSL connection itself (UDP/TCP), then forward an unencrypted one to coturn for usage. as it speaks HTTP, there would be `X-Forwarded-For` headers telling coturn the exact source IP.

is something like this possible? I don't have a dedicated extra IPv4 address for my machine for port 443, let alone coturn to have.

**Comment by misi** [comment]
@karolyi  I don't fully understand your question can you please clarify in a new isse? 
AFAIU You want to mix on one port 443 the  HTTP text based, and STUN binary protocol? It seems difficult problem.
Furthermore if we add that coturn could have also have an http based admin server listening on the same port, it could also adds more difficulty to it. I don't know how nginx could solve this but I am happy to discuss it further.

**Comment by karolyi** [comment]
@misi I'll create a new issue where we can talk about this, and describe the problem in a detailed way.
