### ISSUE TITLE
Coturn only to relay IPs that have previously done a STUN check

### ISSUE THREAD

**Issue by maxpavlov** [coturn/coturn#429]
I would like to have a TURN server to only service the IP's of two peers trying to connect if they have tried to initiate reflexive connectivity before and TURN is the last resort for them to connect. Right now I assume anyone who has the username and password will be able to right away relay traffic, right? Is there a way to only allow "those who need it" that prove it by previously requesting a STUN check? Thanks.

**Comment by 4ydx** [comment]
I believe that on the client side if you provide stun as well as turn the stun connection will most likely be given precedence when attempting connections.  If that fails, turn will be used.  

A more complex approach would be to try stun only and if there is a failure rely on turn.  Again it is all client side.

**Comment by misi** [comment]
@maxpavlov 
We don't have such functionality, and I think this setup needs to store sessions for long time to correlate the stun and the turn sessions. It adds more duty to server and more easy to overload server.
I agree with @4ydx that it is more depends on the client decision.
Of course we can implement in server side but than we need take care for a long time about sessions to be able to correlate.

In general proper implementation of Interactive Connectivity Establishment (ICE) should solve this issue.

**Comment by maxpavlov** [comment]
@4ydx , @misi thanks for the comments, guys. All makes sense.
