### ISSUE TITLE
is it possible to run coturn behind nginx proxy?

### ISSUE THREAD

**Issue by celevra** [coturn/coturn#43]
Hi,

is it possible to run coturn behind a nginx reverse proxy?
i have only 2 ip's on that maschine and need coturn to listen on port 443
so i want to configure nginx to forward name based to coturn, but no luck until now.
if that is known to working, can someone provide me a config?

regards

**Comment by mom040267** [comment]
No, it needs real clients with real IPs.

**Comment by partofthething** [comment]
Dang, 'cause yeah that's probably a relatively useful case for family servers these days. Everyone's home-page has SSL thanks to letsencrypt so web traffic goes through there. It'd be really slick to be able to redirect a subdomain's 443 traffic to localhost's 5349 or something. I'm up and running for all users except people behind corporate firewalls that block non-standard ports for this reason. At least I think that's what's going on.

**Comment by mom040267** [comment]
TURN specs do not have provisioning for that. That would be a custom
feature.

**Comment by ieatcat** [comment]
This is incorrect. Coturn can definitely run behind NGINX using stream. 

Learn more about it here: https://www.nginx.com/resources/admin-guide/tcp-load-balancing/#proxy_pass

**Comment by Zjemm** [comment]
or mayby ha-proxy?

**Comment by CraigZych** [comment]
@ieatcat 
Do you happen to have an example config that would capture turn traffic and forward appropriately while still directing regular https:// and wss:// to the correct port?

**Comment by adam-denny** [comment]
Did not try this with load balancing, but using the link posted by ieatcat I was able to proxy pass to turnserver in nginx and still route to my websockets. Not sure if this is the **best** way to do this, but it does work (inside nginx.conf):

```
http {
	(http and websocket routing in http block)
}

stream {
	server {
		listen 3478 udp;
		proxy_pass my.domain.com:3478;
	}

	server {
		listen 5349 udp;
		proxy_pass my.domain.com:5349;
	}
}
```

**Comment by ntinti** [comment]
Can confirm that streaming proxy works. I have to increase my "proxy_buffer_size" for video to work.

**Comment by mjsobrep** [comment]
@card-b and @ntinti Can you share a bit more about the system that you got to work. I have been trying to get coturn to run behind nginx, but can't seem to make a connection.

**Comment by GeovaneW96** [comment]
I could make it work behind nginx reverse proxy, problem is: stun gets the gateway machine's internal IP.

**Comment by acondura** [comment]
Could you please share your example of nginx proxy settings? I'm having trouble with mine not connecting.

**Comment by Ddvos** [comment]
I am also interested to see some settings in Nginx and coturn

**Comment by fabifrank** [comment]
Does only `udp` require to run coturn with `stream` in nginx so `tcp` turn is able to run behind reverse proxy with classic ssl termination?

**Comment by karolyi** [comment]
+1

**Comment by dhaminitinAltran** [comment]
Hi did anyone manage to do it if yes can you share the co-turn configuration and the ngnix conf file?

**Comment by Anurag2Yadav** [comment]
Hi @dhaminitinAltran ,
We will work together closely to resolve the issue !

**Comment by getarun** [comment]
Sorry to dig that up, but is there any progress yet? Tried something like https://github.com/coturn/coturn/issues/43#issuecomment-395486247 suggested, but i fail.
```
stream {

    map $ssl_preread_server_name $name {
        turn.domain.de turn_backend;
    }

    upstream turn_backend {
        server COTURN_IP:3478;
    }

    server {
        listen PROXY_IP:443 udp;
        proxy_pass $name;
        ssl_preread on;
       #access_log /var/log/proxy/access;
       error_log /var/log/proxy/error;
   }
}
```

**Comment by karolyi** [comment]
@getarun see #702
