### ISSUE TITLE
turnutils_uclients .... -y  fails on 127.0.0.1, but okay with 192.168.2.1

### ISSUE THREAD

**Issue by cameron-elliott** [coturn/coturn#431]
running 4.5.1.1 on ubu 1804

this is a mystery that has me scratching my head.

my local default-route ip is 192.168.86.4

WORKS GOOD: lost packets is zero
turnutils_uclient 192.168.86.4 -u user -w pass -n 1 -c -y

FAILS: "0: channel bind: error 403 (Forbidden IP)"
turnutils_uclient 127.0.0.1 -u user -w pass -n 1 -c -y

**Why does this fail on 127.0.0.1, but not 192.168.86.4 ??**

pcap/wireshark  screenshot ![image](https://user-images.githubusercontent.com/868689/63642727-af3e9480-c678-11e9-9498-121811f6859b.png)

pcap attached
[fail2pcap.zip](https://github.com/coturn/coturn/files/3537573/fail2pcap.zip)

server is running as (allowed-peer-ip makes no difference)
turnserver --no-stun -a -n -r fakerealm --allowed-peer-ip=127.0.0.1 -v

**Comment by thib-ack** [comment]
Hello,

Did you try `--allow-loopback-peers` parameter ?
However keep in mind this parameter creates a security vulnerability, so do not use in production !

Regards,
Thibaut.

**Comment by misi** [comment]
Yes it is disabled by default because of the security risk. 
Thanks @thib-ack for answering it..

**Comment by misi** [comment]
I think @cameron-elliott your question is answered, so I close this issue now. 
Please open a new issue if there is any remaining question. Thanks!
