### ISSUE TITLE
mic and camera only works saperate - not together

### ISSUE THREAD

**Issue by reschresch** [coturn/coturn#432]
Hello,
I try to work with OpenMeetings behind a NAT. I installed Coturn as a Turn-Server.
When I switch on the camera only my clients cann see the video.
When I switch on the microphone (without camera) it works perfectly.
But when I switch on both together nothing appears. No sound, no video, no error in the log.
But when the moderator (who want to stream his sound and video) is in the same Intanet as the server it works perfectly.
I try to forward all ports completely to my server - it doesnt work.

Have anybody an idea what I can try?

I use Ubuntu 18.04 and here is my turnserver.conf
verbose
fingerprint
use-auth-secret
static-auth-secret=SectretVeryVery
realm=webinar.XXXX.YY
log-file=/var/log/turn.log
min-port=49152
max-port=55000
proc-user=nobody
proc-group=nogroup

With best regards,
Resch

**Comment by misi** [comment]
So many things can cause this it is impossible to say it. Check your clients log.. 
For browser chrome:webrtc-internals, about:webrtc (for firefox)

**Comment by eakraly** [comment]
Hi @reschresch 
Do you still have the issue?
