### ISSUE TITLE
videocall only working if at least one device is on wifi

### ISSUE THREAD

**Issue by zecar** [coturn/coturn#434]
I've implemented webrtc videocall in a website. I've installed coturn as a turn server and I'm handling other signaling stuff via socket.io On frontend I'm using [SimplePeer](https://github.com/feross/simple-peer).

The problem:

I've tested this between

2 computers on the same wifi -> **working**

2 computers on different wifi -> **working**

one computer and one android phone on the same wifi -> **working**

one computer on wifi and one android phone on mobile data -> **working**

one computer and one iphone on the same wifi -> **working**

one computer on wifi and one iphone on mobile data -> **working**

one android phone and one iphone on same wifi -> **working**

one iphone and one iphone on same wifi -> **working**

one iphone on wifi and one android phone on mobile data -> **working** - not always

one android phone on wifi and one iphone on mobile data -> **working** - not always

one android phone and one iphone both on mobile data -> **not working**

one iphone and one iphone both on mobile data -> **not working**

I've also tried to make different accounts on coturn and assign an account for each device with the same results as above.

I've attached coturn server output (flag -v). I did 6 tests for mobile devices, after each test I restarted the coturn server. I also replaced all IP's with placeholders, for reasons.

All outputs with descriptive names are [here](https://gist.github.com/zecar/563b5d606adecc1260c6d8729d6b4239)

Also, I noticed that when the android is on mobile data, a 3rd peer is showing (the that is not replaced - it is a private ip)

Any ideas?

**Comment by DevJhns** [comment]
@zecar, hi have u found anything about this?

**Comment by misi** [comment]
What Browsers did you use?
Check the ICE logs in your browser:
Firefox
    about:webrtc
Chrome
   chrome:webrtc

**Comment by zecar** [comment]
@DevJhns , @misi 

sorry for this long delay.

It seems that RTC connections via 4g/3g networks were using ports outside the default range specified in coturn conf (49152 - 65535)

Opening all ports solved the problem and now it works every time on all browsers including android and ios (on ios only safari works)

**Comment by ytkang** [comment]
@zecar can you share your running command for coturn turnserver? I have same issue but It is not working after opening all ports for UDP & TCP
