### ISSUE TITLE
Security of STUN server

### ISSUE THREAD

**Issue by Chandramouli-P** [coturn/coturn#435]
Hello,

I am setting up two different servers for STUN and TURN respectively. I understand that we will provide user name and password along with TURN server URL in the application. This provides some security. But, what about STUN server? When we are using STUN server, we are providing only STUN server URL with port number, with out credentials. I haven't seen anywhere that STUN uses user name and password. Is it possible to create authentication mechanism for STUN server? 

Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Any update would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by paulvi** [comment]
Please ask on Stackoverflow and share URL here

**Comment by Chandramouli-P** [comment]
Hello, 

Please find the below URL:

**https://softwarerecs.stackexchange.com/questions/69080/security-of-stun-server**

Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Any update would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by paulvi** [comment]
you should be keeping asking the question, 
but breaking it and rephrasing. E.g. separate question for every ? sign.
When you just copy-pasted it into SO, it was not even clear what software you are using,   
and what you have tried already.

**Comment by misi** [comment]
See STUN/TURN RFC

>Is it possible to create authentication mechanism for STUN server?

Yes, but it is not implemented in WebRTC. 
It is less computing effort needed when you answer a STUN request without auth, 
than when you authenticate such request.

**Comment by paulvi** [comment]
Don't talk about sacrifice security because of computing power,  
those words could pass 10-20 years ago.

Now all communication solutions must be secure.  
Look the way browsers have changed last 1-2 year.

**Comment by misi** [comment]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1270514
 *  https://tools.ietf.org/html/rfc5389#section-13  
    it states:
```
    "It SHOULD NOT utilize the short-term or long-term credential mechanism. This is because the work involved in authenticating the request is more than the work in simply processing it."
```

**Comment by misi** [comment]
All in all in my opinion this is not coTURN issue, and you should open or if already exists star or vote the issue on your browser issue tracker.

**Comment by NoverNobida** [comment]
I find that there is a flag `--secure-stun`, and document said "Require authentication of the STUN Binding request". I add it but I don't know how to authenticate it. With option `--user <user:password>`? I tested it but it didn't work.

**Comment by ggarber** [comment]
There is support in coturn but the WebRTC browsers don't support it as explained above: https://github.com/coturn/coturn/issues/435#issuecomment-547294271

Closing unless somebody disagrees.
