### ISSUE TITLE
Installation failed turnserver-4.5.0.3-CentOS7.1-x86_64.tar.gz epel-release-7-5.noarch.rpm missing

### ISSUE THREAD

**Issue by parnamis** [coturn/coturn#44]
Installation of above RPM fails.

turnserver-4.5.0.3]# ./install.sh
Loaded plugins: fastestmirror, priorities
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
base
                                         | 3.6 kB  00:00:00
centos-7-updates
                                         | 2.5 kB  00:00:00
epel-7
                                         | 4.3 kB  00:00:00
extras
                                         | 3.4 kB  00:00:00
updates
                                         | 3.4 kB  00:00:00
(1/5): epel-7/updateinfo
                                         | 523 kB  00:00:00
(2/5): epel-7/primary_db
                                         | 4.0 MB  00:00:00
(3/5): centos-7-updates/primary_db
                                         |  27 MB  00:00:00
(4/5): extras/7/x86_64/primary_db
                                         | 117 kB  00:00:01
(5/5): updates/7/x86_64/primary_db
                                         | 4.1 MB  00:00:03
Determining fastest mirrors
 * base: mirror.5ninesolutions.com
 * extras: mirror.5ninesolutions.com
 * updates: mirror.5ninesolutions.com
Package wget-1.14-10.el7_0.1.x86_64 already installed and latest version
Nothing to do
--2016-05-03 17:36:43--
http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
Resolving download.fedoraproject.org (download.fedoraproject.org)...
2604:1580:fe00:0:dead:beef:cafe:fed1,
2610:28:3090:3001:dead:beef:cafe:fed3, 2a00:d1a0:1::131, ...
Connecting to download.fedoraproject.org
(download.fedoraproject.org)|2604:1580:fe00:0:dead:beef:cafe:fed1|:80...
connected.
HTTP request sent, awaiting response... 302 Found
Location: http://mirror.sfo12.us.leaseweb.net/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
[following]
--2016-05-03 17:36:43--
http://mirror.sfo12.us.leaseweb.net/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
Resolving mirror.sfo12.us.leaseweb.net
(mirror.sfo12.us.leaseweb.net)... 2605:fe80:2100:b001::5187,
209.58.135.187
Connecting to mirror.sfo12.us.leaseweb.net
(mirror.sfo12.us.leaseweb.net)|2605:fe80:2100:b001::5187|:80...
connected.
HTTP request sent, awaiting response... 404 Not Found
2016-05-03 17:36:44 ERROR 404: Not Found.

Its a problem with
http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm,
which has been removed from mirroring sites and new version
epel-release-7-6.noarch.rpm has been uploaded, requires correction in install.sh

**Comment by mom040267** [comment]
will be fixed in the next build

**Comment by agol** [comment]
Since CentOS 7 includes `epel-release` package to configure EPEL yum repo, would it make sense not to hardcode the rpm for it but just do:
```sh
yum -y install epel-release
```
in CentOS 7 install script for coturn?

**Comment by parnamis** [comment]
That's right in ./install.sh.

**Comment by mom040267** [comment]
I'll check it.

Thanks
Oleg

**Comment by mom040267** [comment]
fixed in 4.5.0.4
