### ISSUE TITLE
does coturn need two public ip ？ 

### ISSUE THREAD

**Issue by feiyue1206** [coturn/coturn#440]
I use coturn and webrtc to establish p2p vedio communication. I install and configure coturn as readme, and it works , both with STUN and TURN.

I do some research on STUN, and find STUN need two public ip. In coturn configure file i does not configure external-ip, so I wonders. 
Does coturn need two public ip ? if so, how to configure it ?

https://stackoverflow.com/a/8373718/10058131
the link says " the second IP is only needed for determining NAT type (i.e. diagnostics and debugging), not for actual hole punching.", so i think coturn can offer STUN function with only one public IP. 

Am I right ? thanks for any share

############
my configure file is as following:

listening-port=3478
tls-listening-port=5349
verbose
lt-cred-mech
user=111:12345678
channel-lifetime=360
stale-nonce=240
realm=test
log-file=/coturn/logs/turn.log
cert=/coturn/examples/etc/turn_server_cert.pem
pkey=/coturn/examples/etc/turn_server_pkey.pem
mobility
cli-password=12345678
no-stdout-log

**Comment by feiyue1206** [comment]
I do some test about "aux-server" and "external-ip" in config file.

I set "external-ip" = public ip of host, it works. and i deploy coturn on another machine with different public. all setting are same except  "external-ip". two coturns work fine seperately.  so in one server 1 i set "aux-server"=ip2:3478.

but i does find the port that can work. i try 3478/5349/33478. when i start coturn on server1, it shows error info as following:
bind: Cannot assign requested address
Cannot bind local socket to addr: Cannot assign requested address
0: ERROR: Fatal final failure: cannot bind TLS/TCP listener socket to addr X.X.X.X:3478

After a while coturn on server 1 shut down.

Could anyone help ? thanks a lot

**Comment by chenxinlong** [comment]
rfc 3489 : need 2 public ip to determining the NAT type.
rfc 5389 : it depends on the client's NAT traversal solution.

**Comment by feiyue1206** [comment]
> rfc 3489 : need 2 public ip to determining the NAT type.
> rfc 5389 : it depends on the client's NAT traversal solution.

so does coturn nedd 2 public ip ? if it need, how to configure it .
thanks

**Comment by chenxinlong** [comment]
As far as I understand, it depends on the coturn client's NAT traversal solution. 

If your turn client only implements the rfc 3489, then your turnserver need 2 public ip. If not, then you may doesn't need 2 public ip.

Sorry I haven't configure 2 public ip.

**Comment by feiyue1206** [comment]
> As far as I understand, it depends on the coturn client's NAT traversal solution.
> 
> If your turn client only implements the rfc 3489, then your turnserver need 2 public ip. If not, then you may doesn't need 2 public ip.
> 
> Sorry I haven't configure 2 public ip.

what do you mean by coturn client and server ?

In my opinion, coturn works as server, and all users are client.
If so, i cannot decide what type the clients are.

**Comment by feiyue1206** [comment]
adding two public ip of 'listening-ip' in config works for rfc3489

**Comment by misi** [comment]
2 public IP is only required if you want to discover NAT type.

WebRTC don't use this functionality, so I guess you don't need this function. 
In general you need only one global IP. 

Of course you can use multiple IP to have an IP pool.
You can distinguish client from relay address there could be a use case for two or more IP.

**Comment by feiyue1206** [comment]
> You can distinguish client from relay address there could be a use case for two or more IP.

may you explain this in detail ? giving an example is better

thanks a lot

**Comment by misi** [comment]
Your client connect to x.x.x.x, so turn server ip

But relay address is y.y.y.y, so you will allocate ports on this ip
address. And you will communicate with peers using this IP.

Client ====(x.x.x.x) coTURN (y.y.y.y) ------- Peer

Misi

2019. 10. 12. 4:43 keltezéssel, song írta:

**Comment by feiyue1206** [comment]
thanks a lot @misi
