### ISSUE TITLE
[Error] SQLite connection was closed

### ISSUE THREAD

**Issue by chanduthedev** [coturn/coturn#441]
When I run below command, getting this error. Do I need to do any more configuration before running below command? please help.
`turnadmin -a -u adminuser -r admin.org -p admin123`

Thanks in Advance.

**Comment by chanduthedev** [comment]
Resolved this issue. Need to specify db path to this command with --db option. It will create a user in the db.

```turnadmin -a --db /usr/local/var/db/turndb -u adminuser -r admin.org -p admin123 ```

Thanks for your help.

**Comment by xml4cn** [comment]
turnadmin -a --db /usr/local/var/db/turndb -u adminuser -r admin.org -p admin123
0: log file opened: /var/tmp/turn_17088_2019-12-04.log
0: SQLite connection was closed.

**Comment by jespertheend** [comment]
try with `sudo`, that did the trick for me
