### ISSUE TITLE
Need Explanation for the TURN Sessions on Web

### ISSUE THREAD

**Issue by zhoub** [coturn/coturn#443]
As we know the HTTP page displays the TURN sessions below
```
N | Session ID | User | Realm | Origin | Age, secs | Expires, secs | Client protocol | Relay protocol | Client addr | Server addr | Relay addr (IPv4) | Relay addr (IPv6) | Fingerprints | Mobile | TLS method | TLS cipher | BPS (allocated) | Packets | Rate | Peers
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

```

Is there any explanation for these fields ? Thanks !

**Comment by misi** [comment]
Sorry can you please detail your question. 
Unfortunately I don't understand it.

**Comment by misi** [comment]
See the source code and STUN/TURN RFC, it will help you to explain to understand the fields.
I don't think there is such detailed documentation about these fields.

In nutsell
```turn client(client addr) === (server addr)turn server(relay addr) ----- peer```
* Session ID 
turn session internal id
* User 
Auth user name
* Realm 
Auth realm set on server side used in auth HMAC key creation.
* Origin
Used in an old discontinued IETF draft, so ignore it.
* Age, secs
Age of session
* Expires, secs
Expiry /timeout
* Client protocol
tcp/udp/tls/dtls/sctp etc. 
* Relay protocol
udp/tcp
* Client addr 
Client address
* Server addr 
Server addres this session use
* Relay addr (IPv4)
ipv4 relay ip address
* Relay addr (IPv6) 
ipv6 relay ip address
* Fingerprints
Fingerprint is on or not see https://tools.ietf.org/html/rfc5389#section-8
* Mobile
TURN extension: https://tools.ietf.org/html/draft-wing-mmusic-ice-mobility-07
* TLS method
TLS settings
* TLS cipher 
TLS settings
* BPS (allocated) 
Allowed/allocated bit rate upper limit
* Packets
actual packet count
* Rate
Actual packet rate
* Peers
Peer addresses

**Comment by zhoub** [comment]
Got it, thanks !
