### ISSUE TITLE
Unable to Get ICE TCP Relay Candidate from Coturn Server

### ISSUE THREAD

**Issue by O-Jack** [coturn/coturn#447]
I'm currently trying to set up a TURN server using Coturn on CentOS 7 for a WebRTC application. I'd like for the application to relay over TCP due to the strict firewall settings my organization uses. I'm testing the ICE candidate gathering using the WebRTC Trickle ICE tool (https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/), but the only relay candidate I'm getting back is a UDP relay candidate.

This is the case even if I specify "?transport=tcp" in the TURN server URL (e.g., turn:server-ip-address:3478?transport=tcp). After looking at a Wireshark capture, I noticed that even though my WebRTC client is connecting to the TURN server over TCP, the REQUESTED-TRANSPORT attribute in the Allocate Request is still UDP. Does anyone know why this might be the case? How can I configure my Coturn server to return TCP relay candidates?

I'm currently using the following configurations in my turnserver.conf file...

 ```
   listening-port=3478
    alt-listening-port=3479
    lt-cred-mech
    user=test:test
    realm=test-realm
    fingerprint
    verbose
    no-tls
    no-dtls
    log-file=/var/log/turn/turn.log
```
...and the following peer connection configuration in my WebRTC client.

```
peerConn = new RTCPeerConnection({
    constraints: {
            audio: true,
            video: false
    },
    // Testing ICE candidate for coturn
    iceServers: [{
            urls: "turn:10.5.58.239:3478?transport=tcp",
            username: "test",
            credential: "test"
    }],
    iceTransportPolicy: "any"
});
```
And this is the response I'm getting back using the Trickle ICE tool.

```
Time    Component   Type    Foundation  Protocol    Address Port    Priority
0.003   rtp host    547260449   udp 10.0.2.15   49165   126 | 30 | 255
0.349   rtp relay   3606296988  udp 10.5.58.239 56410   1 | 30 | 255
0.349   Done
0.355
```

**Comment by misi** [comment]
Which browser do you use?

**Comment by O-Jack** [comment]
I'm using Google Chrome v74

**Comment by misi** [comment]
Is the same issue with firefox? Can you test it?

**Comment by O-Jack** [comment]
I've tried using Firefox, and I get the same behavior. After a bit more investigation, it seems like may not be a Coturn configuration issue. Rather, it's that Chrome and Firefox WebRTC clients do not support TCP candidate allocation on a TURN server (https://groups.google.com/forum/#!topic/turn-server-project-rfc5766-turn-server/I867K4sVQZI).

**Comment by misi** [comment]
The question is what you want to achieve?
Normally relay servers use UDP between the TURN server and the peer. 
If I am correct You set the transport between Client and TURN server to TCP with the transport option.

**Comment by misi** [comment]
This (https://groups.google.com/forum/#!topic/turn-server-project-rfc5766-turn-server/I867K4sVQZI) explains that WebRTC not implement TCP allocations.
```
(Chrome) --TURN over TCP--> (TURN server) --RTP/UDP--> (Chrome)

or

(Chrome) --TURN over TCP--> (TURN server A) --RTP/UDP--> (TURN server B) --TURN over TCP-->(Chrome)
```
I think there is no open question left here, so I close it. 
Please let me know if you think I should keep it still open, and I will reopen it.

**Comment by Payetus** [comment]
Can you explain the second scenario better?
