### ISSUE TITLE
Logfiles dont write to correct folder

### ISSUE THREAD

**Issue by asciirory** [coturn/coturn#45]
My config is set to /var/log for the logfiles, but the turnserver logs keep going to /var/tmp
Using CoTurn 4.5.0.4

**Comment by mom040267** [comment]
That's probably because you are running turnserver not as a root, but you need root privileges to write to /var/log.

**Comment by asciirory** [comment]
Thanks, I think that did it.
I was told it was running under root, but when I did ps –ef I found it was not.

Regards
Rory McDonald
