### ISSUE TITLE
Coturn not working on raspbian to external Nextcloud

### ISSUE THREAD

**Issue by fuanegua** [coturn/coturn#451]
I would like to use coturn on my Raspberry Pi in my private network for my external Netcloud Talk (installed on hosted webserver).

The coturn server seems to work fine, The ports a forwarded, the DynDNS works fine but Nextcloud Talk can’t use it. And I can’t find the error log to see the problem.

```
listening-port=3478
tls-listening-port=5349
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=[my_secret]
realm=[my_domain]
total-quota=100
bps-capacity=0
stale-nonce
cert=/etc/letsencrypt/live/[my_domain]/fullchain.pem
pkey=/etc/letsencrypt/live/[my_domain]/privkey.pem
dh-file=/etc/ssl/private/dhparam.pem
cipher-list="ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AES:RSA+3DES:!ADH:!AECDH:!MD5"
no-loopback-peers
no-multicast-peers
cli-password=qwertz
```

The coturn status is:

```
coturn.service - coTURN STUN/TURN Server
   Loaded: loaded (/lib/systemd/system/coturn.service; enabled; vendor preset: e
   Active: active (running) since Thu 2019-10-10 14:11:47 CEST; 3s ago
     Docs: man:coturn(1)
           man:turnadmin(1)
           man:turnserver(1)
  Process: 29708 ExecStart=/usr/bin/turnserver --daemon -c /etc/turnserver.conf 
  Process: 29712 ExecStartPost=/bin/sleep 2 (code=exited, status=0/SUCCESS)
 Main PID: 29711 (turnserver)
    Tasks: 9 (limit: 2077)
   Memory: 4.1M
   CGroup: /system.slice/coturn.service
           └─29711 /usr/bin/turnserver --daemon -c /etc/turnserver.conf --pidfil

Okt 10 14:11:45 pi systemd[1]: Starting coTURN STUN/TURN Server...
Okt 10 14:11:47 pi systemd[1]: Started coTURN STUN/TURN Server.
```

Where can I find the log files? And what could be the problem? Thanks for any help.

**Comment by misi** [comment]
Do you forward all ports? 
You need static global ip on turn server side. See external-ip or -X

**Comment by fuanegua** [comment]
Thanks for your post!
I use freeDNS with a domain forwarding to the raspi. On the same system a Nextcloudpi is running and accessible from outside via 443/80.
So I opened the ports 5349 and 3478. So it should work as well.

The other Nextcloud I would like to use with coturn comes from outside. I can’t find any error log. Is there a way to test it from outside with error logging?

The thing is, the external Nextcloud is running on my hoster’s webspace. So I don’t have any root access. That’s why I installed coturn on my Raspbian Pi.

**Comment by misi** [comment]
I don't think it will work with dynamic ip.
You need to specify your external ip in coturn config.

You need to forward media ports too!

You need to see the logs in your browser.
For chrome
- chrome:webrtc-internals
For firefox
- about:webrtc

Read more about ICE protocol

**Comment by misi** [comment]
I think I answered your questions. No new issue raised so I close it now.
Please let me know if I can help you more in a new issue, 
or I can reopen this also if you like.
