### ISSUE TITLE
Cannot find credentials of user 

### ISSUE THREAD

**Issue by chanduthedev** [coturn/coturn#452]
When I use username/password, coturn server is working fine. But when I use use-auth-secret, getting 'Cannot find credentials of user ' error. Below are my configuration details.

turnserver.conf:
---------------
```
listening-port=3478    
use-auth-secret
#lt-cred-mech //this is for username/password usecase
realm=example.com
```
Users from DB:
---------------
```
[coturn-master]$ sudo ./bin/turnadmin -l
1234[example.com]
chandra[example.com]
```
Secret from DB:
---------------
```
[coturn-master]$ sudo ./bin/turnadmin -S       
coturn[example.com]
```

I started coturn server using `turnserver -v`.
Please help me on this.
Thanks in advance.

**Comment by misi** [comment]
Read this:
https://www.ietf.org/proceedings/87/slides/slides-87-behave-10.pdf

If you use REST (shared secret auth) then on Client side 
use as username a timestamp, 
and as password the hashed username (hashed with shared secret)..

The classic username + password and REST (shared secret auth) can't work on the same time!

**Comment by chanduthedev** [comment]
Thank you @misi for the response. Its working fine after starting the server as `turnserver -v -r example.com --use-auth-secret`. 

But earlier it was not working and got 'Cannot find credentials of user' when I started the server `turnserver -v -r example.com --oauth --use-auth-secret`.

Can you please explain why it was not working when oauth, use-auth-secret both options enabled. if this is the expected behavior, can you please add some warning messaging when starting the server with these two options at the same time.

**Comment by chanduthedev** [comment]
Hi @misi need one more clarification. From the below link pdf 
https://www.ietf.org/proceedings/87/slides/slides-87-behave-10.pdf
in page15, it talks about message integrity, in that what is M refers to? I understood everything, except 'M' in that equation. Can you please explain what is M in that message integrity?
```
MESSAGE-INTEGRITY:
HMAC(M, MD5( "1375043478:abcd1234:bar.com:<hmac-password>"
) )
```

**Comment by misi** [comment]
@chanduthedev 
"M" refers to the stun message.

>Can you please explain why it was not working when oauth, use-auth-secret both options enabled. if this is the expected behavior, can you please add some warning messaging when starting the server with these two options at the same time.

Good point we need to add a warning! These couldn't work in the same time..
* OAuth use SHA1 20 byte secret key
* REST/ use-auth-secret use SHA1(MD5(key)) so MD5 output is 16 byte so SHA1 key is 16 byte

**Comment by chanduthedev** [comment]
Thank you @misi for the quick reply.  use-auth-secret is working fine with turnutils_uclient utility command `turnutils_uclient -v -y -u chandu -W secret 127.0.0.1`. This command requires username and secret, so its working fine.
Can you please let me know how to use secret key in https://easyrtc.com/docs/  client. I am using easyrtc and want to integrate coturn with easyrtc. 

With long term secret key(Username/Password): 
----------------------------------------------
 Just sending username and password from easrtc client is working fine.


With use-auth-secret: 
----------------------
I am passing just username and it is failing.  Do I need to pass hmac password as a password in easryrtc client?
please help on this?

**Comment by misi** [comment]
You need to pass the shared key to uclient in case of use-auth-secret. 
It will generate timestamp to username and password on the fly.

**Comment by chanduthedev** [comment]
Yes I am passing shared key and it was working fine. My question is configuring `use-auth-secret` option in webrtc client. for the username password, we will do as below
```
// Testing ICE candidate for coturn
    iceServers: [{
            urls: "turn:127.0.0.1:3478?transport=tcp",
            username: "chandu",
            credential: "test"
    }]
```
how to do in case  of  `use-auth-secret` scenario? Is it in the form of below? passing hmac of username and secret as a password?
```
    iceServers: [{
            urls: "turn:127.0.0.1:3478?transport=tcp",
            username: "chandu",
            credential: "hmac(username, secret)"
    }]
```

**Comment by misi** [comment]
In case of use-auth-secret for easyrtc you need to generate the 
- username(unix timestamp+expiry!): e.g. 1572377576:abcd123 
and 
- the HMAC(username, shared secret) as password.

**Comment by chanduthedev** [comment]
Thank you @misi for quick reply. Yes I sent as below. username is `1572435255:chandra` and password as hmac(1572435255:chandra,new-coturn) which is 63d09dae63b43b22d51991dee1a0e5cb. 
But still I am getting  below error.
** ERROR: check_stun_auth: Cannot find credentials of user <1572435255:chandra>**

```
[                              
    {
      "url":"turn:127.0.0.1:3478?transport=tcp",
      "username":"1572435255:chandra",
      "credential":"63d09dae63b43b22d51991dee1a0e5cb"
    }
];
```
My username is **1572435255:chandra** and my secret is **new-turn**

Am I missing anything?

**Comment by misi** [comment]
hmac(1572435255:chandra,**new-coturn**) 
vs.  
my secret is **new-turn**
```php -r "echo hash_hmac('sha1', '1572435255:chandra', 'new-turn');"```
is 
```e7f434aeac00cce79c1a90d7a13e42eee1e87f19```

```php -r "echo hash_hmac('sha1', '1572435255:chandra', 'new-coturn');"```
is 
```a290bee54ab09ea4025c290845f0e5bf707147ea```

So 
1. check your hash alg that it is sha1.
2. which is your secret new-coturn or new-turn
3. Try to check server clock...
I don't see any other issue here.

**Comment by chanduthedev** [comment]
Sorry @misi  It was my bad, secret is  **new-turn**. Please see below command 
```
$ turnadmin -S
new-turn[example.com]
```
And thank you for your commands to find hmac. I was using md5 instead of sha1 earlier.
this time I sent as below. Still getting error. Any clue? I know there is nothing wrong. but I am clueless. So asking for help.
```
[                              
    {
      "url":"turn:192.168.1.15:3478?transport=tcp",
      "username":"1572435255:chandra",
      "credential":"e7f434aeac00cce79c1a90d7a13e42eee1e87f19"
    }
];
```
I started the server as `turnserver -v -r example.com --use-auth-secret` and no error messages.

Please see error logs below.
$ turnserver -v -r example.com --use-auth-secret
0: log file opened: /var/tmp/turn_14034_2019-10-30.log
0: WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
0: WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
0: 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.1.1 'dan Eider'
0: 
Max number of open files/sockets allowed for this process: 4096
0: 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 2000 (approximately)
0: 

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: DTLS 1.2 is not supported
0: TURN/STUN ALPN is not supported
0: Third-party authorization (oAuth) supported
0: GCM (AEAD) supported
0: OpenSSL compile-time version: OpenSSL 1.0.1e-fips 11 Feb 2013 (0x1000105f)
0: 
0: SQLite supported, default database location is /usr/local/var/db/turndb
0: Redis is not supported
0: PostgreSQL supported
0: MySQL supported
0: MongoDB is not supported
0: 
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: Domain name: 
0: Default realm: example.com
0: ERROR: 
CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
0: WARNING: cannot find certificate file: turn_server_cert.pem (1)
0: WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
0: WARNING: cannot find private key file: turn_server_pkey.pem (1)
0: WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
0: NO EXPLICIT LISTENER ADDRESS(ES) ARE CONFIGURED
0: ===========Discovering listener addresses: =========
0: Listener address to use: 127.0.0.1
0: Listener address to use: 192.168.1.15
0: =====================================================
0: Total: 1 'real' addresses discovered
0: =====================================================
0: NO EXPLICIT RELAY ADDRESS(ES) ARE CONFIGURED
0: ===========Discovering relay addresses: =============
0: Relay address to use: 192.168.1.15
0: =====================================================
0: Total: 1 relay addresses discovered
0: =====================================================
Cannot create pid file: /var/run/turnserver.pid: Permission denied
0: Cannot create pid file: /var/run/turnserver.pid
0: pid file created: /var/tmp/turnserver.pid
0: IO method (main listener thread): epoll (with changelist)
0: Wait for relay ports initialization...
0:   relay 192.168.1.15 initialization...
0:   relay 192.168.1.15 initialization done
0: Relay ports initialization done
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=0 created
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=1 created
0: IPv4. UDP listener opened on: 127.0.0.1:3478
0: IPv4. UDP listener opened on: 127.0.0.1:3479
0: IPv4. UDP listener opened on: 192.168.1.15:3478
0: IPv4. UDP listener opened on: 192.168.1.15:3479
0: Total General servers: 2
0: IO method (admin thread): epoll (with changelist)
0: IO method (auth thread): epoll (with changelist)
0: IO method (auth thread): epoll (with changelist)
socket: Protocol not supported
0: IPv4. TCP listener opened on : 127.0.0.1:3478
0: SQLite DB connection success: /usr/local/var/db/turndb
socket: Protocol not supported
0: IPv4. TCP listener opened on : 127.0.0.1:3478
socket: Protocol not supported
0: IPv4. TCP listener opened on : 127.0.0.1:3479
socket: Protocol not supported
0: IPv4. TCP listener opened on : 127.0.0.1:3479
socket: Protocol not supported
0: IPv4. TCP listener opened on : 192.168.1.15:3478
socket: Protocol not supported
0: IPv4. TCP listener opened on : 192.168.1.15:3478
socket: Protocol not supported
0: IPv4. TCP listener opened on : 192.168.1.15:3479
socket: Protocol not supported
0: IPv4. TCP listener opened on : 192.168.1.15:3479

**Comment by misi** [comment]
try to make a packet capture.

and debug with 
``gdb -p pid``

Add a break point here
https://github.com/coturn/coturn/blob/540ef5fd6e82faad0159ab24e2df92b4701cb62f/src/apps/relay/userdb.c#L535

**Comment by chanduthedev** [comment]
Thank you for the response @misi . I added break point and please see screenshot for that. Please suggest what to do.
<img width="1439" alt="Screenshot 2019-10-31 at 11 22 23 AM" src="https://user-images.githubusercontent.com/6205951/67916525-ef6a4800-fbd0-11e9-8146-fa40098f2fac.png">

FYI, i added lot of print statements to analyze the flow and found that **can_resume** and **postpone_reply** flags also play major role while checking for credentials in case use-auth-secret. Can you please elaborate on these two flags if possible.

**Comment by chanduthedev** [comment]
I captured packet and I could not see anything wrong in the stun message as well. Please see attached packet. 
<img width="1177" alt="Screenshot 2019-10-31 at 5 57 32 PM" src="https://user-images.githubusercontent.com/6205951/67937322-59521400-fc08-11e9-8428-dd70bd7f2b74.png">


Working scenario:
-----------
When I use uclient to send username and secret, working properly.

Not working scenario:
-------------
When I send a request from easyrtc client, getting **ERROR: check_stun_auth: Cannot find credentials of user <1572544327:coturn>**.

Above error is at line no. 3499 from the file name src/server/ns_turn_server.c. As per the code, if password is empty, then only this error occurs. But we are passing password, how password becomes empty?

And as per my understanding coTurn server will re-calculate message integrity and check with message integrity from STUN message to validate credentials. I am suspecting, the calculation of message integrity was not same in easyrtc and coTurn server due to that it was failing.

Please let me know if I my understanding is incorrect.

**Comment by misi** [comment]
How you calculate the timestamp you use in username?
It should be an expiry unix timestamp so actual (unixtimestamp(UTC) + lifetime ) 
is it = 1572544327 in your case?

**Comment by chanduthedev** [comment]
1572544327  is future time timestamp, calculated yesterday + three days, it will be valid till tomorrow 1st Nov.

**Comment by misi** [comment]
Sorry I should check it, and I could realize it earlier that it is a future timestamp.. :(

Can you break here and print out result:
https://github.com/coturn/coturn/blob/540ef5fd6e82faad0159ab24e2df92b4701cb62f/src/apps/relay/userdb.c#L549

And in gdb print out:
```
p turn_time_before(ts, ctime)
next
next
next
next
next
next
next
next
next
next
next
next
next
next
next
next
next
next

```

**Comment by chanduthedev** [comment]
I tried as per your suggestion and please see attached screen shot. Got  **No symbol "turn_time_before" in current context.** errror when I did `p turn_time_before(ts, ctime)` in gdb. After 18 next's also got same error.

<img width="1651" alt="Screenshot 2019-10-31 at 6 56 33 PM" src="https://user-images.githubusercontent.com/6205951/67941324-5a873f00-fc10-11e9-86c6-06c07e156535.png">

**Comment by misi** [comment]
Ok so timestamp works fine.. 
If you go to next steps can you share the output..

**Comment by misi** [comment]
Strange I am getting out of ideas.
You use `static-auth-secret` in config file? 
Or you read it from db where in `turn_secret` table where you added realm(example.com), and shared secret?
Which coturn version? 4.5.1.1?

Which browser do you use Strange it should work if timestamp is matched and key and realm is

**Comment by chanduthedev** [comment]
Hi @misi please see below config details.

**coturn**: Version Coturn-4.5.1.1 'dan Eider'
**Browser**: Chrome (Version 77.0.3865.90 (Official Build) (64-bit))
**Secret Key**: Reading secret key from db table turn_secret table and started the coturn server with command  `turnserver -v -r example.com --use-auth-secret`. Never using conf file.

I use same browser with different tabs for caller and callee. With same setup `lt-cred-mech` (i.e. username/password) was working fine. So trying  `use-auth-secret` option with same setup.

**Comment by chanduthedev** [comment]
Hi @misi , I found one major difference in working scenario and not working scenario.
In working scenario, flow was hitting in file **src/client/ns_turn_msg.c** at line no **1914** where as not working scenario, flow was hitting line no **1912** in the same file. This was basically mismatching message integrity.
    Can you please help me on how message integration was calculated. UIclient is working fine because message integrity calculation and verification both happening in coturn server code only. Whereas in non working scenario, message integration calculation was happening in webrtc client(easyrtc in our case) and verification happening in coturn which was causing the issue.

**Comment by chanduthedev** [comment]
Hi @misi finally this issue got resolved, It was working fine now. The problem is that I am passing password value as hmac(username, secret), but we need to pass base64_encode(hmac(username, secret)).

Earlier I was creating a hmac using `echo -n "1573154558:coturn" | openssl dgst -sha1 -hmac secret` and using this value as password which causing message integrity mismatch.

Now I am using below JS code for password generation and it was working fine. I found this code [here](https://stackoverflow.com/questions/35766382/coturn-how-to-use-turn-rest-api)
```
var crypto = require('crypto');

function getTURNCredentials(name, secret){
    var unixTimeStamp = parseInt(Date.now()/1000) + 24*3600,
        username = [unixTimeStamp, name].join(':'),
        password,
        hmac = crypto.createHmac('sha1', secret);
    hmac.setEncoding('base64');
    hmac.write(username);
    hmac.end();
    password = hmac.read();
    return {
        username: username,
        password: password
    };
}
```

Thank you so much for your help.
