### ISSUE TITLE
Coturn does not care about its configuration file

### ISSUE THREAD

**Issue by YugiFanGX** [coturn/coturn#454]
I am using coturn 4.5.1.1-1.1 and have set up the /etc/turnserver.conf file.
However, restarting coturn does close the default port, nor opens the tls port as I entered.
I also tried to reboot, no workaround.

When killing the process listening on the default port 3478 and launching it again using 
` sudo turnserver -c /etc/turnserver.conf` I am able to to get a tls port open.
But still the default port 3478 is available. If I reboot, my actions are gone, and I have to do it once more.

How can I get coturn to fully accept my config file? (already at bootup)

**Comment by misi** [comment]
If it is not stuck then it should work and read config. 
Use systemctl to restart it.
