### ISSUE TITLE
Is coturn turnserver supporting group call?

### ISSUE THREAD

**Issue by ytkang** [coturn/coturn#458]
Is it just for 1:1 call or supporting group call? 
if it supports, how many people can be added a group?

is this value TURN_PERMISSION_ARRAY_SIZE the max people per a group?

**Comment by benbro** [comment]
No, a turn server doesn't do group calls. From [Wikipedia](https://en.wikipedia.org/wiki/Traversal_Using_Relays_around_NAT)
> Traversal Using Relays around NAT (TURN) is a protocol that assists in traversal of network address translators (NAT) or firewalls for multimedia applications.

**Comment by ytkang** [comment]
@benbro thanks
