### ISSUE TITLE
Turn   error 401: Unauthorized

### ISSUE THREAD

**Issue by jzallimi** [coturn/coturn#459]
Please help me 

matrix config:
turn_uris: ["turn:chat.trinissoft.com:3478?transport=tcp","turn:chat.trinissoft.com:3478?transport=udp"]
turn_shared_secret: "W85lGGbslu9iHFeUHdH3NfoLp3voXKo8lI7RoUidOV3wiJmk7aZ3mylONrprWK3M"
turn_user_lifetime: "86400000"

turn_allow_guests: True

error:

 session 001000000000000001: realm <chat.trinissoft.com> user <juli>: incoming packet message processed, error 401: Unauthorized
8: handle_udp_packet: New UDP endpoint: local addr 5.189.144.69:5349, remote addr 80.78.65.91:61203
8: session 001000000000000002: realm <chat.trinissoft.com> user <>: incoming packet BINDING processed, success
8: session 001000000000000002: realm <chat.trinissoft.com> user <>: incoming packet message processed, error 401: Unauthorized
8: ERROR: check_stun_auth: Cannot find credentials of user <juli>
8: session 001000000000000002: realm <chat.trinissoft.com> user <juli>: incoming packet message processed, error 401: Unauthorized
 error 401: Unauthorized5: session 001000000000000001: realm <chat.trinissoft.com> user <>: incoming packet BINDING processed, success
5: session 001000000000000001: realm <chat.trinissoft.com> user <>: incoming packet message processed, error 401: Unauthorized
65: session 001000000000000001: closed (2nd stage), user <juli> realm <chat.trinissoft.com> origin <>, local 5.189.144.69:5349, remote 80.78.65.91:61196, reason: allocation watchdog determined stale session state
68: session 001000000000000002: closed (2nd stage), user <juli> realm <chat.trinissoft.com> origin <>, local 5.189.144.69:5349, remote 80.78.65.91:61203, reason: allocation watchdog determined stale session state

listening-port=3478
tls-listening-port=5349
listening-ip=5.189.144.69
verbose
lt-cred-mech
user=juli:mypassword
use-auth-secret
static-auth-secret=W85lGGbslu9iHFeUHdH3NfoLp3voXKo8lI7RoUidOV3wiJmk7aZ3mylONrprWK3M
server-name=chat.trinissoft.com
realm=chat.trinissoft.com
cert=/etc/letsencrypt/live/chat.trinissoft.com/fullchain.pem
pkey=/etc/letsencrypt/live/chat.trinissoft.com/privkey.pem
#no-stdout-log
#log-file=/var/log/turnserver/turn.log
#simple-log
#pidfile="/var/run/turnserver/turnserver.pid"
mobility
no-tlsv1
no-tlsv1_1

**Comment by misi** [comment]
Hi,

Use either lt-cred-mech (user:password) or use-auth-secret, both
couldn't be used the in the same time.

  * lt-cred-mech
    user=juli:mypassword
  * use-auth-secret
    static-auth-secret=W85lGGbslu9iHFeUHdH3NfoLp3voXKo8lI7RoUidOV3wiJmk7aZ3mylONrprWK3M


Misi

2019. 10. 30. 11:40 keltezéssel, jzallimi írta:

**Comment by jzallimi** [comment]
When i use to call with 4g :
Call connectiong and nothing happend ???

7: session 001000000000000001: new, realm=<chat.trinissoft.com>, username=<1572519615:@erli:chat>, lifetime=600
7: session 001000000000000001: realm <chat.trinissoft.com> user <1572519615:@erli:chat>: incoming packet ALLOCATE processed, success
8: session 001000000000000001: peer 10.29.12.129 lifetime updated: 300
8: session 001000000000000001: realm <chat.trinissoft.com> user <1572519615:@erli:chat>: incoming packet CREATE_PERMISSION processed, success
17: session 001000000000000001: realm <chat.trinissoft.com> user <1572519615:@erli:chat>: incoming packet BINDING processed, success
25: session 001000000000000001: refreshed, realm=<chat.trinissoft.com>, username=<1572519615:@erli:chat>, lifetime=0
25: session 001000000000000001: realm <chat.trinissoft.com> user <1572519615:@erli:chat>: incoming packet REFRESH processed, success
26: session 001000000000000001: closed (2nd stage), user <1572519615:@erli:chat> realm <chat.trinissoft.com> origin <>, local 5.189.144.69:3478, remote 80.78.65.91:37170, reason: allocation timeout
26: session 001000000000000001: delete: realm=<chat.trinissoft.com>, username=<1572519615:@erli:chat>
26: session 001000000000000001: peer 10.29.12.129 deleted

**Comment by misi** [comment]
It is up to your client and ICE  decision... 
See internals in your browser. Open in new tab ```chrome:webrtc-internals``` or ```about:webrtc``` in firefox

**Comment by marksalpeter** [comment]
@misi @jzallimi  Did you ever get this working? I'm currently stuck at lifetime=0 refresh on all browsers.
