### ISSUE TITLE
why is linux/version.h needed?

### ISSUE THREAD

**Issue by celevra** [coturn/coturn#46]
hi,

i want to run coturn in a docker container under alpine linux.
But the compilation stopps with
```
src/apps/relay/mainrelay.c:1706:27: fatal error: linux/version.h: No such file or directory
```

why are the Kernel headers needed? if i remove the include of linux/version.h everything compiles just fine.

**Comment by mom040267** [comment]
linux/version.h is needed to determine the linux kernel version. Different kernel versions have different capabilities. May be you can fake that file for your purposes.
