### ISSUE TITLE
Which organizations currently using coturn as STUN/TURN server?

### ISSUE THREAD

**Issue by chanduthedev** [coturn/coturn#462]
Hi Team,

I would like to know list of organizations which are currently using coturn as their STUN/TURN server.

Thanks,

**Comment by misi** [comment]
Good question! 
I am also wondering who are the main users..

**Comment by chanduthedev** [comment]
AFAIK Amazon MayDay was using coturn as their STUN/TURN server. Unfortunately now this feature is not available. Other than this I could not find any organizations who announced that they were using coturn as their STUN/TURN server.

**Comment by chanduthedev** [comment]
I found that below are using coturn as their STUN/TURN servers.
 - Confrere (https://confrere.com/)
 - Whereby (https://whereby.com/) formerly appear.in
<br>
However there is no official announcement regarding coturn as their STUN/TURN server. So  I am not 100% sure that this.  And @bradleythughes  was using coturn when he was working appear.in and he mentioned in #328. So I am assuming appear.in using coturn.
