### ISSUE TITLE
Which is the latest stable release?

### ISSUE THREAD

**Issue by gharia** [coturn/coturn#464]
Well, this is not an issue but a question. I was looking for the latest stable release and found the latest tagged version is `4.5.1.1`. But then the wiki page, https://github.com/coturn/coturn/wiki/Downloads, suggests stable release as `4.5.0.8`.

So which one to consider as a stable release. for production?

**Comment by misi** [comment]
4.5.1.1 is the latest stable release. Sorry for the confusion.

**Comment by gharia** [comment]
No problem. Thanks @misi
