### ISSUE TITLE
Connection establish between two parties even though coturn credentials are invalid.

### ISSUE THREAD

**Issue by chanduthedev** [coturn/coturn#465]
Hi @misi I have two issues, Can you please help on this.

**Issue 1:**
I am using  coturn  as STUN/TURN server for our video calls. But the problem was video call established between caller and callee for the **invalid coturn credentials** which was not expected. 

**Issue 2:**

Is there any unique identifier(like socket id ) in coturn session if connection established. How coturn identifies the data if multiple calls are running at the same time?

Thanks in advance

**Comment by chanduthedev** [comment]
I found below variables in the code. Can you please explain what is the major difference among these three id's.
1. turnsession_id
2. turnserver_id
3. session_id_counter

And when connection established, which of these three id values change and what are those values? And Can we use any of these three id's as unique identifier to identify the connection?

Thanks in advance.

**Comment by eakraly** [comment]
Hi @chanduthedev - do you still experience an issue (it's open for 3 years)?
To your question - they could connect if they were able to establish a direct communication, without TURN. In this case, even having incorrect TURN credentials does not prevent them from establishing a direct connection.
