### ISSUE TITLE
Can Coturn be used for peer-to-peer file transfer? Asking for help!!

### ISSUE THREAD

**Issue by yuhorun** [coturn/coturn#467]
I looked for a lot of information, still do not know how to implement. Can you tell me if this is feasible, it is best to provide ideas.
You are my god!
Thanks in advance!

**Comment by yuhorun** [comment]
I installed Coturn on three computers, one of which is a cloud server.and the other two is peer behind Nat, How to get two Peers in touch to send data?

**Comment by eakraly** [comment]
Hi @yuhorun - this question seem loosely related and almost 3 years old

In theory yes but both your applications need to support TURN to establish a p2p connection
