### ISSUE TITLE
is support rtcp-mux(rfc5761) and bundle (rfc5888)?

### ISSUE THREAD

**Issue by new1943** [coturn/coturn#47]
I was using coturn as a turn webrtc service development, but I encountered a new problem, in the webrtc is to use the single port . Using rfc5761 and rfc5888, they seem to be going nowhere. There is no answer address of the other party relay. So I would like to ask coturn support? How to configure?

**Comment by misi** [comment]
These RFC-s controls UA-s behavior amd the rtc-mux and bundle is transparent for TURN service. 
AFAIK no configuration needed. Could you please clarify what you mean?
