### ISSUE TITLE
support export metrics to prometheus 

### ISSUE THREAD

**Issue by chenxinlong** [coturn/coturn#474]
Hi, will you consider supporting export metrics to Prometheus?

**Comment by misi** [comment]
It would be great to add this feature. Any help would be appreciated..

**Comment by wolmi** [comment]
I've started to develop this feature, I'll update on this issue the progress.

At the moment I have prepared the environment and I have the first metric based on the current metrics sent to Redis.

![image](https://user-images.githubusercontent.com/624089/78157481-4bffb680-7440-11ea-9c73-5c4b186d589f.png)

**Comment by wolmi** [comment]
I've pushed some code, it is based on the Prometheus C client from:
https://github.com/digitalocean/prometheus-client-c

My branch is:
https://github.com/wolmi/coturn/tree/prometheus

If you want to review it and give me some feedback it will be very helpful, if you prefer I can open a PR for an easy review.

**Comment by wolmi** [comment]
Please @misi can you review the PR #517 and see if it is correct?

I think the only thing missing to have the first version for using it is to include an option to pass as an argument or in the configuration file.

I'll work on adding the options too.

**Comment by misi** [comment]
@wolmi  Sorry for the delay. I will try to review it and it will be in the next release.

**Comment by samuel-p** [comment]
@misi Can you roughly say when the next release will be? I'm waiting for this in your docker image. At the moment I get still: 

```
Bad configuration format: prometheus
```

It would be awesome to have this feature.

**Comment by os14** [comment]
same here ^^

**Comment by c4m4** [comment]
same here, I am usin Debian 10 and coturn version 4.5.1

**Comment by sj82516** [comment]
You have to build from the source. 
And also prometheus metrics only support debian now, don't forget to install dependency before you build.  
The dependencies are here which I copy from the PR
```
RUN curl -fL -o /tmp/libprom.deb \
         https://github.com/digitalocean/prometheus-client-c/releases/download/v0.1.1/libprom-dev-0.1.1-Linux.deb

RUN curl -fL -o /tmp/libpromhttp.deb \
         https://github.com/digitalocean/prometheus-client-c/releases/download/v0.1.1/libpromhttp-dev-0.1.1-Linux.deb


RUN apt install -y /tmp/libprom.deb
RUN apt install -y /tmp/libpromhttp.deb
```

**Comment by c4m4** [comment]
@sj82516 are you using any grafana dashboard?

**Comment by sj82516** [comment]
Yes I do. 
Any problem here ?

**Comment by c4m4** [comment]
is this dashboard public?

**Comment by sj82516** [comment]
It's private but I organized it and create by docker.    
If you run on native machine, I think the set up is quite the same. 
Here is my github repo and I just tried this morning, it should work fine.  
 
https://github.com/sj82516/coturn-with-prometheus-grafana-on-docker

**Comment by hd-deman** [comment]
@sj82516 can you share your dashboard here https://github.com/coturn/coturn/issues/848 ?

**Comment by sj82516** [comment]
sorry I haven't used it for a long time. And because the memory leak issue, I create another one by my self.
https://github.com/sj82516/turn-monitor
