### ISSUE TITLE
Docker networking question

### ISSUE THREAD

**Issue by creimers** [coturn/coturn#477]
Please bear with me. I'm an experienced web dev, but total a WebRTC novice and by no means an expert on networking.

My question is about the network setup in docker-compose, e.g. [docker-compose-redis.yml](https://github.com/coturn/coturn/blob/master/docker/docker-compose-redis.yml).

Can someone elaborate on the networking setup? Why do I need this ipam entry?

**Comment by NorseGaud** [comment]
This helped me a lot: https://blogs.infoblox.com/community/how-docker-networking-works-and-the-importance-of-ipam/

**Comment by creimers** [comment]
@NorseGaud ad Thanks for the link. Very interesting indeed. 

Let's say I had a coturn instance up and running on premise with exactly this [docker-compose file](https://github.com/coturn/coturn/blob/master/docker/docker-compose-redis.yml), how would I configure my `iceServers` for the `RTCPeerConnection`? 

```javascript
const ip = "192.178.1.33";

const config = {
    iceServers: [
      {
        url: `stun:${ip}:3478`
      }
    ]
};
```

Just like this more or less?

**Comment by creimers** [comment]
I ended up accessing the stun server running in docker like this:

`stun:<HOST_IP>:3478`
