### ISSUE TITLE
Unable to relay over Microsoft Direct Access

### ISSUE THREAD

**Issue by olivierb2** [coturn/coturn#483]
Hi everybody,

Does anybody already has a working coturn configuration with Microsoft Direct Access ? I'm currently running a coTurn server with permission to relay audio and video flux through authentication and this relay is working perfectly but not when client are connected over Direct Access.

Negotiation on port 3478 seems good, but client is forced to use relay mode. Negotiation seems to return usable port on the turn server itself, but because this negotiation return IP addresses of the turn server, Direct Access is unable to transmit IPv4 while everything must use domain name.

Is there any tweak to let coturn returning domain name in reply instead of IP addresses, especially for itself?

**Comment by misi** [comment]
Sorry I don't have any experience w2ith ms direct access.
I don't yet understand your problem. 
When should TURN return domain name? Can you please send a dump with explanation?
Please check what is in RFC and what you expect. If RFC allows such behavior please send PR and I will include it.

**Comment by olivierb2** [comment]
Basically, DirectAccess client cannot communicate to host with its IP address. By example, doing "ping 8.8.8.8" will never work while doing "ping google.com" will work.
While CoTurn negociation seems fine, the result is not usable because it's based on IP adresses. The RFC describes this behavior here : https://tools.ietf.org/html/rfc5766#section-5
I guess there is nothing to do with CoTurn in fact and system should have a fallback way like Jitsi to send raw flow IP packet to specific adress and port. Unfortunately, I didn't seen this kind of mechanism into OpenVidu.

Thanks for your support anyway.
