### ISSUE TITLE
Loadbalancing multiple TURN servers - Round robin DNS option

### ISSUE THREAD

**Issue by jdwalker** [coturn/coturn#485]
I've been looking at [the wiki for loadbalancing](https://github.com/coturn/coturn/wiki/TURN-Performance-and-Load-Balance) and for multiple systems it states:

> Set a less complex scheme with round-robin DNS. The client must send all its requests to the same DNS-discovered TURN server. That scheme supports all use cases.

But how would this work if client A gets the ip of TURN server B, and client C gets the ip of TURN server D - their ICE candidates will be different, right? So how do they connect? How would authentication work even if they can agree on a TURN server.

**Comment by dwin** [comment]
You can use a shared database such as MySQL so that auth credentials would be shared.

**Comment by jdwalker** [comment]
Sorry, I didn't mean authentication, I meant the webrtc connection - how do we go through A -> B -> C -> D?

**Comment by ArtemisMucaj** [comment]
Hi,

To make it simple clients don't need to be connected to the same instance of *coturn* to communicate; the relay IP address obtained by each client is exchanged through your signaling servers.

For example we have two *coturn* instances *s0* and *s1* and two clients *A*, *B*.

*A* obtains a relay address *ip0* from *s0*
*B* obtains a relay address *ip1* from *s1*

These candidates are exchanged though a proprietary signaling protocol and *B* knows that *A* is reachable on the relay address *ip1*, *A* knowns that *B* is reachable on relay address *ip0*

**Comment by jdwalker** [comment]
Ah I think I understand - so the turn server is acting as a proxy - I was assuming there was a man in the middle relay.

Thanks for your help!

**Comment by gurupras** [comment]
A few follow up questions:
Do _s0_ and _s1_ need to know about each other in some way?
Is this applicable for webRTC? Sounds like it is, but just confirming..

**Comment by Fmajor** [comment]
I have the same question as @gurupras. Can we make a turn cluster so that client A can access client B through the turn cluster network, just like how routers transfer web packages?
