### ISSUE TITLE
process terminated with SIGABRT

### ISSUE THREAD

**Issue by sandeep5193** [coturn/coturn#490]
OS: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-1057-aws x86_64)
Coturn version: 4.5.0.7-1ubuntu2.18.04.1

here is backtrace collected from CoreDump generated through apport:

0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
1  0x00007f93c6e89801 in __GI_abort () at abort.c:79
2  0x00007f93c6ed2897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f93c6fffb9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
3  0x00007f93c6ed990a in malloc_printerr (str=str@entry=0x7f93c7001870 "double free or corruption (out)") at malloc.c:5350
4  0x00007f93c6ee0e75 in _int_free (have_lock=0, p=0x7f93bc0000a0, av=0x7f93c7234c40 <main_arena>) at malloc.c:4278
5  __GI___libc_free (mem=0x7f93bc0000b0) at malloc.c:3124
6  0x00007f93c8aca380 in HMAC_CTX_free () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
7  0x00007f93c8aca5fb in HMAC () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
8  0x000055fa3696d8db in ?? ()
9  0x000055fa36970b5c in ?? ()
10 0x000055fa369769ed in ?? ()
11 0x000055fa3693abf3 in ?? ()
12 0x000055fa369787ea in ?? ()
13 0x000055fa36978bf1 in ?? ()
14 0x000055fa3695a94e in ?? ()
15 0x000055fa3695b2b4 in ?? ()
16 0x00007f93c84aded8 in ?? () from /usr/lib/x86_64-linux-gnu/libevent_core-2.1.so.6
17 0x00007f93c84ae91f in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent_core-2.1.so.6
18 0x000055fa36947b89 in ?? ()
19 0x000055fa369490a5 in ?? ()
20 0x00007f93c72416db in start_thread (arg=0x7f93c1936700) at pthread_create.c:463
21 0x00007f93c6f6a88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by misi** [comment]
Please upgrade to 4.5.1.1 and retest it..
Thanks!

**Comment by sandeep5193** [comment]
now we got SIGSEGV on another machine, same OS and Coturn version as  previous.

Program terminated with signal SIGSEGV, Segmentation fault.

0  0x00007f096e4cd947 in BIO_ctrl () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
1  0x00007f096e4cb535 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
2  0x00007f096e4cd949 in BIO_ctrl () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
3  0x00007f096e4cb535 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
4  0x00007f096e4cd949 in BIO_ctrl () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
5  0x00007f096e4cb535 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
6  0x00007f096e4cd949 in BIO_ctrl () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
7  0x00007f096e4cb535 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
8  0x00007f096e4cd949 in BIO_ctrl () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
9  0x00007f096e4cb535 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1

Are these known issues and resolved in 4.5.1.1?

**Comment by sandeep5193** [comment]
1st backtrace I shared looks very similar to #257 , I have installed 4.5.1.1 on a new server, will observe it.

Any thoughts on 2nd trace I shared?

**Comment by sandeep5193** [comment]
one more SIGSEGV, on 4.5.0.7.

Program terminated with signal SIGSEGV, Segmentation fault.
0  0x00007f5fa263ef69 in EVP_MD_CTX_copy_ex () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
1  0x00007f5fa26582fd in HMAC_Final () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
2  0x00007f5fa26585ef in HMAC () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
3  0x000055bf370358db in ?? ()
4  0x000055bf37038b5c in ?? ()
5  0x000055bf3703e9ed in ?? ()
6  0x000055bf37002bf3 in ?? ()
7  0x000055bf370407ea in ?? ()
8  0x000055bf37040acb in ?? ()
9  0x000055bf3700ff9a in ?? ()
10 0x00007f5fa20318ae in ?? () from /usr/lib/x86_64-linux-gnu/libevent_core-2.1.so.6
11 0x00007f5fa203bc94 in ?? () from /usr/lib/x86_64-linux-gnu/libevent_core-2.1.so.6
12 0x00007f5fa203c91f in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent_core-2.1.so.6
13 0x000055bf3700fb89 in ?? ()
14 0x000055bf370110a5 in ?? ()
15 0x00007f5fa0dcf6db in start_thread (arg=0x7f5f9b4c3700) at pthread_create.c:463
16 0x00007f5fa0af888f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

I have updated few servers to 4.5.1.1, those are not having this problem yet.

**Comment by sandeep5193** [comment]
as suggested by @misi we have upgraded all servers to 4.5.1.1. closing this issue, will open a new one if it occurs in 4.5.1.1.
