### ISSUE TITLE
After Restarting Server not able to bind to adress

### ISSUE THREAD

**Issue by NoobKeksTV** [coturn/coturn#491]
Hi there,

After i restarted my Debian 10 (buster) server im not able to start my turnserver. it always spams this error:
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr 194.59.207.61:3479
0: Trying to bind TLS/TCP listener socket to addr 194.59.207.61:3479, again...
bind: Address already in use
0: Trying to bind fd 35 to <194.59.207.61:3479>: errno=98
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr 194.59.207.61:3479
0: Trying to bind TLS/TCP listener socket to addr 194.59.207.61:3479, again...

i alredy removed it with purge argument but it didnt help.

**Comment by misi** [comment]
Check stuck turnserver instance or busy ports with `netstat -lnp`.
I use debain 10 and I don't experience this issue.
It seems some ports are busy. 
Try to stop, killall instance, and wait few seconds before starting it again.

**Comment by ZockerBoysHD** [comment]
there are no processes / instances of the turnserver running at all.

**Comment by eakraly** [comment]
Hi @NoobKeksTV 
Were you able to address the issue?
