### ISSUE TITLE
Short-Term Authentication base on REST API (Error 401: Unauthorized)

### ISSUE THREAD

**Issue by raccoonback** [coturn/coturn#493]
Hi, I am building a turn server using coturn. 

I want to use short-term authentication base on REST API belong to https://www.ietf.org/proceedings/87/slides/slides-87-behave-10.pdf. 

However, I'm struggling with error issues about "incoming packet message processed, error 401: Unauthorized".

Our project set up turnserver.conf as shown below.

```
listening-port=3478
tls-listening-port=5349
min-port=49152
max-port=65535
verbose
fingerprint
use-auth-secret
server-name=test.com
mongo-userdb="mongodb://127.0.0.1:27017/coturn"
cert=/etc/ssl/certs/cert.pem
pkey=/etc/ssl/private/privkey.pem
syslog
rest-api-separator=:
cli-ip=127.0.0.1
cli-port=5766
cli-password=CHANGE_ME
```

The database is MongoDB (version 3.6) and has the same schema as https://github.com/coturn/coturn/blob/master/turndb/schema.mongo.sh

Also, The client is configured to send requests to Turn Server as shown below.

```javascript
const pc = new RTCPeerConnection({
    iceServers: [
        {
          urls: 'turn:127.0.0.1:3478',
          credential: "S/3WRr/YpF2AGlToYCzIOtB85G4=",
          username: 'ninefingers:1582164948',
        },
    ],
    iceTransportPolicy : 'relay'
});
```

🙋‍♂🙋‍♂🙋‍♂
**I'm curious how to set the "nonce, realm, MESSAGE-INTEGRITY" information in the client's first "Allocate Request".**

In Wireshark, the Binding Request succeeds, but the Allocate Request fails.

![image](https://user-images.githubusercontent.com/16451031/74803625-ee485c80-5320-11ea-8cca-ddbb155a03ff.png)

Based on the documentation (draft-uberti-behave-turn-rest-00), the allocation request includes "nonce, realm, MESSAGE-INTEGRITY", but in reality it is not.

![image](https://user-images.githubusercontent.com/16451031/74803787-952cf880-5321-11ea-9deb-93d9ba98101c.png)

And on every request, the following error constantly occurs on the coturn server. 😭😭😭

```bash
session 001000000000000003: realm <> user <>: incoming packet BINDING processed, success
session 000000000000000003: realm <> user <>: incoming packet message processed, error 401: Unauthorized
```

🙋‍♂🙋‍♂🙋‍♂
**Am I misunderstanding short-term authentication? Or am I doing the wrong client or coturn setting?**

**Comment by raccoonback** [comment]
**username and credential** were applied identically to https://stackoverflow.com/questions/35766382/coturn-how-to-use-turn-rest-api.

```javascript
var crypto = require('crypto');

function getTURNCredentials(name, secret){    

    var unixTimeStamp = parseInt(Date.now()/1000) + 24*3600,   // this credential would be valid for the next 24 hours
        username = [unixTimeStamp, name].join(':'),
        password,
        hmac = crypto.createHmac('sha1', secret);
    hmac.setEncoding('base64');
    hmac.write(username);
    hmac.end();
    password = hmac.read();
    return {
        username: username,
        password: password
    };
}
```

**Comment by raccoonback** [comment]
@misi, I've looked up a lot of issues with this error, but haven't found a solution yet. Help...;

**Comment by raccoonback** [comment]
Also, I also stored the **shared secret key** in MongoDB.


> name: ninefingers:1582164948
> hmackey: S/3WRr/YpF2AGlToYCzIOtB85G4=
> realm: north.gov
> secret_key: logen


### turn_secret

![image](https://user-images.githubusercontent.com/16451031/74807632-42a50980-532c-11ea-8097-1e3e86b620e1.png)


### trunuser_lt

![image](https://user-images.githubusercontent.com/16451031/74807573-26a16800-532c-11ea-8f11-f339e719040e.png)


### realm

![image](https://user-images.githubusercontent.com/16451031/74807591-2e610c80-532c-11ea-8554-c7ed95404149.png)

**Comment by raccoonback** [comment]
And, MongoDB is connected.

![image](https://user-images.githubusercontent.com/16451031/74807795-b21af900-532c-11ea-83e1-88ae6fca0452.png)

**Comment by raccoonback** [comment]
@misi, I've looked up a lot of issues with this error, but haven't found a solution yet. 

**Help**...;

**Comment by misi** [comment]
Today will be my colleague memorial service, but tomorrow I will try to help. Thanks for your patience..

**Comment by raccoonback** [comment]
@misi 
Ok. Thanks for the quick reply!

**Comment by misi** [comment]
Please check the reverse the order of timestamp and username:
username: 'ninefingers:1582164948',
name: ninefingers:1582164948

But in
https://tools.ietf.org/html/draft-uberti-rtcweb-turn-rest-00
https://github.com/coturn/coturn/blob/master/README.turnserver
username: timestamp:username

I hope it helps

**Comment by raccoonback** [comment]
@misi
Sorry for the late reply. And Thanks for the help!

I did as you told me. Nevertheless, the result is the same as before. 😭😭😭

🙋‍♂🙋‍♂🙋‍♂
Does short term authentication work like a long term with timeouts? In other words, is it correct to receive a 401 error at least once?

Adding the tcp option causes the browser to resend the 'Allocate Request' with 'realm, nonce, message-integrity' after receiving a 401 error, such as long-term authentication (ex. turn: //127.0.0.1: 3478?transport=tcp). 
However, the udp option does not resend the 'Allocate Request' (ex. turn: //127.0.0.1: 3478?transport=udp). Do you know why this is happening?

**Comment by raccoonback** [comment]
### Case tcp option

![image](https://user-images.githubusercontent.com/16451031/75122956-932eb500-56e6-11ea-91d9-efa38ee18dfe.png)

### Case udp option

![image](https://user-images.githubusercontent.com/16451031/75122986-d6892380-56e6-11ea-94ee-2980b83c69d4.png)

In the case of udp, after a 401 error, the **'Binding Request'** is executed without requesting the **'Allocate request'** again.

**Comment by misi** [comment]
@raccoonback 
>In other words, is it correct to receive a 401 error at least once?
401 for the first time is the expected behaviour. In this 401 you will get the "NONCE". So for the first time it is absolutely normal to get 401.

**Comment by misi** [comment]
You use "short term credential" wrong, it is only used in ICE, 
so You use "Long Term Credential" in your scenario..

**Comment by raccoonback** [comment]
I understand... 😀

Your help has been a lot. Thank you!
