### ISSUE TITLE
Using coTurn TCP allocations with DataChannel webRTC client

### ISSUE THREAD

**Issue by khaldounaldanafcbs** [coturn/coturn#494]
I have configured a coturn server which I need to use with DataChannel for a chat app.

I am trying to reach a point where I can get the coturn server provide me with a tcp allocation.

I am using the standard call of RTCPeerConnection in JS client, providing the turn URI, username and credentials.

The transport I am providing in the URI params is TCP ?transport=tcp.

With all this, I am always receiving a UDP allocation and the server logs ChannelBind requests (UDP based)

Question:

How can I achieve TCP allocations throught webRTC client, to guarantee proper data delivery of the chat app in case of using my relay server?

**Comment by misi** [comment]
Be aware that maybe not all browser implemented TURN+TCP relaying.

**Comment by khaldounaldanafcbs** [comment]
> Be aware that maybe not all browser implemented TURN+TCP relaying.

- Is there a list of browsers that implemented the TURN+TCP relaying?
- What about the implementation with webRTC to retrieve the TCP allocation on the TURN server? Any idea how to achieve this?

**Comment by misi** [comment]
Try to check in browser implementation 
I don't know the actual status..

**Comment by khaldounaldanafcbs** [comment]
> Try to check in browser implementation
> I don't know the actual status..

Is this answer for my first or second question?

**Comment by misi** [comment]
I know that ICE + TCP is implemented in firefox. 
But this is not equivalent to TURN + TCP.
Check it in the source code of the browser.
