### ISSUE TITLE
Unexpected userdb reset

### ISSUE THREAD

**Issue by gydovrowl** [coturn/coturn#498]
We have experienced a very strange issue where all users suddenly disappeared from the turn server.

Client has an Ubuntu server (18.04 LTS) with coturn installed via apt (installation took place somewhere around december 2018). This server has been running ever since. Everything worked as intended until the start of this year or even the end of last year. 
The client started to experience intermittent connectivity issues with a custom webrtc app which used this turn server. We discovered that all connections which needed the turn server failed.
After examining the turn server it turned out all lt credential users had disappeared (running  `turnadmin -l` returned no results). Re-adding the tl users fixed the immediate problem for our client, but the fact that the users could disappear at all worries us.

We are told that the server has not been touched after installation, save for a few restarts (we tested restarting, but everything was as it should be)
The situation at the client did change recently, which meant more connections would need the turn server to work. It could be that the issue has existed for a longer time, but only now became more apparent.
We do not know the exact time at which this issue started and did not find any logs that indicated a problem (or many recent logs at all actually, maybe suggesting that this problem has existed for a longer time)

This is the configuration that was used:
```
listening-port=3478
tls-listening-port=5349

listening-ip=<host-ip>
relay-ip=<host-ip>

fingerprint
lt-cred-mech
stale-nonce=600
no-loopback-peers
no-multicast-peers
```

We think this might be some kind of user error, but just to be absolutely sure: could there be some issue in cotorn to cause this behavior?

**Comment by gydovrowl** [comment]
I understand this issue probably has nowhere near enough information to go on, but it would really help us if a developer/maintainer could indicate if anything like this has ever happened to anyone before. It will help us convince our client whether this was a user error during the initial configuration or not.

**Comment by misi** [comment]
Which version do you use?
Try to use debian and upgrade to 4.5.1.1

**Comment by gydovrowl** [comment]
Thanks for your reply!

> Which version do you use?

Whatever version was available through apt-get at the time (december 2018). Sorry, not much to go on, we don't have direct access to the system... I'll try to find out, but I would guess 4.5.0.7.

> Try to use debian and upgrade to 4.5.1.1
> Don't use older version! There are security issues in older versions where web server is not disabled.

I will suggest we upgrade to our client.
