### ISSUE TITLE
Talso vulnerabilities & 4.5.1.2 ?

### ISSUE THREAD

**Issue by guedou** [coturn/coturn#499]
Hi,

Thank you for your awesome work on coturn.

Could you consider releasing version 4.5.1.2 by applying the two commits that fixes the issues?

Guillaume

**Comment by misi** [comment]
I was ill sorry. I am just back at  work. I will do it ASAP..

**Comment by guedou** [comment]
Thanks a lot for your answer. I hope that you are now feeling better.

**Comment by misi** [comment]
I just want to add that until you don't enable webserver you are safe form  all these vulnerabilities.
So we don't need to panic.  :)
This issue addressed in some form with limiting webserver availibilty in 4.5.1.1.
So with disabling the web by default, and evenif enabled it listens by default on localhost in 4.5.1.1. 

In other hand I am doing my best. 
I try to make the basic function tests work again, and release the next release but it seems it takes a while. So sorry..

Thanks for your patience..

**Comment by misi** [comment]
Sorry I am busy due covid. I will do my best but please expect still some delay..

**Comment by misi** [comment]
@guedou  4.5.1.2 is out.
Sorry for the delay.. I close this issue..

**Comment by guedou** [comment]
Thanks!
