### ISSUE TITLE
Coturn is sending my private IP in headers rather than public header. How to fix this?

### ISSUE THREAD

**Issue by saadat-atta-brainx** [coturn/coturn#501]
a=ice-pwd:04d5c0ff4b36109251581fd81db16c83
a=candidate:Hac1f15e7 1 UDP 2130706431 172.31.21.231 11028 typ host
a=candidate:Hac1f15e7 2 UDP 2130706430 172.31.21.231 11029 typ host

**Comment by rottaran** [comment]
You can try to set the parameter external-ip=EXTERNALIP/INTERNALIP instead of listening-ip and relay-ip.

**Comment by misi** [comment]
@saadat-atta-brainx Check config for relay listener and external-ip settings.
