### ISSUE TITLE
SQLite connection was always closed after killing the process

### ISSUE THREAD

**Issue by wyudong** [coturn/coturn#502]
I accidentally kill the turnserver process on ubuntu and now when I run **turnadmin -L**, it shows "SQLite connection was closed". How can I re-open SQLite connection then?

```
0: log file opened: /var/tmp/turn_13969_2020-03-01.log
0: SQLite connection was closed.
```

**Comment by misi** [comment]
Try to restart the turnserver..

**Comment by wyudong** [comment]
@misi The turnserver is actually running, but I don't know what 's wrong with SQLite. I start the turnserver in this way:

```
turnserver -o -a -f -v -r <realm>
```

**Comment by misi** [comment]
@wyudong  Please set the sqlite db location in your server config..

**Comment by k2hoon** [comment]
@wyudong By reference to the manual..
Options with required values:
       -b, --db, --userdb
              SQLite    user    database    file    name    (default    -    /var/db/turndb    or
              /usr/local/var/db/turndb or /var/lib/turn/turndb).  See  the  same  option  in  the
              turnserver section.

**Try it with the command below**
turnadmin --db <database-name> -L

**Comment by wyudong** [comment]
@misi  @k2hoon I can find /usr/local/var/db/turndb, but running turnadmin with db option also returns the same error.

```
turnadmin --db /usr/local/var/db/turndb -L
0: log file opened: /var/tmp/turn_29353_2020-03-03.log
0: SQLite connection was closed.
```

**Comment by misi** [comment]
@wyudong  try to check the file has right permission..

**Comment by kolserdav** [comment]
> @wyudong try to check the file has right permission..

Hi. I have the same problem. I run with sudo, File permissions is:
```sh
-rw-r--r-- 1 root root 69632 Jun 28 11:19 turndb
```
