### ISSUE TITLE
Relay not work

### ISSUE THREAD

**Issue by wjhtinger** [coturn/coturn#505]
I set a coturn server and use webrtc to test. The STUN work well. But in some neworks, STUN not success, but the Relay not work. That means TURN not work, right?

In configure:
use-auth-secret
static-auth-secret=[your secret key here]
realm=turn.myserver.org
others are default.

So, what wrong with my server? How can I debug the problem?

**Comment by chanduthedev** [comment]
Hi @wjhtinger, 
Are your testing network with in local network? If Signaling server and Client are in the same network, STUN will take precedence than TURN server. Need to keep both in separate network to work TURN server.

**Comment by misi** [comment]
Auth secret is rest so see: https://www.ietf.org/proceedings/87/slides/slides-87-behave-10.pdf

**Comment by wjhtinger** [comment]
> 
> 
> Hi @wjhtinger,
> Are your testing network with in local network? If Signaling server and Client are in the same network, STUN will take precedence than TURN server. Need to keep both in separate network to work TURN server.

I use different network to test, not in local network.

**Comment by wjhtinger** [comment]
> 
> 
> Auth secret is rest so see: https://www.ietf.org/proceedings/87/slides/slides-87-behave-10.pdf
> Make sure you want to use REST and timestamp and check your serve clock..

I think Auth secret is OK, just STUN  work well

**Comment by Sudheerkumar** [comment]
I do have the same issue. Any help please? Am facing similar issue on a corporate network. Never see a `relay` being generated.
While outside VPN i could see `srflx` and it connects. In a whole i could never see a relay candidate generated ever from the browser client

**Comment by Neustradamus** [comment]
@misi: Can you look?

**Comment by chanduthedev** [comment]
HI @Sudheerkumar, if signallng server and coturn are in the same network, relay ICE cadidate will not generate. ICE candidate generating basing on priority. You can check https://tools.ietf.org/html/rfc5245#section-4.1.2 link more info. If signalling server and coturn are in the same network only host ICE candidates will generate.

**Comment by misi** [comment]
See `about:webrtc` or `chrome://webrtc-internals`
@wjhtinger I feel it is not a coturn issue or enhancement please use mailinglist for discussion or help.

**Comment by hktalent** [comment]
me too
no relay, only srflx
> I do have the same issue. Any help please? Am facing similar issue on a corporate network. Never see a `relay` being generated.
> While outside VPN i could see `srflx` and it connects. In a whole i could never see a relay candidate generated ever from the browser client

**Comment by FeatureSpitter** [comment]
same here
