### ISSUE TITLE
Configure coturn to accept connections on port 443 tcp exclusively

### ISSUE THREAD

**Issue by darknight7** [coturn/coturn#508]
I've been under pressure for a while to make webrtc (nextcloud talk) work with people behind restrictive corporate firewalls the way they have experienced with some commercial services.
This means that all connections have to be client initiated and established with port 443 on the server.

I've been trying to figure this out but I'm starting to wonder if it's at all possible with the current implementation.

I apologize if this is the wrong place to ask but extensive searches didn't yield much.

**Comment by misi** [comment]
Redirect or DNAT port to standard port could work with iptables/nftables

**Comment by darknight7** [comment]
Either I didn't explain myself very well or I didn't understand your suggestion, I'll detail a bit better the current setup:
- I have the luxury of two public ip addresses, let's say 1.2.3.4 and 1.2.3.5
- nextcloud+talk is setup on 1.2.3.4:443 with apache server
- coturn is setup on 1.2.3.5:443
- iptables is conveniently setup to allow connections to 443 (**only tcp**) on both ip addresses (444 too on 1.2.3.5, for testing purposes)
- I have a full dual stack v4 and v6 setup, I have omitted v6 because it's not even part of the equation right now, turn.my.tld is configured as just v4 right now. Anyway, v6 is 100% a mirror of v4 for what it's worth and if I add a v6 ip to listen to, coturn handles it just as fine as v4 from what I can tell

Config:
```
tls-listening-port=443
listening-ip=1.2.3.5
verbose
fingerprint
use-auth-secret
static-auth-secret=shhhh
realm=my.secret.tld
total-quota=100
bps-capacity=0
no-udp
no-tcp
stale-nonce=600
cert=/etc/ssl/turn.crt
pkey=/etc/ssl/turn.key
syslog
simple-log
no-multicast-peers
```

netstat grep:
```
tcp        0      0 1.2.3.5:444       0.0.0.0:*               LISTEN      10317/turnserver
tcp        0      0 1.2.3.5:444       0.0.0.0:*               LISTEN      10317/turnserver
tcp        0      0 1.2.3.5:444       0.0.0.0:*               LISTEN      10317/turnserver
tcp        0      0 1.2.3.5:444       0.0.0.0:*               LISTEN      10317/turnserver
tcp        0      0 1.2.3.5:443       0.0.0.0:*               LISTEN      10317/turnserver
tcp        0      0 1.2.3.5:443       0.0.0.0:*               LISTEN      10317/turnserver
tcp        0      0 1.2.3.5:443       0.0.0.0:*               LISTEN      10317/turnserver
tcp        0      0 1.2.3.5:443       0.0.0.0:*               LISTEN      10317/turnserver
udp        0      0 1.2.3.5:443       0.0.0.0:*                           10317/turnserver
udp        0      0 1.2.3.5:443       0.0.0.0:*                           10317/turnserver
udp        0      0 1.2.3.5:443       0.0.0.0:*                           10317/turnserver
udp        0      0 1.2.3.5:443       0.0.0.0:*                           10317/turnserver
udp        0      0 1.2.3.5:444       0.0.0.0:*                           10317/turnserver
udp        0      0 1.2.3.5:444       0.0.0.0:*                           10317/turnserver
udp        0      0 1.2.3.5:444       0.0.0.0:*                           10317/turnserver
udp        0      0 1.2.3.5:444       0.0.0.0:*                           10317/turnserver
```

Thanks for your help! I'll provide any more information required.

**Comment by darknight7** [comment]
Problem solved. The above configuration is working perfectly unless something new makes me think otherwise.
It turns out that the a firewall (not on the machine) was not behaving as it was supposed to be, the relevant policy had not been applied correctly.
I hope this issue proves useful to someone else.

**Comment by peterzanetti** [comment]
Your configuration has no default listening port for TCP/UDP? Why? How are you connecting to the TURN server? Is only using TLS?

I am trying to handle the same kind of scenario.

**Comment by darknight7** [comment]
My understanding of the matter is that right now this is not possible because of how the browsers implement the protocol. Webrtc TCP relay is unsupported, this is not a problem with coturn. Furthermore a proxy or firewall that is sufficiently advanced can and will detect webrtc not being https, and will filter it accordingly if configured to allow only https.
Opening high ports is thus still mandatory.
In my opinion webrtc is great on paper but in the current state it's not ready for all scenarios.
More knowledged people may offer better/different insights.

**Comment by ROBERT-MCDOWELL** [comment]
@[darknight7
what about the port 444 open I can see on your list?

**Comment by darknight7** [comment]
@ROBERT-MCDOWELL 
I'm sorry, this is ancient and I've given up a long long time ago.
