### ISSUE TITLE
tcp stun client recommendation

### ISSUE THREAD

**Issue by yfaker** [coturn/coturn#509]
hi everyone , I'm testing stun over tcp, do you have any tcp stun client to recommend? thanks a lot

**Comment by MiningPickaxe** [comment]
Hey,

you might like this one: https://github.com/coturn/coturn/wiki/turnutils_stunclient

**Comment by yfaker** [comment]
Hi thanks for you advise
i checked turnutils_stunclient and it is over udp
and i have found another clien meets the need:https://github.com/jselbie/stunserver

**Comment by misi** [comment]
@yfaker Try to turnutils_uclient micro stun/turn client has many nice features for testing..
