### ISSUE TITLE
lost packets when server gets 'stressed'

### ISSUE THREAD

**Issue by jbaramidze** [coturn/coturn#51]
Hello.

I'm using coturn server to relay data. I'm using TCP protocol, and when I send too much data together (ChannelData messages themself are small, but I send lot of them together), receiving side starts losing packets. question is: why does this happen? why doesn't it stop accepting new packets instead if it cannot relay them so quickly? logs don't even show any warning. How can I avoid it? is the only solution to add some layer on top of those packets to make sure they get delivered before sending new ones? like implementing 'pseudo-tcp' layer?

here's how I reproduce it:

turnutils_uclient -T -v -y -z 1 -l 500 -n 300 -u user1 -w pass1 server1

**Comment by mom040267** [comment]
TURN was optimized for media applications. Dropping the packets is a more
efficient approach than end-to-end throughput check.

**Comment by jbaramidze** [comment]
what's the point of using TCP to talk to coturn then? if packets may still get lost?

**Comment by jbaramidze** [comment]
I was investigating code, can you please tell me at which part does the packets get lost?

**Comment by mom040267** [comment]
The only real reason to use TCP is to avoid limitations that some firewalls are setting on UDP.

**Comment by mom040267** [comment]
I do not have code right now before me but search for congestion control stuff.

I do not advise changing that part - the result may be unexpected and unpleasant.

**Comment by qvbige240** [comment]
I'm using coturn server to relay data and have the same problem. Have a reliable data transmission version or branch using TCP?  if just modify the variable "tcp_congestion_control " to 0, still lost packets
