### ISSUE TITLE
couldnot connect to turn server on 443 with turns enabled over enterprise network/ enterprise VPN

### ISSUE THREAD

**Issue by Sudheerkumar** [coturn/coturn#515]
Hi,

We are trying the following config urls in ice{turns:xx.xx..xx:443?transport=tcp,turn:xx.xx..xx:80?transport=tcp}

and we are not able to connect to the turn server. We could not see candidates gathering on trickle ice.

0.005	rtp	host	1516508954	udp	192.168.0.106	58213	126 | 30 | 255

I dont see other candidates like we get in stun:xx.xxx:80/3478/443 ports

Please help us on this. 

Note: we are able to **work** on stun:xxx:80/443 without enterprise network/VPN but not VPN case
If we put turns:xx.xx.xx:443 requests are not even reaching the server.

**Comment by Neustradamus** [comment]
@misi: Can you look?

**Comment by misi** [comment]
@Sudheerkumar Try to use turn on tcp 443 instead of  turns.. Is your TURN client support turns?

**Comment by eakraly** [comment]
Hi @Sudheerkumar 
Do you still have an issue?

**Comment by eakraly** [comment]
No response from OP - closing
