### ISSUE TITLE
How to restart the turn server if you changed a config value

### ISSUE THREAD

**Issue by rubo77** [coturn/coturn#520]
The readme is missing such a hint.

- are config values accepted immediately?
- do I have to restart?

if you run `turnserver -o` as a daemon, this is really unclear for a newbie.

**Comment by Neustradamus** [comment]
@misi: Can you look?

**Comment by misi** [comment]
@rubo77  You need to restart to reload config. Please send a Pull Request with a clarification to the readme I am happy to merge..

**Comment by rubo77** [comment]
In which file would you look for such a hint? The main Readme?

**Comment by misi** [comment]
I think here: https://github.com/coturn/coturn/blob/master/README.turnserver
Please notice that man page is also generated from this file..

**Comment by rubo77** [comment]
closed by https://github.com/coturn/coturn/pull/679
