### ISSUE TITLE
how to use full stun server with two public ip

### ISSUE THREAD

**Issue by jianminfly** [coturn/coturn#535]
I have a serve with two public ip and i want to test the stun server of coturn. this is my command `turnserver -f -v -a -m 2 --max-bps=100000 --min-port=32355 --max-port=65535 --user=phz:1 -r phzled.cn -X <public ip/ private ip> -X <public ip/ private ip>` . I can ping the two public ip successfully an test successfully on "https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/".But the result is same with testing use single public ip. I am confused , the documents say "In order to act as a STUN server, two different public IP addresses on the same machine are required,..".Why I have two different public ip , I still can not see the full stun server?

**Comment by localguru** [comment]
Very good question. From my understanding it's just a second `listening-ip=` entry in `/etc/turnserver.conf` like

```
listening-ip=1.1.1.1
listening-ip=1.1.1.2
```
But does that work, if the second IP is in the same subnet?

https://access.redhat.com/solutions/30564

**Comment by localguru** [comment]
And must both or all IPs point to the same DNS name?

**Comment by misi** [comment]
@localguru @jianminfly   use trunutils to test stun e.g.  turnutils_uclient  (and turnutils_stunclient)

**Comment by misi** [comment]
I don't see any coturn issue here. Please use the mailing list for help and discussion..
