### ISSUE TITLE
Nextcloud Talk turn server. Using the turn-server does not give a positive (any) result

### ISSUE THREAD

**Issue by graceastrid** [coturn/coturn#536]
My production server (but in a virtual machine):
- Centos Server 6.10
- Nextcloud 17.0.5
- coTurn v4.5.0.8
- 4 RAM
- 1Gbit channel
- Intel ® Xeon ® CPU E5-2670 0 @ 2.60GHz

Hello everybody! I installed Nextcloud Talk and when I try to talk via voice communication with more than two people (on different networks, not on the local network), problems arise: one of my friends can hear only one person, but he cannot hear the third one (the third one also does not hear him). Many different combinations of inoperability.
Problems and freezes when connecting new people to a voice call.

On the Internet, I found a solution to this problem - this is installing and configuring my own turn-server.
According to HowTo instructions: Setup Nextcloud Talk with TURN server HowTo: Setup Nextcloud Talk with TURN server I am on my separate server from Nextcloud (it is accessible all over the Internet, static IP address) installed and configured the turn server. But this did not give a result: as before, it is impossible to communicate normally and stably if more than two people participate in the conference. Problem saved.

I ask you for help in solving my problem.

I tried many different configurations, but all failed. I have so far settled on the configuration from the post above.

here are the settings from my tuneserver.conf file:
listening-port = 3478
fingerprint
use-auth-secret
static-auth-secret = XXXXXXXXxxxXXXXXXXXXXXxXXXXXXXXXa99cdcec03XxXxXxxx
realm = my-domain.host.ru
total-quota = 100
bps-capacity = 0
stale-nonce
no-loopback-peers

testing the turn-server through the NC admin panel is successful (a daw appears when testing the connection)

**Comment by ruedigerkupper** [comment]
Hi! Have you opened your listening-port 3478 in your firewall (or forwarded it to the right machine, in case you are behind a NAT router)?

**Comment by misi** [comment]
Check your browser ice logs. Open new tab on chrome `chrome://webrtc-internals` or in firefox `about:webrtc` and check ICE logs.
See my old codelab for  WebRTC ICE STUN/TURN misi.github.io/webrtc-c0d3l4b/ may it help to understand more. Or check ICE and STUN/TURN RFC-s.. This issue is not a coturn issue please use the mailing list for further discussion..
