### ISSUE TITLE
Delay in sending Allocation response for only first allocation request

### ISSUE THREAD

**Issue by chehefen** [coturn/coturn#537]
We are seeing coturn taking 2 seconds to send the first allocation response, which is the 401 response. This is the coturn server log:
```
2020-04-22 23:07:46,376: session 014000000000004394: realm <test> user <>: incoming packet message processed, error 401: Unauthorized
2020-04-22 23:07:48,357: IPv4. Local relay addr: 10.0.147.128:60692
2020-04-22 23:07:48,357: session 014000000000004394: new, realm=<test>, username=<test_user>, lifetime=600
```
The client connects to turn server using UDP. The allocation request was sent at 23:07:46 and the response was received at 23:07:48. Allocation requests after the first one all take less than 100ms to get the response. Does anybody know why the first request takes 2 seconds to process? Thanks.

**Comment by chehefen** [comment]
Turns out to be my own issue. Closing.

**Comment by dwydler** [comment]
Will you tell us, what was the problem?!

**Comment by chehefen** [comment]
After checking the tcpdump, the server hello arrived within a few milliseconds, but my application only detect it 2 seconds after sending the client hello. Turns out when I first run select() there were no socket in the list so it times out after 2s and pick up the socket fd and detect the incoming packet.
