### ISSUE TITLE
Behind NAT

### ISSUE THREAD

**Issue by nikhilrayaprolu** [coturn/coturn#54]
what is the minimum configuration to do to make my Turn server work behind NAT?
what are all ports I have to open for it to work behind NAT?
As I have read coturn comes with inbuilt STUN so can I use STUN address in my application instead of default google STUN mentioned here https://github.com/coturn/coturn/wiki/CoturnConfig
if so what should be my configuration there to be modified in the javascript object in RTCPeerConnection

**Comment by ttbek** [comment]
Why was this closed?
