### ISSUE TITLE
How to add multiple coturns to my infrastructure

### ISSUE THREAD

**Issue by Antoine-Sevec** [coturn/coturn#541]
Before coming to ask my question I searched for a lot of info on the general operation of a turn server.
And unfortunately, I couldn't find my answer... :/

@misi I hope you can help me :) 

So my infrastructure is:

publisher 1 ------- turn 1 --------- viewers 2

My problem arises when "turn 1" is at the maximum of these capabilities (CPU, Network)

So I imagined doing load distribution with coturn but I read that it was not feasible ...

So I don't understand how to increase the capacity of viewers that connects to publisher 1?

Do you have an idea, a lead, something?

For your info I read the RFC IETF, I did not understand everything so do not bother to send me read them ;)

**Comment by Antoine1535** [comment]
@misi @misi

**Comment by Neustradamus** [comment]
@misi: Can you look?

**Comment by misi** [comment]
@Antoine-Sevec Sorry for my late reply try to use REDIRECT-s see example in: https://github.com/coturn/coturn/tree/master/examples/scripts/loadbalance

**Comment by misi** [comment]
So one (or more) Redirect server(s) is just round robin redirects to other worker servers the clients..

**Comment by eakraly** [comment]
Another option is having a pool of turnservers whereas some other app (or maybe publisher itself) would chose from the pool using some mechanism (RR, or load based etc)
Another popular approach is to have a pool of turnservers with the same DNS record - and DNS provider doing RR across the pool. Each time turnserver is needed it will be resolved to a different IP.

If there are still questions - please reopen the issue
