### ISSUE TITLE
How to run Stun and Turn Servers using Public IPs

### ISSUE THREAD

**Issue by ShindeSwapnali** [coturn/coturn#545]
How to run Stun and Turn Servers using Public IPs

**Comment by localguru** [comment]
Could you please clarify your question a bit?

**Comment by ShindeSwapnali** [comment]
Instead of using Google Stun and Turn servers, I have installed them on my local windows machine.

So if I need to deploy my code on live servers, I will install all that on live server so Stun and Turn servers should be accessible by public IP..how could I make the relevant changes

**Comment by Syirrus** [comment]
> Instead of using Google Stun and Turn servers, I have installed them on my local windows machine.
> 
> So if I need to deploy my code on live servers, I will install all that on live server so Stun and Turn servers should be accessible by public IP..how could I make the relevant changes

Not sure exactly what you mean, but as you stated you will have to install Coturn on your server that is publicly accessible of course making sure all the port and firewall stuff is sorted out.

**Comment by misi** [comment]
Please use discussion the mailing list I don't feel it is a coturn issue..
