### ISSUE TITLE
Build issue with turnserver-4.5.0.3-CentOS7.1-x86_64.tar.gz

### ISSUE THREAD

**Issue by parnamis** [coturn/coturn#55]
Hi,

turnserver-4.5.0.3/install.sh points to http://download.fedoraproject.org/pub/epel/7/x86_64/e/ to download epel-release-7-6.noarch, which is updated with new version (epel-release-7-7.noarch) and old version removed from repo.
Causes build to fail, could we point it to different repo?

**Comment by mom040267** [comment]
fixed in 4.5.0.4
