### ISSUE TITLE
LibreSSL compilation failures

### ISSUE THREAD

**Issue by feinerer** [coturn/coturn#552]
Compilation with a current version of LibreSSL produces an error and a warning:

- [LibreSSL has no FIPS mode](https://marc.info/?l=openbsd-misc&m=139819485423701) so `FIPS_mode()` is not defined:
https://github.com/coturn/coturn/blob/113f13855a53aeb41ca5b71aa36b3f945cee2052/src/client/ns_turn_msg.c#L247-L249
https://github.com/coturn/coturn/blob/113f13855a53aeb41ca5b71aa36b3f945cee2052/src/client/ns_turn_msg.c#L257-L259

  A potential fix is to enclose both calls with `#ifdef OPENSSL_FIPS ... #endif` which was removed in https://github.com/coturn/coturn/commit/0e03fa86df3c2ba3afb3793c724d3579afd1ecf3 .

- Hardcoding an old OpenSSL version number if LibreSSL is detected
https://github.com/coturn/coturn/blob/113f13855a53aeb41ca5b71aa36b3f945cee2052/src/apps/common/ns_turn_openssl.h#L45-L48
causes a problem when compiling
https://github.com/coturn/coturn/blob/113f13855a53aeb41ca5b71aa36b3f945cee2052/src/apps/relay/dtls_listener.c#L209-L211 as newer LibreSSL versions need the `const` modifier.

  To address this either revisit the mapping of LibreSSL to an old OpenSSL version number or use an explicit `| defined(LIBRESSL_VERSION_NUMBER)` here.

**Comment by Neustradamus** [comment]
@misi: Can you look?

@feinerer A PR?

**Comment by Neustradamus** [comment]
@misi: Can you look? There is a PR!
