### ISSUE TITLE
Centos 7 RPM build

### ISSUE THREAD

**Issue by omaximenco** [coturn/coturn#556]
./CentOS7.pre.build.sh
./build.sh

Getting this error:
RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/share/turnserver/etc/cacert.pem
   /usr/share/turnserver/etc/coturn.service

4.5.1.1 works fine.

**Comment by misi** [comment]
It is fixed so I close it! Thanks for your contribution!
