### ISSUE TITLE
turnserver connections time out when blocking bogon ips.

### ISSUE THREAD

**Issue by schnitzi99** [coturn/coturn#557]
This is not a bug report but I wanted to share my findings somewhere and this seems to be the most appropriate place and google might find this. Feel free to place this somewhere else or close the issue. 

I wanted to set-up a very simple turnserver for Conversations.im video calls and for Nextcloud Talk. The problem was - sometimes it worked and sometimes it didn't. 

After looking into it very closely and debugging it step-by-step I realized the problem was my firewall set-up. I had a rule to block all bogons - so all IP addresses that never should talk to my server. My hardware is a dedicated root server with several public IPv4 ips - so the bogon list also includes all private IPs. And that caused my connections to drop with several errors:
* May 22 13:04:32  turnserver: 507: session 002000000000000005: closed (2nd stage), user <1590231801> realm <replaced-due-to-privacy> origin <>, local replaced-due-to-privacy:3478, remote replaced-due-to-privacy:1037, reason: TCP connection closed by client (callback)
* May 22 13:04:33  turnserver: 508: session 003000000000000008: closed (2nd stage), user <1590231801> realm <replaced-due-to-privacy> origin <>, local replaced-due-to-privacy:3478, remote replaced-due-to-privacy:1842, reason: allocation timeout
* "wrong nonce" also happened a couple of times.

So the solution was to remove all private ip blocks in the firewall and voila - working like a charm.
Also - please be aware that some bogon lists include private ips - so you might block connections to private ips without knowing (like in my case).

I hope this helps someone who gets stuck with this as well.

Cheers + Thanks everybody for all the work on coturn!

**Comment by misi** [comment]
@schnitzi99 Thanks for sharing your experience! 
I will close it, but it will be in the archive and google will find it. Thanks! 
(My suggestion to be careful about removing ip-s from firewall.)
