### ISSUE TITLE
Late logger option parsing from config file

### ISSUE THREAD

**Issue by dimaslv** [coturn/coturn#56]
Even if option "syslog" is defined in config file, small part of log is written to /var/log/turn_<PID>_<DATE>.log.
Example:
```
0: log file opened: /var/log/turn_26966_2016-08-19.log
0: 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.0.4 'dan Eider'
0: 
Max number of open files/sockets allowed for this process: 999999
0: 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 499500 (approximately)
0: 

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: DTLS 1.2 is not supported
0: TURN/STUN ALPN is not supported
0: Third-party authorization (oAuth) supported
0: GCM (AEAD) supported
0: OpenSSL compile-time version: OpenSSL 1.0.1e-fips 11 Feb 2013
0: 
0: SQLite supported, default database location is /var/db/turndb
0: Redis supported
0: PostgreSQL supported
0: MySQL supported
0: MongoDB is not supported
0: 
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================
```
All folowwing lines goes to syslog.
If I additionaly set command line option --syslog, then this part also goes to syslog.
So, I assume, that this part of log is generated before parsing config file.

**Comment by mom040267** [comment]
On Fri, Aug 19, 2016 at 4:55 AM, dimaslv <notifications@github.com> wrote:

> supported
>
> 0: OpenSSL compile-time version: OpenSSL 1.0.1e-fips 11 Feb 2013
> 0:
> 0: SQLite supported, default database location is /var/db/turndb
> 0: Redis supported
> 0: PostgreSQL supported
> 0: MySQL supported
> 0: MongoDB is not supported
> 0:
> 0: Default Net Engine version: 3 (UDP thread per CPU core)
>
> =====================================================
>
> All folowwing lines goes to syslog.
> If I additionaly set command line option --syslog, then this part also
> goes to syslog.
> So, I assume, that this part of log is generated before parsing config
> file.
>

yes, that's right

**Comment by dimaslv** [comment]
Why this issue was closed?

**Comment by mom040267** [comment]
Because we are not going to fix it and we do not consider it as a real problem.

Thanks
Oleg
