### ISSUE TITLE
Is there any api or method to get coturn current bandwidth usage for better load-balancing in application server?

### ISSUE THREAD

**Issue by FJEagle** [coturn/coturn#560]
We use a group of coturn servers for webrtc, and the application server will do the load-balancing by assigning proper coturn servers to  app clients to connect.

In our case, sometimes some of the coturn servers bandwidth usage is full, while others may be pretty idle, e.g., only half. 

Is it possible for us to get coturn server current bandwidth usage for better load-balancing in application server?

Thanks.

**Comment by misi** [comment]
@FJEagle  Sorry for my late reply! 
You can get this info from cli or you can just monitor your server instance network interface.
