### ISSUE TITLE
Strip ending spaces in configuration file

### ISSUE THREAD

**Issue by goudal-emmk** [coturn/coturn#561]
Hello,
I had a problem binding to tlls port. I finally found that in the configuration line
cert=<filepath> 
After three hours of research I found that I had a final white space on the file that was taken into account when opening the file, which is quite invisible when editing the file, and it's quite unusual in a configuration file to take the final spaces or tab into account.
I don't know if it's a feature, but as a user it's quite disturbing.
Furthermore there is no error message when coturn is unable to open the cert / key  file, it could be very helpful to add one.

Thanks in advance.

**Comment by misi** [comment]
Sorry for the late reply. I am busy with other tasks
Can you please send PR with it?

**Comment by misi** [comment]
I will close the issue, please send a PR if you have a fix..
