### ISSUE TITLE
Why always turn fail when using the physical machine deployment in the computer room

### ISSUE THREAD

**Issue by Spring3Coke** [coturn/coturn#565]
When I build coturn on the cloud service, he can return the done correctly, but when I use the physical machine in the machine room to build, it always gets stuck and times out and fails. I do n’t know what the reason is, which is very strange, I use the same deployment method. Can someone tell me what will be different when the physical machine is deployed?

Below is the error message：

Time | Component | Type | Foundation | Protocol | Address | Port | Priority
-- | -- | -- | -- | -- | -- | -- | --
0.009 | rtp | host | 3213931053 | udp | ecdcbd68-bd0c-4145-9909-348403bf5ae4.local | 61480 | 126 \| 30 \| 255
39.818 | Not reachable?
39.820

The server stun:156.255.211.83:3478 returned an error with code=701:
STUN server address is incompatible.
The server stun:156.255.211.83:3478 returned an error with code=701:
STUN allocate request timed out.
The server turn:156.255.211.83:3478?transport=udp returned an error with code=701:
TURN allocate request timed out.

and NIC information is :
eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 44:a8:42:2b:a2:6d brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.10/24 brd 172.16.0.255 scope global noprefixroute eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::46a8:42ff:fe2b:a26d/64 scope link 
       valid_lft forever preferred_lft forever

Thank you very much.

**Comment by Neustradamus** [comment]
@misi: Can you look?

**Comment by misi** [comment]
error code 701 cause IPv6 many times, and it is not always a real error..

**Comment by misi** [comment]
I can't help more so I close it.
