### ISSUE TITLE
How many udp ports are needed to communicate with peers via turn server?

### ISSUE THREAD

**Issue by sungwoo91** [coturn/coturn#568]
Hello,

I implemented WebRTC application and use coturn for turnserver.
We conducted a performance test and the following result was obtained.

All users are in the same room. And Network A and B are separated.

Network A : 5 people
Network B : 5 people

As a result of the test, 180 udp ports were used.

Is it correct that 10 users used 180 ports in two separate networks?
If this is correct, is there a way to calculate roughly?

**Comment by misi** [comment]
IT depends of your webrtc application and setup. multiplexing rtp/rtcp, and bundling.
