### ISSUE TITLE
About read-timeout of MySQL

### ISSUE THREAD

**Issue by oolong-high** [coturn/coturn#57]
[Assumed cause]
Because "MYSQL_OPT_READ_TIMEOUT" is not set, coturn cannot detect mysql_ping timeout.
I think coturn shoud have "READ_TIMEOUT" setting(like tomcat) to detect mysql_ping timeout.

[Possible modification]
Set "READ_TIMEOUT" just after coturn sets "CONNECT_TIMEOUT".

[Target source]
coturn-master\src\apps\relay\dbdrivers\dbd_mysql.c

**Comment by misi** [comment]
Could you please send a pull request?

**Comment by mom040267** [comment]
I committed fix for that. It will be officially supported in 4.5.0.5.
