### ISSUE TITLE
Question regarding reliability when using tcp exclusively for client-server communication and server-peer relaying.

### ISSUE THREAD

**Issue by bishophu** [coturn/coturn#58]
I am currently trying to implement a peer-to-peer file transfer application, which is quite different for the common use of TURN for real-time communication that is not so sensitive about data loss.

So I'm wondering if I use tcp for client to TURN server communication and server-peer relaying, do I have the reliability as if the client connects to peer directly over tcp? Or do I still have to implement reliability at application level?

**Comment by misi** [comment]
AFAIK, to be on the safe side please implement application level reliability. 
(If you use WebRTC stack, in WebRTC in data transfer the sctp solves this for you.)

**Comment by mom040267** [comment]
It is reliable if the server is not overloaded. Otherwise, it will start dropping messages.

**Comment by bishophu** [comment]
@mom040267 Does the client/peer get notified if their message is dropped?

**Comment by mom040267** [comment]
No. How they can be notified ? There is no such a provision in Turn protocol.

**Comment by bishophu** [comment]
@mom040267 From my understanding of RFC 6062, if the receiving side of the client/peer pair is slow, the TURN server should properly back pressure the sender if the pre-configured buffer is full rather than drop the message

section 5.4

>    Otherwise, the client connection is now called a client data
   connection.  Data received on it MUST be sent as-is to the associated
   peer data connection.

**Comment by mom040267** [comment]
On Thu, Aug 25, 2016 at 9:10 AM, Binshuo Hu <notifications@github.com>
wrote:

> @mom040267 <https://github.com/mom040267> From my understanding of RFC
> 6062, if the receiving side of the client/peer pair is slow, the TURN
> server should properly back pressure the sender if the pre-configured
> buffer is full rather than drop the message
>
This is what we are trying to do, actually.

But there is no such explicit requirement in the text. The section 5.4
could be understood differently.

Realistically, it is not very possibly on a multi-user server.

Oleg

**Comment by bishophu** [comment]
I see, thanks for the explanation.
