### ISSUE TITLE
coturn ha with haproxy problem

### ISSUE THREAD

**Issue by c0r3dump3d** [coturn/coturn#580]
Hi, I'm trying to use coturn in HA with haproxy in tcp transparent mode for a BBB service. But I found that with some clients, not all, has an error with ICE (1007). If I change in BBB to a coturn server that doesn't pass for the haproxy the BBB works fine,  it seems a problem of coturn behind haproxy. Does anyone have experience with coturn and haproxy?

In the log I see only that the client suddenly close de connection:

```
Jun 15 17:10:48 turn00ha turnserver: 121: session 000000000000000003: TCP socket closed remotely 80.*.*.*:54097
Jun 15 17:10:48 turn00ha turnserver: 121: session 000000000000000003: closed (2nd stage), user <1592320246:w_qfoodioudy05> realm <pre.csic.es> origin <>, local 10.100.8.188:3478, remote 80.*.*.*:54097, reason: TCP connection closed by client (callback)


```

**Comment by misi** [comment]
I don't have a setup with HA proxy so unfortunately I can't provide you help.

**Comment by c0r3dump3d** [comment]
Ok, but it's a problem that coturn doesn't work with haproxy because haproxy doesn't work with upd traffic?

**Comment by misi** [comment]
It depends on TURN client settings so Browser/BBB settings

**Comment by c0r3dump3d** [comment]
What is that dependency?

**Comment by misi** [comment]
How you set iceServer url in your browser, to use udp or tcp transport.

**Comment by c0r3dump3d** [comment]
My BBB server it's config to use tcp transport.

**Comment by c4m4** [comment]
is there any way to put this daemon in HA?

**Comment by misi** [comment]
@c4m4 You can loadbalance roundrobin see:https://github.com/coturn/coturn/tree/master/examples/scripts/loadbalance

@c0r3dump3d 
If your BBB server configures the browser's ICE agent to use TCP is only one part. In Webrtc it is not implemented AFAIK in any Browsers to request transport protocol. So server will allocate a UDP port by default. HTH

**Comment by c4m4** [comment]
@misi but what happen if the master goes down?

**Comment by misi** [comment]
@c4m4 Master is not handle any traffic just send STUN redirects ALTERNATE-SERVER
You can have multiple master..

**Comment by c4m4** [comment]
@misi thanks for your quick response, So my client could 2 master and behind these master a could multiple servers? if the answer is yes, it look good to me :)

**Comment by misi** [comment]
@c4m4  It is not behind, in reality the master server are just sending back a redirect to the real servers..
So yes. I hope it will work as you expected..
