### ISSUE TITLE
API key expiration

### ISSUE THREAD

**Issue by Astagor** [coturn/coturn#581]
As the API keys are valid for 1 year, so you have to remember to update  every year all configurations using the API to get the TRUN servers. Maybe the keys should be valid for a longer time or you can set while creating that they never expire, just like the login and password. Of course in the admin, you could manually revoke a key, if it gets compromised.

**Comment by misi** [comment]
Your request is not related to coturn.. Sorry I close it here. It is related to edu implementation.
https://github.com/misi/stun-ansible
