### ISSUE TITLE
The google group from the README doesn't exist or is not public

### ISSUE THREAD

**Issue by lockywolf** [coturn/coturn#582]
The google group for coturn, listed in the README, [https://groups.google.com/forum/#!forum/turn-server-project-rfc5766-turn-server](https://groups.google.com/forum/#!forum/turn-server-project-rfc5766-turn-server) is apparently deleted, or not public. Cannot be opened.

**Comment by Neustradamus** [comment]
@misi: Can you look?

**Comment by misi** [comment]
@Neustradamus  @lockywolf  I can open the link. Can you please double check, and if you still can't open it please let me know.
Thanks!

**Comment by lockywolf** [comment]
Seems to be working now.
