### ISSUE TITLE
port blocking woes -- don't lock yourself out

### ISSUE THREAD

**Issue by fippo** [coturn/coturn#584]
if one applies the very reasonable advice from https://www.rtcsec.com/2020/04/01-slack-webrtc-turn-compromise/#how-to-fix-an-open-turn-relay-to-address-this-vulnerability
there is an issue when using an external ip. It gets blocked.
Workaround: allow your external ip using --allowed-peer-ip

Suppose the following config:
```
user=foo:bar
realm=something
no-multicast-peers
no-loopback-peers
external-ip=8.8.8.8
listen-ip=127.0.0.1
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.0.0.0-192.0.0.255
denied-peer-ip=192.0.2.0-192.0.2.255
denied-peer-ip=192.88.99.0-192.88.99.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=198.18.0.0-198.19.255.255
denied-peer-ip=198.51.100.0-198.51.100.255
denied-peer-ip=203.0.113.0-203.0.113.255
denied-peer-ip=240.0.0.0-255.255.255.255
```
and the following piece of javascript
```
const iceTransportPolicy = 'relay';
const iceServers = [{urls: 'turn:127.0.0.1:3478?transport=udp', username: "foo", credential: "bar"}];
const pc1 = new RTCPeerConnection({iceServers, iceTransportPolicy});
const pc2 = new RTCPeerConnection({iceServers, iceTransportPolicy});
pc1.onicecandidate = (e) => e.candidate && e.candidate.candidate.indexOf("relay") !== -1 && pc2.addIceCandidate(e.candidate);
//pc2.onicecandidate = (e) => e.candidate && e.candidate.candidate.indexOf("relay") !== -1 && pc1.addIceCandidate(e.candidate);
pc1.createDataChannel(".");
async function run() {
  const offer = await pc1.createOffer();
  await pc1.setLocalDescription(offer);
  await pc2.setRemoteDescription(offer);
  const answer = await pc2.createAnswer();
  await pc2.setLocalDescription(answer);
  await pc1.setRemoteDescription(answer);
}
run();
```
(pc2.onicecandidate is commented out to reduce the number of createPermission requests)

This doesn't connect as can be seen in webrtc-internals.
When using wireshark, one can see that the create permission request is denied because of a forbidden ip. Now... that IP isn't part of the blocklist, right?

Debugging this is a pretty long story so here is the tl;dr:
- [this maps the public/external ip in the stun request into the internal one](https://github.com/coturn/coturn/blob/4badbbf018733810c98af3e0a519383cdb969f86/src/client/ns_turn_msg.c#L1474)
- [this rejects the allocation creation](https://github.com/coturn/coturn/blob/4badbbf018733810c98af3e0a519383cdb969f86/src/server/ns_turn_server.c#L3127)
because it is now checked against the private ip, not the public/external one.

**Comment by misi** [comment]
@fippo Sorry for my delayed reply. I am working on #583 after it I will get back to you.

**Comment by misi** [comment]
You used in your report 127.0.0.1 as ICEservers in the ICE agent/browser that I think is causing the issue. 
You should set the global IP address of your turn server. 
Have you tried it that way?

**Comment by fippo** [comment]
yes, I actually found out while debugging the meet.jit.si production servers. Reproduces on AWS instances as well.

**Comment by misi** [comment]
@fippo Sorry but I don't fully understand your answer. 
If you use public ip in ICE servers config does solve the problem or not?

If it still does not work, then can you please share more details about the ICE connection logs or what you tried and how can I reproduce it?

**Comment by fippo** [comment]
@misi it doesn't matter that I used localhost as an ip but I thought it would be easier to reproduce.

The same happens if I configure it on a GCE instance, e.g. with
```
external-ip=35.223.199.204
listen-ip=10.128.0.2
```
for an instance I spun up (and allowed udp) and the rest of the configuration as above and then modifying the JS to use 35.223.199.204 instead of 127.0.0.1.
Wireshark dump (pcapng, zipped): [denied.zip](https://github.com/coturn/coturn/files/4827149/denied.zip)
Packet 13 shows the create permission request which is denied in packet  17.
coturn logs the following:
```
283: ERROR: A peer IP 10.128.0.2 denied in the range: 10.0.0.0-10.255.255.255
```

Adding `--allowed-peer-ip=10.128.0.2` to the command line fixed that, see this wireshark dump: [allowed.zip](https://github.com/coturn/coturn/files/4827150/allowed.zip)

**Comment by misi** [comment]
Can I ask you to share your browser (ICE agent) logs too?

**Comment by misi** [comment]
Many thanks for the detailed report I will try to fix it.

**Comment by fippo** [comment]
chrome debug logs (do you know how to interpret them? Then beware, you are being volunteered to write a webrtchacks post!) or webrtc-internals?

i'm not sure what the best way to fix this is but suspect that simply adding the external ip to the whitelist by default is the most side-effect free change.

**Comment by misi** [comment]
I will fix it after the next release. Your idea to add one IP automatically is simple nice and clean. 
I will try to find time to test it. So I can collect than myself everything and see the full picture with logs. 
Chrome, Firefox browser logs, and webrtc-internals.

**Comment by misi** [comment]
@fippo  I am wondering about in your use case the NAT is a DNAT, right?
This way I am thinking about what if we do not map PEER-ADDERESS at all. 
What do you think?

**Comment by fippo** [comment]
@misi sorry for the delay! That is the normal aws or gce deployment (a bit sad but...)
Since [this](https://github.com/coturn/coturn/blob/4badbbf018733810c98af3e0a519383cdb969f86/src/client/ns_turn_msg.c#L1474) seems to be the only place where the backmapping happens it might be easy to remove.
But adding the external ip to the whitelist is less risk and requires less testing ;-)

**Comment by misi** [comment]
@fippo I added to white list the private IP part of the `external-ip` as discussed. Please test it..
See:
https://github.com/coturn/coturn/commit/6101ebd51b6731464ab346ae70159e8312d0b3c6

**Comment by misi** [comment]
I will close it because I feel it has been resolved. Please comment if there is anything I left out, and I will reopen  the issue..
Thanks!
