### ISSUE TITLE
SQLite connection was closed.

### ISSUE THREAD

**Issue by scott17090025902** [coturn/coturn#586]
when exeute  "turnadmin -a -u gst -p 123456 -r demo",appear this message.
--db /usr/local/var/db/turndb is not useful.
turnserver.conf  userdb=/usr/local/var/db/turndb is not useful two.

**Comment by chanduthedev** [comment]
Hi @scott17090025902 make sure db file has write permission. I also faced this issue, DB was updated once I update write permissions by giving DB file to admin access. Below is the command I used for adding user to the db.

`turnadmin -k -a -u chanduthedev -p test -r demo -b ~/Downloads/STUN_TURN/turndb `

**Comment by scott17090025902** [comment]
> Hi @scott17090025902 make sure db file has write permission. I also faced this issue, DB was updated once I update write permissions by giving DB file to admin access. Below is the command I used for adding user to the db.
> 
> `turnadmin -k -a -u chanduthedev -p test -r demo -b ~/Downloads/STUN_TURN/turndb `

Thank You.Maybe is version's error.When I reinstall,it fixed.

**Comment by misi** [comment]
I will close this..
