### ISSUE TITLE
Proxied Cloudflare to AWS ec2 - Coturn

### ISSUE THREAD

**Issue by K12AZ** [coturn/coturn#589]
I have installed coturn on AWS EC2. (Static IP)

1. Works fine
---------------

DNS Managed by Cloudflare 
I have created a subdomain turn.example.com and pointed to AWS EC2
This setup works fine.

Works fine means, two peers are connected and videos transmitted. 

2. Not working
-----------------

When I proxied to AWS EC2, not working. 

Does anyone face this issue? Looking forward

**Comment by misi** [comment]
What do you mean proxied to AWS EC2? 
DNAT?

**Comment by K12AZ** [comment]
![image](https://user-images.githubusercontent.com/63956726/86200921-95bb8280-bb90-11ea-95f7-9de0de9aebdf.png)

I mean this

**Comment by wolmi** [comment]
On the proxy mode of Cloudflare not all the ports and protocols are available.

Here you have an official list from Cloudflare
https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with-

**Comment by misi** [comment]
@K12AZ It seems from the infos you have provided that for me it is cloudflare proxy issue..
@wolmi Thanks for your help and clarification.
