### ISSUE TITLE
crash in coturn-4.5.0.8

### ISSUE THREAD

**Issue by 519790441** [coturn/coturn#590]
I have several coturn servers to run RFC6062 relay service, one server crashes every other month or so, and the other servers are normal.

bind: Address already in use
bind: Address already in use
bind: Address already in use
bind: Address already in use
bind: Address already in use
bind: Address already in use
*** glibc detected *** turnserver: corrupted double-linked list: 0x00007ff88189fd20 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x75e5e)[0x7ff8a33c6e5e]
/lib64/libc.so.6(+0x76263)[0x7ff8a33c7263]
/lib64/libc.so.6(+0x79c28)[0x7ff8a33cac28]
/lib64/libc.so.6(__libc_malloc+0x5c)[0x7ff8a33cbb1c]
/usr/local/lib/libevent_core-2.1.so.6(+0xae48)[0x7ff8a3d18e48]
/usr/local/lib/libevent_core-2.1.so.6(evbuffer_expand_fast_+0x34f)[0x7ff8a3d1cd1f]
/usr/local/lib/libevent_core-2.1.so.6(evbuffer_read+0xc6)[0x7ff8a3d1d026]
/usr/local/lib/libevent_core-2.1.so.6(+0x15fd8)[0x7ff8a3d23fd8]
/usr/local/lib/libevent_core-2.1.so.6(+0x1c617)[0x7ff8a3d2a617]
/usr/local/lib/libevent_core-2.1.so.6(event_base_loop+0x34f)[0x7ff8a3d2ae1f]
turnserver[0x41aa93]
turnserver[0x41afd5]
/lib64/libpthread.so.0(+0x7aa1)[0x7ff8a313baa1]
/lib64/libc.so.6(clone+0x6d)[0x7ff8a3439c4d]
======= Memory map: ========
00400000-0046e000 r-xp 00000000 fd:01 2249611                            /usr/local/bin/turnserver
0066d000-00679000 rw-p 0006d000 fd:01 2249611                            /usr/local/bin/turnserver
00679000-006b0000 rw-p 00000000 00:00 0 
011d1000-01213000 rw-p 00000000 00:00 0                                  [heap]
7ff864000000-7ff864021000 rw-p 00000000 00:00 0 
7ff864021000-7ff868000000 ---p 00000000 00:00 0 
7ff86c000000-7ff86fa8a000 rw-p 00000000 00:00 0 
7ff86fa8a000-7ff870000000 ---p 00000000 00:00 0 
7ff870000000-7ff8737f1000 rw-p 00000000 00:00 0 
7ff8737f1000-7ff874000000 ---p 00000000 00:00 0 
7ff874000000-7ff878000000 rw-p 00000000 00:00 0 
7ff878000000-7ff87bfff000 rw-p 00000000 00:00 0 
7ff87bfff000-7ff87c000000 ---p 00000000 00:00 0 
7ff87c000000-7ff880000000 rw-p 00000000 00:00 0 
7ff880000000-7ff883ffd000 rw-p 00000000 00:00 0 
7ff883ffd000-7ff884000000 ---p 00000000 00:00 0 
7ff884000000-7ff88426d000 rw-p 00000000 00:00 0 
7ff88426d000-7ff888000000 ---p 00000000 00:00 0 
7ff888000000-7ff88a68e000 rw-p 00000000 00:00 0 
7ff88a68e000-7ff88c000000 ---p 00000000 00:00 0 
7ff88c000000-7ff88c021000 rw-p 00000000 00:00 0 
7ff88c021000-7ff890000000 ---p 00000000 00:00 0 
7ff890000000-7ff89026d000 rw-p 00000000 00:00 0 
7ff89026d000-7ff894000000 ---p 00000000 00:00 0 
7ff894000000-7ff898000000 rw-p 00000000 00:00 0 
7ff899ce5000-7ff899cfb000 r-xp 00000000 fd:01 2241644                    /lib64/libgcc_s-4.4.7-20120601.so.1
7ff899cfb000-7ff899efa000 ---p 00016000 fd:01 2241644                    /lib64/libgcc_s-4.4.7-20120601.so.1
7ff899efa000-7ff899efb000 rw-p 00015000 fd:01 2241644                    /lib64/libgcc_s-4.4.7-20120601.so.1
7ff899efb000-7ff899ffc000 rw-p 00000000 00:00 0 
7ff899ffc000-7ff899ffd000 ---p 00000000 00:00 0 
7ff899ffd000-7ff89a7fd000 rw-p 00000000 00:00 0 
7ff89a7fd000-7ff89a7fe000 ---p 00000000 00:00 0 
7ff89a7fe000-7ff89affe000 rw-p 00000000 00:00 0 
7ff89affe000-7ff89afff000 ---p 00000000 00:00 0 
7ff89afff000-7ff89b7ff000 rw-p 00000000 00:00 0 
7ff89b7ff000-7ff89b800000 ---p 00000000 00:00 0 
7ff89b800000-7ff89c000000 rw-p 00000000 00:00 0 
7ff89c000000-7ff89fffe000 rw-p 00000000 00:00 0 
7ff89fffe000-7ff8a0000000 ---p 00000000 00:00 0 
7ff8a0038000-7ff8a0045000 r-xp 00000000 fd:01 2241717                    /lib64/libnss_files-2.12.so
7ff8a0045000-7ff8a0244000 ---p 0000d000 fd:01 2241717                    /lib64/libnss_files-2.12.so
7ff8a0244000-7ff8a0245000 r--p 0000c000 fd:01 2241717                    /lib64/libnss_files-2.12.so
7ff8a0245000-7ff8a0246000 rw-p 0000d000 fd:01 2241717                    /lib64/libnss_files-2.12.so
7ff8a0246000-7ff8a0347000 rw-p 00000000 00:00 0 
7ff8a0347000-7ff8a0448000 rw-p 00000000 00:00 0 
7ff8a0448000-7ff8a04a9000 rw-p 00000000 00:00 0 
7ff8a04a9000-7ff8a050b000 rw-p 00000000 00:00 0 
7ff8a058c000-7ff8a078d000 rw-p 00000000 00:00 0 
7ff8a078d000-7ff8a078e000 ---p 00000000 00:00 0 
7ff8a078e000-7ff8a118f000 rw-p 00000000 00:00 0 
7ff8a118f000-7ff8a1190000 ---p 00000000 00:00 0 
7ff8a1190000-7ff8a1d92000 rw-p 00000000 00:00 0 
7ff8a1d92000-7ff8a1daf000 r-xp 00000000 fd:01 2241746                    /lib64/libselinux.so.1
7ff8a1daf000-7ff8a1fae000 ---p 0001d000 fd:01 2241746                    /lib64/libselinux.so.1
7ff8a1fae000-7ff8a1faf000 r--p 0001c000 fd:01 2241746                    /lib64/libselinux.so.1
7ff8a1faf000-7ff8a1fb0000 rw-p 0001d000 fd:01 2241746                    /lib64/libselinux.so.1
7ff8a1fb0000-7ff8a1fb1000 rw-p 00000000 00:00 0 
7ff8a1fb1000-7ff8a1fb3000 r-xp 00000000 fd:01 2241685                    /lib64/libkeyutils.so.1.3
7ff8a1fb3000-7ff8a21b2000 ---p 00002000 fd:01 2241685                    /lib64/libkeyutils.so.1.3
7ff8a21b2000-7ff8a21b3000 r--p 00001000 fd:01 2241685                    /lib64/libkeyutils.so.1.3
7ff8a21b3000-7ff8a21b4000 rw-p 00002000 fd:01 2241685                    /lib64/libkeyutils.so.1.3
7ff8a21b4000-7ff8a21be000 r-xp 00000000 fd:01 2241689                    /lib64/libkrb5support.so.0.1
7ff8a21be000-7ff8a23bd000 ---p 0000a000 fd:01 2241689                    /lib64/libkrb5support.so.0.1
7ff8a23bd000-7ff8a23be000 r--p 00009000 fd:01 2241689                    /lib64/libkrb5support.so.0.1
7ff8a23be000-7ff8a23bf000 rw-p 0000a000 fd:01 2241689                    /lib64/libkrb5support.so.0.1
7ff8a23bf000-7ff8a23e8000 r-xp 00000000 fd:01 2241683                    /lib64/libk5crypto.so.3.1
7ff8a23e8000-7ff8a25e8000 ---p 00029000 fd:01 2241683                    /lib64/libk5crypto.so.3.1
7ff8a25e8000-7ff8a25e9000 r--p 00029000 fd:01 2241683                    /lib64/libk5crypto.so.3.1
7ff8a25e9000-7ff8a25ea000 rw-p 0002a000 fd:01 2241683                    /lib64/libk5crypto.so.3.1
7ff8a25ea000-7ff8a25eb000 rw-p 00000000 00:00 0 
7ff8a25eb000-7ff8a25ee000 r-xp 00000000 fd:01 2241630                    /lib64/libcom_err.so.2.1
7ff8a25ee000-7ff8a27ed000 ---p 00003000 fd:01 2241630                    /lib64/libcom_err.so.2.1
7ff8a27ed000-7ff8a27ee000 r--p 00002000 fd:01 2241630                    /lib64/libcom_err.so.2.1
7ff8a27ee000-7ff8a27ef000 rw-p 00003000 fd:01 2241630                    /lib64/libcom_err.so.2.1
7ff8a27ef000-7ff8a28cb000 r-xp 00000000 fd:01 2241687                    /lib64/libkrb5.so.3.3
7ff8a28cb000-7ff8a2aca000 ---p 000dc000 fd:01 2241687                    /lib64/libkrb5.so.3.3
7ff8a2aca000-7ff8a2ad4000 r--p 000db000 fd:01 2241687                    /lib64/libkrb5.so.3.3
7ff8a2ad4000-7ff8a2ad6000 rw-p 000e5000 fd:01 2241687                    /lib64/libkrb5.so.3.3
7ff8a2ad6000-7ff8a2b17000 r-xp 00000000 fd:01 2241659                    /lib64/libgssapi_krb5.so.2.2
7ff8a2b17000-7ff8a2d17000 ---p 00041000 fd:01 2241659                    /lib64/libgssapi_krb5.so.2.2
7ff8a2d17000-7ff8a2d18000 r--p 00041000 fd:01 2241659                    /lib64/libgssapi_krb5.so.2.2
7ff8a2d18000-7ff8a2d1a000 rw-p 00042000 fd:01 2241659                    /lib64/libgssapi_krb5.so.2.2
7ff8a2d1a000-7ff8a2d2f000 r-xp 00000000 fd:01 2241762                    /lib64/libz.so.1.2.3
7ff8a2d2f000-7ff8a2f2e000 ---p 00015000 fd:01 2241762                    /lib64/libz.so.1.2.3
7ff8a2f2e000-7ff8a2f2f000 r--p 00014000 fd:01 2241762                    /lib64/libz.so.1.2.3
7ff8a2f2f000-7ff8a2f30000 rw-p 00015000 fd:01 2241762                    /lib64/libz.so.1.2.3
7ff8a2f30000-7ff8a2f32000 r-xp 00000000 fd:01 2241636                    /lib64/libdl-2.12.so
7ff8a2f32000-7ff8a3132000 ---p 00002000 fd:01 2241636                    /lib64/libdl-2.12.so
7ff8a3132000-7ff8a3133000 r--p 00002000 fd:01 2241636                    /lib64/libdl-2.12.so
7ff8a3133000-7ff8a3134000 rw-p 00003000 fd:01 2241636                    /lib64/libdl-2.12.so
7ff8a3134000-7ff8a314b000 r-xp 00000000 fd:01 2241738                    /lib64/libpthread-2.12.so
7ff8a314b000-7ff8a334b000 ---p 00017000 fd:01 2241738                    /lib64/libpthread-2.12.so
7ff8a334b000-7ff8a334c000 r--p 00017000 fd:01 2241738                    /lib64/libpthread-2.12.so
7ff8a334c000-7ff8a334d000 rw-p 00018000 fd:01 2241738                    /lib64/libpthread-2.12.so
7ff8a334d000-7ff8a3351000 rw-p 00000000 00:00 0 
7ff8a3351000-7ff8a34dc000 r-xp 00000000 fd:01 2241623                    /lib64/libc-2.12.so
7ff8a34dc000-7ff8a36db000 ---p 0018b000 fd:01 2241623                    /lib64/libc-2.12.so
7ff8a36db000-7ff8a36df000 r--p 0018a000 fd:01 2241623                    /lib64/libc-2.12.so
7ff8a36df000-7ff8a36e1000 rw-p 0018e000 fd:01 2241623                    /lib64/libc-2.12.so
7ff8a36e1000-7ff8a36e5000 rw-p 00000000 00:00 0 
7ff8a36e5000-7ff8a36e7000 r-xp 00000000 fd:01 2249698                    /usr/local/lib/libevent_pthreads-2.1.so.6.0.2
7ff8a36e7000-7ff8a38e6000 ---p 00002000 fd:01 2249698                    /usr/local/lib/libevent_pthreads-2.1.so.6.0.2
7ff8a38e6000-7ff8a38e7000 rw-p 00001000 fd:01 2249698                    /usr/local/lib/libevent_pthreads-2.1.so.6.0.2
7ff8a38e7000-7ff8a38ec000 r-xp 00000000 fd:01 2249693                    /usr/local/lib/libevent_openssl-2.1.so.6.0.2
7ff8a38ec000-7ff8a3aec000 ---p 00005000 fd:01 2249693                    /usr/local/lib/libevent_openssl-2.1.so.6.0.2
7ff8a3aec000-7ff8a3aed000 rw-p 00005000 fd:01 2249693                    /usr/local/lib/libevent_openssl-2.1.so.6.0.2
7ff8a3aed000-7ff8a3b0e000 r-xp 00000000 fd:01 2249688                    /usr/local/lib/libevent_extra-2.1.so.6.0.2
7ff8a3b0e000-7ff8a3d0d000 ---p 00021000 fd:01 2249688                    /usr/local/lib/libevent_extra-2.1.so.6.0.2
7ff8a3d0d000-7ff8a3d0e000 rw-p 00020000 fd:01 2249688                    /usr/local/lib/libevent_extra-2.1.so.6.0.2
7ff8a3d0e000-7ff8a3d40000 r-xp 00000000 fd:01 2249683                    /usr/local/lib/libevent_core-2.1.so.6.0.2
7ff8a3d40000-7ff8a3f3f000 ---p 00032000 fd:01 2249683                    /usr/local/lib/libevent_core-2.1.so.6.0.2
7ff8a3f3f000-7ff8a3f41000 rw-p 00031000 fd:01 2249683                    /usr/local/lib/libevent_core-2.1.so.6.0.2
7ff8a3f41000-7ff8a3fa3000 r-xp 00000000 fd:01 2247298                    /usr/lib64/libssl.so.1.0.1e
7ff8a3fa3000-7ff8a41a3000 ---p 00062000 fd:01 2247298                    /usr/lib64/libssl.so.1.0.1e
7ff8a41a3000-7ff8a41a7000 r--p 00062000 fd:01 2247298                    /usr/lib64/libssl.so.1.0.1e
7ff8a41a7000-7ff8a41ad000 rw-p 00066000 fd:01 2247298                    /usr/lib64/libssl.so.1.0.1e
7ff8a41ad000-7ff8a4367000 r-xp 00000000 fd:01 2247125                    /usr/lib64/libcrypto.so.1.0.1e
7ff8a4367000-7ff8a4567000 ---p 001ba000 fd:01 2247125                    /usr/lib64/libcrypto.so.1.0.1e
7ff8a4567000-7ff8a4582000 r--p 001ba000 fd:01 2247125                    /usr/lib64/libcrypto.so.1.0.1e
7ff8a4582000-7ff8a458e000 rw-p 001d5000 fd:01 2247125                    /usr/lib64/libcrypto.so.1.0.1e
7ff8a458e000-7ff8a4592000 rw-p 00000000 00:00 0 
7ff8a4592000-7ff8a45a8000 r-xp 00000000 fd:01 2241742                    /lib64/libresolv-2.12.so
7ff8a45a8000-7ff8a47a8000 ---p 00016000 fd:01 2241742                    /lib64/libresolv-2.12.so
7ff8a47a8000-7ff8a47a9000 r--p 00016000 fd:01 2241742                    /lib64/libresolv-2.12.so
7ff8a47a9000-7ff8a47aa000 rw-p 00017000 fd:01 2241742                    /lib64/libresolv-2.12.so
7ff8a47aa000-7ff8a47ac000 rw-p 00000000 00:00 0 
7ff8a47ac000-7ff8a47c2000 r-xp 00000000 fd:01 2241710                    /lib64/libnsl-2.12.so
7ff8a47c2000-7ff8a49c1000 ---p 00016000 fd:01 2241710                    /lib64/libnsl-2.12.so
7ff8a49c1000-7ff8a49c2000 r--p 00015000 fd:01 2241710                    /lib64/libnsl-2.12.so
7ff8a49c2000-7ff8a49c3000 rw-p 00016000 fd:01 2241710                    /lib64/libnsl-2.12.so
7ff8a49c3000-7ff8a49c5000 rw-p 00000000 00:00 0 
7ff8a49c5000-7ff8a49cc000 r-xp 00000000 fd:01 2241744                    /lib64/librt-2.12.so
7ff8a49cc000-7ff8a4bcb000 ---p 00007000 fd:01 2241744                    /lib64/librt-2.12.so
7ff8a4bcb000-7ff8a4bcc000 r--p 00006000 fd:01 2241744                    /lib64/librt-2.12.so
7ff8a4bcc000-7ff8a4bcd000 rw-p 00007000 fd:01 2241744                    /lib64/librt-2.12.so
7ff8a4bcd000-7ff8a4bdc000 r-xp 00000000 fd:01 2249704                    /usr/local/lib/libhiredis.so.0.13
7ff8a4bdc000-7ff8a4ddb000 ---p 0000f000 fd:01 2249704                    /usr/local/lib/libhiredis.so.0.13
7ff8a4ddb000-7ff8a4ddc000 rw-p 0000e000 fd:01 2249704                    /usr/local/lib/libhiredis.so.0.13
7ff8a4ddc000-7ff8a4dfc000 r-xp 00000000 fd:01 2241604                    /lib64/ld-2.12.so
7ff8a4e14000-7ff8a4e45000 rw-p 00000000 00:00 0 
7ff8a4f48000-7ff8a4fa9000 rw-p 00000000 00:00 0 
7ff8a4fbb000-7ff8a4ff7000 rw-p 00000000 00:00 0 
7ff8a4ff9000-7ff8a4ffc000 rw-p 00000000 00:00 0 
7ff8a4ffc000-7ff8a4ffd000 r--p 00020000 fd:01 2241604                    /lib64/ld-2.12.so
7ff8a4ffd000-7ff8a4ffe000 rw-p 00021000 fd:01 2241604                    /lib64/ld-2.12.so
7ff8a4ffe000-7ff8a4fff000 rw-p 00000000 00:00 0 
7ffc35e3b000-7ffc35e5c000 rw-p 00000000 00:00 0                          [stack]

**Comment by misi** [comment]
Please upgrade to the latest versions 4.5.1.3 and test it if the issue still exists

**Comment by 519790441** [comment]
> Please upgrade to the latest versions 4.5.1.3 and test it if the issue still exists

OK, I will try the latest version later.
Also, is the problem related to multithreading?
When I configured, the default parameters were used, so that one CPU used one thread.
This server, which often suffers from crashes, has 4 CPUs. Other servers that are working properly and will not crash have only 2 CPUs.

**Comment by misi** [comment]
@519790441 Unfortunately I can't say from this log what causing it, but probably some race condition..
Thanks for the report. Let me know your experience with 4.5.1.3..

**Comment by eakraly** [comment]
Crash is related to an older version of coturn
Please report if you are still experiencing crashes with latest version
Thank you @519790441

**Comment by 519790441** [comment]
After switching to the 4.5.1.3 there are still crashes, but the frequency is much less (the old 4.5.0.8 one crashes about once a month, and the new one crashes about 1-2 times a year). I feel that this can be regarded as a solution to the problem and does not affect the use of customers.

**Comment by eakraly** [comment]
@519790441 great to hear!
I would advise to upgrade to latest version 4.6.2 - a lot more crash fixes were done there.
