### ISSUE TITLE
Are there plans to use io_uring on Linux?

### ISSUE THREAD

**Issue by vi** [coturn/coturn#591]
Is see `Kernel module for data channels.` entry in the TODO file. Maybe `io_uring`-based interface can be equivalent accelerator for data channels without requiring to do kernel things?

Are there any plans to use it? If not, are you open for contributions that add `io_uring`-based acceleration for data channels?

**Comment by misi** [comment]
@vi  I am very open to any contributions, so absolutely. 
Sorry for my late reply, unfortunately I have limited time to spend on the support of this project.

**Comment by vi** [comment]
Is it safe to say that using io_uring directly in coturn does not make sense anymore, given pending [libevent support](https://github.com/libevent/libevent/pull/1356)?

**Comment by eakraly** [comment]
Yes, see #1034 

Closing this to track this question in one place
