### ISSUE TITLE
turnserver[1424]: ERROR: Cannot open log file for writing

### ISSUE THREAD

**Issue by freemaths** [coturn/coturn#596]
turnserver[1424]: ERROR: Cannot open log file for writing: /var/log/turn_2020-07-15.log

If config is changed to use log rather than syslog then the above error results and no logging is produced. Note: /var/log exists and is fine for all other logging (and indeed contains syslog which coturn logs to using the default config).

**Comment by misi** [comment]
Check which uid and gid runs coturn and if it can write the /var/log.  Normally /var/log owned by root.root but coturn runs  turnserver:turnserver uid:gid.
