### ISSUE TITLE
log is spammed

### ISSUE THREAD

**Issue by 532910** [coturn/coturn#603]
Currently my TURN server is under some kind of attack. Just arrives several STUN Binding Requests per second. From not my clients and most source IPs are listed in spamhaus or sorbs.

The problem is that logs are bloated with `incoming packet BINDING processed, success` (`incoming packet message processed, error 401: Unauthorized` with `secure-stun` and `handle_turn_command: STUN method 0x1 ignored` with `no-stun`) and takes several hundred megabytes.

**Comment by misi** [comment]
Can you please send Pull Request with the proposed fix. I am busy with other fixes.

**Comment by 532910** [comment]
I'm not sure how this should be fiexed. For example [eturnal](https://github.com/processone/eturnal) just doesn't log such requests.

**Comment by misi** [comment]
We should make log levels more sophisticated to log only what operator wants, 
or try to use syslog and then you can filter it.

**Comment by weiss** [comment]
> For example [eturnal](https://eturnal.net) just doesn't log such requests.

FWIW, it does these days (at `[info]` level), and now I'm wondering how to get rid of them myself :smiley:

**Comment by 532910** [comment]
I've added the following ferm rules

```ferm
table filter chain ForwardPreTransport proto udp dport 3478 {
	mod u32 u32 '28=0x00010000 && 32=0x2112A442 && 36=0x0 && 40=0x0 && 44=0x0' {
		&Log( "STUN BINDING Dropped: " );
		DROP;
	}
	mod u32 u32 '28=0x00010008 && 32=0x12233445 && 36=0x56677889 && 40=0x90011223 && 44=0x34455667' {
		&Log( "STUN OLD BINDING Dropped: " );
		DROP;
	}
}
```

and life become easier. But I'm still receiving these packages, and still interesting what is this?
Source address of some packages was 1.1.1.1, but I don't believe they were from 1.1.1.1 and looks like someone who send them don't expect to receive a reply.

**Comment by weiss** [comment]
> still interesting what is this?

BINDING requests are normal STUN requests.  I see millions of those per day on my public STUN servers.

Address spoofing is usually done to DDoS the spoofed address (though STUN isn't really the most effective protocol to perform this kind of attack).

**Comment by 532910** [comment]
Though my server is public I don't receive millions BINDINGs per day.
These don't look like a normal STUN requests as they are absolutely identical. And iptables rules above don't mess up real clients working.

**Comment by misi** [comment]
@532910 @weiss Do you think there is any open question here or can I close it?

**Comment by 532910** [comment]
coturn still spams his log, and this issue must be fixed

**Comment by misi** [comment]
@532910 I agree I will try to fix it.

**Comment by misi** [comment]
If you can forward your logs to syslog you can filter out the unwanted logs before write it to disk. 
And also we can add a new option to disable logging of STUN bind requests. @532910  What do you think?

**Comment by 532910** [comment]
> syslog you can filter out the unwanted logs

this sounds like a workaround

> a new option to disable logging of STUN bind requests

and this is the solution

**Comment by misi** [comment]
@532910  Implemented in latest master the solution. 
Disabled binding logging and added new option --log-binding to keep previous behavior.
Please test it.

**Comment by dominiquefournier** [comment]
The problem persists on Debian bullseye up-to-date, Coturn version 4.5.2-3. Please, could you re-open the bug ?
I have the disabled "# log-binding" and I also try to set it to false without luck.

The log is filled with " session 003000000000000001: realm <Server.TLD> user <>: incoming packet BINDING processed, success"
4.5GB in one week without any valid connection, we are in test (loggued 4 times in daemon log, syslog, user and messages) : 18GB  of not needed messages. It will fill the /var partition.

**Comment by HansPL** [comment]
Exactly the same issue here — crashed my server !

**Comment by dinosmm** [comment]
Same here, my server became unresponsive, after some digging I found the Coturn logs were huge. It's logging all these binding requests that are coming in fast and constant, even though I have the #log-binding option disabled in the conf.

**Comment by HansPL** [comment]
In my /etc/turnserver.conf  I had
`verbose` 
uncommented.  Seems that this overrides 
`#log-binding`
as well as 
`#syslog`
causing dozens of those lines per second to appear in my 
`log-file=/var/log/turnserver/turnserver.log`
AND in /var/log/syslog AND in /var/log/daemonlog AND in /var/log/journal/ …  changing to 
`#verbose`  
stopped this.  Still, I'm wondering where this flooding comes from, in a private server with coturn installed just a week ago.  It started maybe three days after starting coturn.

**Comment by dinosmm** [comment]
Good catch, thanks! My turnserver.conf also had verbose uncommented, I commented it now and the logging stopped.
My TURN server has been running for a year now and this only started happening maybe a week ago. Probably some sort of attack scanning for turn servers?

**Comment by normen** [comment]
I also see these seemingly pointless repeated requests, multiple IPs each causing kilobytes of traffic per second. Maybe some kind of "lets thwart private communication channels"? Maybe even due to current geopolitics?

Whatever the reason, I'd love to see a way to filter the IP of such requests from the logs without overloading the logging system so I could feed fail2ban or something with those. Currently I have to filter the BINDING requests on the rsyslogd level and then enable verbose to get the IPs.. Causing more CPU load than just letting coturn answer them..
