### ISSUE TITLE
how can I disable stale-nonce

### ISSUE THREAD

**Issue by bhspencer** [coturn/coturn#604]
I would like to disable stale-nonce such that a nonce lasts forever.

I see in config file 

# By default, the nonce value is unique for a session,
# and has unlimited lifetime. 

However, despite not setting a stale-nonce in the config I find that I am still getting 438 stale nonce responses after 600 seconds. I am using the lt-cred-mech. Is it possible to prevent a nonce from becoming stale.

The reason I want to disable stale nonce is that if I send a BindRequest and the nonce in that request is stale I get a connection reset sent back instead of a stale nonce response.

**Comment by bhspencer** [comment]
Looks at the code it seems I can set: 

stale-nonce=0

To keep the nonce from going stale. Is that correct?

**Comment by misi** [comment]
I run through the code to check, and I see that nonce initialized to 600 sec 
STUN_DEFAULT_NONCE_EXPIRATION_TIME 
in turn_params initialization
https://github.com/coturn/coturn/blob/87d85f06bd50f81564ccef49df515d26f7801a86/src/apps/relay/mainrelay.c#L146
and if no value set
https://github.com/coturn/coturn/blob/87d85f06bd50f81564ccef49df515d26f7801a86/src/apps/relay/mainrelay.c#L1322

I didn't yet find code where it defaults to unlimited... :-/ so me (or docs is wrong and misleading), and you are right if it is set to 0 it should avoid new nonce generation.

**Comment by misi** [comment]
Documentation need to be fixed
