### ISSUE TITLE
dyld: Symbol not found: _evthread_lock_fns_ & Expected in: flat namespace

### ISSUE THREAD

**Issue by wcxdhr** [coturn/coturn#606]
When I run
`turnserver`
The error occurs:
```
dyld: Symbol not found: _evthread_lock_fns_
  Referenced from: /usr/local/opt/libevent/lib/libevent_openssl-2.1.7.dylib
  Expected in: flat namespace
 in /usr/local/opt/libevent/lib/libevent_openssl-2.1.7.dylib
zsh: abort      turnserver
```

I tried to reinstall libevent, but the error didn't disappear.
OS: MacOs Catalina 10.15.5

**Comment by misi** [comment]
See: 
coturn root dir the .travis.yml file
According it should work. It seems that it compiles, and also the basic test runs fine.

I test it with various osX image.
See: https://docs.travis-ci.com/user/reference/osx/ 

Sorry but I use Linux so I can't test it myself.
