### ISSUE TITLE
DONT FRAGMENT bit on TURN connections

### ISSUE THREAD

**Issue by alnet82** [coturn/coturn#608]
I'm trying to discover path MTU over a relayed link. According to RFC 5766, if a client sends packets with DF bit on, TURN server should set it too in a packet going to the peer.
Is this the behavior in coturn?
Moreover, the RFC suggests to include DF attribute in Allocate request. Not sure though, how to do that...

**Comment by misi** [comment]
serch for `dont_fragment` in the source..
Yes it should work according RFC.
