### ISSUE TITLE
Architecture for load balanced Coturn cluster

### ISSUE THREAD

**Issue by ohameiri** [coturn/coturn#609]
Hi
Having some issues while trying to set up a load balanced auto scaled coturn cluster. 

Anyone had any experience with this? 
Amy documentation regarding this issue? 

10x

**Comment by ohameiri** [comment]
(using AWS)

**Comment by DevRockstarZ** [comment]
I'm using ELB to mantain several coTURN instances.
You can just setup your coTURN instances and use ELB's ip address to use.

**Comment by misi** [comment]
@ohameiri I don't have experience with scaling with loadbalancers. 
Coturn could RoundRobin loadbalance see
https://github.com/coturn/coturn/tree/master/examples/scripts/loadbalance
@DevRockstarZ  
Which ELB type do you use?
* Network Load Balancer
* Gateway Load Balancer
* Classic Load Balancer
?

**Comment by DevRockstarZ** [comment]
@misi I used AWS Network Load Balancer(TCP/UDP) to load balance Coturn instances.

**Comment by misi** [comment]
@DevRockstarZ  Thanks!
I will close this issue, because I feel I can't add more to it, if you think it should be kept open let me know and I will reopen it..

**Comment by marcoberetta96** [comment]
@DevRockstarZ how did you setup the AWS Network Load Balancer?
