### ISSUE TITLE
For the AWS coturn image, is there a performance benefit to using paravirtual over hvm virtualization? Or was the choice arbitrary?

### ISSUE THREAD

**Issue by bloodfire91** [coturn/coturn#61]

**Comment by mom040267** [comment]
the main performance problem is the network throughput. You have to use the
technology that provides the best network driver interactions.

**Comment by bloodfire91** [comment]
So you guys think that pv better network driver interactions over hvm? I'm just curious because I know that some hvm machines have the option for enhanced networking feature on AWS; Were you guys able to look into this?

**Comment by mom040267** [comment]
I did not say that. I just said that check the technical specs and choose
one that has better network throughput.

Oleg
