### ISSUE TITLE
No srflx result in test

### ISSUE THREAD

**Issue by heikar** [coturn/coturn#611]
If i use [https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/](url) for test my coturn Installation i get the follow results:

Server: stun:Domain -> the last two results has as "component type" srflx
Server: stun:Domain:5439 -> the last result has no "component type"

The results are the same with activated or disabled firewall.

What can be the reason for this behavior?

Many greetings
heikar

**Comment by DevRockstarZ** [comment]
Can you write the full result of tricke-ice test?

**Comment by heikar** [comment]
Hi @DevRockstarZ thank for your reply.

This behavior happens in the latest version of coturn.

Here is the result of the test:

> URI: stun:Domain-Name
> 
> Time    Component 	Type 	Foundation 	Protocol 	Address		Port 	Priority
> 0.003    1		host	0		udp		ID1.local	59401	126 | 32512 | 255
> 0.003	1		host	2		tcp		ID1.local	9	125 | 32704 | 255
> 0.004	2		host	0		udp		ID1.local	59402	126 | 32512 | 254
> 0.004	2		host	2		tcp		ID1.local	9	125 | 32704 | 254
> 0.045	1		srflx	1		udp		IP-Address	59401	100 | 32543 | 255
> 0.066	2		srflx	1		udp		IP-Address	59402	100 | 32543 | 254
> 0.066											Done

> URI: stun:Domain-Name:3478
> 
> Time 	Component 	Type 	Foundation 	Protocol 	Address		Port 	Priority
> 0.003	1		host	0		udp		ID2.local	53867	126 | 32512 | 255
> 0.003	1		host	2		tcp		ID2.local	9	125 | 32704 | 255
> 0.003	2		host	0		udp		ID2.local	53868	126 | 32512 | 254
> 0.004	2		host	2		tcp		ID2.local	9	125 | 32704 | 254
> 0.013	1		srflx	1		udp		IP-Address	53867	100 | 32543 | 255
> 0.036	2		srflx	1		udp		IP-Address	53868	100 | 32543 | 254
> 0.036											Done

> URI: stun:Domain-Name:5349
> 
> Time 	Component 	Type 	Foundation 	Protocol 	Address		Port 	Priority
> 0.003	1		host	0		udp		ID3.local	49921	126 | 32512 | 255
> 0.003	1		host	2		tcp		ID3.local	9	125 | 32704 | 255
> 0.004	2		host	0		udp		ID3.local	49922	126 | 32512 | 254
> 0.004	2		host	2		tcp		ID3.local	9	125 | 32704 | 254
> 11.127											Done

**Comment by DevRockstarZ** [comment]
You can see this configuration file [link](https://github.com/coturn/coturn/blob/c5b0bd0e221b2ae11345151eeae2cba2afdc6426/examples/etc/turnserver.conf#L20)

I think TCP/TLS port is 5349, you should use turn:Domain-Name:5349 or when you want to use turn, you should put turn on the front of the Domain-Name.

Also, my coTURN server does not contain srflx when I use 5349 port.

And you can see Trickle ICE's source code. [link](https://github.com/webrtc/samples/blob/5033b81d0e3984179cfeb03b5089f2eb705202db/src/content/peerconnection/trickle-ice/js/main.js#L218)

I hope this will make your question solved. Thanks!

**Comment by heikar** [comment]
Hi @DevRockstarZ ,

'sry for my late reply.

Thank you for your help :)
