### ISSUE TITLE
Multiple TURN server

### ISSUE THREAD

**Issue by apprithm** [coturn/coturn#615]
Hi, I'm pretty new to WebRTC world and I have a question related to how to scale the TURN server:

Assume I have the coturn server up and running, the clients can connect to it and talk to each other without any problem.

Now, If I have **2 coturn servers** T1 and T2 are running. **Client1** connected to T1 and **client2** connected to T2, can they talk to each other via different coturn server(s)? Do I need to do any special setup in corturn config in order to make this happen? 

For a large scale, Is relaying traffic between multiple servers a common practice? Or I should use a different approach such as make the client smart enough to make sure both clients always connect to the same TURN server?

**Comment by DevRockstarZ** [comment]
You can see this document.
[Document](https://www.google.com/url?sa=i&url=https%3A%2F%2Fzenodo.org%2Frecord%2F1442896%2Ffiles%2Fqoe-webrtc-computing.pdf&psig=AOvVaw0yIeeHtkPQU9cMK9V-mURU&ust=1598582552348000&source=images&cd=vfe&ved=0CA0QjhxqFwoTCNjZvJ2uuusCFQAAAAAdAAAAABAD)
On page 11, peers can communicate each other when peers use different TURN servers.

**Comment by apprithm** [comment]
> You can see this document.
> [Document](https://www.google.com/url?sa=i&url=https%3A%2F%2Fzenodo.org%2Frecord%2F1442896%2Ffiles%2Fqoe-webrtc-computing.pdf&psig=AOvVaw0yIeeHtkPQU9cMK9V-mURU&ust=1598582552348000&source=images&cd=vfe&ved=0CA0QjhxqFwoTCNjZvJ2uuusCFQAAAAAdAAAAABAD)
> On page 11, peers can communicate each other when peers use different TURN servers.
> Also, I'm using several TURN servers to load balance each other.
> But there's no problems using multiple TURN servers. Thanks.

Thank you, I will check out the doc!

**Comment by marcoberetta96** [comment]
@DevRockstarZ how do you perform load balancing among multiple TURN servers?
Round robin DNS?

**Comment by MohammedNoureldin** [comment]
@DevRockstarZ thanks a lot! That publication helped me to understand this. Just to make it simpler for the others:

> in order to establish a
 WebRTC session, peers need to exchange an SDP offer and answer. In addition to information about the session, an SDP offer also includes a list of ICE
 candidates. Each ICE candidate describes a method through which the origi
nating peer is able to communicate. To build the list of ICE candidates, each
 peer rst makes a series of requests to STUN. The server returns the public IP
 address and port pair that originated the request. This process is called ICE
 candidate gathering. Once the originating peer has nished gathering ICE can
didates, it can return an SDP and the list of candidates to the destination peer
 through the signaling channel. That peer generates an SDP answer including
 its own ICE candidates. Once the peers have exchanged SDPs, they perform
 a series of connectivity checks ordering the ICE candidates from highest to
 lowest priority, looking for a valid pair. If a peer cannot nd any address port
 pair that achieves connectivity, it makes a request to the TURN server to ob
tain a media relay address. This relay address is then added to the candidate
 list and exchanged via the signaling channel.
