### ISSUE TITLE
two turnserver behind enterprise firewall relay

### ISSUE THREAD

**Issue by ggj66** [coturn/coturn#617]
Two turnservers behind the same enterprise firewall cannot relay through the public network address, but can relay through the internal network address. I think in order for the turnserver behind two different firewalls to be able to relay, external-ip needs to provide a public network address, whether external-ip can support both public network and internal network addresses.

**Comment by misi** [comment]
I think you can solve it with NAT in linux firewall, replace dest IP on the destination machine if source is the neighbour server..
