### ISSUE TITLE
Metrics not available at port 9121/9641 on Coturn Version -4.5.0.7 

### ISSUE THREAD

**Issue by ShubhangiSGaikwad** [coturn/coturn#620]
Hello Coturn team,

Need help on prometheus configuration. On referring the readme , prometheus was not listed in turnserver.conf, so added prometheus in the  turnserver.conf and restarted the turn server , still Prometheus was not available at localhost:9121/metrics or 
localhost:9641/metrics 

Request to please guide , how to get Prometheus up and get the Turn Server Metrics .

our depolyment team has installed Coturn on ubuntu machine. Current Version Coturn-4.5.0.7  

Thanks

**Comment by ShubhangiSGaikwad** [comment]
Hello coturn team,

I am looking forward for a quick resolution on this,  please guide how to get Coturn Metrics on Coturn Version -4.5.0.7

Thanks in advance.

**Comment by c4m4** [comment]
I solved, using the master branch, git clone and compile, first you need to install all the depends, if you are using debian apt-get build-dep coturn

**Comment by misi** [comment]
@ShubhangiSGaikwad  Prometheus will be supported in 4.5.2.

**Comment by eakraly** [comment]
4.5.2 has been released with support for prometheus metrics (enabled by passing --prometheus flag)
