### ISSUE TITLE
Improve configurability

### ISSUE THREAD

**Issue by akatsukle** [coturn/coturn#63]
We're running TURN tests using the coturn.
For unit testing purposes, it would be great if it was possible to configure the different timers inside coturn.
For example, using the flag `--stale-nonce` allows us to change the nonce every 10 minutes, as defined in 
ns_turn_msg_defs.h at line 68. I would like to pass an additionnal parameter to set the value here.

It would be useful for unit tests, but would also be valid considering the RFC for the following : 
- STUN_MAX_ALLOCATE_LIFETIME (3600)
- STUN_NONCE_EXPIRATION_TIME (600)

For unit testing purposes, it would be nice to extend it also to : 
- STUN_DEFAULT_ALLOCATE_LIFETIME (600)
- STUN_CHANNEL_LIFETIME (600)
- STUN_PERMISSION_LIFETIME (300)

I can make a pull request for it if you greenlight it.

**Comment by mom040267** [comment]
Please make a pull request, and we will review it.

Thanks
Oleg

**Comment by misi** [comment]
Many Thanks for the Pull Requests. 
For me it seems to be OK, but let's wait for Oleg review..

**Comment by mom040267** [comment]
I ll check it this week

Thanks
Oleg

**Comment by mom040267** [comment]
these changes require documentation changes. I'll work on it.

thanks
Oleg

**Comment by mom040267** [comment]
I merged everything, please double-check that everything is correct.

Thanks
Oleg

**Comment by akatsukle** [comment]
The merge looked like correct, thanks.
However, I missed a bit on parameters initialization. I opened a pull request with a patch for it. (#70)
