### ISSUE TITLE
Multiple relay IP cfg file format

### ISSUE THREAD

**Issue by mgoodenUK** [coturn/coturn#633]
Hi,

Could someone please advise how you specify multiple relay IP addresses in the configuration file?

I've tried a few different combinations but no success.

Many thanks
Mark

**Comment by misi** [comment]
@mgoodenUK 
You should use relay-ip multiple time, -E 
e.g
```
turnserver --syslog -E 127.0.0.1 -E ::1 
```
I have check and it works both from config and cli

**Comment by mgoodenUK** [comment]
Thanks for the response Misi, I'll give this a go.
