### ISSUE TITLE
Does coturn need nginx when in need of tls-listening-port=443?

### ISSUE THREAD

**Issue by fooness** [coturn/coturn#635]
Hello everyone.

I setup coturn with certbot’s standalone method, so there’s no webserver on my vps to not block the port 443. I configured coturn in the following way:

```
listening-port=3478
tls-listening-port=443
realm={{ coturn_realm }}

use-auth-secret
static-auth-secret={{ coturn_secret }}

cert=/etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem
pkey=/etc/letsencrypt/live/{{ ansible_fqdn }}/privkey.pem
cipher-list="ECDH+AESGCM:ECDH+CHACHA20:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS"

denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=172.16.0.0-172.31.255.255

# Matrix
no-tcp-relay
user-quota=12
total-quota=1200

# BigBlueButton
dh2066
fingerprint
lt-cred-mech
no-tlsv1
no-tlsv1_1
```

There’s no output of `netstat -tunlp | grep 443`, and the server is not reachable via this port I suppose. Could anyone please help out?

**Comment by lonesomewalker** [comment]
Since you use BBB, you should either:
- stick to the official installation method
- get knowledge of Let's Encrypt

No, you don't need nginx, LE certificate are name based, this means if your hostname is the same as requested certificate, you can generate a LE certificate without any further services.

**Comment by fooness** [comment]
Port 443 is privileged and thus can only be used by processes run as e.g. `root`.

The default coturn process is [run as `turnserver`](https://github.com/coturn/coturn/blob/master/examples/etc/coturn.service#L10-L11), which is the problem here.

**Comment by kerel-fs** [comment]
Solution:
1. Modify unit file to start the turnserver as root (remove User & Group directives)
2. Modify turnserver configuration to drop privileges after start with
   ```
   proc-user=turnserver
   proc-group=turnserver
   ```

@misi Would you accept a PR which changes the default in debian to use this privilege dropping scheme?

**Comment by misi** [comment]
The easiest way is to port forward with local firewall rule the privileged port to the standard port.

@kerel-fs  Sorry for my late reply. Yes I will accept and warmly welcome any contribution!!
I am not fully understand yet how systemd handling privileged sockets, maybe we need to handle that way..

**Comment by eakraly** [comment]
Looks like this issue has been resolved (binding to 443 requires root or CAP_NET_BIND_SERVICE)
