### ISSUE TITLE
How to know whether TURN server is using as relay server or not dynamically?

### ISSUE THREAD

**Issue by Chandramouli-P** [coturn/coturn#641]
Hello,

We are aware that when P2P call happens, TURN server acts as relay server sometimes and media will flow through the TURN server. How to know that traffic is going through the TURN server, when active call is going on? And also, how to know that how much bandwidth is utilized by CoTURN, when it acts as relay server? 

Thank you.

Best Regards,
Chandramouli.

**Comment by matiaslopezd** [comment]
From coturn I don't know, but from PeerConnection you can get it using getStats and iceCandidate negotiation. There you can see the last connection, if is relayed or between peer, also the bandwidth and bytes sent and received.

**Comment by misi** [comment]
You need to check the ICE agent on your system in WebRTC stack if you use it then as @matiaslopezd wrote you can check the peerconnection ice agent actual state, and also you can see the stats object.
Open in new tab
Chorme:
`chrome://webrtc-internals`
Firefox
`about:webrtc`

**Comment by docjojo** [comment]
New free TURN server: freeturn.net
