### ISSUE TITLE
Using coturn with syslog

### ISSUE THREAD

**Issue by j4zzc4t** [coturn/coturn#647]
Hello there! I was looking for a way to add timestamps and on my coturn instance and found myself stuck.
Is there a way to have them enabled? 

I thought of editing the code myself, but not being involved in the project would make patching tedious, so, can you help with configuration or maybe directions on how to implement it?

**Comment by misi** [comment]
syslog will add timestamp autmatically.
In 4.5.2 we will have soon an new add new-log-timestamp option see more in master recent changes..
```
 --new-log-timestamp                            Enable full ISO-8601 timestamp in all logs.
 --new-log-timestamp-format     <format>        Set timestamp format (in strftime(1) format)
```
