### ISSUE TITLE
4.5.1.3 not avalible on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by andyxheli** [coturn/coturn#649]
Can you please update the ubuntu 20.04 repository to when doing an apt-get update the 4.5.1.3 shows up only shows 4.5.1.1

**Comment by misi** [comment]
This package is maintained by ubuntu community.

**Comment by axheli** [comment]
So how do we get the ubuntu community to update that?

**Comment by misi** [comment]
@axheli go to https://packages.ubuntu.com/focal/coturn
See:
Maintainer:
    Ubuntu Developers (Mail Archive)
