### ISSUE TITLE
failing pairing icecandidates

### ISSUE THREAD

**Issue by iraklippv** [coturn/coturn#653]
Hi, 
 I just installed coturn server, but unfortunately does not works.
 Can someone help ??

[aboutWebrtc2.txt](https://github.com/coturn/coturn/files/5596900/aboutWebrtc2.txt)

**Comment by misi** [comment]
@iraklippv Try to add: turn:37.46.105.132:3478?transport=tcp
Please check media port range is allowed on your host firewall and any firewall before your coturn server..

**Comment by ggarber** [comment]
old issue and already answered.
