### ISSUE TITLE
unsupport C++17

### ISSUE THREAD

**Issue by pig-peppa** [coturn/coturn#654]
when i use libturnclient.a, compiler reports:
/usr/include/turn/TurnMsgLib.h:78:44: error: ISO C++1z does not allow dynamic exception specifications
  StunAttrIterator(u08bits *buf, size_t sz) throw (WrongStunBufferFormatException)

**can you fix it, when you get time.**

**Comment by misi** [comment]
Please send PR with the fix. 
Unfortunately we don't have actual capacity to make it very soon..
Thanks for your help and cooperation!

**Comment by pig-peppa** [comment]
@misi  I am making my own new cluster mode based on this project. If finish my work, let me fix it.

**Comment by misi** [comment]
Fixed
