### ISSUE TITLE
Trying to bind DTLS/UDP bind: Address already in use

### ISSUE THREAD

**Issue by brunoalex** [coturn/coturn#656]
Im trying to use my mac to get a turnserver online, i never have done this ... iwhen i run
 #turnserver -L ip=192.168.1.66 -a -f -r turn.baixocarbono.pt -c /Users/sam/Downloads/turnserver/turnserver.conf   --pkey /Users/sam/Downloads/turnserver/turn_server_pkey.pem --cert /Users/sam/Downloads/turnserver/turn_server_cer.pem 

i get a few erros :

```
MBP-de-Bruno:~ sam$ turnserver -L ip=192.168.1.66 -a -f -r turn.baixocarbono.pt -c /Users/sam/Downloads/turnserver/turnserver.conf   --pkey /Users/sam/Downloads/turnserver/turn_server_pkey.pem --cert /Users/sam/Downloads/turnserver/turn_server_cer.pem 
0: log file opened: /var/tmp/turn_3530_2020-12-02.log
0: Listener address to use: 0.0.0.0
error resolving 'ip=192.168.1.66' hostname: nodename nor servname provided, or not known
ERROR: Cannot open log file for writing: /turnserver_2020-12-02.log
1: log file opened: /var/tmp/turn_3530_2020-12-02.log
1: ERROR: Cannot add a listener address: ip=192.168.1.66
1: 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.1.3 'dan Eider'
1: 
Max number of open files/sockets allowed for this process: 8191
1: 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 4000 (approximately)
1: 

==== Show him the instruments, Practical Frost: ====

1: TLS supported
1: DTLS supported
1: DTLS 1.2 supported
1: TURN/STUN ALPN supported
1: Third-party authorization (oAuth) is not supported
1: OpenSSL compile-time version: OpenSSL 1.1.1h  22 Sep 2020 (0x1010108f)
1: 
1: SQLite supported, default database location is /usr/local/var/db/turndb
1: Redis is not supported
1: PostgreSQL is not supported
1: MySQL is not supported
1: MongoDB is not supported
1: 
1: Default Net Engine version: 1 (UDP listening socket per session)

=====================================================

1: Domain name: 
1: Default realm: turn.baixocarbono.pt
1: SSL23: Certificate file found: /Users/sam/Downloads/turnserver/turn_server_cer.pem
1: SSL23: Private key file found: /Users/sam/Downloads/turnserver/turn_server_pkey.pem
1: TLS1.0: Certificate file found: /Users/sam/Downloads/turnserver/turn_server_cer.pem
1: TLS1.0: Private key file found: /Users/sam/Downloads/turnserver/turn_server_pkey.pem
1: TLS1.1: Certificate file found: /Users/sam/Downloads/turnserver/turn_server_cer.pem
1: TLS1.1: Private key file found: /Users/sam/Downloads/turnserver/turn_server_pkey.pem
1: TLS1.2: Certificate file found: /Users/sam/Downloads/turnserver/turn_server_cer.pem
1: TLS1.2: Private key file found: /Users/sam/Downloads/turnserver/turn_server_pkey.pem
1: TLS cipher suite: DEFAULT
1: DTLS: Certificate file found: /Users/sam/Downloads/turnserver/turn_server_cer.pem
1: DTLS: Private key file found: /Users/sam/Downloads/turnserver/turn_server_pkey.pem
1: DTLS1.2: Certificate file found: /Users/sam/Downloads/turnserver/turn_server_cer.pem
1: DTLS1.2: Private key file found: /Users/sam/Downloads/turnserver/turn_server_pkey.pem
1: DTLS cipher suite: DEFAULT
1: Relay address to use: 0.0.0.0
Cannot create pid file: /var/run/turnserver.pid: Permission denied
1: Cannot create pid file: /var/run/turnserver.pid
1: pid file created: /var/tmp/turnserver.pid
1: IO method (main listener thread): kqueue
1: IPv6: On this platform, I am using alternative behavior of TTL (HOPLIMIT) according to RFC 6156.
1: WARNING: I cannot support STUN CHANGE_REQUEST functionality because only one IP address is provided
1: Wait for relay ports initialization...
1:   relay 0.0.0.0 initialization...
1:   relay 0.0.0.0 initialization done
1: Relay ports initialization done
1: IO method (general relay thread): kqueue
1: turn server id=0 created
1: IO method (general relay thread): kqueue
1: turn server id=1 created
1: IO method (general relay thread): kqueue
1: turn server id=2 created
1: IO method (general relay thread): kqueue
1: turn server id=3 created
1: IO method (general relay thread): kqueue
1: turn server id=4 created
1: IO method (general relay thread): kqueue
1: turn server id=5 created
1: IO method (general relay thread): kqueue
1: turn server id=6 created
1: IO method (general relay thread): kqueue
1: turn server id=7 created
bind: Address already in use
1: Trying to bind fd 14 to <0.0.0.0:3478>: errno=48
Cannot bind local socket to addr: Address already in use
1: Cannot bind DTLS/UDP listener socket to addr 0.0.0.0:3478
1: Trying to bind DTLS/UDP listener socket to addr 0.0.
```
im behinde a rooter... my mac ip is 192.168.1.66 and my public ip is 85.243.249.150

my conf file is 

realm=turn.baixocarbono.pt
server-name= turn.baixocarbono.pt
fingerprint
listening-ip=192.168.1.66
external-ip=85.243.249.150
listening-port=3478
min-port=10000
max-port=20000
log-file=/turnserver.log
verbose

user=user:pass
lt-cred-mech

can some one point me in the right direction ? can i use my make to a turn server online is my ip set correct??  
tks. for helping

**Comment by brunoalex** [comment]
when i use sudo turnserver -L ip=192.168.1.66 -a -f -r turn.baixocarbono.pt -c /Users/sam/Downloads/turnserver/turnserver.conf   --pkey /Users/sam/Downloads/turnserver/turn_server_pkey.pem --cert /Users/sam/Downloads/turnserver/turn_server_cer.pem  i get : 

0: log file opened: /var/log/turn_3769_2020-12-02.log
0: Listener address to use: 0.0.0.0
error resolving 'ip=192.168.1.66' hostname: nodename nor servname provided, or not known
0: log file opened: /turnserver_2020-12-02.log
0: ERROR: Cannot add a listener address: ip=192.168.1.66
0: 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.1.3 'dan Eider'
0: 
Max number of open files/sockets allowed for this process: 8191
0: 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 4000 (approximately)
0: 

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: DTLS 1.2 supported
0: TURN/STUN ALPN supported
0: Third-party authorization (oAuth) is not supported
0: OpenSSL compile-time version: OpenSSL 1.1.1h  22 Sep 2020 (0x1010108f)
0: 
0: SQLite supported, default database location is /usr/local/var/db/turndb
0: Redis is not supported
0: PostgreSQL is not supported
0: MySQL is not supported
0: MongoDB is not supported
0: 
0: Default Net Engine version: 1 (UDP listening socket per session)

=====================================================

0: Domain name: 
0: Default realm: turn.baixocarbono.pt
0: SSL23: Certificate file found: /Users/sam/Downloads/turnserver/turn_server_cer.pem
0: SSL23: Private key file found: /Users/sam/Downloads/turnserver/turn_server_pkey.pem
0: TLS1.0: Certificate file found: /Users/sam/Downloads/turnserver/turn_server_cer.pem
0: TLS1.0: Private key file found: /Users/sam/Downloads/turnserver/turn_server_pkey.pem
0: TLS1.1: Certificate file found: /Users/sam/Downloads/turnserver/turn_server_cer.pem
0: TLS1.1: Private key file found: /Users/sam/Downloads/turnserver/turn_server_pkey.pem
0: TLS1.2: Certificate file found: /Users/sam/Downloads/turnserver/turn_server_cer.pem
0: TLS1.2: Private key file found: /Users/sam/Downloads/turnserver/turn_server_pkey.pem
0: TLS cipher suite: DEFAULT
0: DTLS: Certificate file found: /Users/sam/Downloads/turnserver/turn_server_cer.pem
0: DTLS: Private key file found: /Users/sam/Downloads/turnserver/turn_server_pkey.pem
0: DTLS1.2: Certificate file found: /Users/sam/Downloads/turnserver/turn_server_cer.pem
0: DTLS1.2: Private key file found: /Users/sam/Downloads/turnserver/turn_server_pkey.pem
0: DTLS cipher suite: DEFAULT
0: Relay address to use: 0.0.0.0
0: pid file created: /var/run/turnserver.pid
0: IO method (main listener thread): kqueue
0: IPv6: On this platform, I am using alternative behavior of TTL (HOPLIMIT) according to RFC 6156.
0: WARNING: I cannot support STUN CHANGE_REQUEST functionality because only one IP address is provided
0: Wait for relay ports initialization...
0:   relay 0.0.0.0 initialization...
0:   relay 0.0.0.0 initialization done
0: Relay ports initialization done
0: IO method (general relay thread): kqueue
0: turn server id=0 created
0: IO method (general relay thread): kqueue
0: turn server id=1 created
0: IO method (general relay thread): kqueue
0: turn server id=2 created
0: IO method (general relay thread): kqueue
0: turn server id=3 created
0: IO method (general relay thread): kqueue
0: turn server id=4 created
0: IO method (general relay thread): kqueue
0: turn server id=5 created
0: IO method (general relay thread): kqueue
0: turn server id=6 created
0: IO method (general relay thread): kqueue
0: turn server id=7 created
0: IPv4. DTLS/UDP listener opened on: 0.0.0.0:3478
0: IPv4. DTLS/UDP listener opened on: 0.0.0.0:5349
socket: Protocol not supported
0: IPv4. TLS/TCP listener opened on : 0.0.0.0:3478
socket: Protocol not supported
0: IPv4. TLS/TCP listener opened on : 0.0.0.0:5349
0: Total General servers: 8
0: IO method (auth thread): kqueue
0: IO method (auth thread): kqueue
0: IO method (auth thread): kqueue
0: IO method (auth thread): kqueue
0: SQLite DB connection success: /usr/local/var/db/turndb
0: IO method (admin thread): kqueue
0: IPv4. CLI listener opened on : 127.0.0.1:5766
43: IPv4. CLI connected to: 127.0.0.1:52939
43: IPv4. CLI connected to: 127.0.0.1:52940
43: IPv4. CLI session disconnected from: 127.0.0.1:52939
44: IPv4. CLI connected to: 127.0.0.1:52942
44: IPv4. CLI session disconnected from: 127.0.0.1:52940
49: IPv4. CLI connected to: 127.0.0.1:52943
49: IPv4. CLI session disconnected from: 127.0.0.1:52942
79: IPv4. CLI connected to: 127.0.0.1:52946
79: IPv4. CLI session disconnected from: 127.0.0.1:52943
139: IPv4. CLI session disconnected from: 127.0.0.1:52946
139: IPv4. CLI connected to: 127.0.0.1:52956
139: IPv4. CLI connected to: 127.0.0.1:52957
139: IPv4. CLI session disconnected from: 127.0.0.1:52956
278: IPv4. CLI session disconnected from: 127.0.0.1:52957

**Comment by misi** [comment]
Please try to read this to understand more ICE and TURN from RFC-s or other sources.
HTH if you read this will help to clarify:
https://misi.github.io/webrtc-c0d3l4b/img/149faeda7a820cf4.png
https://misi.github.io/webrtc-c0d3l4b/

**Comment by brunoalex** [comment]
tks for your reply, im trying for days to get this to work on my home mac... now i get 

0: pid file created: /var/run/turnserver.pid
0: IO method (main listener thread): kqueue
0: IPv6: On this platform, I am using alternative behavior of TTL (HOPLIMIT) according to RFC 6156.
0: WARNING: I cannot support STUN CHANGE_REQUEST functionality because only one IP address is provided
0: Wait for relay ports initialization...
0:   relay 192.168.1.66 initialization...
0:   relay 192.168.1.66 initialization done
0:   relay 2001:8a0:7af0:7001:36:7ab8:43df:6213 initialization...
0:   relay 2001:8a0:7af0:7001:36:7ab8:43df:6213 initialization done
0:   relay 2001:8a0:7af0:7001:f579:c811:e0cd:6444 initialization...
0:   relay 2001:8a0:7af0:7001:f579:c811:e0cd:6444 initialization done
0: Relay ports initialization done
0: IO method (general relay thread): kqueue
0: turn server id=0 created
0: IO method (general relay thread): kqueue
0: turn server id=1 created
0: IO method (general relay thread): kqueue
0: turn server id=2 created
0: IO method (general relay thread): kqueue
0: turn server id=3 created
0: IO method (general relay thread): kqueue
0: turn server id=4 created
0: IO method (general relay thread): kqueue
0: turn server id=5 created
0: IO method (general relay thread): kqueue
0: turn server id=6 created
0: IO method (general relay thread): kqueue
0: turn server id=7 created
0: IPv4. DTLS/UDP listener opened on: 127.0.0.1:3478
0: IPv4. DTLS/UDP listener opened on: 127.0.0.1:5349
0: IPv6. DTLS/UDP listener opened on: ::1:3478
0: IPv6. DTLS/UDP listener opened on: ::1:5349
0: IPv6. DTLS/UDP listener opened on: 2001:8a0:7af0:7001:36:7ab8:43df:6213:3478
0: IPv6. DTLS/UDP listener opened on: 2001:8a0:7af0:7001:36:7ab8:43df:6213:5349
0: IPv6. DTLS/UDP listener opened on: 2001:8a0:7af0:7001:f579:c811:e0cd:6444:3478
0: IPv6. DTLS/UDP listener opened on: 2001:8a0:7af0:7001:f579:c811:e0cd:6444:5349
0: IPv4. DTLS/UDP listener opened on: 192.168.1.66:3478
0: IPv4. DTLS/UDP listener opened on: 192.168.1.66:5349
socket: Protocol not supported
0: IPv4. TLS/TCP listener opened on : 127.0.0.1:3478
socket: Protocol not supported
0: IPv4. TLS/TCP listener opened on : 127.0.0.1:5349
socket: Protocol not supported
0: IPv6. TLS/TCP listener opened on : ::1:3478
socket: Protocol not supported
0: IPv6. TLS/TCP listener opened on : ::1:5349
socket: Protocol not supported
0: IPv6. TLS/TCP listener opened on : 2001:8a0:7af0:7001:36:7ab8:43df:6213:3478
socket: Protocol not supported
0: IPv6. TLS/TCP listener opened on : 2001:8a0:7af0:7001:36:7ab8:43df:6213:5349
socket: Protocol not supported
0: IPv6. TLS/TCP listener opened on : 2001:8a0:7af0:7001:f579:c811:e0cd:6444:3478
socket: Protocol not supported
0: IPv6. TLS/TCP listener opened on : 2001:8a0:7af0:7001:f579:c811:e0cd:6444:5349
socket: Protocol not supported
0: IPv4. TLS/TCP listener opened on : 192.168.1.66:3478
socket: Protocol not supported
0: IPv4. TLS/TCP listener opened on : 192.168.1.66:5349
0: Total General servers: 8
0: IO method (auth thread): kqueue
0: IO method (auth thread): kqueue
0: IO method (auth thread): kqueue
0: IO method (auth thread): kqueue
0: IO method (admin thread): kqueue
0: SQLite DB connection success: /usr/local/var/db/turndb
Connect: Address already in use
5: ERROR: Cannot connect new detached udp client socket from local addr 192.168.1.66:3478 to remote addr 192.168.1.66:51441
5: session 000000000000000001: realm <turn.baixocarbono.pt> user <>: incoming packet BINDING processed, success
5: ERROR: Cannot handle UDP packet, size 20
15: session 000000000000000001: realm <turn.baixocarbono.pt> user <>: incoming packet BINDING processed, success
25: session 000000000000000001: realm <turn.baixocarbono.pt> user <>: incoming packet BINDING processed, success
3

ice test on the web replys done..no errors... can you point me in the right direction? tks misi

**Comment by misi** [comment]
TURN server normally runs on a server and need a global ip address or if it is behind a NAT it needs your extrenal IP address and also to port forward to all of its ports.

**Comment by brunoalex** [comment]
port forward resolved the issue, you save my day Thank you so much Misi.
