### ISSUE TITLE
Proprietary code in ns_turn_khash.h ?

### ISSUE THREAD

**Issue by bodorjzsolt** [coturn/coturn#657]
The file contains the comment: 
"proprietary header added, with proprietary memory management functions. " 
The file contains proprietary code?

**Comment by misi** [comment]
I was not part of the project when it was added. 
We need to ask about it Oleg: @mom040267

**Comment by eakraly** [comment]
khash.h comes from https://github.com/attractivechaos/klib which is MIT licensed
