### ISSUE TITLE
When will 4.5.2 will be released ? 

### ISSUE THREAD

**Issue by rgarrigue** [coturn/coturn#662]
Hi there

I'm waiting for the prometheus metrics feature, when will the version shipping it (I read in the related PR it'ld be 4.5.2) will be release ? 

Thanks,

**Comment by misi** [comment]
As far as the queue will be empty. Depends how I could progress.. I hope soon.. This year hopefully..

**Comment by misi** [comment]
See: https://github.com/coturn/coturn/milestone/2

**Comment by rgarrigue** [comment]
Thanks. "This year" is a bit vague, this feature is really important for us, I hope it can be release ahead of time, without being slowed down by a backlog maybe a bit big ?

**Comment by misi** [comment]
@rgarrigue It will be out before 11 of January 2021, but I can't tell you more.

**Comment by rgarrigue** [comment]
Will do. Thanks !

**Comment by rgarrigue** [comment]
@misi : I got the release notification, thanks. I sent a mail to the related Debian mailing list for an ETA, and saw your name in the uploaders. Did you sent them the .deb too ? 

Half related, I'ld be interested in the .deb as part as the Github release assets.

**Comment by misi** [comment]
@rgarrigue I am working on the new release day and night. And yes I am working on the packaging. So I hope it will be rolled out today in unstable..

**Comment by misi** [comment]
Can you forward me the email that you sent to debian list.. thx..

**Comment by MatMaul** [comment]
Hello there, thanks for the release @misi. Can you also trigger an update of the docker images when you have some time ? Thanks !

**Comment by misi** [comment]
https://hub.docker.com/r/coturn/coturn 
The latest tag automatically builds after every commit or base image change..

**Comment by misi** [comment]
https://buildd.debian.org/status/package.php?p=coturn
4.5.2-1 land in unstable after compilations finihing

**Comment by MatMaul** [comment]
oh thanks. I was actually using https://hub.docker.com/r/instrumentisto/coturn, I didn't know this one exists.
Can we have something a bit more "stable" than building master ? like building the last tagged release for example ?

**Comment by misi** [comment]
I added 4.5.2 tag. 
This is the actual stable. Please help me maintain the docker part.
Let me know if any other adjustment missing what you like in other instrumentisto/coturn

**Comment by rgarrigue** [comment]
Hi @misi. 4.5.3 is in Debian Sid, but will it hit buster backports ? https://buildd.debian.org/status/package.php?p=coturn&suite=buster-backports

**Comment by misi** [comment]
I am strugling with some systemd issues with the backport, but yes I am working on it. Sorry for the delay.

**Comment by misi** [comment]
The debain 10 backport package will be uploaded today. Sorry for the delay.

**Comment by rgarrigue** [comment]
Nothing in the buster-backport's status page yet ?

**Comment by wferi** [comment]
It's waiting for the gatekeepers at https://ftp-master.debian.org/backports-new.html.

**Comment by rgarrigue** [comment]
4.5.2 is now available in buster backports, hence closing
