### ISSUE TITLE
Matrix and coturn: Cannot bind local socket to addr: Address already in use.

### ISSUE THREAD

**Issue by PlanetDyna** [coturn/coturn#668]
Hello Folks,

I have installed Matrix - however the following errors appear in the Coturn log:

0: Trying to bind fd 19 to <192.168.2.131:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr 192.168.2.131:3478

tcp        0      0 192.168.2.131:3478      0.0.0.0:*               LISTEN      684/turnserver
tcp        0      0 192.168.2.131:3478      0.0.0.0:*               LISTEN      684/turnserver

Best regards
PD

**Comment by misi** [comment]
Are you sure it is not running already? Can you check what is listening on port 3478?

**Comment by PlanetDyna** [comment]
Hey Misi! 

Thank you for your reply. Iam sure its running. But maybe I missed to forwared ports?

https://abload.de/img/portszpktw.jpg

**Comment by eakraly** [comment]
@PlanetDyna this issue is 1.5 years old
I hope you were able to address it.
If not please open a new one. TY!
