### ISSUE TITLE
Coturn STUN returns private ip of server's firewall

### ISSUE THREAD

**Issue by luisrr1590** [coturn/coturn#669]
Hello i've been breaking my head for weeks now looking for an asnwer to my problem, but I cant seem to find any.

I have a physical server used for virtualization behind a Fortigate 70D firewall. I created an Ubuntu VM server dedicated to be used as a STUN/TURN server with Coturn and created IPv4 policies in the Fortigate to actually route traffic and ports to the server. I also have a static public IP and a domain of my own wich points to that static IP.

So my Coturn server is visible form the internet and the ports are opened and working as well (I have tested this).

The problem is that when I try to use Trickle ICE for my server i get a response but instead of seeing the public ip of the client it always responds with the private IP of the firewall were the server is which is 192.168.1.1 (this is no matter were the client is connected, I have tried this on my home's WIFI which is a totally different network and even using mobile data).

What is that i'm doing wrong???
my Coturn config looks like this

listening-port = 3478
listening-ip = 0.0.0.0
relay-ip = private ip of server
external-ip = my static public ip
fingerprint
lt-cred-mech
server-name = my domain
realm = my domain
user = guest:12345
total-quota = 100
stale -nonce = 600

the response i get from Trickle ICE is:

Time	Component	Type	Foundation	Protocol	Address	Port	Priority
0.005	rtp	host	4273728266	udp	9e87611f-e096-4a55-ab9b-f58bb694db0d.local	55710	126 | 30 | 255
0.030	rtp	srflx	842163049	udp	192.168.1.1	18038	100 | 30 | 255
0.105	Done
0.109

Can some one please help me??? thanks in advance

**Comment by meyca** [comment]
Let CoTurn decide which relay-ip to use and comment out that setting?!

**Comment by luisrr1590** [comment]
Thank you for answering @meyca....following your suggestions i commented out the listening-ip and relay-ip options of coturn and restarted the service... The server is still accesible but the response continues to be the same (192.168.1.1)

**Comment by meyca** [comment]
A parallel VPN connection to that firewall or to some equipment behind it? ... There are too many options you are playing with: Fortigate-Networking, VM-Host, VM-Host-Networking, VM-Networking just to name a few. And I am not an expert either.

**Comment by luisrr1590** [comment]
managed to solve it....in the Fortigate I set the IPv4 policy with no NAT and then Coturn started to respond with the public IP of the client.....thank a lot....closing issue now.

**Comment by longlnk** [comment]
> managed to solve it....in the Fortigate I set the IPv4 policy with no NAT and then Coturn started to respond with the public IP of the client.....thank a lot....closing issue now.

Hi @luisrr1590 ,

I also have the same situation, I have:
1 x VM Coturn, it use IP private, NAT by Firewall
1 x VM BBB, it use IP private, NAT by Firewall

Network model: (Coturn - Firewall) <-> Internet <-> (Firewall - BBB)

The client can't share audio/camera :(

Can you help me?
