### ISSUE TITLE
Question - How can I test the load capacity?

### ISSUE THREAD

**Issue by akash-docquity** [coturn/coturn#670]
Hi, 

Sorry if this is a weird query. 

But how can I check that how many simultaneous connections could be handled by my coturn server on EC2.

I have implemented P2P call and used coturn on EC2. I know how to load test signalling server using Jmeter. 

Please help..

Thanks.

**Comment by misi** [comment]
There is tool `turnutils_uclient` and `turnutils_peer` you can use to load test.
See in the example/scripts folder for more info.
