### ISSUE TITLE
Possible solution for different realm under different server name?

### ISSUE THREAD

**Issue by tenge-amzn** [coturn/coturn#674]
I have the same server behind different domain name, TURN server is running both TLS and UDP.

I'm wondering if there's a way to use different realm on the session that's connected under different domain name?

For example, having xyz1.com and xyz2.com both pointed to same server.
Credential generated for xyz1.com won't work on xyz2.com, and vice versa.

**Comment by misi** [comment]
The short answer is No.
See the RFC-s for more info..
