### ISSUE TITLE
New official release of coturn before Debian 11 freeze

### ISSUE THREAD

**Issue by Neustradamus** [coturn/coturn#675]
Dear Coturn team, @misi,

It is possible to have a new build before the Debian 11 freeze?
- https://tracker.debian.org/pkg/coturn
- https://packages.debian.org/search?keywords=coturn

Not up-to-date:
- https://salsa.debian.org/pkg-voip-team/coturn
- https://salsa.debian.org/pkg-voip-team/rfc5766-turn-server

Next Debian will be here in 2023.

Thanks in advance.

**Comment by misi** [comment]
I will try to make it.

**Comment by Neustradamus** [comment]
@misi: Thanks!
