### ISSUE TITLE
Question: is there a way to check the coturn version on an existing server ?

### ISSUE THREAD

**Issue by kunlk** [coturn/coturn#680]
Hi Team,

I have an existing coturn server, but don't know how to check the version. Is there a command or version file to show the version? thanks a lot!

**Comment by misi** [comment]
Just run `turnserver` and it will write out the version

**Comment by kunlk** [comment]
Thank you very much !

**Comment by 16g** [comment]
@misi 
Hi!
Maybe you have another way to check?
For example, turnserver --version ?
