### ISSUE TITLE
Question: What's the algorithm to hash the password in Redis?

### ISSUE THREAD

**Issue by wuelcas** [coturn/coturn#681]
Hi everyone, a newbie to all WebRTC things here.

I have the task to configure our TURN server to use long-term credentials, for this we're creating a service that generates those credentials and using Redis to store the credentials. 

According to [the userdb schema for redis](https://github.com/coturn/coturn/blob/master/turndb/schema.userdb.redis) "For the long-term credentials there must be keys  "turn/realm/<realm-name>/user/<username>/key" and the values must be the the hmackeys", then it provides an example with a realm, user and a password but I can't figure out what hash algorithm should I use to generate the correct value to set in Redis, for the key it's pretty straight forward but I'm confused with the value. The doc says the values must be the hmackeys but I'm following what does it mean by that.

Thanks for the help in advance.

**Comment by misi** [comment]
md5
`echo -n “user:realm:secret" | md5sum`

**Comment by wuelcas** [comment]
Hey @misi thank you so much!
