### ISSUE TITLE
how to install 4.5.2 on debian.

### ISSUE THREAD

**Issue by cedricve** [coturn/coturn#685]
I just tried to installed coturn on a Debian VPS (digital ocean), and the version is 4.5.0.5-1+deb9u3
How can I upgrade?

**Comment by misi** [comment]
Debian version?

**Comment by cedricve** [comment]
root@turn2:~# uname -a
Linux turn2 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux

**Comment by misi** [comment]
Please send the output of `lsb_release -a`

**Comment by cedricve** [comment]
root@turn2:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch

**Comment by misi** [comment]
4.5.2 rolled out only to unstable and will be rolled out today to testing. 
After it will arrive to testin I will start work on the backport to stable.

**Comment by cedricve** [comment]
Super!

**Comment by misi** [comment]
Arrived in testing

**Comment by misi** [comment]
Debian 10 backport package will be uploaded today.. Sorry for the delay..

**Comment by cedricve** [comment]
Thanks!

Kind regards,
Verstraeten Cédric

**Comment by misi** [comment]
4.5.2 rolled out so I close now this issue.
