### ISSUE TITLE
4.5.2 with OpenSSL version below 1.1.1 cause an issue

### ISSUE THREAD

**Issue by misi** [coturn/coturn#686]
This is just a tracking issue until new release will fix it properly.

I made a mistake in 4.5.2.and some of you with openssl version below 1.1.1 can experience an issue. 

I tried to fix that in  ssl 1.1.1no more needed:
```
CRYPTO_THREADID_set_callback(coturn_id_function);
``` 

But in the fix I missed to define OPENSSL_VERSION_1_1_1 :-/
So actually
```
CRYPTO_THREADID_set_callback(coturn_id_function);
``` 
never called. 

It not cause all mostly used modern Linux distributions any issue because they use ssl version 1.1.1 or above.

I need to refactor the merged quick fix from https://github.com/coturn/coturn/pull/684

Great thanks to @brevilo to find an correcting my mistake, it is highly appreciated!
@brevilo Sorry for the messy big commit. (I tried to fix all g++ warning in one commit.)

So sorry about it and accept my apologies..

**Comment by brevilo** [comment]
No worries, you merged the PR and issued another release 👍 That's just teamwork...

**Comment by shu-mutou** [comment]
Thank you for fixing this!

F.Y.I. I also faced this issue with following environment.
- OS: RHEL 7.5
- OpenSSL version: 1.0.2k 12.el7

**Comment by eakraly** [comment]
Looks like not an issue anymore.
