### ISSUE TITLE
Allow static users and REST API at the same time

### ISSUE THREAD

**Issue by devurandom** [coturn/coturn#69]
It would be great if coturn would support static users and usage of the REST API at the same time.

From the documentation and own observations it seems that, if the `use-auth-secret` option is enabled, any `user` settings in the config file are ignored. I would like to add additional users who have a static password set, so I can use those with programs that do not have a server component running under my control (and thus cannot use the REST API of my coturn server to generate a temporary user).

**Comment by mom040267** [comment]
that is rather difficult thing to support. We are not planning sucha
change in the new future.
