### ISSUE TITLE
Can't write log!

### ISSUE THREAD

**Issue by riker513** [coturn/coturn#691]
Hi there,

I can't get my coturn installation to write log files. Must be something silly, but I just can't locate the cause.

My `turnserver.conf` contains
`#syslog`
`verbose`
`log-file=/var/log/turn/turn.log`
and I double-checked that the log directory is writeable for the `turnserver` user.

Other entries of the config file are plain and simple, nothing to do with the logs, plus it did work before. Also, Coturn does not complain at startup about being unable to write the log - which it did before when I had forgotten to make the log directory readable for the turnserver user.

Any clues?

Thanks!

**Comment by misi** [comment]
Which version do you use?

**Comment by riker513** [comment]
Hi @misi - I'm on version 4.5.1.1

The following is my startup log when I run turnserver even though the daemon process is already running (so please ignore the `bind` problems below). Interestingly, it shows two times that a log is being created. The first points to a different directory than specified in the conf file. The second one is correct, and in fact also being created - with the content I am posting here. However, the first one is also being created, but with only few lines, please see the first of the two log files below. When turnserver is run as daemon, none of the two logs is being created, instead logging goes to syslog, and the startup log there shows no such mention of `log file opened` or similar.

# cat turn_1840_2021-01-19.log 
0: log file opened: /var/log/turn_1840_2021-01-19.log
0: Listener address to use: x.x.x.x
0: Listener address to use: 127.0.0.1
0: 0 bytes per second allowed, combined server capacity


# turnserver -v
0: log file opened: /var/log/turn_1840_2021-01-19.log
0: Listener address to use: x.x.x.x
0: Listener address to use: 127.0.0.1
0: 0 bytes per second allowed, combined server capacity
0: log file opened: /var/log/turn/turn_2021-01-19.log
0: Black listing: 0.0.0.0-0.255.255.255
0: Black listing: 10.0.0.0-10.255.255.255
0: Black listing: 100.64.0.0-100.127.255.255
0: Black listing: 169.254.0.0-169.254.255.255
0: Black listing: 127.0.0.0-127.255.255.255
0: Black listing: 172.16.0.0-172.31.255.255
0: Black listing: 192.0.0.0-192.0.0.255
0: Black listing: 192.0.2.0-192.0.2.255
0: Black listing: 192.88.99.0-192.88.99.255
0: Black listing: 192.168.0.0-192.168.255.255
0: Black listing: 198.18.0.0-198.19.255.255
0: Black listing: 198.51.100.0-198.51.100.255
0: Black listing: 203.0.113.0-203.0.113.255
0: Black listing: 240.0.0.0-255.255.255.255
0: Config file found: /etc/turnserver.conf
0: 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.1.1 'dan Eider'
0: 
Max number of open files/sockets allowed for this process: 524288
0: 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 262000 (approximately)
0: 

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: DTLS 1.2 supported
0: TURN/STUN ALPN supported
0: Third-party authorization (oAuth) supported
0: GCM (AEAD) supported
0: OpenSSL compile-time version: OpenSSL 1.1.1d  10 Sep 2019 (0x1010104f)
0: 
0: SQLite supported, default database location is /var/lib/turn/turndb
0: Redis supported
0: PostgreSQL supported
0: MySQL supported
0: MongoDB is not supported
0: 
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: Domain name: 
0: Default realm: turn.domain.com
0: ERROR: 
CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
0: SSL23: Certificate file found: /etc/coturn/certs/meet.domain.com.fullchain.pem
0: SSL23: Private key file found: /etc/coturn/certs/meet.domain.com.privkey.pem
0: TLS1.2: Certificate file found: /etc/coturn/certs/meet.domain.com.fullchain.pem
0: TLS1.2: Private key file found: /etc/coturn/certs/meet.domain.com.privkey.pem
0: TLS cipher suite: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
0: DTLS: Certificate file found: /etc/coturn/certs/meet.domain.com.fullchain.pem
0: DTLS: Private key file found: /etc/coturn/certs/meet.domain.com.privkey.pem
0: DTLS1.2: Certificate file found: /etc/coturn/certs/meet.domain.com.fullchain.pem
0: DTLS1.2: Private key file found: /etc/coturn/certs/meet.domain.com.privkey.pem
0: DTLS cipher suite: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
0: Relay address to use: x.x.x.x
0: Relay address to use: 127.0.0.1
0: pid file created: /var/run/turnserver.pid
0: IO method (main listener thread): epoll (with changelist)
0: WARNING: I cannot support STUN CHANGE_REQUEST functionality because only one IP address is provided
0: Wait for relay ports initialization...
0:   relay x.x.x.x initialization...
0:   relay x.x.x.x initialization done
0:   relay 127.0.0.1 initialization...
0:   relay 127.0.0.1 initialization done
0: Relay ports initialization done
0: IO method (general relay thread): epoll (with changelist)
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=0 created
bind: Address already in use
0: turn server id=1 created
0: Trying to bind fd 17 to <x.x.x.x:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr x.x.x.x:3478
0: Trying to bind TLS/TCP listener socket to addr x.x.x.x:3478, again...
0: IO method (general relay thread): epoll (with changelist)
bind: Address already in use
0: Trying to bind fd 18 to <x.x.x.x:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr x.x.x.x:3478
0: Trying to bind TLS/TCP listener socket to addr x.x.x.x:3478, again...
0: turn server id=3 created
bind: Address already in use
0: IO method (general relay thread): epoll (with changelist)
0: Trying to bind fd 26 to <x.x.x.x:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr x.x.x.x:3478
0: Trying to bind TLS/TCP listener socket to addr x.x.x.x:3478, again...
0: turn server id=2 created
bind: Address already in use
0: Trying to bind fd 28 to <x.x.x.x:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr x.x.x.x:3478
0: Trying to bind TLS/TCP listener socket to addr x.x.x.x:3478, again...
0: IPv4. DTLS/UDP listener opened on: x.x.x.x:3478
0: IPv4. DTLS/UDP listener opened on: x.x.x.x:5349
0: IPv4. DTLS/UDP listener opened on: 127.0.0.1:3478
0: IPv4. DTLS/UDP listener opened on: 127.0.0.1:5349
0: Total General servers: 4
0: IO method (auth thread): epoll (with changelist)
0: IO method (admin thread): epoll (with changelist)
0: IO method (auth thread): epoll (with changelist)
0: SQLite DB connection success: /var/lib/turn/turndb

**Comment by riker513** [comment]
Hi @misi - I'm on 4.5.1.1
