### ISSUE TITLE
TURN high availability ?

### ISSUE THREAD

**Issue by rgarrigue** [coturn/coturn#695]
Hi there

How do you achieve high availability for the TURN part ? Will that work out of the box if I set up 2 coturn side by side being the same turn.company.com record ? Or is it a stateful thing that won't accept a client using the 1st IP, than the 2nd, then the 1st... ? 

Best regards,

**Comment by misi** [comment]
You can setup a 3-rd turnserver round robin load balancer that can send alternate server. 
See: https://github.com/coturn/coturn/tree/master/examples/scripts/loadbalance

**Comment by rgarrigue** [comment]
Ok, so the load balancer get the turn:turn.company.com:3478 query, hand it over to one of the "working node". And to avoid the load balancer being the SPOF, I should have two of them answering turn.company.com ? 

I know nothing about the TURN protocol and almost nothing about SIP, I'm just the sysadmin, so can you explain me briefly what wouldn't work putting two coturn upfront without a specific load balancer setup ? Because - at least for HTTP stuff - round robin is what's happening when you're running multiple requests on a A record resolving with IP1 & IP2 & ... That's just for my understanding :)

**Comment by misi** [comment]
The process: LB sends back to client an alternate server STUN message, and client goes to Worker node where LB redirected.
LB is very stable but yes 2 LB in DNS could eliminate SPOF of the loadbalancer.

You can add multiple TURN server in ICE agent (TRUN client), but in some cases may it slows down the candidate gathering and concluding what ICE candidate pair to use, and so may leads longer call establishment time.

**Comment by rgarrigue** [comment]
Well, we tried with turn.company.com = coturn1 IP  and coturn2 IP

First call made a DNS resolution of turn.company.com and got coturn1 IP. The call worked.
2nd call didn't made the resolution, it worked too.
I I stopped coturn1, which automatically updated turn.company.com = coturn2 IP only
3rd call a new DNS resolution was made, the call was fine

So of course if the TURN goes down during a call it'll cut the call. But a subsequent call will be fine. Good enough I think.

Do you have any though on that @misi ? Like "beware, here lie dragons ?" Or does that seems production ready for you ?

**Comment by eakraly** [comment]
Just for the sake of documentation (and get you the answer @rgarrigue )
Using DNS to load balance traffic across multiple STUN/TURN instances is very common - not only hot-cold but also hot-hot where you have multiple instance and DNS would respond with IP of a different server in round-robin manner

Using this methodology you can even scale out and scale in with traffic (add more servers when you have more traffic and remove servers when you have less traffic - as long as you keep you DNS record up to date)

**Comment by MohammedNoureldin** [comment]
Hi @eakraly, DNS multiple entries can balance the load, but this does not supply a failover safety. Do you have any idea or suggestion if fail-over is somehow possible using this method?

**Comment by eakraly** [comment]
>Hi @eakraly, DNS multiple entries can balance the load, but this does not supply a failover safety. Do you have any idea or suggestion if fail-over is somehow possible using this method?

That is correct. Failover requires much more - it requires load balancer in front of turn server that is aware of the protocol, sessions, and available instances. That is whole level of complexity above.
I know companies doing that :)
I suggest making sure the client supports network disconnect and quick reconnect (to another TURN) to alleviate the issue.

> Another related question, let us say TURN server is used for a video chat application. Will users connected to different instances of TURN server be able to talk to each other?

Yes, it is possible (called double TURN). Each client can use relay and connect to a peer - which in itself can be relay.
I think you can achieve it if you force both sides to use relay - so all candidates are relays

**Comment by MohammedNoureldin** [comment]
Hi, I read you response last time and forgot to reply. I have just come to this.

Do you have any resource explaining how to get this load-balancing and different client in different relays working? Let us say I have 3 instances of coturn (STUN/TURN ) behind a load balancer / reverse proxy. How do you have any documentation or example how to get them to be able to reach each other? Taking for example Nextcloud Talk as an example.
