### ISSUE TITLE
coturn does not listen on socket

### ISSUE THREAD

**Issue by haraldkl** [coturn/coturn#697]
After installing coturn, it appears like it is not listening on any port for connections. Netstat does not show it neither for TCP nor UDP.

The rfc5769 check after compilation seems to be fine:

    $ scripts/rfc5769.sh
    RFC 5769 message fingerprint test(0) result: success
    RFC 5769 simple request short-term credentials and integrity test result: success
    RFC 5769 NEGATIVE fingerprint test(0) result: success
    RFC 5769 message structure, long-term credentials and integrity test result: success
    RFC 5769 message encoding test result: success
    RFC 5769 NEGATIVE long-term credentials test result: success
    RFC 5769 message fingerprint test(1) result: success
    RFC 5769 IPv4 response short-term credentials and integrity test result: success
    RFC 5769 NEGATIVE fingerprint test(1) result: success
    RFC 5769 IPv4 encoding result: success
    RFC 5769 message fingerprint test(2) result: success
    RFC 5769 IPv6 response short-term credentials and integrity test result: success
    RFC 5769 NEGATIVE fingerprint test(2) result: success
    RFC 5769 IPv6 encoding result: success
    oauth token A128GCM:OK
    oauth token A256GCM:OK

But when starting the `scripts/basic/relay.sh` it seems like nothing is listening for incoming connections, and when trying to connect to it with the client script I get:

    $ scripts/basic/udp_c2c_client.sh
    0: : IPv4. Connected from: 127.0.0.1:43469
    0: : IPv4. Connected from: 127.0.0.1:43469
    0: : IPv4. Connected to: 127.0.0.1:3478
    0: : IPv4. Connected to: 127.0.0.1:3478
    0: : allocate sent
    0: : allocate sent
    recv: Connection refused

There does nothing register in the logging output of the server even -V, so I ran it with strace: `PATH="bin:../bin:../../bin:${PATH}" strace turnserver -v -n -L 127.0.0.1 -L ::1 -E 127.0.0.1 -E ::1 --allow-loopback-peers --cli-password secred --max-bps=3000000 -f -m 3 --min-port=32355 --max-port=65535 --no-tls --no-dtls --no-auth --db="var/db/turndb" $@`, which also doesn't register anything when the client attempts to connect.
The output with strace of network related events looks like this (with a single thread -m 1):

    0: : Listener address to use: 127.0.0.1
    0: : log file opened: /var/tmp/turn_28160_2021-01-19.log
    0: : Listener address to use: ::1
    0: : Relay address to use: 127.0.0.1
    0: : Relay address to use: ::1
    0: : 3000000 bytes per second allowed per session
    0: :
    RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
    Version Coturn-4.5.2 'dan Eider'
    0: :
    Max number of open files/sockets allowed for this process: 4096
    0: :
    Due to the open files/sockets limitation,
    max supported number of TURN Sessions possible is: 2000 (approximately)
    0: :
    
    ==== Show him the instruments, Practical Frost: ====
    
    0: : TLS supported
    0: : DTLS supported
    0: : DTLS 1.2 supported
    0: : TURN/STUN ALPN supported
    0: : Third-party authorization (oAuth) supported
    0: : GCM (AEAD) supported
    0: : OpenSSL compile-time version: OpenSSL 1.0.2k-fips  26 Jan 2017 (0x100020bf)
    0: :
    0: : SQLite supported, default database location is /home/hgklima/opt/turnserver/var/db/turndb
    0: : Redis is not supported
    0: : PostgreSQL is not supported
    0: : MySQL supported
    0: : MongoDB is not supported
    0: :
    0: : Default Net Engine version: 3 (UDP thread per CPU core)
   
    =====================================================
    
    0: : Domain name:
    0: : Default realm:
    0: : CONFIG WARNING: allow_loopback_peers opens a possible security vulnerability. Do not use in production!!
    Cannot create pid file: /var/run/turnserver.pid: Permission denied
    0: : Cannot create pid file: /var/run/turnserver.pid
    0: : pid file created: /var/tmp/turnserver.pid
    socketpair(AF_UNIX, SOCK_STREAM, 0, [5, 6]) = 0
    0: : IO method (main listener thread): epoll (with changelist)

Netstat does not show anything listening on 127.0.0.1 at this point.
Unfortunately I have no clue, what could be the cause. Setting up some connection with two `nc` instances, one listening on 127.0.0.1:3478 works fine.

**Comment by misi** [comment]
I tried on debian bulls-eye with latest 4.5.2 and it worked for me 
this i my output:
```
misi@agy:~/work/coturn/examples$ ./scripts/basic/relay.sh
0: : Config file found: /home/misi/work/coturn/examples/etc/turnserver.conf
0: : Listener address to use: 127.0.0.1
0: : Listener address to use: ::1
0: : Relay address to use: 127.0.0.1
0: : Relay address to use: ::1
0: : 3000000 bytes per second allowed per session
0: : Config file found: /home/misi/work/coturn/examples/etc/turnserver.conf
0: : 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.2 'dan Eider'
0: : 
Max number of open files/sockets allowed for this process: 1048576
0: : 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
0: : 

==== Show him the instruments, Practical Frost: ====

0: : TLS supported
0: : DTLS supported
0: : DTLS 1.2 supported
0: : TURN/STUN ALPN supported
0: : Third-party authorization (oAuth) supported
0: : GCM (AEAD) supported
0: : OpenSSL compile-time version: OpenSSL 1.1.1i  8 Dec 2020 (0x1010109f)
0: : 
0: : SQLite supported, default database location is /usr/local/var/db/turndb
0: : Redis supported
0: : PostgreSQL supported
0: : MySQL supported
0: : MongoDB is not supported
0: : 
0: : Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: : Domain name: 
0: : Default realm: 
0: : CONFIG WARNING: allow_loopback_peers opens a possible security vulnerability. Do not use in production!!
Cannot create pid file: /var/run/turnserver.pid: Permission denied
0: : Cannot create pid file: /var/run/turnserver.pid
0: : pid file created: /var/tmp/turnserver.pid
0: : IO method (main listener thread): epoll (with changelist)
0: : Wait for relay ports initialization...
0: :   relay 127.0.0.1 initialization...
0: :   relay 127.0.0.1 initialization done
0: :   relay ::1 initialization...
0: :   relay ::1 initialization done
0: : Relay ports initialization done
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=0 created
0: : IPv4. SCTP listener opened on : 127.0.0.1:3478
0: : IPv4. TCP listener opened on : 127.0.0.1:3478
0: : IPv4. SCTP listener opened on : 127.0.0.1:3479
0: : IPv4. TCP listener opened on : 127.0.0.1:3479
0: : IPv6. SCTP listener opened on : ::1:3478
0: : IPv6. TCP listener opened on : ::1:3478
0: : IPv6. SCTP listener opened on : ::1:3479
0: : IPv6. TCP listener opened on : ::1:3479
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=1 created
0: : IPv4. SCTP listener opened on : 127.0.0.1:3478
0: : IPv4. TCP listener opened on : 127.0.0.1:3478
0: : IPv4. SCTP listener opened on : 127.0.0.1:3479
0: : IPv4. TCP listener opened on : 127.0.0.1:3479
0: : IPv6. SCTP listener opened on : ::1:3478
0: : IPv6. TCP listener opened on : ::1:3478
0: : IPv6. SCTP listener opened on : ::1:3479
0: : IPv6. TCP listener opened on : ::1:3479
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=2 created
0: : IPv4. UDP listener opened on: 127.0.0.1:3478
0: : IPv4. SCTP listener opened on : 127.0.0.1:3478
0: : IPv4. TCP listener opened on : 127.0.0.1:3478
0: : IPv4. SCTP listener opened on : 127.0.0.1:3479
0: : IPv4. TCP listener opened on : 127.0.0.1:3479
0: : IPv4. UDP listener opened on: 127.0.0.1:3479
0: : IPv6. SCTP listener opened on : ::1:3478
0: : IPv6. TCP listener opened on : ::1:3478
0: : IPv6. SCTP listener opened on : ::1:3479
0: : IPv6. TCP listener opened on : ::1:3479
0: : IPv6. UDP listener opened on: ::1:3478
0: : IPv6. UDP listener opened on: ::1:3479
0: : Total General servers: 3
0: : IO method (auth thread): epoll (with changelist)
0: : IO method (auth thread): epoll (with changelist)
0: : IO method (auth thread): epoll (with changelist)
0: : IO method (auth thread): epoll (with changelist)
0: : IO method (admin thread): epoll (with changelist)
0: : IPv4. CLI listener opened on : 127.0.0.1:5766
0: : SQLite DB connection success: var/db/turndb
0: : ERROR: 
Could not start Prometheus collector!
^C
misi@agy:~/work/coturn/examples$

**Comment by haraldkl** [comment]
Hey, thanks for looking at this and the feedback. The system I am running on is a shared hoster with "CentOS Linux release 7.9.2009 (Core)" and a Kernel of "3.10.0-1160.6.1.el7.x86_64 #1 SMP". Could you offer any advice what I could do to figure out what is going on?

**Comment by misi** [comment]
Try to run it with `-V` option instead of `-v` to get a more verbose logs. May it could help.

**Comment by haraldkl** [comment]
Thanks, unfortunately it does not provide any more output.

**Comment by misi** [comment]
Strange for me the strace is much more verbose..

**Comment by haraldkl** [comment]
It looks like it gets stuck in trying to lock a mutex in the ssl part of the code. Here is the callstack after interrupting it, when continuing from here the mutex lock does not return:

    #0  0x00007ffff761f54d in __lll_lock_wait () from /lib64/libpthread.so.0
    #1  0x00007ffff761ae9b in _L_lock_883 () from /lib64/libpthread.so.0
    #2  0x00007ffff761ad68 in pthread_mutex_lock () from /lib64/libpthread.so.0
    #3  0x0000000000417536 in coturn_locking_function (mode=9, n=18,
          file=0x7ffff6a06d3b "md_rand.c", line=230)
          at src/apps/relay/mainrelay.c:2559
    #4  0x00007ffff6947291 in ssleay_rand_add.part () from /lib64/libcrypto.so.10
    #5  0x00007ffff6948c19 in RAND_poll () from /lib64/libcrypto.so.10
    #6  0x00007ffff69477ed in ssleay_rand_bytes () from /lib64/libcrypto.so.10
    #7  0x000000000043f394 in turn_random () at src/client/ns_turn_msg.c:99
    #8  0x0000000000407fce in create_ioa_engine (sm=0x4de820, eb=0x4de900,
          tp=0x7ffff43ba010, relay_ifname=0x4793d0 <turn_params+10160> "",
          relays_number=2, relay_addrs=0x4c24d0, default_relays=0, verbose=1)
          at src/apps/relay/ns_ioalib_engine_impl.c:441
    #9  0x000000000041af15 in setup_listener () at src/apps/relay/netengine.c:1054
    #10 0x000000000041d882 in setup_server () at src/apps/relay/netengine.c:1859
    #11 0x000000000041748d in main (argc=0, argv=0x7fffffffdd30)
           at src/apps/relay/mainrelay.c:2520

I am not sure, why it goes into the SSL part, as I thought the basic test deactivates it (Options: -V -L 127.0.0.1 -L ::1 -E 127.0.0.1 -E ::1 --allow-loopback-peers --cli-password secred --max-bps=3000000 -f -m 3 --min-port=32355 --max-port=65535 --no-tls --no-dtls --no-auth --db="var/db/turndb"), therefore I didn't think that SSL may be to fault. The installed OpenSSL version of the system is OpenSSL 1.0.2k-fips, could that be a problem?

**Comment by wferi** [comment]
You may be hitting #686.

**Comment by haraldkl** [comment]
Indeed, this looks likely. So, an earlier release of coturn may help this? Thanks!

**Comment by haraldkl** [comment]
Yay, thanks a lot again. 4.5.1.3 works!
