### ISSUE TITLE
support RFC8445?

### ISSUE THREAD

**Issue by xujingzhou** [coturn/coturn#698]
RFC5245(ICE) is deprecated, does coturn support ICE standard: RFC8445? Or when do you plan to support this standard(RFC8445)?

**Comment by misi** [comment]
Can you please explain what changes needed to support RFC8445? I am happy to merge an Pull Request with that changes.

**Comment by xujingzhou** [comment]
In addition, Are there any plans to implement STUN's latest standard: RFC8489?

**Comment by xujingzhou** [comment]
> 
> 
> Can you please explain what changes needed to support RFC8445? I am happy to merge a Pull Request with that changes.

Because the WebRTC draft in 2020 already plans to support RFC8445, and it is believed that RFC8489 will be supported soon

**Comment by misi** [comment]
ICE implemented not in TURN server, but in WebRTC ICE agent so RFC8445 support is AFAIU not connected to TURN server.

STUN-bis RFC8489 is the really relevant here, but unfortunately I don't know any person from the community who started working on it or planning to work on it.
So please help and send PR with it and I am happy to include it. 

All in all actually there is no developer behind the coturn project! 
I try to maintain and keep alive the project. 
So  don't expect updates until You or someone send PR. 
If you need this please help and contribute!

**Comment by xujingzhou** [comment]
> 
> 
> ICE implemented not in TURN server, but in WebRTC ICE agent so RFC8445 support is AFAIU not connected to TURN server.
> 
> STUN-bis RFC8489 is the really relevant here, but unfortunately I don't know any person from the community who started working on it or planning to work on it.
> So please help and send PR with it and I am happy to include it.
> 
> All in all actually there is no developer behind the coturn project!
> I try to maintain and keep alive the project.
> So don't expect updates until You or someone send PR.
> If you need this please help and contribute!

Yes, I will
