### ISSUE TITLE
prometheus log message 

### ISSUE THREAD

**Issue by misi** [coturn/coturn#699]
If it is disabled by default it logs misleadingly "Could not start Prometheus collector!"
But we should distinct if it is disabled by default or could not strart, because of any error..

**Comment by yoesak** [comment]
So is this only misleading error message? How do I fix it?

**Comment by giavac** [comment]
I have noticed the same misleading log message. Maybe what can be done is:
- In https://github.com/coturn/coturn/blob/master/src/apps/relay/prom_server.c#L30 return something different than 1 in case prometheus is disabled. Something different than what's returned in https://github.com/coturn/coturn/blob/master/src/apps/relay/prom_server.c#L65 where starting the daemon failed.
- In https://github.com/coturn/coturn/blob/master/src/apps/relay/mainrelay.c#L2592 evaluate the returned code and adjust logging accordingly

If this seems reasonable I can raise a PR.

**Comment by patlachance** [comment]
I guess this issue can be closed, now that the PR has been merged?

**Comment by eakraly** [comment]
Closing - prometheus related logging messages appear only when compiled with prometheus support
Trying to enable prometheus flags in a version compiled without prometheus support will result in error about unknown flags
