### ISSUE TITLE
how much is the success rate of Coturn's hole punching In the case of stun only?

### ISSUE THREAD

**Issue by xujingzhou** [coturn/coturn#700]
Hi, 
1. May I ask what is the success rate of Coturn's hole punching under large-scale and various NAT machines In the case of stun only( not turn)?
2. In addition, is there any way to increase the success rate of hole punching to 99% In the case of stun only(not turn)?  For example: merge the try mode code from pwnat into coturn?

Thanks

**Comment by misi** [comment]
It depeneds on your clients. 
According callstats.io old numbers see:
 https://www.slideshare.net/rootkiskacsa/stun-turn-pocpilot slide 6

**Comment by xujingzhou** [comment]
> 
> 
>     1. It depeneds on your clients.
>        According callstats.io old numbers see:
>        https://www.slideshare.net/rootkiskacsa/stun-turn-pocpilot slide 6
> 
>     2. No! There is no other way only TURN and may you still could't reach 99.99%

If there has turn server, why can't the success rate of the hole punching reach to 99.99%?

**Comment by misi** [comment]
There are some firewalls that inspect packets and packet patterns and they may understand that trun on port 443 is not fully following/matching the normal https traffic pattern/behavior.
