### ISSUE TITLE
Make coturn work reverse proxied through nginx

### ISSUE THREAD

**Issue by karolyi** [coturn/coturn#702]
Hey @misi,

so as discussed in #428, the need of putting coturn behind an nginx reverse proxy arises. Here's what nginx as a webserver does:

- it terminates the TLS connection coming from the browser, decrypts the content to plaintext.
- then with [proxy_pass](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass), it forwards a plain (or another TLS encapsulated specified by its configuration) HTTP connection somewhere on another host
- while forwarding to the other 'inner' host, it adds a HTTP `X-Forwarded-For` header that contains the original IP that connected to the nginx endpoint, so coturn could know where the connection actually came from, if required.

This is advantageous for 2 reasons:
- Most rented servers at various hosters have only one public facing IPv4 address, with port 443 already dedicated to HTTPS. With this, coturn could also work externally on port 443 (reverse proxied by nginx), and work with more corporate firewalls not letting custom ports through: they mostly allow only port 443 and 80
- Certificate generation is automated with letsencrypt and its nginx module, meaning that coturn doesn't have to care about certificates at all, because that part is factored out to nginx (again TLS termination happens only there)

Now the question is, if the TURN protocol with WebRTC is something HTTP protocol based. I'm not an expert in WebRTC, so my knowledge lacks that part. But I would assume it is, because it comes from a browser, or maybe if not fully HTTP based, then it can upgrade to websockets (also supported by nginx).

Questions arise:
- Is something like this possible, in your opinion? From what I've gathered by searching around a couple days, the TURN protocol itself is not HTTP based, but maybe equippable with something that is.
- Do you also need the *source port* of the transmitting IP in order for TURN to work?

Let's brainstorm this more in hopes of finding a way for this to work. Maybe if there's no other solution, we could define a new port for coturn that speaks HTTP, and thus would be able to be reverse proxied from nginx. I'm happy to answer all your questions, should you have some.

**Comment by karolyi** [comment]
To address your concerns about the admin UI: nginx can differentiate between various virtual hosts defined, based on [TLS SNI](https://en.wikipedia.org/wiki/Server_Name_Indication), so having a virtualhost for the admin UI (and connecting that to a different port of coturn) and having another virtualhost for the actual TURN functionality (connected to again another port of coturn) shouldn't be an issue.

**Comment by misi** [comment]
@karolyi 
First of all sorry for the late reply.

I did't made such setup yet, so I don't have direct experience with it. 
According  you are right using TLS SNI and different domain name for the web and turn may could work, but still proxy will hide the original source IP address AFAIU, and coturn loadbalance to different threads based on source IP-s. So it will load only load only one thread/core on a multi core machine that maybe not optimal.

>Now the question is, if the TURN protocol with WebRTC is something HTTP protocol based.
No, they are not! STUN and RTP are binary protocols, these are even not text based like HTTP.

I would say it is best way IMHO to keep stun/turn separated on a server from the web server so from the app part and from the signaling.

**Comment by karolyi** [comment]
That's unfortunate.

I will have to trick around with nginx and certbot for the certification creation, and then build some automation to hand that over to coturn so it could always use a valid certificate. Also, coturn behind port 443 (HTTPS) seems to be not doable, since nginx already sits there, and the built-in API in coturn wants to only talk HTTPS. No reverse proxy to that backend either.

Let me know if I'm wrong here.

Does the HUP signal make coturn reload its deployed certificate?

**Comment by omgold** [comment]
Actually it is possible to use nginx to proxy both turn and http services on the same ip/port. You need to use the stream proxy feature of nginx in combination with ssl-preread (not the http proxy). See e.g. 

https://jitsi.github.io/handbook/docs/devops-guide/turn

Depending on your setup you may need to use different ssl_preread variables to get the mapping work reliably, though. Have to try.

**Comment by cruizba** [comment]
@karolyi any news? Where you able to run coturn behind nginx?

It would be interesting for our project to deploy it at `<url>/turn` or something like that.

**Comment by karolyi** [comment]
I don't use it behind an nginx proxy. Firstly, it's UDP based (not sure if nginx can proxy that), and secondly, it's not an HTTP compatible protocol.

You'll have to make due with a custom port, like I did.

**Comment by karolyi** [comment]
Added to this, the only interface of it I use behind an nginx proxy, is the HTTP admin interface, but tha is also something you'll need to secure with an authentication, if you decide to do that.

**Comment by getarun** [comment]
As omgold suggests above. Udp via nginx works:
```
stream {

    upstream turn_backend {
        server xxx.xxx.xxx.xxx:3478;
    }

    server {
        listen 443 udp;
	proxy_pass turn_backend;
        ssl_preread on;
  }
}
```
Thanks :)

**Comment by karolyi** [comment]
@getarun can you prove that you get port 443 RTC candidates with your config?

**Comment by mrhaydari** [comment]
> interesting.
> 
> I'm gonna try this out and give feedback.

15 days later, what happened to the feedback?

**Comment by mrhaydari** [comment]
nginx module

```
stream {
    map $ssl_preread_server_name $name {
        turn.url.com url_backend;
        turn-turn.url.com turn_server ;
    }

    upstream url_backend {
        server 127.0.0.1:4444;
    }

    upstream turn_server {
        server public_ip:5349;
    }

    server {
        listen 443;
        listen [::]:443;
        ssl_preread on;
        proxy_pass $name;
        proxy_buffer_size 10m;
    }
}
```
// sites-enabled

```
server {
    server_name turn.url.com;

    listen 4444 ssl;
    listen [::]:4444 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/url.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/url.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 
}

```
turnserver.conf

```
listening-port=5349

```
[trickle-ice](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) log

```
0.010	rtp	host	186199869	udp	98efdfda-020d-4bf2-8203-32b534412e1e.local	61769	126 | 30 | 255
0.011	rtp	host	1068015679	udp	84d3b0d5-3de2-47e5-8461-2dcc575c4c75.local	61770	126 | 40 | 255
0.162	rtp	srflx	842163049	udp	5.123.79.77	6149	100 | 30 | 255
0.201	rtp	relay	166912235	udp	xxx.xxx.xxx.xxxx	59911	2 | 30 | 255
0.203	Done

```

**Comment by karolyi** [comment]
> > interesting.
> > I'm gonna try this out and give feedback.
> 
> 15 days later, what happened to the feedback?
> 
> [TCP UDP load balancer](https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/)

A critical innodb bug happened in mariadb, but I don't see how that is related here.

So what nginx does is a basic UDP port forward added with come load balancing. This able to be done on the kernel level as well, and is probably much faster. There is no SNI support, there is no protocol level TLS negotiation, it's just a simplistic portforward.

Mind you, the upcoming QUIC protocol (also advertised as HTTP/3), will use the same port.

**Comment by fl0r1s** [comment]
Thanks for the effort. Can you please elaborate on how this nginx module works @mrhaydari ? 

I'm looking specifically to run coturn from a docker-compose stack and reverse proxy using nginx. Do I need to create both turn.example.com and turn-turn.example.com cnames? Any extra info would be greatly appreciated.

**Comment by 0xdefaced** [comment]
nginx.conf:
```
http {
    [...]
}
stream {
    server {
        listen <server ipv4>:5349 ssl;
        listen <server ipv6>:5349 ssl;

        ssl_certificate             /etc/letsencrypt/live/turn.server.domain/fullchain.pem;
        ssl_certificate_key         /etc/letsencrypt/live/turn.server.domain/privkey.pem;
        ssl_session_ticket_key      /etc/nginx/nginx_session_ticket_key;
        ssl_dhparam                 /etc/ssl/certs/dhparam.pem;

        ssl_protocols               TLSv1.2 TLSv1.3;
        ssl_ciphers                 "EECDH+AESGCM:EDH+AESGCM:EECDH:EDH:!SHA:!MD4:!RC4:!LOW:!MEDIUM:!CAMELLIA:!ECDSA:!DES:!DSS:!3DES:!NULL";
        ssl_ecdh_curve              X25519:sect571r1:secp521r1:secp384r1;
        ssl_prefer_server_ciphers   on;

        ssl_session_timeout         4h;
        ssl_session_tickets         on;

        proxy_ssl                   off;
        proxy_pass                  localhost:3478;
    }
}
```
This will terminate the TLS connection at nginx and relay the unecrypted traffic to coturn which is listening on localhost:3478. For UDP add `udp` to the `listen` parameter.

**Comment by 0xdefaced** [comment]
> @0xdefaced you use both `ssl` and `udp` on the same line?

@elhe26 Yes, should do the trick https://nginx.org/en/docs/stream/ngx_stream_core_module.html#listen

**Comment by uniuuu** [comment]
Hi @0xdefaced @karolyi 
What would be configuration labels/rules for Traefik V2 ?

**Comment by TLATER** [comment]
Is there any reason this ticket is still open, given it clearly already works? The fact that this hasn't been documented somewhere nice?

**Comment by WinstonPais** [comment]
Used a similar config to what @mrhaydari Mentioned, listening at 443 and Proxy passing to 5349. This works well with Chrome able to see relay candidates. But This doesn't work with Firefox. Any help is appreciated.

Firefox only gives host candidates and not relay.

**Comment by TafkaMax** [comment]
How do you guys get the web-admin port to work?

I am running coturn in a container and for testing I exposed my web-admin UI using example.com:8080

Now I wish to put this behind reverse proxy, to IP limit to an internal network.

I did it, but now there seems to be a problem with logging in.

I can see the login form, but adding the username and password it redirects back to the /logon endpoint and does nothing.

**Comment by TafkaMax** [comment]
Does it have something to do with these messages in the stdout logs?

592: : web_admin_input_handler socket to be detached: 0x7fba3402c500, st=56, sat=3
592: : web_admin_input_handler new detached socket: 0x7fba34004230, st=56, sat=3
592: : web_admin_input_handler: web-admin socket to be closed in client handler: s=0x7fba3402c500

I have verbose mode enabled

**Comment by cluneke416** [comment]
Ive tried everything listed here but nothing has worked, been at it for 5hrs so far. Can someone confirm that these methods still work and possibly elaborate on how to configure this?

**Comment by breakingflower** [comment]
@cluneke416 

I'm using the following very simple location block for nginx reverse proxy without problems for 6 months now: 
```
location / {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app coturn;
    set $upstream_port 3478;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}
```

based on this docker compose 

```
services:

  coturn_db:
    image: postgres
    container_name: coturn_db
    restart: unless-stopped
    volumes:
      - xxxxxxx/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - xxxxxxxx/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=XXXXXX
      - POSTGRES_PASSWORD=${COTURN_PG_PASS}
      - POSTGRES_DB=XXXXXX
    networks:
      - coturn

  coturn:
    image: coturn/coturn:alpine
    container_name: coturn
    restart: always
    environment:
      - POSTGRES_USER=xxxxx
      - POSTGRES_PASSWORD=${COTURN_PG_PASS}
      - POSTGRES_DB=xxxxxx
    volumes:
      - xxxxxx/turnserver.conf:/etc/turnserver.conf:ro
      - xxxxxx/privkey.pem:/etc/ssl/private/privkey.pem:ro
      - xxxxxx/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
    network_mode: "host"
    depends_on:
      - coturn_db
 ```

i am using a linuxserver/swag nginx reverse proxy and tested my connection with trickle ice.

**Comment by cluneke416** [comment]
@breakingflower 
My nginx and coturn are on different hosts, and I'm not using docker

**Comment by breakingflower** [comment]
I'm sorry I can't help you with that.

**Comment by AlbiRadtke** [comment]
@cluneke416 
Have you found a solution in the meantime?
My configuration is exactly the same: 
I have Nginx as a reverse proxy on web server A, the Coturn server on web server B
Via stream I also manage the forwarding to the coturn server, so that Nextcloud confirms the connection. But no telephony or video telephony traffic arrives at the coturn server.

Config Nginx:
```
stream {
        server {
                listen 5720 ssl;

                ssl_certificate             /etc/letsencrypt/live/turn.url/fullchain.pem;
                ssl_certificate_key         /etc/letsencrypt/live/turn.ulr/privkey.pem;
                ssl_dhparam                 /etc/letsencrypt/ssl-dhparams.pem;

                ssl_protocols               TLSv1.2 TLSv1.3;
                ssl_prefer_server_ciphers   on;

                ssl_session_timeout         4h;
                ssl_session_tickets         on;

                proxy_ssl                   off;
                proxy_pass                  192.168.xxx.xxx:3478;
        }
}
```
Config turnserver.conf
```
realm=turn.url
server-name=turnserver
fingerprint
total-quota=100
bps-capacity=0
stale-nonce=600
no-multicast-peers
listening-ip=0.0.0.0
external-ip=192.168.xxx.xxx
syslog
verbose
use-auth-secret
static-auth-secret=my_secret
cli-password=myclipw

# SSL certificates
cert=/etc/letsencrypt/live/turn.url/cert.pem
pkey=/etc/letsencrypt/live/turn.url/privkey.pem

# for TURN over TLS, which can bypass firewalls
#tls-listening-port=5720
listening-port=3478
min-port=39500
max-port=39700
```

Fritzbox ports to/from reverseproxy:
HTTP: 80
HTTPS: 443
HTTPS: 5720

Fritzbox ports to/from turnserver:
39500-39700 UDP

I hope one of you can help me?
Many thanks in advance! :)

**Comment by NetSamurai** [comment]
@breakingflower are you able to get matrix to work with video calls outside the LAN with that?

**Comment by breakingflower** [comment]
it's so silly that you mention this now as i looked at this post only hours ago. I noticed that indeed it did not work outside of lan. I switched to traefik as proxy some time ago and have not been able to get it to work.

**Comment by MarcelRobitaille** [comment]
> nginx module
> 
> ```
> stream {
>     map $ssl_preread_server_name $name {
>         turn.url.com url_backend;
>         turn-turn.url.com turn_server ;
>     }
> 
>     upstream url_backend {
>         server 127.0.0.1:4444;
>     }
> 
>     upstream turn_server {
>         server public_ip:5349;
>     }
> 
>     server {
>         listen 443;
>         listen [::]:443;
>         ssl_preread on;
>         proxy_pass $name;
>         proxy_buffer_size 10m;
>     }
> }
> ```
> 
> // sites-enabled
> 
> ```
> server {
>     server_name turn.url.com;
> 
>     listen 4444 ssl;
>     listen [::]:4444 ssl; # managed by Certbot
>     ssl_certificate /etc/letsencrypt/live/url.com/fullchain.pem; # managed by Certbot
>     ssl_certificate_key /etc/letsencrypt/live/url.com/privkey.pem; # managed by Certbot
>     include /etc/letsencrypt/options-ssl-nginx.conf; 
>     ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 
> }
> ```
> 
> turnserver.conf
> 
> ```
> listening-port=5349
> ```
> 
> [trickle-ice](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) log
> 
> ```
> 0.010	rtp	host	186199869	udp	98efdfda-020d-4bf2-8203-32b534412e1e.local	61769	126 | 30 | 255
> 0.011	rtp	host	1068015679	udp	84d3b0d5-3de2-47e5-8461-2dcc575c4c75.local	61770	126 | 40 | 255
> 0.162	rtp	srflx	842163049	udp	5.123.79.77	6149	100 | 30 | 255
> 0.201	rtp	relay	166912235	udp	xxx.xxx.xxx.xxxx	59911	2 | 30 | 255
> 0.203	Done
> ```
@mrhaydari would you mind explaining how this works? Why are you proxying the public IP? Nginx as a reverse proxy normally proxies the local IP right? What is turn.url.com and turn-turn.url.com? Do I need a second subdomain?

**Comment by goekce** [comment]
I followed @mrhaydari s snippet and clean up a bit. Websites work however turnserver does not work according to the [webrtc test](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) does not work.

```
stream {                                                                                                                                                                                                                                     
        map $ssl_preread_server_name $name {                                                                                                                                                                                                 
                turn.aydos.de turn_server;                                                                                                                                                                                                   
                default       default_backend;                                                                                                                                                                                               
        }                                                                                                                                                                                                                                    
        upstream turn_server {                                                                                                                                                                                                               
                server public_ip:3478;                                                                                                                                                                                                  
        }                                                                                                                                                                                                                                    
        upstream default_backend {                                                                                                                                                                                                           
                server localhost:4430;                                                                                                                                                                                                       
        }                                                                                                                                                                                                                                    
        server {
                listen 443;
                listen [::]:443;
                ssl_preread on;
                proxy_pass $name;
                proxy_buffer_size 10m;
        }
}

http {
    server {
        server_name example.com;
        listen      4430 ssl;
        listen [::]:4430 ssl;
    }
    # other sites
    include sites-enabled/*;
}
```

**Comment by goekce** [comment]
I followed @mrhaydari s snippet and clean up a bit. Note that it works only for TLS connections (turns, stuns). I tested only `stuns:turn.example.com:443` on https://icetest.info/. On Firefox it worked, however not in Chromium:

```
stream {                                                                                                                                                                                                                                     
        map $ssl_preread_server_name $name {                                                                                                                                                                                                 
                turn.example.com turn_server;                                                                                                                                                                                                   
                default       default_backend;                                                                                                                                                                                               
        }                                                                                                                                                                                                                                    
        upstream turn_server {                                                                                                                                                                                                               
                server localhost:3478;                                                                                                                                                                                                  
        }                                                                                                                                                                                                                                    
        upstream default_backend {                                                                                                                                                                                                           
                server localhost:4430;                                                                                                                                                                                                       
        }                                                                                                                                                                                                                                    
        server {
                listen 443;
                listen [::]:443;
                ssl_preread on;
                proxy_pass $name;
                proxy_buffer_size 10m;
        }
}

http {
    server {
        server_name example.com;
        listen      4430 ssl;
        listen [::]:4430 ssl;
    }
    # other sites
    include sites-enabled/*;
}
```
5349 or 3478 can both use TLS.

**Comment by MohammedNoureldin** [comment]
This question seems directly related to my issue https://github.com/coturn/coturn/issues/1523

Could someone please check it and tell if you can help?

**Comment by schlagmichdoch** [comment]
@mrhaydari @goekce  This looks great, thanks!

Unfortunately, this still is not the complete solution for me and I would appreciate your help!

> Note that it works only for TLS connections (turns, stuns)

This is a problem as most browsers support TURNS but not all support STUNS. @WinstonPais Have you found a solution?

Is it possible to configure nginx in a similar fashion to add STUN on port 80 by adding a server block for port 80?

## My current setup
Coturn _turnserver.conf_:
```conf
listening-port=3478
tls-listening-port=5349
```

- `example.com:443` --decrypt ssl via nginx--> serve page which runs on port 4444
- `stuns:turn.example.com:5349` -> coturn tls (5349)
- `turns:turn.example.com:5349` -> coturn tls (5349)
- `stun:turn.example.com:3478` -> coturn (3478)

## Your setup (@mrhaydari) (as far as I understand)
```conf
listening-port=3478
tls-listening-port=5349
```
- `example.com:443` --decrypt ssl via nginx--> serve page which runs on port 4444
- `stuns:turn.example.com:443` --decrypt ssl via nginx--> coturn (3478)
- `turns:turn.example.com:443` --decrypt ssl via nginx--> coturn (3478)

At what point is the TURNS ssl connection decrypted in the nginx config? Or is it only relayed to coturn and decrypted over there? Then your config actually looks like this?
## Your setup (variant)
```conf
listening-port=3478
tls-listening-port=5349
```
- `example.com:443` --decrypt ssl via nginx--> serve page which runs on port 4444
- `stuns:turn.example.com:443` --nginx--> coturn tls (5349)
- `turns:turn.example.com:443` --nginx--> coturn tls (5349)

## My target setup
I'd like to add one classic STUN candidate.
Everything should then be available on ports 80 and 443:
- `example.com:443` --decrypt ssl via nginx--> serve page which runs on port 4444
- `example.com:80` --redirect via nginx--> https://example.com/
- `stuns:turn.example.com:443` --decrypt ssl via nginx--> coturn (3478)
- `turns:turn.example.com:443` --decrypt ssl via nginx--> coturn (3478)
- `stun:turn.example.com:80` --nginx--> coturn (3478)

## Config port 80 - Draft 1
Is this possible?

nginx module

```nginx
stream {
    map $ssl_preread_server_name $name {
        example.com url_backend;
        turn.example.com turn_server;
    }

    upstream turn_server {
        server 127.0.0.1:3478;
    }

    server {
        listen 80;
        listen [::]:80;
        ssl_preread on;
        proxy_pass $name;
    }
}

stream {
    map $ssl_preread_server_name $name {
        example.com url_backend;
        turn.example.com turn_server;
    }

    upstream url_backend {
        server 127.0.0.1:4444;
    }

    upstream turn_server {
        server 127.0.0.1:3478;
    }

    server {
        listen 443;
        listen [::]:443;
        ssl_preread on;
        proxy_pass $name;
    }
}
```

// sites-enabled

```nginx
server {
    server_name example.com;

    listen 4444 ssl;
    listen [::]:4444 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/url.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/url.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 
}
```

turnserver.conf

```conf
listening-port=3478
```

##  Config port 80 - Draft 2 - `server_name` directive in stream block
since nginx 1.25.5 we can add a server_name directive to a stream block:
https://nginx.org/en/docs/stream/ngx_stream_core_module.html#server_name

Maybe we could simplify the nginx module then:
```nginx
stream {
    upstream url_backend {
        server 127.0.0.1:4440;
    }

    upstream turn_server {
        server 127.0.0.1:3478;
    }

    server {
        server_name turn.example.com
        listen 80;
        listen [::]:80;
        proxy_pass turn_server;
    }

    server {
        server_name example.com
        listen 80;
        listen [::]:80;
        proxy_pass url_backend;
    }
}

stream {
    map $ssl_preread_server_name $name {
        example.com url_backend;
        turn.example.com turn_server;
    }

    upstream url_backend {
        server 127.0.0.1:4444;
    }

    upstream turn_server {
        server 127.0.0.1:3478;
    }

    server {
        listen 443;
        listen [::]:443;
        ssl_preread on;
        proxy_pass $name;
    }
}
```

// sites-enabled

```nginx
server {
    server_name example.com;

    listen 4440;
    listen [::]:4440;

    rewrite ^ https://example.com$request_uri? permanent;
}

server {
    server_name example.com;

    listen 4444 ssl;
    listen [::]:4444 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/url.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/url.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 
}
```

## Alternative STUN via port 3478
If this is not possible for port 80 without ssl I could simply leave port 3478 open to have this setup, correct?
- `example.com:443` --decrypt ssl via nginx--> serve page which runs on port 4444
- `example.com:80` --redirect via nginx--> https://example.com/
- `stuns:turn.example.com:443` --decrypt ssl via nginx--> coturn (3478)
- `turns:turn.example.com:443` --decrypt ssl via nginx--> coturn (3478)
- `stun:turn.example.com:3478` --> coturn (3478)

I'd be really glad to get any help!
