### ISSUE TITLE
When I use the requests module of Python to log in to web admin, there is an exception。

### ISSUE THREAD

**Issue by qwe624758472** [coturn/coturn#708]
When I use the requests module of Python to log in to web admin, there is an exception。
When using Python to simulate login, the login page is returned.

It turns out that's what happened next
![image](https://user-images.githubusercontent.com/22900394/106136068-a355dc80-6160-11eb-8da8-6fcfa93cfe22.png)

The code for Python is
`# -*- coding:utf-8 -*-
__author__ = "MuT6 Sch01aR"
import requests

url = "https://127.0.0.1:8080/logon"

payload = "uname=lsh&pwd=123456"
headers = {
    'Content-Type': "application/x-www-form-urlencoded",
    'Connection': "keep-alive",
    'User-Agent': "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    'Cache-Control': "no-cache",
    'Postman-Token': "3df272a4-b814-4bdf-8bf8-0da82b5eaa4a"
    }

response = requests.request("POST", url, data=payload, headers=headers,verify=False)

print(response.text)`

please

**Comment by qwe624758472** [comment]
4363: : IPv4. tcp or tls connected to: 113.200.76.118:43832
4363: : send_socket_to_admin_server: --------------success to register callback on web-admin ioa socket
4363: : --------------socket_input_worker 2645
4363: : --------------TCP & TLS  & SCTP & SCTP/TLS  2889
4363: : ret =  0,  len = -1,  line:3025
4363: : --------------socket_input_worker 2645
4363: : --------------TCP & TLS  & SCTP & SCTP/TLS  2889
4363: : ret =  404,  len = 404,  line:3025
4363: : socket_input_worker: 000000000000000000if(s->read_cb) {
4363: : web_admin_input_handler: ------------st == TLS_SOCKET 
4363: : web_admin_input_handler: HTTPS (ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2) request: POST /logon HTTP/1.1
Host: ************ :8080
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Postman-Token: 3df272a4-b814-4bdf-8bf8-0da82b5eaa4a
Content-Length: 20

uname=ls85h&pwd=12342256
4363: : web_admin_input_handler socket to be detached: 0x7f99a80998e0, st=56, sat=3
4363: : web_admin_input_handler new detached socket: 0x7f99a80d6a20, st=56, sat=3
4363: : web_admin_input_handler: web-admin socket to be closed in client handler: s=0x7f99a80998e0
4363: : close_ioa_socket_after_processing_if_necessary https server socket closed: 0x7f99a80998e0, st=56, sat=3
4363: : https_admin_server_receive_message: https_admin_server_receive_message
4363: : handle_https: HTTPS connection initial input
4363: : eventcb_bev https server socket closed: 0x7f99a80d6a20, st=56, sat=3, remote addr=113.200.76.118:43832

**Comment by qwe624758472** [comment]
Can I turn off SSL verification of Web admin?

**Comment by misi** [comment]
I think you can't turn out ssl on web admin.. Web admin is dangerous and turned off by default. It is not robust enough as it is today.

**Comment by qwe624758472** [comment]
Thank you for your reply。

**Comment by qwe624758472** [comment]
I didn't open SSL verification on postman, which is also accessible?

**Comment by misi** [comment]
@qwe624758472 
I don't really understand your last question. Can you please clarify it more.. Thanks!
