### ISSUE TITLE
Crashing if I use it with wrong credentials

### ISSUE THREAD

**Issue by dnish** [coturn/coturn#71]
If I add wrong credentials in our WebRTC application and I'm forcing a TURN connection, the coturn server shuts down (https://myserver:5349 is offline). 

Can't find any specific information in my syslog.

**Comment by mom040267** [comment]
which version are you using ?

do you see a crash report (core dump) ?

**Comment by mom040267** [comment]
I cannot reproduce the problem. I need to know the version and more details about authentication scheme.

**Comment by dnish** [comment]
Okay, just tried to reproduce it again - this time without success. Can't figure out if it was a temporary problem, will reopen the issue if I have more information.
