### ISSUE TITLE
Not seeing "prometheus" parameter in turnserver.conf file

### ISSUE THREAD

**Issue by Chandramouli-P** [coturn/coturn#712]
Hello,

"prometheus" parameter is not coming in turnserver.conf file. Do I need to install anything, before installing CoTurn? Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by misi** [comment]
It is here: https://github.com/coturn/coturn/blob/b58166cc90f85eb3dc8178b40ae83dfc34d2c7b1/examples/etc/turnserver.conf#L199

**Comment by Chandramouli-P** [comment]
Hello,

Operating system: Ubuntu 18.04 AWS

Good morning and thank you very much for your reply. I have already gone through that sample configuration file on Internet. But, I can not see "prometheus" parameter in configuration file. I tried to added this "prometheus" parameter manually and CoTurn failed to start. This is for your information.

I installed CoTurn and it is running successfully. But, I can not see "prometheus" parameter anywhere in coturn/examples/etc/turnserver.conf file. Do I need to install anything else before or after installing CoTurn? If so, please tell me what else do I need to install?

Any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello Misi,

Any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

I added "prometheus" parameter in the configuration file and it CoTurn is started successfully. I understand that this uses 9641 port. But, when I am executing netstat command, I am not seeing this service:

root@ip-172-31-32-187:~# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 172.31.32.187:80        0.0.0.0:*               LISTEN      509/turnserver      
tcp        0      0 172.31.32.187:80        0.0.0.0:*               LISTEN      509/turnserver      
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      636/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      722/sshd            
tcp        0      0 172.31.32.187:443       0.0.0.0:*               LISTEN      509/turnserver      
tcp        0      0 172.31.32.187:443       0.0.0.0:*               LISTEN      509/turnserver      
tcp6       0      0 :::22                   :::*                    LISTEN      722/sshd            
tcp6       0      0 :::9100                 :::*                    LISTEN      686/node_exporter   
udp        0      0 127.0.0.53:53           0.0.0.0:*                           636/systemd-resolve 
udp        0      0 172.31.32.187:68        0.0.0.0:*                           635/systemd-network 
udp        0      0 172.31.32.187:80        0.0.0.0:*                           509/turnserver      
udp        0      0 172.31.32.187:80        0.0.0.0:*                           509/turnserver      
udp        0      0 172.31.32.187:443       0.0.0.0:*                           509/turnserver      
udp        0      0 172.31.32.187:443       0.0.0.0:*                           509/turnserver

Am I missing anything? Please help me. Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello Misi,

Any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by hendrikhuels** [comment]
@Chandramouli-P can you show us the logs?
As soon as i activate prometheus in my config, Bad configuration format: prometheus appears.

**Comment by yuanchieh-cheng** [comment]
You could follow these install steps in Dockerfile https://github.com/coturn/coturn/blob/master/docker/coturn/Dockerfile  
It should be the same if you install natively on debian system.  
Don't forget to pull the source code, prometheus works only under 4.5.2  

Please note there is still some memory issue in 4.5.2  
https://github.com/coturn/coturn/issues/666
So my recommendation is to wait for next fixed version.

**Comment by Chandramouli-P** [comment]
Hello team,

Good morning and thank you all for your suggestions. It is working now. Here I am posting the documentation for other users:

wget https://github.com/digitalocean/prometheus-client-c/releases/download/v0.1.3/libprom-dev-0.1.3-Linux.deb
sudo dpkg -i libprom-dev-0.1.3-Linux.deb
wget https://github.com/digitalocean/prometheus-client-c/releases/download/v0.1.3/libpromhttp-dev-0.1.3-Linux.deb
sudo dpkg -i libpromhttp-dev-0.1.3-Linux.deb
sudo apt install libmicrohttpd-dev
sudo apt --fix-broken install
sudo dpkg -i libpromhttp-dev-0.1.3-Linux.deb

Thank you.

Best Regards,
Chandramouli.
