### ISSUE TITLE
How to obtain ip address of client in turn server

### ISSUE THREAD

**Issue by chrisooo3** [coturn/coturn#714]
How can I use some turn server to establish a TCP connection between two machines, each in a different network and behind NAT? 
I mean to which ip address I should send data from client A, and to which address I should send data from B client. 

I am building p2p chat, on a very low level in C#.

**Comment by misi** [comment]
Use the ICE protocol 
See ICE, STUN, TURN RFCs on IETF.
or more high level see how WebRTC use ICE: https://misi.github.io/webrtc-c0d3l4b/#9

**Comment by chrisooo3** [comment]
@misi 
So what should I write in terminal to get know to what ip should I send data?

**Comment by misi** [comment]
@chrisooo3 You need to negotiate it with ICE

**Comment by chrisooo3** [comment]
@misi
could you explain a little bit more?
How can I use the turn server to redirect requests from client A to client B on a low level? So what type of command should I use or what types of application should I use?

**Comment by misi** [comment]
Unfortunately I don't have enough time to support you more. 
Please read RFC-s and understand ICE and TURN protocol. See slides on slideshare or find other sources.. 
If you have specific question I happy to answer, but unfortunately I don't have the time to support you more.

**Comment by chrisooo3** [comment]
Hi @misi 
So I have specific questions:

I am using xirsys turn server. 

Now I want to connect client A which is behind symmetric NAT with client B which is also behind symmetric NAT. 

1) On which port should I listen on client A?
2) To which ip and port should I connect to establish tcp connection with client A from client B?
3) How can I obtain the ip of xirsys turn server?

On client A I want to run this command, but I dont know which port should I use:
```sh
sudo tcpdump -ni any port ???
```
On client B I want to run this command, but I dont know which ip and port should I use:
```sh
echo "Hello from B" | netcat ip??? port???
```
PS. 
The xirsys after executhing this command:
```sh
curl -s -H "Content-type: application/json" -XPUT "https://name:pass@global.xirsys.net/_turn/app" -d '{"format": "urls"}'
```
Return something like this
```sh
{
   "s" : "ok",
   "v" : {
      "iceServers" : {
         "credential" : "123",
         "urls" : [
            "stun:eu-turn4.xirsys.com",
            "turn:eu-turn4.xirsys.com:80?transport=udp",
            "turn:eu-turn4.xirsys.com:3478?transport=udp",
            "turn:eu-turn4.xirsys.com:80?transport=tcp",
            "turn:eu-turn4.xirsys.com:3478?transport=tcp",
            "turns:eu-turn4.xirsys.com:443?transport=tcp",
            "turns:eu-turn4.xirsys.com:5349?transport=tcp"
         ],
         "username" : "123"
      }
   }
}
```
