### ISSUE TITLE
am I logging STUN or TURN?

### ISSUE THREAD

**Issue by Carpintonto** [coturn/coturn#716]
I'm running Version: 4.5.0.7-1ubuntu2.18.04.3 set up exactly as described at

https://prosody.im/doc/coturn

plus logging enabled

It totally works with Android Conversations app.

How can I tell if I have established a STUN or TURN connection from the log?

I am watching the log scroll with tail -f and updates append until we disconnect, which I think would suggest TURN ?

Thanks to all.

**Comment by misi** [comment]
TURN is extension of STUN protocol. So it is confusing how can I answer. 
Maybe very simplified if you see port Allocaction in a session then it is TURN.

**Comment by Carpintonto** [comment]
thanks misi.
Examples of what I think you mean:
```
IPv4. Local relay addr: XXX.XXX.XXX.XX:54655
New UDP endpoint: local addr XXX.XXX.XXX.XX:3478
```
recurring and changing ports continuously throughout the calls evidence TURN.
That makes sense.

**Comment by misi** [comment]
HTH: https://misi.github.io/webrtc-c0d3l4b/#9

**Comment by Carpintonto** [comment]
Great explanation - thank you.  

Also very helpful for the prosody set-up is the TURN REST API section of
https://github.com/coturn/coturn/blob/master/README.turnserver

I find the coturn documentation to be extensive and really good - just SO much of it !!
