### ISSUE TITLE
socket: Protocol not supported

### ISSUE THREAD

**Issue by averyzhong** [coturn/coturn#722]
It's always this error to run on CentOS 7

RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.2 'dan Eider'
0: : 
Max number of open files/sockets allowed for this process: 1000000
0: : 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 500000 (approximately)
0: : 

==== Show him the instruments, Practical Frost: ====

0: : TLS supported
0: : DTLS supported
0: : DTLS 1.2 supported
0: : TURN/STUN ALPN supported
0: : Third-party authorization (oAuth) supported
0: : GCM (AEAD) supported
0: : OpenSSL compile-time version: OpenSSL 1.1.1g FIPS  21 Apr 2020 (0x1010107f)
0: : 
0: : SQLite supported, default database location is /var/lib/coturn/turndb
0: : Redis supported
0: : PostgreSQL supported
0: : MySQL supported
0: : MongoDB is not supported
0: : 
0: : Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: : Domain name: 
0: : Default realm: avery
0: : WARNING: cannot find certificate file: turn_server_cert.pem (1)
0: : WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
0: : WARNING: cannot find private key file: turn_server_pkey.pem (1)
0: : WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
0: : NO EXPLICIT LISTENER ADDRESS(ES) ARE CONFIGURED
0: : ===========Discovering listener addresses: =========
0: : Listener address to use: 127.0.0.1
0: : Listener address to use: 91.141.5.202
0: : Listener address to use: 172.17.0.1
0: : Listener address to use: 10.244.1.0
0: : Listener address to use: 10.244.1.1
0: : Listener address to use: ::1
0: : =====================================================
0: : Total: 4 'real' addresses discovered
0: : =====================================================
0: : NO EXPLICIT RELAY ADDRESS(ES) ARE CONFIGURED
0: : ===========Discovering relay addresses: =============
0: : Relay address to use: 91.141.5.202
0: : Relay address to use: 172.17.0.1
0: : Relay address to use: 10.244.1.0
0: : Relay address to use: 10.244.1.1
0: : Relay address to use: ::1
0: : =====================================================
0: : Total: 5 relay addresses discovered
0: : =====================================================
0: : pid file created: /var/run/turnserver.pid
0: : IO method (main listener thread): epoll (with changelist)
0: : WARNING: I cannot support STUN CHANGE_REQUEST functionality because only one IP address is provided
0: : Wait for relay ports initialization...
0: :   relay 91.141.5.202 initialization...
0: :   relay 91.141.5.202 initialization done
0: :   relay 172.17.0.1 initialization...
0: :   relay 172.17.0.1 initialization done
0: :   relay 10.244.1.0 initialization...
0: :   relay 10.244.1.0 initialization done
0: :   relay 10.244.1.1 initialization...
0: :   relay 10.244.1.1 initialization done
0: :   relay ::1 initialization...
0: :   relay ::1 initialization done
0: : Relay ports initialization done
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=0 created
0: : turn server id=1 created
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=2 created
0: : turn server id=3 created
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=4 created
0: : turn server id=5 created
0: : turn server id=7 created
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=6 created
0: : IPv4. UDP listener opened on: 127.0.0.1:3478
0: : IPv4. UDP listener opened on: 91.141.5.202:3478
0: : IPv4. UDP listener opened on: 172.17.0.1:3478
0: : IPv4. UDP listener opened on: 10.244.1.0:3478
0: : IPv4. UDP listener opened on: 10.244.1.1:3478
0: : IPv6. UDP listener opened on: ::1:3478
0: : Total General servers: 8
0: : IO method (auth thread): epoll (with changelist)
0: : IO method (admin thread): epoll (with changelist)
0: : IPv4. CLI listener opened on : 127.0.0.1:5766
0: : IO method (auth thread): epoll (with changelist)
0: : SQLite DB connection success: /var/lib/coturn/turndb
0: : IO method (auth thread): epoll (with changelist)
0: : IO method (auth thread): epoll (with changelist)
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 127.0.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 127.0.0.1:3478
socket: Protocol not supported
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 127.0.0.1:3478
0: : IPv4. TCP listener opened on : 127.0.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 127.0.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 127.0.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 127.0.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 91.141.5.202:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 91.141.5.202:3478
socket: Protocol not supported
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 91.141.5.202:3478
0: : IPv4. TCP listener opened on : 127.0.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 91.141.5.202:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 91.141.5.202:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 91.141.5.202:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 91.141.5.202:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 172.17.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 172.17.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 172.17.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 91.141.5.202:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 172.17.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 172.17.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 172.17.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 172.17.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 172.17.0.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.0:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.0:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.0:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.0:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.0:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.0:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.0:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.0:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.1:3478
socket: Protocol not supported
0: : IPv6. TCP listener opened on : ::1:3478
socket: Protocol not supported
0: : IPv6. TCP listener opened on : ::1:3478
socket: Protocol not supported
0: : IPv6. TCP listener opened on : ::1:3478
socket: Protocol not supported
0: : IPv4. TCP listener opened on : 10.244.1.1:3478
socket: Protocol not supported
0: : IPv6. TCP listener opened on : ::1:3478
socket: Protocol not supported
0: : IPv6. TCP listener opened on : ::1:3478
socket: Protocol not supported
0: : IPv6. TCP listener opened on : ::1:3478
socket: Protocol not supported
0: : IPv6. TCP listener opened on : ::1:3478
socket: Protocol not supported
0: : IPv6. TCP listener opened on : ::1:3478

**Comment by zrx1118** [comment]
I met the same problem.How to resolve
