### ISSUE TITLE
300 Alternate-Server Redundancy Possibilities

### ISSUE THREAD

**Issue by Cybermilitia** [coturn/coturn#726]
Hi all,

I have a problem about 300 Alternate-server feature. It's very useful and easy-to-use feature for the load balancing. I tested it. However, as far as I understand, this feature can not cover the redundancy scenarios. 

I mean, when I configured -for example- two different servers as alternate-servers and one of them is down later on, there is no way to detect the situation and then to recover it easily - ie. a health check may be, then to remove the server from the list etc.  

I can't see any clue about 300 Alternate Server feature with this type of redundancy scenarios. Did I miss something? What do you use for it? 

I attached the sniffer trace by testing the alternate server system I set up with https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

As you can see, .91 routed the Allocate Request to .92

![wireshark](https://user-images.githubusercontent.com/12972305/109972960-e3345480-7d08-11eb-841d-39e14a14b6b1.png)

**Comment by jbg** [comment]
One way we have done it before is to anycast an IP from the servers running coturn (advertising the IP from each server using BGP and using a health check on coturn to drop the BGP advertisement if coturn is not healthy) and then use ALTERNATE-SERVER to redirect the user to that server's own unicast IP (so that long-running sessions don't get set up on the anycast IP which would cause them to break if it routes to a different server for any reason).

The main problem is, Firefox doesn't support ALTERNATE-SERVER.

**Comment by Cybermilitia** [comment]
Thanks for your reply, @jbg Sorry for my clumsy censoring attempt for IPs:

![image](https://user-images.githubusercontent.com/12972305/111270612-219f0d00-8641-11eb-8f87-9995c9d90be3.png)

As you said, looks Firefox doesn't support this method.

So, what is the solution can be used? I mean the Load balancing + High Availability. I'm not interested in DNS or other commercial solutions. I've tried Nginx by the way, and as far as I understand some users use HAProxy for them. What's your opinion about this? Would you tell me a bit about it, please?

**Comment by marcoberetta96** [comment]
@Cybermilitia have you tried to setup an HAProxy? I'm interested in Load balancing + High Availability as you are/were and I end up here :)

**Comment by Cybermilitia** [comment]
We solved this issue by creating another app that sends binding requests to turn servers under control and recieves responses from them.

**Comment by eakraly** [comment]
@Cybermilitia Interesting approach!
Yes, alternate-server feature is not load balancing or redundancy mechanism.
Most people use DNS load balancing as a redundancy and load balancing mechanism (and using DNS healthchecks as TURN health checks).
