### ISSUE TITLE
> still interesting what is this?

### ISSUE THREAD

**Issue by Carpintonto** [coturn/coturn#728]
> still interesting what is this?

BINDING requests are normal STUN requests.  I see millions of those per day on my public STUN servers.

Address spoofing is usually done to DDoS the spoofed address (though STUN isn't really the most effective protocol to perform this kind of attack).

_Originally posted by @weiss in https://github.com/coturn/coturn/issues/603#issuecomment-677579596_

**Comment by Carpintonto** [comment]
I am just curious to know the order of operations request, authorization, binding, and what is the default log level?
What does 

> incoming packet BINDING processed, success

 mean exactly?

It blew my mind to see how big log files get in 24 hours, but I've figured out I'm probably incurring as much bandwidth tailing the logs via ssh as the requests themselves. (I have disabled TURN)

The unauthorized requests invariably end up 

> closed (2nd stage), user <> realm <turn.domain.tld> origin <>, local X.X.X.X:3478, remote X.X.X.X:XXX, reason: allocation watchdog determined stale session state

I recall seeing the switch to toggle logging binding requests in verbose level.  Could it be possible to have an option to eliminate them at any less than verbose level?

Also, I found a useful program for developing denied-peer-ip lists
https://github.com/NetSPI/NetblockTool

**Comment by Carpintonto** [comment]
finding some answers:

to my first question see here
https://github.com/coturn/coturn/issues/435#issuecomment-547290965

"BINDING success" <> binding request in terms of the --log-binding switch

still would like to know if in the log lines 

> closed (2nd stage), user <> realm <turn.domain.tld> origin <>, local X.X.X.X:3478, remote X.X.X.X:XXX, reason: allocation watchdog determined stale session state

is the remote IP the "[reflexive transport address](https://tools.ietf.org/html/rfc8489#page-6)"?

**Comment by misi** [comment]
So sorry for the delayed answer. 
Remote IP is the client IP that server sees, so it is the server reflexive transport address.

**Comment by Carpintonto** [comment]
not at all misi.  

I have had time to configure and compare different scenarios, and am slowly beginning to understand what is being logged.  For my purposes the server totally works. Thanks for the great work.  

Also, I never knew how popular I could be until I spun up coturn. Yikes !!
