### ISSUE TITLE
RFC5245 implementation

### ISSUE THREAD

**Issue by john357smith** [coturn/coturn#729]
Hi,

I see COTURN receiving STUN BIND request, I see submitted BIND response but that's all ... RFC5245 defines connectivity checks as 4-way handshake but COTURN handles only 2 way - any idea what is wrong here?

Thanks.

**Comment by misi** [comment]
ICE is between ICE agents. The 4 way check is between somehow "client 2 client". 
Both ICE agent act it is a server and other is the client and after it there is swap so 2 times 2way check = 4
coturn is doing right the 2 way stun binding request handling.

**Comment by ggarber** [comment]
Please reopen if the latest comment didn't answer the question.
