### ISSUE TITLE
CoTurn stopped functioning suddenly

### ISSUE THREAD

**Issue by Chandramouli-P** [coturn/coturn#730]
Hello,

CoTurn (v.4.5.2), Ubuntu 18.04 server, AWS. 

I am using CoTurn in 3 servers. I am clearly noticing that CoTurn is stopped functioning frequently. Please note that CoTurn service is running and not seeing any errors in the log file. When I restarted the server, it is starting functioning again. 

Can anyone tell what could be the root cause and suggest a solution? Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Good morning and any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello Team,

Good morning and any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello Team,

Good morning and any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by hakicode** [comment]
I am also having the same problem on the latest automatic installation on ubuntu, I need your help as well, hope someone can help us.

**Comment by Chandramouli-P** [comment]
Hello Team,

Good morning and any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello Team,

Good morning and any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by Mart-Bogdan** [comment]
Hello, @Chandramouli-P. I have no idea how coturn work, but I could suggest some workaround.

If it's working for few days, and restart helps. I'd suggest creating crontab job that would restart daemon (not the whole server) once a day. Dirty workaround, but that should do the work. I've used a similar hack in production. Perfectly would be to set up restarts on not working hours.

**Comment by Chandramouli-P** [comment]
Hello @Mart-Bogdan ,

Good morning and thank you for your suggestion. It seems that this issue is resolved. I am not seeing this behavior from last couple of days. If it repeats again, I will follow your suggestion. Thank you.

Best Regards,
Chandramouli.
