### ISSUE TITLE
Stun working but turn not

### ISSUE THREAD

**Issue by fleixi** [coturn/coturn#731]
I have running coturn 4.5.2 on an Arch-Linux with this config:
```
tls-listening-port=5349
fingerprint
realm= my.test.de
use-auth-secret
static-auth-secret=XXXXXXXXX
total-quota=100
bps-capacity=0
stale-nonce
log-file=/var/log/turnserver/turn.log
no-multicast-peers
cert=/var/www/ssl/cert_test.pem
pkey=/var/www/ssl/key_test.pem
no-tlsv1
no-tlsv1_1
external-ip=<public-ip>
listening-ip=<public-ip>
relay-ip=<public-ip>
```

real,static-auth-secret, external-ip,listening-ip and relay-ip are replaced with sane values

if i try to test it with https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
the stun is working but the turn could not be reached.

Firewall has open 5349 for udp and tcp and the server is accessable via internet directly, no nat

what could i miss?

**Comment by yuanchieh-cheng** [comment]
Did you open the relay port
You could modify the port range, but remember open this port in your Firewall
```
# Lower and upper bounds of the UDP relay endpoints:
# (default values are 49152 and 65535)
#
min-port=49152
max-port=65535
```

**Comment by misi** [comment]
@fleixi  if you add verbose logging do you see the incoming requests?

**Comment by fleixi** [comment]
I dont know why but after the next system update (without any update on coturn) it is working again. Sorry for this useless issue report
