### ISSUE TITLE
where can i learn about coturn configuration?

### ISSUE THREAD

**Issue by bschelling** [coturn/coturn#732]
the wiki more or less says read the source, but this seems a little hard.
can anyone point me to some information/tutorials where i can read up on it?

**Comment by gabrielssanches** [comment]
if you mean the turnserver, just take a look at https://github.com/coturn/coturn/blob/master/README.turnserver

**Comment by bschelling** [comment]
thanks that's a start :) i'd be particulary interested in configuring short term credentials . all i found so far were some pdf slides that explain the theory but it would be great to have a more hands on tutorial...

**Comment by misi** [comment]
See: https://www.ietf.org/proceedings/87/slides/slides-87-behave-10.pdf

**Comment by misi** [comment]
It explains little bit turn auth methods..

**Comment by ggarber** [comment]
AFAICT almost everybody uses long-term STUN credentials with TURN servers.   If you want those credentials to expire you can use the static shared secret support in coturn.   That generates credentials that are valid only for a while (1 hour, 5 minutes... whatever) even if they are sent to coturn using the long-term credentials mechanism.

You can see how that is configured in the test script that runs to test coturn changes: https://github.com/coturn/coturn/blob/master/examples/run_tests.sh

@bschelling Please reopen if the information received in this comment and the previous ones is not enough.
