### ISSUE TITLE
what is the difference between UDP servers(udp listener/relay thread) and General servers(general relay thread) 

### ISSUE THREAD

**Issue by sfomp** [coturn/coturn#74]
hi,  what is the difference between them, i found they would invoke the method of open_client_connection_session.

**Comment by misi** [comment]
I am not sure, so let's wait for Oleg answer, but AFAIU:

- "general relay threads" are handling/relayin all incoming traffic that the "main listener thread" receives
- "udp  listener/relay thread" are separate threads per udp port and listening and also handling relaying

**Comment by mom040267** [comment]
On Tue, Oct 11, 2016 at 1:40 AM, misi <notifications@github.com> wrote:

> I am not sure, so let's wait for Oleg answer, but AFAIU:
>
>    - "general relay threads" are handling/relayin all incoming traffic
>    that the "main listener thread" receives
>
>
Yes, this is mostly about TCP/TLS traffic


>
>    - "udp listener/relay thread" are separate threads per udp port and
>    listening and also handling relaying
>
>
And yes, this is about UDP/DTLS

Regards,
Oleg
