### ISSUE TITLE
My coturn server can only work in a LAN，unable to visit through 4G network on my phone

### ISSUE THREAD

**Issue by tianqingqingyun** [coturn/coturn#742]
**When I use this link (https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) to test my coturn server(it's on my company's intranet) on my phone(using 4G Net)，the configurations are as below**

> **STUN or TURN URI** turn:103.19.65.188:19303
**TURN username** aaa
**TURN password** 123

**The coturn logged as below, and my phone finally logged _TURN allocate timed out._** 
> 1: handle_udp_packet: New UDP endpoint: local addr 192.168.1.212:19303, remote addr 124.64.17.46:10488
> 1: session 128000000000000001: realm <test> user <>: incoming packet BINDING processed, success
> 1: session 128000000000000001: realm <test> user <>: incoming packet message processed, error 401: Unauthorized
> 61: session 128000000000000001: closed (2nd stage), user <> realm <test> origin <>, local 192.168.1.212:19303, remote 124.64.17.46:10488, reason: allocation watchdog determined stale session state

**While if I visit http://103.19.65.188:19303, it replys with:**

> TURN Server
use https connection for the admin session

**The configurations of my coturn server are as below**

> external-ip=103.19.65.188
listening-ip=192.168.1.212
listening-port=19303
user=aaa:123
realm=test

**And I use this command to start my coturn server.**

> turnsever -a -v

**What I get puzzled is that if my phone get connected to the WLAN of my company, then I can receive all the ICE candidate I want(the coturn logged as below). I still need to tell that the coturn server does have an external IP, and the port 19303 is opened for both TCP and UDP.**

> 1: handle_udp_packet: New UDP endpoint: local addr 192.168.1.212:19303, remote addr 103.19.65.188:57518
1: session 128000000000000001: realm <test> user <>: incoming packet BINDING processed, success
1: session 128000000000000001: realm <test> user <>: incoming packet message processed, error 401: Unauthorized
1: session 128000000000000001: realm <test> user <>: incoming packet BINDING processed, success
1: session 128000000000000001: realm <test> user <>: incoming packet message processed, error 401: Unauthorized
1: IPv4. Local relay addr: 192.168.1.212:49342
1: session 128000000000000001: new, realm=<test>, username=<aaa>, lifetime=600
1: session 128000000000000001: realm <test> user <aaa>: incoming packet ALLOCATE processed, success
1: session 128000000000000001: refreshed, realm=<test>, username=<aaa>, lifetime=0
1: session 128000000000000001: realm <test> user <aaa>: incoming packet REFRESH processed, success
2: session 128000000000000001: closed (2nd stage), user <aaa> realm <test> origin <>, local 192.168.1.212:19303, remote 103.19.65.188:57518, reason: allocation timeout
2: session 128000000000000001: delete: realm=<test>, username=<aaa>

**Thanks for help.**

**Comment by misi** [comment]
Please make a tcpdump on both side (client and server or phone and coturn side on the same time) and compare and check any packet filtered on 4G network..
