### ISSUE TITLE
Feature request : HTTPS management interface on a different port from the main TURN/STUN listener.

### ISSUE THREAD

**Issue by yohan-b** [coturn/coturn#75]
Hi,
it would be great if we could have an option so the HTTPS management interface listens on a different port from the main TURN/STUN listener. Right now, we are going to have to disable the management interface completely (by removing the admin users) to satisfy our security policies.

Regards.

**Comment by misi** [comment]
Many thanks! 
I fully agree that this separation may could be beneficial.
Could you please donate the project and send a Pull Request?

**Comment by misi** [comment]
Would be enough to satisfy your  security policies to turn off completely https management?

**Comment by benturner** [comment]
I would certainly like to turn it off entirely, but that could be a different feature request too.

**Comment by yohan-b** [comment]
Hi,
unfortunately I don't have time to implement this right now. I'll see what I can do in the future.
In the meantime, I realized that not creating an admin user was not enough to completely disable HTTPS responses : for example, the version can still be seen in the header which our security guidelines forbid. I wrote a patch which gives the option to hide the version (completely I hope). Here is the pull request: https://github.com/coturn/coturn/pull/79

**Comment by mom040267** [comment]
Yohan, we will review your changes and include them if everything is fine
in the next build.

Thanks,
Oleg

**Comment by mom040267** [comment]
I see some problems in your pull request:

1) If I understand and remember the code correctly, the definition of the
new option PROD_OPT is incorrect. Its value is zero in the enum; this is
not what it has to be.
2) The expression sizeof(get_version(server))-1; is just wrong. It will
always return 7 on 64-bits platforms or 3 on 32-bits platforms. The
sizeof(...) expression is evaluated in compile time.

I'll fix that when I'll be merging.

Thanks
Oleg

**Comment by thib-ack** [comment]
Hello,
I think this issue can be closed as this has been implemented in #129 and is available since 4.5.1.0.

Thanks,

**Comment by misi** [comment]
I close it according to @thib-ack suggestion.
