### ISSUE TITLE
Possible to get the IP address of STUN user agents?

### ISSUE THREAD

**Issue by Chandramouli-P** [coturn/coturn#751]
Hello,

I can see the public IP address of some of the user agents only in the log files. May be, these IP addresses are belongs to the user agents who is using TURN. I am not seeing the IP address of the user agents who is using STUN.

Can anyone suggest how to see / store the IP addresses of all user agents? Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Good morning and any update would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Good morning and any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Good morning and any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by ggarber** [comment]
Why do you need this for the STUN messages?   STUN interfaces are usually public (no auth) and you can get tons of traffic / IPs?

Anyway if that info is not in the logs today and you need it feel free to submit a patch and I will revie wit.

**Comment by eakraly** [comment]
Closing this as a dup of #756
