### ISSUE TITLE
Request for Fail2Ban configuration for CoTurn

### ISSUE THREAD

**Issue by Chandramouli-P** [coturn/coturn#758]
Hello,

Can anyone send the working configuration file of Fail2Ban with CoTurn? Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Good morning and any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Good morning and any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Good morning and any help would be appreciated of Fail2Ban configuration for CoTurn. Thank you.

Best Regards,
Chandramouli.

**Comment by misi** [comment]
This tracker is about coturn issues and it seems no one pick up this topic, so please try on mailing list.
