### ISSUE TITLE
any way to calculate the relay data?

### ISSUE THREAD

**Issue by notedit** [coturn/coturn#76]

**Comment by misi** [comment]
Relay data is up to the client. Could you please clarify more your question?

**Comment by notedit** [comment]
i want to know how many data  data was relayed by  server,   so i can  calculate  throughput  of my each user  in server.

**Comment by notedit** [comment]
i have the  saw the struct  https://github.com/coturn/coturn/blob/master/src/server/ns_turn_session.h#L68

may be  i can  write some http api  get these data?

**Comment by misi** [comment]
Please implement it in [admin interface](https://github.com/coturn/coturn/blob/master/src/apps/relay/turn_admin_server.c), cli and https and send a Pull Request.
Thanks..

**Comment by notedit** [comment]
i am a little busy these days,  close for now.
