### ISSUE TITLE
Is this below log is ok?

### ISSUE THREAD

**Issue by Alex-YddeR** [coturn/coturn#764]
Is the below log is ok as i am testing with webrtc client. i want to know about the error  **incoming packet message processed, error 401: Unauthorized**

1318: : session 001000000000000001: realm <wsturn.alex.com> user <>: incoming packet BINDING processed, success
1318: : session 000000000000000007: realm <wsturn.alex.com> user <>: incoming packet BINDING processed, success
1318: : session 000000000000000007: realm <wsturn.alex.com> user <>: incoming packet message processed, error 401: Unauthorized
1318: : IPv4. tcp or tls connected to: 183.83.136.191:37728
1318: : session 000000000000000008: realm <wsturn.alex.com> user <>: incoming packet message processed, error 401: Unauthorized
1318: : IPv4. Local relay addr: 10.0.1.193:38522
1318: : session 000000000000000007: new, realm=<wsturn.alex.com>, username=<1620734400.042>, lifetime=600
1318: : session 000000000000000007: realm <wsturn.alex.com> user <1620734400.042>: incoming packet ALLOCATE processed, success
1318: : IPv4. Local relay addr: 10.0.1.193:57361
1318: : session 000000000000000008: new, realm=<wsturn.alex.com>, username=<1620734400.042>, lifetime=600
1318: : session 000000000000000008: realm <wsturn.alex.com> user <1620734400.042>: incoming packet ALLOCATE processed, success
1318: : session 000000000000000007: peer 10.0.1.131 lifetime updated: 300
1318: : session 000000000000000007: realm <wsturn.alex.com> user <1620734400.042>: incoming packet CREATE_PERMISSION processed, success
1318: : session 000000000000000008: peer 10.0.1.131 lifetime updated: 300
1318: : session 000000000000000008: realm <wsturn.alex.com> user <1620734400.042>: incoming packet CREATE_PERMISSION processed, success
1318: : session 000000000000000008: peer 13.234.135.194 lifetime updated: 300
1318: : session 000000000000000008: realm <wsturn.alex.com> user <1620734400.042>: incoming packet CREATE_PERMISSION processed, success
1318: : session 000000000000000007: peer 13.234.135.194 lifetime updated: 300
1318: : session 000000000000000007: realm <wsturn.alex.com> user <1620734400.042>: incoming packet CREATE_PERMISSION processed, success
1318: : session 000000000000000007: peer 10.0.1.131 lifetime updated: 600
1318: : session 000000000000000007: realm <wsturn.alex.com> user <1620734400.042>: incoming packet CHANNEL_BIND processed, success
1324: : session 000000000000000007: usage: realm=<wsturn.alex.com>, username=<1620734400.042>, rp=1012, rb=619026, sp=1042, sb=680052
1324: : session 000000000000000007: peer usage: realm=<wsturn.alex.com>, username=<1620734400.042>, rp=1037, rb=675099, sp=1005, sb=614174

Thanks

**Comment by misi** [comment]
Yes it is.
