### ISSUE TITLE
Mobility with TURN is still a draft

### ISSUE THREAD

**Issue by yfaker** [coturn/coturn#769]
Hi, I'm curious why <Mobility with TURN  draft-wing-tram-turn-mobility-02> is still a draft, not becoming  a RFC standard, since it's may be a good mechanism to improving experience in changing IP address during a mobility event, is there any security considerations or what? 
Thanks~

**Comment by misi** [comment]
You should ask from IETF tram list. 
I see this is seem to be an RFC https://datatracker.ietf.org/doc/html/rfc8016

**Comment by yfaker** [comment]
ok, thanks~
