### ISSUE TITLE
ICE server Coturn

### ISSUE THREAD

**Issue by GiacomoSilli** [coturn/coturn#77]
Hello,
I'm using coturn as TURN server.
unfortunately I can not understand it completely

the TURN server is operating properly.
I can use the same IP/PORT as STUN server?

How to configure a server using ICE Coturn?

**Comment by misi** [comment]
TURN is an extension to the STUN (Session Traversal Utilities for NAT) protocol [RFC5389].

If you want help on yourself then please read these:
https://tools.ietf.org/search/rfc5389
https://tools.ietf.org/search/rfc5766
https://tools.ietf.org/search/rfc5245
