### ISSUE TITLE
Time Limited Credentials & turn secret problem?

### ISSUE THREAD

**Issue by modestas0326** [coturn/coturn#774]
I have a working Coturn setup with time limited credentials & dynamic turn secret generation.

### Problem
There are two problems:
    1. I generate time limited credentials with 1 minute duration, then successfully connect two people to each other, the duration time expires and the connection is still active(video is still broadcasting).
    2. I generate time limited credentials with a secret from turn_secret table, then connect two people to each other and with 3rd party program delete the secret from turn_secret table(sqlite), my connection is still active and working(video broadcasting).

### Question
I can't find a proper explanation or documentation, that explains if this logic is intentonial. If the case appear to be intentonial, maybe someone can give some ideas how to solve it? Btw, if you close the connection and try to use them again, they don't work like it should be.

**Comment by misi** [comment]
The expired turn credential will only checked on session creation it will not tear down the session. You can do it on your application level. So application knows the turn credential so the expiry timestamp and it should handle turn expiry.

**Comment by eakraly** [comment]
Good discussion @modestas0326. Chiming in very late and want to provide some additional perspective:
- As pointed out: credentials are validated when used for the first time. This protects well agains credentials abuse. Short time is relative (1 minute is too short for my taste but it very much depends on app).
- If we enforce TURN session to be closed on short term credentials expiration - we are in a world of pain. As @weiss stated it requires the client to refresh connection with new credentials. I have not found anything in RFCs to address this scenario which means there is no standard solution to this - so we stick to what we have. 
- From architectural perspective it would be weird to have TURN as some kind of access control device - RFC states that it is up to the application to decide on what to do with timeouts.
- I see credentials as "access" credentials - they allow you in: like if you have a key to a house you can enter the house. While inside the house, even if the locks change, you still stay inside the house. BUT you cannot leave and re-enter with the old key....

Closing this issue. Pls comment if there is more to discuss. TY!
