### ISSUE TITLE
Is ubuntu coturn package a production ready pacakge?

### ISSUE THREAD

**Issue by Sudheerkumar** [coturn/coturn#775]
Hi,

Is the coturn pacakge available in ubuntu repo `sudo apt-get install coturn` is a production grade package?
Can we use the package for the production systems?

**Comment by misi** [comment]
I package releases (with the highly appreciated help of a debian developer) only for Debian. As far as I know Ubuntu is lacking behind few versions sometimes.. (You need to compare the package and versions in the Linux distributions.)
If possible I propose to use Debian or Docker image, or ask ubuntu package maintainers about the package status..

**Comment by Nicholi** [comment]
I can concur the Ubuntu packages are typically quite behind. Best to compile from source, or yeah go Docker route.
