### ISSUE TITLE
Building fails on arm32 (Raspberry Pi 4) 

### ISSUE THREAD

**Issue by whowantsmybigdata** [coturn/coturn#777]
Hi,
I use the [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) to set up Matrix with coturn in my Raspberry Pi 4 (arm32). It worked for over a year now but since about a month coturn fails to build with 

<details><summary>this error:</summary>
<code>msg: 'Error building localhost/coturn/coturn - code: 2, message: The command ''/bin/sh -c apk update  && apk add --no-cache         autoconf ca-certificates coreutils g++ git libtool make  && update-ca-certificates'' returned a non-zero code: 2, logs: [u''Step 1/29 : ARG alpine_ver=3.13'', u''\n'', u''Step 2/29 : FROM alpine:${alpine_ver} AS dist-coturn'', u''\n'', u'' ---> b6342193e7c0\n'', u''Step 3/29 : RUN apk update  && apk add --no-cache         autoconf ca-certificates coreutils g++ git libtool make  && update-ca-certificates'', u''\n'', u'' ---> Running in 9716ec9fee9c\n'', u''fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz\n'', u''\x1b[91mERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)\nWARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory\n\x1b[0m'', u''fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz\n'', u''\x1b[91mERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community:
    temporary error (try again later)\nWARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory\n\x1b[0m'', u''2 errors; 14 distinct packages available\n'', u''Removing intermediate container 9716ec9fee9c\n'']'</code>
</details>

Pinging the error-link https://dl-cdn.alpinelinux.org/alpine/v3.13/community didnt work but I did a `wget` (from the same machine where the playbook is running) and it works...
I also tried to setup without coturn and everything else works as normal.

As it also stopped working when pulling the ansible-playbook I use from one of my backups to have its state before it broke, it still fails, so I got recommended I should report this upstream...

thanks in advance!

**Comment by misi** [comment]
For me it seems not a coturn issue.. 
Maybe connected to docker and firewall. 
Try to clear firewall rules so stop temporary firewall and restart docker and try again.

**Comment by whowantsmybigdata** [comment]
@misi thanks for taking the time!
for me it still seems like it as of this points:
- stopped firewall, stopped all other services running on the machine, rebooted, updated and so on
- completely pruned (docker system prune -fa) docker and restarted it
- tried to build it from a backup I had from beginning of May where coturn still worked (I don't know how to put the working coturn-docker-stuff from my backup to my machine without loosing data gathered in the meantime)

All leads to the very same error...

**Comment by misi** [comment]
I can't help you more on this unfortunately..
