### ISSUE TITLE
How to limit max TURN bandwidth (for all connections) 

### ISSUE THREAD

**Issue by stogupd** [coturn/coturn#78]
I have 100 mbit/sec server bandwidth

I want to limit max total bandwidth of TURN to 50 mbit/sec max

If i understood it right in coturn config options such as:

--bps-capacity
--max-bps

Accept values in mbyte/sec (mbit/sec / 8)

So it should be:

1024 \* 1024 \* 50 / 8 = 6553600

So i set in turnserver.conf

bps-capacity=6553600

When i try to start the server it fails with error:

CONFIG ERROR: If you set the --bps-capacity option, then you must set --max-bps options, too.

Although for now i don't need per session limit, let set it if required.

Let it be equal to all allowed bandwidth (one connection allowed to utilize all the channel)

bps-capacity=6553600
max-bps=6553600

With this settings the server reject even one connection.

What i am doing wrong?

My target for now is just limit total bandwidth (with no limit of single connection).

**Comment by mom040267** [comment]
We will check that, thanks for report

**Comment by FJEagle** [comment]
As stated in config comments, input and output are treated separatedly, so should it be (50 input + 50 output)*1000*1000/8 ?

**Comment by ggarber** [comment]
Closing this old ticket.  @stogupd reopen if the answers from FJEagle and mom040267 were not clear or you still have any issue
