### ISSUE TITLE
DoS risk

### ISSUE THREAD

**Issue by yfaker** [coturn/coturn#780]
coturn will create session for every incoming udp packet，and set a timeout for it(60s for turn and 3s for stun)，so I'm a little concerned whether there is any DoS risk, someone can send thousands of udp packet to run out of the server's memory?
thanks

**Comment by misi** [comment]
Yes production servers need to apply some firewall reasonable rate limitation on incoming STUN packets from the same IP and subnet. 
e.g. iptables hashlimit

**Comment by yfaker** [comment]
thank for your reply~
