### ISSUE TITLE
memory consumption keep increasing in long run test

### ISSUE THREAD

**Issue by yfaker** [coturn/coturn#782]
cpu info:  Intel(R) Xeon(R) Gold 6278C
system：Linux version 3.10.0-327.62.59.83.h230.x86_64
coturn version: coturn 4.5.2

turnserver.conf:
tls-listening-port=5349
alt-tls-listening-port=5350
listening-ip=xx.xx.xx.67
external-ip=xx.xx.xx.111/xx.xx.xx.67
verbose
realm=hello.com
no-tcp
no-tls
no-tcp-relay
cert=/opt/coturn/coturn/etc/turn_server_cert.pem
pkey=/opt/coturn/coturn/etc/turn_server_pkey.pem
cipher-list="ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:HIGH:!MEDIUM:!LOW:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4"
no-stdout-log
log-file=/opt/logs/coturn/turn.log
simple-log
log-binding
no-software-attribute
no-cli
no-tlsv1
no-tlsv1_1
#no-tlsv1_2

I run performance for test, send Binding request with multi client concurrently, rps is about 580Hits/s
the memory usage keep increasing slowly, and never decrease when the test stopped
![image](https://user-images.githubusercontent.com/23066914/123057108-2b9f8b80-d43a-11eb-836b-d1b709baf8b5.png)

and run with valgrind, got some info below , don't know if helps
![image](https://user-images.githubusercontent.com/23066914/123057542-8cc75f00-d43a-11eb-9ab3-d2f2228afc01.png)
![image](https://user-images.githubusercontent.com/23066914/123057629-9ea90200-d43a-11eb-9ca1-82afbfa3eed5.png)
![image](https://user-images.githubusercontent.com/23066914/123057848-cc8e4680-d43a-11eb-9bb7-1ee33bd8943d.png)

Thanks

**Comment by yfaker** [comment]
![image](https://user-images.githubusercontent.com/23066914/123058299-41618080-d43b-11eb-9afb-13777a506f1e.png)

**Comment by misi** [comment]
Many thanks for the detailed info!! Appreciated..

**Comment by yfaker** [comment]
ps: DTLS is inuse

**Comment by groupboard** [comment]
Was this issue fixed?
