### ISSUE TITLE
Unable to see packets on Prometheus Port No. 9641

### ISSUE THREAD

**Issue by Chandramouli-P** [coturn/coturn#785]
Hello,

I installed CoTurn along with Prometheus. Also, enabled "Prometheus" in configuration file and CoTurn is running successfully along with "Prometheus". Below is the listening ports in our CoTurn server:

$ netstat -tulpn
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      **0 0.0.0.0:9641            0.0.0.0:*               LISTEN      -**                   
tcp        0      0 1.2.3.4:80        0.0.0.0:*               LISTEN      -                   
tcp        0      0 1.2.3.4:80        0.0.0.0:*               LISTEN      - 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -  
tcp        0      0 1.2.3.4:443       0.0.0.0:*               LISTEN      -                   
tcp        0      0 1.2.3.4:443       0.0.0.0:*               LISTEN      -
tcp6       0      0 :::9100                 :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
udp        0      0 127.0.0.53:53           0.0.0.0:*                           -                   
udp        0      0 1.2.3.4:68        0.0.0.0:*                           -                   
udp        0      0 1.2.3.4:80        0.0.0.0:*                           -                   
udp        0      0 1.2.3.4:80        0.0.0.0:*                           -                   
udp        0      0 1.2.3.4:443       0.0.0.0:*                           -                   
udp        0      0 1.2.3.4:443       0.0.0.0:*                           - 

When I am trying to establish a P2P call, call is establishing successfully. But, Unable to see any packets in 9641 port.

ubuntu@ip-172-31-21-246:~$ **sudo tcpdump -n port 9641**
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens5, link-type EN10MB (Ethernet), capture size 262144 bytes

^C
0 packets captured
0 packets received by filter
0 packets dropped by kernel

Hence, request you to help me in resolving the issue. Thank you in advance.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Good evening and any update would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by ggarber** [comment]
The prometheus endpoint is for you to request metrics, it is expected to not capture any packet unless you have some application requesting those metrics.

Prometheus IS NOT used to establish a P2P call so it is normal to not get any traffic in the prometheus port during the call.

You can just open http://localhost:9641/metrics in a browser to get the prometheus metrics.

**Comment by docjojo** [comment]
I have 

```
realm=***
server-name=***
listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
external-ip=***
lt-cred-mech
user=***:***
cert=/home/coturn/certs/fullchain1.pem
pkey=/home/coturn/certs/privkey1.pem
min-port=32769
max-port=65535
log-file=/var/log/turnserver/turnserver.log
cli-password=***
prometheus
```
and coturn is running, but it is not exposing data on port 9641

curl 127.0.0.1:9641/metrics
curl: (7) Failed to connect to 127.0.0.1 port 9641 after 0 ms: Connection refused

What can I do?

coturn was installed using "apt install coturn"

Do I have to compile coturn to enable prometheus?

C.
