### ISSUE TITLE
user quota release 

### ISSUE THREAD

**Issue by yfaker** [coturn/coturn#786]
when user quota check is enabled, user's quota info is recorded in map(rp->status.alloc_counters) according to check_new_allocation_quota function, and seems to be never deleted from the map.
as the map stucture is LIST, the map will become longer and longer when new incoming users continues, and the user quota check processing will takes more time

**Comment by yfaker** [comment]
in release_allocation_quota function, when user's quota count becomes 0, should we delete the record like this? or maybe I have some misunderstanding?
'
if (value) {
    value = (ur_string_map_value_type)(((size_t)value) - 1);
    if (value == 0) {
          ur_string_map_del(rp->status.alloc_counters, (ur_string_map_key_type) username);
      } else {
          ur_string_map_put(rp->status.alloc_counters, (ur_string_map_key_type) username, value);
      }
}
'

**Comment by eakraly** [comment]
Fixed in #792
