### ISSUE TITLE
403 IP Forbidden - Peer address is zero

### ISSUE THREAD

**Issue by tilmanrpk** [coturn/coturn#788]
Here is a very strange issue with coturn. When using turnutils_uclient with coturn, the ip validity is checked after channel_bind is sent in the method "good_peer_addr" (ns_turn_server.c) and fails because peer_addr is zero. This happens through turnutils_uclient in the same network and also with a webrtc client. What is going on here?

Client command:
`turnutils_uclient -u username -w password -p 3478 -v 192.168.2.222`

Config:
>realm=domain
>server-name=turnserver
>listening-ip=0.0.0.0
>listening-port=3478
>fingerprint
>verbose
>user=username:password
>lt-cred-mech

**Comment by longvhv** [comment]
I have the same problem.
My conf file:
[turnserver.conf.txt](https://github.com/coturn/coturn/files/6783719/turnserver.conf.txt)

I run that command on client:
turnutils_uclient -p 3478 183.81.35.xxx -u colombo -w xxxxxx -v

Response:
0: IPv4. Connected from: 192.168.1.130:59080
0: IPv4. Connected to: 183.81.35.98:3478
0: allocate sent
0: allocate response received:
0: allocate sent
0: allocate response received:
0: success
0: IPv4. Received relay addr: 183.81.35.98:49436
0: clnet_allocate: rtv=14025891960573782183
0: refresh sent
0: refresh response received:
0: success
0: IPv4. Connected from: 192.168.1.130:43015
0: IPv4. Connected to: 183.81.35.98:3478
0: IPv4. Connected from: 192.168.1.130:50502
0: IPv4. Connected to: 183.81.35.98:3478
0: allocate sent
0: allocate response received:
0: allocate sent
0: allocate response received:
0: success
0: IPv4. Received relay addr: 183.81.35.98:49437
0: clnet_allocate: rtv=0
0: refresh sent
0: refresh response received:
0: success
0: allocate sent
0: allocate response received:
0: allocate sent
0: allocate response received:
0: success
0: IPv4. Received relay addr: 183.81.35.98:58526
0: clnet_allocate: rtv=12201400917068806101
0: refresh sent
0: refresh response received:
0: success
0: channel bind sent
0: cb response received:
0: channel bind: error 403 (Forbidden IP)
[colombo@sonar root]$ turnutils_uclient -p 3478 183.81.35.98 -u colombo -w Vhv12345 -v
0: IPv4. Connected from: 192.168.1.130:63410
0: IPv4. Connected to: 183.81.35.98:3478
0: allocate sent
0: allocate response received:
0: allocate sent
0: allocate response received:
0: success
0: IPv4. Received relay addr: 183.81.35.98:57612
0: clnet_allocate: rtv=4517827810345411725
0: refresh sent
0: refresh response received:
0: success
0: IPv4. Connected from: 192.168.1.130:41216
0: IPv4. Connected to: 183.81.35.98:3478
0: IPv4. Connected from: 192.168.1.130:22463
0: IPv4. Connected to: 183.81.35.98:3478
0: allocate sent
0: allocate response received:
0: allocate sent
0: allocate response received:
0: success
0: IPv4. Received relay addr: 183.81.35.98:57613
0: clnet_allocate: rtv=0
0: refresh sent
0: refresh response received:
0: success
0: allocate sent
0: allocate response received:
0: allocate sent
0: allocate response received:
0: success
0: IPv4. Received relay addr: 183.81.35.98:64032
0: clnet_allocate: rtv=11623327447495724730
0: refresh sent
0: refresh response received:
0: success
0: channel bind sent
0: cb response received:
0: channel bind: error 403 (Forbidden IP)


Server log:
235: : IPv4. Local relay addr: 183.81.35.98:57612
235: : IPv4. Local reserved relay addr: 183.81.35.98:57613
235: : session 003000000000000001: new, realm=<turn.vhv.vn>, username=<colombo>, lifetime=777
235: : session 003000000000000001: realm <turn.vhv.vn> user <colombo>: incoming packet ALLOCATE processed, success
235: : session 003000000000000001: refreshed, realm=<turn.vhv.vn>, username=<colombo>, lifetime=777
235: : session 003000000000000001: realm <turn.vhv.vn> user <colombo>: incoming packet REFRESH processed, success
235: : session 003000000000000002: realm <turn.vhv.vn> user <>: incoming packet message processed, error 401: Unauthorized
235: : IPv4. Local relay addr (RTCP): 183.81.35.98:57613
235: : session 003000000000000002: new, realm=<turn.vhv.vn>, username=<colombo>, lifetime=777
235: : session 003000000000000002: realm <turn.vhv.vn> user <colombo>: incoming packet ALLOCATE processed, success
235: : session 003000000000000002: refreshed, realm=<turn.vhv.vn>, username=<colombo>, lifetime=777
235: : session 003000000000000002: realm <turn.vhv.vn> user <colombo>: incoming packet REFRESH processed, success
235: : session 004000000000000001: realm <turn.vhv.vn> user <>: incoming packet message processed, error 401: Unauthorized
235: : IPv4. Local relay addr: 183.81.35.98:64032
235: : IPv4. Local reserved relay addr: 183.81.35.98:64033
235: : session 004000000000000001: new, realm=<turn.vhv.vn>, username=<colombo>, lifetime=777
235: : session 004000000000000001: realm <turn.vhv.vn> user <colombo>: incoming packet ALLOCATE processed, success
235: : session 004000000000000001: refreshed, realm=<turn.vhv.vn>, username=<colombo>, lifetime=777
235: : session 004000000000000001: realm <turn.vhv.vn> user <colombo>: incoming packet REFRESH processed, success
235: : session 003000000000000002: realm <turn.vhv.vn> user <colombo>: incoming packet CHANNEL_BIND processed, error 403: Forbidden IP
235: : session 003000000000000002: realm <turn.vhv.vn> user <colombo>: incoming packet message processed, error 403: Forbidden IP

I have spent a day search many times on Google, but can not fix that problem.
Please help me!
Thanks & Best regards!
Long.

**Comment by NeoCat** [comment]
I think uclient should show an error message when users forget to specify either -y or -e option. I have pull-requested: #934
