### ISSUE TITLE
coturn crashing with segfault

### ISSUE THREAD

**Issue by peterzanetti** [coturn/coturn#790]
Here is the exact line from syslog

`Jul  7 08:33:28 coturn02 kernel: [1596505.809235] turnserver[32028]: segfault at 7f4e5c0008d0 ip 00007f4e5c0008d0 sp 00007f4e63a7b8d8 error 15
Jul  7 08:33:28 coturn02 kernel: [1596505.809240] Code: 00 00 00 40 0c 00 00 00 00 00 00 40 0c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 55 02 00 00 00 00 00 00 <04> 04 07 07 07 06 03 04 07 06 07 03 00 07 07 06 07 02 01 01 05 07`

I have another coturn server that is on an older version and doesn't have this issue. I just created a new Ubuntu 18 server with a fresh install of latest coturn and at least once per day it is crashing with this error. What is going on here?

**Comment by misi** [comment]
Do you have a core file? It would nice to have a backtrace about the issue.

**Comment by peterzanetti** [comment]
From reading other issues on segfaults in coturn it seemed like people were updating to Ubuntu 20 to avoid them. I've done that and reinstalled coturn, so I'll update here if it happens again. Where would I find the "core file"?

**Comment by misi** [comment]
It depends on your system settings 
e.g.
https://www.freedesktop.org/software/systemd/man/systemd-coredump.html
But I couldn't help more howto capture it..

**Comment by eakraly** [comment]
Hi @peterzanetti ! Were you able to address the issue?
Can you please share some info?

**Comment by eakraly** [comment]
Multiple memory issues were addressed in 4.6.0 - potentially could fix the crash
Since there is no respond from OP - closing
