### ISSUE TITLE
coturn build failed---src/apps/relay/netengine.c: In function 'replace_one_ssl_ctx':

### ISSUE THREAD

**Issue by gaoxiong523** [coturn/coturn#795]
mkdir -p bin
rm -rf bin/turnadmin
cc  -g  -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Wcast-qual  -DLIBEV_OK -DTURN_HAS_DAEMON     -pthread   -DTURN_NO_PROMETHEUS       -DINSTALL_PREFIX=/usr -DTURNDB=/var/db/turndb -Isrc -Isrc/apps/common -Isrc/server -Isrc/client -Isrc/client++ -I/usr/include/ -I/usr/local/include/  -I/usr/include/mysql -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis   -DTURN_NO_PQ   -DTURN_NO_MONGO  -DTURN_NO_SYSTEMD src/apps/relay/ns_ioalib_engine_impl.c src/apps/relay/turn_ports.c src/apps/relay/http_server.c src/apps/relay/acme.c -Ilib src/apps/relay/mainrelay.c src/apps/relay/netengine.c src/apps/relay/libtelnet.c src/apps/relay/turn_admin_server.c src/apps/relay/userdb.c src/apps/relay/tls_listener.c src/apps/relay/dtls_listener.c src/apps/relay/prom_server.c src/apps/common/hiredis_libevent2.c src/apps/relay/dbdrivers/dbdriver.c src/apps/relay/dbdrivers/dbd_sqlite.c src/apps/relay/dbdrivers/dbd_pgsql.c src/apps/relay/dbdrivers/dbd_mysql.c src/apps/relay/dbdrivers/dbd_mongo.c src/apps/relay/dbdrivers/dbd_redis.c src/apps/common/apputils.c src/apps/common/ns_turn_utils.c src/apps/common/stun_buffer.c src/client/ns_turn_ioaddr.c src/client/ns_turn_msg_addr.c src/client/ns_turn_msg.c  src/server/ns_turn_allocation.c src/server/ns_turn_maps_rtcp.c src/server/ns_turn_maps.c src/server/ns_turn_server.c -o bin/turnserver -lsqlite3   -L/usr/lib64/mysql -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto -lhiredis   -lrt -lnsl -lresolv -pthread -lcrypto   -lssl -lcrypto   -levent_openssl -levent_pthreads -levent    -Wl,-rpath,/usr/local/lib 
src/apps/relay/netengine.c: In function 'replace_one_ssl_ctx':
src/apps/relay/netengine.c:312:2: warning: implicit declaration of function 'SSL_CTX_up_ref' [-Wimplicit-function-declaration]
  SSL_CTX_up_ref(from);
  ^
src/apps/relay/netengine.c:312:2: warning: nested extern declaration of 'SSL_CTX_up_ref' [-Wnested-externs]
/tmp/ccBYWANI.o: In function `replace_one_ssl_ctx':
/root/rpmbuild/BUILD/turnserver-4.5.2/src/apps/relay/netengine.c:312: undefined reference to `SSL_CTX_up_ref'
collect2: error: ld returned 1 exit status
make: *** [bin/turnserver] Error 1
错误：/var/tmp/rpm-tmp.IMD54f (%build) 退出状态不好

RPM 构建错误：
    /var/tmp/rpm-tmp.IMD54f (%build) 退出状态不好

**Comment by lichtz** [comment]
Did you ask? I've had the same problem

**Comment by gaoxiong523** [comment]
> Did you ask? I've had the same problem

no , i havnt resole it

**Comment by lichtz** [comment]
wget https://github.com/coturn/coturn/archive/4.5.1.1.tar.gz

**Comment by eakraly** [comment]
Hi @gaoxiong523 ! Were you able to address the issue?
As of today `SSL_CTX_up_ref` is still in coturn code and  is still in openssl.

What looks suspicious to me is that your command  does not have a path to OpenSSL includes - which means it picks up some files but necessarily the version you want

Can you provide more information on your setup? What OS and openssl version?

**Comment by steffen-moser** [comment]
Which OpenSSL version do you use? Which operating system is used to build coturn?

I am running into the same problem when trying to build the current HEAD revision of coturn on Solaris 11.4 SRU 48. By default, Solaris comes with "openssl-1.0.2ze" which does not seem to support "SSL_CTX_up_ref()".

Solaris 11.4 also comes with "openssl-1.1.1o", which can be set as default by issuing a "pkg set-mediator -I default@1.1 openssl" as [mentioned here](https://blogs.oracle.com/solaris/post/managing-multiple-openssl-versions-and-modes-on-a-single-system). When doing so, coturn compiles fine and uses OpenSSL 1.1.1. 

The problem is, it still segfaults after a while due to a lib mismatch. "/usr/lib/64/libevent_openssl-2.1.so.7" is used by coturn and links to the old "/lib/64/libssl.so.1.0.0" and "/lib/64/libcrypto.so.1.0.0". This means, I am sure that I'll also have to recompile libevent_openssl.

**Comment by eakraly** [comment]
I think you are right @steffen-moser - libevent is dependent on openssl and if you are using libevent provided by Solaris then it makes sense it would be dependent on openssl-1.0.2ze

All OpenSSL versions below 1.1.1 are deprecated and supporting them becomes harder and harder, unfortunately.
This can be fixed though... Something along the lines of https://github.com/eclipse/mosquitto/issues/715#issuecomment-380635785

Can you please try this approach and test it? Maybe submit a PR?

**Comment by steffen-moser** [comment]
Thank you very much for the hint, @eakraly - it works. After having coturn (HEAD) running for about 24 hours on Solaris 11.4 SRU 48, I am quite sure that this could be the way to go. I am going to prepare a PR.

**Comment by steffen-moser** [comment]
Fixed for Solaris with PR #951.
