### ISSUE TITLE
Log in with the key instead of the password still not working

### ISSUE THREAD

**Issue by spine001** [coturn/coturn#797]
This issue was closed long time ago with no explanation, and it is still happening. The problem is this:
We create a key with 
turnadmin -k -u testinguser -r turnserver.example.com -p I_love_my-beautiful-cat
and get the key, 

Then enter the key into turnserver.conf under user:key as
testinguser:0x............

And then we test this credential with trickle and it responds error with code:401 Unauthorized

The username/ password combination used to generate the key above work when tested with
turnutils_uclient -y -v -u testinguser -w I_love_my-beautiful-cat

works perfect, but I don't see an option to test the key generated with turnadmin.

We should either fix this or remove the key option all together.

Closing the issue will not make it go away. If I'm wrong and a dummy, once educated by my betters, may be able to improve the documentation so that other people don't make the same mistake.

**Comment by eakraly** [comment]
Hi @spine001 ! Thank you for the issue
Did you figure out the issue? Can you submit a PR to update the documentation?

**Comment by spine001** [comment]
Sorry, gave up and found another solution. The breaking problem is that I couldn't figure out how to make it work with cells phone browsers (blocked ports) while simultaneously running apache using only one public IP.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
