### ISSUE TITLE
MongoDB replica set not connecting

### ISSUE THREAD

**Issue by sumeetkpatel** [coturn/coturn#80]
I am using MongoDB for authorization but it only works if I set my connection string to a single IP like so
```
mongo-userdb="mongodb://10.0.0.2:27017/turn"
```
OR
```
mongo-userdb="mongodb://10.0.0.3:27017/turn"
```
If I try something like the proper:
```
mongo-userdb="mongodb://10.0.0.2:27017,10.0.0.3:27017/turn?replicaSet=replica1"
```
Including simpler or more complicated variations... nothing works.
It would also be super if we could get a useful error message in the log about it instead of a silent failure to connect.

This is important since the primary and secondary may switch roles and we want to remain reliable.
If it had connected, I wonder if it would fail over automatically as well.

**Comment by mom040267** [comment]
I cannot reproduce the problem. It works as expected. 

When I am trying to connect like to a cluster it works:

   Opened MongoDB URI <mongodb://localhost,localhost/coturn>
0: Reconnecting to sharded cluster.
0: IO method (admin thread): kqueue
0: IPv4. CLI listener opened on : 127.0.0.1:5766
0: Reconnecting to sharded cluster.
0: Reconnecting to sharded cluster.

When I try to use an invalid connection string, I see the error message:
0: Opened MongoDB URI <mongodb://localhost,localhost/coturn?replicaSet=replica1>
0: Reconnecting to replica set.
0: IO method (admin thread): kqueue
0: IPv4. CLI listener opened on : 127.0.0.1:5766
0: localhost:27017: Got replicaSet "(null)" expected "replica1".
0: Reconnecting to replica set.
0: localhost:27017: Got replicaSet "(null)" expected "replica1".
0: Reconnecting to replica set.

The errors are available in the log or in the standard output.
