### ISSUE TITLE
Error in Document https://github.com/coturn/coturn/blob/master/examples/scripts/restapi/secure_relay_secret_with_db_mysql.sh

### ISSUE THREAD

**Issue by spine001** [coturn/coturn#800]
the document lines 2-3  asks the reader to read a file but provides no reference to it. After a through search with grep and zgrep after a new installation the file is  nowhere in the system. 

An Internet search for the file only yields 18 reautls and none to the actual file but to document references of it.

This occurs in all the examples in 

/usr/share/doc/coturn/examples/scripts/restapi/secure_relay_secret_with_db_mongo.sh:# secure 'dynamic' 'secret' mode (see TURNServerRESTAPI.pdf)
/usr/share/doc/coturn/examples/scripts/restapi/secure_udp_client_with_secret.sh:# secret-based authorization (see TURNServerRESTAPI.pdf document).
/usr/share/doc/coturn/examples/scripts/restapi/secure_relay_secret_with_db_redis.sh:# secure 'dynamic' 'secret' mode (see TURNServerRESTAPI.pdf)
/usr/share/doc/coturn/examples/scripts/restapi/secure_relay_secret.sh:# secure 'static' 'secret' mode (see TURNServerRESTAPI.pdf)
/usr/share/doc/coturn/examples/scripts/restapi/secure_relay_secret_with_db_mysql.sh:# secure 'dynamic' 'secret' mode (see TURNServerRESTAPI.pdf)
/usr/share/doc/coturn/examples/scripts/restapi/secure_relay_secret_with_db_sqlite.sh:# secure 'dynamic' 'secret' mode (see TURNServerRESTAPI.pdf)
/usr/share/doc/coturn/examples/scripts/restapi/secure_relay_secret_with_db_psql.sh:# secure 'dynamic' 'secret' mode (see TURNServerRESTAPI.pdf)

File needs to be linked or removed and assumption that the user will get more information from it removed by making the documentation complete on itself.

**Comment by eakraly** [comment]
Note:
Should point to https://github.com/coturn/coturn/blob/master/README.turnserver#L673 instead
Replace all references to TURNServerRESTAPI.pdf throughout the repo
