### ISSUE TITLE
Random service restart in AWS ARM instances

### ISSUE THREAD

**Issue by facundojsanchez** [coturn/coturn#808]
Hi,

I tested two AWS EC2 families: T3a and T4g.

Test was done using Ubuntu Server 20.04 LTS

Some specs of two EC2 instances:

**T3a** are powered by AMD EPYC 7000
**T4g** are powered by Arm-based AWS Graviton2

With the same configuration COTURN works fine on **T3a** but in **T4g (ARM CPU)** randomly service is restarted and produces service downs.

I can't get any log info because the service restarts with any additional info

**Comment by eakraly** [comment]
Hi @facundojsanchez - this is a very interesting and important issue
Were you able to find anything?

**Comment by eakraly** [comment]
Stale issue - closing.
For documentation purpose: latest 4.6.0 version has a few crash fixes - may have been one of them.
