### ISSUE TITLE
Reason: TLS/TCP socket buffer operation error (callback)

### ISSUE THREAD

**Issue by andyxheli** [coturn/coturn#809]
322: handle_udp_packet: New UDP endpoint: local addr 66.158.36.55:443, remote addr 188.172.110.153:37915
322: session 002000000000000024: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
322: handle_udp_packet: New UDP endpoint: local addr 66.158.36.55:443, remote addr 188.172.110.153:39927
322: session 002000000000000025: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
322: handle_udp_packet: New UDP endpoint: local addr 66.158.36.55:443, remote addr 188.172.110.153:38019
322: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
322: IPv4. tcp or tls connected to: 188.172.110.153:44450
322: IPv4. tcp or tls connected to: 188.172.110.153:45354
322: IPv4. tcp or tls connected to: 188.172.110.153:51851
323: session 002000000000000024: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
323: session 002000000000000025: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
323: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
323: session 003000000000000018: TLS/TCP socket disconnected: 188.172.110.153:44450
323: session 003000000000000018: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
323: session 002000000000000027: TLS/TCP socket disconnected: 188.172.110.153:45354
323: session 002000000000000027: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
323: session 003000000000000018: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:44450, reason: TLS/TCP socket buffer operation error (callback)
323: session 002000000000000027: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:45354, reason: TLS/TCP socket buffer operation error (callback)
323: session 003000000000000019: TLS/TCP socket disconnected: 188.172.110.153:51851
323: session 003000000000000019: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
323: session 003000000000000019: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:51851, reason: TLS/TCP socket buffer operation error (callback)
323: IPv4. tcp or tls connected to: 188.172.110.153:34398
323: IPv4. tcp or tls connected to: 188.172.110.153:53906
323: IPv4. tcp or tls connected to: 188.172.110.153:56365
324: session 003000000000000020: TLS/TCP socket disconnected: 188.172.110.153:56365
324: session 003000000000000020: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
324: session 003000000000000020: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:56365, reason: TLS/TCP socket buffer operation error (callback)
324: session 001000000000000015: TLS/TCP socket disconnected: 188.172.110.153:53906
324: session 001000000000000015: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
324: session 001000000000000015: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:53906, reason: TLS/TCP socket buffer operation error (callback)
325: session 000000000000000022: TLS/TCP socket disconnected: 188.172.110.153:34398
325: session 000000000000000022: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
325: session 000000000000000022: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:34398, reason: TLS/TCP socket buffer operation error (callback)
326: IPv4. tcp or tls connected to: 66.158.36.34:62884
326: IPv4. tcp or tls connected to: 66.158.36.34:56719
326: IPv4. tcp or tls connected to: 66.158.36.34:63836
326: IPv4. tcp or tls connected to: 66.158.36.34:57723
326: IPv4. tcp or tls connected to: 66.158.36.34:55736
326: IPv4. tcp or tls connected to: 66.158.36.34:53584
326: session 001000000000000016: realm <turn.axtsolutions.com> user <>: incoming packet message processed, error 401: Unauthorized
326: session 001000000000000017: realm <turn.axtsolutions.com> user <>: incoming packet message processed, error 401: Unauthorized
326: IPv4. Local relay addr: 66.158.36.55:65441
326: session 001000000000000016: new, realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, lifetime=600, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
326: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet ALLOCATE processed, success
326: IPv4. Local relay addr: 66.158.36.56:52892
326: session 001000000000000017: new, realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, lifetime=600, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
326: session 001000000000000017: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet ALLOCATE processed, success
326: session 001000000000000016: peer 10.107.47.112 lifetime updated: 300
326: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
326: session 001000000000000016: peer 10.107.47.112 lifetime updated: 300
326: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
326: session 001000000000000016: peer 10.207.195.153 lifetime updated: 300
326: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
326: session 001000000000000017: peer 10.107.47.112 lifetime updated: 300
326: session 001000000000000017: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
326: session 001000000000000017: peer 10.107.47.112 lifetime updated: 300
326: session 001000000000000017: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
326: session 001000000000000017: peer 10.207.195.153 lifetime updated: 300
326: session 001000000000000017: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
331: session 001000000000000016: peer 188.172.110.153 lifetime updated: 300
331: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
331: session 001000000000000017: peer 188.172.110.153 lifetime updated: 300
331: session 001000000000000017: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
331: session 001000000000000016: peer 188.172.110.153 lifetime updated: 300
331: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
331: session 001000000000000017: peer 188.172.110.153 lifetime updated: 300
331: session 001000000000000017: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CREATE_PERMISSION processed, success
331: session 001000000000000016: peer 188.172.110.153 lifetime updated: 600
331: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet CHANNEL_BIND processed, success
333: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
333: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
336: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=1124, rb=810368, sp=924, sb=523064
341: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=1014, rb=754530, sp=1034, sb=697436
343: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
345: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=778, rb=469813, sp=1270, sb=976316
351: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=749, rb=330110, sp=1299, sb=941652
353: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
354: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
357: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=643, rb=183835, sp=1405, sb=1046468
363: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=561, rb=90282, sp=1487, sb=1097328
364: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
369: session 003000000000000021: TLS/TCP socket disconnected: 66.158.36.34:53584
369: session 003000000000000021: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
369: session 002000000000000028: TLS/TCP socket disconnected: 66.158.36.34:57723
369: session 003000000000000021: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:53584, reason: TLS/TCP socket buffer operation error (callback)
369: session 000000000000000023: TLS/TCP socket disconnected: 66.158.36.34:63836
369: session 000000000000000023: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
369: session 000000000000000023: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:63836, reason: TLS/TCP socket buffer operation error (callback)
369: session 002000000000000028: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
369: session 002000000000000028: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:57723, reason: TLS/TCP socket buffer operation error (callback)
369: session 002000000000000029: TLS/TCP socket disconnected: 66.158.36.34:55736
369: session 002000000000000029: usage: realm=<turn.axtsolutions.com>, username=<>, rp=0, rb=0, sp=0, sb=0
369: session 002000000000000029: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:55736, reason: TLS/TCP socket buffer operation error (callback)
370: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=589, rb=75351, sp=1459, sb=1021352
374: session 002000000000000026: realm <turn.axtsolutions.com> user <>: incoming packet BINDING processed, success
376: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=519, rb=68391, sp=1529, sb=1197756
382: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=473, rb=62824, sp=1575, sb=1314792
382: session 002000000000000024: usage: realm=<turn.axtsolutions.com>, username=<>, rp=2, rb=40, sp=2, sb=192
382: session 002000000000000024: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:37915, reason: allocation watchdog determined stale session state
382: session 002000000000000025: usage: realm=<turn.axtsolutions.com>, username=<>, rp=2, rb=40, sp=2, sb=192
382: session 002000000000000025: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:39927, reason: allocation watchdog determined stale session state
382: session 002000000000000026: usage: realm=<turn.axtsolutions.com>, username=<>, rp=9, rb=180, sp=9, sb=864
382: session 002000000000000026: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 188.172.110.153:38019, reason: allocation watchdog determined stale session state
384: session 001000000000000016: refreshed, realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, lifetime=0, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
384: session 001000000000000016: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet REFRESH processed, success
384: session 001000000000000016: TLS/TCP socket disconnected: 66.158.36.34:62884
384: session 001000000000000016: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=161, rb=20049, sp=490, sb=399684
384: session 001000000000000016: closed (2nd stage), user <1628794364:aNFRTZLWQ3k8mqOg> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:62884, reason: TLS/TCP socket buffer operation error (callback)
384: session 001000000000000016: delete: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>
384: session 001000000000000016: peer 188.172.110.153 deleted
384: session 001000000000000016: peer 10.207.195.153 deleted
384: session 001000000000000016: peer 10.107.47.112 deleted
384: session 001000000000000017: refreshed, realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, lifetime=0, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
384: session 001000000000000017: realm <turn.axtsolutions.com> user <1628794364:aNFRTZLWQ3k8mqOg>: incoming packet REFRESH processed, success
384: session 001000000000000017: TLS/TCP socket disconnected: 66.158.36.34:56719
384: session 001000000000000017: usage: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>, rp=59, rb=7672, sp=10, sb=1072
384: session 001000000000000017: closed (2nd stage), user <1628794364:aNFRTZLWQ3k8mqOg> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:56719, reason: TLS/TCP socket buffer operation error (callback)
384: session 001000000000000017: delete: realm=<turn.axtsolutions.com>, username=<1628794364:aNFRTZLWQ3k8mqOg>
384: session 001000000000000017: peer 188.172.110.153 deleted
384: session 001000000000000017: peer 10.207.195.153 deleted
384: session 001000000000000017: peer 10.107.47.112 deleted
TLS/TCP socket buffer operation error (callback)560: IPv4. tcp or tls connected to: 192.241.221.12:43372
620: session 001000000000000018: usage: realm=<turn.axtsolutions.com>, username=<>, rp=1, rb=104, sp=0, sb=0
620: session 001000000000000018: closed (2nd stage), user <> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 192.241.221.12:43372, reason: allocation watchdog determined stale session state

**Comment by matthk0309** [comment]
I have found a solution for me. I only allow TLSv1.3, the rest of the methods are explicitly set to "no", so:
no-sslv3
no-tlsv1
no-tlsv1_1
no-tlsv1_2

I looked in the coturn-logs and captured the packets with wireshark on the server. There are many TLSv1.3 connections and no SSL or TLS errors. So I think the encrypted telephony should work now. Of course I am grateful for suggestions and constructive criticism.

**Comment by andyxheli** [comment]
I will give that a try thank you!!

**Comment by matthk0309** [comment]
Let me know if you were successful.

**Comment by andyxheli** [comment]
Yup i added and no more  TLS/TCP socket buffer errors. So far looks good. Thank you for the recommendation @matthk0309  🙏🏼🙂
no-sslv3
no-tlsv1
no-tlsv1_1
no-tlsv1_2

**Comment by Tycho-X** [comment]
Hello,

i am using the current Version 4.5.3 'dan Eider' and there seems to be no  "no-sslv3" option?!
