### ISSUE TITLE
Turn_uclient doesn't manage ephemeral ports under UDP

### ISSUE THREAD

**Issue by DoruM** [coturn/coturn#81]
Hello,

**Context**
We are trying to stress test via UDP the coturn server. To this end we use turn_uclient

**Steps to reproduce**

1. Install coturn server
1. Run `turnserver -p 3700 -n -a -v --use-auth-secret --realm=demo --static-auth-secret=kaazshared --rest-api-separator=: 2>&1 | tee ./log.txt`
1. Run `turnutils_uclient -n 200 -z 1 -m 400 -l 1000 -y -g -W kaazshared -p 3700 127.0.0.1 | tee ./uclient.log`

These commands will generate the following error:

14 0.350495223 127.0.0.1 3700 127.0.0.1 53750 STUN 156 Allocate Error Response error-code: 437 (Allocation Mismatch) Mismatched allocation: wrong transaction ID\
Message Transaction ID: 3acd3316b077d1bed6ee010f

[This](https://github.com/coturn/coturn/files/574919/mismatchTrans.zip)  captured stream describes a stream generated by the turnutils_uclient.

**Cause**

The problem is (in my opinion) the following: 
The local port (ephemeral) is allocated dynamically by the kernel when calling `connect` [here](https://github.com/coturn/coturn/blob/master/src/apps/common/apputils.c#L234). Since this is more or less random, an allocate request might be sent twice, from the same port with two different transaction ids.

**Possible solutions**

1. The first possible solution is to call bind before allocate. This solution has to take care of all the exception cases (such as if the port is already in use or not), and to check what is the range of ephemeral ports and so on.
1. A second solution consists in making sure that a package is not sent within the same allocation period from the same local (ephemeral) port. This means keeping track (at least for 10 minutes) of the ports and transactions ID sent from each port, OR modifying the actual time required by an allocation. According to the [RFC](https://tools.ietf.org/html/rfc5766#section-5): 

> By default, each Allocate or Refresh transaction resets this timer to the default lifetime value of **600 seconds (10 minutes)**, but the client can request a different value in the Allocate and Refresh request.

A similar note is done in the same [RFC](https://tools.ietf.org/html/rfc5766#section-6.4) with regards to 2 minutes:

>437 (Allocation Mismatch): This indicates that the client has picked a 5-tuple that the server sees as already in use.  One way this could happen is if an intervening NAT assigned a mapped transport address that was used by another client that recently crashed.  The client considers the current transaction as having failed.  The client SHOULD pick another client transport address and retry the Allocate request (using a different transaction id). The client SHOULD try three different client transport addresses before giving up on this server.  Once the client gives up on the server, it SHOULD NOT try to create another allocation on the server for **2 minutes.**

**Comment by mom040267** [comment]
turnutils_uclient is merely a toy and it is not meant to be accurate.
And for the stress-test, by the way, that behavior is actually beneficial.

But I'll take a look if that can be fixed.


On Mon, Nov 7, 2016 at 1:40 AM, Doru-Mihai Muntean <notifications@github.com

**Comment by mom040267** [comment]
The kernel does not allocate the local ports randomly. They are being taken from the pool, and the same port will not be allocated twice. Something else is not right if you see that problem. But as I said, the uclient is just a test toy, it is not supposed to be as robust and reliable as the turnserver.
