### ISSUE TITLE
What is the default configuration?

### ISSUE THREAD

**Issue by lambdaofgod** [coturn/coturn#811]
I run the docker container, but there is no config file in `/etc/coturn`.
I also tried to grep .conf files in `/etc` but I didn't find anything that looks like coturn config.

**Comment by mikouaji** [comment]
I dont know if you found it but if not here it is
https://github.com/coturn/coturn/blob/master/docker/coturn/turnserver.conf
Found it here https://github.com/coturn/coturn/tree/master/docker
