### ISSUE TITLE
When I start the turnserver, it tells me 'redis not supported'

### ISSUE THREAD

**Issue by ArSrNa** [coturn/coturn#813]
/usr/local/bin/turnserver  -L LISTEN-IP -o -a -b /etc/turnuserdb.conf -f -r REALM

and them
````
==== Show him the instruments, Practical Frost: ====
..........(all supported)
0: SQLite supported, default database location is /usr/local/var/db/turndb
0: Redis is not supported
0: PostgreSQL is not supported
0: MySQL is not supported
0: MongoDB is not supported
.........(all supported)
````

CentOS 8.0, Redis,MongoDB,PostgreSQL installed by 'sudo yum install xxx' (xxx are databases' name)

**Comment by plukito** [comment]
I was encountered this error.
What I did are:
1. Build coturn
2. Install database clients afterwards

But these steps wrong. I need to install the database first, then build coturn.
So I fixed this by simply rebuild the coturn.

**Comment by Tycho-X** [comment]
Coturn must be compiled with redis support / libs.

**Comment by eakraly** [comment]
Hi @ArSrNa ! Were you able to rebuild coturn with redis and DB support?
They are required for turnserver to operate unless you need the feature that relies on redis or DB
