### ISSUE TITLE
Question about entries in logs

### ISSUE THREAD

**Issue by cantontowerstation** [coturn/coturn#816]
This is just a question, hope that's ok.  

My `turnserver.conf` specifies:  
```
use-auth-secret
static-auth-secret=<SECRET>
```

In my logs I see a lot of the following:  
`realm <example.com> user <>: incoming packet BINDING processed, success`  
Note, the user is blank.  

Is this ok, from a security persepective? Is it to be expected when using `use-auth-secret` or something I should be concerned about?

Thanks for any pointers.

**Comment by eakraly** [comment]
Hi @cantontowerstation 
There is no security concern from what I see
If you still have questions please open additional issue
