### ISSUE TITLE
Python client to python client through turn or stun

### ISSUE THREAD

**Issue by C-monC** [coturn/coturn#817]
Hi,

I have a linode server running coturn and trickle ICE says it is working apparently. 

This is what I want to do:
Webserver on port 5000 <--> NAT <--> coturn <--> NAT <--> client accessing webserver

Server:
```
from flask import Flask

app = Flask(__name__)

@app.route("/")
def ping():
    return "ping"
app.run()
```
Client:
```
import requests

r = requests.get("http://TURNSERVER:5349/")
print(r.content)
```
Apologies if I missed the solution in the documentation/examples but how do I initiate the connections?
How do I ask coturn to forward the connection to the webserver and how does the webserver choose to receive connections?

Is http/https supported between peers? I can make use of sockets too if that is necessary.

**Comment by C-monC** [comment]
Ah, I have found a [library](https://github.com/aiortc/aiortc) that replaces the javascript RTCPeerConnection from [here](https://misi.github.io/webrtc-c0d3l4b/#24).

Will post a working example here if I manage.

**Comment by malhotraguy** [comment]
@C-monC  were you able to get any working solution for it ?

**Comment by C-monC** [comment]
@malhotraguy Yes. This is quite an embarrassing issue. 
Just add the turn server ip on line [110](https://github.com/aiortc/aiortc/blob/c41606ba216fea837f58e7799d12e8d71798184f/examples/datachannel-cli/cli.py#L110) as config object into the peer connection and it will work.
