### ISSUE TITLE
Need help to authenticate user with our session token server.

### ISSUE THREAD

**Issue by pjmun** [coturn/coturn#82]
I'm trying to modify some coturn code to check user through our session server.
Our session server keeps session token for every users.
And this server provide rest api to get token string.

-Below is my plan
1. Client connect to session server and get session token(token1234).
2. Client request allocation to coturn server with this token.(username: token1234, credential:token1234) 
3. coturn check(call rest api to session server) this token
    : I skipped checking user, password in check_stun_auth() function.
    : I just compared token(token1234).

-status
Client : javascript client in chrome browser.
Client doesn't work.
I think MESSAGE-INTEGRITY value is not proper in allocation response .
It'll be great if you give me some tip , advice, anything.

**Comment by misi** [comment]
I don't understand your motivations  (Why you are doing this way?)
I think the fastest way to in step 1. add also this token to other side in coturn auth db, 
so when client requests a token auth server should insert the token also to
coturn auth database in e.g. turnusers_lt table;
(and create a automation to delete these after the token expired.)

**Comment by pjmun** [comment]
IMHO, checking auth through rest api is simple, if there's a session server.
Because it's burden to manage another database in turnusers_lt table.

I figured out as my plan,
Thanks misi.

**Comment by misi** [comment]
I am now confuse did you solve it finally? If yes please close this issue.
Other way as you mentioned it he REST API

Set a static/or rotated/ shared secret(SS) on turn server side and shared this with your Auth Server side and generate username/credential based on  
- https://tools.ietf.org/html/draft-uberti-rtcweb-turn-rest-00
- https://www.ietf.org/proceedings/87/slides/slides-87-behave-10.pdf

**Comment by pjmun** [comment]
Function test is done, but need to performance test.
I think that there can be error in concurrent test.

Do i need to use mutex lock to call rest api in check_stun_auth() function ?

**Comment by misi** [comment]
It depends how you will handle outgoing connection, but probably you don't need mutex.
I would rather modifying code, but use the REST API method as I described in previous post. 
It is more mainstream, and has the benefit that TURN server could validate credential if Auth server is unavailable or down. (Of course your solution has also other benefits.)

**Comment by pjmun** [comment]
I guess one thread handles below flow, and that's why you mentioned mutex is not needed.
```
udp_server_input_handler() 
handle_udp_packet()
open_client_connection_session()
create_new_ss()
client_input_handler()
read_client_connection()
handle_turn_command()
check_stun_auth()
```

I wonder which point create multi thread to handle turn command(packet) for better performance ?

**Comment by Sacryn** [comment]
I'm looking to do something similar. Using a external authentication mechanism instead of local DB stuff. @pjmun Did you ever complete your work?

**Comment by ggarber** [comment]
@pjmun As misi said the recommended way is to use the shared secret support in coturn.  You can find an explanation here: https://stackoverflow.com/questions/35766382/coturn-how-to-use-turn-rest-api

This has been opening for too long.   Feel free to reopen the ticket if that solution doesn't work for you and explain why.
