### ISSUE TITLE
When TURN REST API used Prometheus metrics send wrong user name

### ISSUE THREAD

**Issue by udovichenkoAlexander** [coturn/coturn#827]
When TURN REST API used then Prometheus metrics user name send as **TIME:USER**. 
As result users not grouped correctly in monitoring and this lead to errors like **max-values-per-tag limit exceeded** in influx. 
It looks like user part must be extracted in this case before send metric username

![Снимок экрана от 2021-09-29 13-14-24](https://user-images.githubusercontent.com/23613015/135249824-aed19ade-0c2c-4c8e-b0f7-1688d2bf1f58.png)

**Comment by misi** [comment]
This is the right thing to log. username=timestamp:appdata 
see https://www.ietf.org/proceedings/87/slides/slides-87-behave-10.pdf

**Comment by udovichenkoAlexander** [comment]
Yes, I understand how REST API AUTH works.
Ok, it seems that to properly aggregate statistics by users and not by user tokens, I need truncate EXPIRY DATE by myself

**Comment by misi** [comment]
Sorry if you have any better proposal how to make it differently, we are open to improve the actual behavior.
Please make a PR and we can make an option to only put appdata in the reports.

**Comment by udovichenkoAlexander** [comment]
Ok, If I choose this solution I will make a PR
