### ISSUE TITLE
Bad configuration format: no-rfc5780

### ISSUE THREAD

**Issue by rgl** [coturn/coturn#830]
While trying out the following configuration file with the [coturn/coturn:4.5.2-r5 docker image](https://hub.docker.com/r/coturn/coturn):

```conf
verbose
log-file=stdout
listening-ip=0.0.0.0
listening-port=3478
alt-listening-port=3479
min-port=49160
max-port=49200
realm=coturn
# NB no need to use proc-user and proc-group. the container uses
#    the USER nouser:nogroup directive.
#proc-user=turnserver
#proc-group=turnserver
lt-cred-mech
fingerprint
no-software-attribute
no-multicast-peers
no-cli
# NB when using WebRTC (which already encrypts data) over TURN
#    we do not need TURN TLS nor DTLS.
#    TODO do we need TLS for the TURN credentials?
no-tls
no-dtls
no-rfc5780
no-stun-backward-compatibility
response-origin-only-with-rfc5780
```

I got the following errors in the logs:

```
0: : Bad configuration format: no-rfc5780
0: : Bad configuration format: no-rfc5780
0: : Bad configuration format: no-stun-backward-compatibility
0: : Bad configuration format: no-stun-backward-compatibility
0: : Bad configuration format: response-origin-only-with-rfc5780
0: : Bad configuration format: response-origin-only-with-rfc5780
0: : Config file found: //etc/coturn/turnserver.conf
0: : Config file found: //etc/coturn/turnserver.conf
```

I believe the options I'm using are correct because they are also used in the example configuration file at:

https://github.com/coturn/coturn/blob/4ee8f8e7d8632760e0b4ed8da328974fc5d1e190/examples/etc/turnserver.conf#L774

And are listed as `long_options` at:

https://github.com/coturn/coturn/blob/60eaa25d2b239235988161c01f4262f487126733/src/apps/relay/mainrelay.c#L989

Why is coturn showing them as errors?

**Comment by misi** [comment]
It seems r5 not built with that code,  so we need to make a new release.

**Comment by jdfalls** [comment]
Confirmed I'm also getting the same errors with docker image 4.5.2-r14.

**Comment by tyranron** [comment]
@kamilr @jdfalls I don't see those options in [4.5.2 release of Coturn](https://github.com/coturn/coturn/blob/upstream/4.5.2/src/apps/relay/mainrelay.c), I guess they have been [added after 4.5.2 release](https://github.com/coturn/coturn/commit/eda11698f0f5512e0149e807e39b5737187ae33f).

At the moment, until the new Coturn version is released, you may try to use `edge` Docker tag, which is built from the latest `master`.
