### ISSUE TITLE
/ home/tanyiyuan/webrtc/coturn/SRC/apps/relay/netengine. C: 316: 'SSL_CTX_up_ref undefined reference

### ISSUE THREAD

**Issue by Mangomm** [coturn/coturn#833]
‐ when I execute "sudo apt get install libssl‐dev" and "sudo apt get install libevent‐dev", then execute "./configure".

tanyiyuan@ubuntu:~/webrtc/coturn$ ./configure

ginstall: not found

install is /usr/bin/install

pkill is /usr/bin/pkill

sqlite3 is /usr/bin/sqlite3

Use TMP dir /var/tmp

Compiler: cc

pkgconf: not found

pkg-config is /usr/bin/pkg-config

pkg-config: pkg-config

Library option -lsocket cannot be used

Library option -lwldap32 cannot be used

Library option -lwldap64 cannot be used

Library option -lintl cannot be used

Sockets code is fine: no sin_len field present

Ignore IP_RECVERR

OpenSSL Crypto lib found.

OpenSSL lib found.

Libevent2 runtime found.

Library option -lprom cannot be used

Warning: Libprom development libraries are not installed properly in required location.

Prometheus support will be disabled.

See the INSTALL file.

Systemd library not found. Building without systemd support.

SQLite3 library found.

PostgreSQL not found. Building without PostgreSQL support.

MySQL found.

MongoDB not found. Building without MongoDB support.

Hiredis not found. Building without hiredis support.

PREFIX=/usr/local LOCALSTATEDIR=/usr/local/var OSLIBS= -lrt -lnsl -lresolv -pthread -lcrypto -lssl -levent_openssl -levent_pthreads -levent -Wl,-rpath,/usr/local/lib DBLIBS= -lsqlite3 -lmysqlclient OSCFLAGS=-g -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -DTURN_HAS_DAEMON -pthread -DTURN_NO_PROMETHEUS -DINSTALL_PREFIX=/usr/local -DTURNDB=/usr/local/var/db/turndb DBCFLAGS= -I/usr/include/mysql

Makefile created: success.

Then I execute "make "and the following error occurs:

SRC/apps/relay/netengine. C: 316:3: warning: nested extern declaration of 'SSL_CTX_up_ref [- Wnested - externs]

/ TMP/cchfcijy. o: in function 'replace_one_ssl_ctx' :

/ home/tanyiyuan/webrtc/coturn/SRC/apps/relay/netengine. C: 316: 'SSL_CTX_up_ref undefined reference

collect2: error: ld returned 1 exit status

Makefile:134: recipe for target 'bin/turnserver' failed

make: *** [bin/turnserver] Error 1

So what kind of mistake is this?

**Comment by Mangomm** [comment]
My solution was to change the version：

wget https://github.com/coturn/coturn/archive/4.5.1.1.tar.gz
tar -zxvf 4.5.1.1.tar.gz
cd coturn-4.5.1.1
./configure
make
sudo make install

**Comment by ggarber** [comment]
If I understand it correctly the build was failing with an old version of coturn but working with a newer one so I think this can be closed.  Reopen if that's not the case.  Than kyou!
