### ISSUE TITLE
coturn 4.5.2 compile --> MySQL not found

### ISSUE THREAD

**Issue by SenaSokmen-KL** [coturn/coturn#835]
Hi,
I try to upgrade the coturn 4.5.1.2 to 4.5.2 . I complied the 4.5.1.2v on rhel6.10 server without any problem but when I try to compile 4.5.2v the logs said MySQL not found. I failed on that. The server and tools are same but result is different. Why? Could you please help me ?

**from 4.5.1.2:**
Compiler: gcc
Library option -lsocket cannot be used
Library option -lwldap32 cannot be used
Library option -lwldap64 cannot be used
Library option -lintl cannot be used
Sockets code is fine: no sin_len field present
Ignore IP_RECVERR
Library option -lsqlite3 cannot be used
SQLite3 development library cannot be found.

SQLite DEVELOPMENT LIBRARY (libsqlite3) AND/OR HEADER (sqlite3.h)
        ARE NOT INSTALLED PROPERLY ON THIS SYSTEM.
        THAT'S OK BUT THE TURN SERVER IS BUILDING WITHOUT SQLITE SUPPORT.

POSTGRESQL DEVELOPMENT LIBRARY (libpq.a) AND/OR HEADER (libpq-fe.h)
        ARE NOT INSTALLED PROPERLY ON THIS SYSTEM.
        THAT'S OK BUT THE TURN SERVER IS BUILDING WITHOUT POSTGRESQL DATABASE SUPPORT.

MySQL found.

MONGODB DEVELOPMENT LIBRARIES (libmongoc-1.0 and libbson-1.0) AND/OR HEADER (mongoc.h)
        ARE NOT INSTALLED PROPERLY ON THIS SYSTEM.
        THAT'S OK BUT THE TURN SERVER IS BUILDING WITHOUT MONGODB SUPPORT.

HIREDIS DEVELOPMENT LIBRARY (libhiredis.*) AND/OR HEADERS (hiredis/*.h)
        ARE NOT INSTALLED PROPERLY ON THIS SYSTEM.
        THAT'S OK BUT THE TURN SERVER IS BUILDING WITHOUT REDIS SUPPORT.

**from 4.5.2**
Compiler: gcc
pkg-config is /usr/bin/pkg-config
pkg-config: pkg-config
Library option -lsocket cannot be used
Library option -lwldap32 cannot be used
Library option -lwldap64 cannot be used
Library option -lintl cannot be used
Sockets code is fine: no sin_len field present
Ignore IP_RECVERR
Library option -lprom cannot be used

Warning: Libprom development libraries are not installed properly in required location.
Prometheus support will be disabled.
See the INSTALL file.

Systemd library not found. Building without systemd support.
SQLite3 development library not found. Building without SQLite3 support.
PostgreSQL not found. Building without PostgreSQL support.
MySQL not found. Building without MySQL support.
MongoDB not found. Building without MongoDB support.
Hiredis not found. Building without hiredis support.

**Comment by robert-scheck** [comment]
This issue has been solved using commit 699497272624df86126f769c4b5b839e7b0c92a9 and could be closed.

**Comment by eakraly** [comment]
Thank you @robert-scheck for confirmation
