### ISSUE TITLE
No log generated from Conturn server

### ISSUE THREAD

**Issue by smallfish01** [coturn/coturn#839]
Hi Everyone,

I just installed Coturn on my Ubuntu server(20.04.2 LTS) and enabled turnserver.conf log as below:
#syslog
verbose
log-file=/var/log/turnserver.log
systemctl restart coturn.service

But I cannot found log file /var/log/turnserver.log, I'd like to know which configuration I missed?

Thank you.

**Comment by eakraly** [comment]
Hi @smallfish01 
Were you able to address the issue?
