### ISSUE TITLE
OLD STUN method

### ISSUE THREAD

**Issue by tangxinzhou** [coturn/coturn#84]
Hi , I have installed coturn on ubuntu 16.04, but there are some problems in the opration, the log file shows:

61572: session 000000000000000004: realm <turn.devicetalk.cc> user <>: incoming packet OLD BINDING processed, success
61572: session 000000000000000004: realm <turn.devicetalk.cc> user <>: incoming packet OLD BINDING processed, success
61572: session 000000000000000004: realm <turn.devicetalk.cc> user <>: incoming packet OLD BINDING processed, success
61572: handle_old_stun_command: OLD STUN method 0x3 ignored
61572: handle_old_stun_command: OLD STUN method 0x3 ignored
61572: handle_old_stun_command: OLD STUN method 0x3 ignored
61573: handle_old_stun_command: OLD STUN method 0x3 ignored

I can get the binding responsed , but allocation failed .

It looked like that the messages to the coturn server are judged as "OLD STUN method" , and only "OLD BINDING" are accepted , all others discarded.

I have tested my turn client program with the public turn server "numb.viagenie.ca/" , and it works.

What about the meaning of OLD STUN method?  If I forget to add something in the message?

BR

**Comment by mom040267** [comment]
The legacy STUN protocol is not supported, only the old BINDING can be used
(not advised).

What kind of client library you are using ?

Oleg

**Comment by tangxinzhou** [comment]
Hi ,

The client program is written in C++, Qt , by myself, revised from some other programs.

I have checked the program, the magic cookie is wrongly set. It now works well, I can get the correct request and response message in wireshark.

Thanks for the help.

BR
