### ISSUE TITLE
"new-log-timestamp-format" does not work 

### ISSUE THREAD

**Issue by SenaSokmen-KL** [coturn/coturn#847]
Hi @PaulWay @misi ,

I added the parameter to the turnserver.conf file as below and then restart the turn, but timestamp is not logged. 

new-log-timestamp-format  "%y-%m-%d %H:%M:%S"

or

new-log-timestamp-format "%FT%T%z"

On the other hand if I use only "new-log-timestamp", then it works. I used lots of format of timestamp but could not be successful. What's the correct format or is there any problem about formatting ?

2021-11-01T23:57:03+0300: IPv4. CLI authentication success: 127.0.0.1:38712
2021-11-01T23:57:08+0300: IPv4. CLI session disconnected from: 127.0.0.1:38712
2021-11-01T23:58:03+0300: IPv4. CLI connected to: 127.0.0.1:38714
2021-11-01T23:58:03+0300: IPv4. CLI authentication success: 127.0.0.1:38714
2021-11-01T23:58:08+0300: IPv4. CLI session disconnected from: 127.0.0.1:38714
2021-11-01T23:59:03+0300: IPv4. CLI connected to: 127.0.0.1:38716
2021-11-01T23:59:03+0300: IPv4. CLI authentication success: 127.0.0.1:38716

coTurn version: 4.5.2

Thanks,
Sena

**Comment by a-arda** [comment]
While investigating the code, it has been seen that new-log-timestamp-format works if new-log-timestamp config is also enabled.

Maybe this should be documented in README.turnserver file or use_new_log_timestamp_format in mainrelay.c should be set to 1 for NEW_LOG_TIMESTAMP_FORMAT_OPT config case.

**Comment by brian-collins-af** [comment]
Testing this on `coturn v4.5.2` I think I might be missing something,
The `logfile` does not pick the timestamps even after enabling `new-log-timestamp` in the config file.
I have commented out `syslog` and added this `log-file=/path/to/my/turnserver.log` but still the created logfile do not pick the timestamps. **Is there a way to enable timestamps in the log-files**

**Comment by GD-Dheer** [comment]
> Testing this on `coturn v4.5.2` on `Ubuntu 20.04.5 LTS` I think I might be missing something, The `logfile` does not pick the timestamps even after enabling `new-log-timestamp` in the config file. I have commented out `syslog` and added this `log-file=/path/to/my/turnserver.log` but still the created logfile do not pick the timestamps. **Is there a way to enable timestamps in the log-files**

Did you ever find a solution to this? Restarting my coturn by hand gave me:
Bad configuration format: new-log-timestamp

**Comment by PaulWay** [comment]
@GD-Dheer - can you give us the `new-log-timestamp` lines of the config file that gives this error?

`new-log-timestamp` is a boolean - if it's present, the timestamps in the log are in the new format; if it's absent they are in the old format.  It does not take a value - i.e. it just appears as `new-log-timestamp`, not `new-log-timestamp=true`.

`new-log-timestamp-format` takes a string value.  This does not need to be quoted but it can be.  It can also be preceded by an '`=`' but it can be.  In other words you can do `new-log-timestamp-format=%F-%T`, `new-log-timestamp-format="%F %T"`, `new-log-timestamp-format %F-%T` or `new-log-timestamp-format "%F %T"`.  The quotes allow the value to include spaces.

The message `Bad configuration format` comes from failing to parse that argument.  If you can show us the line you're using, we can work out what's going wrong.
