### ISSUE TITLE
closed (2nd stage), user <wtf> realm <test> origin <>, local 172.16.101.192:3478, remote 59.153.92.168:52423, reason: allocation timeout

### ISSUE THREAD

**Issue by joinwen** [coturn/coturn#850]
19: : session 003000000000000001: peer 172.16.101.192 lifetime updated: 300
19: : session 003000000000000001: realm <test> user <wtf>: incoming packet CREATE_PERMISSION processed, success
259: : session 003000000000000001: peer 192.168.50.47 lifetime updated: 300
259: : session 003000000000000001: realm <test> user <wtf>: incoming packet CREATE_PERMISSION processed, success
259: : session 003000000000000001: peer 59.153.92.168 lifetime updated: 300
259: : session 003000000000000001: realm <test> user <wtf>: incoming packet CREATE_PERMISSION processed, success
259: : session 003000000000000001: peer 192.168.200.1 lifetime updated: 300
259: : session 003000000000000001: realm <test> user <wtf>: incoming packet CREATE_PERMISSION processed, success
259: : session 003000000000000001: peer 192.168.121.1 lifetime updated: 300
259: : session 003000000000000001: realm <test> user <wtf>: incoming packet CREATE_PERMISSION processed, success
259: : session 003000000000000001: peer 172.16.101.192 lifetime updated: 300
259: : session 003000000000000001: realm <test> user <wtf>: incoming packet CREATE_PERMISSION processed, success
319: : session 003000000000000001: refreshed, realm=<test>, username=<wtf>, lifetime=0
319: : session 003000000000000001: realm <test> user <wtf>: incoming packet REFRESH processed, success
320: : session 003000000000000001: usage: realm=<test>, username=<wtf>, rp=44, rb=1744, sp=44, sb=3956
320: : session 003000000000000001: peer usage: realm=<test>, username=<wtf>, rp=0, rb=0, sp=0, sb=0
320: : session 003000000000000001: closed (2nd stage), user <wtf> realm <test> origin <>, local 172.16.101.192:3478, remote 59.153.92.168:52423, reason: allocation timeout
320: : session 003000000000000001: delete: realm=<test>, username=<wtf>
320: : session 003000000000000001: peer 192.168.121.1 deleted
320: : session 003000000000000001: peer 192.168.50.47 deleted
320: : session 003000000000000001: peer 192.168.200.1 deleted
320: : session 003000000000000001: peer 59.153.92.168 deleted
320: : session 003000000000000001: peer 172.16.101.192 deleted

********************************************************************************************************************************************

why allocation timeout and delete realm, how to solve

**Comment by mBouamama** [comment]
hi @joinwen,
do you find a solution?
Regards

**Comment by 6stprod** [comment]
solution?

**Comment by lampham2505** [comment]
does any one find a solution for this?

**Comment by kolserdav** [comment]
+1

**Comment by eakraly** [comment]
There is no issue here: allocations were created, maintained, some lifetimes were extended, and eventually closed due to timeout (not used)

This is a self-protection mechanism that ensures resource clean up in turnserver.

I see no reason to worry about
