### ISSUE TITLE
How to update coturn to latest version

### ISSUE THREAD

**Issue by rushglen** [coturn/coturn#852]
I installed using: sudo apt-get install coturn
checking the version (using run turnserver) I get
Version Coturn-4.5.0.7 'dan Eider'
What's the best way to update to  4.5.2-r6 ?

**Comment by GingerAdonis** [comment]
The easiest way is to look into the Docker images that are provided.

**Comment by jienco** [comment]
Does someone know if `4.5.3` version of `coturn` will be published in docker hub https://hub.docker.com/r/coturn/coturn ? Thanks!

**Comment by eakraly** [comment]
@rushglen did you find a solution? What distro are you using?

As commented above you can build from source code instead of using coturn version of your distro. You can use any of the docker files as an inspiration.
