### ISSUE TITLE
CoTurn Crashes Instandly

### ISSUE THREAD

**Issue by GivouDev** [coturn/coturn#854]
Hey Guys,

i dont know why, but my Turn Server crashes instandly when i try to start it with "turnserver -c /etc/turnserver/turnserver.conf -o --no-cli"
It worked like a charm and i used it with NextCloud Talk.

After a Server restart we noticed that we hang on "Connecting" in NextCloud Talk.
I looked after the CoTurn Server and it crashed.

I tried to start it manually with the command above and it just rattles the following output down and then it exit:

`
[root@thiemoo turnserver]# turnserver -c /etc/turnserver/turnserver.conf -o --no-cli
0: : Bad configuration format: no-loopback-peers
0: : log file opened: /var/log/turnserver/turn_755149_2021-11-19.log
0: : Whitelisting external-ip private part: 64
0: : Bad configuration format: no-loopback-peers
0: : Bad configuration format: no-loopback-peers
0: :
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.2 'dan Eider'
0: :
Max number of open files/sockets allowed for this process: 524288
0: :
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 262000 (approximately)
0: :

==== Show him the instruments, Practical Frost: ====

0: : TLS supported
0: : DTLS supported
0: : DTLS 1.2 supported
0: : TURN/STUN ALPN supported
0: : Third-party authorization (oAuth) supported
0: : GCM (AEAD) supported
0: : OpenSSL compile-time version: OpenSSL 1.1.1k  25 Mar 2021 (0x101010bf)
0: :
0: : SQLite supported, default database location is /var/db/turndb
0: : Redis supported
0: : PostgreSQL supported
0: : MySQL supported
0: : MongoDB is not supported
0: :
0: : Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: : Domain name:
0: : Default realm: hub.thiemoo.at
0: : SSL23: Certificate file found: /etc/letsencrypt/live/thiemoo.at/fullchain.pem
0: : SSL23: Private key file found: /etc/letsencrypt/live/thiemoo.at/privkey.pem
0: : TLS1.2: Certificate file found: /etc/letsencrypt/live/thiemoo.at/fullchain.pem
0: : TLS1.2: Private key file found: /etc/letsencrypt/live/thiemoo.at/privkey.pem
0: : TLS cipher suite: Nope                                                         
0: : DTLS: Certificate file found: /etc/letsencrypt/live/thiemoo.at/fullchain.pem
0: : DTLS: Private key file found: /etc/letsencrypt/live/thiemoo.at/privkey.pem
0: : DTLS1.2: Certificate file found: /etc/letsencrypt/live/thiemoo.at/fullchain.pem
0: : DTLS1.2: Private key file found: /etc/letsencrypt/live/thiemoo.at/privkey.pem
0: : DTLS cipher suite: Nope
0: : NO EXPLICIT LISTENER ADDRESS(ES) ARE CONFIGURED
0: : ===========Discovering listener addresses: =========
0: : Listener address to use: 127.0.0.1
0: : Listener address to use: 157.90.27.117
0: : Listener address to use: 10.8.0.1
0: : Listener address to use: 172.20.0.1
0: : Listener address to use: 172.22.1.1
0: : Listener address to use: 172.17.0.1
0: : Listener address to use: 172.18.0.1
0: : Listener address to use: ::1
0: : Listener address to use: fd4d:6169:6c63:6f77::1
0: : Listener address to use: fd00:dead:beef:c0::1
0: : Listener address to use: fdba:17c8:6c94::1011
0: : =====================================================
0: : Total: 9 'real' addresses discovered
0: : =====================================================
0: : NO EXPLICIT RELAY ADDRESS(ES) ARE CONFIGURED
0: : ===========Discovering relay addresses: =============
0: : Relay address to use: 157.90.27.117
0: : Relay address to use: 10.8.0.1
0: : Relay address to use: 172.20.0.1
0: : Relay address to use: 172.22.1.1
0: : Relay address to use: 172.17.0.1
0: : Relay address to use: 172.18.0.1
0: : Relay address to use: fd4d:6169:6c63:6f77::1
0: : Relay address to use: fd00:dead:beef:c0::1
0: : Relay address to use: fdba:17c8:6c94::1011
0: : =====================================================
0: : Total: 9 relay addresses discovered
0: : =====================================================
`

My turnserver.conf looks like this:

`
external-ip=157.90.27.117
external-ip=2a01:4f8:1c0c:6e40::/64

listening-port=3478
tls-listening-port=443

realm=hub.thiemoo.at

cert=/etc/letsencrypt/live/thiemoo.at/fullchain.pem
pkey=/etc/letsencrypt/live/thiemoo.at/privkey.pem

no-tlsv1
no-tlsv1_1

cipher-list=DontKnowIfIShouldHideThisButIDo

use-auth-secret
static-auth-secret=NotForYou

no-loopback-peers
no-multicast-peers

fingerprint
total-quota=50
`

**Comment by MicheleTedesco** [comment]
0: : Bad configuration format: no-loopback-peers
Your system was obviously updated to turnserver-4.5.2 at some time, where the option "no-loopback-peers" is no longer valid in the configuration. This should not cause the crash, but it might be a hint to look at the config and compare with the 4.5.2 example config, check the systemd configuration of the turnserver or if some libraries are out of date (openssl 1.1.1k is listed above, this should be OK).

**Comment by MicheleTedesco** [comment]
just another hint: all the listener and relay adresses listed above will be transmitted to the peers connecting to your server. Maybe there are some internal adresses in there, for admin or backup networks by example, which should not be known to the public. If you configure a listener address and maybe an external ip too the list of adresses offered to the peers should be very short.

**Comment by eakraly** [comment]
HI @GivouDev! Did you find a solution for your issue?

If yes - could you please post how you fixed it and close the issue?
