### ISSUE TITLE
Probably memory leak during long run

### ISSUE THREAD

**Issue by yzabalotski** [coturn/coturn#857]
We run coturn inside docker. Memory usage daily increases for 40-100 Mb.

Looks like can be reproduced with latest master(fcff27f88b690afa):
1. start coturn: `turnserver -z -v --max-allocate-lifetime=20 --max-allocate-timeout=2 --no-cli`
2. run htop to track RSS
3. stress: `for (( i=1; i <= 10000; i++ )) ; do; turnutils_uclient -y -v YOUR_IP; done`

Note that RSS is slowly, but constantly growing.

I've tried to run under valgrind - only constant one, looks unrelated. Massif seems to be OK too.

@misi  Any tip? Might be a configuration issue?

Thanks in advance!

**Comment by eakraly** [comment]
#792 potentially related

**Comment by WwwJy** [comment]
the same this question；
And I added some debug logs to see if it was the same as the #792 problem
`
			if (value) {
				size_t size = ur_string_map_size(rp->status.alloc_counters);
				TURN_LOG_FUNC(TURN_LOG_LEVEL_ERROR, "map length %d \n", (int)size);
				value = (ur_string_map_value_type)(((size_t)value) - 1);
				ur_string_map_put(rp->status.alloc_counters, (ur_string_map_key_type) username, value);
			}
`
The map length is always 1, so it may not be the problem #792 says

**Comment by eakraly** [comment]
Another memory leak fix here #962
@WwwJy any chance you can test latest master and confirm if that addresses memory leak in your case?

**Comment by WwwJy** [comment]
> Another memory leak fix here #962 @WwwJy any chance you can test latest master and confirm if that addresses memory leak in your case?

version: release docker/4.5.2-r14
This problem still exists

test script
`
for i in `seq 10000`
do
turnutils_uclient -T -t -y -g -u ${user_name} -w ${password} -p ${listening_port} $@ 127.0.0.1
done
`

**Comment by eakraly** [comment]
>release docker/4.5.2-r14
It does not contain the fix

**Comment by WwwJy** [comment]
> > release docker/4.5.2-r14
> > It does not contain the fix

I used the latest master branch code and continued to test. The problem of memory growth still exists. However, the problem has been improved and the memory growth rate has become slow.

**Comment by eakraly** [comment]
Thank you @WwwJy !
Can you please post some graphs or numbers from your test?

**Comment by eakraly** [comment]
There is a dramatic improvement in memory usage with 4.6.0
Closing this issue
