### ISSUE TITLE
Problems when deploying in EC2 container

### ISSUE THREAD

**Issue by Kimblis** [coturn/coturn#858]
Hey, I spent a long time fixing issues since there are not any clear deployment documentation in aws ec2 (that would be really well appreciated). Currently I'm running into this problem in my logs:

![image](https://user-images.githubusercontent.com/46688616/144042909-7d84f6d0-6d9d-488f-b3d3-3b19d214a39c.png)
![image](https://user-images.githubusercontent.com/46688616/144042933-3bc2d093-3cee-46f4-8ed0-170f2d9ba5ff.png)
and well it keeps going like this for a while...
Any ideas what could go wrong?

**Comment by gufronr** [comment]
did you open the ports that used by coturn in aws console?

**Comment by eakraly** [comment]
How do you run the container? What is the ec2 setup?
Please share configuration file

It seems like the underlying OS does not provide enough privilege for the container to bind to the network address you provided. One possibility is that 13.37.71.9 is not an IP address of the instance

Could be a misconfiguration - external IP does not necessarily mean your instance IP

**Comment by eakraly** [comment]
Closing as not active
Please reopen if you are still having an issue
