### ISSUE TITLE
4.5.2 cannot be installed because of missing latest libevent

### ISSUE THREAD

**Issue by laszloh11** [coturn/coturn#862]
Hi,

I have 4.5.11 and libevent 2.1.8 installed on Red Hat 7 and it works fine. I try to install coturn 4.5.2 but it says: ERROR: Libevent2 development libraries are not installed properly in required location.

I updated libevent to the latest 2.1.12 but receives the same error message. 

What is the issue?

**Comment by wferi** [comment]
What's the output of the `pkg-config --libs libevent` command?

**Comment by laszloh11** [comment]
After setting PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
-L/usr/local/lib -levent_core -levent_extra -levent_openssl -levent_pthreads -levent
-L/usr/local/lib -levent_openssl -levent_pthreads -levent

In the meantime we realized that coturn 4.5.2 is available on Red Hat as an RPM package and after installing it works fine. However the manual installation is still aborted because of the Libevent error

**Comment by wferi** [comment]
Do you mean you still get the same error when you run `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure`?

**Comment by laszloh11** [comment]
Yes

**Comment by eakraly** [comment]
Hi @laszloh11 ! Do you still have the issue? Is it still relevant?

**Comment by laszloh11** [comment]
> Hi @laszloh11 ! Do you still have the issue? Is it still relevant?

I skipped the manual installation and went on with the RPM package installation instead, so the issue is not relevant for me.

Thanks
