### ISSUE TITLE
Ports for external-ip

### ISSUE THREAD

**Issue by QuickBanny** [coturn/coturn#866]
I have no connection when calling via TURN. My guess is that this is due to the external IP address. I have a question "do I need to open port 3478 for an external IP address?"

**Comment by GingerAdonis** [comment]
Yes, you definitely need to open up various ports. The following ports are a good start if you're using the default config:
- `3478` (TCP & UDP)
- `5349` (TCP & UDP)
- `49152` - `65535` (UDP)

**Comment by QuickBanny** [comment]
> Yes, you definitely need to open up various ports. The following ports are a good start if you're using the default config:
> 
> * `3478` (TCP & UDP)
> * `5349` (TCP & UDP)
> * `49152` - `65535` (UDP)

Thanks, I also notice that I don't have CREATE_PERMISSION in my logs at all

**Comment by QuickBanny** [comment]
incoming packet BINDING processed, success other than that, nothing happens

**Comment by ggarber** [comment]
@QuickBanny The list of ports shared by GingerAdonis is correct.

1/ what is the client you are using?  Are you forcing it to use turn? What error do you get in the client?
2/ can you share a network capture? you can use wireshark.

BTW Before the create permission there should be an allocation creation.
