### ISSUE TITLE
init script does not run the daemon on Ubuntu 16.04

### ISSUE THREAD

**Issue by ibc** [coturn/coturn#87]
* Ubuntu 16.04
* coturn 4.5.0.3-1build1 (deb package)

Something very weird.  `TURNSERVER_ENABLED=1` in `/etc/default/coturn`. Then I run (as root):

```bash
$ /etc/init.d/coturn start
```

*NOTE:* Using `systemctl start coturn` the same happens.

The init script just ends without even trying to run the daemon. After inspecting what happens, I've realized of the following weird issue:

* `/etc/init.d/coturn` loads LSB related stuff into line 40:

```bash
. /lib/lsb/init-functions
```

* Such a file, at the end, does this:

```bash
# Include hooks from other packages in /lib/lsb/init-functions.d
for hook in $(run-parts --lsbsysinit --list /lib/lsb/init-functions.d 2>/dev/null); do
    [ -r $hook ] && . $hook || true
done
```

* That loop loads files under `/lib/lsb/init-functions.d/`. First it loads `01-upstart-lsb`, then `20-left-info-blocks`, and then it tries to load `40-systemd`...

* But it happens that, at the end of `40-systemd` this code is executed:

```bash
if [ "$_use_systemctl" = "1" ]; then
    # Some init scripts use "set -e" and "set -u", we don't want that
    # here
    set +e
    set +u

    if  [ "x$1" = xstart -o \
        "x$1" = xstop -o \
        "x$1" = xrestart -o \
        "x$1" = xreload -o \
        "x$1" = xforce-reload -o \
        "x$1" = xstatus ] ; then

        systemctl_redirect $0 $1
        exit $?
    fi
fi
```

* `$1` is indeed "start" so `"x$1" = "xstart"` is true. The `exit` call ends the entire script execution and nothing else happens.

**Comment by mom040267** [comment]
We maintain and test the Debian package. We do not test it on Ubuntu. This
may be an incompatibility between the package version and the Ubuntu
version.

**Comment by ibc** [comment]
Fine. You may want to also include a proper systemd service (rather than a boring and deprecated systemv init script):

/etc/systemd/system/coturn.service:

```
[Unit]
Description=coturn TURN Server
After=network.target

[Service]
Type=forking
PIDFile=/var/run/turnserver.pid
ExecStart=/usr/bin/turnserver -c /etc/turnserver.conf -o -v
KillMode=process
Restart=on-failure
IgnoreSIGPIPE=yes

[Install]
WantedBy=multi-user.target
```

It works.

**Comment by mom040267** [comment]
Thanks for the systemd file example.

**Comment by dbrgn** [comment]
Here's an extended version that can increases the limits and runs as non-root user:

```
[Unit]
Description=coturn
Documentation=man:coturn(1) man:turnadmin(1) man:turnserver(1)
After=syslog.target network.target

[Service]
Type=forking
User=turnserver
Group=turnserver
RuntimeDirectory=turnserver
RuntimeDirectoryMode=0750
EnvironmentFile=/etc/default/coturn
PIDFile=/run/turnserver/turnserver.pid
ExecStart=/usr/bin/turnserver --daemon --pidfile /run/turnserver/turnserver.pid --syslog -c /etc/turnserver.conf $EXTRA_OPTIONS
Restart=on-abort
LimitCORE=infinity
LimitNOFILE=1000000
LimitNPROC=60000
LimitRTPRIO=infinity
LimitRTTIME=7000000
CPUSchedulingPolicy=other
UMask=0007

[Install]
WantedBy=multi-user.target
```

To enable verbose logging, /etc/default/coturn should contain `EXTRA_OPTIONS=-v`.

To be able to bind to port 443 as non-root, the `/usr/bin/turnserver` binary needs the `CAP_NET_BIND_SERVICE` capability (`setcap /usr/bin/turnserver cap_net_bind_service=+ep`).

**Comment by mom040267** [comment]
Running it as a non-root would make damage the process ability to create
sockets on port numbers less than 1024, right ?

Oleg

**Comment by dbrgn** [comment]
No, you missed the last part:

> To be able to bind to port 443 as non-root, the /usr/bin/turnserver binary needs the CAP_NET_BIND_SERVICE capability (setcap /usr/bin/turnserver cap_net_bind_service=+ep).

I think this feature has been in the Linux kernel for a few years now.

**Comment by mom040267** [comment]
OK, I'll check that.

Thanks
Oleg

**Comment by davidmweber** [comment]
Use `setcap 'cap_net_bind_service=+ep' /usr/bin/turnserver` instead of the command proposed by @dbrgn

**Comment by ggarber** [comment]
I think this old issue was already addressed .  Reopen if that's not the case and thank you very much for the report and the discussion.
