### ISSUE TITLE
Can't get srflx and relay candidates! Tried a lot of suggestions but all failed, Please read detail

### ISSUE THREAD

**Issue by abdelmark** [coturn/coturn#873]
### Linux VPS - Linux 8:
OS: Debian 10 (64-bit)- Debian 4.19.37-5
Processor: 2 x 2.6 GHz
Memory: 8192 MB

### Firewall and system privileges
Firewall: no firewall set, all ports are enabled and tested with: telnet <ip> <port>
Coturn "turnserver" process: running with "Root" user, to be able to read ssl certificates

### /etc/turnserver.conf:

listening-port=3478
tls-listening-port=5349
external-ip=public-ip/private-ip
min-port=49152
max-port=65535
fingerprint
verbose
syslog
realm=domain.com
server-name=domain.com
lt-cred-mech
user=username:password
cert=/etc/letsencrypt/live/domain.com/fullchain.pem
pkey=/etc/letsencrypt/live/domain.com/privkey.pem
no-cli
stale-nonce

### /var/log/syslog:

Coturn starting logs show that the coturn was started correctly, cert and pkey are found, all listener/relay addresses and port was found and successfully initialized...

### Testing results (on FireFox 95.0.2 (64-bit)) :
ICE servers:
stun:stun.domain.com:3478?transport=tcp
turn:turn.domain.com:3478?transport=tcp[username:password]

TEST1 WITH:  https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
![image](https://user-images.githubusercontent.com/88550100/147655652-d2b7cbd0-c8fe-4ebd-9401-71973b573c16.png)

TEST2 WITH: https://icetest.info/ 
![image](https://user-images.githubusercontent.com/88550100/147655932-26b462b0-b44e-44a3-a813-6e820c061843.png)

As you can see the stun and turn servers are not working:
no candidate with type "srflx".
no candidate with type "relay".

How can I solve this!?? I appriciate your help

**Comment by abdelmark** [comment]
@misi any suggestions? Thank you.

**Comment by oort7** [comment]
Try without `transport=tcp` parameter. You can read more here: https://stackoverflow.com/questions/54546022/should-a-turn-request-include-candidates-for-stun

**Comment by ggarber** [comment]
@abdelmark Is this still an issue ? IT is an old ticket and it is likely to be a configuration problem in your coturn instance or its firewall.   Let me know if we can still help and otherwise I think it is better to close this ticket.  Thx!
