### ISSUE TITLE
Rootles Docker Container gives an error message "Could not start Prometheus collector!"

### ISSUE THREAD

**Issue by taurhine** [coturn/coturn#874]
I'm trying to make a rootless coturn docker container work. However coturn seems not to listen to the ports and I'm getting "Could not start Prometheus collector!"
At first I thought it was maybe related to my configuration file, but it seems even the command mentioned in docker hub seems to cause the same issue:

docker run -d --name coturn -p 3478:3478 -p 3478:3478/udp -p 5349:5349 -p 5349:5349/udp -p 49160-49200:49160-49200/udp        coturn/coturn -n --log-file=stdout                         --external-ip='$(detect-external-ip)'                         --min-port=49160 --max-port=49200

So far, I've tried the following tags

coturn/coturn
coturn/coturn:4
coturn/coturn:4.5
coturn/coturn:4.5.2
coturn/coturn:debian
coturn/coturn:latest

and all of them have the same issue.

As my coturn instance is not working, I'm not sure whether this error is the reason for the problem or not.

**Comment by cihadturhan** [comment]
@taurhine Were you able to find solution?

**Comment by cihadturhan** [comment]
Ok I added `--prometheus` argument so it doesn't give the error anymore

**Comment by taurhine** [comment]
Thanks for the reply @cihadturhan I haven't found a solution yet. Adding --prometheus gives me "unknown flag: --prometheus"

**Comment by sitwaheed9** [comment]
> Ok I added `--prometheus` argument so it doesn't give the error anymore

its working :)

**Comment by eakraly** [comment]
@taurhine you need to recompile coturn with prometheus support
`unknown flag: --prometheus` in the log means coturn was build without support for prometheus

**Comment by taurhine** [comment]
Thanks for the info. I presume prometheus is not a dependency which would stop container working normally right? The problem I have is, I have a coturn config which I've been using for years without a problem but coturn was running as a normal package. When I use the very same with a rootless coturn container it simply does not work. After seeing the error message about the prometheus, I thought that it could be the reason. But from your answer I get the feeling that prometheus is an optional dependency.

**Comment by taurhine** [comment]
I've just tried with the tag 4.6, I get no error message and coturn works as expected as a rootless container, thanks for fixing it!

**Comment by kamrapooja** [comment]
> ust tried with the tag 4.6, I g

from where to get tag 4.6. I am not able to find it
