### ISSUE TITLE
how alternate-server  works?

### ISSUE THREAD

**Issue by notedit** [coturn/coturn#88]
i know there is alternate-server options.  

when i have three alternate-servers,  how and when  the master server  will  redirect to the  alternate-server

**Comment by misi** [comment]
@notedit 
AFAIU it sends round robin the request to Alternative servers. 

See https://github.com/coturn/coturn/blob/c8313ac68dd9f8114fb50e380c07460f340f9cc5/src/server/ns_turn_server.c#L3483-L3519

And see the https://github.com/coturn/coturn/tree/c8313ac68dd9f8114fb50e380c07460f340f9cc5/examples/scripts/loadbalance

**Comment by misi** [comment]
I hope I answered your question..

**Comment by notedit** [comment]
@misi  wow,  thanks.  it is question two years ago.  :)

**Comment by notedit** [comment]
Another question,  i see 
```
built-in 300 ALTERNATE-SERVER mechanism (requires 300 response support by the TURN client);
```
Does webrtc support this?

**Comment by misi** [comment]
@notedit  I just strarted to updated and address all issues.
I 
I found alternate server test in webrtc native so I assuming it should work, but I do not tested it. 
And be aware that Mozilla use different STUN/TURN stack: https://github.com/resiprocate/nICEr

So in webrtc native I found tests:
https://github.com/pristineio/webrtc-mirror/blob/7a5bcdffaab90a05bc1146b2b1ea71c004e54d71/webrtc/p2p/base/turnport_unittest.cc

Please close the issue if there no other question..

**Comment by notedit** [comment]
thanks

**Comment by rasos** [comment]
Do I understand right: as soon as I have set one ALTERNATE-SERVER,  coturn ALWAYS redirects and will not handle Stun/TURN requests by itself anymore.  

In fact I would prefer that coturn is redirecting to ALTERNATE-SERVER only if it reaches a certain load. But I can't find any such setting.

https://github.com/coturn/coturn/blob/master/examples/etc/turnserver.conf 

```
# Option to set the "redirection" mode. The value of this option
# will be the address of the alternate server for UDP & TCP service in the form of
# <ip>[:<port>]. The server will send this value in the attribute
# ALTERNATE-SERVER, with error 300, on ALLOCATE request, to the client.
# Client will receive only values with the same address family
# as the client network endpoint address family.
# See RFC 5389 and RFC 5766 for the description of ALTERNATE-SERVER functionality.
# The client must use the obtained value for subsequent TURN communications.
# If more than one --alternate-server option is provided, then the functionality
# can be more accurately described as "load-balancing" than a mere "redirection".
# If the port number is omitted, then the default port
# number 3478 for the UDP/TCP protocols will be used.
# Colon (:) characters in IPv6 addresses may conflict with the syntax of
# the option. To alleviate this conflict, literal IPv6 addresses are enclosed
# in square brackets in such resource identifiers, for example:
# [2001:db8:85a3:8d3:1319:8a2e:370:7348]:3478 .
# Multiple alternate servers can be set. They will be used in the
# round-robin manner. All servers in the pool are considered of equal weight and
# the load will be distributed equally. For example, if you have 4 alternate servers,
# then each server will receive 25% of ALLOCATE requests. A alternate TURN server
# address can be used more than one time with the alternate-server option, so this
# can emulate "weighting" of the servers.
#
# Examples:
#alternate-server=1.2.3.4:5678
#alternate-server=11.22.33.44:56789
#alternate-server=5.6.7.8
#alternate-server=[2001:db8:85a3:8d3:1319:8a2e:370:7348]:3478

# Option to set alternative server for TLS & DTLS services in form of
# <ip>:<port>. If the port number is omitted, then the default port
# number 5349 for the TLS/DTLS protocols will be used. See the previous
# option for the functionality description.
#
# Examples:
#tls-alternate-server=1.2.3.4:5678
#tls-alternate-server=11.22.33.44:56789
#tls-alternate-server=[2001:db8:85a3:8d3:1319:8a2e:370:7348]:3478
```

**Comment by kesshei** [comment]
I also need answers.
