### ISSUE TITLE
Help override turnserver.conf

### ISSUE THREAD

**Issue by filoucrackeur** [coturn/coturn#883]
Greetings,

I would like to know how is it possible to overwrite ```/etc/coturn/turnserver.conf``` without modify file himself.

did something like conf.d/* is possible ?

best regards

**Comment by ggarber** [comment]
you can pass most of the configuration settings in the command line to override the values in turnserver.conf.  Is that enough for you?
https://github.com/coturn/coturn/wiki/turnserver
