### ISSUE TITLE
Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478

### ISSUE THREAD

**Issue by malhotraguy** [coturn/coturn#884]
Hi I am trying to deploy the Coturn-4.5.1.1 on Amazon EC2 instance t2.micro. 
And for my instance I have opened all the traffic , just for testing .
But getting this error while starting turnserver: `"Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478"`

**Comment by malhotraguy** [comment]
My Configuration file :- 
[turnserver.conf.txt](https://github.com/coturn/coturn/files/7953061/turnserver.conf.txt)

**Comment by malhotraguy** [comment]
Log file output:-
0: log file opened: /var/log/turn_2575_2022-01-27.log
0: 10240 bytes per second allowed per session

**Comment by malhotraguy** [comment]
systemctl status coturn
● coturn.service - coTURN STUN/TURN Server
     Loaded: loaded (/lib/systemd/system/coturn.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-01-27 18:11:44 UTC; 39min ago
       Docs: man:coturn(1)
             man:turnadmin(1)
             man:turnserver(1)
    Process: 2525 ExecStart=/usr/bin/turnserver --daemon -c /etc/turnserver.conf --pidfile /run/turnserver/turnserver.pid (code=exited, status=0/SUCCESS)
    Process: 2527 ExecStartPost=/bin/sleep 2 (code=exited, status=0/SUCCESS)
   Main PID: 2526 (turnserver)
      Tasks: 7 (limit: 1147)
     Memory: 5.6M
     CGroup: /system.slice/coturn.service
             └─2526 /usr/bin/turnserver --daemon -c /etc/turnserver.conf --pidfile /run/turnserver/turnserver.pid

Jan 27 18:11:42 ip-172-31-25-5 turnserver[2526]: 0: IPv4. TCP listener opened on : 127.0.0.1:3478
Jan 27 18:11:42 ip-172-31-25-5 turnserver[2526]: 0: IPv4. SCTP listener opened on : 172.31.25.5:3478
Jan 27 18:11:42 ip-172-31-25-5 turnserver[2526]: 0: IPv4. TCP listener opened on : 172.31.25.5:3478
Jan 27 18:11:42 ip-172-31-25-5 turnserver[2526]: 0: IPv6. SCTP listener opened on : ::1:3478
Jan 27 18:11:42 ip-172-31-25-5 turnserver[2526]: 0: IPv6. TCP listener opened on : ::1:3478
Jan 27 18:11:42 ip-172-31-25-5 turnserver[2526]: 0: IO method (admin thread): epoll (with changelist)
Jan 27 18:11:42 ip-172-31-25-5 turnserver[2526]: 0: IO method (auth thread): epoll (with changelist)
Jan 27 18:11:42 ip-172-31-25-5 turnserver[2526]: 0: IO method (auth thread): epoll (with changelist)
Jan 27 18:11:42 ip-172-31-25-5 turnserver[2526]: 0: SQLite DB connection success: /var/lib/turn/turndb
Jan 27 18:11:44 ip-172-31-25-5 systemd[1]: Started coTURN STUN/TURN Server.

**Comment by malhotraguy** [comment]
**Output of turnserver -o**  :- 
0: log file opened: /var/log/turn_2981_2022-01-27.log
0: 10240 bytes per second allowed per session
0: Config file found: /etc/turnserver.conf
0: 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.1.1 'dan Eider'
0: 
Max number of open files/sockets allowed for this process: 1048576
0: 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
0: 

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: DTLS 1.2 supported
0: TURN/STUN ALPN supported
0: Third-party authorization (oAuth) supported
0: GCM (AEAD) supported
0: OpenSSL compile-time version: OpenSSL 1.1.1f  31 Mar 2020 (0x1010106f)
0: 
0: SQLite supported, default database location is /var/lib/turn/turndb
0: Redis supported
0: PostgreSQL supported
0: MySQL supported
0: MongoDB is not supported
0: 
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: Domain name: 
0: Default realm: 
0: 
CONFIG: WARNING: --server-relay: NON-STANDARD AND DANGEROUS OPTION.
0: ERROR: 
CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
0: NO EXPLICIT LISTENER ADDRESS(ES) ARE CONFIGURED
0: ===========Discovering listener addresses: =========
0: Listener address to use: 127.0.0.1
0: Listener address to use: 172.31.25.5
0: Listener address to use: ::1
0: =====================================================
0: Total: 1 'real' addresses discovered
0: =====================================================
0: NO EXPLICIT RELAY ADDRESS(ES) ARE CONFIGURED
0: ===========Discovering relay addresses: =============
0: Relay address to use: 172.31.25.5
0: Relay address to use: ::1
0: =====================================================
0: Total: 2 relay addresses discovered
0: =====================================================

**Comment by malhotraguy** [comment]
**Output of  `turnserver` :-** 
0: log file opened: /var/log/turn_3009_2022-01-27.log
0: 10240 bytes per second allowed per session
0: Config file found: /etc/turnserver.conf
0: 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.1.1 'dan Eider'
0: 
Max number of open files/sockets allowed for this process: 1048576
0: 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
0: 

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: DTLS 1.2 supported
0: TURN/STUN ALPN supported
0: Third-party authorization (oAuth) supported
0: GCM (AEAD) supported
0: OpenSSL compile-time version: OpenSSL 1.1.1f  31 Mar 2020 (0x1010106f)
0: 
0: SQLite supported, default database location is /var/lib/turn/turndb
0: Redis supported
0: PostgreSQL supported
0: MySQL supported
0: MongoDB is not supported
0: 
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: Domain name: 
0: Default realm: 
0: 
CONFIG: WARNING: --server-relay: NON-STANDARD AND DANGEROUS OPTION.
0: ERROR: 
CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
0: NO EXPLICIT LISTENER ADDRESS(ES) ARE CONFIGURED
0: ===========Discovering listener addresses: =========
0: Listener address to use: 127.0.0.1
0: Listener address to use: 172.31.25.5
0: Listener address to use: ::1
0: =====================================================
0: Total: 1 'real' addresses discovered
0: =====================================================
0: NO EXPLICIT RELAY ADDRESS(ES) ARE CONFIGURED
0: ===========Discovering relay addresses: =============
0: Relay address to use: 172.31.25.5
0: Relay address to use: ::1
0: =====================================================
0: Total: 2 relay addresses discovered
0: =====================================================
0: pid file created: /var/run/turnserver.pid
0: IO method (main listener thread): epoll (with changelist)
0: WARNING: I cannot support STUN CHANGE_REQUEST functionality because only one IP address is provided
0: Wait for relay ports initialization...
0:   relay 172.31.25.5 initialization...
0:   relay 172.31.25.5 initialization done
0:   relay ::1 initialization...
0:   relay ::1 initialization done
0: Relay ports initialization done
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=1 created
bind: Address already in use
0: Trying to bind fd 12 to <127.0.0.1:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:3478, again...
0: IO method (general relay thread): epoll (with changelist)
0: IPv4. UDP listener opened on: 127.0.0.1:3478
0: IPv4. UDP listener opened on: 172.31.25.5:3478
0: IPv6. UDP listener opened on: ::1:3478
0: Total General servers: 2
0: turn server id=0 created
bind: Address already in use
0: Trying to bind fd 23 to <127.0.0.1:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:3478, again...
0: IO method (admin thread): epoll (with changelist)
0: IO method (auth thread): epoll (with changelist)
0: IO method (auth thread): epoll (with changelist)
0: SQLite DB connection success: /var/lib/turn/turndb
bind: Address already in use
0: Trying to bind fd 12 to <127.0.0.1:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:3478, again...
bind: Address already in use
0: Trying to bind fd 23 to <127.0.0.1:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:3478, again...
bind: Address already in use
0: Trying to bind fd 12 to <127.0.0.1:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:3478, again...
bind: Address already in use
0: Trying to bind fd 23 to <127.0.0.1:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:3478, again...

**Comment by ggarber** [comment]
According to those logs it says: 
`Cannot bind local socket to addr: Address already in use`

Check you don't have any process already listening in that port (for example other instance of coturn running in background).

You can use this command to find if something else is listening in port 3478: `netstat -ltnp | grep 3478`

**Comment by Nirmeen23** [comment]
I got this output, what does this mean and what should i do?
tcp        0      0 172.31.38.165:3478      0.0.0.0:*               LISTEN      8041/turnserver     
tcp        0      0 172.31.38.165:3478      0.0.0.0:*               LISTEN      8041/turnserver     
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      8041/turnserver     
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      8041/turnserver     
tcp6       0      0 ::1:3478                :::*                    LISTEN      8041/turnserver     
tcp6       0      0 ::1:3478                :::*                    LISTEN      8041/turnserver
