### ISSUE TITLE
REST API users never expire

### ISSUE THREAD

**Issue by Karmahero** [coturn/coturn#888]
After setting up coturn, everything is working including generating REST API users with this configuration:

fingerprint

listening-ip=0.0.0.0
use-auth-secret
static-auth-secret=XXXXXXXXXXXXXXXXXXXX

and browser iceServer request with:

const iceServers = [
{
    urls: 'turn:turn.server.com:5349',
    username: '1644736502:test',
    credential: 'vxFSIqcAsiScl67IBxOd+LMh5PQ='
}];

The problem with this approach though appears to be that once this username/credential is published to the user, it never expires from being able to directly access the TURN server  and can just be copied and reused. These dynamically created users also don't exist in any database so it appears that once published the only way to revoke access would be to change the "static-auth-secret".

Is there some additional setting or configuration that would allow the REST API process to force coturn to expire the user? If not, I can always dynamically inject and remove long term users, but I'd rather not unless that is the only viable way to secure the TURN server (that needs to be publicly available).

**Comment by vitorf7** [comment]
@Karmahero have you found a solution to this? I am currently facing a slightly similar issue, although I cannot seem to even get it to authenticate correctly at the moment.
