### ISSUE TITLE
CPU at 100%

### ISSUE THREAD

**Issue by dnish** [coturn/coturn#89]
I'm having an issue with Coturn on Ubuntu 16.04. Suddenly, the CPU goes up to 100% and stays there. The webserver (http://myturn.app.com) stops serving the "TURNSERVER page".

If I type in <code>nload</code>, there is no network load shown which means the TURN server isn't used. It seems like it's crashing after a while.

![bildschirmfoto 2016-12-31 um 11 59 15](https://cloud.githubusercontent.com/assets/7636313/21577149/cfad00f2-cf50-11e6-935b-7832bc45e727.png)

**Comment by mom040267** [comment]
that may be a problem related to the recent OpenSSL migration on
Debian-based platform. Double-check that your binary package has the same
compile-time and runtime OpenSSL versions, or re-compile Coturn yourself.

Oleg

**Comment by dnish** [comment]
I'm using the official Ubuntu repo, so my Coturn package is still on 4.5.0.3

**Comment by mom040267** [comment]
Check which OpenSSL version you have.

**Comment by dnish** [comment]
I've upgraded the local version for my user to 1.1.10

<code>
openssl version
OpenSSL 1.1.0  25 Aug 2016
</code>

System is using:

<code>
/usr/bin/openssl version
OpenSSL 1.0.2g  1 Mar 2016
</code>

**Comment by mom040267** [comment]
That can be the problem. I'd advise to have a single OpenSSL version per
system. Otherwise, the setup may be fragile.

Also, are you sure that your Coturn binaries were compiled for the OpenSSL
version that the Coturn is actually using when running ? It is dynamically
linked.

Oleg

**Comment by dnish** [comment]
We've used a single SSL version before, I've just installed 1.1.0 to check if it solves the CoTurn issue, but server is still crashing. So OpenSSL 1.0.2g  1 Mar 2016 was the version when we've installed CoTurn via apt-get.

**Comment by mom040267** [comment]
Then i recommend getting the latest code from the project page and recompiling yourself.

**Comment by dnish** [comment]
@mom040267 Just using the latest version on a fresh installed Debian server, turnserver is killing my CPU and seems crashed (I can't access it from outside):

      %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                                    
       652.8  0.3 150384:43 turnserver 

On this server, I've disabled TLS within turnserver.conf.

**Comment by mom040267** [comment]
Even without TLS, the TURN server is using the OpenSSL libraries a lot.

My advise is to recompile the TURN server yourself on the system that you
are using. Debian world is transitioning to the new OpenSSL version with
uncertain results.

Oleg
