### ISSUE TITLE
 ERROR: Cannot open PostgreSQL DB connection

### ISSUE THREAD

**Issue by chauhan19911** [coturn/coturn#902]
Hi,
While connecting to the external PostgreSQL database, installed in my Windows 11 machine, through docker I'm getting this error:
`ERROR: Cannot open PostgreSQL DB connection: <host=192.168.31.173>, runtime error`

I'm using this command :
`docker run -d -p 3478:3478 -p 3478:3478/udp -p 5349:5349 -p 5349:5349/udp -p 49160-49200:49160-49200/udp coturn/coturn -n --log-file=stdout --external-ip='$(detect-external-ip)' --min-port=49160 --max-port=49200 -e, --psql-userdb="host=192.168.31.173 port=5432 dbname=webrtc connect_timeout=10"`

In C:\Program Files\PostgreSQL\14\data\pg_hba.conf, I have give permission to my IP:
`host 	all 			all 			192.168.31.173/16  		trust`

**Comment by ggarber** [comment]
Doesn't look like a coturn issue.  Can you get into the docker container and try to connect to the PG server from there?

```docker exec -it CONTAINER_ID /bin/bash```

And then you can do a telnet to test basic connectivity or a psql cli.
