### ISSUE TITLE
STUN response does not take into account the RESPONSE-ADDRESS (0x0002) field backwards compatibility with RFC 3489

### ISSUE THREAD

**Issue by emathioudakis** [coturn/coturn#903]
[wireshark.zip](https://github.com/coturn/coturn/files/8581980/wireshark.zip)
In attached wireshark using filter classicstun.id == 8e:4f:96:bb:56:8b:22:af:5d:30:bd:be:35:96:5b:26 , it can identify that client (10.0.200.164) is using the RESPONSE-ADDRESS field in the Binding Request but STUN server ignores the port that client is requesting for the reply and reply to port 5060 where it has received the UDP packet
![stun](https://user-images.githubusercontent.com/97613354/165736271-9810b7fd-68e4-4305-82d0-74a5833981ae.jpg)

Thank you in advance,

**Comment by ggarber** [comment]
The support for that legacy mode (RESPONSE-ADDRESS) has been disabled by default in the latest version of coturn: https://github.com/coturn/coturn/blob/master/examples/etc/turnserver.conf#L782

It can be enabled if needed.    Can you test if that's the case and close this issue ?  Thank you!

**Comment by emathioudakis** [comment]
I will test it. I am closing the issue.
