### ISSUE TITLE
Does coturn help with clients in networks where only TLS on port 443 is allowed out? 

### ISSUE THREAD

**Issue by dinosmm** [coturn/coturn#904]
Apologies if this is not the right place to ask, I wasn't sure where else to ask this.

From what I gather, some people advise running coturn on 443, to enable clients in restrictive networks, who are only allowed outbound connections on 443, to use VoIP. 
However, I also understand the actual streams have to go to different ports other than 443. This means that restrictive network clients won't be able to send and receive audio/video streams even if they can set up a call with a coturn server on 443.

Is this correct? And if so, is there any other reason why running coturn on 443 might be better than the default ports?

**Comment by danir-de** [comment]
That's not correct - the same things happen when you open a web page.

Your browser queries the webserver at the destination port 443, the webserver then has to send a response back to you. 
For obvious reasons you don't have a firewall opening at port 443 yourself - the webserver actually sends his data back to a random source port on your client, let's say 34732.

In case random ports are not blocked by your clients firewall, which they most likely are not, connections should go through.

Please close.
