### ISSUE TITLE
Coturn segfault ubuntu 18.04 

### ISSUE THREAD

**Issue by mriosfer** [coturn/coturn#909]
Hi ,

Coturn continue doing random kernel segfaults:
turnserver kernel: [69790.888375] turnserver[1218]: segfault at 7f1e380008d0 ip 00007f1e380008d0 sp 00007f1e469fe8d8 error 15

OS: Ubuntu 18.04 LTS
Kernel: 4.15.0-177-generic
Version Coturn-4.5.0.7 'dan Eider'

Did anyone solve the problem?

**Comment by SebastianLuebke** [comment]
Upgrade your distro to 20.04. Solved the problem for multiple people i know

**Comment by ggarber** [comment]
Thx a lot for the answer @SebastianLuebke .  Closing this ticket as there hasn't been any further comment from @mriosfer in some months.
