### ISSUE TITLE
AWS Turn Server Not Connecting

### ISSUE THREAD

**Issue by vinodmap** [coturn/coturn#91]
Hello, I have launched an instance of AWS Turn Server (AMI ami-b7b613d7, README at http://turnserver.open-sys.org/downloads/v4.5.0.5/turnserver-4.5.0.5-amazon-aws-ec2-x86_64.txt).  I am following the instructions at the link above, but am having difficulty getting this up and running correctly.  I am using the following link to test whether the turn server is running correctly: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/.  However, I enter the below info and it does not connect successfully.  

![image](https://cloud.githubusercontent.com/assets/24858762/21675305/3dbd4a96-d2e6-11e6-8d56-6899ca7c12b3.png)

On the server itself, I have specified the following config info in turnserver.conf (note, the 35.166.198.72 is the Public IP address of the instance that is provided by AWS):

> listening-port=3478
> external-ip=35.166.198.72
> user=ninefingers:youhavetoberealistic
> 

Note, once I have this working, I will be changing the user and password (obviously).

I have then done a netstat on the machine, and here is the output:

> [ec2-user@ip-172-31-21-221 etc]$ sudo netstat -nlp | grep 3478
> tcp        0      0 172.31.21.221:3478          0.0.0.0:*                   LISTEN      1785/turnserver
> tcp        0      0 127.0.0.1:3478              0.0.0.0:*                   LISTEN      1785/turnserver
> tcp        0      0 ::1:3478                    :::*                        LISTEN      1785/turnserver
> udp        0      0 172.31.21.221:3478          0.0.0.0:*                               1785/turnserver
> udp        0      0 172.31.21.221:3478          0.0.0.0:*                               1785/turnserver
> udp        0      0 127.0.0.1:3478              0.0.0.0:*                               1785/turnserver
> udp        0      0 127.0.0.1:3478              0.0.0.0:*                               1785/turnserver
> udp        0      0 ::1:3478                    :::*                                    1785/turnserver
> udp        0      0 ::1:3478                    :::*                                    1785/turnserver

Note, I don't know why the netstat has an IP address of 172.31.21.221, while the Public IP given by AWS is 35.166.198.72.  Not sure if this is causing the problem, but I also ran the trickle-ice test using the 172.31.21.221 address and it had the same result.

Then I opened port 3478 using iptables on INPUT, FORWARD, and OUTPUT.  Here is the resulting iptables after opening the ports.  

>  sudo iptables -L
> Chain INPUT (policy ACCEPT)
> target     prot opt source               destination
> ACCEPT     udp  --  anywhere             anywhere             udp dpt:stun
> ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:stun flags:FIN,SYN,RST,ACK/SYN
> ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:stun
> 
> Chain FORWARD (policy ACCEPT)
> target     prot opt source               destination
> ACCEPT     udp  --  anywhere             anywhere             udp dpt:stun
> ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:stun flags:FIN,SYN,RST,ACK/SYN
> ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:stun
> 
> Chain OUTPUT (policy ACCEPT)
> target     prot opt source               destination
> ACCEPT     udp  --  anywhere             anywhere             udp dpt:stun
> ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:stun flags:FIN,SYN,RST,ACK/SYN
> ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:stun
> 

I then did a "service iptables save" and then rebooted the instance from the AWS console.  I also did a "/etc/rc.d/init.d/coturn stop" and then subsequently a start.  Note, I also tested that when I do a stop, and then display the netstat on port 3478, there are no entries when it is stopped, but when I start it, there are the entries as listed above stating listen on port 3478.

Is there anything wrong with the settings I have above?  Also, is there anything else I can do to get this working or provide any other debug info?  Any help you can provide would be most helpful.  Thanks.

V

**Comment by itsalltoomuch** [comment]
Hi. I got sample problem few days ago.
Trying to modify your URI as:

> turn:35.166.x.x:3478?transport=tcp

It worked for me :)

**Comment by naz-mul** [comment]
anyone got this to work?

**Comment by felipecsl** [comment]
I got this to work by creating an inbound rule in the instance security group for port 3478 TCP and UDP.

**Comment by imrizwan89** [comment]
I am not able to access my turn server over https, however it works fine on http
http://live.talkrecruit.com:3478  --is working
https://live.talkrecruit.com:3478  -- is not working

**Comment by felipecsl** [comment]
i got the trickle-ice page to see it, but streaming via the turn server still wont work for me

**Comment by imrizwan89** [comment]
@felipecsl is turn server over https working for you?

**Comment by felipecsl** [comment]
If you are referring to the web admin interface, then yes

**Comment by vinodmap** [comment]
I previously got this to work; the issue was relating to the ports opened in AWS.  My interface currently works.

**Comment by felipecsl** [comment]
@vinodmap mind sharing more details? Did you have to set up 2 Public ips? Did you use it with webrtc?

**Comment by vinodmap** [comment]
I am using it with webrtc and am basically just specifying the turn server parameters in the configuration for the webrtc at each point they are connecting from.  I only have the one public IP for the AWS Turn server, which I point to from each client that wants to make a connection.

**Comment by Mahes-P** [comment]
Hi All,

I am able to setup turnserver using AWS Public IP,but when try to assign ELB for this AWS instance turnserver testing fails.
I used https://test.webrtc.org/ for testing, while using AWS ELB. There i see response as below:
UDP enabled  ------------X
TCP enable---------------Y

Relay Connectivity-------X
Reflexive connectivity----X
Host Connectivity --------Y

When i use AWS public IP, test resource is good, as below:

UDP enabled  -------------Y
TCP enable----------------Y

Relay Connectivity--------Y
Reflexive connectivity-----Y
Host Connectivity --------Y

So, my test is failing through AWS ELB. I think its because UDP is not allowed on AWS ELB.
Is my understanding correct?
Is there anybody else facing same issue?

Kindly Advise.

Thanks.

**Comment by RTKSoftware** [comment]
Same problem on EC Ubuntu 16.04. Coturn listen local ip and ignore public IP.
 --external-ip IP/localIP - exists

**Comment by Mahes-P** [comment]
I was able to resolve it myself. 

In your case, is this AWS ec2 PUBLIC ip or do you mean AWS ELB as public ip??

**Comment by vinodmap** [comment]
Did you do the same for both Inbound and Outbound on your AWS EC2 instance?  On my AWS EC2, for inbound, my turn server (which works) opens port 3478 for both TCP and UDP.  For my outbound, the instance allows all ports.

**Comment by Mahes-P** [comment]
Can you please share your turnserver.conf file content.

External IP should be public IP of ec2 instance, and internal IP should be private IP of ec2 instance.

Also in security group you need to allow both TCP and UDP on 3478(turn server port).

You can try to access turn server using browser as http://<public-ip>:3478. This is a simple test of installation, but not stun/turn actual test.

**Comment by misi** [comment]
My guess is that as you wrote You  use in --external-ip parameter the external/internal IP
Use instead of of both only your's external IP Address!

**Comment by abhinanth** [comment]
Hi i am trying to setup a turn server in aws by launching turn-server ami if i try to connect to connect the webrtc application iam getting this error
IPv4. tcp or tls connected to: 122.xxx.xxx.xxx:14603
17: session 000000000000000001: user <>: incoming packet message processed, error 401: Unauthorised
17: IPv4. tcp or tls connected to: 122.xxx.xxx.xxx:14604
17: session 000000000000000001: user <>: incoming packet message processed, error 401: Unauthorised
17: check_stun_auth: Cannot find credentials of user <test2>
17: session 000000000000000001: user <test2>: incoming packet message processed, error 401: Unauthorised
17: check_stun_auth: Cannot find credentials of user <test2>
17: session 000000000000000001: user <test2>: incoming packet message processed, error 401: Unauthorised
21: session 000000000000000001: TCP socket closed remotely 122.xxx.xxx.xxx:14603
21: session 000000000000000001: closed (2nd stage), user <test2>, local 172.31.29.7:80, remote 122.166.247.129:14603, reason: TCP connection closed by client (callback)

this is my config file
listening-port=80
tls-listening-port=443
external-ip=52.xx.xx.xx/172.31.29.7
lt-cred-mech
user=tes2:test123
userdb=/etc/turnuserdb.conf
realm=our-domain
log-file=/var/tmp/turn.log
mobility

can you please help me to sort out this issue

**Comment by misi** [comment]
@abhinanth 
1.
According the logs Your credential is not valid..
Your webrtc application may using REST? What application do you use?
2.
I don't think that mobility is used in your app so if I were you, I would skip this config option.

**Comment by abhinanth** [comment]
Hi
Thanks for the replay 
We are using bigbluebutton server. For bypassing the firewall in UAE we are trying to implement turn server.

**Comment by zerefati** [comment]
@imrizwan89, Did you managed to use it over HTTPS?

**Comment by stavros-zavrakas** [comment]
@Mahes-P can you guide through a bit with the coturn configuration behind a load balancer. Now it seems that the turn server works if I hit the instance directly but it doesn't work when I hit the load balancer. Below you can see some of the configuration and some logs:

https://serverfault.com/questions/938965/coturn-server-behind-aws-application-load-balancer

**Comment by RamyaAshika** [comment]
Hi I'm also facing the same problem.I'm using peerjs. Can anyone please sort out this? @misi @abhinanth

**Comment by dingdongnigetou** [comment]
> My guess is that as you wrote You use in --external-ip parameter the external/internal IP
> Use instead of of both only your's external IP Address!

Awesome, that saves my day!

**Comment by jbouse** [comment]
Curious if people are still having issues using an AWS LB as this ticket is over 4 years old... AWS NLB (Network Load Balancer) does support TCP_UDP listeners over IPv4 only at this point. NLB also supports PROXY PROTOCOL v1 and v2 which should be able to provide the necessary connectivity. With PROXY PROTOCOL on an NLB using TCP_UDP listener the daemon on the server should be receiving the client's source IP and it just simply passes through the NLB to the target server behind it. 

The NLB should not be confused with ALB (Application Load Balancer) which only supports HTTP/HTTPS.

**Comment by boyundefeated** [comment]
Hi, I always got error 403: Forbidden IP, please help me out
My server config;
> listening-port=3478
tls-listening-port=5349
external-ip=18.118.x.x
realm=user
Verbose

My server log:
> 9: : udp_server_input_handler:628:start
9: : open_client_connection_session:4713:start
9: : read_client_connection:4497:start
9: : read_client_connection: data.buffer=0x7f5be80040ac, data.len=60
9: : IPv4. Local relay addr: 172.31.5.67:53096
9: : IPv4. Local reserved relay addr: 172.31.5.67:53097
9: : session 001000000000000001: new, realm=<user>, username=<>, lifetime=777
9: : session 001000000000000001: realm <user> user <>: incoming packet ALLOCATE processed, success
9: : write_client_connection:4281:start
9: : write_client_connection: prepare to write to s 0x7f5be80140b0
9: : write_client_connection:4304:end
9: : read_client_connection:4603:end
9: : open_client_connection_session:4747:end
9: : udp_server_input_handler:666:end
9: : udp_server_input_handler:628:start
9: : read_client_connection:4497:start
9: : read_client_connection: data.buffer=0x7f5be80040ac, data.len=36
9: : session 001000000000000001: refreshed, realm=<user>, username=<>, lifetime=777
9: : session 001000000000000001: realm <user> user <>: incoming packet REFRESH processed, success
9: : write_client_connection:4281:start
9: : write_client_connection: prepare to write to s 0x7f5be80140b0
9: : write_client_connection:4304:end
9: : read_client_connection:4603:end
9: : udp_server_input_handler:666:end
9: : timer_event_handler: timeout 0x55a7ec114f30: rtcp_map_timeout_handler
9: : timer_event_handler: timeout 0x55a7ec114860: timer_handler
9: : udp_server_input_handler:628:start
9: : open_client_connection_session:4713:start
9: : read_client_connection:4497:start
9: : read_client_connection: data.buffer=0x7f5bf00040ac, data.len=56
9: : IPv4. Local relay addr (RTCP): 172.31.5.67:53097
9: : session 000000000000000001: new, realm=<user>, username=<>, lifetime=777
9: : session 000000000000000001: realm <user> user <>: incoming packet ALLOCATE processed, success
9: : write_client_connection:4281:start
9: : write_client_connection: prepare to write to s 0x7f5bf00140b0
9: : write_client_connection:4304:end
9: : read_client_connection:4603:end
9: : open_client_connection_session:4747:end
9: : udp_server_input_handler:666:end
9: : timer_event_handler: timeout 0x7f5bf00036e0: timer_timeout_handler
9: : timer_event_handler: timeout 0x7f5bf0002490: timer_handler
10: : timer_event_handler: timeout 0x7f5be80036e0: timer_timeout_handler
10: : timer_event_handler: timeout 0x7f5be8002490: timer_handler
10: : timer_event_handler: timeout 0x7f5bd8002630: timer_handler
10: : udp_server_input_handler:628:start
10: : read_client_connection:4497:start
10: : read_client_connection: data.buffer=0x7f5bf00040ac, data.len=36
10: : session 000000000000000001: refreshed, realm=<user>, username=<>, lifetime=777
10: : session 000000000000000001: realm <user> user <>: incoming packet REFRESH processed, success
10: : write_client_connection:4281:start
10: : write_client_connection: prepare to write to s 0x7f5bf00140b0
10: : write_client_connection:4304:end
10: : read_client_connection:4603:end
10: : udp_server_input_handler:666:end
10: : udp_server_input_handler:628:start
10: : open_client_connection_session:4713:start
10: : read_client_connection:4497:start
10: : read_client_connection: data.buffer=0x7f5bf00040ac, data.len=60
10: : IPv4. Local relay addr: 172.31.5.67:56640
10: : IPv4. Local reserved relay addr: 172.31.5.67:56641
10: : session 000000000000000002: new, realm=<user>, username=<>, lifetime=777
10: : session 000000000000000002: realm <user> user <>: incoming packet ALLOCATE processed, success
10: : write_client_connection:4281:start
10: : write_client_connection: prepare to write to s 0x7f5bf00290c0
10: : write_client_connection:4304:end
10: : read_client_connection:4603:end
10: : open_client_connection_session:4747:end
10: : udp_server_input_handler:666:end
10: : udp_server_input_handler:628:start
10: : read_client_connection:4497:start
10: : read_client_connection: data.buffer=0x7f5bf00040ac, data.len=36
10: : session 000000000000000002: refreshed, realm=<user>, username=<>, lifetime=777
10: : session 000000000000000002: realm <user> user <>: incoming packet REFRESH processed, success
10: : write_client_connection:4281:start
10: : write_client_connection: prepare to write to s 0x7f5bf00290c0
10: : write_client_connection:4304:end
10: : read_client_connection:4603:end
10: : udp_server_input_handler:666:end
10: : timer_event_handler: timeout 0x55a7ec114860: timer_handler
10: : timer_event_handler: timeout 0x7f5bf00036e0: timer_timeout_handler
10: : timer_event_handler: timeout 0x7f5bf0002490: timer_handler
11: : timer_event_handler: timeout 0x7f5be80036e0: timer_timeout_handler
11: : timer_event_handler: timeout 0x7f5be8002490: timer_handler
11: : timer_event_handler: timeout 0x7f5bd8002630: timer_handler
11: : udp_server_input_handler:628:start
11: : read_client_connection:4497:start
11: : read_client_connection: data.buffer=0x7f5bf00040ac, data.len=48
11: : handle_turn_channel_bind:2583:start
11: : handle_turn_channel_bind:2749:end
11: : session 000000000000000001: realm <user> user <>: incoming packet CHANNEL_BIND processed, error 403: Forbidden IP
11: : session 000000000000000001: realm <user> user <>: incoming packet message processed, error 403: Forbidden IP
11: : write_client_connection:4281:start
11: : write_client_connection: prepare to write to s 0x7f5bf00140b0
11: : write_client_connection:4304:end
11: : read_client_connection:4603:end
11: : udp_server_input_handler:666:end

I already opened all ports
![image](https://user-images.githubusercontent.com/17901098/137383653-cede06a2-75e0-4f51-ae44-3330f7d1f65e.png)

My test:
>  ➜  ~ turnutils_uclient -p 3478 18.118.x. x 
0: channel bind: error 403 (Forbidden IP)

**Comment by eakraly** [comment]
Hi @boyundefeated ,
Were you able to figure it out?

**Comment by eakraly** [comment]
Closing the issue
Please open new issue if the problem persists
