### ISSUE TITLE
(Potential) Feature Request: publish public address of local VPC server to external endpoint

### ISSUE THREAD

**Issue by saidmasoud** [coturn/coturn#92]
Hello,

In my AWS VPC, I have a PBX server inside the same VPC as my STUN server. Because I want to limit the external access of my PBX server as much as possible, I want to be able to connect the PBX and STUN server using their local addresses. However, when I currently attempt this, STUN will publish the local address of the PBX server to the endpoint, which will obviously fail because the endpoint does not have the PBX server in its local network. To get around this, I must open port 3478 on my PBX server to the open internet, and communicate with the STUN server via the open internet as well. Is it possible to configure this with the current version of turnserver? If not, I would like to request this feature for a future release.

**Comment by saidmasoud** [comment]
Disregard, wrong turn server :)

**Comment by saidmasoud** [comment]
Sorry I'm confusing myself, this is the right project :)

My apologies

**Comment by eakraly** [comment]
@saidmasoud were you able to address the issue?

**Comment by saidmasoud** [comment]
Unfortunately I haven't worked with STUN for a few years now. I don't think I was able to resolve this issue at that time.

**Comment by eakraly** [comment]
Thank you for your reply
Since you do not need it anymore (and no watchers here) I'm closing the issue
