### ISSUE TITLE
CGNAT Traversal Supported? 

### ISSUE THREAD

**Issue by Shreyas-R** [coturn/coturn#923]
Going through the repo, I found that this server requires external public IP address (either static or dynamic) to work. Can we get it working with a server behind a CGNAT, having access to only private IP address of a local NAT? Can we get it working with tunneling systems like Cloudflare tunnel or VPC? I'm trying to achieve this but couldn't find much information in this repo and the internet.

**Comment by ggarber** [comment]
TURN uses UDP and TCP while those tunneling systems (at least Cloudflare) only supports TCP as far as I know.   So even if it would be a good idea (that I think is not) it won't work for UDP that is the recommended way to use TURN as much as possible.

What is your use case?  

If it is for local testing it is ok to have TURN with a private IP if the endpoints using it are in the same private network (or it is reachable).
If it is for some other type of testing get a super cheap GCP instance and run your TURN server there.
