### ISSUE TITLE
Build 4.5.2-r11 from source with openssl1.1.1q failure because some methods referred by the source code are deprecated  in openssl 1.1.1

### ISSUE THREAD

**Issue by weiliu1005** [coturn/coturn#924]
We try to build 4.5.2-r11 from source code, but failed because some of the openssl method used in 4.5.2-r11 are deprecated in openssl  version 1.1.1 now, for example, in the fiile of src\apps\relay\mainrelay.c, line#3219-3255, it uses following method 
TLSv1_1_server_method()
TLSv1_2_server_method()
DTLSv1_2_server_method()
DTLSv1_server_method()

While those methods are deprecated in openssl version 1.1.1 according to the document https://www.openssl.org/docs/man1.1.1/man3/TLSv1_1_method.html

And also in the openssl/ssl.h, they are defined as deprecated, so when compile 4.5.2-r11 with openssl 1.1.1q, the build is failed

# ifndef OPENSSL_NO_TLS1_1_METHOD
DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_method(void)) /* TLSv1.1 */
DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_server_method(void))
DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_client_method(void))
# endif

# ifndef OPENSSL_NO_TLS1_2_METHOD
DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_method(void)) /* TLSv1.2 */
DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void))
DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_client_method(void))
# endif

# ifndef OPENSSL_NO_DTLS1_METHOD
DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_method(void)) /* DTLSv1.0 */
DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_server_method(void))
DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_client_method(void))
# endif

should the CoTURN code be changed to  replaced these method by TLS_method(), TLS_server_method(), TLS_client_method() DTLS_method(), DTLS_server_method(), DTLS_client_method() etc?

**Comment by ggarber** [comment]
> should the CoTURN code be changed to replaced these method by TLS_method(), TLS_server_method(), TLS_client_method() DTLS_method(), DTLS_server_method(), DTLS_client_method() etc?

Probably.  Are you willing to submit a patch?

**Comment by eakraly** [comment]
Will be addressed within the context of #989 and #996
