### ISSUE TITLE
Binding Request as Connectivity Check

### ISSUE THREAD

**Issue by Cybermilitia** [coturn/coturn#930]
I try to expand (or make bigger) the binding requests which is used for connectivity check by adding a big realm attribute. Because, I need to test a network issue on my network. Anyway, when I tried to observe my bigger binding request, I saw no response from the coturn. Beside, I'm not able to see any log about it. No clue. 

After eliminating potential network possibilities, and after being sure that the coturn received my binding requests, I tried to put a lot of trace in server, client and relay sections of coturn code to observe and understand my binding request's destiny. However I didn't find any clue about it. Looks like the coturn devours my bigger binding requests without any trace. 

I'm pretty sure that I use XOR-RELAYED-ADDRESS in Allocate Success Response as connectivity check target. In any case, when I tried to send the binding request without realm, everything was OK.

Besides, as far as I understand from RFCs, a binding request can transport a realm attribute. So, looks like there is no obstacle against my bigger binding requests with realm. 

So, do you have any idea about my observation? I mean, how can I see the code flow when I try to send my bigger binding requests? Any idea?

**Comment by ggarber** [comment]
Thank you for the report!

Can you try to send that request to Google's stun server to see how it behaves? f.e. sending it to `stun.l.google.com:19302`

Did you put a log inside coturn to log all the messages received and you didn't see your message?    Can you send a wireshark capture from the coturn server when it receives your message?

**Comment by Cybermilitia** [comment]
You can see the response from stun.l.google.com:19302. I sent the package by using this command: 
echo -n -e "\x00\x01\x00\x94\blablabla" | nc -u stun.l.google.com 19302

Looks like everything is OK:

<img width="1715" alt="Screen Shot 2022-07-28 at 14 05 54" src="https://user-images.githubusercontent.com/12972305/181495138-735f020e-961d-4a7f-bd4b-141207188a56.png">

However, when I try to send the same or similar messages to my coturn (not default 3478 port but XOR-RELAYED-ADDRESS' port on 104th row), it ends up with this:

<img width="1678" alt="Screen Shot 2022-07-28 at 14 34 37" src="https://user-images.githubusercontent.com/12972305/181495684-5ca62adf-f0a8-4fcd-bb5f-c775bf080c6c.png">

So, I didn't any response against my expanded binding request as you can see.

Debug level is "Verbose", so I think I can see all logs- normal and custom logs. Frankly, if I can see and understand the code flow (handlers or hooks etc.) via trace, looks like it will be go well.

**Comment by Cybermilitia** [comment]
When we inspected all packages, we've noticed that Coturn transfers all kind of Binding Requests properly. It looks like the missing response's reason is the B clients side. I'll try to handle the client side problem with them. So I think we can close this one.
