### ISSUE TITLE
Provider detects a lot of port scans in private IP range

### ISSUE THREAD

**Issue by dnish** [coturn/coturn#932]
Hey,
I'm getting several messages from my server provider that a port scan was detected and we have to stop it. All IPs where within the private ip range.

After some research I found some code for the config and added the following lines:

```
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
# Other IPv4 Special-Purpose addresses
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=192.0.0.0-192.0.0.255
denied-peer-ip=192.0.2.0-192.0.2.255
denied-peer-ip=198.18.0.0-198.19.255.255
denied-peer-ip=198.51.100.0-198.51.100.255
denied-peer-ip=203.0.113.0-203.0.113.255
# IPv6 Unique-Local
denied-peer-ip=fc00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
# IPv6 Link-Local Unicast
denied-peer-ip=fe80::-febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff
# Other IPv6 Special-Purpose assignments
denied-peer-ip=::ffff:0:0-::ffff:ffff:ffff
denied-peer-ip=64:ff9b::-64:ff9b::ffff:ffff
denied-peer-ip=64:ff9b:1::-64:ff9b:1:ffff:ffff:ffff:ffff:ffff
denied-peer-ip=2001::-2001:1ff:ffff:ffff:ffff:ffff:ffff:ffff
denied-peer-ip=2001:db8::-2001:db8:ffff:ffff:ffff:ffff:ffff:ffff
denied-peer-ip=2002::-2002:ffff:ffff:ffff:ffff:ffff:ffff:ffff
```

After saving the configuration, I get the following logs from coturn:

```
Jul 29 16:31:23 Ubuntu-2004-focal-64-minimal turnserver[2648]: 304: A peer IP 192.168.1.112 denied in the range: 192.168.0.0-192.168.255.255
Jul 29 16:31:23 Ubuntu-2004-focal-64-minimal turnserver[2648]: 305: A peer IP 192.168.2.100 denied in the range: 192.168.0.0-192.168.255.255
Jul 29 16:31:23 Ubuntu-2004-focal-64-minimal turnserver[2648]: 305: A peer IP 10.30.114.179 denied in the range: 10.0.0.0-10.255.255.255
Jul 29 16:31:23 Ubuntu-2004-focal-64-minimal turnserver[2648]: 305: A peer IP 10.0.0.12 denied in the range: 10.0.0.0-10.255.255.255
Jul 29 16:31:24 Ubuntu-2004-focal-64-minimal turnserver[2648]: 306: A peer IP 10.0.0.57 denied in the range: 10.0.0.0-10.255.255.255
Jul 29 16:31:24 Ubuntu-2004-focal-64-minimal turnserver[2648]: 306: A peer IP 10.201.117.130 denied in the range: 10.0.0.0-10.255.255.255
Jul 29 16:31:24 Ubuntu-2004-focal-64-minimal turnserver[2648]: 306: A peer IP 10.201.117.130 denied in the range: 10.0.0.0-10.255.255.255
Jul 29 16:31:24 Ubuntu-2004-focal-64-minimal turnserver[2648]: 306: A peer IP 10.0.0.57 denied in the range: 10.0.0.0-10.255.255.255
Jul 29 16:31:25 Ubuntu-2004-focal-64-minimal turnserver[2648]: 307: A peer IP 192.168.178.23 denied in the range: 192.168.0.0-192.168.255.255
Jul 29 16:31:25 Ubuntu-2004-focal-64-minimal turnserver[2648]: 307: A peer IP 192.168.178.23 denied in the range: 192.168.0.0-192.168.255.255
```

Now my question is, if this causes some issues for users who get connected to our TURN server or if I could simply ignore this message?

**Comment by fippo** [comment]
This is not a port scan and your provider is misclassifying this. ICE is attempting to create a pair between the relay port opened on the server and the local IP address of the peer. This is unlikely to work.

Blocking those ranges (as suggested [by this great post](https://www.rtcsec.com/article/slack-webrtc-turn-compromise-and-bug-bounty/) should work but you might want to monitor P2P connectivity establishment rates in your app before and after to verify this.

**Comment by dnish** [comment]
Ah I understand. So the client tells the server that he can be reached under this private IP, but the connection will not work because the IP isn't public. Is there any single configuration option where I can tell the TURN server that he is only accessible to the public and can ignore all private IPs?

**Comment by ggarber** [comment]
Not a single option afaict but the `denied-peer-ip` option you were using looks like a reasonable workaround to me.

**Comment by ggarber** [comment]
Closing this question, let me know if my latest answer is not helping or you need something else.
