### ISSUE TITLE
Stun on CoTurn doesnt work

### ISSUE THREAD

**Issue by LilToaster69** [coturn/coturn#933]
Hi, I'm trying to configure CoTurn on a Debian 11 Server and Stun doesn't work.

My Config: 
`realm=coturn.darkly.biz
fingerprint
listening-ip=0.0.0.0
external-ip=37.114.40.239 #or just the external ip
listening-port=3478
#min-port=10000
#max-port=20000
#log-file=/var/log/turnserver.log
verbose

static-auth-secret=my secret`

**Comment by ggarber** [comment]
What is exactly what you are testing and it is not working?   What type of client, what is the failure...?

**Comment by LilToaster69** [comment]
I need a turn server for matrix synapse and test the settings with https://test.voip.librepush.net/ and mostly I get a "poor" result because Stun doesn't work.

**Comment by LilToaster69** [comment]
I changed the authentication for coturn and now it works just fine

here my new config:
`realm=turn.darkly.biz
#fingerprint
listening-ip=0.0.0.0
external-ip=3.120.249.185
listening-port=3478
tls-listening-port=5349
#min-port=10000
#max-port=20000
#log-file=/var/log/turnserver.log
verbose

#static-auth-secret=secret

# Specify the user for the TURN authentification
user=turnuser:secret

# Enable long-term credential mechanism
lt-cred-mech

cert=/etc/letsencrypt/live/turn.darkly.biz/fullchain.pem
pkey=/etc/letsencrypt/live/turn.darkly.biz/privkey.pem
`

Thank you for your help
