### ISSUE TITLE
No video stream on some connections

### ISSUE THREAD

**Issue by dnish** [coturn/coturn#941]
Hey,
I'm having a strange issue when using coTURN as a relay. I'm forcing each connection to use TURN by enabling <code>iceTransportPolicy: "relay"</code> within my Javascript code. After that I try to establish connections between my 2 clients (Chrome on Mac and Safari on iOS). This works most of the time, but sometimes there is a strange error: Chrome receives a stream, but only the audio one. The video is black and empty. On Safari everything is working perfect, I get the audio and video tracks from Chrome. The <code>chrome://webrtc-internals/</code> shows that there were no video packets received (everything is zero). If I do a camera switch on Safari (renegotiation), Chrome also starts receiving a video stream. When I disable the relay, I don't get this error. There are no errors shown within my Javascript code or on syslog. Has anyone an idea what could cause this issue? We are using version 4.5.2.

```

Statistics RTCMediaStreamTrack_receiver_8
--
timestamp | 15.8.2022, 21:26:39
trackIdentifier | 45c3c810-1ad7-42da-884c-1ddcf74352b5
remoteSource | true
ended | false
detached | false
kind | video
jitterBufferDelay | 0
[jitterBufferDelay/jitterBufferEmittedCount_in_ms] | 0
jitterBufferEmittedCount | 0
framesReceived | 0
[framesReceived/s] | 0
[framesReceived-framesDecoded-framesDropped] | 0
framesDecoded | 0
framesDropped | 0
freezeCount* | 0
pauseCount* | 0
totalFreezesDuration* | 0
totalPausesDuration* | 0
totalFramesDuration* | 0
sumOfSquaredFramesDuration* | 0
```

**Comment by ggarber** [comment]
Are you using a single PeerConnection with BUNDLE enabled for audio and video?   
Can you share the whole webrtc-internals dump?

**Comment by ggarber** [comment]
Please reopen if you can provide more information or need more help.

**Comment by FunkyYang** [comment]
yes I meet this problem
