### ISSUE TITLE
Suggestions to change default PR merge and PR subject line settings

### ISSUE THREAD

**Issue by eakraly** [coturn/coturn#947]
Today coturn/coturn uses default settings of GitHub repo which is
- Pull Requests - Allow merge commits
- Use Default message

This settings control how the PRs are merged and how the merge commits are named/described:
- PR is merged with all the commits so the history of commits shows up in master, including the branch used for PR.
- PR name only contains 
```
"Merge pull request #NNN from contributor/branch_name" (First line of commit message so shows up as Subject)
"Original Subject of the PR"
```

Example https://github.com/coturn/coturn/commit/4de2d530ff6e53fa12852261a4c5c2819d18ac82

I see downsides to this approach and suggest slightly different setup:
- Use "Allow squash merging" only which creates linear history (original PR branch is not stored and whole PR appears as a single commit)
- "Default to pull request title and description" this will copy the original title and description from PR - making sure the PR commit has all the original information from PR.

Benefits I see:

1. Linear history - it is rare that intermediate commits from PR are of interest to community. History "is cleaner"

2. Git commits have full description that the original author of PR wrote - in this case the whole description can be see using git cli or any other git tool (including local). PRs are GitHub unique construct so needs extra navigation to get to the original description and explanations of commit (which is not available while browsing code locally or running blame locally). In those cases having all commits named "Merge pull request #NNN from contributor/branch_name" is very unhelpful.

This question is to document the discussion and decision.

**Comment by ggarber** [comment]
I very much prefer the new proposed approach.   So unless somebody or @misi has anything against it I will enable it.
