### ISSUE TITLE
encrypt password for mysql example?

### ISSUE THREAD

**Issue by hongkongkiwi** [coturn/coturn#964]
Could somebody share an example using openssl of how to encrypt the mysql password? I couldn't find it anywhere in the docs. Perhaps @misi could help since he did the change a few years ago.

It appears to use aes-128-ctr looking at the code, but I just couldn't quite get it to work.

**Comment by hongkongkiwi** [comment]
So far I've tried this, with or without salt, but just can't get it right:
```
IV="00000000000000000000000000000000"
KEY="ca25cb230366173ab09bc84c6ef649d6"
openssl enc -aes-128-ctr -K $KEY -iv $IV -in passfile | openssl base64
```

**Comment by ggarber** [comment]
The turnadmin has a -P command to generate a password.  Did you try that?

From the README:

```
turnadmin - a TURN relay administration tool.

  SYNOPSIS

$ turnadmin [command] [options]

$ turnadmin [ -h | --help]

  DESCRIPTION

Commands:

-P, --generate-encrypted-password	Generate and print to the standard
output an encrypted form of a password (for web admin user or CLI).
The value then can be used as a safe key for the password
storage on disk or in the database. Every invocation for the same password
produces a different result. The format of the encrypted password is:
$5$<...salt...>$<...sha256(salt+password)...>. Salt is 16 characters,
the sha256 output is 64 characters. Character 5 is the algorithm id (sha256).
Only sha256 is supported as the hash function.
```

(I'm not familiar with this part of the code but happy to try to help you figure it out)

**Comment by ggarber** [comment]
DId this help @hongkongkiwi  or did you find any other solution?

**Comment by eakraly** [comment]
Unless the issue is still there - please comment. TY!
