### ISSUE TITLE
coturn stun configuration works in firefox but fails in chrome 

### ISSUE THREAD

**Issue by RavikumarTulugu** [coturn/coturn#969]
I am testing the webrtc sample application 
[https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/](url)

The application works fine on firefox with out any issue but on chrome it throws following icecandidate error. Any special setting needs to be enabled to work with chrome  ?

url: stun:www.xyz.com:3478
address: 0.0.0.x
port: 59201
host_candidate: 0.0.0.x:59201
error_text: STUN binding request timed out.
error_code: 701

chrome error logs : 
Note: errors from onicecandidateerror above are not neccessarily fatal. For example an IPv6 DNS lookup may fail but relay candidates can still be gathered via IPv4.
The server stun:www.playme.one:3478 returned an error with code=701:
STUN binding request timed out.
The server stun:www.playme.one:3478 returned an error with code=701:
STUN binding request timed out.

Please advise. 
Thanks & regards,

**Comment by RavikumarTulugu** [comment]
I am using below config

listening-device=enp1s0
listening-port=3478
listening-ip=1.2.3.4
listening-ip=2001::95c2
no-udp
no-tls
no-dtls
no-tcp-relay
stun-only
no-rfc5780
no-stun-backward-compatibility
response-origin-only-with-rfc5780

**Comment by RavikumarTulugu** [comment]
I tested this on edge browser and the configuration works fine. it may not be a coturn but a chrome issue.

**Comment by ggarber** [comment]
Do you have the coturn server running in `stun:www.playme.one:3478` still?  I cannot access neither with Chrome or Firefox.

I think it could be the "no-udp" setting you are using.  Can you try removing that to allow udp?

**Comment by RavikumarTulugu** [comment]
Can you pls try now ?? I removed no-udp now , but no change.

**Comment by RavikumarTulugu** [comment]
I analyzed the traffic on tshark i can see only bind request arriving but no bind response going out.

**Comment by RavikumarTulugu** [comment]
on firefox the webrtc samples i have the following output for my coturn server 

![image](https://user-images.githubusercontent.com/2748005/188632887-524537f0-53c1-497e-9a01-f161385eacd7.png)

on chrome the webrtc samples i have the following output clearly some thing is wrong. 

![Screenshot Capture - 2022-09-06 - 17-54-14](https://user-images.githubusercontent.com/2748005/188634525-df561d0b-9cc6-4a8c-8ce3-728323479009.png)

**Comment by RavikumarTulugu** [comment]
I have opened 3479 along with 3478 , now i can see the srflx candidate but still ice says disconnected. I am not seeing the binding request timed out any more.

**Comment by ggarber** [comment]
If you are getting `srflx` candidates as I can see in the latest screenshot that means that the browser is able to use STUN with your coturn instance properly.

3479 shouldn't be needed for this (only 3478).  Perhaps when you did that change something else changed too?

Regarding "still ice says disconnected" what is the app you are using and what is the whole scenario?   If your clients are behind a NAT you may need also TURN and not only STUN.

**Comment by RavikumarTulugu** [comment]
More update, i have one host and a VM ,  the chrome in VM shows ( "Binding request timed out ") , the VM is not behind NAT it is using a bridged network. I have verified the connectivity ( udp & tcp ) using netcat and it works. ok i will remove "stun-only" and see whether it solves. but i dont have 2 public ip addresses which are needed for TURN.

**Comment by RavikumarTulugu** [comment]
This turned out to be a operating system / vm network issue. after recreating the vm , every thing started working like magic. 
Thanks for taking a look. i am still clueless on why it started working suddenly.
