### ISSUE TITLE
netstat shows too many results

### ISSUE THREAD

**Issue by tipoc123** [coturn/coturn#97]
When I run 'netstat' command for the turnserver, results are repeated, showing the same IP/port combinations multiple times:
```
# netstat -lptn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
...
tcp        0      0 [my ip]:3478    0.0.0.0:*               LISTEN      13872/turnserver
tcp        0      0 [my ip]:3478    0.0.0.0:*               LISTEN      13872/turnserver
tcp        0      0 [my ip]:3478    0.0.0.0:*               LISTEN      13872/turnserver
tcp        0      0 [my ip]:3478    0.0.0.0:*               LISTEN      13872/turnserver
tcp        0      0 [my ip]:3478    0.0.0.0:*               LISTEN      13872/turnserver
tcp        0      0 [my ip]:3478    0.0.0.0:*               LISTEN      13872/turnserver
tcp        0      0 [my ip]:3478    0.0.0.0:*               LISTEN      13872/turnserver
tcp        0      0 [my ip]:3478    0.0.0.0:*               LISTEN      13872/turnserver
tcp        0      0 [my ip]:3478    0.0.0.0:*               LISTEN      13872/turnserver
tcp        0      0 [my ip]:3478    0.0.0.0:*               LISTEN      13872/turnserver
(and much more)
...
```

How do I fix it?

OS Ubuntu 16.04.1 LTS
Version Coturn-4.5.0.3 'dan Eider' (installed through apt)

**Comment by mom040267** [comment]
Those results are correct legitimate results. There are multiple sockets
listening on the same IP/port combination. You do not have to fix anything.

Oleg

**Comment by tipoc123** [comment]
OK, but in previous versions of coturn netstat shows only two connections. It keeps me confused.

For example:
```
admin@localhost:~$ sudo netstat -lptn | grep turn
tcp        0      0 127.0.0.1:5766          0.0.0.0:*               LISTEN      5990/turnserver 
tcp        0      0 [my ip]:3478    0.0.0.0:*               LISTEN      5990/turnserver 
```
Why so much difference?

OS Ubuntu 12.04.5 LTS
Version Coturn-4.4.5.3 'Ardee West' (installed from sources)

**Comment by mom040267** [comment]
It depends on the system (Linux, FreeBSD, etc) and on the kernel version.
It automatically adjusts to the optimal configuration for your system.
Ubuntu 12 and Ubuntu 16 have different kernel versions with different
capabilities, so Coturn uses different setup for them.
