### ISSUE TITLE
Reminder for oss-fuzz integration.

### ISSUE THREAD

**Issue by 0x34d** [coturn/coturn#979]
Hello coturn team,
I hope you all are doing well, I wanna remind you like a bot (I'm not a bot).
I really wanna hear your thoughts on integration in ```oss-fuzz``` https://github.com/google/oss-fuzz/pull/8239.
I have created some fuzzing harnesses for coturn.
```oss-fuzz``` do fuzzing to find interesting ```memory-corruption-related``` bugs.

**Comment by ggarber** [comment]
Hi bot :)

Sounds like a very good idea.   Can you share your fuzzing in a PR?

Thank you very much

**Comment by 0x34d** [comment]
PR in coturn Repo https://github.com/coturn/coturn/pull/982 .

The point here is if anyone fuzz this project at the local level, 
they usually cannot scale at the level of oss-fuzz infrastructure.
