### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NasserAlmanji** [coturn/coturn#98]
Hi there,

---------------------------------------------------------------------
Terminal Output ->
---------------------------------------------------------------------
Max number of open files/sockets allowed for this process: 4096
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 2000 (approximately)
---------------------------------------------------------------------

Does the Turn Session indicate the number of concurrent calls is limited to 2000?
Why id different from 4096

Kind regards,
Nasser

**Comment by mom040267** [comment]
On Wed, Jan 25, 2017 at 8:46 PM, Nasser <notifications@github.com> wrote:

> Hi there,
> ------------------------------
> Terminal Output -> Max number of open files/sockets allowed for this
> process: 4096
> Due to the open files/sockets limitation,
> max supported number of TURN Sessions possible is: 2000 (approximately)
>
> Does the Turn Session indicate the number of concurrent calls is limited
> to 2000?
>
Yes, roughly.

Why id different from 4096
>
Because more than one socket may be involved into a session.

**Comment by NasserAlmanji** [comment]
Ok, Thank you @mom040267 for your answer
