### ISSUE TITLE
Sources for rpm builds

### ISSUE THREAD

**Issue by mathieu-aubin** [coturn/coturn#99]
Follow-up from #93 

As per spec file pattern, src files with current version (4.5.0.6) are not available at given location:

[http://turnserver.open-sys.org/downloads/v%{version}/%{name}-%{version}.tar.gz](http://turnserver.open-sys.org/downloads/v4.5.0.6/turnserver-4.5.0.6.tar.gz)

**Comment by mom040267** [comment]
that's because that version has not been officially released yet, the
"current" version is 4.5.0.5

Oleg

**Comment by mathieu-aubin** [comment]
I see.. Wouldn't it make sense to create a dev branch for the 'updated' build stuff while a release isn't official? I run 4 c7 machines running 4.5.0.6 without complains (thanks!) - Oh, maybe a bit of barking here and there, blame it on my pkg building skills...

Thx again
