### ISSUE TITLE
[Question] How to install coturn on RHEL 8 AWS EC2 instance

### ISSUE THREAD

**Issue by Govind10g** [coturn/coturn#992]
Hi All,

I m trying to install coturn on RHEL 8 as RHEL 8 is approved server in my project.
However after running command yum install coturn not getting installed on server.

```
[root@ip-XX-XX-XX-XX ec2-user]# sudo yum install coturn
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Last metadata expiration check: 0:00:21 ago on Wed Sep 21 03:57:14 2022.
No match for argument: coturn
```

Please help me on this.

**Comment by Govind10g** [comment]
@misi  @ggarber  - Any idea on this issue ? :)

**Comment by robert-scheck** [comment]
I'm the RPM package maintainer of coturn in EPEL. However, coturn is not in RHEL, but in EPEL - a high-quality but third party community repository driven by the Fedora Project.

1. `sudo dnf install -y epel-release`
2. `sudo dnf install -y coturn`

If step 2 does not succeed, you need to add a valid RHEL subscription to your instance using `subscription-manager register`.
