### ISSUE TITLE
[BUG]Logs are not generating on specified location in turnserver.conf 

### ISSUE THREAD

**Issue by Govind10g** [coturn/coturn#993]
Hi Team,

my coturn server is stop writing logs on specified file declared in turnserver.conf
Earlier I was able to see the log on syslog and I also created a separate file location to write the logs but that is not working.

Below is my configuration of tunrserver.conf
```
# Log file path

log-file=/var/log/turnserver/turnserver1.log
# Enable verbose logging
verbose

# Option to redirect all log output into system log (syslog)
syslog  
```

Currently I m not able to get any logs in the above two specified location. i.e. syslog and log-file=/var/log/turnserver/turnserver1.log
Please suggest and help on this blocker.
@misi  @ggarber

**Comment by ggarber** [comment]
when did it stop working?
do you get any error in the stdout/stderr when starting turnserver?
can you make sure you you are not running out of disk space and the user running the turnserver process has permissions to write in /var/log/turnserver/turnserver1.log?

**Comment by Govind10g** [comment]
@ggarber 
I did a fresh installation of coturn in RHEL 8 EC2 instance and below is my setup details :-

1. Coturn is running as a coturn user.

```
[root@ip-xyz log]# ps -aef | grep -i coturn
coturn     24058       1  0 10:11 ?        00:00:00 /usr/bin/turnserver -o -c /etc/coturn/turnserver.conf --pidfile /run/coturn/turnserver.pid
root       24115   23893  0 10:20 pts/0    00:00:00 grep --color=auto -i coturn
[root@ip-xyz log]#
```

2. Config file details :

```
# Log file path
log-file=/var/log/coturn/turnserverCoturn.log
# Enable verbose logging
verbose
# Option to redirect all log output into system log (syslog)
messages
```

I tried with both syslog as well as messages. As i m using RHEL hence we have messages instead of syslog.


3. Folder permission details 

`drwxrwxrwx. 2 coturn coturn     45 Sep 23 10:11 coturn`

4. Details of coturn.service file 

```
[Service]
User=coturn
Group=coturn
Type=forking
PIDFile=/run/coturn/turnserver.pid
ExecStart=/usr/bin/turnserver -o -c /etc/coturn/turnserver.conf --pidfile /run/coturn/turnserver.pid
Restart=on-abort
ExecReload=/bin/kill -HUP $MAINPID
AmbientCapabilities=CAP_NET_BIND_SERVICE
```

With all above config I can see the log file is generated under coturn folder as below 
```
[root@ip-xyz coturn]# pwd
/var/log/coturn
[root@ip-xyz coturn]# ll
total 4
-rwxrwxrwx. 1 coturn coturn 3756 Sep 23 10:11 turnserverCoturn_2022-09-23.log
```

**I can see this file turnserverCoturn_2022-09-23.log and it has coturn stop and start log but when I m placing a call between two user , I won't be able to get any transaction log of network.** 

Please help me on this issue because of this we are not able to debug coturn issue.

**Comment by Govind10g** [comment]
@ggarber @misi @tony2001 @byronclark 
Hello, Can anyone help me on this issue. It is blocking me to solve networking issues.

**Comment by Govind10g** [comment]
@ggarber 

Below is the startup logs coturn server, I can see it started fine. But still logs are not coming in log file.

```
root@ip-xyz :/var/log# systemctl status coturn
● coturn.service - coTURN STUN/TURN Server
     Loaded: loaded (/lib/systemd/system/coturn.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-09-26 11:22:21 UTC; 11s ago
       Docs: man:coturn(1)
             man:turnadmin(1)
             man:turnserver(1)
    Process: 28005 ExecStart=/usr/bin/turnserver --daemon -c /etc/turnserver.conf --pidfile /run/turnserver/turnserver.pid (code=exited, status=0/SUCCESS)
    Process: 28007 ExecStartPost=/bin/sleep 2 (code=exited, status=0/SUCCESS)
   Main PID: 28006 (turnserver)
      Tasks: 7 (limit: 9401)
     Memory: 3.9M
     CGroup: /system.slice/coturn.service
             └─28006 /usr/bin/turnserver --daemon -c /etc/turnserver.conf --pidfile /run/turnserver/turnserver.pid

Sep 26 11:22:19 ip-xyz turnserver[28006]: 0: IPv4. TLS/SCTP listener opened on : 10.41.15.158:443
Sep 26 11:22:19 ip-xyz turnserver[28006]: 0: IPv4. TLS/TCP listener opened on : 10.41.15.158:443
Sep 26 11:22:19 ip-xyz turnserver[28006]: 0: IPv4. DTLS/UDP listener opened on: 10.41.15.158:3478
Sep 26 11:22:19 ip-xyz turnserver[28006]: 0: IPv4. DTLS/UDP listener opened on: 10.41.15.158:443
Sep 26 11:22:19 ip-xyz turnserver[28006]: 0: Total General servers: 2
Sep 26 11:22:19 ip-xyz turnserver[28006]: 0: IO method (admin thread): epoll (with changelist)
Sep 26 11:22:19 ip-xyz turnserver[28006]: 0: IO method (auth thread): epoll (with changelist)
Sep 26 11:22:19 ip-xyz turnserver[28006]: 0: IO method (auth thread): epoll (with changelist)
Sep 26 11:22:19 ip-xyz turnserver[28006]: 0: SQLite DB connection success: /var/lib/turn/turndb
Sep 26 11:22:21 ip-xyz systemd[1]: Started coTURN STUN/TURN Server.
root@ip-xyz:/var/log#
```

**Comment by eakraly** [comment]
Hi @Govind10g ! What version are you running?
Are you enabling syslog (it is not very clear from your description)?

**Comment by Govind10g** [comment]
@eakraly  I tried both version Version Coturn-4.5.1.1 'dan Eider' as well as 4.5.2 on AWS EC2 instance.
facing same issue on version.

**Comment by Puvendhan** [comment]
Its same issue with in Ubuntu 20.4 version. Logs are not getting generated. It would be good if someone can suggest on this.?

Is it the issue with coturn version?

**Comment by eakraly** [comment]
@Govind10g @Puvendhan thank you for input

Any chance you can run latest 4.6.0 - there are multiple log related bug fixes in it. And it is easier for us to understand an issue while referencing latest version.

Also, it is possible that there is no log (as in no log lines printed because turnserver has nothing to log) - can you please test a connection to the server using turnutils_uclient?

**Comment by Govind10g** [comment]
@eakraly 
Thank you so much for your input. 
With the help of latest version, we can see the logs in coturn generated log file. 
**But When we enabled TLS i.e. 443 then in that case it is not generating the logs** 
however we are getting logs when we used 3478 port. 

Any idea on this issue ??

**Comment by eakraly** [comment]
Are you sure the app is able to connect and use TURN with 443?
Or you are not getting ANY log at all (even the start lines)?

**Comment by Govind10g** [comment]
@eakraly - Yes I'm sure that app is connecting through TURN 443.
Because the network load balancer which we are using is pointing to EC2 server on which coturn is running. 
We enable TLS on NLB and also provisioned private certificate in coturn for enabling TLS.


As per the Load balancer log, I can see the TLS connection details of network flow.

I m getting health check logs in log file but not getting call transaction logs.

**Comment by ggarber** [comment]
Just tested it and it works fine for me.
Check the only process listening in 443 is coturn in that machine.
Try ssh'ing into the EC2 instance and doing a "telnet 10.41.15.158 443".  That generates a log in coturn if you are running it in verbose mode.

**Comment by Govind10g** [comment]
@ggarber @eakraly 
Thank you so much for the input, while debugging into this issue we found that we are using whiteListed IPs in the security group of EC2 instance and when we use 0.0.0.0/0 instead of whitelisted IPs, logs are started populating in log file.


**@ggarber @eakraly One more question - we found that our coturn application is not working if we are making a call from Firefox to android and vice-versa. 
however android to edge and vice versa is working with the same configuration.** 

Is there any issue with Firefox ? we are using firefox version 91.12.

**Comment by eakraly** [comment]
Hi @Govind10g 
Since the original issue has been addressed I suggest we close this one and open a new one for Firefox issue (if still relevant)
This will help other developers in future references (not to mix different problems in one issue).
