### ISSUE TITLE
Container goes into CrashLoopBackOff in a kubernetes cluster  

### ISSUE THREAD

**Issue by jattind** [coturn/coturn#994]
This is my first time deploying the coturn container in a kubernetes cluster. I was able to deploy and run an old container from 
instrumentisto/coturn, but wanted to move to an officially supported one.

The coturn container is going into a crashloop. I don't see any errors besides the following:
```
kubectl logs coturn-app-coturn-d7545fddc-zwqhc -n coturn

/usr/local/bin/docker-entrypoint.sh: line 8: /usr/bin/turnserver: Operation not permitted
/usr/local/bin/docker-entrypoint.sh: line 8: /usr/bin/turnserver: Success
```

I deployed it as a docker container on another machine to see what's in the docker-entrypoint.sh and I see less than 8 lines:
```
cat docker-entrypoint.sh 
#!/bin/bash

# If command starts with an option, prepend it with a `turnserver` binary.
if [ "${1:0:1}" == '-' ]; then
  set -- turnserver "$@"
fi

exec $(eval "echo $@")
```

Any help or pointers on how to debug and get this container running would be appreciated. Thanks in advance.

**Comment by ggarber** [comment]
Hi @jattind , Can you provide more information on coturn docker image you use, parameters passed when running it and what k8s spec you use to launch it?  I can try to reproduce it and help.

**Comment by jattind** [comment]
I used the following docker image: 4.6.0-r0
Also I used the helm charts available here, except when deploying the container I modified the repository location from instrumentisto/coturn to coturn/coturn. I have tried passing different parameters from their values, but all seem to result in container going into crashloop, whereas theirs works and I was able to get video calls working.GitHub - iits-consulting/coturn-chart: Coturn Helm Chart to provide a STUN/TURN Server inside Kubernetes

Here are the parameters I changing in their Helm values:use-auth-secretstatic-auth-secret=northfingerprinttotal-quota=0bps-capacity=0stale-nonceno-multicast-peers
repository: coturn/coturntag: 4.6.0-r0tls-listening-port=443
Remove:    lt-cred-mech
I have already created a TLS issuer and secret secret
certificate:  enabled: true  host: <my-doamin>  issuerName: ca-issuer  secret: ca-key-pair
I am in the process of creating Kubernetes spec., instead of using their Helm, which I hope can help me to debug the issue further.
Jattin

    On Saturday, September 24, 2022 at 01:14:21 AM PDT, Gustavo Garcia ***@***.***> wrote:  
 
 


Hi @jattind , Can you provide more information on coturn docker image you use, parameters passed when running it and what k8s spec you use to launch it? I can try to reproduce it and help.

**Comment by eakraly** [comment]
Hi @jattind 
I see 2 important points to pay attention to:
1. That helm chart runs turnserver behind LB - which means it fully proxies all the connections
2. Containers runs without privilege to use privileged port range whereas you want it to use 443
```
securityContext:
            capabilities:
              drop:
                - ALL
```
I think bullet 2 could be a reason to why turnserver crashes (not a good thing I agree - should log at least)

Can you please remove requirement to use 443 and try again?

**Comment by jattind** [comment]
I removed the following but see the same issue.
tls-listening-port=443

I also tried changing the config from a secret to a regular ConfigMap, but see the same issue. Lastly I removed all the config, so that it would run with what ever the defaults are, but still see the same issue.

I have converted the helm to bunch of Kubernetes specs so it's easier to understand and debug. Here is the deployment spec.
`# Source: coturn/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coturn
  namespace: coturn
  labels:
    app.kubernetes.io/name: "coturn"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: coturn
      app.kubernetes.io/instance: coturn
  template:
    metadata:
      annotations:
        # re-roll deployment on config change
        checksum/coturn-config: '{{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}'
      labels:
        app.kubernetes.io/name: coturn
        app.kubernetes.io/instance: coturn
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: "coturn"
          image: "coturn/coturn:4.6.0-r0"
          imagePullPolicy: IfNotPresent
          args: ["-c", "/turnserver.conf"]
          ports:
            - name: turn-udp
              containerPort: 3478
              protocol: UDP
            - name: turn-tcp
              containerPort: 3478
              protocol: TCP
            - name: turn-tcp-tls
              containerPort: 5349
              protocol: TCP
            - name: turn-udp-dtls
              containerPort: 5349
              protocol: UDP
          volumeMounts:
            - name: coturn-config
              mountPath: /turnserver.conf
              subPath: turnserver.conf
              readOnly: true
            - name: tls
              mountPath: /tls
              readOnly: true
            - name: var-tmp
              mountPath: /var/tmp
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
        - name: tls
          secret:
            secretName: turn-tls
        - name: coturn-config
          secret:
            secretName: coturn-config
        - name: var-tmp
          emptyDir: {}`

**Comment by jattind** [comment]
I continued debugging further and removed the following:
`          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false`

The cotrun pod is able to start successfully!
I will need to understand the implication of the above change, but I can make progress.

**Comment by eakraly** [comment]
Good callout - if you make filesystem read-only then turnserver cannot write any file
That includes logs and that includes turnserver.pid file

We might want to address this in code - running with read-only filesystem is a great way to increase security (and having pid file in this case is useless anyway)

**Comment by eakraly** [comment]
@jattind could please try and find which of the 3 options you removed from the `securityContext ` made it work?

**Comment by jattind** [comment]
I actually removed all 3, but I can test removing each one-at-a-time and see what causes the crash.

**Comment by jattind** [comment]
Quick question. Is it possible to have user/password as well as secret auth enabled at the same time. It seem to test the ICE servers it requires username/password whereas Nextcloud talk requires a secret for auth.

**Comment by eakraly** [comment]
OK, makes sense
You requested 443 (unlike the helm chart provides) which requires capability NET_BIND_SERVICE
Can you please try following (add NET_BIND_SERVICE) :
```
capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
```

And to confirm - `readOnlyRootFilesystem: true ` is not an issue?

**Comment by eakraly** [comment]
>Quick question. Is it possible to have user/password as well as secret auth enabled at the same time?
It seem to test the ICE servers it requires username/password whereas Nextcloud talk requires a secret for auth.

I do not think so. Quick look into code tells me that there is A credential mechanism used (one).

**Comment by eakraly** [comment]
@jattind is this issue addressed? Can we close the issue then?

**Comment by jattind** [comment]
I will give this a try tomorrow and confirm.

Jattin

**Comment by jattind** [comment]
readOnlyRootFilesystem: true is not an issue.

Also adding the NET_BIND_SERVICE solve the crash issue.
capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
You can also close this issue. Thanks for your help!
