### ISSUE TITLE
Add prometheus support to CI builds

### ISSUE THREAD

**Issue by fancycode** [coturn/coturn#998]
It would be nice if the CI would also cover building with prometheus support.

**Comment by eakraly** [comment]
That's a great suggestion @fancycode 
Any chance you can propose a PR for that?
Thanks in advance!

**Comment by ggarber** [comment]
FYI CI builds the docker images and the docker images are building coturn with prometheus support.    

But LGTM if somebody wants to spend the time adding it also to the non-docker CI jobs.
